import type { PracticalAnchor } from "./types";

export const foundationAnchors: PracticalAnchor[] = [
  {
    id: "FND-01-A01", skillId: "FND-01", kind: "recognition", sourceRefs: ["FTGU-E01"],
    assumptions: ["all-in decision", "call 1bb to win 2bb", "no future betting"],
    promptRu: "В банке 1bb, соперник ставит 1bb. Hero должен доставить 1bb, и дальше ставок не будет. Нужно ли выигрывать больше половины раздач, чтобы call был прибыльным?",
    promptEn: "Hero risks 1 unit to win 2. Must the call win more than 50% of the time to be profitable?",
    answerRu: "Нет. Hero рискует 1bb, чтобы выиграть уже лежащие в банке 2bb: pot odds 1:2, а порог безубыточности около одной трети.", answerEn: "No. The break-even threshold is about one third.",
    rationaleRu: "Сначала определи цену колла и банк, который можно выиграть. Затем переведи соотношение 1:2 в требуемую equity: около 33%.",
    rationaleEn: "FTGU-E01 explicitly shows that pot odds determine required equity and the threshold is not automatically 50%.",
  },
  {
    id: "FND-01-A02", skillId: "FND-01", kind: "changed", sourceRefs: ["FTGU-E01"],
    assumptions: ["all-in decision", "call 2bb to win 2bb", "future decisions removed"],
    promptRu: "В банке 2bb, соперник ставит 2bb. Hero должен доставить 2bb, и дальше ставок не будет. Какой новый порог безубыточности?",
    promptEn: "The call price becomes worse while villain's range is unchanged. What happens to required equity?",
    answerRu: "50%: требуемая equity выросла.", answerEn: "Required equity increases.",
    rationaleRu: "Hero вкладывает 2bb в итоговый банк 4bb, поэтому порог равен 2 / 4 = 50%. Изменилась только цена колла, и порог вырос.",
    rationaleEn: "With no future decisions, price and equity dominate; a worse price requires a larger share of the pot.",
    changedVariables: ["call_price"],
  },
  {
    id: "FND-02-A01", skillId: "FND-02", kind: "decision", sourceRefs: ["FTGU-E01", "FTGU-E05"],
    assumptions: ["meaningful stack remains", "future betting possible"],
    promptRu: "У руки заметная equity, но Hero OOP и может часто фолдить на будущих улицах. Можно ли приравнять эту equity к EV решения?",
    promptEn: "A hand has meaningful raw equity, but Hero is OOP and may fold often on future streets. Can raw equity be treated as the EV of the decision?",
    answerRu: "Нет. Нужно учитывать, сколько equity реально реализуется на будущих улицах.", answerEn: "No. Equity realization and future branches must be considered.",
    rationaleRu: "Часть номинальной equity можно потерять, когда приходится фолдить под давлением. Позиция, цена и будущие решения определяют, сколько equity дойдёт до шоудауна.",
    rationaleEn: "FTGU-E01 separates equity from EV; FTGU-E05 adds that postflop execution can make a marginal BB defend unprofitable.",
  },
  {
    id: "FND-02-A02", skillId: "FND-02", kind: "changed", sourceRefs: ["FTGU-E05"],
    assumptions: ["same hand", "same opener range", "BB closes action"],
    promptRu: "Если Hero закрывает торговлю и получает лучшую цену, что происходит с реализацией пограничной защиты?",
    promptEn: "If Hero now closes the action and gets a better price, what happens to the practical viability of a marginal defend?",
    answerRu: "Она улучшается: пограничный call становится жизнеспособнее.", answerEn: "It improves; the marginal call becomes more viable.",
    rationaleRu: "Когда никто не может сделать рейз позади, а цена ниже, нужно реализовать меньшую долю equity, чтобы call окупался.",
    rationaleEn: "FTGU-E05 identifies closing action and a small open as factors that lower the required realizable equity.",
    changedVariables: ["closing_action", "price"],
  },
  {
    id: "FND-03-A01", skillId: "FND-03", kind: "recognition", sourceRefs: ["FTGU-E01"],
    assumptions: ["small current investment", "meaningful stack remains"],
    promptRu: "Почему рука с невысоким текущим equity иногда всё же может продолжить прибыльно?",
    promptEn: "Why can a hand with low current equity sometimes continue profitably?",
    answerRu: "Из-за выгодного будущего дерева и implied odds.", answerEn: "Because of a favorable future tree and implied odds.",
    rationaleRu: "FTGU-E01 прямо связывает implied odds с потенциальной будущей отдачей относительно текущей инвестиции.",
    rationaleEn: "FTGU-E01 explicitly frames implied odds as potential future return relative to the current investment.",
  },
  {
    id: "FND-03-A02", skillId: "FND-03", kind: "boundary", sourceRefs: ["FTGU-E05"],
    assumptions: ["weak top-pair potential", "tight early-position opening range"],
    promptRu: "Почему nominally playable high-card hand хуже реализуется против tight EP range, чем против wide late-position range?",
    promptEn: "Why does a nominally playable high-card hand realize worse versus a tight EP range than versus a wide late-position range?",
    answerRu: "Растут domination и плотность сильных overpair/top-pair regions.", answerEn: "Domination and strong overpair/top-pair density increase.",
    rationaleRu: "FTGU-E05 отдельно подчёркивает top-pair domination против concentrated early-position ranges.",
    rationaleEn: "FTGU-E05 explicitly highlights top-pair domination against concentrated early-position ranges.",
  },
  {
    id: "FND-05-A01", skillId: "FND-05", kind: "recognition", sourceRefs: ["FTGU-E11"],
    assumptions: ["preflop", "no blockers removed"],
    promptRu: "Сколько стандартных preflop комбинаций у pocket pair, suited hand и offsuit hand?",
    promptEn: "How many standard preflop combinations are there for a pocket pair, suited hand and offsuit hand?",
    answerRu: "6 / 4 / 12.", answerEn: "6 / 4 / 12.",
    rationaleRu: "Это прямые стандартные combo counts из FTGU-E11.",
    rationaleEn: "These are the standard combo counts stated directly in FTGU-E11.",
  },
  {
    id: "FND-05-A02", skillId: "FND-05", kind: "changed", sourceRefs: ["FTGU-E11"],
    assumptions: ["postflop", "board or Hero cards remove suits/ranks"],
    promptRu: "После выхода новой board card можно ли продолжать использовать исходное preflop число combos без пересчёта?",
    promptEn: "After a new board card arrives, can you keep using the original preflop combo count without recalculating?",
    answerRu: "Нет. Board и hole cards удаляют combos и могут менять их роль.", answerEn: "No. Board and hole cards remove combos and can change their role.",
    rationaleRu: "FTGU-E11 требует пересчитывать диапазон после board/action changes.",
    rationaleEn: "FTGU-E11 requires recounting as board cards and action change the surviving range.",
    changedVariables: ["board_card", "card_removal"],
  },
  {
    id: "FND-06-A01", skillId: "FND-06", kind: "decision", sourceRefs: ["LCM-01"],
    assumptions: ["multiway", "stacks differ"],
    promptRu: "В multiway pot Hero покрывает одного соперника, но не другого. Есть ли одна общая effective depth для всего банка?",
    promptEn: "In a multiway pot Hero covers one opponent but not another. Is there one global effective depth for the whole pot?",
    answerRu: "Нет. Effective stack считается pairwise против каждого релевантного соперника.", answerEn: "No. Effective stack is pairwise against each relevant opponent.",
    rationaleRu: "Это действующий LCM-01 mechanism.", rationaleEn: "This is the existing LCM-01 mechanism.",
  },
  {
    id: "FND-06-A02", skillId: "FND-06", kind: "changed", sourceRefs: ["LCM-01", "FTGU-E01"],
    assumptions: ["same starting stack", "much larger preflop pot"],
    promptRu: "Стартовая глубина не изменилась, но preflop pot стал намного больше. Что происходит с postflop decision tree?",
    promptEn: "Starting depth is unchanged, but the preflop pot becomes much larger. What happens to the postflop decision tree?",
    answerRu: "SPR падает, дерево сжимается и commitment/leverage меняются.", answerEn: "SPR falls, the tree compresses, and commitment/leverage change.",
    rationaleRu: "LCM-01 и FTGU-E01 связывают remaining stack relative to pot с количеством будущих решений.",
    rationaleEn: "LCM-01 and FTGU-E01 connect remaining stack relative to pot with the future decision tree.",
    changedVariables: ["preflop_pot_size", "post_action_spr"],
  },
  {
    id: "FND-07-A01", skillId: "FND-07", kind: "recognition", sourceRefs: ["FTGU-E01"],
    assumptions: ["river or all-in", "no future leverage"],
    promptRu: "Когда equity наиболее тесно связано с EV: при большом числе будущих решений или когда action tree почти закончен?",
    promptEn: "When is equity most closely related to EV: with many future decisions or when the action tree is nearly finished?",
    answerRu: "Когда action tree почти закончен.", answerEn: "When the action tree is nearly finished.",
    rationaleRu: "FTGU-E01 прямо выделяет all-in/river nodes как случаи, где price и equity доминируют.",
    rationaleEn: "FTGU-E01 explicitly identifies all-in/river nodes as cases where price and equity dominate.",
  },
];
