import type { PracticalAnchor } from "./types";

export const preflopAndBlindAnchors: PracticalAnchor[] = [
  {
    id: "PF-01-A01", skillId: "PF-01", kind: "changed", sourceRefs: ["FTGU-E02"],
    assumptions: ["same hand class", "same stack/rake", "fewer players remain"],
    promptRu: "Если та же fringe hand перемещается из HJ на BTN и остальные условия равны, какое структурное изменение обычно помогает open?",
    promptEn: "If the same fringe hand moves from HJ to BTN with other assumptions unchanged, what structural change generally helps the open?",
    answerRu: "Меньше игроков остаётся позади и позиция улучшает equity realisation, поэтому fringe opens могут расширяться.",
    answerEn: "Fewer players remain and position improves equity realization, so fringe opens can widen.",
    rationaleRu: "FTGU-E02 описывает постепенное расширение диапазона от ранних к поздним позициям и отдельно связывает BTN с лучшей реализацией.",
    rationaleEn: "FTGU-E02 describes gradual widening toward late position and explicitly links BTN with better realization.",
    changedVariables: ["position", "players_behind"],
  },
  {
    id: "PF-01-A02", skillId: "PF-01", kind: "boundary", sourceRefs: ["FTGU-E02"],
    assumptions: ["fringe open candidate", "aggressive competent players behind"],
    promptRu: "Нужно ли сохранять fringe open только потому, что chart обычно его допускает, если игроки позади часто создают давление?",
    promptEn: "Should a fringe open be kept just because a default chart often includes it when players behind apply frequent pressure?",
    answerRu: "Нет. Fringe range нужно корректировать к players behind; default chart не является законом.",
    answerEn: "No. The fringe should adjust to players behind; the default chart is not a law.",
    rationaleRu: "FTGU-E02 прямо требует адаптировать fringe range к игрокам позади.",
    rationaleEn: "FTGU-E02 explicitly says to adjust the fringe to players behind.",
  },
  {
    id: "PF-02-A01", skillId: "PF-02", kind: "decision", sourceRefs: ["FTGU-E03"],
    assumptions: ["several limpers", "low fold equity", "likely multiway", "implied-odds hand"],
    promptRu: "При низком fold equity и высокой вероятности multiway что чаще лучше сохраняет implied odds: огромный iso или маленькая инвестиция через overlimp?",
    promptEn: "With low fold equity and a likely multiway pot, what more often preserves implied odds for an implied-odds hand: a huge isolation raise or a small overlimp investment?",
    answerRu: "Overlimp может быть лучше, если raise часто получит calls/squeezes и не создаст нужных folds.",
    answerEn: "Overlimping can be better when a raise will often get called/squeezed and does not create the needed folds.",
    rationaleRu: "FTGU-E03 прямо выделяет overlimp для small pairs/suited connected hands при плохом fold equity и multiway expectation.",
    rationaleEn: "FTGU-E03 explicitly supports overlimping small pairs/suited connected hands when fold equity is poor and the pot is likely multiway.",
  },
  {
    id: "PF-02-A02", skillId: "PF-02", kind: "changed", sourceRefs: ["FTGU-E03"],
    assumptions: ["same hand", "one limper", "Hero now IP", "fold equity materially higher"],
    promptRu: "Если Hero теперь IP и fold equity против limper существенно выше, какая ветка получает больше EV относительно пассивного overlimp?",
    promptEn: "If Hero is now in position and fold equity versus the limper is materially higher, which branch gains EV relative to a passive overlimp?",
    answerRu: "Isolation raise становится привлекательнее.",
    answerEn: "The isolation raise becomes more attractive.",
    rationaleRu: "FTGU-E03 строит iso через frequent strength, fold equity и position.",
    rationaleEn: "FTGU-E03 organizes isolation around frequent strength, fold equity and position.",
    changedVariables: ["position", "fold_equity"],
  },
  {
    id: "PF-03-A01", skillId: "PF-03", kind: "decision", sourceRefs: ["FTGU-E04"],
    assumptions: ["Hero IP", "hand has implied-odds value", "aggressive squeezers behind"],
    promptRu: "Можно ли считать cold-call прибыльным, не учитывая игроков позади?",
    promptEn: "Can a cold call be evaluated as profitable without accounting for players behind?",
    answerRu: "Нет. Squeeze risk и multiway participation могут сделать nominally good call хуже 3-bet или fold.",
    answerEn: "No. Squeeze risk and multiway participation can make a nominally good call worse than 3-betting or folding.",
    rationaleRu: "FTGU-E04 делает players behind частью самого EV call.",
    rationaleEn: "FTGU-E04 makes players behind part of the call's EV evaluation.",
  },
  {
    id: "PF-03-A02", skillId: "PF-03", kind: "recognition", sourceRefs: ["FTGU-E04"],
    assumptions: ["cold-call in position"],
    promptRu: "Какие две основные причины FTGU даёт для IP cold-call?",
    promptEn: "What two principal reasons does FTGU give for an in-position cold call?",
    answerRu: "Value либо implied odds.", answerEn: "Value or implied odds.",
    rationaleRu: "Это прямой framework FTGU-E04.", rationaleEn: "This is the direct framework in FTGU-E04.",
  },
  {
    id: "PF-04-A01", skillId: "PF-04", kind: "decision", sourceRefs: ["FTGU-E05"],
    assumptions: ["Hero in BB", "closes action", "small open", "wide opener"],
    promptRu: "Почему рука, которая позади opening range, всё же может быть прибыльным BB call?",
    promptEn: "Why can a hand that is behind the opening range still be a profitable BB call?",
    answerRu: "Blind discount, pot odds, closing action и достаточная realisation могут сделать call лучше автоматической потери от fold.",
    answerEn: "The blind discount, pot odds, closing action and enough realization can make calling better than the automatic loss from folding.",
    rationaleRu: "Это центральный mechanism FTGU-E05.", rationaleEn: "This is the central mechanism in FTGU-E05.",
  },
  {
    id: "PF-04-A02", skillId: "PF-04", kind: "changed", sourceRefs: ["FTGU-E05"],
    assumptions: ["same BB hand", "opener moves from late position to early position"],
    promptRu: "Что происходит с marginal BB defend, если origin range становится значительно сильнее?",
    promptEn: "What happens to a marginal BB defend when the origin range becomes materially stronger?",
    answerRu: "Он ухудшается из-за domination и большей плотности сильных one-pair/overpair regions.",
    answerEn: "It worsens because domination and strong one-pair/overpair density increase.",
    rationaleRu: "FTGU-E05 прямо сравнивает weak hand против wide и concentrated early-position ranges.",
    rationaleEn: "FTGU-E05 explicitly contrasts weak-hand performance versus wide and concentrated early-position ranges.",
    changedVariables: ["opener_position", "origin_range_strength"],
  },
  {
    id: "PF-05-A01", skillId: "PF-05", kind: "decision", sourceRefs: ["FTGU-E06"],
    assumptions: ["Hero SB", "faces open", "BB remains to act"],
    promptRu: "Почему SB flat структурно хуже аналогичного BB call?",
    promptEn: "Why is an SB flat structurally worse than a comparable BB call?",
    answerRu: "SB получает хуже price, остаётся OOP, не закрывает action и может быть squeezed BB.",
    answerEn: "SB gets a worse price, remains OOP, does not close the action and can be squeezed by BB.",
    rationaleRu: "Это прямой механизм FTGU-E06.", rationaleEn: "This is the direct mechanism in FTGU-E06.",
  },
  {
    id: "PF-05-A02", skillId: "PF-05", kind: "boundary", sourceRefs: ["FTGU-E06"],
    assumptions: ["Hero SB", "BB weak/passive"],
    promptRu: "Означает ли название '3-bet or fold' буквальный запрет любых SB flats?",
    promptEn: "Does the title '3-bet or fold' mean all SB flats are literally forbidden?",
    answerRu: "Нет. Это default simplification; некоторые flats могут выживать при пассивном BB или подходящей hand structure.",
    answerEn: "No. It is a default simplification; some flats can survive with a passive BB or suitable hand structure.",
    rationaleRu: "FTGU-E06 специально ограничивает правило и описывает conditional flats.",
    rationaleEn: "FTGU-E06 explicitly limits the rule and describes conditional flats.",
  },
  {
    id: "PF-06-A01", skillId: "PF-06", kind: "decision", sourceRefs: ["FTGU-E15"],
    assumptions: ["low fold equity", "opponent continues too much"],
    promptRu: "Какой 3-bet shape обычно лучше соответствует низкому fold equity: polar или более linear?",
    promptEn: "Which 3-bet shape generally fits low fold equity better: polar or more linear?",
    answerRu: "Более linear, концентрируясь на руках, которые лучше играют when called.",
    answerEn: "More linear, concentrating on hands that perform best when called.",
    rationaleRu: "FTGU-E15 прямо связывает low fold equity с linear value/isolation.",
    rationaleEn: "FTGU-E15 explicitly links low fold equity to linear value/isolation.",
  },
  {
    id: "PF-06-A02", skillId: "PF-06", kind: "changed", sourceRefs: ["FTGU-E15"],
    assumptions: ["viable calling range exists", "fold equity becomes high"],
    promptRu: "Если folds становятся реальными и между value и bluff существует прибыльный call region, какой 3-bet shape получает больше смысла?",
    promptEn: "If folds become meaningful and a profitable calling region exists between value and bluffs, which 3-bet shape becomes more sensible?",
    answerRu: "Polarized 3-bet structure.", answerEn: "A polarized 3-bet structure.",
    rationaleRu: "FTGU-E15 именно так определяет условия для polarization.",
    rationaleEn: "FTGU-E15 defines the conditions for polarization this way.",
    changedVariables: ["fold_equity", "calling_range_viability"],
  },
  {
    id: "PF-07-A01", skillId: "PF-07", kind: "changed", sourceRefs: ["FTGU-E17"],
    assumptions: ["same opening range", "3-bet size becomes larger", "Hero OOP"],
    promptRu: "Как должна двигаться defence frequency против более крупного 3-bet OOP?",
    promptEn: "How should defense frequency move against a larger 3-bet while OOP?",
    answerRu: "В сторону большего количества folds.", answerEn: "Toward more folds.",
    rationaleRu: "FTGU-E17 прямо говорит: larger bets и OOP justify more folds.",
    rationaleEn: "FTGU-E17 explicitly states that larger bets and being OOP justify more folds.",
    changedVariables: ["three_bet_size", "position"],
  },
  {
    id: "PF-07-A02", skillId: "PF-07", kind: "boundary", sourceRefs: ["FTGU-E17"],
    assumptions: ["standard competent pressure"],
    promptRu: "Является ли 'continue about half' точным equilibrium requirement?",
    promptEn: "Is 'continue about half' an exact equilibrium requirement?",
    answerRu: "Нет. Это ballpark practical baseline, который меняется с size, position, range shape и underbluffing.",
    answerEn: "No. It is a ballpark practical baseline that changes with size, position, range shape and underbluffing.",
    rationaleRu: "FTGU-E17 прямо запрещает трактовать 50% как точный закон.",
    rationaleEn: "FTGU-E17 explicitly says the 50% figure is not an exact law.",
  },
  {
    id: "PF-08-A01", skillId: "PF-08", kind: "decision", sourceRefs: ["FTGU-E18"],
    assumptions: ["opponent responds mostly jam-or-fold", "medium hand has profitable call"],
    promptRu: "Что чаще сохраняет EV medium-strength hand против jam-or-fold 5-bet response: 4-bet/fold или protected call region?",
    promptEn: "What more often preserves EV for a medium-strength hand against a jam-or-fold 5-bet response: 4-bet/fold or a protected calling region?",
    answerRu: "Protected call region.", answerEn: "The protected calling region.",
    rationaleRu: "FTGU-E18 объясняет polarization именно через strong value + bluffs вокруг прибыльных calls.",
    rationaleEn: "FTGU-E18 explains polarization as strong value plus bluffs around profitable calls.",
  },
  {
    id: "PF-08-A02", skillId: "PF-08", kind: "boundary", sourceRefs: ["FTGU-E18"],
    assumptions: ["weak underbluffing opponent"],
    promptRu: "Нужно ли сохранять balanced 4-bet bluff region против underbluffing recreational 3-bet range?",
    promptEn: "Should a balanced 4-bet bluff region be preserved against an underbluffing recreational 3-bet range?",
    answerRu: "Нет автоматически; source сдвигается к более value-heavy/linear response и tighter stack-offs.",
    answerEn: "Not automatically; the source shifts toward a more value-heavy/linear response and tighter stack-offs.",
    rationaleRu: "FTGU-E18 прямо удаляет часть bluffs против underbluffing ranges.",
    rationaleEn: "FTGU-E18 explicitly removes bluffs against underbluffing ranges.",
  },
  {
    id: "BL-03-A01", skillId: "BL-03", kind: "recognition", sourceRefs: ["FTGU-E05"],
    assumptions: ["BB closes action", "BTN opens wider than EP"],
    promptRu: "Какие три structural factors особенно поддерживают более широкий BB defend против BTN?",
    promptEn: "Which three structural factors especially support wider BB defense versus BTN?",
    answerRu: "Blind discount/pot odds, closing action и более широкий origin range; realisation всё равно ограничивает fringe.",
    answerEn: "Blind discount/pot odds, closing action and a wider origin range; realization still constrains the fringe.",
    rationaleRu: "Все три фактора прямо перечислены в FTGU-E05.", rationaleEn: "All three factors are stated directly in FTGU-E05.",
  },
  {
    id: "BL-04-A01", skillId: "BL-04", kind: "changed", sourceRefs: ["FTGU-E05"],
    assumptions: ["same opener range", "BB closes action", "open size increases"],
    promptRu: "Если open size растёт, должен ли BB автоматически копировать прежний defend range?",
    promptEn: "If the open size increases, should BB automatically copy the previous defense range?",
    answerRu: "Нет. Цена ухудшается, поэтому marginal defends теряют EV.",
    answerEn: "No. The price worsens, so marginal defenses lose EV.",
    rationaleRu: "FTGU-E05 связывает small opens с более жизнеспособной defence.",
    rationaleEn: "FTGU-E05 links smaller opens with more viable defense.",
    changedVariables: ["open_size", "pot_odds"],
  },
  {
    id: "BL-05-A01", skillId: "BL-05", kind: "decision", sourceRefs: ["FTGU-E06"],
    assumptions: ["SB faces open", "BB competent/aggressive"],
    promptRu: "Как меняется привлекательность passive SB flat, если BB часто squeezes?",
    promptEn: "How does the attractiveness of a passive SB flat change when BB squeezes frequently?",
    answerRu: "Она резко ухудшается; вероятность потерять всю equity before flop must enter EV.",
    answerEn: "It worsens sharply; the probability of losing all equity before the flop must enter the EV calculation.",
    rationaleRu: "FTGU-E06 делает squeeze risk одной из главных причин слабости SB flats.",
    rationaleEn: "FTGU-E06 makes squeeze risk one of the central reasons SB flats are weak.",
  },
  {
    id: "BL-10-A01", skillId: "BL-10", kind: "decision", sourceRefs: ["SLC-M02-L05"],
    assumptions: ["same flop", "compare opener vs BB caller and opener vs SB caller", "200bb example family"],
    promptRu: "Можно ли использовать одинаковый c-bet default на той же доске против BB и SB только потому, что board не изменился?",
    promptEn: "Can the same c-bet default be used on the same board versus BB and SB just because the board is unchanged?",
    answerRu: "Нет. Сначала нужно определить, какой blind range дошёл до flop.",
    answerEn: "No. First identify which blind range reached the flop.",
    rationaleRu: "SLC-M02-L05 показывает, что одинаковые boards могут менять strategy direction из-за разной range identity BB и SB.",
    rationaleEn: "SLC-M02-L05 shows that identical boards can change strategic direction because BB and SB arrive with different range identities.",
  },
  {
    id: "BL-10-A02", skillId: "BL-10", kind: "changed", sourceRefs: ["SLC-M02-L05"],
    assumptions: ["same opener", "same flop", "caller changes from BB to SB"],
    promptRu: "Caller меняется с BB на SB. Какой первый стратегический вопрос важнее: 'доска выглядит хорошей' или 'как изменилась arriving range'?",
    promptEn: "The caller changes from BB to SB. Which first strategic question matters more: 'does the board look good' or 'how did the arriving range change'?",
    answerRu: "Как изменилась arriving range.", answerEn: "How the arriving range changed.",
    rationaleRu: "SLC-M02-L05 прямо предупреждает против board-appearance autopilot.",
    rationaleEn: "SLC-M02-L05 explicitly warns against board-appearance autopilot.",
    changedVariables: ["blind_identity", "arriving_range"],
  },
];
