import type { PracticalAnchor } from "./types";

export const advancedPracticalAnchors: PracticalAnchor[] = [
  // W7 — 3-bet pots
  {
    id: "3BP-01-A01", skillId: "3BP-01", kind: "decision", sourceRefs: ["FTGU-E28"],
    assumptions: ["3-bet pot", "aggressor retains concentrated premium advantage", "dry high-card or paired family"],
    promptRu: "Может ли 3-bettor использовать очень частый small c-bet даже OOP, если flop почти не разрушает premium-range advantage?",
    promptEn: "Can the 3-bettor use a very frequent small c-bet even OOP when the flop barely disrupts the premium-range advantage?",
    answerRu: "Да. Concentrated preflop advantage может перевесить positional disadvantage на таких boards.",
    answerEn: "Yes. Concentrated preflop advantage can outweigh the positional disadvantage on such boards.",
    rationaleRu: "FTGU-E28 прямо описывает dry high-card/paired boards как high-frequency small-bet candidates.",
    rationaleEn: "FTGU-E28 explicitly describes dry high-card/paired boards as high-frequency small-bet candidates.",
  },
  {
    id: "3BP-01-A02", skillId: "3BP-01", kind: "changed", sourceRefs: ["FTGU-E28"],
    assumptions: ["flop range bet was called", "same 3-bettor"],
    promptRu: "После flop range-bet и call можно ли range-bet turn по инерции?",
    promptEn: "After a flop range bet gets called, can Hero range-bet the turn by inertia?",
    answerRu: "Нет. Caller отфильтровал weakest hands, aggressor сохранил flop air; ranges нужно пересчитать.",
    answerEn: "No. The caller filtered the weakest hands while the aggressor kept flop air; ranges must be recalculated.",
    rationaleRu: "Это главный turn warning FTGU-E28.", rationaleEn: "This is the main turn warning in FTGU-E28.",
    changedVariables: ["flop_call_filtering", "turn_range_strength"],
  },
  {
    id: "3BP-05-A01", skillId: "3BP-05", kind: "decision", sourceRefs: ["FTGU-E29"],
    assumptions: ["3-bet pot", "flop materially equalises ranges but does not reverse them"],
    promptRu: "Что лучше подходит moderate range advantage: автоматический range bet или split strategy?",
    promptEn: "What better fits moderate range advantage: an automatic range bet or a split strategy?",
    answerRu: "Split strategy: strongest value + promising bluffs bet, medium showdown value checks.",
    answerEn: "A split strategy: strongest value plus promising bluffs bet, medium showdown value checks.",
    rationaleRu: "FTGU-E29 занимает именно middle ground между range bet и range check.",
    rationaleEn: "FTGU-E29 explicitly covers the middle ground between range betting and range checking.",
  },
  {
    id: "3BP-05-A02", skillId: "3BP-05", kind: "boundary", sourceRefs: ["FTGU-E29"],
    assumptions: ["board contains high cards", "both players can hold nutted region"],
    promptRu: "Гарантируют ли high cards на flop, что 3-bettor обязан владеть board?",
    promptEn: "Do high cards on the flop guarantee that the 3-bettor owns the board?",
    answerRu: "Нет. Shared nutted hands могут neutralise preflop premium advantage.",
    answerEn: "No. Shared nutted hands can neutralize the preflop premium advantage.",
    rationaleRu: "FTGU-E29 прямо отвергает high-card shortcut.", rationaleEn: "FTGU-E29 explicitly rejects the high-card shortcut.",
  },

  // W8 — 4-bet / low SPR
  {
    id: "4BP-01-A01", skillId: "4BP-01", kind: "decision", sourceRefs: ["CP-G3-L10"],
    assumptions: ["low-SPR 4-bet pot", "flop favourable/neutral to 4-bettor"],
    promptRu: "Какой practical simplification source предлагает для многих favourable/neutral low-SPR 4-bet flops?",
    promptEn: "What practical simplification does the source propose for many favorable/neutral low-SPR 4-bet flops?",
    answerRu: "Small range-bet branch; exact size/frequency не переносится как универсальное правило.",
    answerEn: "A small range-bet branch; the exact size/frequency is not promoted as a universal rule.",
    rationaleRu: "CP-G3-L10 описывает flop strategy compression и отдельно ограничивает exact numeric claims.",
    rationaleEn: "CP-G3-L10 describes flop strategy compression and explicitly limits exact numeric claims.",
  },
  {
    id: "4BP-03-A01", skillId: "4BP-03", kind: "boundary", sourceRefs: ["CP-G3-L10"],
    assumptions: ["low SPR", "strong stable hands available"],
    promptRu: "Означает ли low SPR, что strong hands обязаны всегда ставить немедленно?",
    promptEn: "Does low SPR mean strong hands must always bet immediately?",
    answerRu: "Нет. Strong hands могут защищать checking range, если check-call/check-jam остаются credible.",
    answerEn: "No. Strong hands can protect the checking range when check-call/check-jam remain credible.",
    rationaleRu: "CP-G3-L10 отдельно учит protected checking at low SPR.",
    rationaleEn: "CP-G3-L10 explicitly teaches protected checking at low SPR.",
  },
  {
    id: "4BP-04-A01", skillId: "4BP-04", kind: "decision", sourceRefs: ["CP-G3-L10"],
    assumptions: ["turn", "low SPR", "medium-EV hand", "larger bet would leave jam-friendly remainder"],
    promptRu: "Почему нельзя выбирать turn size, игнорируя вероятность jam после ставки?",
    promptEn: "Why can turn sizing not ignore the probability of facing a jam after betting?",
    answerRu: "Потому что large bet может повысить jam frequency и уничтожить equity realisation medium-EV region.",
    answerEn: "Because a large bet can increase jam frequency and destroy equity realization for the medium-EV region.",
    rationaleRu: "Это jam-exposure band CP-G3-L10.", rationaleEn: "This is the jam-exposure band in CP-G3-L10.",
  },

  // W9 — turn
  {
    id: "TURN-01-A01", skillId: "TURN-01", kind: "recognition", sourceRefs: ["FTGU-E21"],
    assumptions: ["defender called flop", "turn arrives"],
    promptRu: "Перед тем как назвать turn 'blank' и продолжить pressure, какой вопрос нужно задать о flop response?",
    promptEn: "Before calling the turn a blank and continuing pressure, what must be asked about the flop response?",
    answerRu: "Имел ли defender raise range на flop и действительно ли call branch был capped.",
    answerEn: "Whether the defender had a flop raising range and whether the call branch was actually capped.",
    rationaleRu: "FTGU-E21 делает это первым gate turn strategy.", rationaleEn: "FTGU-E21 makes this the first gate in turn strategy.",
  },
  {
    id: "TURN-02-A01", skillId: "TURN-02", kind: "changed", sourceRefs: ["FTGU-E21"],
    assumptions: ["flop caller was capped on blank turns", "new turn completes relevant two-pair/straight/flush region"],
    promptRu: "Если game-changing turn возвращает caller nutted hands, можно ли продолжать стратегию как против capped range?",
    promptEn: "If a game-changing turn restores nutted hands to the caller, can Hero continue as if the range were capped?",
    answerRu: "Нет. Range становится uncapped и betting strategy должна стать более selective/polar.",
    answerEn: "No. The range becomes uncapped and betting strategy should become more selective/polar.",
    rationaleRu: "FTGU-E21 прямо показывает cap reversal на game-changing turns.",
    rationaleEn: "FTGU-E21 explicitly shows cap reversal on game-changing turns.",
    changedVariables: ["turn_card", "caller_cap_state"],
  },
  {
    id: "TURN-03-A01", skillId: "TURN-03", kind: "decision", sourceRefs: ["FTGU-E20"],
    assumptions: ["PFR checks back flop", "turn does not restore many nutted hands"],
    promptRu: "Какой range-history факт может поддержать turn probe?",
    promptEn: "Which range-history fact can support a turn probe?",
    answerRu: "Flop check-back мог удалить часть strong value и оставить PFR capped относительно caller.",
    answerEn: "The flop check-back may have removed some strong value and left the PFR capped relative to the caller.",
    rationaleRu: "FTGU-E20 строит probe именно из missed-cbet filtering.", rationaleEn: "FTGU-E20 builds the probe from missed-cbet filtering.",
  },
  {
    id: "TURN-03-A02", skillId: "TURN-03", kind: "boundary", sourceRefs: ["FTGU-E20"],
    assumptions: ["flop checked back", "turn improves checked range substantially"],
    promptRu: "Является ли 'missed c-bet -> overbet probe' универсальным правилом?",
    promptEn: "Is 'missed c-bet -> overbet probe' a universal rule?",
    answerRu: "Нет. Turn может uncapped checked range; probe начинается с exact range + new card.",
    answerEn: "No. The turn can uncap the checked range; probing starts from the exact range plus the new card.",
    rationaleRu: "FTGU-E20 специально предупреждает против механического probe.",
    rationaleEn: "FTGU-E20 explicitly warns against mechanical probing.",
  },

  // W10 — river
  {
    id: "RIV-03-A01", skillId: "RIV-03", kind: "decision", sourceRefs: ["FTGU-E22"],
    assumptions: ["river bluff-catcher", "two hands have same pair rank", "different blockers"],
    promptRu: "Должны ли две руки одинаковой pair rank иметь одинаковый river call EV?",
    promptEn: "Should two hands with the same pair rank have the same river call EV?",
    answerRu: "Нет. Blockers могут удалять value или natural bluffs и сильно менять call quality.",
    answerEn: "No. Blockers can remove value or natural bluffs and materially change call quality.",
    rationaleRu: "Это центральный lesson FTGU-E22.", rationaleEn: "This is the central lesson of FTGU-E22.",
  },
  {
    id: "RIV-03-A02", skillId: "RIV-03", kind: "boundary", sourceRefs: ["FTGU-E22"],
    assumptions: ["close river decision", "no reliable exploit evidence"],
    promptRu: "Разрешает ли близкое решение придумать player read, чтобы оправдать call/fold?",
    promptEn: "Does a close river decision justify inventing a player read to support a call or fold?",
    answerRu: "Нет. Line, size, ranges, blockers и реальное evidence должны нести решение; uncertainty можно оставить uncertainty.",
    answerEn: "No. The line, size, ranges, blockers and real evidence must carry the decision; uncertainty can remain uncertainty.",
    rationaleRu: "FTGU-E22 прямо предупреждает против invented narratives.",
    rationaleEn: "FTGU-E22 explicitly warns against invented narratives.",
  },
  {
    id: "RIV-02-A01", skillId: "RIV-02", kind: "decision", sourceRefs: ["FTGU-E23"],
    assumptions: ["river", "several missed draws available"],
    promptRu: "Нужно ли bluff every missed draw только потому, что у них нет showdown value?",
    promptEn: "Should Hero bluff every missed draw just because it has no showdown value?",
    answerRu: "Нет. Bluff volume выводится из size/value region, а кандидаты выбираются по blockers и ancestry.",
    answerEn: "No. Bluff volume is derived from size/value region, and candidates are selected by blockers and ancestry.",
    rationaleRu: "FTGU-E23 прямо запрещает bluff every missed draw.", rationaleEn: "FTGU-E23 explicitly rejects bluffing every missed draw.",
  },
  {
    id: "RIV-02-A02", skillId: "RIV-02", kind: "boundary", sourceRefs: ["FTGU-E23"],
    assumptions: ["candidate bluff did not plausibly continue earlier streets"],
    promptRu: "Может ли рука быть хорошим river bluff только из-за blocker, если она не должна была дойти до river по предыдущей линии?",
    promptEn: "Can a hand be a good river bluff solely because of a blocker if it should not have reached the river through the prior line?",
    answerRu: "Нет. Range ancestry является обязательным gate.", answerEn: "No. Range ancestry is a required gate.",
    rationaleRu: "FTGU-E23 требует, чтобы bluff реально существовал в flop/turn branches.",
    rationaleEn: "FTGU-E23 requires the bluff to plausibly exist in the flop/turn branches.",
  },
  {
    id: "RIV-05-A01", skillId: "RIV-05", kind: "decision", sourceRefs: ["FTGU-E24"],
    assumptions: ["large river bet", "passive profile", "prior filtering removed air", "few missed draws"],
    promptRu: "Нужно ли защищать MDF механически, если branch demonstrably underbluffed?",
    promptEn: "Must Hero defend MDF mechanically when the branch is demonstrably underbluffed?",
    answerRu: "Нет. Source поддерживает exploitative overfold против реально underbluffed branch.",
    answerEn: "No. The source supports exploitative overfolding against a genuinely underbluffed branch.",
    rationaleRu: "Это прямой mechanism FTGU-E24.", rationaleEn: "This is the direct mechanism in FTGU-E24.",
  },
  {
    id: "RIV-05-A02", skillId: "RIV-05", kind: "changed", sourceRefs: ["FTGU-E25"],
    assumptions: ["same river size", "branch now contains many natural air combos", "opponent barrels too many"],
    promptRu: "Если bluff-to-value ratio становится слишком высоким из-за uncontrolled air, как должен двигаться bluff-catch threshold?",
    promptEn: "If the bluff-to-value ratio becomes too high because of uncontrolled air, how should the bluff-catch threshold move?",
    answerRu: "В сторону более широких calls, если evidence действительно относится к этой branch.",
    answerEn: "Toward wider calls, if the evidence genuinely applies to this branch.",
    rationaleRu: "FTGU-E25 описывает exploitative overcalling именно так.", rationaleEn: "FTGU-E25 describes exploitative overcalling this way.",
    changedVariables: ["bluff_density", "opponent_evidence"],
  },
  {
    id: "RIV-04-A01", skillId: "RIV-04", kind: "decision", sourceRefs: ["CINJ-E08"],
    assumptions: ["OOP river", "IP bet earlier street then checked back", "small probe considered"],
    promptRu: "Является ли small river block/probe ставкой 'чтобы не получить большой bet'?",
    promptEn: "Is a small river block/probe simply a bet 'to avoid facing a big bet'?",
    answerRu: "Нет. Её нужно строить из range advantage, thin value/bluff function и response elasticity.",
    answerEn: "No. It must be built from range advantage, thin-value/bluff function and response elasticity.",
    rationaleRu: "CINJ-E08 прямо отвергает mystical block-bet explanation.",
    rationaleEn: "CINJ-E08 explicitly rejects the mystical block-bet explanation.",
  },

  // W11 — multiway / limp
  {
    id: "MW-01-A01", skillId: "MW-01", kind: "decision", sourceRefs: ["SLC-M04-L36"],
    assumptions: ["three-way pot", "Hero sandwiched", "uncapped range behind"],
    promptRu: "Почему sandwiched player не может защищаться так же свободно, как в heads-up pot?",
    promptEn: "Why can the sandwiched player not defend as freely as in a heads-up pot?",
    answerRu: "Потому что action behind остаётся живым; defence burden shared и range позади может punish calls/raises.",
    answerEn: "Because action behind remains live; defense is shared and the range behind can punish calls/raises.",
    rationaleRu: "SLC-M04-L36 называет sandwich effect центральной multiway dynamic.",
    rationaleEn: "SLC-M04-L36 calls the sandwich effect the central multiway dynamic.",
  },
  {
    id: "MW-03-A01", skillId: "MW-03", kind: "boundary", sourceRefs: ["SLC-M04-L36"],
    assumptions: ["multiway", "low-equity random air"],
    promptRu: "Нужно ли переносить heads-up random-air bluff candidates в multiway tree?",
    promptEn: "Should random low-equity heads-up bluff candidates be copied into a multiway tree?",
    answerRu: "Нет. Source требует более tight bluff categories с equity/removal и правильной strategic shape.",
    answerEn: "No. The source requires tighter bluff categories with equity/removal and the correct strategic shape.",
    rationaleRu: "SLC-M04-L36 прямо отвергает random low-equity multiway bluffs.",
    rationaleEn: "SLC-M04-L36 explicitly rejects random low-equity multiway bluffs.",
  },
  {
    id: "MW-02-A01", skillId: "MW-02", kind: "changed", sourceRefs: ["SLC-M04-L36"],
    assumptions: ["strong one-pair hand", "action becomes bet + call + check-raise multiway"],
    promptRu: "Как меняется ценность one-pair hand без backup equity после сильной multiway sequence?",
    promptEn: "How does the value of a one-pair hand without backup equity change after a strong multiway sequence?",
    answerRu: "Она резко падает; backup equity и nutted improvement paths становятся важнее.",
    answerEn: "It drops sharply; backup equity and nutted improvement paths become more important.",
    rationaleRu: "SLC-M04-L36 прямо отмечает pure-fold potential top pair without backup в сильной multiway sequence.",
    rationaleEn: "SLC-M04-L36 explicitly notes the pure-fold potential of top pair without backup in a strong multiway sequence.",
    changedVariables: ["number_of_live_ranges", "action_strength"],
  },

  // W12 — deep / straddle
  {
    id: "DEEP-01-A01", skillId: "DEEP-01", kind: "decision", sourceRefs: ["SLC-M02-L21"],
    assumptions: ["200bb", "OOP", "dynamic board"],
    promptRu: "Почему deep OOP нельзя просто 'нажать value' с medium-equity region, даже если raw equity неплохое?",
    promptEn: "Why can deep OOP not simply press value with the medium-equity region even when raw equity is decent?",
    answerRu: "Position и changing runouts снижают realised EV; protected checking/calling сохраняет middle range.",
    answerEn: "Position and changing runouts reduce realized EV; protected checking/calling preserves the middle range.",
    rationaleRu: "Это центральный mechanism SLC-M02-L21.", rationaleEn: "This is the central mechanism in SLC-M02-L21.",
  },
  {
    id: "DEEP-01-A02", skillId: "DEEP-01", kind: "changed", sourceRefs: ["SLC-M02-L21"],
    assumptions: ["deep OOP", "opponent c-bet size becomes larger"],
    promptRu: "Как source меняет OOP response против larger c-bet deep?",
    promptEn: "How does the source change the OOP response versus a larger c-bet when deep?",
    answerRu: "Raise frequency снижается, calling dominates; strong hands/draws защищают call line.",
    answerEn: "Raise frequency falls and calling dominates; strong hands/draws protect the call line.",
    rationaleRu: "SLC-M02-L21 прямо формулирует этот size response.", rationaleEn: "SLC-M02-L21 states this size response explicitly.",
    changedVariables: ["cbet_size"],
  },
  {
    id: "DEEP-03-A01", skillId: "DEEP-03", kind: "decision", sourceRefs: ["LCM-01"],
    assumptions: ["mandatory straddle"],
    promptRu: "Что нужно пересчитать первым после появления mandatory straddle?",
    promptEn: "What should be recalculated first after a mandatory straddle appears?",
    answerRu: "Рабочую forced unit, effective depth и последующий SPR; обычные BB больше не единственное описание.",
    answerEn: "The working forced unit, effective depth and later SPR; ordinary BB are no longer the only useful description.",
    rationaleRu: "Это существующий LCM-01 mechanism, перенесённый в отдельную practical family.",
    rationaleEn: "This is the existing LCM-01 mechanism moved into a dedicated practical family.",
  },

  // W13 — exploit
  {
    id: "EXP-01-A01", skillId: "EXP-01", kind: "boundary", sourceRefs: ["FTGU-E24", "FTGU-E25", "LCM-10"],
    assumptions: ["opponent labelled aggressive", "no branch-specific evidence"],
    promptRu: "Достаточно ли ярлыка 'агрессивный' для wider river calls?",
    promptEn: "Is the label 'aggressive' enough to justify wider river calls?",
    answerRu: "Нет. Нужны exact line, available air и evidence, что именно эта branch overbluffed.",
    answerEn: "No. The exact line, available air and evidence that this branch is overbluffed are required.",
    rationaleRu: "FTGU-E25 и LCM-10 требуют branch-specific evidence.", rationaleEn: "FTGU-E25 and LCM-10 require branch-specific evidence.",
  },
  {
    id: "EXP-03-A01", skillId: "EXP-03", kind: "decision", sourceRefs: ["FTGU-E24"],
    assumptions: ["airless runout", "prior streets removed low-equity bluffs", "large river aggression"],
    promptRu: "Какой exploit source поддерживает, если natural bluff supply почти исчез?",
    promptEn: "Which exploit does the source support when natural bluff supply has nearly disappeared?",
    answerRu: "Overfold relative to balanced baseline, особенно против large size.",
    answerEn: "Overfold relative to the balanced baseline, especially versus a large size.",
    rationaleRu: "FTGU-E24 описывает structurally airless runouts как источник underbluff.",
    rationaleEn: "FTGU-E24 describes structurally airless runouts as a source of underbluffing.",
  },
  {
    id: "EXP-04-A01", skillId: "EXP-04", kind: "decision", sourceRefs: ["FTGU-E25"],
    assumptions: ["air-rich river branch", "opponent barrels too many available air combos"],
    promptRu: "Какой exploit source поддерживает против реально overbluffed air-rich branch?",
    promptEn: "Which exploit does the source support against a genuinely overbluffed air-rich branch?",
    answerRu: "Wider bluff-catch calls, с учётом blockers и оставшихся missed draws.",
    answerEn: "Wider bluff-catch calls, still accounting for blockers and remaining missed draws.",
    rationaleRu: "Это центральный mechanism FTGU-E25.", rationaleEn: "This is the central mechanism in FTGU-E25.",
  },
  {
    id: "EXP-05-A01", skillId: "EXP-05", kind: "boundary", sourceRefs: ["CINJ-E08"],
    assumptions: ["small river probe exploit", "pool overfold claim not field-validated"],
    promptRu: "Можно ли превратить source claim 'люди часто overfold small river probes' в универсальный live rule?",
    promptEn: "Can the source claim 'people often overfold small river probes' be turned into a universal live rule?",
    answerRu: "Нет. Mechanism принят, но population magnitude остаётся field hypothesis.",
    answerEn: "No. The mechanism is accepted, but the population magnitude remains a field hypothesis.",
    rationaleRu: "CINJ-E08 разделяет accepted mechanism и pool hypothesis requiring validation.",
    rationaleEn: "CINJ-E08 separates the accepted mechanism from the pool hypothesis requiring validation.",
  },
];
