import type { PracticalAnchor } from "./types";

export const recognitionAndSrpAnchors: PracticalAnchor[] = [
  {
    id: "W4-BOARD-01-A01", skillId: "W4-BOARD-01", kind: "recognition", sourceRefs: ["FTGU-E07"],
    assumptions: ["BTN vs BB SRP", "preflop ranges known"],
    promptRu: "Достаточно ли назвать flop 'низким и связанным', чтобы автоматически решить, кому он принадлежит?",
    promptEn: "Is calling a flop 'low and connected' enough to automatically decide which range owns it?",
    answerRu: "Нет. Board texture нужно применить к конкретным preflop ranges и отсутствующим premium combos.",
    answerEn: "No. Board texture must be applied to the actual preflop ranges and their missing premium combinations.",
    rationaleRu: "FTGU-E07 прямо предупреждает против board-label shortcuts.", rationaleEn: "FTGU-E07 explicitly warns against board-label shortcuts.",
  },
  {
    id: "W4-BOARD-01-A02", skillId: "W4-BOARD-01", kind: "changed", sourceRefs: ["SLC-M02-L05"],
    assumptions: ["same flop", "same preflop raiser", "caller changes BB -> SB"],
    promptRu: "Если board не изменился, но caller теперь SB вместо BB, можно ли сохранить прежнюю c-bet frequency по внешнему виду доски?",
    promptEn: "If the board is unchanged but the caller is now SB instead of BB, can the previous c-bet frequency be preserved from board appearance alone?",
    answerRu: "Нет. Range source изменился; сначала пересчитай arriving-range advantage.",
    answerEn: "No. The range source changed; reassess the arriving-range advantage first.",
    rationaleRu: "SLC-M02-L05 показывает стратегические flips на одинаковых boards против BB и SB.",
    rationaleEn: "SLC-M02-L05 shows strategic flips on identical boards versus BB and SB.",
    changedVariables: ["caller_position", "arriving_range"],
  },
  {
    id: "W4-RUNOUT-01-A01", skillId: "W4-RUNOUT-01", kind: "recognition", sourceRefs: ["FTGU-E20"],
    assumptions: ["PFR checks back flop", "caller considers turn probe"],
    promptRu: "Перед turn probe достаточно знать, что flop был checked back?",
    promptEn: "Before a turn probe, is it enough to know that the flop was checked back?",
    answerRu: "Нет. Нужно проверить, какие сильные руки check-back удалил и не вернул ли turn часть nut strength обратно.",
    answerEn: "No. Check which strong hands the flop check removed and whether the turn card restored some nut strength.",
    rationaleRu: "FTGU-E20 требует пересматривать cap после конкретной turn card.",
    rationaleEn: "FTGU-E20 requires reassessing the cap after the specific turn card.",
  },
  {
    id: "W4-HAND-01-A01", skillId: "W4-HAND-01", kind: "decision", sourceRefs: ["FTGU-E09"],
    assumptions: ["Hero likely ahead of full betting range", "opponent continuing range much stronger"],
    promptRu: "Если Hero часто впереди полного betting range, достаточно ли этого, чтобы raise был value raise?",
    promptEn: "If Hero is often ahead of the full betting range, is that enough to make a raise a value raise?",
    answerRu: "Нет. Value raise должен хорошо стоять против range, который продолжает после raise.",
    answerEn: "No. A value raise must perform well against the range that continues versus the raise.",
    rationaleRu: "FTGU-E09 прямо отвергает shortcut 'likely best hand -> value raise'.",
    rationaleEn: "FTGU-E09 explicitly rejects the shortcut 'likely best hand -> value raise'.",
  },
  {
    id: "W4-REL-01-A01", skillId: "W4-REL-01", kind: "changed", sourceRefs: ["FTGU-E07", "FTGU-E09"],
    assumptions: ["same made-hand label", "opponent continuing range becomes stronger"],
    promptRu: "Рука всё ещё называется top pair. Если continuing range соперника стал сильнее, остаётся ли её strategic strength неизменной?",
    promptEn: "The hand is still called top pair. If villain's continuing range becomes stronger, is its strategic strength unchanged?",
    answerRu: "Нет. Relative strength падает, хотя абсолютное название комбинации не меняется.",
    answerEn: "No. Relative strength falls even though the absolute hand label is unchanged.",
    rationaleRu: "FTGU-E07/E09 строят решения относительно range interaction и continuing range, а не названия made hand.",
    rationaleEn: "FTGU-E07/E09 build decisions around range interaction and the continuing range, not the made-hand label.",
    changedVariables: ["continuing_range_strength"],
  },
  {
    id: "OOP-01-A01", skillId: "OOP-01", kind: "decision", sourceRefs: ["FTGU-E27"],
    assumptions: ["PFR OOP", "caller has positional and range advantage on wet/middling texture"],
    promptRu: "Нужно ли c-bet из-за одной только preflop initiative?",
    promptEn: "Should Hero c-bet solely because of preflop initiative?",
    answerRu: "Нет. На boards, которые принадлежат caller range и где позиция усиливает disadvantage, high-frequency check или range-check simplification может быть лучше.",
    answerEn: "No. On boards owned by the caller where position compounds the disadvantage, a high-frequency check or range-check simplification can be better.",
    rationaleRu: "Это центральный mechanism FTGU-E27.", rationaleEn: "This is the central mechanism of FTGU-E27.",
  },
  {
    id: "OOP-01-A02", skillId: "OOP-01", kind: "boundary", sourceRefs: ["FTGU-E27"],
    assumptions: ["OOP uses range-check simplification"],
    promptRu: "Может ли range-check означать пассивный check-fold всей средней части range?",
    promptEn: "Can a range-check simplification mean passively check-folding the whole middle of the range?",
    answerRu: "Нет. Check range должна быть защищена calls и raises.", answerEn: "No. The checking range must be protected with calls and raises.",
    rationaleRu: "FTGU-E27 требует active check-calls/check-raises/check-folds внутри range-check tree.",
    rationaleEn: "FTGU-E27 requires active check-calls/check-raises/check-folds inside the range-check tree.",
  },
  {
    id: "OOP-02-A01", skillId: "OOP-02", kind: "decision", sourceRefs: ["FTGU-E08"],
    assumptions: ["raising adds little EV", "board not highly urgent", "strong hands can remain in call branch"],
    promptRu: "Если raising мало добавляет EV, можно ли использовать call-only response strategy?",
    promptEn: "If raising adds little EV, can a call-only response strategy be used?",
    answerRu: "Да, но call-only всё ещё содержит folds; это не 'call everything'.",
    answerEn: "Yes, but call-only still contains folds; it does not mean 'call everything'.",
    rationaleRu: "FTGU-E08 специально отделяет call-only от indiscriminate calling.",
    rationaleEn: "FTGU-E08 explicitly separates call-only from indiscriminate calling.",
  },
  {
    id: "OOP-03-A01", skillId: "OOP-03", kind: "decision", sourceRefs: ["FTGU-E09"],
    assumptions: ["OOP", "strong hand vulnerable", "many bad turns", "value available now"],
    promptRu: "Что делает raising range более необходимой: низкая urgency или vulnerability + immediate value/denial?",
    promptEn: "What makes a raising range more necessary: low urgency or vulnerability plus immediate value/denial?",
    answerRu: "Vulnerability + immediate value/equity denial.", answerEn: "Vulnerability plus immediate value/equity denial.",
    rationaleRu: "FTGU-E09 перечисляет vulnerability, OOP и urgent denial как причины строить raise branch.",
    rationaleEn: "FTGU-E09 lists vulnerability, OOP and urgent denial as reasons to build a raise branch.",
  },
  {
    id: "OOP-03-A02", skillId: "OOP-03", kind: "boundary", sourceRefs: ["FTGU-E09"],
    assumptions: ["opponent betting range polar"],
    promptRu: "Почему medium-strength raise часто плох против polar bet?",
    promptEn: "Why is a medium-strength raise often poor versus a polar bet?",
    answerRu: "Он выбивает bluffs и получает action преимущественно от stronger hands; response тоже должен становиться более polar.",
    answerEn: "It folds out bluffs and gets action mostly from stronger hands; the response should also become more polar.",
    rationaleRu: "FTGU-E09 прямо связывает response shape с исходным betting range.",
    rationaleEn: "FTGU-E09 directly links response shape to the original betting range.",
  },
  {
    id: "IP-01-A01", skillId: "IP-01", kind: "decision", sourceRefs: ["FTGU-E07"],
    assumptions: ["PFR IP", "large concentrated range advantage", "board does not equalize ranges"],
    promptRu: "Какой simplified flop plan source поддерживает при большом concentrated advantage?",
    promptEn: "Which simplified flop plan does the source support with a large concentrated range advantage?",
    answerRu: "Small high-frequency / near-range bet может быть уместен.", answerEn: "A small high-frequency / near-range bet can be appropriate.",
    rationaleRu: "FTGU-E07 связывает unselective betting с большим concentrated advantage и small size.",
    rationaleEn: "FTGU-E07 links unselective betting with large concentrated advantage and a small size.",
  },
  {
    id: "IP-01-A02", skillId: "IP-01", kind: "changed", sourceRefs: ["FTGU-E07"],
    assumptions: ["same preflop roles", "board now strongly connects with defender"],
    promptRu: "Если новая board texture neutralises overpairs и даёт defender больше two-pair/straight density, что происходит с c-bet strategy?",
    promptEn: "If the new board texture neutralizes overpairs and gives the defender more two-pair/straight density, what happens to c-bet strategy?",
    answerRu: "Она становится более selective/polar; medium showdown hands чаще check.",
    answerEn: "It becomes more selective/polar; medium showdown hands check more often.",
    rationaleRu: "FTGU-E07 прямо описывает такой shift.", rationaleEn: "FTGU-E07 explicitly describes this shift.",
    changedVariables: ["board_range_interaction", "nut_advantage"],
  },
  {
    id: "IP-02-A01", skillId: "IP-02", kind: "decision", sourceRefs: ["FTGU-E08"],
    assumptions: ["IP", "strong hand", "opponent aggressive", "low urgency"],
    promptRu: "Почему strong hand иногда лучше оставить в call/check branch вместо немедленного raise?",
    promptEn: "Why can a strong hand sometimes be better left in the call/check branch rather than raised immediately?",
    answerRu: "Чтобы не cap passive branch и позволить агрессивному сопернику продолжать bluffing, когда urgency низкая.",
    answerEn: "To avoid capping the passive branch and let an aggressive opponent keep bluffing when urgency is low.",
    rationaleRu: "FTGU-E08 использует range protection и letting bluffs continue как основные причины.",
    rationaleEn: "FTGU-E08 uses range protection and letting bluffs continue as core reasons.",
  },
  {
    id: "IP-04-A01", skillId: "IP-04", kind: "decision", sourceRefs: ["FTGU-E20"],
    assumptions: ["PFR checked back flop", "caller probes turn"],
    promptRu: "Почему missed flop c-bet может создать turn attack opportunity?",
    promptEn: "Why can a missed flop c-bet create a turn attack opportunity?",
    answerRu: "Check-back может удалить часть nutted flop hands и сделать aggressor range capped относительно caller.",
    answerEn: "The check-back can remove some nutted flop hands and leave the aggressor range capped relative to the caller.",
    rationaleRu: "Это базовая range-ancestry логика FTGU-E20.", rationaleEn: "This is the core range-ancestry logic in FTGU-E20.",
  },
];
