import type { PracticalAnchor } from "./types";

export const foundationAnchors: PracticalAnchor[] = [
  {
    id: "FND-01-A01", skillId: "FND-01", kind: "recognition", sourceRefs: ["FTGU-E01"],
    assumptions: ["all-in decision", "call 2bb to win 8bb", "no future betting"],
    promptRu: "В банке 6bb, соперник ставит 2bb. Hero должен доставить 2bb, и дальше ставок не будет. Как часто нужно выигрывать, чтобы колл хотя бы не терял деньги?",
    promptEn: "The pot is 6bb, Villain bets 2bb, and Hero must call 2bb with no future betting. How often must Hero win for the call to break even?",
    answerRu: "Около 20%. Hero рискует 2bb, чтобы выиграть уже лежащие в банке 8bb.", answerEn: "About 20%. Hero risks 2bb to win the 8bb already in the pot.",
    rationaleRu: "Сначала сравни цену колла с банком, который можно выиграть: 2 к 8, то есть 1 к 4. Минимальная доля выигрышей равна 2 / (8 + 2) = 20%. Этот порог и называют требуемой эквити.",
    rationaleEn: "Compare the 2bb call with the 8bb available reward: 2 / (8 + 2) = 20%. That break-even share is the required equity.",
  },
  {
    id: "FND-01-A02", skillId: "FND-01", kind: "changed", sourceRefs: ["FTGU-E01"],
    assumptions: ["all-in decision", "call 4bb to win 16bb", "future decisions removed"],
    promptRu: "Теперь все суммы ровно удвоены: в банке 12bb, соперник ставит 4bb, Hero должен доставить 4bb. Меняется ли порог безубыточности?",
    promptEn: "Now every amount is doubled: the pot is 12bb, Villain bets 4bb, and Hero must call 4bb. Does the break-even threshold change?",
    answerRu: "Нет: порог остаётся 20%.", answerEn: "No: the threshold stays 20%.",
    rationaleRu: "Hero рискует 4bb, чтобы выиграть уже лежащие 16bb: 4 / (16 + 4) = 20%. Цена колла определяется отношением сумм, поэтому пропорциональное увеличение всех чисел не меняет требуемую эквити.",
    rationaleEn: "Hero risks 4bb to win the 16bb already available: 4 / (16 + 4) = 20%. The price is a ratio, so scaling every amount proportionally does not change required equity.",
    changedVariables: ["absolute_scale"],
  },
  {
    id: "FND-02-A01", skillId: "FND-02", kind: "decision", sourceRefs: ["FTGU-E01", "FTGU-E05"],
    assumptions: ["meaningful stack remains", "future betting possible"],
    promptRu: "У руки заметная equity, но Hero OOP и может часто фолдить на будущих улицах. Можно ли приравнять эту equity к EV решения?",
    promptEn: "A hand has meaningful raw equity, but Hero is OOP and may fold often on future streets. Can raw equity be treated as the EV of the decision?",
    answerRu: "Нет. Нужно учитывать, сколько equity реально реализуется на будущих улицах.", answerEn: "No. Equity realization and future branches must be considered.",
    rationaleRu: "Часть номинальной equity можно потерять, когда приходится фолдить под давлением. Позиция, цена и будущие решения определяют, сколько equity дойдёт до шоудауна.",
    rationaleEn: "FTGU-E01 separates equity from EV; FTGU-E05 adds that postflop execution can make a marginal BB defend unprofitable.",
  },
  {
    id: "FND-02-A02", skillId: "FND-02", kind: "changed", sourceRefs: ["FTGU-E05"],
    assumptions: ["same hand", "same opener range", "BB closes action"],
    promptRu: "Если Hero закрывает торговлю и получает лучшую цену, что происходит с реализацией пограничной защиты?",
    promptEn: "If Hero now closes the action and gets a better price, what happens to the practical viability of a marginal defend?",
    answerRu: "Она улучшается: пограничный call становится жизнеспособнее.", answerEn: "It improves; the marginal call becomes more viable.",
    rationaleRu: "Когда никто не может сделать рейз позади, а цена ниже, нужно реализовать меньшую долю equity, чтобы call окупался.",
    rationaleEn: "FTGU-E05 identifies closing action and a small open as factors that lower the required realizable equity.",
    changedVariables: ["closing_action", "price"],
  },
  {
    id: "FND-03-A01", skillId: "FND-03", kind: "recognition", sourceRefs: ["FTGU-E01"],
    assumptions: ["small current investment", "meaningful stack remains"],
    promptRu: "Почему рука с невысоким текущим equity иногда всё же может продолжить прибыльно?",
    promptEn: "Why can a hand with low current equity sometimes continue profitably?",
    answerRu: "Из-за выгодного будущего дерева и implied odds.", answerEn: "Because of a favorable future tree and implied odds.",
    rationaleRu: "FTGU-E01 прямо связывает implied odds с потенциальной будущей отдачей относительно текущей инвестиции.",
    rationaleEn: "FTGU-E01 explicitly frames implied odds as potential future return relative to the current investment.",
  },
  {
    id: "FND-03-A02", skillId: "FND-03", kind: "boundary", sourceRefs: ["FTGU-E05"],
    assumptions: ["weak top-pair potential", "tight early-position opening range"],
    promptRu: "Почему nominally playable high-card hand хуже реализуется против tight EP range, чем против wide late-position range?",
    promptEn: "Why does a nominally playable high-card hand realize worse versus a tight EP range than versus a wide late-position range?",
    answerRu: "Растут domination и плотность сильных overpair/top-pair regions.", answerEn: "Domination and strong overpair/top-pair density increase.",
    rationaleRu: "FTGU-E05 отдельно подчёркивает top-pair domination против concentrated early-position ranges.",
    rationaleEn: "FTGU-E05 explicitly highlights top-pair domination against concentrated early-position ranges.",
  },
  {
    id: "FND-05-A01", skillId: "FND-05", kind: "recognition", sourceRefs: ["FTGU-E11"],
    assumptions: ["preflop", "no blockers removed"],
    promptRu: "Сколько стандартных preflop комбинаций у pocket pair, suited hand и offsuit hand?",
    promptEn: "How many standard preflop combinations are there for a pocket pair, suited hand and offsuit hand?",
    answerRu: "6 / 4 / 12.", answerEn: "6 / 4 / 12.",
    rationaleRu: "Это прямые стандартные combo counts из FTGU-E11.",
    rationaleEn: "These are the standard combo counts stated directly in FTGU-E11.",
  },
  {
    id: "FND-05-A02", skillId: "FND-05", kind: "changed", sourceRefs: ["FTGU-E11"],
    assumptions: ["postflop", "board or Hero cards remove suits/ranks"],
    promptRu: "После выхода новой board card можно ли продолжать использовать исходное preflop число combos без пересчёта?",
    promptEn: "After a new board card arrives, can you keep using the original preflop combo count without recalculating?",
    answerRu: "Нет. Board и hole cards удаляют combos и могут менять их роль.", answerEn: "No. Board and hole cards remove combos and can change their role.",
    rationaleRu: "FTGU-E11 требует пересчитывать диапазон после board/action changes.",
    rationaleEn: "FTGU-E11 requires recounting as board cards and action change the surviving range.",
    changedVariables: ["board_card", "card_removal"],
  },
  {
    id: "FND-06-A01", skillId: "FND-06", kind: "decision", sourceRefs: ["LCM-01"],
    assumptions: ["multiway", "stacks differ"],
    promptRu: "В multiway pot Hero покрывает одного соперника, но не другого. Есть ли одна общая effective depth для всего банка?",
    promptEn: "In a multiway pot Hero covers one opponent but not another. Is there one global effective depth for the whole pot?",
    answerRu: "Нет. Effective stack считается pairwise против каждого релевантного соперника.", answerEn: "No. Effective stack is pairwise against each relevant opponent.",
    rationaleRu: "Это действующий LCM-01 mechanism.", rationaleEn: "This is the existing LCM-01 mechanism.",
  },
  {
    id: "FND-06-A02", skillId: "FND-06", kind: "changed", sourceRefs: ["LCM-01", "FTGU-E01"],
    assumptions: ["same starting stack", "much larger preflop pot"],
    promptRu: "Стартовая глубина не изменилась, но preflop pot стал намного больше. Что происходит с postflop decision tree?",
    promptEn: "Starting depth is unchanged, but the preflop pot becomes much larger. What happens to the postflop decision tree?",
    answerRu: "SPR падает, дерево сжимается и commitment/leverage меняются.", answerEn: "SPR falls, the tree compresses, and commitment/leverage change.",
    rationaleRu: "LCM-01 и FTGU-E01 связывают remaining stack relative to pot с количеством будущих решений.",
    rationaleEn: "LCM-01 and FTGU-E01 connect remaining stack relative to pot with the future decision tree.",
    changedVariables: ["preflop_pot_size", "post_action_spr"],
  },
  {
    id: "FND-07-A01", skillId: "FND-07", kind: "recognition", sourceRefs: ["FTGU-E01"],
    assumptions: ["river or all-in", "no future leverage"],
    promptRu: "Когда equity наиболее тесно связано с EV: при большом числе будущих решений или когда action tree почти закончен?",
    promptEn: "When is equity most closely related to EV: with many future decisions or when the action tree is nearly finished?",
    answerRu: "Когда action tree почти закончен.", answerEn: "When the action tree is nearly finished.",
    rationaleRu: "FTGU-E01 прямо выделяет all-in/river nodes как случаи, где price и equity доминируют.",
    rationaleEn: "FTGU-E01 explicitly identifies all-in/river nodes as cases where price and equity dominate.",
  },
];
