import type { PracticalRule } from "./mental-model";

export const blindA4Rules: PracticalRule[] = [
  {
    id: "RULE-BLIND-BB-VS-SB-CONTRAST",
    mode: "TRIGGER_RULE",
    triggerFamily: "PLAYERS_BEHIND",
    skillIds: ["PF-04", "PF-05", "BL-05"],
    sourceRefs: ["FTGU-E05", "FTGU-E06"],
    triggerRu: "Сравнивается защита из BB и passive flat из SB против open.",
    triggerEn: "Compare defending from the BB with passively flatting from the SB versus an open.",
    defaultRu: "Не переносить BB defend logic в SB: BB закрывает action и имеет лучший discount; SB остаётся OOP и оставляет BB позади.",
    defaultEn: "Do not transfer BB-defense logic to the SB: the BB closes the action and gets a better discount; the SB remains OOP with the BB still behind.",
    whyRu: "Цена, closing action, squeeze risk и postflop realisation создают разные range identities.",
    whyEn: "Price, closing action, squeeze risk and postflop realization create different range identities.",
    amplifiersRu: ["aggressive BB behind", "dominated SB hand", "высокий rake"],
    amplifiersEn: ["aggressive BB behind", "dominated SB hand", "high rake"],
    reversalsRu: ["очень passive/weak BB может вернуть часть conditional SB flats"],
    reversalsEn: ["a very passive/weak BB can restore some conditional SB flats"],
    transferCueRu: "Оставь opener и hand теми же; перемести Hero BB → SB.",
    transferCueEn: "Keep opener and hand fixed; move Hero from BB → SB.",
  },
  {
    id: "RULE-BLIND-ORIGIN-STRENGTH",
    mode: "TRIGGER_RULE",
    triggerFamily: "ORIGIN_RANGE",
    skillIds: ["BL-01", "BL-02", "BL-03"],
    sourceRefs: ["FTGU-E05"],
    triggerRu: "Тот же BB hand сталкивается с opener из более ранней позиции.",
    triggerEn: "The same BB hand faces an opener from an earlier position.",
    defaultRu: "Сжимай fringe defence по мере усиления origin range.",
    defaultEn: "Contract the fringe defense as the origin range becomes stronger.",
    whyRu: "Цена BB может быть той же, но domination и strong-overpair density растут против ранних ranges.",
    whyEn: "The BB price can be unchanged while domination and strong-overpair density rise against earlier ranges.",
    amplifiersRu: ["dominated offsuit high cards", "tight opener", "high rake"],
    amplifiersEn: ["dominated offsuit high cards", "tight opener", "high rake"],
    reversalsRu: ["необычно широкий early opener", "малый sizing", "сильная playability"],
    reversalsEn: ["unusually wide early opener", "small sizing", "strong playability"],
    transferCueRu: "Не меняй hand/sizing; поменяй BTN → CO → EP.",
    transferCueEn: "Keep hand/sizing fixed; change BTN → CO → EP.",
  },
  {
    id: "RULE-BLIND-SIZE-PRICE",
    mode: "TRIGGER_RULE",
    triggerFamily: "OPEN_SIZE",
    skillIds: ["BL-04", "BL-12"],
    sourceRefs: ["FTGU-E05"],
    triggerRu: "Open size заметно растёт при той же hand и позиции opener-а.",
    triggerEn: "The open size rises materially with the same hand and opener position.",
    defaultRu: "Marginal BB continues теряют EV первыми; не копируй defence frequency между sizing-ами.",
    defaultEn: "Marginal BB continues lose EV first; do not copy a defense frequency across sizes.",
    whyRu: "Больший risk ухудшает price, а rake/realisation могут дополнительно перевернуть close calls.",
    whyEn: "More risk worsens the price, while rake/realization can further flip close calls.",
    amplifiersRu: ["high rake", "poor postflop execution", "strong origin range"],
    amplifiersEn: ["high rake", "poor postflop execution", "strong origin range"],
    reversalsRu: ["small open", "wide origin range", "closing action + strong playability"],
    reversalsEn: ["small open", "wide origin range", "closing action plus strong playability"],
    transferCueRu: "Оставь всё неизменным и поменяй 2.5bb → 4bb.",
    transferCueEn: "Keep everything else fixed and change 2.5bb → 4bb.",
  },
  {
    id: "RULE-BLIND-POSTFLOP-IDENTITY",
    mode: "TRIGGER_RULE",
    triggerFamily: "BOARD_OWNERSHIP",
    skillIds: ["BL-10", "W4-BOARD-01"],
    sourceRefs: ["SLC-M02-L05"],
    triggerRu: "Одинаковый flop достигнут через BB call или через SB call.",
    triggerEn: "The same flop is reached through a BB call or an SB call.",
    defaultRu: "Сначала переопредели range identity: SB calling range обычно tighter/condensed, поэтому нельзя копировать vs-BB c-bet default.",
    defaultEn: "Re-read range identity first: the SB calling range is typically tighter/condensed, so a vs-BB c-bet default cannot simply be copied.",
    whyRu: "Board appearance одинаков, но preflop source range меняет folds, strong-pair density и ownership.",
    whyEn: "Board appearance is identical, but the preflop source range changes folds, strong-pair density and ownership.",
    amplifiersRu: ["boards, где condensed SB retains stronger pairs/Kx", "PFR рассчитывает на automatic folds"],
    amplifiersEn: ["boards where a condensed SB retains stronger pairs/Kx", "PFR relies on automatic folds"],
    reversalsRu: ["это postflop rule; оно не определяет preflop SB limp/raise/fold strategy"],
    reversalsEn: ["this is a postflop rule; it does not define preflop SB limp/raise/fold strategy"],
    transferCueRu: "Оставь board и PFR position; поменяй только caller BB → SB.",
    transferCueEn: "Keep the board and PFR position fixed; change only caller BB → SB.",
  },
];

export function blindA4RulesForSkill(skillId: string): PracticalRule[] {
  return blindA4Rules.filter((rule) => rule.skillIds.includes(skillId));
}
