import type { PracticalDecision } from "./types";

const o = (id: string, textRu: string, textEn: string, misconception?: string) => ({ id, textRu, textEn, misconception });

export const preflopAdvancedExpansionDecisions: PracticalDecision[] = [
  // PF-06 — 3-bet construction. FTGU E15/E16.
  {
    id:"PM-PF-06-101",skillId:"PF-06",kind:"recognition",sourceRefs:["FTGU-E15"],assumptions:["opponent folds meaningfully","viable calling range exists"],cueRu:"3-bet получает заметные folds, а между value и bluffs можно сохранить calls.",cueEn:"The 3-bet gets meaningful folds and a viable calling region exists between value and bluffs.",questionRu:"Какая shape естественнее?",questionEn:"Which shape is more natural?",actionOptions:[o("a","Polar","Polar"),o("b","Linear","Linear","SHAPE_BACKWARDS"),o("c","No calling range by definition","No calling range by definition","CALL_RANGE_IGNORED")],reasonOptions:[o("r1","Polar keeps strong value plus folds-preferring bluffs around profitable calls","Polar keeps strong value plus folds-preferring bluffs around profitable calls"),o("r2","High fold equity requires only strongest hands","High fold equity requires only the strongest hands","SHAPE_BACKWARDS"),o("r3","Calls cannot coexist with 3-bets","Calls cannot coexist with 3-bets","CALL_RANGE_FALSE")],correctActionId:"a",correctReasonId:"r1",targetSeconds:22,explanationRu:"FTGU-E15 defines polarization through fold equity plus a viable calling region.",explanationEn:"FTGU-E15 defines polarization through fold equity plus a viable calling region."},
  {
    id:"PM-PF-06-102",skillId:"PF-06",kind:"recognition",sourceRefs:["FTGU-E15"],assumptions:["opponent continues too much","fold equity low"],cueRu:"Opponent продолжает слишком много против 3-bet.",cueEn:"Opponent continues too much versus 3-bets.",questionRu:"Куда должна двигаться range shape?",questionEn:"Where should the range shape move?",actionOptions:[o("a","More linear/value-heavy","More linear/value-heavy"),o("b","More polar bluff-heavy","More polar bluff-heavy","FOLD_EQUITY_BACKWARDS"),o("c","Random","Random","NO_STRUCTURE")],reasonOptions:[o("r1","Low fold equity rewards hands that perform best when called","Low fold equity rewards hands that perform best when called"),o("r2","Low folds make weak bluffs better","Low folds make weak bluffs better","FOLD_EQUITY_BACKWARDS"),o("r3","Called branch is irrelevant","The called branch is irrelevant","CALL_BRANCH_IGNORED")],correctActionId:"a",correctReasonId:"r1",targetSeconds:20,explanationRu:"FTGU-E15 explicitly pushes toward linear construction when fold equity is low.",explanationEn:"FTGU-E15 explicitly pushes toward linear construction when fold equity is low."},
  {
    id:"PM-PF-06-103",skillId:"PF-06",kind:"decision",sourceRefs:["FTGU-E16"],assumptions:["call EV and 3-bet EV close","hand flexible/playable"],cueRu:"Flexible hand имеет близкие EV как call и 3-bet.",cueEn:"A flexible playable hand has similar EV as a call and a 3-bet.",questionRu:"Какой practical treatment поддерживает source?",questionEn:"Which practical treatment does the source support?",actionOptions:[o("a","Mix branches approximately","Mix branches approximately"),o("b","Force one permanent action","Force one permanent action","PURE_ACTION_DOGMA"),o("c","Copy exact solver randomization","Copy exact solver randomization","EXACT_MIX_REQUIRED")],reasonOptions:[o("r1","Mixing can give both ranges coverage without demanding exact solver frequencies","Mixing can give both ranges coverage without demanding exact solver frequencies"),o("r2","Every hand must have one eternal action","Every hand must have one eternal action","PURE_ACTION_DOGMA"),o("r3","Exact frequency is the learning objective","Exact frequency is the learning objective","FREQUENCY_OVER_MECHANISM")],correctActionId:"a",correctReasonId:"r1",targetSeconds:25,explanationRu:"FTGU-E16 treats mixing as practical approximation; exact randomisation is explicitly not required.",explanationEn:"FTGU-E16 treats mixing as a practical approximation; exact randomization is explicitly not required."},
  {
    id:"PM-PF-06-104",skillId:"PF-06",kind:"decision",sourceRefs:["FTGU-E15"],assumptions:["polar range","bluff candidate gains little from folds"],cueRu:"Предполагаемый polar bluff почти не выигрывает от fold и плохо играет when called.",cueEn:"A proposed polar bluff gains little from folds and plays poorly when called.",questionRu:"Что с candidate?",questionEn:"What about the candidate?",actionOptions:[o("a","Poor polar bluff candidate","Poor polar bluff candidate"),o("b","Ideal because weak","Ideal because it is weak","WEAK_EQUALS_BLUFF"),o("c","Automatic 3-bet if blocker absent","Automatic 3-bet if no blocker","NO_MECHANISM")],reasonOptions:[o("r1","Polar bluffs need material fold benefit plus useful blocker/equity properties","Polar bluffs need material fold benefit plus useful blocker/equity properties"),o("r2","The weakest hand is always the best bluff","The weakest hand is always the best bluff","BOTTOM_ALWAYS_BLUFF"),o("r3","Called branch never matters","The called branch never matters","CALL_BRANCH_IGNORED")],correctActionId:"a",correctReasonId:"r1",targetSeconds:25,explanationRu:"E15 does not define bluffs as merely weak hands; they need fold benefit and useful properties.",explanationEn:"E15 does not define bluffs as merely weak hands; they need fold benefit and useful properties."},
  {
    id:"PM-PF-06-105",skillId:"PF-06",kind:"decision",sourceRefs:["FTGU-E16"],assumptions:["medium hand earns more by calling","3-bet inflates pot unnecessarily"],cueRu:"Medium hand сохраняет domination и weaker range лучше через call.",cueEn:"A medium hand preserves domination and weaker ranges better by calling.",questionRu:"Нужно ли mix её только ради coverage?",questionEn:"Should it be mixed merely for coverage?",actionOptions:[o("a","No; it can remain pure call","No; it can remain a pure call"),o("b","Yes; every hand must mix","Yes; every hand must mix","MIX_EVERYTHING"),o("c","Always 3-bet medium hands","Always 3-bet medium hands","POT_INFLATION_AUTOPILOT")],reasonOptions:[o("r1","E16 preserves pure-call hands when calling has clearer branch value","E16 preserves pure-call hands when calling has clearer branch value"),o("r2","Coverage requires every combo in every branch","Coverage requires every combo in every branch","COVERAGE_MISREAD"),o("r3","Calling cannot dominate worse hands","Calling cannot dominate worse hands","DOMINATION_FALSE")],correctActionId:"a",correctReasonId:"r1",targetSeconds:25,explanationRu:"Mixed strategy still contains pure value, mixed and pure-call regions.",explanationEn:"A mixed strategy still contains pure value, mixed and pure-call regions."},
  {
    id:"PM-PF-06-106",skillId:"PF-06",kind:"changed",sourceRefs:["FTGU-E15"],assumptions:["same node","opponent fold equity high -> low"],cueRu:"Opponent сначала много fold, затем начинает много continue.",cueEn:"Opponent initially folds a lot, then begins continuing much more.",questionRu:"Как должна двигаться 3-bet shape?",questionEn:"How should the 3-bet shape move?",actionOptions:[o("a","Polar -> more linear","Polar -> more linear"),o("b","Linear -> more bluff-heavy polar","Linear -> more bluff-heavy polar","FOLD_EQUITY_BACKWARDS"),o("c","No change","No change","OPPONENT_IGNORED")],reasonOptions:[o("r1","Lower fold equity increases the weight on when-called performance","Lower fold equity increases the weight on when-called performance"),o("r2","More calls improve weak bluff EV","More calls improve weak bluff EV","CALL_BRANCH_BACKWARDS"),o("r3","Opponent response does not shape ranges","Opponent response does not shape ranges","OPPONENT_IGNORED")],correctActionId:"a",correctReasonId:"r1",targetSeconds:22,explanationRu:"This is the core E15 changed-node transfer.",explanationEn:"This is the core E15 changed-node transfer.",changedVariables:["fold_equity","opponent_continue"]},
  {
    id:"PM-PF-06-107",skillId:"PF-06",kind:"changed",sourceRefs:["FTGU-E15"],assumptions:["same range shape","sizing becomes much larger"],cueRu:"3-bet sizing становится значительно больше.",cueEn:"The 3-bet sizing becomes materially larger.",questionRu:"Что должно согласовываться с sizing?",questionEn:"What should remain coherent with sizing?",actionOptions:[o("a","Range shape and hand incentives","Range shape and hand incentives"),o("b","Nothing; size independent","Nothing; sizing is independent","SIZE_SHAPE_DISCONNECT"),o("c","Only card suits","Only card suits","IRRELEVANT")],reasonOptions:[o("r1","E15 links larger pressure sizing more naturally to polar structures","E15 links larger pressure sizing more naturally to polar structures"),o("r2","Sizing never changes called branch","Sizing never changes the called branch","SIZE_IGNORED"),o("r3","All shapes use identical sizing by rule","All shapes use identical sizing by rule","SIZE_LAW")],correctActionId:"a",correctReasonId:"r1",targetSeconds:24,explanationRu:"Range shape and size are not independent knobs in E15.",explanationEn:"Range shape and size are not independent knobs in E15.",changedVariables:["three_bet_size"]},
  {
    id:"PM-PF-06-108",skillId:"PF-06",kind:"boundary",sourceRefs:["FTGU-E16"],assumptions:["solver displays exact mix","visual cells not reviewed"],cueRu:"Источник говорит о mixing, но exact visual frequency не подтверждена.",cueEn:"The source discusses mixing, but the exact visual frequency has not been reviewed.",questionRu:"Что должен учить trainer?",questionEn:"What should the trainer teach?",actionOptions:[o("a","Branch purpose and approximate mixing eligibility","Branch purpose and approximate mixing eligibility"),o("b","Invent exact 37% frequency","Invent an exact 37% frequency","UNSUPPORTED_FREQUENCY"),o("c","Ban mixing entirely","Ban mixing entirely","OVERREACTION")],reasonOptions:[o("r1","E16 explicitly prioritizes structural coverage over exact randomisation","E16 explicitly prioritizes structural coverage over exact randomization"),o("r2","Exact percentages are always source-independent","Exact percentages are always source-independent","UNSUPPORTED_FREQUENCY"),o("r3","No exact cell means no mechanism can be taught","No exact cell means no mechanism can be taught","SOURCE_OVERBLOCK")],correctActionId:"a",correctReasonId:"r1",targetSeconds:25,explanationRu:"Boundary preserves source fidelity without throwing away the usable mechanism.",explanationEn:"The boundary preserves source fidelity without throwing away the usable mechanism."},

  // PF-07 — facing 3-bets. FTGU E17.
  {
    id:"PM-PF-07-101",skillId:"PF-07",kind:"recognition",sourceRefs:["FTGU-E17"],assumptions:["standard competent 3-bet","sensible opening range"],cueRu:"Facing standard competent 3-bet.",cueEn:"Facing a standard competent 3-bet.",questionRu:"Как трактовать 'примерно половину continue'?",questionEn:"How should 'continue about half' be interpreted?",actionOptions:[o("a","Ballpark baseline, not law","Ballpark baseline, not law"),o("b","Exact equilibrium frequency","Exact equilibrium frequency","FIFTY_AS_LAW"),o("c","Every individual hand mixes 50/50","Every individual hand mixes 50/50","HAND_FREQUENCY_MISREAD")],reasonOptions:[o("r1","E17 explicitly calls it a practical ballpark that changes with size/position/range/opponent","E17 explicitly calls it a practical ballpark that changes with size/position/range/opponent"),o("r2","50% is invariant to sizing","50% is invariant to sizing","FIFTY_AS_LAW"),o("r3","Range defence and individual hand frequency are identical","Range defense and individual hand frequency are identical","RANGE_HAND_CONFUSION")],correctActionId:"a",correctReasonId:"r1",targetSeconds:22,explanationRu:"E17's 50/50 is a safe baseline, never a universal threshold.",explanationEn:"E17's 50/50 is a safe baseline, never a universal threshold."},
  {
    id:"PM-PF-07-102",skillId:"PF-07",kind:"recognition",sourceRefs:["FTGU-E17"],assumptions:["defence range"],cueRu:"Continue range делится на несколько branches.",cueEn:"The continuing range splits into several branches.",questionRu:"Что входит в total defence?",questionEn:"What belongs in total defense?",actionOptions:[o("a","Calls + 4-bet value + 4-bet bluffs","Calls + 4-bet value + 4-bet bluffs"),o("b","Calls only","Calls only","DEFENCE_CALLS_ONLY"),o("c","4-bets only","4-bets only","DEFENCE_4BET_ONLY")],reasonOptions:[o("r1","Defence frequency is total reach across continuing actions","Defense frequency is total reach across continuing actions"),o("r2","A call is the only non-fold action","A call is the only non-fold action","ACTION_SET_FALSE"),o("r3","4-bets cannot be defensive","4-bets cannot be defensive","ACTION_SET_FALSE")],correctActionId:"a",correctReasonId:"r1",targetSeconds:18,explanationRu:"E17 explicitly partitions continues into calls and value/bluff 4-bets.",explanationEn:"E17 explicitly partitions continues into calls and value/bluff 4-bets."},
  {
    id:"PM-PF-07-103",skillId:"PF-07",kind:"decision",sourceRefs:["FTGU-E17"],assumptions:["large 3-bet","Hero OOP","dominated offsuit hand"],cueRu:"Large 3-bet, Hero OOP, dominated offsuit hand.",cueEn:"Large 3-bet, Hero OOP, dominated offsuit hand.",questionRu:"Какой direction supported?",questionEn:"Which direction is supported?",actionOptions:[o("a","Fold more","Fold more"),o("b","Defend wider because pot larger","Defend wider because the pot is larger","PRICE_BACKWARDS"),o("c","Call because open already invested","Call because the open is already invested","SUNK_COST_OVERUSE")],reasonOptions:[o("r1","Larger size + OOP + domination reduce realisation and worsen price","Larger size + OOP + domination reduce realization and worsen price"),o("r2","Larger bets improve caller price","Larger bets improve caller price","PRICE_BACKWARDS"),o("r3","Open investment forces continuation","The open investment forces continuation","SUNK_COST")],correctActionId:"a",correctReasonId:"r1",targetSeconds:25,explanationRu:"E17 says larger bets and OOP justify more folds; dominated offsuit hands are among the first to lose EV.",explanationEn:"E17 says larger bets and OOP justify more folds; dominated offsuit hands are among the first to lose EV."},
  {
    id:"PM-PF-07-104",skillId:"PF-07",kind:"decision",sourceRefs:["FTGU-E17"],assumptions:["undersized 3-bet","Hero IP","suited playable hand"],cueRu:"Undersized 3-bet, Hero IP, suited playable hand.",cueEn:"Undersized 3-bet, Hero IP, suited playable hand.",questionRu:"Какой direction supported?",questionEn:"Which direction is supported?",actionOptions:[o("a","Continue wider than vs large OOP 3-bet","Continue wider than versus a large OOP 3-bet"),o("b","Fold more because bet is smaller","Fold more because the bet is smaller","PRICE_BACKWARDS"),o("c","Use exact 50% regardless","Use exactly 50% regardless","FIFTY_AS_LAW")],reasonOptions:[o("r1","Better price and position improve realisation","Better price and position improve realization"),o("r2","Smaller bets require more equity","Smaller bets require more equity","PRICE_BACKWARDS"),o("r3","Position is irrelevant preflop","Position is irrelevant preflop","POSITION_IGNORED")],correctActionId:"a",correctReasonId:"r1",targetSeconds:25,explanationRu:"E17 explicitly widens defence versus undersized bets and in position.",explanationEn:"E17 explicitly widens defense versus undersized bets and in position."},
  {
    id:"PM-PF-07-105",skillId:"PF-07",kind:"decision",sourceRefs:["FTGU-E17"],assumptions:["call loses from hand start","call beats folding from current node"],cueRu:"После open call может быть overall losing from hand start, но лучше fold прямо сейчас.",cueEn:"After opening, a call can be losing from the start of the hand but still better than folding now.",questionRu:"Как оценивать решение?",questionEn:"How should the decision be evaluated?",actionOptions:[o("a","From current decision point","From the current decision point"),o("b","Against zero total investment","Against zero total investment","SUNK_COST_CONFUSION"),o("c","By whether hand is profitable preflop overall","By whether the hand is profitable preflop overall","WHOLE_HAND_CONFUSION")],reasonOptions:[o("r1","The open is already invested; choose highest EV among remaining actions","The open is already invested; choose the highest-EV remaining action"),o("r2","Past chips must be won back","Past chips must be won back","SUNK_COST"),o("r3","Current fold refunds the open","Current fold refunds the open","REFUND_FALSE")],correctActionId:"a",correctReasonId:"r1",targetSeconds:25,explanationRu:"E17 explicitly distinguishes point-of-decision EV from whole-hand profit.",explanationEn:"E17 explicitly distinguishes point-of-decision EV from whole-hand profit."},
  {
    id:"PM-PF-07-106",skillId:"PF-07",kind:"changed",sourceRefs:["FTGU-E17"],assumptions:["same hand/range","3-bet size increases"],cueRu:"Same hand and positions, 3-bet size increases materially.",cueEn:"Same hand and positions, the 3-bet size increases materially.",questionRu:"Как двигается defence fringe?",questionEn:"How does the defense fringe move?",actionOptions:[o("a","Tighter","Tighter"),o("b","Wider","Wider","PRICE_BACKWARDS"),o("c","Unchanged","Unchanged","SIZE_IGNORED")],reasonOptions:[o("r1","Worse price raises the bar for calls/continues","A worse price raises the bar for calls/continues"),o("r2","Bigger size creates more dead money for Hero","A bigger size creates more dead money for Hero","PRICE_MISREAD"),o("r3","Size never affects defence","Size never affects defense","SIZE_IGNORED")],correctActionId:"a",correctReasonId:"r1",targetSeconds:20,explanationRu:"Size is an explicit E17 defence variable.",explanationEn:"Size is an explicit E17 defense variable.",changedVariables:["three_bet_size"]},
  {
    id:"PM-PF-07-107",skillId:"PF-07",kind:"changed",sourceRefs:["FTGU-E17"],assumptions:["same size","Hero IP -> OOP"],cueRu:"Same 3-bet size, Hero loses position.",cueEn:"Same 3-bet size, Hero loses position.",questionRu:"Как двигается defence?",questionEn:"How does defense move?",actionOptions:[o("a","Tighter","Tighter"),o("b","Wider","Wider","POSITION_BACKWARDS"),o("c","No change","No change","POSITION_IGNORED")],reasonOptions:[o("r1","OOP lowers future realization and E17 explicitly permits more folds","OOP lowers future realization and E17 explicitly permits more folds"),o("r2","OOP improves realisation","OOP improves realization","POSITION_BACKWARDS"),o("r3","Position affects only river","Position affects only river","POSITION_IGNORED")],correctActionId:"a",correctReasonId:"r1",targetSeconds:20,explanationRu:"E17 directly changes defence by position.",explanationEn:"E17 directly changes defense by position.",changedVariables:["position"]},
  {
    id:"PM-PF-07-108",skillId:"PF-07",kind:"boundary",sourceRefs:["FTGU-E17"],assumptions:["opponent strongly underbluffs 3-bets","same nominal size"],cueRu:"Evidence показывает strongly underbluffed 3-bet range.",cueEn:"Evidence shows a strongly underbluffed 3-bet range.",questionRu:"Нужно ли защищать ballpark 50% ради 'неэксплойтабельности'?",questionEn:"Must Hero defend the ballpark 50% for 'unexploitability'?",actionOptions:[o("a","No; tighten to actual range assumptions","No; tighten to actual range assumptions"),o("b","Yes, exactly 50% always","Yes, exactly 50% always","FIFTY_AS_LAW"),o("c","Always 4-bet bluff more","Always 4-bet bluff more","UNDERBLUFF_BACKWARDS")],reasonOptions:[o("r1","E17 explicitly adjusts defence for opponent underbluffing","E17 explicitly adjusts defense for opponent underbluffing"),o("r2","Baseline frequencies override evidence","Baseline frequencies override evidence","EVIDENCE_IGNORED"),o("r3","Underbluffing creates more fold targets","Underbluffing creates more fold targets","UNDERBLUFF_BACKWARDS")],correctActionId:"a",correctReasonId:"r1",targetSeconds:28,explanationRu:"This boundary prevents the pedagogical 50% baseline from becoming a dogma.",explanationEn:"This boundary prevents the pedagogical 50% baseline from becoming dogma."},

  // PF-08 — 4-bet fundamentals. FTGU E18.
  {
    id:"PM-PF-08-101",skillId:"PF-08",kind:"recognition",sourceRefs:["FTGU-E18"],assumptions:["opponent mostly 5-bet jam or fold"],cueRu:"Opponent отвечает на 4-bet в основном jam-or-fold.",cueEn:"Opponent responds to 4-bets mostly by jamming or folding.",questionRu:"Какая structure source предпочитает?",questionEn:"Which structure does the source prefer?",actionOptions:[o("a","Polar 4-bet around protected calls","Polar 4-bet around protected calls"),o("b","4-bet every medium hand","4-bet every medium hand","MEDIUM_HAND_INFLATION"),o("c","No calls at all by definition","No calls at all by definition","CALL_RANGE_FALSE")],reasonOptions:[o("r1","Medium hands can retain more EV by calling rather than 4-bet/folding to jams","Medium hands can retain more EV by calling rather than 4-bet/folding to jams"),o("r2","Jam-or-fold opponents make medium 4-bets safest","Jam-or-fold opponents make medium 4-bets safest","BRANCH_BACKWARDS"),o("r3","Polar means no calling region","Polar means no calling region","POLAR_MISREAD")],correctActionId:"a",correctReasonId:"r1",targetSeconds:22,explanationRu:"E18 defines polar 4-betting around a protected calling region versus jam-or-fold responses.",explanationEn:"E18 defines polar 4-betting around a protected calling region versus jam-or-fold responses."},
  {
    id:"PM-PF-08-102",skillId:"PF-08",kind:"recognition",sourceRefs:["FTGU-E18"],assumptions:["Hero OOP","4-bet considered"],cueRu:"Hero OOP considers 4-bet.",cueEn:"Hero OOP considers a 4-bet.",questionRu:"Какой structural benefit besides fold equity?",questionEn:"Which structural benefit exists besides fold equity?",actionOptions:[o("a","Equity denial + lower SPR reduces positional leverage","Equity denial + lower SPR reduces positional leverage"),o("b","Hero becomes IP","Hero becomes IP","POSITION_FALSE"),o("c","Position disappears completely","Position disappears completely","ABSOLUTE_CLAIM")],reasonOptions:[o("r1","A shallower future tree can reduce how much IP compounds its advantage","A shallower future tree can reduce how much IP compounds its advantage"),o("r2","4-betting changes seats","4-betting changes seats","POSITION_FALSE"),o("r3","SPR has no strategic effect","SPR has no strategic effect","SPR_IGNORED")],correctActionId:"a",correctReasonId:"r1",targetSeconds:22,explanationRu:"E18 explicitly links more OOP 4-betting to equity denial and SPR reduction.",explanationEn:"E18 explicitly links more OOP 4-betting to equity denial and SPR reduction."},
  {
    id:"PM-PF-08-103",skillId:"PF-08",kind:"decision",sourceRefs:["FTGU-E18"],assumptions:["candidate called value 4-bet","Hero plans to fold versus assumed 5-bet range"],cueRu:"Hero хочет назвать 4-bet 'value', но против expected 5-bet собирается fold.",cueEn:"Hero wants to call the 4-bet 'value' but plans to fold versus the expected 5-bet range.",questionRu:"Что говорит source?",questionEn:"What does the source say?",actionOptions:[o("a","Reconsider value classification","Reconsider the value classification"),o("b","Still value by definition","Still value by definition","VALUE_LABEL_ONLY"),o("c","Jam regardless","Jam regardless","STACKOFF_AUTOPILOT")],reasonOptions:[o("r1","Do not 4-bet for value unless prepared to continue appropriately versus assumed 5-bet range","Do not 4-bet for value unless prepared to continue appropriately versus the assumed 5-bet range"),o("r2","Value means only ahead of opening range","Value means only ahead of the opening range","VALUE_MISREAD"),o("r3","Five-bet branch never matters","The five-bet branch never matters","FIVEBET_IGNORED")],correctActionId:"a",correctReasonId:"r1",targetSeconds:25,explanationRu:"This is an explicit E18 value-4bet boundary.",explanationEn:"This is an explicit E18 value-4bet boundary."},
  {
    id:"PM-PF-08-104",skillId:"PF-08",kind:"decision",sourceRefs:["FTGU-E18"],assumptions:["underbluffing recreational 3-bet range","few folds to bluff 4-bets"],cueRu:"Opponent 3-bets value-heavy and underbluffs; bluff 4-bets получают мало folds.",cueEn:"Opponent 3-bets value-heavy and underbluffs; bluff 4-bets get few folds.",questionRu:"Как adjust?",questionEn:"How should Hero adjust?",actionOptions:[o("a","Remove bluffs / become more value-heavy","Remove bluffs / become more value-heavy"),o("b","Add more blocker bluffs","Add more blocker bluffs","UNDERBLUFF_BACKWARDS"),o("c","Stack off wider automatically","Stack off wider automatically","STACKOFF_BACKWARDS")],reasonOptions:[o("r1","Without fold targets, polar bluffs lose their main EV source","Without fold targets, polar bluffs lose their main EV source"),o("r2","Underbluffing creates more fold equity","Underbluffing creates more fold equity","UNDERBLUFF_BACKWARDS"),o("r3","Balance overrides opponent response","Balance overrides opponent response","EVIDENCE_IGNORED")],correctActionId:"a",correctReasonId:"r1",targetSeconds:25,explanationRu:"E18 explicitly removes bluffs and tightens stack-off thresholds against underbluffing ranges.",explanationEn:"E18 explicitly removes bluffs and tightens stack-off thresholds against underbluffing ranges."},
  {
    id:"PM-PF-08-105",skillId:"PF-08",kind:"decision",sourceRefs:["FTGU-E18"],assumptions:["opponent flats 4-bets too often","rarely jams","strong value hand"],cueRu:"Opponent часто flat 4-bets и редко jam; Hero has strong value.",cueEn:"Opponent flats 4-bets too often and rarely jams; Hero has strong value.",questionRu:"Какой sizing direction source допускает?",questionEn:"Which sizing direction does the source allow?",actionOptions:[o("a","Larger value sizing can gain EV","Larger value sizing can gain EV"),o("b","Always smallest possible","Always the smallest possible","SIZE_DOGMA"),o("c","Sizing unrelated to response","Sizing is unrelated to response","OPPONENT_IGNORED")],reasonOptions:[o("r1","Frequent flats let value charge more instead of facing jam-or-fold","Frequent flats let value charge more instead of facing jam-or-fold"),o("r2","Larger size guarantees a jam","A larger size guarantees a jam","GUARANTEE_FALSE"),o("r3","Opponent branch cannot affect sizing","Opponent branch cannot affect sizing","BRANCH_IGNORED")],correctActionId:"a",correctReasonId:"r1",targetSeconds:25,explanationRu:"E18 allows larger value sizing when opponents flat too often and rarely use jam-or-fold.",explanationEn:"E18 allows larger value sizing when opponents flat too often and rarely use jam-or-fold."},
  {
    id:"PM-PF-08-106",skillId:"PF-08",kind:"changed",sourceRefs:["FTGU-E18"],assumptions:["same node","opponent balanced folds -> underbluffing value-heavy"],cueRu:"Opponent moves from fold-capable balanced response to value-heavy underbluffing.",cueEn:"Opponent moves from a fold-capable balanced response to value-heavy underbluffing.",questionRu:"Как moves bluff region?",questionEn:"How does the bluff region move?",actionOptions:[o("a","Contracts","Contracts"),o("b","Expands","Expands","UNDERBLUFF_BACKWARDS"),o("c","Unchanged","Unchanged","OPPONENT_IGNORED")],reasonOptions:[o("r1","Fewer folds remove the EV engine for blocker bluffs","Fewer folds remove the EV engine for blocker bluffs"),o("r2","Stronger ranges fold more by definition","Stronger ranges fold more by definition","RANGE_BACKWARDS"),o("r3","Bluff construction ignores fold targets","Bluff construction ignores fold targets","FOLD_TARGET_IGNORED")],correctActionId:"a",correctReasonId:"r1",targetSeconds:22,explanationRu:"E18 is branch-responsive, not balance-for-balance's-sake.",explanationEn:"E18 is branch-responsive, not balance for balance's sake.",changedVariables:["opponent_three_bet_shape","fold_equity"]},
  {
    id:"PM-PF-08-107",skillId:"PF-08",kind:"changed",sourceRefs:["FTGU-E18"],assumptions:["same hand","Hero IP -> OOP"],cueRu:"Same 4-bet candidate, Hero loses position.",cueEn:"Same 4-bet candidate, Hero loses position.",questionRu:"Какой incentive может усилиться?",questionEn:"Which incentive can strengthen?",actionOptions:[o("a","Equity denial / lower-SPR 4-bet incentive","Equity denial / lower-SPR 4-bet incentive"),o("b","Flat always becomes better","Flat always becomes better","POSITION_BACKWARDS"),o("c","Position ceases to matter","Position ceases to matter","POSITION_IGNORED")],reasonOptions:[o("r1","E18 notes OOP may prefer compressing the tree to reduce positional leverage","E18 notes OOP may prefer compressing the tree to reduce positional leverage"),o("r2","OOP automatically improves realization","OOP automatically improves realization","POSITION_BACKWARDS"),o("r3","4-bet makes Hero IP","A 4-bet makes Hero IP","POSITION_FALSE")],correctActionId:"a",correctReasonId:"r1",targetSeconds:25,explanationRu:"Directional mechanism only; no exact OOP frequency is claimed.",explanationEn:"Directional mechanism only; no exact OOP frequency is claimed.",changedVariables:["position","spr"]},
  {
    id:"PM-PF-08-108",skillId:"PF-08",kind:"boundary",sourceRefs:["FTGU-E18"],assumptions:["premium blocker bluff candidate","opponent does not fold"],cueRu:"Hand имеет красивый blocker, но opponent почти не fold to 4-bet.",cueEn:"The hand has an attractive blocker, but the opponent almost never folds to 4-bets.",questionRu:"Достаточен ли blocker?",questionEn:"Is the blocker sufficient?",actionOptions:[o("a","No","No"),o("b","Yes, blocker alone creates EV","Yes, the blocker alone creates EV","BLOCKER_AUTOPILOT"),o("c","Yes, if suited","Yes, if suited","SUITED_AUTOPILOT")],reasonOptions:[o("r1","E18 requires folds to be available for premium blocker bluffs","E18 requires folds to be available for premium blocker bluffs"),o("r2","Blockers guarantee folds","Blockers guarantee folds","BLOCKER_GUARANTEE"),o("r3","Opponent response is irrelevant","Opponent response is irrelevant","OPPONENT_IGNORED")],correctActionId:"a",correctReasonId:"r1",targetSeconds:25,explanationRu:"Blocker is a mechanism inside a response tree, not a standalone license to bluff.",explanationEn:"A blocker is a mechanism inside a response tree, not a standalone license to bluff."},
];
