import type { PracticalDecision } from "./types";

// Final high-EV content delta: bounded extension of existing skill families.
// Correct option identities stay stable; display order is intentionally varied
// so learner correctness cannot be inferred from a fixed option position.
const o = (id: string, textRu: string, textEn: string, misconception?: string) => ({ id, textRu, textEn, misconception });

export const finalContentDeltaDecisions: PracticalDecision[] = [
  {
    id: "PM-FND-06-FINAL-101", skillId: "FND-06", kind: "recognition", sourceRefs: ["FTGU-E01", "LCM-01"],
    assumptions: ["single-raised pot", "после текущего действия остаются две улицы", "для сравнения рука и доска те же"],
    cueRu: "Та же рука и та же доска, но SPR отличается от прошлой раздачи.",
    cueEn: "Same hand and same board, only SPR differs from the previous hand.",
    questionRu: "Что должно измениться вместе с SPR?", questionEn: "What should change together with SPR?",
    actionOptions: [
      o("b", "Ничего — сайзинг зависит только от структуры доски", "Nothing — sizing depends only on board texture", "SPR_IGNORED"),
      o("a", "Семейство геометрических сайзингов на оставшихся улицах", "The family of geometric sizes on the remaining streets"),
      o("c", "Ничего — сайзинг зависит только от абсолютной силы руки", "Nothing — sizing depends only on absolute hand strength", "SIZE_DOGMA"),
    ],
    reasonOptions: [
      o("r1", "Отношение эффективного остатка стека к банку задаёт долю банка, которую нужно ставить на каждой оставшейся улице, если выбран план довести деньги до олл-ина", "The remaining stack relative to the pot sets the pot fraction needed on each remaining street if the plan is to reach an all-in"),
      o("r3", "Сайзинг определяется исключительно абсолютной силой руки", "Sizing is determined solely by absolute hand strength", "SIZE_DOGMA"),
      o("r2", "Сайзинг — просто визуальная привычка под структуру доски", "Sizing is simply a visual habit tied to board texture", "GEOMETRY_IGNORED"),
    ],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 20,
    explanationRu: "LCM-01 связывает SPR с геометрическим сайзингом на будущих улицах: при той же доске другой SPR требует другой доли банка на каждой улице для одного и того же плана довести деньги до олл-ина.",
    explanationEn: "LCM-01 links SPR with the geometric size family on future streets: the same board with a different SPR requires a different pot fraction on each street for the same plan of reaching an all-in.",
  },
  {
    id: "PM-FND-06-FINAL-102", skillId: "FND-06", kind: "decision", sourceRefs: ["FTGU-E01", "LCM-01"],
    assumptions: ["SPR≈2 в момент действия", "Hero планирует олл-ин за две оставшиеся улицы", "точная solver-частота не требуется"],
    cueRu: "SPR≈2, и Hero хочет использовать одну и ту же долю текущего банка на этой улице и на следующей, чтобы естественно прийти к олл-ину.",
    cueEn: "SPR≈2, and Hero wants to use the same fraction of the current pot on this street and the next to naturally reach an all-in.",
    questionRu: "Какой класс сайзинга естественно доводит Hero до олл-ина за две улицы?", questionEn: "Which sizing class naturally gets Hero to an all-in over two streets?",
    actionOptions: [
      o("c", "Минимальные блокирующие ставки — около 20–25% банка", "Minimal blocking bets — roughly 20–25% pot", "DEPTH_IGNORED"),
      o("b", "Класс pot/pot — 100% банка на каждой улице", "The pot/pot class — 100% pot on each street", "SIZE_MEMORIZED"),
      o("a", "Класс b60/b60 — примерно 60% банка на каждой из двух улиц", "The b60/b60 class — roughly 60% pot on each of the two streets"),
    ],
    reasonOptions: [
      o("r2", "Класс pot/pot универсален для любого SPR", "The pot/pot class is universal for any SPR", "SIZE_DOGMA"),
      o("r3", "Маленький сайзинг всегда безопаснее независимо от SPR", "A small sizing is always safer regardless of SPR", "DEPTH_IGNORED"),
      o("r1", "Для одинаковой доли банка x на двух улицах SPR=2x+2x²; при SPR≈2 получаем x≈0,618, то есть ориентир около 60% банка на каждой улице", "For the same pot fraction x on two streets, SPR=2x+2x²; at SPR≈2, x≈0.618, giving an anchor of about 60% pot on each street"),
    ],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25,
    explanationRu: "Геометрия FTGU-E01/LCM-01: если ставить одинаковую долю текущего банка на обеих оставшихся улицах, SPR=2x+2x². При SPR≈2 x≈0,618, поэтому рабочий ориентир — b60/b60. Это ориентир исполнения, а не обязательный стратегический сайзинг.",
    explanationEn: "FTGU-E01/LCM-01 geometry: when betting the same fraction of the current pot on both remaining streets, SPR=2x+2x². At SPR≈2, x≈0.618, so b60/b60 is the execution anchor. It is not a mandatory strategic sizing.",
  },
  {
    id: "PM-FND-06-FINAL-103", skillId: "FND-06", kind: "decision", sourceRefs: ["FTGU-E01", "LCM-01"],
    assumptions: ["SPR≈4 в момент действия", "Hero планирует олл-ин за две оставшиеся улицы", "точная solver-частота не требуется"],
    cueRu: "SPR≈4, тот же план: использовать одну и ту же долю текущего банка на двух оставшихся улицах и прийти к олл-ину.",
    cueEn: "SPR≈4, with the same plan: use the same fraction of the current pot on both remaining streets to reach an all-in.",
    questionRu: "Какой класс сайзинга здесь ближе к нужной геометрии?", questionEn: "Which sizing class is closer to the required geometry here?",
    actionOptions: [
      o("a", "Класс pot/pot — примерно 100% банка на каждой улице", "The pot/pot class — roughly 100% pot on each street"),
      o("c", "Полный олл-ин уже на этой улице", "A full all-in already on this street", "DEPTH_MISREAD"),
      o("b", "Класс b60/b60, как при SPR≈2", "The b60/b60 class, as at SPR≈2", "SIZE_MEMORIZED"),
    ],
    reasonOptions: [
      o("r3", "SPR≈4 сам по себе уже означает немедленный олл-ин", "SPR≈4 is already immediate all-in depth by itself", "DEPTH_MISREAD"),
      o("r1", "Для одинаковой доли банка x на двух улицах SPR=2x+2x²; при SPR=4 решение x=1, то есть pot/pot", "For the same pot fraction x on two streets, SPR=2x+2x²; at SPR=4, x=1, which is pot/pot"),
      o("r2", "Один и тот же класс сайзинга подходит любому SPR", "One and the same sizing class fits any SPR", "SIZE_DOGMA"),
    ],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25,
    explanationRu: "Геометрия FTGU-E01/LCM-01: SPR=2x+2x² для одной и той же доли банка на двух улицах. При SPR=4 получаем x=1, поэтому ориентир — pot/pot.",
    explanationEn: "FTGU-E01/LCM-01 geometry: SPR=2x+2x² for the same pot fraction on two streets. At SPR=4, x=1, so the execution anchor is pot/pot.",
  },
  {
    id: "PM-FND-06-FINAL-104", skillId: "FND-06", kind: "changed", sourceRefs: ["FTGU-E01", "LCM-01"],
    assumptions: ["банк одинаков в двух сравнениях", "эффективный остаток стека удваивается", "план — олл-ин за две улицы"],
    cueRu: "Банк тот же, но эффективный остаток стека во втором сравнении вдвое больше.", cueEn: "Same pot; the remaining stack doubles from one comparison to the other.",
    questionRu: "Куда сдвигается доля банка, нужная на каждой из двух улиц?", questionEn: "Which way does the required pot fraction on each of the two streets move?",
    actionOptions: [
      o("b", "Вниз — больший остаток стека требует меньшего сайзинга", "Down — a larger remaining stack requires smaller sizing", "SPR_BACKWARDS"),
      o("c", "Не меняется — банк тот же, значит сайзинг тот же", "It stays the same — the pot is unchanged, so sizing is unchanged", "POT_IGNORED"),
      o("a", "Вверх — нужна большая доля банка на каждой улице", "Up — a larger pot fraction is needed on each street"),
    ],
    reasonOptions: [
      o("r2", "SPR зависит только от банка, а не от стека", "SPR depends only on the pot, not on the stack", "SPR_BACKWARDS"),
      o("r1", "Больший эффективный остаток при том же банке повышает SPR; из SPR=2x+2x² следует, что требуемая одинаковая доля банка x тоже растёт", "A larger remaining stack at the same pot raises SPR; from SPR=2x+2x², the required equal pot fraction x also rises"),
      o("r3", "Сайзинг связан только со структурой доски", "Sizing is tied only to board texture", "POT_IGNORED"),
    ],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 22,
    explanationRu: "Удвоение эффективного остатка стека при том же банке удваивает SPR. Для одинаковой доли банка на двух улицах x растёт вместе с SPR: ориентир меняется, например, с ≈0,62 при SPR≈2 до 1,00 при SPR=4.",
    explanationEn: "Doubling the remaining stack at the same pot doubles SPR. For the same pot fraction on both streets, x rises with SPR: for example, from ≈0.62 at SPR≈2 to 1.00 at SPR=4.",
    changedVariables: ["effective_stack", "spr"],
  },
  {
    id: "PM-FND-06-FINAL-105", skillId: "FND-06", kind: "boundary", sourceRefs: ["FTGU-E01", "LCM-01"],
    assumptions: ["SPR≈3 в момент действия", "у Hero нет преимущества по натсам", "нет худших рук, готовых платить выбранный сайзинг"],
    cueRu: "SPR≈3 хорошо подходит для геометрического плана на две улицы, но у Hero нет преимущества по натсам и нет худших рук, готовых платить выбранный сайзинг.",
    cueEn: "SPR≈3 fits a geometric two-street plan nicely, but Hero has no nut advantage and no worse hands that would pay the chosen sizing.",
    questionRu: "Значит ли подходящий SPR, что здесь нужно ставить?", questionEn: "Does a suitable SPR mean Hero should bet here?",
    actionOptions: [
      o("c", "Да — если сайзинг естественно доводит до олл-ина, стек-офф всегда оправдан", "Yes — since the sizing naturally reaches the stacks, stacking off is always justified", "STACKOFF_AUTOPILOT"),
      o("a", "Нет — геометрия определяет размер только после того, как уже есть стратегическая причина ставить", "No — geometry determines the size only after there is a strategic reason to bet"),
      o("b", "Да — подходящий SPR сам по себе достаточная причина ставить", "Yes — a suitable SPR is itself sufficient reason to bet", "GEOMETRY_AS_REASON"),
    ],
    reasonOptions: [
      o("r1", "Преимущество по натсам, роль руки и наличие худших рук для оплаты решают, нужна ли ставка; геометрия только задаёт способ распределить ставки по банку после этого решения", "Nut ownership, hand role and worse hands that can pay decide whether to bet; geometry only determines how to size after that decision"),
      o("r2", "Любой подходящий SPR создаёт причину для агрессии", "Any suitable SPR creates a reason for aggression", "GEOMETRY_AS_REASON"),
      o("r3", "Само семейство сайзингов создаёт fold equity против любого диапазона", "The sizing family itself creates fold equity against any range", "STACKOFF_AUTOPILOT"),
    ],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 28,
    explanationRu: "Граница правила: геометрический сайзинг описывает, какую долю банка ставить по улицам, если ставка уже стратегически оправдана. Сам подходящий SPR не создаёт причину ставить без преимущества по натсам, цели для вэлью или другой стратегической работы ставки.",
    explanationEn: "Boundary: geometric sizing describes what pot fraction to use across streets once betting is strategically justified. A suitable SPR does not itself create a reason to bet without nut advantage, a value target, or another strategic job for the bet.",
  },
  {
    id: "PM-FND-06-FINAL-106", skillId: "FND-06", kind: "changed", sourceRefs: ["FTGU-E01", "LCM-01"],
    assumptions: ["стартовая глубина 200bb", "экшен префлоп и на флопе уже уменьшил эффективный остаток", "к терну текущий SPR≈2"],
    cueRu: "Раздача началась на глубине 200bb, но экшен префлоп и на флопе уже уменьшил эффективный остаток; к терну текущий SPR≈2.",
    cueEn: "The hand started at 200bb, but preflop and flop action already compressed the remaining stack; by the turn, current SPR≈2.",
    questionRu: "Какой SPR должен определять план сайзинга на две улицы с терна?", questionEn: "Which SPR should determine the two-street sizing plan on the turn?",
    actionOptions: [
      o("a", "Текущий SPR≈2 в этот момент", "Current SPR≈2 at this point"),
      o("b", "Стартовая глубина 200bb", "The headline 200bb starting depth", "NOMINAL_STACK_ONLY"),
      o("c", "Среднее между стартовой глубиной и текущим SPR", "An average between the starting depth and current SPR", "DEPTH_MISREAD"),
    ],
    reasonOptions: [
      o("r3", "План сайзинга должен усреднять весь путь раздачи", "The sizing plan should average the whole path of the hand", "DEPTH_MISREAD"),
      o("r2", "Стартовая глубина 200bb гарантирует много будущих улиц независимо от экшена", "A 200bb starting depth guarantees many future streets regardless of the action", "NOMINAL_STACK_ONLY"),
      o("r1", "Геометрия строится на текущем эффективном остатке и текущем банке, а не на количестве фишек в начале раздачи", "Geometry is built on the remaining stack and pot right now, not on how much was there at the start of the hand"),
    ],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 26,
    explanationRu: "LCM-01: стартовые 200bb не задают рабочую геометрию на терне. После префлоп- и флоп-экшена текущий SPR≈2, поэтому ориентир для одинаковой доли банка на двух улицах — x≈0,62, то есть класс b60/b60.",
    explanationEn: "LCM-01: nominal 200bb does not determine the turn geometry. After preflop and flop action, current SPR≈2, so the equal-pot-fraction two-street anchor is x≈0.62, the b60/b60 class.",
    changedVariables: ["effective_stack", "spr"],
  },
  {
    id: "PM-OOP-03-FINAL-101", skillId: "OOP-03", kind: "boundary", sourceRefs: ["FTGU-E09", "FTGU-E10"],
    assumptions: ["Hero поставил c-bet на флопе и получил рейз", "проверяется универсальный лозунг о рейзах флопа"],
    cueRu: "Hero ставит c-bet на флопе и получает рейз. Возникает соблазн применить правило: любой рейз флопа всегда означает сильный диапазон.",
    cueEn: "Hero c-bet the flop and got raised. The learner wants to apply one universal slogan: any flop raise is always strong.",
    questionRu: "Это верный подход?", questionEn: "Is that approach correct?",
    actionOptions: [
      o("b", "Да — рейз почти никогда не бывает богат блефами", "Yes — a raise is almost never bluff-heavy", "RAISE_ALWAYS_STRONG"),
      o("c", "Да — маленький c-bet всегда получает более сильный диапазон рейза, чем крупный", "Yes — a small c-bet always draws a stronger raising range than a large one", "SIZE_RESPONSE_BACKWARDS"),
      o("a", "Нет — состав диапазона рейза зависит от размера c-bet и структуры доски", "No — the raising range's composition depends on the c-bet size and the board"),
    ],
    reasonOptions: [
      o("r2", "Диапазон рейза всегда один и тот же независимо от сайзинга", "The raising range is always the same regardless of sizing", "SIZE_RESPONSE_BACKWARDS"),
      o("r1", "Рейз против маленького частого c-bet может идти из более широкого региона, чем против крупного выборочного c-bet; структура доски дополнительно определяет доступные сильные руки и блефы", "A raise against a tiny/frequent c-bet can come from a wider region than a raise against a large/selective c-bet, and the board constrains strong hands and bluffs"),
      o("r3", "После рейза важна только абсолютная сила руки Hero", "Only Hero's absolute hand strength matters after the raise", "ABSOLUTE_HAND_ONLY"),
    ],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 28,
    explanationRu: "FTGU-E09/E10: диапазон рейза зависит от срочности, владения сильными комбинациями на этой доске и размера предыдущей ставки. Универсальный ярлык «рейз = всегда сила» слишком груб.",
    explanationEn: "FTGU-E09/E10: the raising range depends on urgency, board ownership and the previous bet size. A universal 'raise equals strength' label is too crude.",
  },
  {
    id: "PM-OOP-03-FINAL-102", skillId: "OOP-03", kind: "changed", sourceRefs: ["FTGU-E09", "FTGU-E10"],
    assumptions: ["рука, доска и оппонент те же", "Hero ставит c-bet и получает рейз", "меняется только размер c-bet"],
    cueRu: "Рука, доска и оппонент те же; меняется только размер c-bet Hero — с малого на крупный. В обоих случаях Hero получает рейз.",
    cueEn: "Same hand, board and opponent; only Hero's c-bet size changes — from small to large — and both times Hero gets raised.",
    questionRu: "Что должно измениться в оценке диапазона рейза?", questionEn: "What should change in the assessment of the raising range after this switch?",
    actionOptions: [
      o("a", "Состав диапазона рейза: против малого c-bet он обычно шире, против крупного — уже и сильнее", "The raising range's composition — against a small c-bet it is usually wider and softer, against a large one it is narrower and stronger"),
      o("c", "Только pot odds на колл; состав диапазона рейза не меняется", "Only the pot odds for calling; the raising range's composition does not change", "SIZE_IGNORED"),
      o("b", "Ничего — рейз остаётся тем же событием независимо от предыдущего сайзинга", "Nothing — a raise is a raise regardless of the previous sizing", "SIZE_IGNORED"),
    ],
    reasonOptions: [
      o("r1", "Размер c-bet — часть ветки: он меняет набор рук, которые выгодно рейзят, и степень поляризации диапазона", "The c-bet size is part of the branch: it changes which hands profitably raise and how polar that range is"),
      o("r3", "После рейза имеет значение только абсолютная сила руки Hero", "Only Hero's absolute hand matters after a raise", "ABSOLUTE_HAND_ONLY"),
      o("r2", "Диапазон рейза оппонента фиксирован заранее и не зависит от сайзинга Hero", "The opponent's raising range is fixed in advance and independent of Hero's sizing", "SIZE_IGNORED"),
    ],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 26,
    explanationRu: "FTGU-E09/E10: размер c-bet — часть идентичности узла. Рейз против частого малого c-bet и рейз против выборочного крупного c-bet формируются из разных регионов диапазона даже при той же руке, доске и оппоненте.",
    explanationEn: "FTGU-E09/E10: the c-bet size is part of node identity. A raise against a high-frequency small c-bet and a raise against a selective large c-bet come from different regions, even with the same hand, board and opponent.",
    changedVariables: ["bet_size", "raising_range_shape"],
  },
  {
    id: "PM-OOP-03-FINAL-103", skillId: "OOP-03", kind: "changed", sourceRefs: ["FTGU-E09", "FTGU-E10"],
    assumptions: ["рука, сайзинг и оппонент те же", "Hero получает рейз на разных досках"],
    cueRu: "Рука, сайзинг и оппонент те же; доска меняется с сухой высокой на низкую связанную. В обоих случаях Hero получает рейз.",
    cueEn: "Same hand, same sizing, same opponent; the board changes from dry high-card to low connected, and both times Hero gets raised.",
    questionRu: "Как владение сильными комбинациями на доске влияет на диапазон рейза?", questionEn: "How does board ownership affect how legitimately strong this raising range can be?",
    actionOptions: [
      o("c", "Сухая высокая доска всегда даёт более сильный диапазон рейза, чем низкая связанная", "A dry high board always gives a stronger raising range than a low connected one", "BOARD_LABEL_SHORTCUT"),
      o("a", "Низкая связанная доска поддерживает больше действительно сильных рейзов, чем сухая высокая, где коллер покрывает меньше сильных комбинаций", "A low connected board supports more genuinely strong raises than a dry high board, where the caller-friendly region is smaller"),
      o("b", "Структура доски не влияет на диапазон рейза", "Board texture does not affect the raising range", "BOARD_IGNORED"),
    ],
    reasonOptions: [
      o("r3", "Высокие карты всегда создают больше сильных рук, чем низкие", "High cards always create more strong hands than low cards", "BOARD_LABEL_SHORTCUT"),
      o("r2", "Доска — только визуальный ярлык без влияния на диапазон", "The board is just a visual label without influence on the range", "BOARD_IGNORED"),
      o("r1", "Структура доски определяет, у кого реально есть сильные готовые руки и комбо-дро для рейза; доска, лучше подходящая коллеру, расширяет этот регион", "Board ownership determines who genuinely has strong made hands and combo draws for a raise; a caller-friendly board widens that region"),
    ],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 28,
    explanationRu: "FTGU-E09/E10: структура доски — часть построения диапазона рейза. Низкие связанные доски чаще дают коллеру больше сильных готовых рук и комбо-дро, чем сухие высокие доски.",
    explanationEn: "FTGU-E09/E10: board ownership is part of raise construction. Low connected boards are more often caller-friendly and support more legitimately strong raises than dry high boards.",
    changedVariables: ["board_class", "raiser_range_ownership"],
  },
  {
    id: "PM-OOP-03-FINAL-104", skillId: "OOP-03", kind: "changed", sourceRefs: ["FTGU-E09", "FTGU-E10", "SLC-CHECK-RAISE"],
    assumptions: ["рука, доска и сайзинг те же", "меняется только накопленный профиль оппонента"],
    cueRu: "Рука, доска и сайзинг те же. В одном случае оппонент неизвестный или агрессивный; в другом накопленные наблюдения в этой же ветке показывают пассивного недоблефовывающего игрока.",
    cueEn: "Same hand, board and sizing. In one case the opponent is unknown/aggressive; in the other, observations in this same branch show a passive underbluffer with few bluff raises.",
    questionRu: "Как должен измениться диапазон продолжения Hero против пассивного недоблефовывающего игрока?", questionEn: "How should Hero's continuing region shift against a passive underbluffer?",
    actionOptions: [
      o("b", "Не меняется — одна и та же ветка должна разыгрываться одинаково", "It does not change — the same branch should be played identically", "PROFILE_IGNORED"),
      o("a", "Заметно сужается — bluff-catchers и пограничные продолжения теряют ценность против диапазона с малым числом блефов", "Materially tighter — bluff-catchers and marginal continues lose value against a range with few bluffs"),
      o("c", "Расширяется — против пассивного игрока всегда выгодно продолжать больше рук", "Wider — against a passive opponent it always pays to continue more hands", "PASSIVE_ALWAYS_WEAKER"),
    ],
    reasonOptions: [
      o("r2", "Один наблюдённый случай уже доказывает постоянный ярлык игрока", "One observed case already proves a permanent player label", "EVIDENCE_OVERGENERALIZED"),
      o("r3", "Профиль оппонента не связан с количеством блефов в этой ветке", "The opponent's profile is unrelated to the bluff supply in this branch", "PROFILE_IGNORED"),
      o("r1", "Диапазон продолжения строится против реального количества блефов; устойчивые наблюдения именно в этой ветке снижают ожидаемую частоту блефа и делают пограничные коллы хуже", "The continuing region is built against the actual bluff supply; stable observations in this branch lower the expected bluff count and make marginal calls worse"),
    ],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 28,
    explanationRu: "Наблюдения, относящиеся именно к этой ветке, материально сдвигают порог продолжения: если пассивный игрок здесь недоблефовывает, в диапазоне рейза меньше реальных блефов и пограничные bluff-catchers нужно коллировать реже.",
    explanationEn: "Branch-specific observations materially shift the continuing threshold: a passive underbluffer leaves fewer real bluffs in the raising range, so marginal bluff-catchers become less profitable calls.",
    changedVariables: ["opponent_profile", "bluff_supply"],
  },
  {
    id: "PM-TURN-02-FINAL-101", skillId: "TURN-02", kind: "recognition", sourceRefs: ["FTGU-E21", "SLC-TURN-BARREL"],
    assumptions: ["Hero поставил c-bet на флопе, получил колл, поставил терн и получил рейз", "источник анализа — диапазон, переживший колл флопа"],
    cueRu: "Hero ставит c-bet на флопе, получает колл, затем ставит на терне и получает рейз.", cueEn: "Hero c-bet the flop, got called, bet the turn and got raised.",
    questionRu: "С какого диапазона нужно начинать разбор рейза на терне?", questionEn: "Which range should the turn raising-range analysis start from?",
    actionOptions: [
      o("a", "С диапазона, который действительно пережил колл флопа, а не с исходного префлоп-диапазона", "The range that actually survived the flop call, not the original preflop range"),
      o("b", "С исходного префлоп-диапазона целиком", "The original preflop range as a whole", "ANCESTRY_IGNORED"),
      o("c", "Только с абсолютной силы руки Hero, без учёта диапазона оппонента", "Hero's absolute hand without considering the opponent's range at all", "RANGE_HISTORY_IGNORED"),
    ],
    reasonOptions: [
      o("r2", "Префлоп-роль сама определяет действие на терне", "Preflop identity by itself decides the turn action", "ANCESTRY_IGNORED"),
      o("r1", "Колл флопа уже отфильтровал префлоп-диапазон; рейзить терн могут только руки, которые реально дошли до этого узла", "The flop call already filtered the preflop range; only hands that actually reached this node can raise the turn"),
      o("r3", "История улиц не влияет на текущий узел", "Street history does not affect the current node", "RANGE_HISTORY_IGNORED"),
    ],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25,
    explanationRu: "FTGU-E21: решения поздних улиц зависят от контекста. Диапазон рейза на терне строится из рук, которые действительно пережили колл флопа, а не из исходного префлоп-диапазона.",
    explanationEn: "FTGU-E21: later-street classes are contextual. The turn raising range is built from hands that actually survived the flop call, not from the original preflop range.",
  },
  {
    id: "PM-TURN-02-FINAL-102", skillId: "TURN-02", kind: "changed", sourceRefs: ["FTGU-E21", "SLC-TURN-BARREL"],
    assumptions: ["рука и сайзинг на терне те же", "меняется только накопленный профиль оппонента"],
    cueRu: "Рука и сайзинг на терне те же. В одном случае оппонент доказанно агрессивно рейзит терны; в другом наблюдения в этой ветке показывают пассивного недоблефовывающего игрока.",
    cueEn: "Same hand and sizing on the turn. In one case the opponent is a proven aggressive raiser with a history of turn raises; in the other, observations in the same branch show a passive underbluffer.",
    questionRu: "Как должен измениться ответ Hero против пассивного недоблефовывающего игрока?", questionEn: "How should Hero's response shift against the passive underbluffer?",
    actionOptions: [
      o("c", "Расшириться — против пассивного игрока Hero всегда должен продолжать больше", "Wider — against a passive opponent Hero should always continue more", "PASSIVE_ALWAYS_WEAKER"),
      o("b", "Остаться тем же — сайзинг и рука не изменились", "The same in both cases — the sizing and hand are unchanged", "PROFILE_IGNORED"),
      o("a", "Заметно сузиться — меньше bluff-catchers продолжают против диапазона с малым числом естественных блефов", "Materially tighter — fewer bluff-catchers continue against a range with few natural bluffs"),
    ],
    reasonOptions: [
      o("r1", "Наблюдения в конкретной ветке напрямую меняют оценку количества естественных блефов; меньше блефов — уже диапазон продолжения при той же цене", "A branch-specific profile directly changes the natural bluff supply; fewer bluffs mean a tighter continuing region at the same price"),
      o("r3", "Пассивный стиль гарантирует меньше вэлью в диапазоне рейза", "A passive style guarantees less value in the raising range", "PASSIVE_ALWAYS_WEAKER"),
      o("r2", "Профиль игрока не связан с составом диапазона рейза", "Player profile is unrelated to the raising range's composition", "PROFILE_IGNORED"),
    ],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 28,
    explanationRu: "При той же руке и цене устойчивые наблюдения в этой ветке меняют ожидаемое количество естественных блефов, а значит и порог продолжения.",
    explanationEn: "With the same hand and price, stable observations in this branch change the expected natural bluff supply and therefore the continuing threshold.",
    changedVariables: ["opponent_profile", "bluff_supply"],
  },
  {
    id: "PM-TURN-02-FINAL-103", skillId: "TURN-02", kind: "changed", sourceRefs: ["FTGU-E21", "SLC-TURN-BARREL"],
    assumptions: ["диапазон после колла флопа тот же", "меняется только карта терна"],
    cueRu: "После того же колла флопа на терне приходит либо бланк, либо карта, которая заметно усиливает диапазон коллера: закрывает дро или возвращает ему сильные комбинации.",
    cueEn: "After the same flop call, the turn brings either a brick or a card that materially strengthens the caller's range by completing draws or restoring strong combinations.",
    questionRu: "Как карта терна влияет на возможную силу диапазона рейза?", questionEn: "How does the turn card affect how threatening a raise can be?",
    actionOptions: [
      o("b", "Карта терна не влияет — рейз остаётся рейзом", "The turn card does not matter — a raise is a raise", "RUNOUT_IGNORED"),
      o("a", "Карта, усиливающая диапазон коллера, делает сильные рейзы и естественные полублефы правдоподобнее, чем бланк", "A card that strengthens the caller's range makes strong raises and natural semi-bluffs more plausible than a brick"),
      o("c", "Бланк всегда опаснее, потому что его не ждали", "A brick is always more dangerous because it was not expected", "SURPRISE_EQUALS_STRENGTH"),
    ],
    reasonOptions: [
      o("r3", "Неожиданная карта сама по себе создаёт силу диапазона", "An unexpected card creates strength by itself", "SURPRISE_EQUALS_STRENGTH"),
      o("r2", "Карта терна влияет только на размер банка, но не на состав диапазона", "The turn card affects only the pot size, not the range composition", "RUNOUT_IGNORED"),
      o("r1", "Карта, которая закрывает дро или возвращает сильные комбинации диапазону коллера, добавляет реальные сильные руки и естественные блефы в диапазон рейза; бланк этого не делает", "A card that completes a draw or restores strong combinations to the caller adds genuine strong hands and natural bluffs to the raising range; a brick does not"),
    ],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 27,
    explanationRu: "FTGU-E21: класс ранаута меняет выживший диапазон. Терн, который закрывает дро или возвращает сильные комбинации коллеру, делает сильные рейзы и естественные блефы правдоподобнее; бланк такого усиления не даёт.",
    explanationEn: "FTGU-E21: the runout class changes the surviving range. A turn that completes draws or restores strong combinations to the caller makes strong raises and natural bluffs more plausible; a brick does not provide that reinforcement.",
    changedVariables: ["turn_card", "caller_range_repair"],
  },
  {
    id: "PM-TURN-02-FINAL-104", skillId: "TURN-02", kind: "boundary", sourceRefs: ["FTGU-E21", "SLC-TURN-BARREL"],
    assumptions: ["Hero уже вложил крупный колл на флопе и ставку на терне", "при текущем SPR продолжение против рейза дорого"],
    cueRu: "Hero уже вложил крупный колл на флопе и ставку на терне; теперь рейз делает продолжение особенно дорогим при текущем SPR.", cueEn: "Hero already committed a large call on the flop and a bet on the turn; now the turn raise makes continuing especially expensive at the current SPR.",
    questionRu: "Оправдывают ли уже вложенные фишки более широкий диапазон продолжения?", questionEn: "Do the chips Hero already committed justify a wider continuing range here?",
    actionOptions: [
      o("c", "Да — иначе прошлые ставки пропадут зря", "Yes — otherwise the earlier bets are wasted", "SUNK_COST_AS_EQUITY"),
      o("b", "Да — крупные прошлые вложения обязывают продолжать", "Yes — a large prior investment obligates Hero to continue", "SUNK_COST_AS_EQUITY"),
      o("a", "Нет — решение зависит от текущего диапазона и текущей цены, а не от уже вложенных фишек", "No — the decision depends on the current range and price, not on how much is already committed"),
    ],
    reasonOptions: [
      o("r2", "Больше вложенных фишек означает больше equity в текущей раздаче", "More committed chips mean more equity in the current hand", "SUNK_COST_AS_EQUITY"),
      o("r3", "Большие прошлые вложения автоматически превращают fold в ошибку", "A large prior investment automatically turns a fold into a mistake", "SUNK_COST_AS_EQUITY"),
      o("r1", "Уже вложенные фишки — невозвратные издержки, а не equity; продолжение зависит от текущего диапазона соперника и цены колла сейчас", "Chips already committed are sunk cost, not equity; continuing depends on the opponent's current range and the call price now"),
    ],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30,
    explanationRu: "Граница правила: уже вложенные фишки — невозвратные издержки, а не equity. Прошлые вложения не входят в текущий расчёт цены и диапазона.",
    explanationEn: "Boundary: chips already committed are sunk cost, not equity. Prior investment does not enter the current price/range calculation.",
  },
  {
    id: "PM-W4-BOARD-01-FINAL-101", skillId: "W4-BOARD-01", kind: "recognition", sourceRefs: ["FTGU-E07", "SLC-SRP-BOARD-CLASSES"],
    assumptions: ["префлоп-роли те же", "доска меняется с высокой rainbow на высокую monotone"],
    cueRu: "Префлоп-роли те же; доска меняется с K83 rainbow на K♠8♠3♠ monotone.", cueEn: "Same preflop role in both hands; the board changes from K83 rainbow to K♠8♠3♠ monotone.",
    questionRu: "Что Hero должен пересчитать первым на monotone-доске?", questionEn: "What should Hero first recompute on a monotone board?",
    actionOptions: [
      o("a", "Распределение флешей, натсов и комбинаций с одной картой нужной масти", "The flush/nut potential distribution and who holds one-card-suit holdings"),
      o("c", "Только абсолютный ранг руки Hero, без учёта мастей", "Only Hero's absolute hand rank, without considering suits at all", "SUIT_IGNORED"),
      o("b", "Ничего — это всё ещё высокая доска, масти не важны", "Nothing — the board class is still the same high-card class; suits do not matter", "SUIT_IGNORED"),
    ],
    reasonOptions: [
      o("r3", "Сам факт высокой карты определяет преимущество диапазона независимо от мастей", "High-card texture by itself decides range advantage regardless of suits", "BOARD_LABEL_SHORTCUT"),
      o("r1", "Monotone-доска заметно меняет распределение натсов: флеши и комбинации с одной картой нужной масти становятся важной частью сильного региона, а пограничные готовые руки хуже переносят большой банк", "A monotone board materially changes the nut distribution: flushes and one-card-suit holdings become important in the strong region, while marginal made hands are less comfortable building a large pot"),
      o("r2", "Одна масть на доске не меняет комбинаторику диапазонов", "One suit on the board does not change range combinatorics", "SUIT_IGNORED"),
    ],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25,
    explanationRu: "SLC-SRP-BOARD-CLASSES: monotone — отдельный класс досок. Распределение натсов сдвигается к флешам и комбинациям с одной картой нужной масти, поэтому пограничные вэлью-руки чаще предпочитают меньший банк, чем на rainbow-доске той же высоты.",
    explanationEn: "FTGU-E07/SLC-SRP-BOARD-CLASSES: monotone is a distinct board class. Nut distribution shifts toward flushes and one-card-suit holdings, so marginal value more often prefers a smaller pot than on a rainbow board with the same high-card label.",
    changedVariables: ["board_class", "nut_distribution"],
  },
  {
    id: "PM-W4-BOARD-01-FINAL-102", skillId: "W4-BOARD-01", kind: "boundary", sourceRefs: ["FTGU-E07", "SLC-SRP-BOARD-CLASSES"],
    assumptions: ["проверяется универсальный ярлык «monotone = всегда check»"],
    cueRu: "Возникает упрощённое правило: на любой monotone-доске правильный default — всегда check.", cueEn: "The learner hears the word 'monotone' and decides: on any monotone board the correct default is always to check.",
    questionRu: "Это верная эвристика?", questionEn: "Is that a correct heuristic?",
    actionOptions: [
      o("b", "Да — monotone-доска полностью исключает ставки", "Yes — a monotone board completely rules out betting", "LABEL_AS_LAW"),
      o("a", "Нет — стимул к чеку обычно растёт, но small-bet и value-линии всё ещё зависят от дошедших диапазонов и роли", "No — the checking incentive usually rises, but small-bet and value lines still depend on the arriving ranges and role"),
      o("c", "Да — единственная безопасная линия здесь check-fold", "Yes — the only safe line here is check-fold", "LABEL_AS_LAW"),
    ],
    reasonOptions: [
      o("r2", "Одно слово monotone полностью определяет стратегию", "The single word 'monotone' fully determines the whole strategy", "LABEL_AS_LAW"),
      o("r3", "Мастевая структура отменяет необходимость анализа диапазонов", "Suit texture eliminates the need for range analysis", "LABEL_AS_STRATEGY"),
      o("r1", "Monotone повышает стимул к чеку во многих узлах, но префлоп-преимущество диапазона, роль и владение флешевым регионом всё ещё определяют, где сохраняется смысл small-bet или value-линии", "Monotone raises the checking incentive in many nodes, but preflop range advantage, role and flush-region ownership still determine where a small-bet or value line makes sense"),
    ],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 28,
    explanationRu: "Граница правила: «monotone = всегда check» неверно. Класс доски меняет распределение сильных комбинаций и стимулы, но не заменяет анализ реально дошедших диапазонов и роли в конкретном узле.",
    explanationEn: "Boundary: 'monotone equals always check' is wrong. The board class changes strong-combination distribution and incentives, but it does not replace analysis of the arriving ranges and role at the specific node.",
  },
  {
    id: "PM-3BP-05-FINAL-101", skillId: "3BP-05", kind: "changed", sourceRefs: ["FTGU-E28", "FTGU-E29"],
    assumptions: ["роль в 3-bet pot и префлоп-история те же", "доска меняется с высокой rainbow на высокую monotone"],
    cueRu: "Роль в 3-bet pot и префлоп-история те же; доска меняется с высокой rainbow на высокую monotone.", cueEn: "Same 3-bet-pot role and the same preflop history; the board changes from rainbow high to monotone high.",
    questionRu: "Как меняется возможность широко использовать small-bet при таком переходе?", questionEn: "How does the license for a wide small-bet range change with this shift?",
    actionOptions: [
      o("c", "Расширяется — monotone-доска всегда даёт большему числу рук натсовый статус", "It widens — a monotone board always gives more hands nut status", "BOARD_LABEL_SHORTCUT"),
      o("a", "Сужается — натсовый регион смещается к флешам, и часть прежних кандидатов на small-bet хуже защищена", "It narrows — the nut region shifts toward flushes, and part of the prior small-bet candidates lose comfortable protection"),
      o("b", "Не меняется — роль в 3-bet pot заранее фиксирует стратегию", "It does not change — the 3BP role already fixed the strategy in advance", "BOARD_IGNORED"),
    ],
    reasonOptions: [
      o("r1", "Роль в 3-bet pot задаёт префлоп-исходную точку, но владение натсами и возможность широкого small-bet всё равно пересчитываются под класс доски; monotone смещает часть натсового региона к флешам", "The 3BP role sets the preflop starting point, but nut ownership and wide small-bet license are still recomputed for the board class; monotone shifts part of the nut region toward flushes"),
      o("r3", "Мастевая структура автоматически расширяет натсовый регион агрессора", "Suit texture automatically widens the nut region for the aggressor", "BOARD_LABEL_SHORTCUT"),
      o("r2", "Доска никогда не меняет дерево решений в 3-bet pot", "The board never changes 3-bet-pot role trees", "BOARD_IGNORED"),
    ],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 28,
    explanationRu: "3BP-05 переносит ролевое дерево между классами досок, и monotone — один из них. Владение натсами и допустимая ширина small-bet меняются вместе с доской, даже если роль и префлоп-история неизменны.",
    explanationEn: "3BP-05 transfers role trees between board classes; monotone is one of them. Nut ownership and the small-bet license shift with the board even when role and preflop history are unchanged.",
    changedVariables: ["board_class", "nut_distribution"],
  },
];
