import type { PracticalDecision } from "./types";

const o = (id: string, textRu: string, textEn: string, misconception?: string) => ({ id, textRu, textEn, misconception });
const d = (id: string, skillId: string, kind: PracticalDecision["kind"], sourceRefs: string[], cueRu: string, cueEn: string, questionRu: string, questionEn: string, goodRu: string, goodEn: string, whyRu: string, whyEn: string, badRu: string, badEn: string, changedVariables?: string[]): PracticalDecision => ({
  id, skillId, kind, sourceRefs, assumptions: [], cueRu, cueEn, questionRu, questionEn,
  actionOptions: [o("a", goodRu, goodEn), o("b", badRu, badEn, "TARGET_REACHABILITY_DISTRACTOR"), o("c", "Нужна другая причинная проверка", "A different causal check is required", "TARGET_REACHABILITY_DISTRACTOR")],
  reasonOptions: [o("r1", whyRu, whyEn), o("r2", "Исходного примера достаточно, потому что новое условие не меняет механизм", "The original example is enough because the new condition does not change the mechanism", "MEMORIZATION_SHORTCUT"), o("r3", "Контекст линии можно игнорировать, если название ситуации осталось тем же", "The line context can be ignored when the situation keeps the same label", "CONTEXT_IGNORED")],
  correctActionId: "a", correctReasonId: "r1", targetSeconds: 25, explanationRu: whyRu, explanationEn: whyEn, changedVariables,
});

export const targetReachabilityClosureDecisions: PracticalDecision[] = [
  d("PM-FND-05-TRC-101","FND-05","recognition",["FTGU-E11"],"На флопе часть карт уже видна.","Some cards are visible on the flop.","Что происходит с исходным числом комбинаций?","What happens to the starting combo count?","Убираем комбинации, содержащие известные карты","Remove combos containing known cards","Известные карты удаляют содержащие их комбинации из доступного диапазона.","Known cards remove combinations containing them from the available range.","Оставляем исходное число префлоп-комбинаций","Keep the original preflop count"),
  d("PM-FND-05-TRC-102","FND-05","decision",["FTGU-E11"],"Два диапазона содержат одинаковое число сильных комбинаций, но один исходный диапазон намного уже.","Two ranges contain the same number of strong combos, but one starting range is much narrower.","Как сравнивать их вес?","How should their weight be compared?","Относительно размера исходного диапазона","Relative to the size of the starting range","Вес сильной части зависит от её доли в исходном диапазоне.","The weight of a strong region depends on its share of the starting range.","Считать абсолютное число достаточным","Treat the absolute count as sufficient"),
  d("PM-FND-05-TRC-103","FND-05","decision",["FTGU-E11","FTGU-E13"],"В диапазоне на ривере есть вэлью-руки и блеф-кандидаты.","A river range contains value and bluff candidates.","Что проверить до вывода о балансе?","What should be checked before judging balance?","Посчитать оставшиеся вэлью- и блеф-комбинации после исключения недоступных карт","Count surviving value and bluff combos after removal","Подсчёт оставшихся вэлью- и блеф-комбинаций показывает их реальное соотношение в этой линии.","Counting surviving value and bluff combos reveals their actual ratio in this line.","Сравнить только названия классов рук","Compare hand-class labels only"),
  d("PM-FND-05-TRC-104","FND-05","decision",["FTGU-E13"],"Одна и та же карта рассматривается для блефа и блеф-кетча.","The same card is considered for a bluff and a bluff-catch.","Одинаково ли качество её блокера?","Is its blocker quality the same?","Нет, роль зависит от действия и целевого диапазона","No; its role depends on the action and target range","Эффект блокера зависит от того, какие руки мы хотим убрать или сохранить для выбранного действия.","Blocker effect depends on which hands the chosen action wants to remove or preserve.","Да, хороший блокер универсален","Yes; a good blocker is universal"),
  d("PM-FND-05-TRC-105","FND-05","changed",["FTGU-E11"],"На следующей улице появилась карта, удаляющая часть прежнего вэлью-диапазона.","The next street removes part of the previous value region.","Что делать с подсчётом?","What should happen to the count?","Пересчитать оставшиеся комбинации","Recount the surviving combinations","Новая известная карта меняет оставшийся диапазон, поэтому комбинации нужно пересчитать.","A newly known card changes the surviving range, so the combinations must be recounted.","Сохранить предыдущий подсчёт", "Keep the previous count",["board_card","card_removal"]),
  d("PM-FND-05-TRC-106","FND-05","changed",["FTGU-E13"],"Та же карта у Hero, но задача меняется с блеф-кетча на вэлью-бет.","Hero holds the same card, but the task changes from bluff-catching to value betting.","Переносится ли вывод о блокере автоматически?","Does the blocker conclusion transfer automatically?","Нет, заново оценить блокеры против нового целевого диапазона","No; re-evaluate removal against the new target range","Смена действия меняет целевой диапазон и вместе с ним смысл блокеров.","Changing the action changes the target range and therefore the meaning of removal.","Да, эффект блокера имеет фиксированный знак", "Yes; blocker quality has a fixed sign",["action_role","target_range"]),

  d("PM-FND-07-TRC-101","FND-07","recognition",["FTGU-E01"],"Риск 1, выигрыш при успехе 2; дальнейших решений нет.","Risk 1 to win 2; no future action remains.","Нужно ли выигрывать половину раз?","Must the call win half the time?","Нет, порог безубыточности около одной трети","No; the break-even threshold is about one third","При риске 1 ради выигрыша 2 порог безубыточности составляет примерно одну треть.","Risking 1 to win 2 gives a break-even threshold of about one third.","Да, любой колл требует 50%","Yes; every call requires 50%"),
  d("PM-FND-07-TRC-102","FND-07","recognition",["FTGU-E01"],"После решения остаются несколько улиц и глубокий стек.","Several streets and a large stack remain after the decision.","Достаточен ли порог по текущей эквити?","Is an immediate-equity threshold sufficient?","Нет, будущие решения и потенциальный дополнительный выигрыш тоже входят в EV","No; future leverage and implied odds enter EV","При длинном дереве будущие решения могут существенно изменить итоговый EV.","With a long future tree, later decisions can materially change total EV.","Да, текущая эквити полностью определяет EV","Yes; current equity fully determines EV"),
  d("PM-FND-07-TRC-103","FND-07","decision",["FTGU-E01"],"Для олл-ин колла цена требует примерно 33% эквити; у Hero 38%.","An all-in call gets a price requiring about 33% equity; Hero has 38%.","Как классифицировать колл по этой модели?","How is the call classified under this model?","Прибыльный по порогу цены и эквити","Profitable by the price/equity threshold","Колл может быть прибыльным при эквити выше порога цены, даже если проигрывает чаще половины.","A call can be profitable above the price threshold even when it loses more than half the time.","Убыточный, потому что эквити ниже 50%","Unprofitable because equity is below 50%"),
  d("PM-FND-07-TRC-104","FND-07","decision",["FTGU-E01"],"Решение на ривере завершает дерево после колла или фолда.","A river decision ends the tree after call/fold.","Что связывает риск и выигрыш с решением?","What should connect risk/reward to the decision?","Цена банка и требуемая эквити","Pot price and required equity","Когда будущих ставок нет, цена банка напрямую задаёт требуемую эквити.","When future betting is gone, pot price directly sets the required equity.","Частота выигрыша должна быть больше 50%","Win frequency must exceed 50%"),
  d("PM-FND-07-TRC-105","FND-07","decision",["FTGU-E01"],"Колл на флопе имеет низкую текущую эквити, но небольшую инвестицию сейчас и большой потенциальный будущий выигрыш.","A flop call has weak immediate equity but a small current investment and large potential future return.","Можно ли решить только по текущему порогу?","Can the decision be made from the immediate threshold alone?","Нет, оценить EV всей ветки и потенциальный дополнительный выигрыш","No; estimate whole-branch EV and implied odds","Низкая текущая эквити не исключает прибыльное продолжение при выгодном будущем дереве.","Low current equity does not rule out a profitable continue when the future tree is favorable.","Да, всегда фолдить, если текущая эквити ниже порога по шансам банка","Yes; always fold when current equity is below the pot-odds threshold"),
  d("PM-FND-07-TRC-106","FND-07","changed",["FTGU-E01"],"Та же рука и цена, но решение становится олл-ин и будущих ставок больше нет.","Same hand and price, but the decision becomes all-in and future betting disappears.","Что меняется в оценке?","What changes in the evaluation?","Порог цены и эквити становится более прямым ориентиром","The price/equity threshold becomes a more direct guide","Без будущих решений цена и эквити становятся более прямым приближением EV.","Without future decisions, price and equity become a more direct approximation of EV.","Ничего, будущие решения никогда не важны", "Nothing; the future tree never matters",["future_action","spr"]),
  d("PM-FND-07-TRC-107","FND-07","changed",["FTGU-E01"],"Та же текущая цена, но эффективный стек становится намного глубже.","Same immediate price, but the effective stack becomes much deeper.","Можно ли сохранить прежний упрощённый порог безубыточности?","Can the previous break-even shortcut be kept unchanged?","Нет, EV будущих решений получает больший вес","No; future-tree EV carries more weight","Более глубокий стек добавляет будущие решения и делает текущий порог менее достаточным.","A deeper stack adds future decisions and weakens the immediate-threshold shortcut.","Да, текущий порог всегда полностью решает ситуацию", "Yes; the immediate threshold always fully solves the node",["effective_stack","future_leverage"]),

  d("PM-BL-10-TRC-101","BL-10","recognition",["SLC-BB-VS-SB"],"Один и тот же флоп сравнивается против коллера из SB и BB.","The same flop is compared versus an SB caller and a BB caller.","Что нужно определить до выбора частоты c-bet?","What must be identified before choosing a c-bet default?","Из какого диапазона блайнда пришёл коллер","Which blind range the caller came from","Сначала определи исходный диапазон коллера, затем оцени стимулы доски.","Identify the caller's source range before evaluating the board incentives.","Только внешний вид доски","Only the board's appearance"),
  d("PM-BL-10-TRC-102","BL-10","decision",["SLC-BB-VS-SB"],"HJ PFR играет флоп K-K-J против коллера из BB.","HJ PFR plays a K-K-J flop versus a BB caller.","Какую базовую линию поддерживает материал?","Which baseline does the source support?","PFR может ставить c-bet очень часто из-за сильного преимущества диапазона","The PFR can c-bet very often because of strong range advantage","Против широкого диапазона BB на K-K-J у PFR сохраняется сильное преимущество диапазона.","Against the wider BB range on K-K-J, the PFR retains a strong range advantage.","Автоматически часто чекать против любого блайнда","Automatically heavy-check versus either blind"),
  d("PM-BL-10-TRC-103","BL-10","decision",["SLC-BB-VS-SB"],"HJ PFR играет тот же флоп K-K-J против коллера из SB.","HJ PFR plays the same K-K-J flop versus an SB caller.","Как меняется базовая линия?","How does the baseline change?","Чекать заметно чаще против более плотного диапазона SB","Check materially more often versus the more condensed SB range","Более плотный диапазон SB сохраняет больше сильных продолжений и реже автоматически фолдит.","The more condensed SB range retains more strong continues and folds less automatically.","Копировать частоту c-bet против BB без изменений","Copy the BB c-bet default unchanged"),
  d("PM-BL-10-TRC-104","BL-10","decision",["SLC-BB-VS-SB","LCM-03"],"Доска выглядит благоприятно для агрессора, но исходный диапазон коллера меняется с BB на SB.","The board looks favorable for the aggressor, but the caller source range changed from BB to SB.","Что важнее для базовой линии?","What matters for the baseline?","Текстура доски вместе с формой пришедшего диапазона","Board texture together with arriving-range shape","Постфлоп-базовая линия зависит от сочетания текстуры доски и формы пришедшего диапазона.","The postflop baseline depends on both board texture and the shape of the arriving range.","Только тип доски, независимо от исходного диапазона","The board label independent of source range"),
  d("PM-BL-10-TRC-105","BL-10","boundary",["SLC-BB-VS-SB","LCM-03"],"Конкретный SB регулярно слишком широко коллирует префлоп и приходит на флоп шире базового диапазона.","A specific SB repeatedly over-calls preflop and reaches the flop wider than baseline.","Нужно ли слепо применять базовое различие SB против BB?","Should the baseline SB-vs-BB contrast be applied blindly?","Нет, надёжные данные об оппоненте могут изменить исходное предположение о диапазоне","No; strong opponent evidence can change the arriving-range prior","Механизм зависит от фактической формы диапазона, а не только от позиции.","The mechanism depends on the actual range shape, not the seat label alone.","Да, позиция всегда полностью определяет диапазон", "Yes; the seat label always determines the range"),

  d("PM-W4-HAND-01-TRC-109","W4-HAND-01","boundary",["FTGU-E09"],"Готовая рука выглядит сильной по абсолютной категории, но диапазон, который продолжает против рейза, намного сильнее.","A made hand looks strong by its absolute label, but the range continuing versus a raise is much stronger.","Достаточно ли категории руки для вэлью-рейза?","Is the hand-family label sufficient for a value raise?","Нет, относительная сила против продолжающего диапазона ограничивает действие","No; relative strength versus the continuing range constrains the action","Категория руки — промежуточная классификация; действие зависит от относительной силы против продолжающего диапазона.","The family label is intermediate; the action depends on relative strength versus the continuing range.","Да, сильное название руки автоматически означает вэлью-рейз","Yes; a strong hand label automatically means a value raise"),
];
