import type { PracticalDecision } from "./types";

const o = (id: string, textRu: string, textEn: string, misconception?: string) => ({ id, textRu, textEn, misconception });

type S = {
  kind: PracticalDecision["kind"];
  sourceRefs: string[];
  cueRu: string; cueEn: string;
  questionRu: string; questionEn: string;
  goodRu: string; goodEn: string;
  bad1Ru: string; bad1En: string;
  bad2Ru: string; bad2En: string;
  whyRu: string; whyEn: string;
  badWhy1Ru: string; badWhy1En: string;
  badWhy2Ru: string; badWhy2En: string;
  changedVariables?: string[];
};

function make(skillId: string, prefix: string, scenarios: S[]): PracticalDecision[] {
  return scenarios.map((s, index) => {
    const slot = index % 3;
    const goodA = o("good", s.goodRu, s.goodEn);
    const badA1 = o("bad1", s.bad1Ru, s.bad1En, "ROLE_OR_RANGE_SHORTCUT");
    const badA2 = o("bad2", s.bad2Ru, s.bad2En, "SIZE_OR_SPR_AUTOPILOT");
    const goodR = o("goodR", s.whyRu, s.whyEn);
    const badR1 = o("badR1", `${s.badWhy1Ru} Поэтому относительное взаимодействие диапазонов может менять частоту исполнения, но не сам стратегический выбор в этом узле`, `${s.badWhy1En} Therefore relative range interaction can change execution frequency but not the strategic choice in this node`, "MECHANISM_SHORTCUT");
    const badR2 = o("badR2", `${s.badWhy2Ru} Поэтому после существенного изменения узла прежний вывод сохраняется без нового расчёта цены, диапазонов или SPR`, `${s.badWhy2En} Therefore after a material node change the old conclusion remains valid without recomputing price, ranges, or SPR`, "UNIVERSAL_RULE");
    const actions = slot === 0 ? [goodA, badA1, badA2] : slot === 1 ? [badA1, goodA, badA2] : [badA1, badA2, goodA];
    const reasons = slot === 0
      ? [badR1, goodR, badR2]
      : slot === 1
        ? (skillId === "3BP-05" ? [badR1, goodR, badR2] : [goodR, badR1, badR2])
        : [badR1, badR2, goodR];
    return {
      id: `${prefix}-${101 + index}`,
      skillId,
      kind: s.kind,
      sourceRefs: s.sourceRefs,
      assumptions: ["source-scoped mechanism; no unreviewed exact frequency claimed"],
      cueRu: s.cueRu, cueEn: s.cueEn,
      questionRu: s.questionRu, questionEn: s.questionEn,
      actionOptions: actions,
      reasonOptions: reasons,
      correctActionId: "good",
      correctReasonId: "goodR",
      targetSeconds: 25,
      explanationRu: s.whyRu,
      explanationEn: s.whyEn,
      changedVariables: s.changedVariables,
    } satisfies PracticalDecision;
  });
}

const aggrIp: S[] = [
  { kind:"recognition",sourceRefs:["FTGU-E28"],cueRu:"3BP, Hero — IP 3-bettor. Dry A-high board сохраняет premium/high-card density.",cueEn:"3BP, Hero is the IP 3-bettor. A dry A-high board preserves premium/high-card density.",questionRu:"Какой сигнал о структуре диапазона здесь важен?",questionEn:"Which family signal matters?",goodRu:"Broad small-bet pressure может быть уместен",goodEn:"Broad small-bet pressure can be appropriate",bad1Ru:"IP означает всегда overbet",bad1En:"IP always means overbet",bad2Ru:"3BP всегда требует check",bad2En:"3BP always requires checking",whyRu:"FTGU-E28 связывает small high-frequency betting с сохранённым concentrated range advantage.",whyEn:"Small high-frequency betting is supported when concentrated range advantage is preserved.",badWhy1Ru:"Позиция сама создаёт range advantage.",badWhy1En:"Position itself creates range advantage.",badWhy2Ru:"Любой 3-bettor имеет одинаковую flop strategy.",badWhy2En:"Every 3-bettor has the same flop strategy."},
  { kind:"recognition",sourceRefs:["FTGU-E29"],cueRu:"3BP IP aggressor на middling connected flop, где caller сохраняет много pair/draw/nut coverage.",cueEn:"3BP IP aggressor on a middling connected flop where the caller retains pair/draw/nut coverage.",questionRu:"Что распознать?",questionEn:"What should be recognized?",goodRu:"Range-bet license ослабла",goodEn:"The range-bet license weakened",bad1Ru:"Preflop aggression гарантирует range-bet",bad1En:"Preflop aggression guarantees a range bet",bad2Ru:"Connected board всегда означает fold",bad2En:"A connected board always means fold",whyRu:"FTGU-E29 переходит к selective strategies когда board materially equalises ranges.",whyEn:"When the board materially equalizes ranges, strategy should become more selective.",badWhy1Ru:"3-bet pot сохраняет preflop advantage на любой доске.",badWhy1En:"A 3-bet pot preserves preflop advantage on every board.",badWhy2Ru:"Texture label достаточно без arriving ranges.",badWhy2En:"The texture label is sufficient without arriving ranges."},
  { kind:"decision",sourceRefs:["FTGU-E28"],cueRu:"Dry paired flop; caller редко имеет trips region, aggressor сохраняет overpairs.",cueEn:"Dry paired flop; caller rarely has the trips region while the aggressor retains overpairs.",questionRu:"Какой default practical branch?",questionEn:"Which practical branch is the better default?",goodRu:"Small broad bet",goodEn:"Small broad bet",bad1Ru:"Large polar bet всей range",bad1En:"Large polar bet with the whole range",bad2Ru:"Range check только потому что pot 3-bet",bad2En:"Range check solely because the pot is 3-bet",whyRu:"Broad advantage + protection incentives support small high-frequency pressure.",whyEn:"Broad advantage plus protection incentives support small high-frequency pressure.",badWhy1Ru:"Large size лучше для любой advantage board.",badWhy1En:"A large size is better on every advantage board.",badWhy2Ru:"Pot type определяет action независимо от board.",badWhy2En:"Pot type determines action regardless of the board."},
  { kind:"decision",sourceRefs:["FTGU-E29"],cueRu:"Low connected board materially improves caller coverage.",cueEn:"A low connected board materially improves caller coverage.",questionRu:"Как скорректировать c-bet?",questionEn:"How should the c-bet plan adjust?",goodRu:"Больше check/selective betting",goodEn:"More checking/selective betting",bad1Ru:"Ставить range маленько как на A-high",bad1En:"Small range-bet as on A-high",bad2Ru:"Overbet всей range",bad2En:"Overbet the whole range",whyRu:"Equalising boards требуют selectivity и не наследуют dry-board defaults.",whyEn:"Equalizing boards require selectivity and do not inherit dry-board defaults.",badWhy1Ru:"Все 3BP boards одинаково благоприятны aggressor.",badWhy1En:"All 3BP boards favor the aggressor equally.",badWhy2Ru:"Большой pot делает board interaction неважным.",badWhy2En:"A large pot makes board interaction irrelevant."},
  { kind:"decision",sourceRefs:["FTGU-E28","FTGU-E29"],cueRu:"Board даёт умеренный advantage, но не чистый range-bet node.",cueEn:"The board gives a moderate advantage but not a clean range-bet node.",questionRu:"Какой подход лучше?",questionEn:"Which approach is better?",goodRu:"Split/selective strategy",goodEn:"A split/selective strategy",bad1Ru:"Только range-bet",bad1En:"Range-bet only",bad2Ru:"Только range-check",bad2En:"Range-check only",whyRu:"E28/E29 образуют spectrum между high-frequency и selective nodes.",whyEn:"3-bet-pot nodes span a spectrum from high-frequency betting to selective pressure as board-range interaction changes.",badWhy1Ru:"Strategy должна быть бинарной.",badWhy1En:"Strategy must be binary.",badWhy2Ru:"Один sizing обязан покрывать любой board.",badWhy2En:"One sizing must cover every board."},
  { kind:"changed",sourceRefs:["FTGU-E28","FTGU-E29"],cueRu:"Та же preflop линия; flop меняется с dry A-high на low connected.",cueEn:"Same preflop line; flop changes from dry A-high to low connected.",questionRu:"Как меняется pressure?",questionEn:"How does pressure change?",goodRu:"От broad/small к более selective",goodEn:"From broad/small toward more selective",bad1Ru:"Не меняется",bad1En:"No change",bad2Ru:"Становится ещё более automatic",bad2En:"Becomes even more automatic",whyRu:"Material range equalisation меняет flop family несмотря на ту же preflop role.",whyEn:"Material range equalization changes the flop family despite the same preflop role.",badWhy1Ru:"Preflop role полностью фиксирует flop strategy.",badWhy1En:"Preflop role completely fixes flop strategy.",badWhy2Ru:"Board changes только equity, не strategy shape.",badWhy2En:"Board changes equity but not strategy shape.",changedVariables:["board_class","range_equalization"]},
  { kind:"changed",sourceRefs:["FTGU-E28"],cueRu:"Та же board family, но Hero теперь OOP aggressor вместо IP.",cueEn:"Same board family, but Hero is now the OOP aggressor instead of IP.",questionRu:"Можно ли сохранить IP plan без проверки?",questionEn:"Can the IP plan be kept without re-evaluation?",goodRu:"Нет — role/position требует нового tree",goodEn:"No — role/position requires a new tree",bad1Ru:"Да, aggressor role важнее position",bad1En:"Yes, aggressor role matters more than position",bad2Ru:"Да, 3BP одинаковы IP/OOP",bad2En:"Yes, 3BPs are identical IP/OOP",whyRu:"Position changes realisation and checking incentives even when preflop aggressor identity is unchanged.",whyEn:"Position changes realization and checking incentives even when preflop aggressor identity is unchanged.",badWhy1Ru:"Initiative стирает positional disadvantage.",badWhy1En:"Initiative erases positional disadvantage.",badWhy2Ru:"SPR делает position неважной.",badWhy2En:"SPR makes position irrelevant.",changedVariables:["position_role"]},
  { kind:"boundary",sourceRefs:["FTGU-E28"],cueRu:"Learner видит '3-bet pot' и хочет ставить range маленько на любом flop.",cueEn:"The learner sees '3-bet pot' and wants to small range-bet every flop.",questionRu:"Где граница правила?",questionEn:"Where is the boundary?",goodRu:"High-frequency small bet требует сохранённого range advantage",goodEn:"High-frequency small betting requires preserved range advantage",bad1Ru:"Правило универсально",bad1En:"The rule is universal",bad2Ru:"Только stack depth ограничивает его",bad2En:"Only stack depth limits it",whyRu:"E28 не лицензирует universal c-bet; board-range interaction остаётся условием.",whyEn:"High-frequency examples do not license universal c-betting; board-range interaction remains a condition.",badWhy1Ru:"Pot type заменяет board analysis.",badWhy1En:"Pot type replaces board analysis.",badWhy2Ru:"Preflop 3-bet означает permanent nut advantage.",badWhy2En:"A preflop 3-bet means permanent nut advantage."},
];

const aggrOop: S[] = [
  {kind:"recognition",sourceRefs:["SLC-EXPLOITING-OOP-CBETS"],cueRu:"Hero — OOP 3-bettor; caller IP реализует equity легче.",cueEn:"Hero is the OOP 3-bettor; the IP caller realizes equity more easily.",questionRu:"Что меняется первым?",questionEn:"What changes first?",goodRu:"Checking/selection incentives растут",goodEn:"Checking/selection incentives increase",bad1Ru:"Initiative отменяет OOP",bad1En:"Initiative cancels OOP",bad2Ru:"Всегда range-bet",bad2En:"Always range-bet",whyRu:"Smash OOP 3BP material treats position as a structural cost rather than copying IP c-bets.",whyEn:"Smash OOP 3BP material treats position as a structural cost rather than copying IP c-bets.",badWhy1Ru:"Preflop aggressor всегда контролирует tree.",badWhy1En:"The preflop aggressor always controls the tree.",badWhy2Ru:"Caller IP не получает realisation edge.",badWhy2En:"The IP caller gets no realization edge."},
  {kind:"recognition",sourceRefs:["FTGU-E29"],cueRu:"OOP aggressor на board, где preflop advantage заметно equalised.",cueEn:"OOP aggressor on a board where the preflop advantage is materially equalized.",questionRu:"Какой signal?",questionEn:"Which signal?",goodRu:"Selective/check-heavy branch",goodEn:"Selective/check-heavy branch",bad1Ru:"Small range-bet по инициативе",bad1En:"Small range-bet because of initiative",bad2Ru:"Large range overbet",bad2En:"Large range overbet",whyRu:"Equalisation plus OOP makes unselective pressure especially fragile.",whyEn:"Equalization plus OOP makes unselective pressure especially fragile.",badWhy1Ru:"OOP не влияет после 3-bet.",badWhy1En:"OOP does not matter after a 3-bet.",badWhy2Ru:"Pot size гарантирует fold equity.",badWhy2En:"Pot size guarantees fold equity."},
  {kind:"decision",sourceRefs:["SLC-EXPLOITING-OOP-CBETS"],cueRu:"OOP 3-bettor имеет medium showdown hand на neutral board.",cueEn:"The OOP 3-bettor has a medium showdown hand on a neutral board.",questionRu:"Что лучше проверить?",questionEn:"What should be considered first?",goodRu:"Protected check branch",goodEn:"A protected check branch",bad1Ru:"Bet потому что hand впереди",bad1En:"Bet because the hand is ahead",bad2Ru:"Overbet для защиты",bad2En:"Overbet for protection",whyRu:"Medium hands often benefit from preserving a credible checking range and avoiding unnecessary pot inflation OOP.",whyEn:"Medium hands often benefit from preserving a credible checking range and avoiding unnecessary pot inflation OOP.",badWhy1Ru:"Любая likely-best hand обязана value bet.",badWhy1En:"Any likely-best hand must value bet.",badWhy2Ru:"Protection всегда требует большого sizing.",badWhy2En:"Protection always requires a large sizing."},
  {kind:"decision",sourceRefs:["FTGU-E29"],cueRu:"OOP 3-bettor на coordinated equaliser с marginal bluff candidate.",cueEn:"OOP 3-bettor on a coordinated equalizer with a marginal bluff candidate.",questionRu:"Default?",questionEn:"Default?",goodRu:"Check чаще",goodEn:"Check more often",bad1Ru:"Bluff из-за range advantage preflop",bad1En:"Bluff because of preflop range advantage",bad2Ru:"Jam low equity",bad2En:"Jam low equity",whyRu:"Selective nodes remove weak pressure candidates when caller coverage rises.",whyEn:"Selective nodes remove weak pressure candidates when caller coverage rises.",badWhy1Ru:"Preflop advantage never decays.",badWhy1En:"Preflop advantage never decays.",badWhy2Ru:"OOP bluffing получает бонус от position.",badWhy2En:"OOP bluffing gets a positional bonus."},
  {kind:"decision",sourceRefs:["SLC-EXPLOITING-OOP-CBETS"],cueRu:"Caller IP has shown tendency to attack weak OOP checking ranges.",cueEn:"The IP caller has shown a tendency to attack weak OOP checking ranges.",questionRu:"Как строить check range?",questionEn:"How should the checking range be built?",goodRu:"Оставлять достаточно strong hands в check",goodEn:"Keep enough strong hands in the checking range",bad1Ru:"Check только air",bad1En:"Check only air",bad2Ru:"Никогда не check",bad2En:"Never check",whyRu:"An unprotected check range creates an exploitable branch for the IP caller.",whyEn:"An unprotected check range creates an exploitable branch for the IP caller.",badWhy1Ru:"Check всегда означает weakness.",badWhy1En:"A check always means weakness.",badWhy2Ru:"Protection требует 100% betting.",badWhy2En:"Protection requires 100% betting."},
  {kind:"changed",sourceRefs:["FTGU-E28","FTGU-E29"],cueRu:"Та же OOP role; board меняется premium-preserving → equalising.",cueEn:"Same OOP role; board changes premium-preserving → equalizing.",questionRu:"Как меняется plan?",questionEn:"How does the plan change?",goodRu:"От некоторого broad pressure к большей selectivity/checking",goodEn:"From some broad pressure toward more selectivity/checking",bad1Ru:"Не меняется",bad1En:"No change",bad2Ru:"OOP требует больше bluff",bad2En:"OOP requires more bluffing",whyRu:"Board interaction still decides whether preflop advantage survives.",whyEn:"Board interaction still decides whether the preflop advantage survives.",badWhy1Ru:"Position alone fixes strategy.",badWhy1En:"Position alone fixes strategy.",badWhy2Ru:"Equalising board усиливает aggressor automatically.",badWhy2En:"An equalizing board automatically strengthens the aggressor.",changedVariables:["board_class"]},
  {kind:"changed",sourceRefs:["SLC-EXPLOITING-OOP-CBETS"],cueRu:"Та же board; Hero меняется OOP → IP aggressor.",cueEn:"Same board; Hero changes from OOP → IP aggressor.",questionRu:"Что пересчитать?",questionEn:"What should be recomputed?",goodRu:"Bet/check incentives и realisation",goodEn:"Bet/check incentives and realization",bad1Ru:"Ничего",bad1En:"Nothing",bad2Ru:"Только pot size",bad2En:"Only pot size",whyRu:"Position is a first-order branch variable in 3BP postflop.",whyEn:"Position is a first-order branch variable in 3BP postflop.",badWhy1Ru:"Aggressor identity makes positions equivalent.",badWhy1En:"Aggressor identity makes positions equivalent.",badWhy2Ru:"SPR fully determines strategy.",badWhy2En:"SPR fully determines strategy.",changedVariables:["position"]},
  {kind:"boundary",sourceRefs:["SLC-EXPLOITING-OOP-CBETS"],cueRu:"Learner хочет копировать IP 3BP c-bet heuristics в OOP node.",cueEn:"The learner wants to copy IP 3BP c-bet heuristics into an OOP node.",questionRu:"Допустимо?",questionEn:"Is that valid?",goodRu:"Нет — роль OOP требует отдельного tree",goodEn:"No — the OOP role requires a separate tree",bad1Ru:"Да, если Hero 3-bettor",bad1En:"Yes, if Hero is the 3-bettor",bad2Ru:"Да, если SPR низкий",bad2En:"Yes, if SPR is low",whyRu:"The source specifically treats OOP c-bet behaviour as distinct and exploitable when overextended.",whyEn:"Overextended OOP c-betting can create a distinct exploit, but it remains branch-specific.",badWhy1Ru:"Initiative dominates position.",badWhy1En:"Initiative dominates position.",badWhy2Ru:"Low SPR erases positional asymmetry.",badWhy2En:"Low SPR erases positional asymmetry."},
];

const callerIp: S[] = [
  {kind:"recognition",sourceRefs:["FTGU-E28","FTGU-E29"],cueRu:"Caller IP faces small high-frequency c-bet on a dry premium-preserving flop.",cueEn:"The IP caller faces a small high-frequency c-bet on a dry premium-preserving flop.",questionRu:"Что распознать?",questionEn:"What should be recognized?",goodRu:"Цена мала, но aggressor range остаётся сильной",goodEn:"The price is small, but the aggressor range remains strong",bad1Ru:"Small bet всегда weak",bad1En:"A small bet is always weak",bad2Ru:"IP caller всегда raise",bad2En:"The IP caller always raises",whyRu:"Defence must combine price with range strength rather than interpret size as weakness.",whyEn:"Defense must combine price with range strength rather than interpret size as weakness.",badWhy1Ru:"Sizing напрямую раскрывает hand strength.",badWhy1En:"Sizing directly reveals hand strength.",badWhy2Ru:"Position guarantees profitable aggression.",badWhy2En:"Position guarantees profitable aggression."},
  {kind:"recognition",sourceRefs:["CINJ-E09"],cueRu:"IP caller видит repeated small c-bet branch, который population может overuse/fold too much vs raise.",cueEn:"The IP caller sees a repeated small-cbet branch that the population may overuse/fold too much versus raises.",questionRu:"Какой exploit signal возможен?",questionEn:"Which exploit signal can exist?",goodRu:"Selective click-back/raise candidate",goodEn:"A selective click-back/raise candidate",bad1Ru:"Raise any two cards",bad1En:"Raise any two cards",bad2Ru:"Never raise in 3BP",bad2En:"Never raise in 3BPs",whyRu:"A small IP click-back is a branch-specific exploit, not a universal aggression rule.",whyEn:"A small IP click-back is a branch-specific exploit, not a universal aggression rule.",badWhy1Ru:"Population leak means all hands profitably raise.",badWhy1En:"A population leak means all hands profitably raise.",badWhy2Ru:"3BP callers cannot have raising ranges.",badWhy2En:"3BP callers cannot have raising ranges."},
  {kind:"decision",sourceRefs:["FTGU-E28"],cueRu:"IP caller has medium showdown hand vs small bet on dry board.",cueEn:"The IP caller has a medium showdown hand versus a small bet on a dry board.",questionRu:"Default response?",questionEn:"Default response?",goodRu:"Continue frequently via call when hand realizes well",goodEn:"Continue frequently by calling when the hand realizes well",bad1Ru:"Fold because 3-bettor strong",bad1En:"Fold because the 3-bettor is strong",bad2Ru:"Raise because bet small",bad2En:"Raise because the bet is small",whyRu:"A cheap price plus position can support continued realization without forcing a raise.",whyEn:"A cheap price plus position can support continued realization without forcing a raise.",badWhy1Ru:"Range disadvantage means every medium hand folds.",badWhy1En:"Range disadvantage means every medium hand folds.",badWhy2Ru:"Small sizing automatically invites a raise.",badWhy2En:"Small sizing automatically invites a raise."},
  {kind:"decision",sourceRefs:["FTGU-E29"],cueRu:"IP caller has strong draw on equalising coordinated board vs selective c-bet.",cueEn:"The IP caller has a strong draw on an equalizing coordinated board versus a selective c-bet.",questionRu:"Что важнее?",questionEn:"What matters most?",goodRu:"Evaluate call/raise through equity, nut potential and continuing range",goodEn:"Evaluate call/raise through equity, nut potential and the continuing range",bad1Ru:"Auto-raise every draw",bad1En:"Auto-raise every draw",bad2Ru:"Auto-fold because 3BP",bad2En:"Auto-fold because it is a 3BP",whyRu:"Selective boards require hand-family and range interaction, not a draw-name shortcut.",whyEn:"Selective boards require hand-family and range interaction, not a draw-name shortcut.",badWhy1Ru:"Draw label determines action.",badWhy1En:"The draw label determines the action.",badWhy2Ru:"Preflop caller cannot pressure postflop.",badWhy2En:"The preflop caller cannot apply pressure postflop."},
  {kind:"decision",sourceRefs:["CINJ-E09"],cueRu:"Observed branch-specific overfold to small IP click-back raises is credible.",cueEn:"A credible branch-specific overfold to small IP click-back raises has been observed.",questionRu:"Как использовать leak?",questionEn:"How should the leak be used?",goodRu:"Expand selected raise candidates within the evidenced branch",goodEn:"Expand selected raise candidates within the evidenced branch",bad1Ru:"Raise every flop forever",bad1En:"Raise every flop forever",bad2Ru:"Ignore evidence",bad2En:"Ignore the evidence",whyRu:"Exploit stays branch-specific and evidence-qualified.",whyEn:"The exploit stays branch-specific and evidence-qualified.",badWhy1Ru:"One leak generalises to all boards/sizes.",badWhy1En:"One leak generalizes to all boards/sizes.",badWhy2Ru:"Exploit requires exact solver frequency first.",badWhy2En:"An exploit requires an exact solver frequency first."},
  {kind:"changed",sourceRefs:["FTGU-E28","FTGU-E29"],cueRu:"Same hand/role; c-bet size changes small → large.",cueEn:"Same hand/role; c-bet size changes small → large.",questionRu:"Как сдвигается marginal defence?",questionEn:"How does marginal defense shift?",goodRu:"Tighter; price and bettor range concentration matter more",goodEn:"Tighter; price and bettor range concentration matter more",bad1Ru:"Defend wider because pot bigger",bad1En:"Defend wider because the pot is bigger",bad2Ru:"No change",bad2En:"No change",whyRu:"A larger price removes marginal continues and usually represents a more selected betting range.",whyEn:"A larger price removes marginal continues and usually represents a more selected betting range.",badWhy1Ru:"Bigger pot improves caller price.",badWhy1En:"A bigger pot improves the caller's price.",badWhy2Ru:"Sizing does not alter defence EV.",badWhy2En:"Sizing does not alter defense EV.",changedVariables:["cbet_size"]},
  {kind:"changed",sourceRefs:["FTGU-E29"],cueRu:"Same IP caller; board changes dry high → equalising connected.",cueEn:"Same IP caller; board changes dry high → equalizing connected.",questionRu:"Как меняется caller leverage?",questionEn:"How does caller leverage change?",goodRu:"More credible continue/raise coverage",goodEn:"More credible continue/raise coverage",bad1Ru:"Worse because aggressor always stronger",bad1En:"Worse because the aggressor is always stronger",bad2Ru:"No change",bad2En:"No change",whyRu:"Equalising boards retain more strong caller regions and reduce automatic aggressor leverage.",whyEn:"Equalizing boards retain more strong caller regions and reduce automatic aggressor leverage.",badWhy1Ru:"Preflop caller range never catches up.",badWhy1En:"The preflop caller range never catches up.",badWhy2Ru:"Board class does not affect caller coverage.",badWhy2En:"Board class does not affect caller coverage.",changedVariables:["board_class"]},
  {kind:"boundary",sourceRefs:["CINJ-E09"],cueRu:"Population click-back leak is not observed in this room/size/board branch.",cueEn:"The population click-back leak is not observed in this room/size/board branch.",questionRu:"Можно ли переносить exploit?",questionEn:"Can the exploit be imported?",goodRu:"Нет — вернуть baseline until evidence",goodEn:"No — return to baseline until evidence",bad1Ru:"Да, leak universal",bad1En:"Yes, the leak is universal",bad2Ru:"Да, потому что Hero IP",bad2En:"Yes, because Hero is IP",whyRu:"CINJ exploit is branch-specific evidence, not a permanent theorem.",whyEn:"The CINJ exploit is branch-specific evidence, not a permanent theorem.",badWhy1Ru:"Population tendencies одинаковы во всех pools.",badWhy1En:"Population tendencies are identical in all pools.",badWhy2Ru:"Position alone proves overfold.",badWhy2En:"Position alone proves overfold."},
];

const callerOop: S[] = [
  {kind:"recognition",sourceRefs:["CP-G3-L09"],cueRu:"OOP caller in 3BP faces flop pressure.",cueEn:"The OOP caller in a 3BP faces flop pressure.",questionRu:"Какой structural problem ключевой?",questionEn:"Which structural problem is key?",goodRu:"Poor realisation + future pressure",goodEn:"Poor realization plus future pressure",bad1Ru:"Only pot odds",bad1En:"Only pot odds",bad2Ru:"Initiative is irrelevant",bad2En:"Initiative is irrelevant",whyRu:"CP-G3-L09 treats OOP 3BP defence as a range construction/realisation problem, not a one-street price problem.",whyEn:"OOP 3-bet-pot defense is a range-construction and realization problem, not a one-street price problem.",badWhy1Ru:"Current price fully determines OOP defence.",badWhy1En:"The current price fully determines OOP defense.",badWhy2Ru:"Future streets do not matter in 3BP.",badWhy2En:"Future streets do not matter in 3BPs."},
  {kind:"recognition",sourceRefs:["CP-G3-L09"],cueRu:"OOP caller has strong hand but checking range would be empty of strength if it always raises.",cueEn:"The OOP caller has a strong hand, but the checking range would be empty of strength if it always raised.",questionRu:"Что распознать?",questionEn:"What should be recognized?",goodRu:"Need protected continues/checks",goodEn:"Need protected continues/checks",bad1Ru:"Raise all strong hands",bad1En:"Raise all strong hands",bad2Ru:"Fold all medium hands",bad2En:"Fold all medium hands",whyRu:"A defendable OOP tree needs strength distributed into non-aggressive branches.",whyEn:"A defendable OOP tree needs strength distributed into non-aggressive branches.",badWhy1Ru:"Strong hand label forces raise.",badWhy1En:"A strong-hand label forces a raise.",badWhy2Ru:"Checking always caps range.",badWhy2En:"Checking always caps the range."},
  {kind:"decision",sourceRefs:["CP-G3-L09"],cueRu:"Small c-bet, OOP caller has medium hand with robust equity.",cueEn:"Small c-bet, OOP caller has a medium hand with robust equity.",questionRu:"Default?",questionEn:"Default?",goodRu:"Defend enough via call/check-call",goodEn:"Defend sufficiently via call/check-call",bad1Ru:"Overfold because OOP",bad1En:"Overfold because OOP",bad2Ru:"Raise all medium hands",bad2En:"Raise all medium hands",whyRu:"Cheap sizing plus robust equity supports continuing despite positional disadvantage.",whyEn:"Cheap sizing plus robust equity supports continuing despite positional disadvantage.",badWhy1Ru:"OOP means marginal hands cannot realise any equity.",badWhy1En:"OOP means marginal hands cannot realize any equity.",badWhy2Ru:"Only aggression can realize equity.",badWhy2En:"Only aggression can realize equity."},
  {kind:"decision",sourceRefs:["CP-G3-L09"],cueRu:"Large c-bet, OOP caller has dominated weak pair/no redraw.",cueEn:"Large c-bet, OOP caller has a dominated weak pair with no redraw.",questionRu:"Default?",questionEn:"Default?",goodRu:"Fold more readily",goodEn:"Fold more readily",bad1Ru:"Call because pot already large",bad1En:"Call because the pot is already large",bad2Ru:"Raise as bluff-catcher",bad2En:"Raise as a bluff-catcher",whyRu:"Large sizing worsens price and magnifies poor realisation for weak dominated classes.",whyEn:"Large sizing worsens price and magnifies poor realization for weak dominated classes.",badWhy1Ru:"Sunk investment justifies wider calls.",badWhy1En:"Sunk investment justifies wider calls.",badWhy2Ru:"Weak pair blocks enough value automatically.",badWhy2En:"A weak pair automatically blocks enough value."},
  {kind:"decision",sourceRefs:["CP-G3-L09"],cueRu:"OOP caller checks strong value on board where aggressor continues betting many worse hands.",cueEn:"The OOP caller checks strong value on a board where the aggressor keeps betting many worse hands.",questionRu:"Может ли slow branch быть valid?",questionEn:"Can a slower branch be valid?",goodRu:"Да, если check keeps range protected and captures future bets",goodEn:"Yes, if checking protects the range and captures future bets",bad1Ru:"Нет, strong always raise",bad1En:"No, strong hands always raise",bad2Ru:"Нет, OOP must lead",bad2En:"No, OOP must lead",whyRu:"Low-frequency strong checks can protect OOP continues and preserve opponent bluffs/value mistakes.",whyEn:"Strong checks can protect OOP continues and preserve opponent bluffs/value mistakes.",badWhy1Ru:"Immediate value always dominates future EV.",badWhy1En:"Immediate value always dominates future EV.",badWhy2Ru:"OOP position requires taking initiative immediately.",badWhy2En:"Being OOP requires taking initiative immediately."},
  {kind:"changed",sourceRefs:["CP-G3-L09"],cueRu:"Same hand/board, bet size small → large.",cueEn:"Same hand/board, bet size small → large.",questionRu:"Как меняется weakest continue?",questionEn:"How does the weakest continue change?",goodRu:"Many marginal continues fall out",goodEn:"Many marginal continues fall out",bad1Ru:"More calls because pot larger",bad1En:"More calls because the pot is larger",bad2Ru:"No change",bad2En:"No change",whyRu:"Price and future SPR materially change OOP realisation EV.",whyEn:"Price and future SPR materially change OOP realization EV.",badWhy1Ru:"Pot size alone improves calls.",badWhy1En:"Pot size alone improves calls.",badWhy2Ru:"Sizing does not change future pressure.",badWhy2En:"Sizing does not change future pressure.",changedVariables:["bet_size","future_spr"]},
  {kind:"changed",sourceRefs:["CP-G3-L09"],cueRu:"Same hand/size, Hero moves OOP caller → IP caller.",cueEn:"Same hand/size, Hero moves from OOP caller → IP caller.",questionRu:"Что меняется?",questionEn:"What changes?",goodRu:"Realisation improves and defence can widen/select differently",goodEn:"Realization improves and defense can widen/select differently",bad1Ru:"Nothing",bad1En:"Nothing",bad2Ru:"Only preflop range",bad2En:"Only the preflop range",whyRu:"Position directly changes future action control and equity realisation.",whyEn:"Position directly changes future action control and equity realization.",badWhy1Ru:"Caller role fixes strategy regardless of position.",badWhy1En:"The caller role fixes strategy regardless of position.",badWhy2Ru:"SPR removes position from the tree.",badWhy2En:"SPR removes position from the tree.",changedVariables:["position"]},
  {kind:"boundary",sourceRefs:["CP-G3-L09"],cueRu:"Learner thinks OOP caller should either overfold or overraise to simplify.",cueEn:"The learner thinks the OOP caller should either overfold or overraise to simplify.",questionRu:"Boundary?",questionEn:"Boundary?",goodRu:"Need a protected call/check-call region",goodEn:"Need a protected call/check-call region",bad1Ru:"Overfold is always safest",bad1En:"Overfolding is always safest",bad2Ru:"Overraise removes positional disadvantage",bad2En:"Overraising removes positional disadvantage",whyRu:"A defendable OOP tree includes calls; it should not collapse to fold-or-raise extremes.",whyEn:"A defendable OOP tree includes calls; it should not collapse to fold-or-raise extremes.",badWhy1Ru:"Position disadvantage justifies abandoning equilibrium protection.",badWhy1En:"Positional disadvantage justifies abandoning range protection.",badWhy2Ru:"Aggression cancels OOP structurally.",badWhy2En:"Aggression structurally cancels OOP."},
];

const matrix: S[] = [
  {kind:"recognition",sourceRefs:["FTGU-E28","FTGU-E29"],cueRu:"3BP flop family changes dry-high → coordinated-middle.",cueEn:"3BP flop family changes dry-high → coordinated-middle.",questionRu:"Что должно меняться вместе с board?",questionEn:"What should change with the board?",goodRu:"Frequency/size/check split",goodEn:"Frequency/size/check split",bad1Ru:"Nothing because pot type same",bad1En:"Nothing because pot type is the same",bad2Ru:"Only hand names",bad2En:"Only hand names",whyRu:"E28/E29 define different strategic families by how the board preserves or equalises preflop advantage.",whyEn:"Whether the board preserves or equalizes preflop advantage determines the 3-bet-pot strategic family.",badWhy1Ru:"3BP is one strategy class.",badWhy1En:"A 3BP is one strategy class.",badWhy2Ru:"Sizing independent of range interaction.",badWhy2En:"Sizing is independent of range interaction."},
  {kind:"recognition",sourceRefs:["FTGU-E28","FTGU-E29"],cueRu:"Same board, c-bet size changes small → large.",cueEn:"Same board, c-bet size changes small → large.",questionRu:"Что меняется у defender?",questionEn:"What changes for the defender?",goodRu:"Price + likely bettor selection",goodEn:"Price plus likely bettor selection",bad1Ru:"Nothing",bad1En:"Nothing",bad2Ru:"Only pot visual size",bad2En:"Only the pot's visual size",whyRu:"Sizing is part of the range/defence matrix, not decoration.",whyEn:"Sizing is part of the range/defense matrix, not decoration.",badWhy1Ru:"All bets represent same range.",badWhy1En:"All bets represent the same range.",badWhy2Ru:"Defence thresholds never move with price.",badWhy2En:"Defense thresholds never move with price."},
  {kind:"decision",sourceRefs:["FTGU-E28"],cueRu:"Premium-preserving board + small size.",cueEn:"Premium-preserving board plus small size.",questionRu:"Best matrix cell?",questionEn:"Best matrix cell?",goodRu:"Broad aggressor bet / wide enough defence",goodEn:"Broad aggressor bet / sufficiently wide defense",bad1Ru:"Polar only / overfold",bad1En:"Polar only / overfold",bad2Ru:"Range check / range fold",bad2En:"Range check / range fold",whyRu:"Small broad betting and cheap defence are paired consequences of the same node.",whyEn:"Small broad betting and cheap defense are paired consequences of the same node.",badWhy1Ru:"Small size always means polar strength.",badWhy1En:"A small size always means polar strength.",badWhy2Ru:"Defender should ignore pot odds.",badWhy2En:"The defender should ignore pot odds."},
  {kind:"decision",sourceRefs:["FTGU-E29"],cueRu:"Equalising board + selected larger size.",cueEn:"Equalizing board plus a selected larger size.",questionRu:"Best matrix cell?",questionEn:"Best matrix cell?",goodRu:"Narrower bettor range / tighter defence",goodEn:"Narrower bettor range / tighter defense",bad1Ru:"Range-bet / same defence",bad1En:"Range-bet / same defense",bad2Ru:"Bet size irrelevant",bad2En:"Bet size irrelevant",whyRu:"Selective strategy and higher price jointly remove marginal hands from both sides' active branches.",whyEn:"Selective strategy and a higher price jointly remove marginal hands from both sides' active branches.",badWhy1Ru:"Board equalisation increases all betting.",badWhy1En:"Board equalization increases all betting.",badWhy2Ru:"Defender responds only to hand rank.",badWhy2En:"The defender responds only to hand rank."},
  {kind:"decision",sourceRefs:["FTGU-E28","FTGU-E29"],cueRu:"Unknown exact solver frequency, mechanism authority is clear.",cueEn:"Exact solver frequency is unknown, but the mechanism authority is clear.",questionRu:"Что учить?",questionEn:"What should be taught?",goodRu:"Direction/range shape/size family",goodEn:"Direction/range shape/size family",bad1Ru:"Invent exact 63%",bad1En:"Invent an exact 63%",bad2Ru:"Teach nothing",bad2En:"Teach nothing",whyRu:"The product can teach robust structural differences without fabricating exact frequencies.",whyEn:"The product can teach robust structural differences without fabricating exact frequencies.",badWhy1Ru:"Exact precision can be guessed from mechanism.",badWhy1En:"Exact precision can be guessed from the mechanism.",badWhy2Ru:"No exact frequency means no useful knowledge.",badWhy2En:"No exact frequency means no useful knowledge."},
  {kind:"changed",sourceRefs:["FTGU-E28","FTGU-E29"],cueRu:"Same role/board; sizing doubles.",cueEn:"Same role/board; sizing doubles.",questionRu:"Как меняется marginal defender?",questionEn:"How does the marginal defender change?",goodRu:"More folds / stronger continuing region",goodEn:"More folds / stronger continuing region",bad1Ru:"Wider calls",bad1En:"Wider calls",bad2Ru:"No change",bad2En:"No change",whyRu:"Larger price lowers marginal continue EV and often corresponds to a more selected bettor range.",whyEn:"A larger price lowers marginal continue EV and often corresponds to a more selected bettor range.",badWhy1Ru:"Bigger pot means better price.",badWhy1En:"A bigger pot means a better price.",badWhy2Ru:"Sizing never changes range composition.",badWhy2En:"Sizing never changes range composition.",changedVariables:["bet_size"]},
  {kind:"changed",sourceRefs:["FTGU-E28","FTGU-E29"],cueRu:"Same sizing; board dry-high → connected-middle.",cueEn:"Same sizing; board dry-high → connected-middle.",questionRu:"Что меняется?",questionEn:"What changes?",goodRu:"Aggressor frequency/selectivity and defender continue shape",goodEn:"Aggressor frequency/selectivity and defender continue shape",bad1Ru:"Nothing",bad1En:"Nothing",bad2Ru:"Only targetSeconds",bad2En:"Only targetSeconds",whyRu:"The board changes which range regions survive and therefore both sides' branches.",whyEn:"The board changes which range regions survive and therefore both sides' branches.",badWhy1Ru:"Sizing fixes strategy independent of board.",badWhy1En:"Sizing fixes strategy independent of board.",badWhy2Ru:"3BP caller never has nut coverage.",badWhy2En:"A 3BP caller never has nut coverage.",changedVariables:["board_class"]},
  {kind:"boundary",sourceRefs:["FTGU-E28","FTGU-E29"],cueRu:"Learner wants one memorized 3BP c-bet size/frequency for every role and board.",cueEn:"The learner wants one memorized 3BP c-bet size/frequency for every role and board.",questionRu:"Boundary?",questionEn:"Boundary?",goodRu:"Matrix must retain role × board × size",goodEn:"The matrix must retain role × board × size",bad1Ru:"One default is enough",bad1En:"One default is enough",bad2Ru:"Only stack matters",bad2En:"Only stack matters",whyRu:"The sources explicitly split high-frequency and selective nodes, while position changes execution.",whyEn:"The sources explicitly split high-frequency and selective nodes, while position changes execution.",badWhy1Ru:"Simplification should erase causal variables.",badWhy1En:"Simplification should erase causal variables.",badWhy2Ru:"Range advantage is static after preflop.",badWhy2En:"Range advantage is static after preflop."},
];

const fourBetScenarios: Record<"4BP-01" | "4BP-02" | "4BP-03" | "4BP-04", S[]> = {
  "4BP-01": [
    {kind:"recognition",sourceRefs:["CP-G3-L10"],cueRu:"4BP low-SPR: геометрия банка и сжатие дерева.",cueEn:"4BP low-SPR: pot geometry and tree compression.",questionRu:"Что распознать прежде всего?",questionEn:"What should be recognized first?",goodRu:"Меньше будущих веток, но не automatic stack-off",goodEn:"Fewer future branches, but not an automatic stack-off",bad1Ru:"Low SPR сам выбирает action",bad1En:"Low SPR chooses the action by itself",bad2Ru:"SPR не влияет на planning",bad2En:"SPR does not affect planning",whyRu:"CP-G3-L10 использует low SPR как simplification geometry: дерево короче, но board/range/hand context остаётся.",whyEn:"Low SPR simplifies the geometry: the tree is shorter, but board/range/hand context remains.",badWhy1Ru:"Compression превращает SPR в answer key.",badWhy1En:"Compression turns SPR into an answer key.",badWhy2Ru:"Размер оставшегося stack не меняет будущие branches.",badWhy2En:"The remaining stack does not change future branches."},
    {kind:"recognition",sourceRefs:["CP-G3-L10"],cueRu:"После 4-bet на flop остаётся мало stack относительно pot.",cueEn:"After the 4-bet, little stack remains relative to the pot on the flop.",questionRu:"Какое следствие относится именно к compression?",questionEn:"Which consequence is specifically about compression?",goodRu:"Доступных sizing и будущих решений становится меньше",goodEn:"There are fewer available sizings and future decisions",bad1Ru:"Все made hands становятся равными по EV",bad1En:"All made hands become equal in EV",bad2Ru:"Board interaction перестаёт иметь значение",bad2En:"Board interaction stops mattering",whyRu:"Low SPR сокращает branch depth и пространство sizing, не выравнивая intrinsic value разных hand families.",whyEn:"Low SPR reduces branch depth and sizing space without equalizing the intrinsic value of different hand families.",badWhy1Ru:"Меньше streets стирает различия между hands.",badWhy1En:"Fewer streets erase differences between hands.",badWhy2Ru:"Compression отменяет arriving-range interaction.",badWhy2En:"Compression cancels arriving-range interaction."},
    {kind:"decision",sourceRefs:["CP-G3-L10"],cueRu:"Благоприятный или нейтральный 4BP flop сохраняет range advantage, а SPR низкий.",cueEn:"A favorable or neutral 4BP flop preserves range advantage and SPR is low.",questionRu:"Какое practical simplification поддерживает source?",questionEn:"Which practical simplification is strategically coherent here?",goodRu:"Небольшая ставка широким подходящим диапазоном",goodEn:"A small bet with a broad eligible range",bad1Ru:"Крупная ставка всей range из-за low SPR",bad1En:"A large bet with the whole range because SPR is low",bad2Ru:"Range-check независимо от range relation",bad2En:"Range-check regardless of range relation",whyRu:"L10 допускает small range-bet на подходящих compressed flops; exact size/frequency остаются configuration-dependent.",whyEn:"On suitable compressed flops, a small range bet can simplify the tree; exact size and frequency still depend on the configuration.",badWhy1Ru:"Compression требует максимального sizing.",badWhy1En:"Compression requires maximum sizing.",badWhy2Ru:"Low SPR сам по себе требует check.",badWhy2En:"Low SPR by itself requires a check."},
    {kind:"decision",sourceRefs:["CP-G3-L10"],cueRu:"Тот же low SPR, но flop становится очень неблагоприятным для range relation 4-bettor.",cueEn:"Same low SPR, but the flop becomes very unfavorable for the 4-bettor's range relation.",questionRu:"Что происходит с compressed default?",questionEn:"What happens to the compressed default?",goodRu:"Range-check может заменить small range-bet",goodEn:"Range-check can replace the small range bet",bad1Ru:"SPR сохраняет прежнюю ставку автоматически",bad1En:"The same SPR is enough reason to preserve the previous bet",bad2Ru:"Нужно увеличить sizing, чтобы компенсировать board",bad2En:"Increase sizing to compensate for the board",whyRu:"L10 сжимает flop tree до small range-bet или range-check в зависимости от range relation; compression не означает один action на всех boards.",whyEn:"A compressed flop tree can favor a small range bet or a range check depending on range relation; compression does not imply one action on every board.",badWhy1Ru:"Одинаковый SPR фиксирует одинаковую flop branch.",badWhy1En:"The same SPR fixes the same flop branch.",badWhy2Ru:"Неблагоприятный board автоматически лечится большим sizing.",badWhy2En:"An unfavorable board is automatically fixed by larger sizing."},
    {kind:"decision",sourceRefs:["CP-G3-L10"],cueRu:"Hero выбирает между двумя flop lines, которые оставят разный stack-to-pot ratio на turn.",cueEn:"Hero chooses between two flop lines that leave different SPR on the turn.",questionRu:"Что нужно сохранить в плане?",questionEn:"What must remain in the plan?",goodRu:"Геометрию следующей улицы, а не только текущий pot",goodEn:"The next-street geometry, not only the current pot",bad1Ru:"Только абсолютную силу hand сейчас",bad1En:"Only the hand's absolute strength now",bad2Ru:"Только сумму уже вложенных chips",bad2En:"Only the chips already invested",whyRu:"Compression означает, что текущий sizing быстро определяет оставшееся пространство будущих branches.",whyEn:"Compression means the current sizing quickly determines the remaining space for future branches.",badWhy1Ru:"При low SPR future tree не требует planning.",badWhy1En:"At low SPR the future tree needs no planning.",badWhy2Ru:"Sunk investment определяет следующий action.",badWhy2En:"Sunk investment determines the next action."},
    {kind:"changed",sourceRefs:["CP-G3-L10"],cueRu:"Hand и board те же; preflop pot больше, поэтому flop SPR materially ниже.",cueEn:"Same hand and board; the preflop pot is larger, so flop SPR is materially lower.",questionRu:"Какая causal variable изменила tree?",questionEn:"Which causal variable changed the tree?",goodRu:"Меньший SPR сократил sizing space и branch depth",goodEn:"Lower SPR reduced sizing space and branch depth",bad1Ru:"Меньший SPR сам усилил hand",bad1En:"The lower SPR itself strengthened the hand",bad2Ru:"Больший preflop pot сам перевернул range relation",bad2En:"The larger preflop pot itself reversed the range relation",whyRu:"Changed node изолирует SPR: геометрия сжимается при неизменных hand/board inputs.",whyEn:"The changed node isolates SPR: geometry compresses while hand/board inputs stay fixed.",badWhy1Ru:"SPR меняет intrinsic hand rank.",badWhy1En:"SPR changes intrinsic hand rank.",badWhy2Ru:"Размер pot сам меняет ownership board.",badWhy2En:"Pot size itself changes board ownership.",changedVariables:["spr"]},
    {kind:"changed",sourceRefs:["CP-G3-L10"],cueRu:"SPR остаётся тем же, но flop меняется с neutral на very unfavourable для 4-bettor range.",cueEn:"SPR stays the same, but the flop changes from neutral to very unfavorable for the 4-bettor's range.",questionRu:"Что может измениться при той же compression?",questionEn:"What can change despite the same compression?",goodRu:"Flop branch: small range-bet может стать range-check",goodEn:"The flop branch: a small range bet can become a range check",bad1Ru:"Ничего, потому что SPR тот же",bad1En:"Nothing, because SPR is unchanged",bad2Ru:"Только targetSeconds",bad2En:"Only targetSeconds",whyRu:"L10 отделяет geometry от range relation: одинаковый low SPR не делает разные boards стратегически одинаковыми.",whyEn:"Geometry and range relation remain separate variables: the same low SPR does not make different boards strategically identical.",badWhy1Ru:"Compression стирает board classification.",badWhy1En:"Compression erases board classification.",badWhy2Ru:"Board change не влияет на action family.",badWhy2En:"A board change does not affect the action family.",changedVariables:["board_range_relation"]},
    {kind:"boundary",sourceRefs:["CP-G3-L10"],cueRu:"Learner превращает «low SPR compresses the tree» в «low SPR dictates the action».",cueEn:"The learner turns 'low SPR compresses the tree' into 'low SPR dictates the action'.",questionRu:"Где граница simplification?",questionEn:"Where is the simplification boundary?",goodRu:"Compression сокращает branches, но action всё ещё зависит от range relation и hand context",goodEn:"Compression reduces branches, but action still depends on range relation and hand context",bad1Ru:"Один low-SPR default подходит всем boards",bad1En:"One low-SPR default fits every board",bad2Ru:"При low SPR можно игнорировать будущую агрессию",bad2En:"At low SPR future aggression can be ignored",whyRu:"Source explicitly treats low SPR as simplification, not universal commitment or universal betting authority.",whyEn:"Low SPR simplifies the tree; it does not create universal commitment or universal betting authority.",badWhy1Ru:"Одинаковая geometry означает одинаковую strategy.",badWhy1En:"Identical geometry means identical strategy.",badWhy2Ru:"Короткое дерево делает future response irrelevant.",badWhy2En:"A short tree makes future responses irrelevant."},
  ],
  "4BP-02": [
    {kind:"recognition",sourceRefs:["CP-G3-L10"],cueRu:"4BP low-SPR: hand-family commitment thresholds.",cueEn:"4BP low-SPR: hand-family commitment thresholds.",questionRu:"Что распознать прежде всего?",questionEn:"What should be recognized first?",goodRu:"Одинаковый SPR не делает разные hand families эквивалентными",goodEn:"The same SPR does not make different hand families equivalent",bad1Ru:"Low SPR делает все made hands stack-off",bad1En:"Low SPR makes all made hands stack-offs",bad2Ru:"Hand family не важна после 4-bet",bad2En:"Hand family does not matter after a 4-bet",whyRu:"L10 разделяет stable top-end, vulnerable value, hybrids, checking median и give-ups даже внутри compressed tree.",whyEn:"Stable top-end, vulnerable value, hybrids, checking median, and give-ups remain distinct hand families even inside a compressed tree.",badWhy1Ru:"Compression выравнивает EV всех hand classes.",badWhy1En:"Compression equalizes EV across all hand classes.",badWhy2Ru:"Preflop pot ancestry заменяет postflop hand evaluation.",badWhy2En:"Preflop pot ancestry replaces postflop hand evaluation."},
    {kind:"recognition",sourceRefs:["CP-G3-L10"],cueRu:"Две руки приходят в один и тот же low-SPR node: одна stable top-end, другая vulnerable value.",cueEn:"Two hands reach the same low-SPR node: one is stable top-end, the other vulnerable value.",questionRu:"Какой family distinction source сохраняет?",questionEn:"Which family distinction matters strategically here?",goodRu:"Stable hand может slow-play чаще; vulnerable value чаще нуждается в active branch",goodEn:"The stable hand can slow-play more; vulnerable value more often needs an active branch",bad1Ru:"Одинаковый SPR требует одинаковой линии",bad1En:"The same SPR requires the same line",bad2Ru:"По family label vulnerable value стоит ниже bluff candidates",bad2En:"By family label, vulnerable value belongs below bluff candidates",whyRu:"L10 прямо различает stable top-end и vulnerable value по urgency, не задавая универсальных frequencies.",whyEn:"Stable top-end can tolerate more trapping, while vulnerable value gains more from immediate value and protection; neither implies a universal frequency.",badWhy1Ru:"Geometry стирает vulnerability.",badWhy1En:"Geometry erases vulnerability.",badWhy2Ru:"Family label задаёт абсолютный ranking против всех ranges.",badWhy2En:"A family label sets an absolute ranking against every range."},
    {kind:"decision",sourceRefs:["CP-G3-L10"],cueRu:"Hero имеет stable top-end hand в compressed pot; check сохраняет opponent bluffs и worse value.",cueEn:"Hero has a stable top-end hand in a compressed pot; checking preserves opponent bluffs and worse value.",questionRu:"Как family влияет на urgency?",questionEn:"How does the family affect urgency?",goodRu:"Низкая vulnerability позволяет рассмотреть slow-play/check",goodEn:"Low vulnerability allows a slow-play/check to be considered",bad1Ru:"Low SPR обязывает bet любую strong hand",bad1En:"Low SPR forces a bet with every strong hand",bad2Ru:"Сама strength hand требует largest size",bad2En:"Hand strength by itself calls for the largest size",whyRu:"L10 сохраняет stable strong hands в passive branch, когда они не теряют слишком много от будущих cards/actions.",whyEn:"Stable strong hands can remain in the passive branch when future cards and actions do not cost them much value.",badWhy1Ru:"Hand strength автоматически требует immediate betting.",badWhy1En:"Hand strength automatically requires immediate betting.",badWhy2Ru:"Value class сам выбирает maximum sizing.",badWhy2En:"The value class itself chooses maximum sizing."},
    {kind:"decision",sourceRefs:["CP-G3-L10"],cueRu:"Hero имеет vulnerable value: сейчас впереди многих continues, но future cards могут ухудшить value/realisation.",cueEn:"Hero has vulnerable value: ahead of many continues now, but future cards can reduce value/realization.",questionRu:"Какой family pressure появляется?",questionEn:"Which family pressure appears?",goodRu:"Больше urgency к active value/protection branch",goodEn:"More urgency toward an active value/protection branch",bad1Ru:"Чек обязателен, потому что range должна быть protected",bad1En:"Checking is mandatory because the range must be protected",bad2Ru:"SPR сам гарантирует stack-off",bad2En:"SPR itself guarantees a stack-off",whyRu:"Compared with stable top-end, vulnerable value can gain more from immediate betting because protection is more urgent.",whyEn:"Compared with stable top-end, vulnerable value can gain more from immediate betting because protection is more urgent.",badWhy1Ru:"Protected checking требует поместить туда каждую strong hand.",badWhy1En:"Protected checking requires putting every strong hand there.",badWhy2Ru:"Compression заменяет family-specific urgency.",badWhy2En:"Compression replaces family-specific urgency."},
    {kind:"decision",sourceRefs:["CP-G3-L10"],cueRu:"Hand не чистое value и не чистый bluff: bet может получить fold better, call worse и deny equity.",cueEn:"The hand is neither pure value nor pure bluff: betting can fold better, get called by worse, and deny equity.",questionRu:"Как source классифицирует такой candidate?",questionEn:"How should such a candidate be classified?",goodRu:"Hybrid candidate, если full-tree EV и blocker effects это поддерживают",goodEn:"A hybrid candidate if full-tree EV and blocker effects support it",bad1Ru:"Automatic bluff, потому что hand не top value",bad1En:"An automatic bluff because the hand is not top value",bad2Ru:"Automatic check, потому что category смешанная",bad2En:"An automatic check because the category is mixed",whyRu:"L10 допускает hybrid bets, но требует оценивать весь tree и blocker effects вместо ярлыка.",whyEn:"Hybrid bets are coherent when full-tree incentives and blocker effects support them; the family label alone is not enough.",badWhy1Ru:"Любая не-top hand становится bluff.",badWhy1En:"Every non-top hand becomes a bluff.",badWhy2Ru:"Смешанный источник EV запрещает betting.",badWhy2En:"Mixed EV sources prohibit betting."},
    {kind:"changed",sourceRefs:["CP-G3-L10"],cueRu:"SPR, board и opponent range те же; hand меняется stable top-end → vulnerable value.",cueEn:"SPR, board, and opponent range stay the same; the hand changes from stable top-end → vulnerable value.",questionRu:"Что должно измениться?",questionEn:"What should change?",goodRu:"Urgency к immediate value/protection может вырасти",goodEn:"Urgency for immediate value/protection can increase",bad1Ru:"Ничего: одинаковый SPR фиксирует branch",bad1En:"Nothing: the same SPR fixes the branch",bad2Ru:"Только название hand, не incentives",bad2En:"Only the hand name, not the incentives",whyRu:"Changed node изолирует vulnerability/hand family: source разрешает stable hands slow-play чаще, vulnerable value — bet чаще.",whyEn:"The changed node isolates vulnerability and hand family: stable hands can slow-play more, while vulnerable value can prefer betting sooner.",badWhy1Ru:"SPR полностью определяет commitment.",badWhy1En:"SPR fully determines commitment.",badWhy2Ru:"Family differences не влияют на future EV.",badWhy2En:"Family differences do not affect future EV.",changedVariables:["hand_family","vulnerability"]},
    {kind:"changed",sourceRefs:["CP-G3-L10"],cueRu:"SPR и board те же; hand меняется checking-median → high-EV bluff/hybrid candidate с полезными blocker effects.",cueEn:"SPR and board stay the same; the hand changes from checking median → high-EV bluff/hybrid candidate with useful blocker effects.",questionRu:"Что меняется в family assignment?",questionEn:"What changes in the family assignment?",goodRu:"Active betting branch становится более убедительной",goodEn:"The active betting branch becomes more credible",bad1Ru:"Ничего, потому что обе руки не top value",bad1En:"Nothing, because neither hand is top value",bad2Ru:"Обе non-top-value hands относятся к jam branch",bad2En:"Both non-top-value hands belong in the jam branch",whyRu:"L10 строит turn geography по value/bluff/hybrid/median families; blocker effects помогают candidacy, но не задают exact frequency.",whyEn:"Turn strategy can separate value, bluff, hybrid, and median families; blocker effects inform candidacy without setting an exact frequency.",badWhy1Ru:"Все non-value hands имеют одинаковую role.",badWhy1En:"All non-value hands have the same role.",badWhy2Ru:"Low SPR превращает любую active candidate в jam.",badWhy2En:"Low SPR turns every active candidate into a jam.",changedVariables:["hand_family","blocker_effect"]},
    {kind:"boundary",sourceRefs:["CP-G3-L10"],cueRu:"Learner хочет использовать один stack-off threshold для stable value, vulnerable value, hybrid и bluff-catcher families.",cueEn:"The learner wants one stack-off threshold for stable value, vulnerable value, hybrid, and bluff-catcher families.",questionRu:"Где граница simplification?",questionEn:"Where is the simplification boundary?",goodRu:"Low SPR сжимает tree, но family-specific vulnerability и EV sources остаются",goodEn:"Low SPR compresses the tree, but family-specific vulnerability and EV sources remain",bad1Ru:"Один threshold достаточен для всех families",bad1En:"One threshold is sufficient for every family",bad2Ru:"Достаточно знать preflop hand rank",bad2En:"Preflop hand rank alone is sufficient",whyRu:"Source сохраняет несколько hand families внутри одного low-SPR framework; exact combo/frequency claims не нужны для этого distinction.",whyEn:"Multiple hand families remain distinct inside one low-SPR framework; this distinction does not require exact combo/frequency claims.",badWhy1Ru:"Compression делает family distinctions лишними.",badWhy1En:"Compression makes family distinctions unnecessary.",badWhy2Ru:"Postflop vulnerability не меняет commitment reasoning.",badWhy2En:"Postflop vulnerability does not change commitment reasoning."},
  ],
  "4BP-03": [
    {kind:"recognition",sourceRefs:["CP-G3-L10"],cueRu:"4BP low-SPR: protected checking.",cueEn:"4BP low-SPR: protected checking.",questionRu:"Что распознать прежде всего?",questionEn:"What should be recognized first?",goodRu:"Check branch может содержать strong hands и draws",goodEn:"The checking branch can contain strong hands and draws",bad1Ru:"Low SPR требует bet всех strong hands",bad1En:"Low SPR requires betting all strong hands",bad2Ru:"Check оставляет range capped, если strong hands обычно bet",bad2En:"Checking leaves the range capped if strong hands normally bet",whyRu:"L10 сохраняет strong hands, overpairs и draws в checking range, чтобы IP не мог profitably attack every check.",whyEn:"Keeping strong hands, overpairs, and draws in the checking range prevents IP from profitably attacking every check.",badWhy1Ru:"Compression уничтожает passive strength.",badWhy1En:"Compression eliminates passive strength.",badWhy2Ru:"Action check сам раскрывает weakness.",badWhy2En:"The check action itself reveals weakness."},
    {kind:"recognition",sourceRefs:["CP-G3-L10"],cueRu:"Hero checks low-SPR turn и всё ещё может credibly check-call или check-jam часть range.",cueEn:"Hero checks a low-SPR turn and can still credibly check-call or check-jam part of the range.",questionRu:"Какой signal это даёт?",questionEn:"What signal does this provide?",goodRu:"Checking branch остаётся protected",goodEn:"The checking branch remains protected",bad1Ru:"Check означает surrender",bad1En:"Checking means surrender",bad2Ru:"Нужно было bet 100% range",bad2En:"Hero should have bet 100% of range",whyRu:"L10 operational gate: credible check-call/check-jam уменьшает urgency немедленной ставки.",whyEn:"Credible check-call and check-jam branches reduce the urgency to bet immediately by keeping the passive branch protected.",badWhy1Ru:"Passive action не может содержать strong continues.",badWhy1En:"A passive action cannot contain strong continues.",badWhy2Ru:"Protection возможна только через betting.",badWhy2En:"Protection is possible only through betting."},
    {kind:"decision",sourceRefs:["CP-G3-L10"],cueRu:"Stable top-end hand может check, а opponent после check продолжит с bluffs и worse value.",cueEn:"A stable top-end hand can check while the opponent continues with bluffs and worse value after the check.",questionRu:"Какой branch source допускает?",questionEn:"Which branch remains strategically coherent here?",goodRu:"Protected slow-play/check",goodEn:"A protected slow-play/check",bad1Ru:"Bet обязательно из-за low SPR",bad1En:"Betting is mandatory because SPR is low",bad2Ru:"Check только с give-ups",bad2En:"Check only with give-ups",whyRu:"Stable top-end hands могут slow-play чаще и одновременно защищать checking range.",whyEn:"Stable top-end hands can slow-play more often while protecting the checking range.",badWhy1Ru:"Low SPR запрещает delayed value.",badWhy1En:"Low SPR forbids delayed value.",badWhy2Ru:"Checking range должна быть intentionally capped.",badWhy2En:"The checking range should be intentionally capped."},
    {kind:"decision",sourceRefs:["CP-G3-L10"],cueRu:"Hero хочет range-check, но после check у него нет убедительных strong calls или jams.",cueEn:"Hero wants to range-check, but after checking has no credible strong calls or jams.",questionRu:"Что говорит source gate?",questionEn:"What does this protection requirement imply?",goodRu:"Checking branch может быть exposed; immediate betting становится более urgent",goodEn:"The checking branch may be exposed; immediate betting becomes more urgent",bad1Ru:"Range-check всё равно protected самим low SPR",bad1En:"The range check is protected by low SPR itself",bad2Ru:"IP не может атаковать check в 4BP",bad2En:"IP cannot attack a check in a 4BP",whyRu:"L10 прямо связывает допустимость protected check с credible check-call/check-jam continuation.",whyEn:"Protected checking requires credible strong continuations such as check-call and check-jam branches.",badWhy1Ru:"SPR автоматически создаёт strong passive branch.",badWhy1En:"SPR automatically creates a strong passive branch.",badWhy2Ru:"Pot type запрещает opponent aggression.",badWhy2En:"The pot type prevents opponent aggression."},
    {kind:"decision",sourceRefs:["CP-G3-L10"],cueRu:"Checking range содержит только median hands и give-ups, а все strong hands всегда bet.",cueEn:"The checking range contains only median hands and give-ups because all strong hands always bet.",questionRu:"Какой leak возникает?",questionEn:"Which leak appears?",goodRu:"IP получает слишком чистую ветку для pressure после check",goodEn:"IP gets too clean a pressure branch after the check",bad1Ru:"Check становится сильнее, потому что pot меньше",bad1En:"The check becomes stronger because the pot is smaller",bad2Ru:"Никакого: low SPR делает range protection ненужной",bad2En:"None: low SPR makes range protection unnecessary",whyRu:"Если strong region полностью покидает check, passive branch становится exploitable; L10 поэтому сохраняет strength внутри check.",whyEn:"If the strong region fully leaves the check, the passive branch becomes exploitable; keeping some strength in check protects it.",badWhy1Ru:"Меньший pot сам защищает capped range.",badWhy1En:"A smaller pot protects a capped range by itself.",badWhy2Ru:"Compression отменяет need for range construction.",badWhy2En:"Compression removes the need for range construction."},
    {kind:"changed",sourceRefs:["CP-G3-L10"],cueRu:"Board/SPR те же; checking branch меняется с credible check-call/check-jam coverage на отсутствие strong continues.",cueEn:"Board/SPR stay the same; the checking branch changes from credible check-call/check-jam coverage to no strong continues.",questionRu:"Как меняется incentive к immediate bet?",questionEn:"How does the incentive to bet immediately change?",goodRu:"Растёт: check теперь хуже защищён",goodEn:"It increases: the check is now less protected",bad1Ru:"Не меняется, потому что SPR тот же",bad1En:"It does not change because SPR is the same",bad2Ru:"Падает, потому что weak check заманивает opponent",bad2En:"It falls because a weak check lures the opponent",whyRu:"Changed node изолирует protection coverage — именно causal variable из L10 gate.",whyEn:"The changed node isolates protection coverage: stronger credible continuations make the checking branch harder to attack.",badWhy1Ru:"SPR один определяет bet/check split.",badWhy1En:"SPR alone determines the bet/check split.",badWhy2Ru:"Незащищённый check автоматически создаёт profitable trap.",badWhy2En:"An unprotected check automatically creates a profitable trap.",changedVariables:["check_continuation_strength"]},
    {kind:"changed",sourceRefs:["CP-G3-L10"],cueRu:"SPR и range relation те же; hand меняется stable strong → vulnerable value.",cueEn:"SPR and range relation stay the same; the hand changes from stable strong → vulnerable value.",questionRu:"Как меняется checking incentive?",questionEn:"How does the checking incentive change?",goodRu:"Может снизиться: vulnerable value чаще нуждается в immediate action",goodEn:"It can decrease: vulnerable value more often needs immediate action",bad1Ru:"Не меняется, потому что обе hands strong",bad1En:"It does not change because both hands are strong",bad2Ru:"Check становится обязательным для vulnerable hand",bad2En:"Checking becomes mandatory for the vulnerable hand",whyRu:"L10 разрешает stable top-end slow-play чаще, тогда как vulnerable value может bet чаще.",whyEn:"Stable top-end hands can slow-play more often, while vulnerable value can prefer betting sooner because protection matters more.",badWhy1Ru:"Absolute strength label стирает vulnerability.",badWhy1En:"An absolute strength label erases vulnerability.",badWhy2Ru:"Protected checking требует выбирать самые vulnerable hands.",badWhy2En:"Protected checking requires choosing the most vulnerable hands.",changedVariables:["hand_stability","vulnerability"]},
    {kind:"boundary",sourceRefs:["CP-G3-L10"],cueRu:"Learner считает: «если protected checks существуют, любую strong hand лучше check».",cueEn:"The learner says: 'if protected checks exist, every strong hand is better checked.'",questionRu:"Где граница?",questionEn:"Where is the boundary?",goodRu:"Protection требует некоторой strength в check, но vulnerable value всё ещё может предпочитать bet",goodEn:"Protection requires some strength in the check, but vulnerable value can still prefer betting",bad1Ru:"Все strong hands должны check",bad1En:"All strong hands should check",bad2Ru:"Все strong hands должны bet",bad2En:"All strong hands should bet",whyRu:"Source сохраняет strong checks без превращения их в universal slow-play rule; urgency зависит от stability/vulnerability и branch incentives.",whyEn:"Strong checks can protect the checking branch without becoming a universal slow-play rule; urgency still depends on stability/vulnerability and branch incentives.",badWhy1Ru:"Range protection требует 100% strong checks.",badWhy1En:"Range protection requires 100% strong checks.",badWhy2Ru:"Low SPR запрещает strong checks.",badWhy2En:"Low SPR forbids strong checks."},
  ],
  "4BP-04": [
    {kind:"recognition",sourceRefs:["CP-G3-L10"],cueRu:"4BP low-SPR: jam/reopen exposure и investment ceiling.",cueEn:"4BP low-SPR: jam/reopen exposure and the investment ceiling.",questionRu:"Что распознать прежде всего?",questionEn:"What should be recognized first?",goodRu:"Следующую aggressive branch нужно планировать до новой инвестиции",goodEn:"The next aggressive branch must be planned before new investment",bad1Ru:"Сначала bet, потом решать против jam",bad1En:"Bet first, then decide against a jam",bad2Ru:"Уже большой pot делает next call обязательным",bad2En:"The already-large pot makes the next call mandatory",whyRu:"Future jam exposure belongs in current size selection because the chosen size changes the response tree.",whyEn:"Future jam exposure belongs in current size selection because the chosen size changes the response tree.",badWhy1Ru:"Future response не влияет на current sizing.",badWhy1En:"The future response does not affect current sizing.",badWhy2Ru:"Sunk chips создают commitment независимо от EV.",badWhy2En:"Sunk chips create commitment regardless of EV."},
    {kind:"recognition",sourceRefs:["CP-G3-L10"],cueRu:"Turn bet оставит настолько мало behind, что IP получает удобный jam branch.",cueEn:"A turn bet leaves so little behind that IP gets a convenient jam branch.",questionRu:"Какой risk нужно увидеть до bet?",questionEn:"Which risk must be seen before betting?",goodRu:"Sizing может повысить jam frequency и ухудшить equity realisation medium-EV hands",goodEn:"Sizing can raise jam frequency and hurt equity realization for medium-EV hands",bad1Ru:"Jam exposure появляется только после bet и не относится к sizing",bad1En:"Jam exposure appears only after betting and is unrelated to sizing",bad2Ru:"Low SPR гарантирует profitable call против jam",bad2En:"Low SPR guarantees a profitable call against a jam",whyRu:"L10 выделяет dangerous jam-exposure band, где слишком большой bet делает и call, и fold против jam болезненными.",whyEn:"Betting too large can enter a jam-exposure band where both calling and folding versus a jam become costly.",badWhy1Ru:"Current sizing не меняет opponent reopen incentives.",badWhy1En:"Current sizing does not change opponent reopen incentives.",badWhy2Ru:"Compression автоматически решает jam response.",badWhy2En:"Compression automatically solves the jam response."},
    {kind:"decision",sourceRefs:["CP-G3-L10"],cueRu:"Medium-EV hand может выбрать меньший turn barrel или больший bet, который создаёт damaging jam exposure.",cueEn:"A medium-EV hand can choose a smaller turn barrel or a larger bet that creates damaging jam exposure.",questionRu:"Какой filter должен участвовать в sizing?",questionEn:"Which filter must participate in sizing?",goodRu:"Будущий jam response и предел вложений Hero",goodEn:"Hero's future jam response and investment ceiling",bad1Ru:"Только текущее equity",bad1En:"Only current equity",bad2Ru:"Только желание увеличить pot",bad2En:"Only the desire to grow the pot",whyRu:"L10 включает future jam branch в size selection, особенно для medium-EV hands.",whyEn:"Size selection should include the future jam branch, especially for medium-EV hands that dislike reopening pressure.",badWhy1Ru:"Одно-street equity полностью определяет sizing.",badWhy1En:"One-street equity fully determines sizing.",badWhy2Ru:"Больший pot всегда повышает EV medium hand.",badWhy2En:"A larger pot always increases a medium hand's EV."},
    {kind:"decision",sourceRefs:["CP-G3-L10"],cueRu:"Opponent range остаётся relatively polar; larger turn size рискует overpay for indifference и открыть damaging jams.",cueEn:"The opponent range remains relatively polar; a larger turn size risks overpaying for indifference and opening damaging jams.",questionRu:"Какой direction source допускает?",questionEn:"Which sizing direction remains strategically coherent here?",goodRu:"Меньший barrel может быть достаточен",goodEn:"A smaller barrel can be sufficient",bad1Ru:"При low SPR largest size предпочтительнее сам по себе",bad1En:"At low SPR, the largest size is preferable by itself",bad2Ru:"Sizing не связан с opponent range shape",bad2En:"Sizing is unrelated to opponent range shape",whyRu:"L10 связывает smaller turn price с polar caller range и одновременно учитывает jam exposure.",whyEn:"Against a polar caller range, a smaller turn price can achieve the objective while limiting unnecessary jam exposure.",badWhy1Ru:"Compression требует maximum leverage независимо от response.",badWhy1En:"Compression requires maximum leverage regardless of the response.",badWhy2Ru:"Range shape не влияет на required price.",badWhy2En:"Range shape does not affect the required price."},
    {kind:"decision",sourceRefs:["CP-G3-L10"],cueRu:"Перед bet Hero не знает, будет ли call или fold против jam после выбранного sizing.",cueEn:"Before betting, Hero does not know whether the plan is call or fold against a jam after the chosen sizing.",questionRu:"Что это говорит о plan?",questionEn:"What does that say about the plan?",goodRu:"Sizing ещё не завершён: нужно определить response branch до вложения",goodEn:"The sizing plan is incomplete: define the response branch before investing",bad1Ru:"Можно bet и решить только после jam",bad1En:"Bet now and decide only after the jam",bad2Ru:"Уже большой pot сам делает call правильным",bad2En:"The already-large pot itself makes the call correct",whyRu:"Investment ceiling требует заранее знать, сколько Hero готов вложить и что делает против reopen/jam.",whyEn:"The investment ceiling requires knowing in advance how much Hero is willing to invest and what happens versus a reopen/jam.",badWhy1Ru:"Первый bet можно оценивать отдельно от response tree.",badWhy1En:"The first bet can be evaluated separately from the response tree.",badWhy2Ru:"Sunk pot определяет future call.",badWhy2En:"The sunk pot determines the future call."},
    {kind:"changed",sourceRefs:["CP-G3-L10"],cueRu:"Hand и opponent range те же; turn sizing увеличивается и оставляет намного меньше behind.",cueEn:"Same hand and opponent range; turn sizing increases and leaves much less behind.",questionRu:"Какая exposure меняется?",questionEn:"Which exposure changes?",goodRu:"Jam/reopen становится удобнее и может ухудшить realisation",goodEn:"Jam/reopen becomes easier and can hurt realization",bad1Ru:"Никакая: hand/board те же",bad1En:"None: the hand/board are unchanged",bad2Ru:"Больший bet сам даёт Hero больше showdown value",bad2En:"A larger bet itself gives Hero more showdown value",whyRu:"Changed node изолирует bet size/stack behind — causal driver jam-exposure band в L10.",whyEn:"The changed node isolates bet size and stack behind: together they determine how much future jam exposure the current bet creates.",badWhy1Ru:"Sizing не меняет future action incentives.",badWhy1En:"Sizing does not change future action incentives.",badWhy2Ru:"Больший bet меняет intrinsic hand strength.",badWhy2En:"A larger bet changes intrinsic hand strength.",changedVariables:["bet_size","stack_behind","jam_exposure"]},
    {kind:"changed",sourceRefs:["CP-G3-L10"],cueRu:"Bet size и ranges те же; remaining SPR становится ниже перед turn decision.",cueEn:"Bet size and ranges stay the same; remaining SPR is lower before the turn decision.",questionRu:"Как меняется jam planning?",questionEn:"How does jam planning change?",goodRu:"Future jam branch становится более immediate и должна весить сильнее",goodEn:"The future jam branch becomes more immediate and must weigh more heavily",bad1Ru:"Не меняется: sizing тот же",bad1En:"It does not change because sizing is the same",bad2Ru:"Низкий SPR отменяет investment ceiling",bad2En:"Low SPR removes the investment ceiling",whyRu:"L10 называет lower SPR одним из факторов роста jam frequency; exact threshold не требуется.",whyEn:"Lower SPR can increase jam frequency by shortening the remaining tree; no exact threshold is required.",badWhy1Ru:"Only bet size can affect jam exposure.",badWhy1En:"Only bet size can affect jam exposure.",badWhy2Ru:"Compression делает future investment irrelevant.",badWhy2En:"Compression makes future investment irrelevant.",changedVariables:["spr","jam_exposure"]},
    {kind:"boundary",sourceRefs:["CP-G3-L10"],cueRu:"Learner выбирает turn sizing без заранее определённого ответа на jam/reopen.",cueEn:"The learner chooses a turn sizing without a predefined response to a jam/reopen.",questionRu:"Где граница такого plan?",questionEn:"Where is the boundary of that plan?",goodRu:"До bet нужно проверить jam exposure и investment ceiling",goodEn:"Jam exposure and the investment ceiling must be checked before betting",bad1Ru:"Jam response можно отложить до момента после вложения",bad1En:"The jam response can be deferred until after investing",bad2Ru:"Low SPR делает любой reopen call обязательным",bad2En:"Low SPR makes every reopen call mandatory",whyRu:"L10 делает future jam exposure частью current decision; sunk investment не заменяет EV response.",whyEn:"Future jam exposure is part of the current decision; sunk investment does not replace the EV of the response branch.",badWhy1Ru:"Current action независим от next branch.",badWhy1En:"The current action is independent of the next branch.",badWhy2Ru:"Compression равна automatic commitment.",badWhy2En:"Compression equals automatic commitment."},
  ],
};

function fourBet(skillId: keyof typeof fourBetScenarios, prefix: string): PracticalDecision[] {
  return make(skillId, prefix, fourBetScenarios[skillId]);
}

export const threeBetFourBetA7ExpansionDecisions: PracticalDecision[] = [
  ...make("3BP-01","PM-3BP-01-A7",aggrIp),
  ...make("3BP-02","PM-3BP-02-A7",aggrOop),
  ...make("3BP-03","PM-3BP-03-A7",callerIp),
  ...make("3BP-04","PM-3BP-04-A7",callerOop),
  ...make("3BP-05","PM-3BP-05-A7",matrix),
  ...fourBet("4BP-01","PM-4BP-01-A7"),
  ...fourBet("4BP-02","PM-4BP-02-A7"),
  ...fourBet("4BP-03","PM-4BP-03-A7"),
  ...fourBet("4BP-04","PM-4BP-04-A7"),
];
