import type { PracticalDecision } from "./types";

const o = (id: string, textRu: string, textEn: string, misconception?: string) => ({ id, textRu, textEn, misconception });

export const foundationPreflopBlindDecisions: PracticalDecision[] = [
  {
    id: "PM-FND-01-001", skillId: "FND-01", kind: "recognition", sourceRefs: ["FTGU-E01"],
    assumptions: ["all-in", "call 1bb to win 2bb", "no future betting"],
    cueRu: "В банке 1bb, соперник ставит 1bb. Hero должен доставить 1bb, и дальше ставок не будет.", cueEn: "Hero risks 1 to win 2.",
    questionRu: "Какой вывод о требуемой equity верный?", questionEn: "Which statement about required equity is correct?",
    actionOptions: [
      o("a", "Для call нужно около 33% equity", "The call requires about 33% equity"),
      o("b", "Для call нужно больше 50% equity", "The call requires more than 50% equity", "WIN_RATE_50_SHORTCUT"),
      o("c", "Требуемая equity не зависит от цены", "Required equity does not depend on price", "PRICE_IGNORED"),
    ],
    reasonOptions: [
      o("r1", "Pot odds 1:2 задают порог безубыточности около 33%", "Pot odds determine the break-even threshold"),
      o("r2", "Нужно выигрывать большинство раздач", "The hand must win most runouts", "WIN_RATE_50_SHORTCUT"),
      o("r3", "Equity и EV всегда одно и то же", "Equity and EV are always the same", "EQUITY_EQUALS_EV"),
    ],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25,
    explanationRu: "Hero платит 1bb за шанс выиграть 2bb, уже лежащие в банке. Это pot odds 1:2, поэтому для безубыточного call достаточно около 33% equity, а не 50%.",
    explanationEn: "FTGU-E01 explicitly shows that risking 1 to win 2 gives a break-even threshold around one third, not 50%.",
  },
  {
    id: "PM-FND-02-001", skillId: "FND-02", kind: "decision", sourceRefs: ["FTGU-E01", "FTGU-E05"],
    assumptions: ["meaningful stack remains", "Hero OOP", "future pressure possible"],
    cueRu: "У Hero заметное raw equity, но он OOP и может часто fold на будущих улицах.", cueEn: "Hero has meaningful raw equity but is OOP and may fold often on future streets.",
    questionRu: "Что использовать для решения?", questionEn: "What should drive the decision?",
    actionOptions: [
      o("a", "Оценить realisation и будущие EV-ветки", "Evaluate realization and future EV branches"),
      o("b", "Смотреть только на raw equity", "Look only at raw equity", "RAW_EQUITY_ONLY"),
      o("c", "Всегда продолжать, если equity выше 25%", "Always continue if equity is above 25%", "UNSUPPORTED_THRESHOLD"),
    ],
    reasonOptions: [
      o("r1", "Equity может быть сдана до showdown; позиция и future action влияют на EV", "Equity can be surrendered before showdown; position and future action affect EV"),
      o("r2", "Raw equity автоматически реализуется полностью", "Raw equity is automatically realized in full", "RAW_EQUITY_ONLY"),
      o("r3", "OOP не влияет на будущие решения", "Being OOP does not affect future decisions", "POSITION_IGNORED"),
    ],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30,
    explanationRu: "FTGU-E01 отделяет equity от EV, а FTGU-E05 подчёркивает роль postflop execution для marginal defends.",
    explanationEn: "FTGU-E01 separates equity from EV, while FTGU-E05 emphasizes postflop execution for marginal defenses.",
  },
  {
    id: "PM-FND-05-001", skillId: "FND-05", kind: "recognition", sourceRefs: ["FTGU-E11"],
    assumptions: ["preflop", "no cards removed"],
    cueRu: "Стандартные preflop combo counts.", cueEn: "Standard preflop combo counts.",
    questionRu: "Какой набор верный: pocket pair / suited / offsuit?", questionEn: "Which set is correct: pocket pair / suited / offsuit?",
    actionOptions: [o("a", "6 / 4 / 12", "6 / 4 / 12"), o("b", "4 / 6 / 16", "4 / 6 / 16", "COMBO_COUNT_SWAP"), o("c", "6 / 4 / 16", "6 / 4 / 16", "OFFSUIT_16")],
    reasonOptions: [o("r1", "Hand class содержит exact suit combinations, а board/hole cards позже их удаляют", "A hand class contains exact suit combinations, and board/hole cards remove them later"), o("r2", "Каждая offsuit hand всегда имеет 16 playable combos", "Every offsuit hand always has 16 playable combos", "OFFSUIT_16"), o("r3", "Combo count важен только preflop", "Combo counting matters only preflop", "NO_POSTFLOP_REMOVAL")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 20,
    explanationRu: "FTGU-E11 даёт стандартные counts 6/4/12 и требует пересчитывать removal после board/action changes.",
    explanationEn: "FTGU-E11 gives the standard counts 6/4/12 and requires recounting removal after board/action changes.",
  },
  {
    id: "PM-PF-01-001", skillId: "PF-01", kind: "changed", sourceRefs: ["FTGU-E02"],
    assumptions: ["same fringe hand", "same rake/stack", "HJ -> BTN"],
    cueRu: "Та же fringe hand перемещается из HJ на BTN.", cueEn: "The same fringe hand moves from HJ to BTN.",
    questionRu: "Как меняется open attractiveness?", questionEn: "How does opening attractiveness change?",
    actionOptions: [o("a", "Обычно растёт", "It generally increases"), o("b", "Не меняется", "It does not change", "POSITION_IGNORED"), o("c", "Обычно падает из-за более широкой range", "It generally falls because the range is wider", "BACKWARDS_POSITION_LOGIC")],
    reasonOptions: [o("r1", "Меньше игроков позади и лучше realisation", "Fewer players remain and realization is better"), o("r2", "BTN платит больше rake автоматически", "BTN automatically pays more rake", "FALSE_RAKE_POSITION"), o("r3", "Position влияет только postflop, не на open", "Position affects only postflop, not opening", "POSITION_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25,
    explanationRu: "FTGU-E02 описывает постепенное расширение opening range к поздним позициям из-за fewer players behind и лучшей realisation.",
    explanationEn: "FTGU-E02 describes gradual widening toward late position because fewer players remain and realization improves.",
    changedVariables: ["position", "players_behind"],
  },
  {
    id: "PM-PF-02-001", skillId: "PF-02", kind: "decision", sourceRefs: ["FTGU-E03"],
    assumptions: ["multiple limpers", "low fold equity", "likely multiway", "implied-odds hand"],
    cueRu: "Несколько limpers, folds почти не ожидаются, pot часто будет multiway.", cueEn: "Several limpers, little fold equity, pot likely goes multiway.",
    questionRu: "Какая ветка заслуживает приоритетной проверки?", questionEn: "Which branch deserves priority consideration?",
    actionOptions: [o("a", "Overlimp / малая инвестиция", "Overlimp / small investment"), o("b", "Огромный iso независимо от состава стола", "Huge isolation raise regardless of the table", "ISO_AUTOPILOT"), o("c", "Всегда fold implied-odds hands", "Always fold implied-odds hands", "OVERFOLD_IMPLIED_ODDS")],
    reasonOptions: [o("r1", "При плохом fold equity малая инвестиция может лучше сохранять implied odds", "With poor fold equity, a small investment can better preserve implied odds"), o("r2", "Iso гарантирует heads-up pot", "Isolation guarantees a heads-up pot", "ISO_GUARANTEES_HU"), o("r3", "Multiway всегда уничтожает implied odds", "Multiway always destroys implied odds", "MULTIWAY_ALWAYS_BAD")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30,
    explanationRu: "FTGU-E03 прямо рекомендует оценивать iso/overlimp/fold через frequent strength, fold equity и position.",
    explanationEn: "FTGU-E03 explicitly frames isolate/overlimp/fold through frequent strength, fold equity and position.",
  },
  {
    id: "PM-PF-03-001", skillId: "PF-03", kind: "decision", sourceRefs: ["FTGU-E04"],
    assumptions: ["Hero IP", "call looks profitable heads-up", "aggressive squeezers behind"],
    cueRu: "IP cold-call выглядит нормально против opener, но позади активные squeezers.", cueEn: "The IP cold call looks fine versus the opener, but aggressive squeezers remain behind.",
    questionRu: "Что делать с оценкой call?", questionEn: "How should the call be evaluated?",
    actionOptions: [o("a", "Пересчитать EV с учётом players behind", "Recalculate EV including players behind"), o("b", "Игнорировать BB/SB, потому что Hero IP", "Ignore BB/SB because Hero is IP", "PLAYERS_BEHIND_IGNORED"), o("c", "Call всегда лучше 3-bet с suited hand", "Calling is always better than 3-betting with a suited hand", "SUITED_CALL_AUTOPILOT")],
    reasonOptions: [o("r1", "Squeeze risk и multiway participation меняют realisation", "Squeeze risk and multiway participation change realization"), o("r2", "Cold-call range никогда не бывает capped", "A cold-call range is never capped", "CAPPEDNESS_IGNORED"), o("r3", "Позиция отменяет риск squeeze", "Position eliminates squeeze risk", "PLAYERS_BEHIND_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30,
    explanationRu: "FTGU-E04 делает players behind частью EV call и объясняет vulnerability capped cold-call ranges к squeeze.",
    explanationEn: "FTGU-E04 makes players behind part of call EV and explains the squeeze vulnerability of capped cold-call ranges.",
  },
  {
    id: "PM-PF-04-001", skillId: "PF-04", kind: "decision", sourceRefs: ["FTGU-E05"],
    assumptions: ["Hero BB", "closes action", "small open", "wide late-position range"],
    cueRu: "BB получает discount и закрывает action против wide late-position open.", cueEn: "BB gets a discount and closes the action versus a wide late-position open.",
    questionRu: "Как сравнивать marginal call?", questionEn: "How should a marginal call be compared?",
    actionOptions: [o("a", "С EV fold, учитывая уже потерянный blind", "Against the EV of folding, including the blind already invested"), o("b", "С нулём, будто blind не поставлен", "Against zero as if the blind were not posted", "SUNK_BLIND_IGNORED"), o("c", "Только по тому, выигрывает ли hand >50%", "Only by whether the hand wins more than 50%", "WIN_RATE_50_SHORTCUT")],
    reasonOptions: [o("r1", "Pot odds и dead money могут сделать losing-most-pots call лучше fold", "Pot odds and dead money can make a call that loses most pots better than folding"), o("r2", "BB всегда обязан защищать любую suited hand", "BB must always defend any suited hand", "BB_ANY_SUITED"), o("r3", "Closing action не влияет на EV", "Closing the action does not affect EV", "CLOSING_ACTION_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30,
    explanationRu: "FTGU-E05 прямо требует сравнивать call с автоматической потерей fold, а не с нулём.",
    explanationEn: "FTGU-E05 explicitly says to compare the call with the automatic loss from folding, not with zero.",
  },
  {
    id: "PM-PF-05-001", skillId: "PF-05", kind: "decision", sourceRefs: ["FTGU-E06"],
    assumptions: ["Hero SB", "faces open", "competent BB behind"],
    cueRu: "SB рассматривает passive flat, BB ещё действует.", cueEn: "SB considers a passive flat while BB still acts.",
    questionRu: "Какой structural cost нельзя игнорировать?", questionEn: "Which structural cost cannot be ignored?",
    actionOptions: [o("a", "Squeeze risk + poor realisation OOP", "Squeeze risk plus poor OOP realization"), o("b", "Никакой: SB получает ту же цену, что BB", "None: SB gets the same price as BB", "SB_EQUALS_BB"), o("c", "Только отсутствие initiative", "Only lack of initiative", "SINGLE_FACTOR")],
    reasonOptions: [o("r1", "SB не закрывает action, получает хуже price и может потерять equity до flop", "SB does not close the action, gets a worse price and can lose equity before the flop"), o("r2", "BB никогда не squeezes cold-call", "BB never squeezes a cold call", "NO_SQUEEZE"), o("r3", "Position не влияет после preflop call", "Position does not matter after a preflop call", "POSITION_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30,
    explanationRu: "FTGU-E06 делает poor price, OOP и squeeze risk центральными причинами слабости SB flats.",
    explanationEn: "FTGU-E06 makes poor price, OOP play and squeeze risk central reasons SB flats are weak.",
  },
  {
    id: "PM-PF-06-001", skillId: "PF-06", kind: "changed", sourceRefs: ["FTGU-E15"],
    assumptions: ["opponent continues too much", "fold equity low"],
    cueRu: "3-bet получает мало folds и часто играет called pot.", cueEn: "The 3-bet gets few folds and often plays a called pot.",
    questionRu: "Какой range shape обычно получает больше смысла?", questionEn: "Which range shape generally makes more sense?",
    actionOptions: [o("a", "Более linear", "More linear"), o("b", "Максимально polar с большим количеством слабых bluff hands", "Maximally polar with many weak bluff hands", "POLAR_WITHOUT_FOLDS"), o("c", "Shape не связан с opponent response", "Shape is unrelated to opponent response", "RESPONSE_IGNORED")],
    reasonOptions: [o("r1", "При low fold equity важнее hands, которые лучше играют when called", "With low fold equity, hands that perform best when called matter more"), o("r2", "Bluff hands всегда лучше value hands в 3-bet pot", "Bluff hands are always better than value hands in 3-bet pots", "BLUFF_PRIORITY"), o("r3", "Fold equity влияет только на size, не на range", "Fold equity affects only size, not range", "SHAPE_SIZE_DISCONNECTED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25,
    explanationRu: "FTGU-E15 связывает low fold equity с более linear value/isolation construction.",
    explanationEn: "FTGU-E15 links low fold equity with more linear value/isolation construction.",
    changedVariables: ["fold_equity", "opponent_continuation"],
  },
  {
    id: "PM-PF-07-001", skillId: "PF-07", kind: "changed", sourceRefs: ["FTGU-E17"],
    assumptions: ["same opening range", "larger 3-bet", "Hero OOP"],
    cueRu: "3-bet становится крупнее, Hero остаётся OOP.", cueEn: "The 3-bet becomes larger while Hero remains OOP.",
    questionRu: "Как должна двигаться defence?", questionEn: "How should defense move?",
    actionOptions: [o("a", "В сторону большего количества folds", "Toward more folds"), o("b", "В сторону более широких calls", "Toward wider calls", "PRICE_BACKWARDS"), o("c", "Не менять из-за fixed 50% rule", "Do not change because of a fixed 50% rule", "FIFTY_PERCENT_LAW")],
    reasonOptions: [o("r1", "Larger size и OOP ухудшают price/realisation", "Larger size and OOP worsen price/realization"), o("r2", "50% — точная equilibrium константа", "50% is an exact equilibrium constant", "FIFTY_PERCENT_LAW"), o("r3", "Size влияет только на pot, но не на defence", "Size affects only the pot, not defense", "SIZE_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25,
    explanationRu: "FTGU-E17 прямо говорит, что larger bets и OOP justify more folds; 50% — ballpark baseline, не закон.",
    explanationEn: "FTGU-E17 explicitly says larger bets and OOP justify more folds; 50% is a ballpark baseline, not a law.",
    changedVariables: ["three_bet_size", "position"],
  },
  {
    id: "PM-PF-08-001", skillId: "PF-08", kind: "boundary", sourceRefs: ["FTGU-E18"],
    assumptions: ["underbluffing recreational 3-bet range"],
    cueRu: "Оппонент underbluffs 3-bets и редко имеет нужный bluff volume.", cueEn: "Opponent underbluffs 3-bets and rarely has the required bluff volume.",
    questionRu: "Нужно ли сохранять balanced polar 4-bet bluff package?", questionEn: "Must Hero preserve a balanced polar 4-bet bluff package?",
    actionOptions: [o("a", "Нет, сдвигаться value-heavy/tighter", "No, shift value-heavy/tighter"), o("b", "Да, solver balance важнее opponent range", "Yes, solver balance matters more than opponent range", "BALANCE_OVER_EVIDENCE"), o("c", "Добавить ещё больше blocker bluffs", "Add even more blocker bluffs", "BLOCKER_AUTOPILOT")],
    reasonOptions: [o("r1", "Bluff 4-bets требуют folds; underbluffing/value-heavy branch удаляет часть bluff incentives", "Bluff 4-bets require folds; an underbluffing/value-heavy branch removes some bluff incentives"), o("r2", "Blocker сам по себе делает bluff profitable", "A blocker alone makes a bluff profitable", "BLOCKER_AUTOPILOT"), o("r3", "Opponent type не влияет на 4-bet architecture", "Opponent type does not affect 4-bet architecture", "OPPONENT_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30,
    explanationRu: "FTGU-E18 прямо убирает часть balanced bluffs против underbluffing recreational ranges.",
    explanationEn: "FTGU-E18 explicitly removes balanced bluffs against underbluffing recreational ranges.",
  },
  {
    id: "PM-BL-03-001", skillId: "BL-03", kind: "decision", sourceRefs: ["FTGU-E05"],
    assumptions: ["BB closes action", "BTN opens wide", "reasonable playability"],
    cueRu: "BB против wide BTN open.", cueEn: "BB versus a wide BTN open.",
    questionRu: "Что делает marginal continue более жизнеспособным?", questionEn: "What makes a marginal continue more viable?",
    actionOptions: [o("a", "Discount + closing action + wide opener", "Discount + closing action + wide opener"), o("b", "Только то, что Hero уже поставил blind", "Only the fact that Hero already posted the blind", "SUNK_COST_ONLY"), o("c", "Любая suited hand обязана call", "Any suited hand must call", "ANY_SUITED")],
    reasonOptions: [o("r1", "Pot odds и closing action снижают required realisable equity", "Pot odds and closing action lower required realizable equity"), o("r2", "BB всегда реализует 100% equity", "BB always realizes 100% equity", "FULL_REALIZATION"), o("r3", "BTN range не отличается от EP", "BTN range does not differ from EP", "ORIGIN_RANGE_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25,
    explanationRu: "FTGU-E05 перечисляет small opens, wide ranges, closing action и playability как факторы лучшей BB defence.",
    explanationEn: "FTGU-E05 lists small opens, wide ranges, closing action and playability as factors supporting BB defense.",
  },
  {
    id: "PM-BL-04-001", skillId: "BL-04", kind: "changed", sourceRefs: ["FTGU-E05"],
    assumptions: ["same BB hand", "same opener position", "open size increases"],
    cueRu: "Open size вырос, всё остальное одинаково.", cueEn: "Open size increased; everything else is unchanged.",
    questionRu: "Как меняется marginal BB defend?", questionEn: "How does a marginal BB defend change?",
    actionOptions: [o("a", "Становится хуже", "It becomes worse"), o("b", "Становится лучше", "It becomes better", "PRICE_BACKWARDS"), o("c", "Не меняется, потому что closing action тот же", "It does not change because closing action is unchanged", "PRICE_IGNORED")],
    reasonOptions: [o("r1", "Pot odds ухудшаются и требуемая realisation растёт", "Pot odds worsen and required realization rises"), o("r2", "Bigger open даёт BB больше dead money", "A bigger open gives BB more dead money", "PRICE_BACKWARDS"), o("r3", "Size не участвует в BB defence", "Size does not matter in BB defense", "PRICE_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 20,
    explanationRu: "FTGU-E05 прямо говорит, что smaller opens поддерживают wider defence; обратное изменение ухудшает fringe calls.",
    explanationEn: "FTGU-E05 explicitly says smaller opens support wider defense; the reverse worsens fringe calls.",
    changedVariables: ["open_size", "pot_odds"],
  },
  {
    id: "PM-BL-05-001", skillId: "BL-05", kind: "boundary", sourceRefs: ["FTGU-E06"],
    assumptions: ["SB faces open", "BB weak/passive"],
    cueRu: "SB против open, но BB необычно пассивен.", cueEn: "SB faces an open, but BB is unusually passive.",
    questionRu: "Является ли 3-bet-or-fold абсолютным запретом flat?", questionEn: "Is 3-bet-or-fold an absolute ban on flatting?",
    actionOptions: [o("a", "Нет, некоторые flats могут выживать", "No, some flats can survive"), o("b", "Да, flat всегда ошибка", "Yes, flatting is always a mistake", "ABSOLUTE_RULE"), o("c", "Да, если hand suited", "Yes, unless the hand is suited", "SUITED_EXCEPTION_INVENTED")],
    reasonOptions: [o("r1", "Default зависит от squeeze risk и table behind; passive BB может изменить branch EV", "The default depends on squeeze risk and the table behind; a passive BB can change branch EV"), o("r2", "Название урока важнее stated exceptions", "The lesson title matters more than stated exceptions", "TITLE_OVER_SOURCE"), o("r3", "SB получает closing action при flat", "SB closes the action when flatting", "SB_CLOSING_FALSE")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25,
    explanationRu: "FTGU-E06 специально говорит, что 3-bet-or-fold — полезный default, а не unconditional law.",
    explanationEn: "FTGU-E06 explicitly says 3-bet-or-fold is a useful default, not an unconditional law.",
  },
  {
    id: "PM-BL-10-001", skillId: "BL-10", kind: "changed", sourceRefs: ["SLC-M02-L05"],
    assumptions: ["same flop", "same PFR", "caller changes BB -> SB"],
    cueRu: "Та же доска; caller теперь SB вместо BB.", cueEn: "Same board; caller is now SB instead of BB.",
    questionRu: "Можно ли сохранить прежний c-bet default?", questionEn: "Can the prior c-bet default be preserved?",
    actionOptions: [o("a", "Нет, сначала пересчитать range ownership", "No, reassess range ownership first"), o("b", "Да, board одинаковый", "Yes, because the board is identical", "BOARD_ONLY"), o("c", "Да, preflop caller position не влияет postflop", "Yes, caller position does not matter postflop", "RANGE_SOURCE_IGNORED")],
    reasonOptions: [o("r1", "SB calling range tighter/condensed и даёт stronger continues than BB", "SB calling range is tighter/condensed and produces stronger continues than BB"), o("r2", "Board appearance полностью определяет c-bet", "Board appearance fully determines c-betting", "BOARD_ONLY"), o("r3", "Все blind ranges одинаковы после flop", "All blind ranges are identical after the flop", "BLINDS_SAME")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30,
    explanationRu: "SLC-M02-L05 показывает, что одна и та же board может быть high-frequency bet vs BB и heavy check vs SB из-за range identity.",
    explanationEn: "SLC-M02-L05 shows the same board can be high-frequency bet versus BB and heavy check versus SB because of range identity.",
    changedVariables: ["blind_identity", "arriving_range"],
  },
];
