import type { PracticalDecision } from "./types";

const o = (id: string, textRu: string, textEn: string, misconception?: string) => ({ id, textRu, textEn, misconception });
const d = (id: string, skillId: string, kind: PracticalDecision["kind"], sourceRefs: string[], cueRu: string, cueEn: string, questionRu: string, questionEn: string, goodRu: string, goodEn: string, whyRu: string, whyEn: string, badRu: string, badEn: string, changedVariables?: string[]): PracticalDecision => ({
  id, skillId, kind, sourceRefs, assumptions: [], cueRu, cueEn, questionRu, questionEn,
  actionOptions: [o("a", goodRu, goodEn), o("b", badRu, badEn, "TARGET_REACHABILITY_DISTRACTOR"), o("c", "Нужна другая причинная проверка", "A different causal check is required", "TARGET_REACHABILITY_DISTRACTOR")],
  reasonOptions: [o("r1", whyRu, whyEn), o("r2", "Исходного примера достаточно, потому что новое условие не меняет механизм", "The original example is enough because the new condition does not change the mechanism", "MEMORIZATION_SHORTCUT"), o("r3", "Контекст линии можно игнорировать, если название ситуации осталось тем же", "The line context can be ignored when the situation keeps the same label", "CONTEXT_IGNORED")],
  correctActionId: "a", correctReasonId: "r1", targetSeconds: 25, explanationRu: whyRu, explanationEn: whyEn, changedVariables,
});

export const targetReachabilityClosureDecisions: PracticalDecision[] = [
  d("PM-FND-05-TRC-101","FND-05","recognition",["FTGU-E11"],"На флопе часть карт уже видна.","Some cards are visible on the flop.","Что происходит с исходным числом комбинаций?","What happens to the starting combo count?","Убираем комбинации, содержащие известные карты","Remove combos containing known cards","Известные карты удаляют содержащие их комбинации из доступного диапазона.","Known cards remove combinations containing them from the available range.","Оставляем исходный preflop count","Keep the original preflop count"),
  d("PM-FND-05-TRC-102","FND-05","decision",["FTGU-E11"],"Два диапазона содержат одинаковое число сильных комбинаций, но один исходный диапазон намного уже.","Two ranges contain the same number of strong combos, but one starting range is much narrower.","Как сравнивать их вес?","How should their weight be compared?","Относительно размера исходного диапазона","Relative to the size of the starting range","Вес сильной части зависит от её доли в исходном диапазоне.","The weight of a strong region depends on its share of the starting range.","Считать абсолютное число достаточным","Treat the absolute count as sufficient"),
  d("PM-FND-05-TRC-103","FND-05","decision",["FTGU-E11","FTGU-E13"],"В river range есть value и bluff candidates.","A river range contains value and bluff candidates.","Что проверить до вывода о балансе?","What should be checked before judging balance?","Посчитать surviving value и bluff combos после removal","Count surviving value and bluff combos after removal","Counting surviving value and bluff combos reveals their actual ratio in this line.","Counting surviving value and bluff combos reveals their actual ratio in this line.","Сравнить только названия hand classes","Compare hand-class labels only"),
  d("PM-FND-05-TRC-104","FND-05","decision",["FTGU-E13"],"Одна и та же карта рассматривается для bluff и bluff-catch.","The same card is considered for a bluff and a bluff-catch.","Одинаково ли её blocker качество?","Is its blocker quality the same?","Нет, роль зависит от action и target range","No; its role depends on the action and target range","Blocker effect зависит от того, какие руки мы хотим убрать или сохранить для выбранного действия.","Blocker effect depends on which hands the chosen action wants to remove or preserve.","Да, хороший blocker универсален","Yes; a good blocker is universal"),
  d("PM-FND-05-TRC-105","FND-05","changed",["FTGU-E11"],"На следующей улице появилась карта, удаляющая часть прежнего value region.","The next street removes part of the previous value region.","Что делать с подсчётом?","What should happen to the count?","Пересчитать surviving combinations","Recount the surviving combinations","Новая известная карта меняет surviving range, поэтому комбинации нужно пересчитать.","A newly known card changes the surviving range, so the combinations must be recounted.","Сохранить предыдущий count", "Keep the previous count",["board_card","card_removal"]),
  d("PM-FND-05-TRC-106","FND-05","changed",["FTGU-E13"],"Та же карта Hero, но задача меняется с bluff-catch на value bet.","Hero holds the same card, but the task changes from bluff-catching to value betting.","Переносится ли blocker вывод автоматически?","Does the blocker conclusion transfer automatically?","Нет, пересчитать removal против новой target range","No; re-evaluate removal against the new target range","Смена действия меняет target range и вместе с ней смысл removal.","Changing the action changes the target range and therefore the meaning of removal.","Да, blocker знак фиксирован", "Yes; blocker quality has a fixed sign",["action_role","target_range"]),

  d("PM-FND-07-TRC-101","FND-07","recognition",["FTGU-E01"],"Риск 1, выигрыш при успехе 2; future action отсутствует.","Risk 1 to win 2; no future action remains.","Нужно ли выигрывать половину раз?","Must the call win half the time?","Нет, break-even threshold около одной трети","No; the break-even threshold is about one third","При риске 1 ради выигрыша 2 порог безубыточности составляет примерно одну треть.","Risking 1 to win 2 gives a break-even threshold of about one third.","Да, любой call требует 50%","Yes; every call requires 50%"),
  d("PM-FND-07-TRC-102","FND-07","recognition",["FTGU-E01"],"После решения остаются несколько улиц и большой stack.","Several streets and a large stack remain after the decision.","Достаточен ли immediate equity threshold?","Is an immediate-equity threshold sufficient?","Нет, future leverage и implied odds входят в EV","No; future leverage and implied odds enter EV","При длинном дереве будущие решения могут существенно изменить итоговый EV.","With a long future tree, later decisions can materially change total EV.","Да, current equity полностью определяет EV","Yes; current equity fully determines EV"),
  d("PM-FND-07-TRC-103","FND-07","decision",["FTGU-E01"],"All-in call получает цену, требующую примерно 33% equity; Hero имеет 38%.","An all-in call gets a price requiring about 33% equity; Hero has 38%.","Как классифицировать call по этой модели?","How is the call classified under this model?","Прибыльный по price/equity threshold","Profitable by the price/equity threshold","Колл может быть прибыльным при equity выше порога цены, даже если проигрывает чаще половины.","A call can be profitable above the price threshold even when it loses more than half the time.","Убыточный, потому что equity ниже 50%","Unprofitable because equity is below 50%"),
  d("PM-FND-07-TRC-104","FND-07","decision",["FTGU-E01"],"River decision заканчивает дерево после call/fold.","A river decision ends the tree after call/fold.","Что должно связывать risk/reward с решением?","What should connect risk/reward to the decision?","Цена банка и требуемая equity","Pot price and required equity","Когда будущих ставок нет, цена банка напрямую задаёт требуемую equity.","When future betting is gone, pot price directly sets the required equity.","Win frequency должна быть больше 50%","Win frequency must exceed 50%"),
  d("PM-FND-07-TRC-105","FND-07","decision",["FTGU-E01"],"Flop call имеет слабую immediate equity, но малую текущую инвестицию и большой потенциальный future return.","A flop call has weak immediate equity but a small current investment and large potential future return.","Можно ли решить только по immediate threshold?","Can the decision be made from the immediate threshold alone?","Нет, оценить whole-branch EV и implied odds","No; estimate whole-branch EV and implied odds","Низкая текущая equity не исключает прибыльное продолжение при выгодном будущем дереве.","Low current equity does not rule out a profitable continue when the future tree is favorable.","Да, fold всегда если current equity ниже pot-odds threshold","Yes; always fold when current equity is below the pot-odds threshold"),
  d("PM-FND-07-TRC-106","FND-07","changed",["FTGU-E01"],"Тот же hand и price, но решение становится all-in и future betting исчезает.","Same hand and price, but the decision becomes all-in and future betting disappears.","Что меняется в оценке?","What changes in the evaluation?","Price/equity threshold становится более прямым ориентиром","The price/equity threshold becomes a more direct guide","Без будущих решений price/equity становятся более прямым приближением EV.","Without future decisions, price and equity become a more direct approximation of EV.","Ничего, future tree никогда не важен", "Nothing; the future tree never matters",["future_action","spr"]),
  d("PM-FND-07-TRC-107","FND-07","changed",["FTGU-E01"],"Тот же immediate price, но effective stack становится намного глубже.","Same immediate price, but the effective stack becomes much deeper.","Можно ли сохранить прежний break-even shortcut?","Can the previous break-even shortcut be kept unchanged?","Нет, future-tree EV получает больший вес","No; future-tree EV carries more weight","Более глубокий стек добавляет будущие решения и ослабляет immediate-threshold shortcut.","A deeper stack adds future decisions and weakens the immediate-threshold shortcut.","Да, immediate threshold всегда полностью решает node", "Yes; the immediate threshold always fully solves the node",["effective_stack","future_leverage"]),

  d("PM-BL-10-TRC-101","BL-10","recognition",["SLC-BB-VS-SB"],"Один и тот же flop сравнивается против SB caller и BB caller.","The same flop is compared versus an SB caller and a BB caller.","Что нужно определить до c-bet default?","What must be identified before choosing a c-bet default?","Из какого blind range пришёл caller","Which blind range the caller came from","Сначала определи исходный диапазон caller, затем оцени стимулы доски.","Identify the caller's source range before evaluating the board incentives.","Только внешний вид board","Only the board's appearance"),
  d("PM-BL-10-TRC-102","BL-10","decision",["SLC-BB-VS-SB"],"HJ PFR играет K-K-J flop против BB caller.","HJ PFR plays a K-K-J flop versus a BB caller.","Какой baseline поддерживает source?","Which baseline does the source support?","PFR может c-bet очень часто из-за сильного range advantage","The PFR can c-bet very often because of strong range advantage","Против широкого BB range на K-K-J у PFR сохраняется сильное range advantage.","Against the wider BB range on K-K-J, the PFR retains a strong range advantage.","Автоматически heavy check против любого blind","Automatically heavy-check versus either blind"),
  d("PM-BL-10-TRC-103","BL-10","decision",["SLC-BB-VS-SB"],"HJ PFR играет тот же K-K-J flop против SB caller.","HJ PFR plays the same K-K-J flop versus an SB caller.","Как меняется baseline?","How does the baseline change?","Чекать заметно чаще против более condensed SB range","Check materially more often versus the more condensed SB range","Более condensed SB range сохраняет больше сильных продолжений и меньше автоматически фолдит.","The more condensed SB range retains more strong continues and folds less automatically.","Копировать BB c-bet default без изменений","Copy the BB c-bet default unchanged"),
  d("PM-BL-10-TRC-104","BL-10","decision",["SLC-BB-VS-SB","LCM-03"],"Board выглядит благоприятно для aggressor, но caller source range изменился BB -> SB.","The board looks favorable for the aggressor, but the caller source range changed from BB to SB.","Что важнее для baseline?","What matters for the baseline?","Текстура доски вместе с формой пришедшего диапазона","Board texture together with arriving-range shape","Postflop baseline зависит от сочетания texture доски и формы пришедшего диапазона.","The postflop baseline depends on both board texture and the shape of the arriving range.","Board label независимо от source range","The board label independent of source range"),
  d("PM-BL-10-TRC-105","BL-10","boundary",["SLC-BB-VS-SB","LCM-03"],"Конкретный SB регулярно over-call preflop и приходит на flop шире baseline.","A specific SB repeatedly over-calls preflop and reaches the flop wider than baseline.","Нужно ли слепо применять baseline SB-vs-BB contrast?","Should the baseline SB-vs-BB contrast be applied blindly?","Нет, надёжные данные об оппоненте могут изменить исходное предположение о диапазоне","No; strong opponent evidence can change the arriving-range prior","The mechanism depends on the actual range shape, not the seat label alone.","The mechanism depends on the actual range shape, not the seat label alone.","Да, seat label всегда определяет range", "Yes; the seat label always determines the range"),

  d("PM-W4-HAND-01-TRC-109","W4-HAND-01","boundary",["FTGU-E09"],"Made hand выглядит сильной по абсолютному названию, но range, который продолжает против raise, намного сильнее.","A made hand looks strong by its absolute label, but the range continuing versus a raise is much stronger.","Достаточно ли hand-family label для value raise?","Is the hand-family label sufficient for a value raise?","Нет, relative strength против continuing range ограничивает действие","No; relative strength versus the continuing range constrains the action","Family label — промежуточная классификация; действие зависит от relative strength против continuing range.","The family label is intermediate; the action depends on relative strength versus the continuing range.","Да, сильное название hand автоматически означает value raise","Yes; a strong hand label automatically means a value raise"),
];
