import type { PracticalDecision } from "./types";

const o=(id:string,textRu:string,textEn:string,misconception?:string)=>({id,textRu,textEn,misconception});
type S={skillId:string;id:string;kind:PracticalDecision["kind"];sourceRefs:string[];cueRu:string;cueEn:string;qRu:string;qEn:string;goodRu:string;goodEn:string;whyRu:string;whyEn:string;bad1Ru:string;bad1En:string;bad2Ru:string;bad2En:string;changedVariables?:string[]};
function d(s:S,index:number):PracticalDecision{const slot=index%3;const good=o("good",s.goodRu,s.goodEn);const b1=o("b1",s.bad1Ru,s.bad1En,"WRONG_MECHANISM");const b2=o("b2",s.bad2Ru,s.bad2En,"TOPIC_SHORTCUT");const gr=o("goodR",s.whyRu,s.whyEn);const br1=o("br1","Последний изученный topic должен управлять ответом","The most recently studied topic should drive the answer","TOPIC_RECENCY_BIAS");const br2=o("br2","Exact cards/result важнее decision mechanism","Exact cards/result matter more than the decision mechanism","RESULT_OR_STIMULUS_BIAS");return{id:s.id,skillId:s.skillId,kind:s.kind,sourceRefs:s.sourceRefs,assumptions:["topic hidden or transfer context","mechanism-level integration"],cueRu:s.cueRu,cueEn:s.cueEn,questionRu:s.qRu,questionEn:s.qEn,actionOptions:slot===0?[good,b1,b2]:slot===1?[b1,good,b2]:[b1,b2,good],reasonOptions:slot===0?[br1,gr,br2]:slot===1?[gr,br1,br2]:[br1,br2,gr],correctActionId:"good",correctReasonId:"goodR",targetSeconds:24,explanationRu:s.whyRu,explanationEn:s.whyEn,changedVariables:s.changedVariables};}

const rows:S[]=[
// INT-01 topic-hidden mixed mechanism selection
{skillId:"INT-01",id:"PM-INT-01-A11-101",kind:"mixed",sourceRefs:["FTGU-E05"],cueRu:"BB закрывает action против small BTN open; marginal suited hand.",cueEn:"BB closes action versus a small BTN open; marginal suited hand.",qRu:"Какой mechanism first?",qEn:"Which mechanism comes first?",goodRu:"Price + closing action + realisation",goodEn:"Price + closing action + realization",whyRu:"Node is BB defence; mechanism must be recognized from state rather than a topic label.",whyEn:"The node is BB defense; the mechanism must be recognized from state rather than a topic label.",bad1Ru:"River blockers",bad1En:"River blockers",bad2Ru:"Multiway sandwich",bad2En:"Multiway sandwich"},
{skillId:"INT-01",id:"PM-INT-01-A11-102",kind:"mixed",sourceRefs:["FTGU-E27"],cueRu:"PFR OOP reaches a board that strongly hits caller coverage.",cueEn:"PFR OOP reaches a board that strongly hits caller coverage.",qRu:"Which mechanism first?",qEn:"Which mechanism comes first?",goodRu:"Board×range ownership + OOP checking",goodEn:"Board×range ownership + OOP checking",whyRu:"Initiative is subordinate to actual range interaction and position.",whyEn:"Initiative is subordinate to actual range interaction and position.",bad1Ru:"Automatic c-bet",bad1En:"Automatic c-bet",bad2Ru:"Preflop 4-bet logic",bad2En:"Preflop 4-bet logic"},
{skillId:"INT-01",id:"PM-INT-01-A11-103",kind:"mixed",sourceRefs:["FTGU-E29"],cueRu:"3BP coordinated middling flop materially equalises ranges.",cueEn:"A coordinated middling 3BP flop materially equalizes ranges.",qRu:"Which mechanism first?",qEn:"Which mechanism comes first?",goodRu:"Role × board × selective strategy",goodEn:"Role × board × selective strategy",whyRu:"3BP is not one universal range-bet family; role and board interaction decide selectivity.",whyEn:"A 3BP is not one universal range-bet family; role and board interaction decide selectivity.",bad1Ru:"Small range-bet because 3BP",bad1En:"Small range-bet because it is a 3BP",bad2Ru:"Limp isolation",bad2En:"Limp isolation"},
{skillId:"INT-01",id:"PM-INT-01-A11-104",kind:"mixed",sourceRefs:["FTGU-E20"],cueRu:"Flop checked back; turn may have restored strong hands to IP.",cueEn:"Flop checked back; the turn may have restored strong hands to IP.",qRu:"Which mechanism first?",qEn:"Which mechanism comes first?",goodRu:"Check-back ancestry before probe",goodEn:"Check-back ancestry before probing",whyRu:"Probe leverage depends on what the flop check removed and what the turn card restored.",whyEn:"Probe leverage depends on what the flop check removed and what the turn card restored.",bad1Ru:"Missed c-bet = probe",bad1En:"Missed c-bet = probe",bad2Ru:"BB price",bad2En:"BB price"},
{skillId:"INT-01",id:"PM-INT-01-A11-105",kind:"mixed",sourceRefs:["FTGU-E22"],cueRu:"River bluff-catcher faces a large bet after a line with few natural missed bluffs.",cueEn:"A river bluff-catcher faces a large bet after a line with few natural missed bluffs.",qRu:"Which mechanism first?",qEn:"Which mechanism comes first?",goodRu:"Price × credible bluff supply × removal",goodEn:"Price × credible bluff supply × removal",whyRu:"Pot odds set a threshold but line ancestry determines whether enough bluffs actually exist.",whyEn:"Pot odds set a threshold but line ancestry determines whether enough bluffs actually exist.",bad1Ru:"Good price = call",bad1En:"Good price = call",bad2Ru:"Flop range-bet",bad2En:"Flop range-bet"},
{skillId:"INT-01",id:"PM-INT-01-A11-106",kind:"mixed",sourceRefs:["LCM-08","SLC-MULTIWAY"],cueRu:"Three-way pot; Hero is sandwiched with one player still behind.",cueEn:"Three-way pot; Hero is sandwiched with one player still behind.",qRu:"Which mechanism first?",qEn:"Which mechanism comes first?",goodRu:"Relative position + remaining ranges",goodEn:"Relative position + remaining ranges",whyRu:"Multiway decision quality depends on who still acts and aggregate continuing strength.",whyEn:"Multiway decision quality depends on who still acts and aggregate continuing strength.",bad1Ru:"Heads-up IP/OOP only",bad1En:"Heads-up IP/OOP only",bad2Ru:"River blockers",bad2En:"River blockers"},
{skillId:"INT-01",id:"PM-INT-01-A11-107",kind:"mixed",sourceRefs:["LCM-01"],cueRu:"Mandatory straddle appears; physical stack dollars are unchanged.",cueEn:"A mandatory straddle appears; physical stack dollars are unchanged.",qRu:"Which mechanism first?",qEn:"Which mechanism comes first?",goodRu:"Reset forced unit / effective depth / action order",goodEn:"Reset forced unit / effective depth / action order",whyRu:"Straddle changes strategic geometry even when nominal dollars are unchanged.",whyEn:"A straddle changes strategic geometry even when nominal dollars are unchanged.",bad1Ru:"Keep ordinary BB tree",bad1En:"Keep the ordinary-BB tree",bad2Ru:"Only hand rank matters",bad2En:"Only hand rank matters"},
{skillId:"INT-01",id:"PM-INT-01-A11-108",kind:"boundary",sourceRefs:["LCM-11"],cueRu:"Mixed practice names the topic before every question.",cueEn:"Mixed practice names the topic before every question.",qRu:"Does that prove mechanism selection?",qEn:"Does that prove mechanism selection?",goodRu:"No — topic cue must be hidden before commitment",goodEn:"No — the topic cue must be hidden before commitment",whyRu:"Integrated transfer requires recognizing which model applies without a lesson label.",whyEn:"Integrated transfer requires recognizing which model applies without a lesson label.",bad1Ru:"Yes, topic labels are harmless",bad1En:"Yes, topic labels are harmless",bad2Ru:"Yes, exact answer matters only",bad2En:"Yes, only the exact answer matters"},
// INT-02 changed-node transfer
{skillId:"INT-02",id:"PM-INT-02-A11-101",kind:"changed",sourceRefs:["FTGU-E05","FTGU-E06"],cueRu:"Same hand: BB closes action → SB with BB behind.",cueEn:"Same hand: BB closing action → SB with BB behind.",qRu:"Transfer unchanged?",qEn:"Transfer unchanged?",goodRu:"No — price/position/players behind changed",goodEn:"No — price/position/players behind changed",whyRu:"Changing one structural variable can invalidate the previous branch even with identical cards.",whyEn:"Changing one structural variable can invalidate the previous branch even with identical cards.",bad1Ru:"Yes, both are blinds",bad1En:"Yes, both are blinds",bad2Ru:"Yes, cards same",bad2En:"Yes, cards are the same",changedVariables:["position","closing_action"]},
{skillId:"INT-02",id:"PM-INT-02-A11-102",kind:"changed",sourceRefs:["FTGU-E07"],cueRu:"Same ranges: dry-high flop → low-connected equaliser.",cueEn:"Same ranges: dry-high flop → low-connected equalizer.",qRu:"Transfer unchanged?",qEn:"Transfer unchanged?",goodRu:"No — c-bet structure becomes more selective",goodEn:"No — the c-bet structure becomes more selective",whyRu:"Board-range interaction changes while preflop history stays constant.",whyEn:"Board-range interaction changes while preflop history stays constant.",bad1Ru:"Yes, PFR still has initiative",bad1En:"Yes, PFR still has initiative",bad2Ru:"Yes, same pot type",bad2En:"Yes, same pot type",changedVariables:["board_class"]},
{skillId:"INT-02",id:"PM-INT-02-A11-103",kind:"changed",sourceRefs:["CP-G3-L09"],cueRu:"Same 3BP hand/board/size: caller moves IP → OOP.",cueEn:"Same 3BP hand/board/size: caller moves IP → OOP.",qRu:"Transfer unchanged?",qEn:"Transfer unchanged?",goodRu:"No — realisation and future pressure change",goodEn:"No — realization and future pressure change",whyRu:"Position is a causal branch variable, not a cosmetic label.",whyEn:"Position is a causal branch variable, not a cosmetic label.",bad1Ru:"Yes, caller role same",bad1En:"Yes, caller role is the same",bad2Ru:"Yes, SPR same",bad2En:"Yes, SPR is the same",changedVariables:["position"]},
{skillId:"INT-02",id:"PM-INT-02-A11-104",kind:"changed",sourceRefs:["FTGU-E21"],cueRu:"Same flop branch: turn blank → range-uncapping draw completion.",cueEn:"Same flop branch: turn blank → range-uncapping draw completion.",qRu:"Transfer unchanged?",qEn:"Transfer unchanged?",goodRu:"No — assumed cap can disappear",goodEn:"No — the assumed cap can disappear",whyRu:"Runout classification is defined by how it changes surviving ranges.",whyEn:"Runout classification is defined by how it changes surviving ranges.",bad1Ru:"Yes, aggressor still aggressor",bad1En:"Yes, the aggressor is still the aggressor",bad2Ru:"Yes, turn labels fixed",bad2En:"Yes, turn labels are fixed",changedVariables:["turn_class"]},
{skillId:"INT-02",id:"PM-INT-02-A11-105",kind:"changed",sourceRefs:["FTGU-E22"],cueRu:"Same river hand/price: line ancestry removes most missed draws.",cueEn:"Same river hand/price: line ancestry removes most missed draws.",qRu:"Transfer unchanged?",qEn:"Transfer unchanged?",goodRu:"No — bluff-catch becomes worse",goodEn:"No — the bluff-catch becomes worse",whyRu:"Price alone does not preserve bluff supply when the previous line changes.",whyEn:"Price alone does not preserve bluff supply when the previous line changes.",bad1Ru:"Yes, pot odds same",bad1En:"Yes, pot odds are the same",bad2Ru:"Yes, hand label same",bad2En:"Yes, hand label is the same",changedVariables:["line_ancestry"]},
{skillId:"INT-02",id:"PM-INT-02-A11-106",kind:"changed",sourceRefs:["SLC-MULTIWAY"],cueRu:"Same hand/board: heads-up → four-way.",cueEn:"Same hand/board: heads-up → four-way.",qRu:"Transfer unchanged?",qEn:"Transfer unchanged?",goodRu:"No — value/bluff thresholds tighten",goodEn:"No — value/bluff thresholds tighten",whyRu:"More credible ranges raise the bar for marginal value and aggression.",whyEn:"More credible ranges raise the bar for marginal value and aggression.",bad1Ru:"Yes, exact hand same",bad1En:"Yes, the exact hand is the same",bad2Ru:"Yes, board same",bad2En:"Yes, the board is the same",changedVariables:["number_of_ranges"]},
{skillId:"INT-02",id:"PM-INT-02-A11-107",kind:"changed",sourceRefs:["LCM-01"],cueRu:"Same physical stack: no straddle → mandatory straddle.",cueEn:"Same physical stack: no straddle → mandatory straddle.",qRu:"Transfer unchanged?",qEn:"Transfer unchanged?",goodRu:"No — effective depth/action geometry changes",goodEn:"No — effective depth/action geometry changes",whyRu:"Working blind unit and future SPR change even though dollar stack is identical.",whyEn:"The working blind unit and future SPR change even though the dollar stack is identical.",bad1Ru:"Yes, dollars same",bad1En:"Yes, dollars are the same",bad2Ru:"Yes, positions labels same",bad2En:"Yes, position labels are the same",changedVariables:["straddle"]},
{skillId:"INT-02",id:"PM-INT-02-A11-108",kind:"boundary",sourceRefs:["FINAL_LEARNING_INTEGRITY"],cueRu:"Only wording changes; material poker variables do not.",cueEn:"Only wording changes; material poker variables do not.",qRu:"Should action be forced to change?",qEn:"Should the action be forced to change?",goodRu:"No — changed-node tests require material variables",goodEn:"No — changed-node tests require material variables",whyRu:"Transfer evidence comes from causal node changes, not superficial prompt variation.",whyEn:"Transfer evidence comes from causal node changes, not superficial prompt variation.",bad1Ru:"Yes, every new wording needs new action",bad1En:"Yes, every new wording needs a new action",bad2Ru:"Yes, novelty itself is transfer",bad2En:"Yes, novelty itself is transfer"},
// INT-03 mistake family repair
{skillId:"INT-03",id:"PM-INT-03-A11-101",kind:"mixed",sourceRefs:["FTGU-E27"],cueRu:"Repeated leak: initiative → automatic OOP c-bet on equalising boards.",cueEn:"Repeated leak: initiative → automatic OOP c-bet on equalizing boards.",qRu:"Repair family?",qEn:"Repair family?",goodRu:"OOP-01 + W4-BOARD-01",goodEn:"OOP-01 + W4-BOARD-01",whyRu:"Repair should target board ownership and OOP checking, the underlying repeated mechanism.",whyEn:"Repair should target board ownership and OOP checking, the underlying repeated mechanism.",bad1Ru:"RIV-04",bad1En:"RIV-04",bad2Ru:"PF-08",bad2En:"PF-08"},
{skillId:"INT-03",id:"PM-INT-03-A11-102",kind:"mixed",sourceRefs:["FTGU-E05"],cueRu:"Repeated leak: BB fold decisions ignore open size and closing action.",cueEn:"Repeated leak: BB fold decisions ignore open size and closing action.",qRu:"Repair family?",qEn:"Repair family?",goodRu:"PF-04 + BL-04",goodEn:"PF-04 + BL-04",whyRu:"The repeated mechanism is price/open-size sensitivity in BB defence.",whyEn:"The repeated mechanism is price/open-size sensitivity in BB defense.",bad1Ru:"RIV-02",bad1En:"RIV-02",bad2Ru:"4BP-03",bad2En:"4BP-03"},
{skillId:"INT-03",id:"PM-INT-03-A11-103",kind:"mixed",sourceRefs:["FTGU-E20"],cueRu:"Repeated leak: probe every turn after flop check-back.",cueEn:"Repeated leak: probe every turn after a flop check-back.",qRu:"Repair family?",qEn:"Repair family?",goodRu:"TURN-03 + W4-RUNOUT-01",goodEn:"TURN-03 + W4-RUNOUT-01",whyRu:"The leak is ancestry/cap recognition, not generic aggression.",whyEn:"The leak is ancestry/cap recognition, not generic aggression.",bad1Ru:"PF-01",bad1En:"PF-01",bad2Ru:"EXP-02",bad2En:"EXP-02"},
{skillId:"INT-03",id:"PM-INT-03-A11-104",kind:"mixed",sourceRefs:["FTGU-E22"],cueRu:"Repeated leak: bluff-catch whenever pot odds look good without naming bluffs.",cueEn:"Repeated leak: bluff-catch whenever pot odds look good without naming bluffs.",qRu:"Repair family?",qEn:"Repair family?",goodRu:"RIV-03 + FND-05",goodEn:"RIV-03 + FND-05",whyRu:"The leak combines bluff-supply/removal with river price.",whyEn:"The leak combines bluff supply/removal with river price.",bad1Ru:"MW-04",bad1En:"MW-04",bad2Ru:"PF-02",bad2En:"PF-02"},
{skillId:"INT-03",id:"PM-INT-03-A11-105",kind:"mixed",sourceRefs:["SLC-MULTIWAY"],cueRu:"Repeated leak: heads-up top-pair value threshold copied multiway.",cueEn:"Repeated leak: heads-up top-pair value threshold copied multiway.",qRu:"Repair family?",qEn:"Repair family?",goodRu:"MW-02 + W4-REL-01",goodEn:"MW-02 + W4-REL-01",whyRu:"The underlying issue is relative strength across multiple ranges.",whyEn:"The underlying issue is relative strength across multiple ranges.",bad1Ru:"BL-02",bad1En:"BL-02",bad2Ru:"RIV-04",bad2En:"RIV-04"},
{skillId:"INT-03",id:"PM-INT-03-A11-106",kind:"mixed",sourceRefs:["LCM-10"],cueRu:"Repeated leak: one showdown becomes a global player label.",cueEn:"Repeated leak: one showdown becomes a global player label.",qRu:"Repair family?",qEn:"Repair family?",goodRu:"EXP-01",goodEn:"EXP-01",whyRu:"The error is evidence qualification and branch scope.",whyEn:"The error is evidence qualification and branch scope.",bad1Ru:"TURN-02",bad1En:"TURN-02",bad2Ru:"PF-06",bad2En:"PF-06"},
{skillId:"INT-03",id:"PM-INT-03-A11-107",kind:"mixed",sourceRefs:["LCM-01"],cueRu:"Repeated leak: deep physical stack treated as same geometry after straddle.",cueEn:"Repeated leak: a deep physical stack is treated as the same geometry after a straddle.",qRu:"Repair family?",qEn:"Repair family?",goodRu:"DEEP-03 + FND-06",goodEn:"DEEP-03 + FND-06",whyRu:"The repeated error is denominator/effective-depth geometry.",whyEn:"The repeated error is denominator/effective-depth geometry.",bad1Ru:"RIV-01",bad1En:"RIV-01",bad2Ru:"3BP-05",bad2En:"3BP-05"},
{skillId:"INT-03",id:"PM-INT-03-A11-108",kind:"boundary",sourceRefs:["LCM-11"],cueRu:"Learner fails one exact card once.",cueEn:"The learner fails one exact card once.",qRu:"Does this prove a stable mistake family?",qEn:"Does this prove a stable mistake family?",goodRu:"No — need pattern or high-confidence meaningful miss",goodEn:"No — need a pattern or a meaningful high-confidence miss",whyRu:"Repair should avoid overfitting noise while still prioritising costly confident mistakes.",whyEn:"Repair should avoid overfitting noise while still prioritizing costly confident mistakes.",bad1Ru:"Yes, permanent leak",bad1En:"Yes, permanent leak",bad2Ru:"Yes, reset whole course",bad2En:"Yes, reset the whole course"},
// INT-04 delayed retrieval
{skillId:"INT-04",id:"PM-INT-04-A11-101",kind:"mixed",sourceRefs:["LCM-11"],cueRu:"Same day exact repeat after a wrong answer.",cueEn:"Same-day exact repeat after a wrong answer.",qRu:"Can it grant delayed retrieval?",qEn:"Can it grant delayed retrieval?",goodRu:"No — repair evidence only",goodEn:"No — repair evidence only",whyRu:"Delayed retrieval requires an actual time gap and non-identical retrieval.",whyEn:"Delayed retrieval requires an actual time gap and non-identical retrieval.",bad1Ru:"Yes, if correct",bad1En:"Yes, if correct",bad2Ru:"Yes, exact repeat is strongest retention",bad2En:"Yes, exact repeat is the strongest retention"},
{skillId:"INT-04",id:"PM-INT-04-A11-102",kind:"mixed",sourceRefs:["FTGU-E22","LCM-11"],cueRu:"Three days later: new river bluff-catcher, different blockers, same mechanism family.",cueEn:"Three days later: a new river bluff-catcher, different blockers, same mechanism family.",qRu:"What evidence is this?",qEn:"What evidence is this?",goodRu:"Delayed non-identical mechanism retrieval",goodEn:"Delayed non-identical mechanism retrieval",whyRu:"The learner must rebuild price/bluff/removal logic rather than recall wording.",whyEn:"The learner must rebuild price/bluff/removal logic rather than recall wording.",bad1Ru:"Exact recall",bad1En:"Exact recall",bad2Ru:"No useful evidence",bad2En:"No useful evidence"},
{skillId:"INT-04",id:"PM-INT-04-A11-103",kind:"mixed",sourceRefs:["FTGU-E05","LCM-11"],cueRu:"One day later: BB defence item changes opener position and size.",cueEn:"One day later: a BB defense item changes opener position and size.",qRu:"What is being tested?",qEn:"What is being tested?",goodRu:"Retention plus transfer",goodEn:"Retention plus transfer",whyRu:"The mechanism must survive both time and a changed node.",whyEn:"The mechanism must survive both time and a changed node.",bad1Ru:"Memory of exact answer",bad1En:"Memory of the exact answer",bad2Ru:"Only speed",bad2En:"Only speed"},
{skillId:"INT-04",id:"PM-INT-04-A11-104",kind:"mixed",sourceRefs:["FTGU-E07","LCM-11"],cueRu:"Seven days later: new board/range pair with same ownership concept.",cueEn:"Seven days later: a new board/range pair with the same ownership concept.",qRu:"What is the strongest evidence?",qEn:"What is the strongest evidence?",goodRu:"Correct mechanism without topic cue",goodEn:"Correct mechanism without a topic cue",whyRu:"Topic-hidden non-identical delayed performance is stronger than exact prompt memory.",whyEn:"Topic-hidden non-identical delayed performance is stronger than exact prompt memory.",bad1Ru:"Recognizing lesson title",bad1En:"Recognizing the lesson title",bad2Ru:"Repeating old wording",bad2En:"Repeating old wording"},
{skillId:"INT-04",id:"PM-INT-04-A11-105",kind:"changed",sourceRefs:["LCM-11"],cueRu:"Delayed item is correct but uses the exact previous decision ID/stimulus.",cueEn:"The delayed item is correct but uses the exact previous decision ID/stimulus.",qRu:"Should it count as full transfer?",qEn:"Should it count as full transfer?",goodRu:"No — keep it as recall, seek non-identical item",goodEn:"No — keep it as recall and seek a non-identical item",whyRu:"Exact repetition cannot prove abstraction/transfer.",whyEn:"Exact repetition cannot prove abstraction/transfer.",bad1Ru:"Yes, full transfer",bad1En:"Yes, full transfer",bad2Ru:"Yes, stronger than changed node",bad2En:"Yes, stronger than a changed node",changedVariables:["stimulus_identity"]},
{skillId:"INT-04",id:"PM-INT-04-A11-106",kind:"changed",sourceRefs:["LCM-11"],cueRu:"Retrieval gap changes 10 minutes → 3 days.",cueEn:"Retrieval gap changes from 10 minutes → 3 days.",qRu:"Evidence change?",qEn:"How does the evidence change?",goodRu:"Now eligible for delayed evidence if stimulus is non-identical",goodEn:"Now eligible for delayed evidence if the stimulus is non-identical",whyRu:"A real spacing interval is part of the evidence claim.",whyEn:"A real spacing interval is part of the evidence claim.",bad1Ru:"No difference",bad1En:"No difference",bad2Ru:"Immediate is stronger",bad2En:"Immediate is stronger",changedVariables:["time_gap"]},
{skillId:"INT-04",id:"PM-INT-04-A11-107",kind:"changed",sourceRefs:["LCM-11"],cueRu:"Time gap remains 3 days; stimulus changes exact repeat → non-identical changed node.",cueEn:"The time gap remains 3 days; stimulus changes from exact repeat → non-identical changed node.",qRu:"Evidence change?",qEn:"How does the evidence change?",goodRu:"Stronger transfer evidence",goodEn:"Stronger transfer evidence",whyRu:"Non-identical retrieval tests the mechanism rather than wording memory.",whyEn:"Non-identical retrieval tests the mechanism rather than wording memory.",bad1Ru:"Weaker because unfamiliar",bad1En:"Weaker because it is unfamiliar",bad2Ru:"No difference",bad2En:"No difference",changedVariables:["stimulus_identity"]},
{skillId:"INT-04",id:"PM-INT-04-A11-108",kind:"boundary",sourceRefs:["LCM-11"],cueRu:"System marks delayed retrieval immediately after concept lesson.",cueEn:"The system marks delayed retrieval immediately after the concept lesson.",qRu:"Valid?",qEn:"Valid?",goodRu:"No — evidence inflation",goodEn:"No — evidence inflation",whyRu:"Delayed evidence cannot be created without delay.",whyEn:"Delayed evidence cannot be created without delay.",bad1Ru:"Yes, concept understood",bad1En:"Yes, the concept was understood",bad2Ru:"Yes, confidence high",bad2En:"Yes, confidence was high"},
// INT-05 real-hand routing
{skillId:"INT-05",id:"PM-INT-05-A11-101",kind:"mixed",sourceRefs:["FTGU-E05"],cueRu:"Real hand: BB folded marginal hand versus tiny BTN open and later says 'I was OOP'.",cueEn:"Real hand: BB folded a marginal hand versus a tiny BTN open and later says 'I was OOP'.",qRu:"Causal repair?",qEn:"Causal repair?",goodRu:"PF-04 / BL-04 price + closing action",goodEn:"PF-04 / BL-04 price + closing action",whyRu:"Route the decision mechanism, not the result or emotion.",whyEn:"Route the decision mechanism, not the result or emotion.",bad1Ru:"Generic confidence lesson",bad1En:"Generic confidence lesson",bad2Ru:"River bluffing",bad2En:"River bluffing"},
{skillId:"INT-05",id:"PM-INT-05-A11-102",kind:"mixed",sourceRefs:["FTGU-E27"],cueRu:"Real hand: PFR OOP range-bet a caller-friendly connected flop and got raised.",cueEn:"Real hand: PFR OOP range-bet a caller-friendly connected flop and got raised.",qRu:"Causal repair?",qEn:"Causal repair?",goodRu:"W4-BOARD-01 + OOP-01",goodEn:"W4-BOARD-01 + OOP-01",whyRu:"The decision leak is board ownership/OOP checking, not the fact that Hero lost the pot.",whyEn:"The decision leak is board ownership/OOP checking, not the fact that Hero lost the pot.",bad1Ru:"Tilt because lost",bad1En:"Tilt because the pot was lost",bad2Ru:"RFI chart",bad2En:"RFI chart"},
{skillId:"INT-05",id:"PM-INT-05-A11-103",kind:"mixed",sourceRefs:["FTGU-E20"],cueRu:"Real hand: automatic turn probe after flop check-back on a card restoring IP strength.",cueEn:"Real hand: automatic turn probe after a flop check-back on a card restoring IP strength.",qRu:"Causal repair?",qEn:"Causal repair?",goodRu:"TURN-03 + W4-RUNOUT-01",goodEn:"TURN-03 + W4-RUNOUT-01",whyRu:"The error is ancestry/range-cap reassessment.",whyEn:"The error is ancestry/range-cap reassessment.",bad1Ru:"Preflop squeeze",bad1En:"Preflop squeeze",bad2Ru:"Generic aggression",bad2En:"Generic aggression"},
{skillId:"INT-05",id:"PM-INT-05-A11-104",kind:"mixed",sourceRefs:["FTGU-E22"],cueRu:"Real hand: river call justified only by pot odds although line had almost no bluffs.",cueEn:"Real hand: river call justified only by pot odds although the line had almost no bluffs.",qRu:"Causal repair?",qEn:"Causal repair?",goodRu:"RIV-03 + FND-05",goodEn:"RIV-03 + FND-05",whyRu:"Repair bluff supply/removal in addition to price.",whyEn:"Repair bluff supply/removal in addition to price.",bad1Ru:"Value betting",bad1En:"Value betting",bad2Ru:"Deep preflop",bad2En:"Deep preflop"},
{skillId:"INT-05",id:"PM-INT-05-A11-105",kind:"mixed",sourceRefs:["SLC-MULTIWAY"],cueRu:"Real hand: thin top-pair value line copied heads-up into four-way pot.",cueEn:"Real hand: a thin top-pair value line was copied from heads-up into a four-way pot.",qRu:"Causal repair?",qEn:"Causal repair?",goodRu:"MW-02 + W4-REL-01",goodEn:"MW-02 + W4-REL-01",whyRu:"The leak is multi-range relative strength/value threshold.",whyEn:"The leak is multi-range relative strength/value threshold.",bad1Ru:"BL-01",bad1En:"BL-01",bad2Ru:"4BP-04",bad2En:"4BP-04"},
{skillId:"INT-05",id:"PM-INT-05-A11-106",kind:"mixed",sourceRefs:["LCM-01"],cueRu:"Real hand: 200bb physical stack with straddle treated as unchanged deep geometry.",cueEn:"Real hand: a 200bb physical stack with a straddle was treated as unchanged deep geometry.",qRu:"Causal repair?",qEn:"Causal repair?",goodRu:"DEEP-03 + FND-06",goodEn:"DEEP-03 + FND-06",whyRu:"The leak is forced unit/effective depth/future SPR.",whyEn:"The leak is forced unit/effective depth/future SPR.",bad1Ru:"River exploit",bad1En:"River exploit",bad2Ru:"Flop blockers",bad2En:"Flop blockers"},
{skillId:"INT-05",id:"PM-INT-05-A11-107",kind:"mixed",sourceRefs:["LCM-10"],cueRu:"Real hand: one bluff showdown caused global 'maniac' adjustments across unrelated nodes.",cueEn:"Real hand: one bluff showdown caused global 'maniac' adjustments across unrelated nodes.",qRu:"Causal repair?",qEn:"Causal repair?",goodRu:"EXP-01 evidence qualification",goodEn:"EXP-01 evidence qualification",whyRu:"The leak is converting one observation into global strategy.",whyEn:"The leak is converting one observation into global strategy.",bad1Ru:"TURN-05",bad1En:"TURN-05",bad2Ru:"PF-09",bad2En:"PF-09"},
{skillId:"INT-05",id:"PM-INT-05-A11-108",kind:"boundary",sourceRefs:["LCM-11"],cueRu:"Real hand lost a huge pot despite a source-supported decision.",cueEn:"A real hand lost a huge pot despite a source-supported decision.",qRu:"Does loss size define repair?",qEn:"Does loss size define the repair?",goodRu:"No — classify decision quality/mechanism, not result",goodEn:"No — classify decision quality/mechanism, not the result",whyRu:"Outcome size is not a skill-family label.",whyEn:"Outcome size is not a skill-family label.",bad1Ru:"Yes, big loss = mental game",bad1En:"Yes, a big loss = mental game",bad2Ru:"Yes, big loss = strategy error",bad2En:"Yes, a big loss = strategy error"},
];

export const integratedA11ExpansionDecisions:PracticalDecision[]=rows.map(d);
