import type { PracticalDecision } from "./types";

const o = (id: string, textRu: string, textEn: string, misconception?: string) => ({ id, textRu, textEn, misconception });

type S = {
  kind: PracticalDecision["kind"];
  sourceRefs: string[];
  cueRu: string; cueEn: string;
  questionRu: string; questionEn: string;
  goodRu: string; goodEn: string;
  bad1Ru: string; bad1En: string;
  bad2Ru: string; bad2En: string;
  whyRu: string; whyEn: string;
  badWhy1Ru: string; badWhy1En: string;
  badWhy2Ru: string; badWhy2En: string;
  changedVariables?: string[];
};

function make(skillId: string, prefix: string, scenarios: S[]): PracticalDecision[] {
  return scenarios.map((s, index) => {
    const slot = index % 3;
    const goodA = o("good", s.goodRu, s.goodEn);
    const badA1 = o("bad1", s.bad1Ru, s.bad1En, "ROLE_OR_RANGE_SHORTCUT");
    const badA2 = o("bad2", s.bad2Ru, s.bad2En, "SIZE_OR_SPR_AUTOPILOT");
    const goodR = o("goodR", s.whyRu, s.whyEn);
    const badR1 = o("badR1", s.badWhy1Ru, s.badWhy1En, "MECHANISM_SHORTCUT");
    const badR2 = o("badR2", s.badWhy2Ru, s.badWhy2En, "UNIVERSAL_RULE");
    const actions = slot === 0 ? [goodA, badA1, badA2] : slot === 1 ? [badA1, goodA, badA2] : [badA1, badA2, goodA];
    const reasons = slot === 0 ? [badR1, goodR, badR2] : slot === 1 ? [goodR, badR1, badR2] : [badR1, badR2, goodR];
    return {
      id: `${prefix}-${101 + index}`,
      skillId,
      kind: s.kind,
      sourceRefs: s.sourceRefs,
      assumptions: ["source-scoped mechanism; no unreviewed exact frequency claimed"],
      cueRu: s.cueRu, cueEn: s.cueEn,
      questionRu: s.questionRu, questionEn: s.questionEn,
      actionOptions: actions,
      reasonOptions: reasons,
      correctActionId: "good",
      correctReasonId: "goodR",
      targetSeconds: 25,
      explanationRu: s.whyRu,
      explanationEn: s.whyEn,
      changedVariables: s.changedVariables,
    } satisfies PracticalDecision;
  });
}

const aggrIp: S[] = [
  { kind:"recognition",sourceRefs:["FTGU-E28"],cueRu:"3BP, Hero — IP 3-bettor. Dry A-high board сохраняет premium/high-card density.",cueEn:"3BP, Hero is the IP 3-bettor. A dry A-high board preserves premium/high-card density.",questionRu:"Какой сигнал о структуре диапазона здесь важен?",questionEn:"Which family signal matters?",goodRu:"Broad small-bet pressure может быть уместен",goodEn:"Broad small-bet pressure can be appropriate",bad1Ru:"IP означает всегда overbet",bad1En:"IP always means overbet",bad2Ru:"3BP всегда требует check",bad2En:"3BP always requires checking",whyRu:"FTGU-E28 связывает small high-frequency betting с сохранённым concentrated range advantage.",whyEn:"FTGU-E28 links small high-frequency betting to preserved concentrated range advantage.",badWhy1Ru:"Позиция сама создаёт range advantage.",badWhy1En:"Position itself creates range advantage.",badWhy2Ru:"Любой 3-bettor имеет одинаковую flop strategy.",badWhy2En:"Every 3-bettor has the same flop strategy."},
  { kind:"recognition",sourceRefs:["FTGU-E29"],cueRu:"3BP IP aggressor на middling connected flop, где caller сохраняет много pair/draw/nut coverage.",cueEn:"3BP IP aggressor on a middling connected flop where the caller retains pair/draw/nut coverage.",questionRu:"Что распознать?",questionEn:"What should be recognized?",goodRu:"Range-bet license ослабла",goodEn:"The range-bet license weakened",bad1Ru:"Preflop aggression гарантирует range-bet",bad1En:"Preflop aggression guarantees a range bet",bad2Ru:"Connected board всегда означает fold",bad2En:"A connected board always means fold",whyRu:"FTGU-E29 переходит к selective strategies когда board materially equalises ranges.",whyEn:"FTGU-E29 moves toward selective strategies when the board materially equalizes ranges.",badWhy1Ru:"3-bet pot сохраняет preflop advantage на любой доске.",badWhy1En:"A 3-bet pot preserves preflop advantage on every board.",badWhy2Ru:"Texture label достаточно без arriving ranges.",badWhy2En:"The texture label is sufficient without arriving ranges."},
  { kind:"decision",sourceRefs:["FTGU-E28"],cueRu:"Dry paired flop; caller редко имеет trips region, aggressor сохраняет overpairs.",cueEn:"Dry paired flop; caller rarely has the trips region while the aggressor retains overpairs.",questionRu:"Какой default practical branch?",questionEn:"Which practical branch is the better default?",goodRu:"Small broad bet",goodEn:"Small broad bet",bad1Ru:"Large polar bet всей range",bad1En:"Large polar bet with the whole range",bad2Ru:"Range check только потому что pot 3-bet",bad2En:"Range check solely because the pot is 3-bet",whyRu:"Broad advantage + protection incentives support small high-frequency pressure.",whyEn:"Broad advantage plus protection incentives support small high-frequency pressure.",badWhy1Ru:"Large size лучше для любой advantage board.",badWhy1En:"A large size is better on every advantage board.",badWhy2Ru:"Pot type определяет action независимо от board.",badWhy2En:"Pot type determines action regardless of the board."},
  { kind:"decision",sourceRefs:["FTGU-E29"],cueRu:"Low connected board materially improves caller coverage.",cueEn:"A low connected board materially improves caller coverage.",questionRu:"Как скорректировать c-bet?",questionEn:"How should the c-bet plan adjust?",goodRu:"Больше check/selective betting",goodEn:"More checking/selective betting",bad1Ru:"Ставить range маленько как на A-high",bad1En:"Small range-bet as on A-high",bad2Ru:"Overbet всей range",bad2En:"Overbet the whole range",whyRu:"Equalising boards требуют selectivity и не наследуют dry-board defaults.",whyEn:"Equalizing boards require selectivity and do not inherit dry-board defaults.",badWhy1Ru:"Все 3BP boards одинаково благоприятны aggressor.",badWhy1En:"All 3BP boards favor the aggressor equally.",badWhy2Ru:"Большой pot делает board interaction неважным.",badWhy2En:"A large pot makes board interaction irrelevant."},
  { kind:"decision",sourceRefs:["FTGU-E28","FTGU-E29"],cueRu:"Board даёт умеренный advantage, но не чистый range-bet node.",cueEn:"The board gives a moderate advantage but not a clean range-bet node.",questionRu:"Какой подход лучше?",questionEn:"Which approach is better?",goodRu:"Split/selective strategy",goodEn:"A split/selective strategy",bad1Ru:"Только range-bet",bad1En:"Range-bet only",bad2Ru:"Только range-check",bad2En:"Range-check only",whyRu:"E28/E29 образуют spectrum между high-frequency и selective nodes.",whyEn:"E28/E29 form a spectrum between high-frequency and selective nodes.",badWhy1Ru:"Strategy должна быть бинарной.",badWhy1En:"Strategy must be binary.",badWhy2Ru:"Один sizing обязан покрывать любой board.",badWhy2En:"One sizing must cover every board."},
  { kind:"changed",sourceRefs:["FTGU-E28","FTGU-E29"],cueRu:"Та же preflop линия; flop меняется с dry A-high на low connected.",cueEn:"Same preflop line; flop changes from dry A-high to low connected.",questionRu:"Как меняется pressure?",questionEn:"How does pressure change?",goodRu:"От broad/small к более selective",goodEn:"From broad/small toward more selective",bad1Ru:"Не меняется",bad1En:"No change",bad2Ru:"Становится ещё более automatic",bad2En:"Becomes even more automatic",whyRu:"Material range equalisation меняет flop family несмотря на ту же preflop role.",whyEn:"Material range equalization changes the flop family despite the same preflop role.",badWhy1Ru:"Preflop role полностью фиксирует flop strategy.",badWhy1En:"Preflop role completely fixes flop strategy.",badWhy2Ru:"Board changes только equity, не strategy shape.",badWhy2En:"Board changes equity but not strategy shape.",changedVariables:["board_class","range_equalization"]},
  { kind:"changed",sourceRefs:["FTGU-E28"],cueRu:"Та же board family, но Hero теперь OOP aggressor вместо IP.",cueEn:"Same board family, but Hero is now the OOP aggressor instead of IP.",questionRu:"Можно ли сохранить IP plan без проверки?",questionEn:"Can the IP plan be kept without re-evaluation?",goodRu:"Нет — role/position требует нового tree",goodEn:"No — role/position requires a new tree",bad1Ru:"Да, aggressor role важнее position",bad1En:"Yes, aggressor role matters more than position",bad2Ru:"Да, 3BP одинаковы IP/OOP",bad2En:"Yes, 3BPs are identical IP/OOP",whyRu:"Position changes realisation and checking incentives even when preflop aggressor identity is unchanged.",whyEn:"Position changes realization and checking incentives even when preflop aggressor identity is unchanged.",badWhy1Ru:"Initiative стирает positional disadvantage.",badWhy1En:"Initiative erases positional disadvantage.",badWhy2Ru:"SPR делает position неважной.",badWhy2En:"SPR makes position irrelevant.",changedVariables:["position_role"]},
  { kind:"boundary",sourceRefs:["FTGU-E28"],cueRu:"Learner видит '3-bet pot' и хочет ставить range маленько на любом flop.",cueEn:"The learner sees '3-bet pot' and wants to small range-bet every flop.",questionRu:"Где граница правила?",questionEn:"Where is the boundary?",goodRu:"High-frequency small bet требует сохранённого range advantage",goodEn:"High-frequency small betting requires preserved range advantage",bad1Ru:"Правило универсально",bad1En:"The rule is universal",bad2Ru:"Только stack depth ограничивает его",bad2En:"Only stack depth limits it",whyRu:"E28 не лицензирует universal c-bet; board-range interaction остаётся условием.",whyEn:"E28 does not license universal c-betting; board-range interaction remains a condition.",badWhy1Ru:"Pot type заменяет board analysis.",badWhy1En:"Pot type replaces board analysis.",badWhy2Ru:"Preflop 3-bet означает permanent nut advantage.",badWhy2En:"A preflop 3-bet means permanent nut advantage."},
];

const aggrOop: S[] = [
  {kind:"recognition",sourceRefs:["SLC-EXPLOITING-OOP-CBETS"],cueRu:"Hero — OOP 3-bettor; caller IP реализует equity легче.",cueEn:"Hero is the OOP 3-bettor; the IP caller realizes equity more easily.",questionRu:"Что меняется первым?",questionEn:"What changes first?",goodRu:"Checking/selection incentives растут",goodEn:"Checking/selection incentives increase",bad1Ru:"Initiative отменяет OOP",bad1En:"Initiative cancels OOP",bad2Ru:"Всегда range-bet",bad2En:"Always range-bet",whyRu:"Smash OOP 3BP material treats position as a structural cost rather than copying IP c-bets.",whyEn:"Smash OOP 3BP material treats position as a structural cost rather than copying IP c-bets.",badWhy1Ru:"Preflop aggressor всегда контролирует tree.",badWhy1En:"The preflop aggressor always controls the tree.",badWhy2Ru:"Caller IP не получает realisation edge.",badWhy2En:"The IP caller gets no realization edge."},
  {kind:"recognition",sourceRefs:["FTGU-E29"],cueRu:"OOP aggressor на board, где preflop advantage заметно equalised.",cueEn:"OOP aggressor on a board where the preflop advantage is materially equalized.",questionRu:"Какой signal?",questionEn:"Which signal?",goodRu:"Selective/check-heavy branch",goodEn:"Selective/check-heavy branch",bad1Ru:"Small range-bet по инициативе",bad1En:"Small range-bet because of initiative",bad2Ru:"Large range overbet",bad2En:"Large range overbet",whyRu:"Equalisation plus OOP makes unselective pressure especially fragile.",whyEn:"Equalization plus OOP makes unselective pressure especially fragile.",badWhy1Ru:"OOP не влияет после 3-bet.",badWhy1En:"OOP does not matter after a 3-bet.",badWhy2Ru:"Pot size гарантирует fold equity.",badWhy2En:"Pot size guarantees fold equity."},
  {kind:"decision",sourceRefs:["SLC-EXPLOITING-OOP-CBETS"],cueRu:"OOP 3-bettor имеет medium showdown hand на neutral board.",cueEn:"The OOP 3-bettor has a medium showdown hand on a neutral board.",questionRu:"Что лучше проверить?",questionEn:"What should be considered first?",goodRu:"Protected check branch",goodEn:"A protected check branch",bad1Ru:"Bet потому что hand впереди",bad1En:"Bet because the hand is ahead",bad2Ru:"Overbet для защиты",bad2En:"Overbet for protection",whyRu:"Medium hands often benefit from preserving a credible checking range and avoiding unnecessary pot inflation OOP.",whyEn:"Medium hands often benefit from preserving a credible checking range and avoiding unnecessary pot inflation OOP.",badWhy1Ru:"Любая likely-best hand обязана value bet.",badWhy1En:"Any likely-best hand must value bet.",badWhy2Ru:"Protection всегда требует большого sizing.",badWhy2En:"Protection always requires a large sizing."},
  {kind:"decision",sourceRefs:["FTGU-E29"],cueRu:"OOP 3-bettor на coordinated equaliser с marginal bluff candidate.",cueEn:"OOP 3-bettor on a coordinated equalizer with a marginal bluff candidate.",questionRu:"Default?",questionEn:"Default?",goodRu:"Check чаще",goodEn:"Check more often",bad1Ru:"Bluff из-за range advantage preflop",bad1En:"Bluff because of preflop range advantage",bad2Ru:"Jam low equity",bad2En:"Jam low equity",whyRu:"Selective nodes remove weak pressure candidates when caller coverage rises.",whyEn:"Selective nodes remove weak pressure candidates when caller coverage rises.",badWhy1Ru:"Preflop advantage never decays.",badWhy1En:"Preflop advantage never decays.",badWhy2Ru:"OOP bluffing получает бонус от position.",badWhy2En:"OOP bluffing gets a positional bonus."},
  {kind:"decision",sourceRefs:["SLC-EXPLOITING-OOP-CBETS"],cueRu:"Caller IP has shown tendency to attack weak OOP checking ranges.",cueEn:"The IP caller has shown a tendency to attack weak OOP checking ranges.",questionRu:"Как строить check range?",questionEn:"How should the checking range be built?",goodRu:"Оставлять достаточно strong hands в check",goodEn:"Keep enough strong hands in the checking range",bad1Ru:"Check только air",bad1En:"Check only air",bad2Ru:"Никогда не check",bad2En:"Never check",whyRu:"An unprotected check range creates an exploitable branch for the IP caller.",whyEn:"An unprotected check range creates an exploitable branch for the IP caller.",badWhy1Ru:"Check всегда означает weakness.",badWhy1En:"A check always means weakness.",badWhy2Ru:"Protection требует 100% betting.",badWhy2En:"Protection requires 100% betting."},
  {kind:"changed",sourceRefs:["FTGU-E28","FTGU-E29"],cueRu:"Та же OOP role; board меняется premium-preserving → equalising.",cueEn:"Same OOP role; board changes premium-preserving → equalizing.",questionRu:"Как меняется plan?",questionEn:"How does the plan change?",goodRu:"От некоторого broad pressure к большей selectivity/checking",goodEn:"From some broad pressure toward more selectivity/checking",bad1Ru:"Не меняется",bad1En:"No change",bad2Ru:"OOP требует больше bluff",bad2En:"OOP requires more bluffing",whyRu:"Board interaction still decides whether preflop advantage survives.",whyEn:"Board interaction still decides whether the preflop advantage survives.",badWhy1Ru:"Position alone fixes strategy.",badWhy1En:"Position alone fixes strategy.",badWhy2Ru:"Equalising board усиливает aggressor automatically.",badWhy2En:"An equalizing board automatically strengthens the aggressor.",changedVariables:["board_class"]},
  {kind:"changed",sourceRefs:["SLC-EXPLOITING-OOP-CBETS"],cueRu:"Та же board; Hero меняется OOP → IP aggressor.",cueEn:"Same board; Hero changes from OOP → IP aggressor.",questionRu:"Что пересчитать?",questionEn:"What should be recomputed?",goodRu:"Bet/check incentives и realisation",goodEn:"Bet/check incentives and realization",bad1Ru:"Ничего",bad1En:"Nothing",bad2Ru:"Только pot size",bad2En:"Only pot size",whyRu:"Position is a first-order branch variable in 3BP postflop.",whyEn:"Position is a first-order branch variable in 3BP postflop.",badWhy1Ru:"Aggressor identity makes positions equivalent.",badWhy1En:"Aggressor identity makes positions equivalent.",badWhy2Ru:"SPR fully determines strategy.",badWhy2En:"SPR fully determines strategy.",changedVariables:["position"]},
  {kind:"boundary",sourceRefs:["SLC-EXPLOITING-OOP-CBETS"],cueRu:"Learner хочет копировать IP 3BP c-bet heuristics в OOP node.",cueEn:"The learner wants to copy IP 3BP c-bet heuristics into an OOP node.",questionRu:"Допустимо?",questionEn:"Is that valid?",goodRu:"Нет — роль OOP требует отдельного tree",goodEn:"No — the OOP role requires a separate tree",bad1Ru:"Да, если Hero 3-bettor",bad1En:"Yes, if Hero is the 3-bettor",bad2Ru:"Да, если SPR низкий",bad2En:"Yes, if SPR is low",whyRu:"The source specifically treats OOP c-bet behaviour as distinct and exploitable when overextended.",whyEn:"The source specifically treats OOP c-bet behavior as distinct and exploitable when overextended.",badWhy1Ru:"Initiative dominates position.",badWhy1En:"Initiative dominates position.",badWhy2Ru:"Low SPR erases positional asymmetry.",badWhy2En:"Low SPR erases positional asymmetry."},
];

const callerIp: S[] = [
  {kind:"recognition",sourceRefs:["FTGU-E28","FTGU-E29"],cueRu:"Caller IP faces small high-frequency c-bet on a dry premium-preserving flop.",cueEn:"The IP caller faces a small high-frequency c-bet on a dry premium-preserving flop.",questionRu:"Что распознать?",questionEn:"What should be recognized?",goodRu:"Цена мала, но aggressor range остаётся сильной",goodEn:"The price is small, but the aggressor range remains strong",bad1Ru:"Small bet всегда weak",bad1En:"A small bet is always weak",bad2Ru:"IP caller всегда raise",bad2En:"The IP caller always raises",whyRu:"Defence must combine price with range strength rather than interpret size as weakness.",whyEn:"Defense must combine price with range strength rather than interpret size as weakness.",badWhy1Ru:"Sizing напрямую раскрывает hand strength.",badWhy1En:"Sizing directly reveals hand strength.",badWhy2Ru:"Position guarantees profitable aggression.",badWhy2En:"Position guarantees profitable aggression."},
  {kind:"recognition",sourceRefs:["CINJ-E09"],cueRu:"IP caller видит repeated small c-bet branch, который population может overuse/fold too much vs raise.",cueEn:"The IP caller sees a repeated small-cbet branch that the population may overuse/fold too much versus raises.",questionRu:"Какой exploit signal возможен?",questionEn:"Which exploit signal can exist?",goodRu:"Selective click-back/raise candidate",goodEn:"A selective click-back/raise candidate",bad1Ru:"Raise any two cards",bad1En:"Raise any two cards",bad2Ru:"Never raise in 3BP",bad2En:"Never raise in 3BPs",whyRu:"CINJ-E09 supports a branch-specific IP click-back exploit, not universal aggression.",whyEn:"CINJ-E09 supports a branch-specific IP click-back exploit, not universal aggression.",badWhy1Ru:"Population leak means all hands profitably raise.",badWhy1En:"A population leak means all hands profitably raise.",badWhy2Ru:"3BP callers cannot have raising ranges.",badWhy2En:"3BP callers cannot have raising ranges."},
  {kind:"decision",sourceRefs:["FTGU-E28"],cueRu:"IP caller has medium showdown hand vs small bet on dry board.",cueEn:"The IP caller has a medium showdown hand versus a small bet on a dry board.",questionRu:"Default response?",questionEn:"Default response?",goodRu:"Continue frequently via call when hand realizes well",goodEn:"Continue frequently by calling when the hand realizes well",bad1Ru:"Fold because 3-bettor strong",bad1En:"Fold because the 3-bettor is strong",bad2Ru:"Raise because bet small",bad2En:"Raise because the bet is small",whyRu:"A cheap price plus position can support continued realization without forcing a raise.",whyEn:"A cheap price plus position can support continued realization without forcing a raise.",badWhy1Ru:"Range disadvantage means every medium hand folds.",badWhy1En:"Range disadvantage means every medium hand folds.",badWhy2Ru:"Small sizing automatically invites a raise.",badWhy2En:"Small sizing automatically invites a raise."},
  {kind:"decision",sourceRefs:["FTGU-E29"],cueRu:"IP caller has strong draw on equalising coordinated board vs selective c-bet.",cueEn:"The IP caller has a strong draw on an equalizing coordinated board versus a selective c-bet.",questionRu:"Что важнее?",questionEn:"What matters most?",goodRu:"Evaluate call/raise through equity, nut potential and continuing range",goodEn:"Evaluate call/raise through equity, nut potential and the continuing range",bad1Ru:"Auto-raise every draw",bad1En:"Auto-raise every draw",bad2Ru:"Auto-fold because 3BP",bad2En:"Auto-fold because it is a 3BP",whyRu:"Selective boards require hand-family and range interaction, not a draw-name shortcut.",whyEn:"Selective boards require hand-family and range interaction, not a draw-name shortcut.",badWhy1Ru:"Draw label determines action.",badWhy1En:"The draw label determines the action.",badWhy2Ru:"Preflop caller cannot pressure postflop.",badWhy2En:"The preflop caller cannot apply pressure postflop."},
  {kind:"decision",sourceRefs:["CINJ-E09"],cueRu:"Observed branch-specific overfold to small IP click-back raises is credible.",cueEn:"A credible branch-specific overfold to small IP click-back raises has been observed.",questionRu:"Как использовать leak?",questionEn:"How should the leak be used?",goodRu:"Expand selected raise candidates within the evidenced branch",goodEn:"Expand selected raise candidates within the evidenced branch",bad1Ru:"Raise every flop forever",bad1En:"Raise every flop forever",bad2Ru:"Ignore evidence",bad2En:"Ignore the evidence",whyRu:"Exploit stays branch-specific and evidence-qualified.",whyEn:"The exploit stays branch-specific and evidence-qualified.",badWhy1Ru:"One leak generalises to all boards/sizes.",badWhy1En:"One leak generalizes to all boards/sizes.",badWhy2Ru:"Exploit requires exact solver frequency first.",badWhy2En:"An exploit requires an exact solver frequency first."},
  {kind:"changed",sourceRefs:["FTGU-E28","FTGU-E29"],cueRu:"Same hand/role; c-bet size changes small → large.",cueEn:"Same hand/role; c-bet size changes small → large.",questionRu:"Как сдвигается marginal defence?",questionEn:"How does marginal defense shift?",goodRu:"Tighter; price and bettor range concentration matter more",goodEn:"Tighter; price and bettor range concentration matter more",bad1Ru:"Defend wider because pot bigger",bad1En:"Defend wider because the pot is bigger",bad2Ru:"No change",bad2En:"No change",whyRu:"A larger price removes marginal continues and usually represents a more selected betting range.",whyEn:"A larger price removes marginal continues and usually represents a more selected betting range.",badWhy1Ru:"Bigger pot improves caller price.",badWhy1En:"A bigger pot improves the caller's price.",badWhy2Ru:"Sizing does not alter defence EV.",badWhy2En:"Sizing does not alter defense EV.",changedVariables:["cbet_size"]},
  {kind:"changed",sourceRefs:["FTGU-E29"],cueRu:"Same IP caller; board changes dry high → equalising connected.",cueEn:"Same IP caller; board changes dry high → equalizing connected.",questionRu:"Как меняется caller leverage?",questionEn:"How does caller leverage change?",goodRu:"More credible continue/raise coverage",goodEn:"More credible continue/raise coverage",bad1Ru:"Worse because aggressor always stronger",bad1En:"Worse because the aggressor is always stronger",bad2Ru:"No change",bad2En:"No change",whyRu:"Equalising boards retain more strong caller regions and reduce automatic aggressor leverage.",whyEn:"Equalizing boards retain more strong caller regions and reduce automatic aggressor leverage.",badWhy1Ru:"Preflop caller range never catches up.",badWhy1En:"The preflop caller range never catches up.",badWhy2Ru:"Board class does not affect caller coverage.",badWhy2En:"Board class does not affect caller coverage.",changedVariables:["board_class"]},
  {kind:"boundary",sourceRefs:["CINJ-E09"],cueRu:"Population click-back leak is not observed in this room/size/board branch.",cueEn:"The population click-back leak is not observed in this room/size/board branch.",questionRu:"Можно ли переносить exploit?",questionEn:"Can the exploit be imported?",goodRu:"Нет — вернуть baseline until evidence",goodEn:"No — return to baseline until evidence",bad1Ru:"Да, leak universal",bad1En:"Yes, the leak is universal",bad2Ru:"Да, потому что Hero IP",bad2En:"Yes, because Hero is IP",whyRu:"CINJ exploit is branch-specific evidence, not a permanent theorem.",whyEn:"The CINJ exploit is branch-specific evidence, not a permanent theorem.",badWhy1Ru:"Population tendencies одинаковы во всех pools.",badWhy1En:"Population tendencies are identical in all pools.",badWhy2Ru:"Position alone proves overfold.",badWhy2En:"Position alone proves overfold."},
];

const callerOop: S[] = [
  {kind:"recognition",sourceRefs:["CP-G3-L09"],cueRu:"OOP caller in 3BP faces flop pressure.",cueEn:"The OOP caller in a 3BP faces flop pressure.",questionRu:"Какой structural problem ключевой?",questionEn:"Which structural problem is key?",goodRu:"Poor realisation + future pressure",goodEn:"Poor realization plus future pressure",bad1Ru:"Only pot odds",bad1En:"Only pot odds",bad2Ru:"Initiative is irrelevant",bad2En:"Initiative is irrelevant",whyRu:"CP-G3-L09 treats OOP 3BP defence as a range construction/realisation problem, not a one-street price problem.",whyEn:"CP-G3-L09 treats OOP 3BP defense as a range-construction/realization problem, not a one-street price problem.",badWhy1Ru:"Current price fully determines OOP defence.",badWhy1En:"The current price fully determines OOP defense.",badWhy2Ru:"Future streets do not matter in 3BP.",badWhy2En:"Future streets do not matter in 3BPs."},
  {kind:"recognition",sourceRefs:["CP-G3-L09"],cueRu:"OOP caller has strong hand but checking range would be empty of strength if it always raises.",cueEn:"The OOP caller has a strong hand, but the checking range would be empty of strength if it always raised.",questionRu:"Что распознать?",questionEn:"What should be recognized?",goodRu:"Need protected continues/checks",goodEn:"Need protected continues/checks",bad1Ru:"Raise all strong hands",bad1En:"Raise all strong hands",bad2Ru:"Fold all medium hands",bad2En:"Fold all medium hands",whyRu:"A defendable OOP tree needs strength distributed into non-aggressive branches.",whyEn:"A defendable OOP tree needs strength distributed into non-aggressive branches.",badWhy1Ru:"Strong hand label forces raise.",badWhy1En:"A strong-hand label forces a raise.",badWhy2Ru:"Checking always caps range.",badWhy2En:"Checking always caps the range."},
  {kind:"decision",sourceRefs:["CP-G3-L09"],cueRu:"Small c-bet, OOP caller has medium hand with robust equity.",cueEn:"Small c-bet, OOP caller has a medium hand with robust equity.",questionRu:"Default?",questionEn:"Default?",goodRu:"Defend enough via call/check-call",goodEn:"Defend sufficiently via call/check-call",bad1Ru:"Overfold because OOP",bad1En:"Overfold because OOP",bad2Ru:"Raise all medium hands",bad2En:"Raise all medium hands",whyRu:"Cheap sizing plus robust equity supports continuing despite positional disadvantage.",whyEn:"Cheap sizing plus robust equity supports continuing despite positional disadvantage.",badWhy1Ru:"OOP means marginal hands cannot realise any equity.",badWhy1En:"OOP means marginal hands cannot realize any equity.",badWhy2Ru:"Only aggression can realize equity.",badWhy2En:"Only aggression can realize equity."},
  {kind:"decision",sourceRefs:["CP-G3-L09"],cueRu:"Large c-bet, OOP caller has dominated weak pair/no redraw.",cueEn:"Large c-bet, OOP caller has a dominated weak pair with no redraw.",questionRu:"Default?",questionEn:"Default?",goodRu:"Fold more readily",goodEn:"Fold more readily",bad1Ru:"Call because pot already large",bad1En:"Call because the pot is already large",bad2Ru:"Raise as bluff-catcher",bad2En:"Raise as a bluff-catcher",whyRu:"Large sizing worsens price and magnifies poor realisation for weak dominated classes.",whyEn:"Large sizing worsens price and magnifies poor realization for weak dominated classes.",badWhy1Ru:"Sunk investment justifies wider calls.",badWhy1En:"Sunk investment justifies wider calls.",badWhy2Ru:"Weak pair blocks enough value automatically.",badWhy2En:"A weak pair automatically blocks enough value."},
  {kind:"decision",sourceRefs:["CP-G3-L09"],cueRu:"OOP caller checks strong value on board where aggressor continues betting many worse hands.",cueEn:"The OOP caller checks strong value on a board where the aggressor keeps betting many worse hands.",questionRu:"Может ли slow branch быть valid?",questionEn:"Can a slower branch be valid?",goodRu:"Да, если check keeps range protected and captures future bets",goodEn:"Yes, if checking protects the range and captures future bets",bad1Ru:"Нет, strong always raise",bad1En:"No, strong hands always raise",bad2Ru:"Нет, OOP must lead",bad2En:"No, OOP must lead",whyRu:"Low-frequency strong checks can protect OOP continues and preserve opponent bluffs/value mistakes.",whyEn:"Strong checks can protect OOP continues and preserve opponent bluffs/value mistakes.",badWhy1Ru:"Immediate value always dominates future EV.",badWhy1En:"Immediate value always dominates future EV.",badWhy2Ru:"OOP position requires taking initiative immediately.",badWhy2En:"Being OOP requires taking initiative immediately."},
  {kind:"changed",sourceRefs:["CP-G3-L09"],cueRu:"Same hand/board, bet size small → large.",cueEn:"Same hand/board, bet size small → large.",questionRu:"Как меняется weakest continue?",questionEn:"How does the weakest continue change?",goodRu:"Many marginal continues fall out",goodEn:"Many marginal continues fall out",bad1Ru:"More calls because pot larger",bad1En:"More calls because the pot is larger",bad2Ru:"No change",bad2En:"No change",whyRu:"Price and future SPR materially change OOP realisation EV.",whyEn:"Price and future SPR materially change OOP realization EV.",badWhy1Ru:"Pot size alone improves calls.",badWhy1En:"Pot size alone improves calls.",badWhy2Ru:"Sizing does not change future pressure.",badWhy2En:"Sizing does not change future pressure.",changedVariables:["bet_size","future_spr"]},
  {kind:"changed",sourceRefs:["CP-G3-L09"],cueRu:"Same hand/size, Hero moves OOP caller → IP caller.",cueEn:"Same hand/size, Hero moves from OOP caller → IP caller.",questionRu:"Что меняется?",questionEn:"What changes?",goodRu:"Realisation improves and defence can widen/select differently",goodEn:"Realization improves and defense can widen/select differently",bad1Ru:"Nothing",bad1En:"Nothing",bad2Ru:"Only preflop range",bad2En:"Only the preflop range",whyRu:"Position directly changes future action control and equity realisation.",whyEn:"Position directly changes future action control and equity realization.",badWhy1Ru:"Caller role fixes strategy regardless of position.",badWhy1En:"The caller role fixes strategy regardless of position.",badWhy2Ru:"SPR removes position from the tree.",badWhy2En:"SPR removes position from the tree.",changedVariables:["position"]},
  {kind:"boundary",sourceRefs:["CP-G3-L09"],cueRu:"Learner thinks OOP caller should either overfold or overraise to simplify.",cueEn:"The learner thinks the OOP caller should either overfold or overraise to simplify.",questionRu:"Boundary?",questionEn:"Boundary?",goodRu:"Need a protected call/check-call region",goodEn:"Need a protected call/check-call region",bad1Ru:"Overfold is always safest",bad1En:"Overfolding is always safest",bad2Ru:"Overraise removes positional disadvantage",bad2En:"Overraising removes positional disadvantage",whyRu:"CP-G3-L09 explicitly builds a defendable OOP tree rather than collapsing it to fold/raise extremes.",whyEn:"CP-G3-L09 explicitly builds a defendable OOP tree rather than collapsing it to fold/raise extremes.",badWhy1Ru:"Position disadvantage justifies abandoning equilibrium protection.",badWhy1En:"Positional disadvantage justifies abandoning range protection.",badWhy2Ru:"Aggression cancels OOP structurally.",badWhy2En:"Aggression structurally cancels OOP."},
];

const matrix: S[] = [
  {kind:"recognition",sourceRefs:["FTGU-E28","FTGU-E29"],cueRu:"3BP flop family changes dry-high → coordinated-middle.",cueEn:"3BP flop family changes dry-high → coordinated-middle.",questionRu:"Что должно меняться вместе с board?",questionEn:"What should change with the board?",goodRu:"Frequency/size/check split",goodEn:"Frequency/size/check split",bad1Ru:"Nothing because pot type same",bad1En:"Nothing because pot type is the same",bad2Ru:"Only hand names",bad2En:"Only hand names",whyRu:"E28/E29 define different strategic families by how the board preserves or equalises preflop advantage.",whyEn:"E28/E29 define different strategic families by how the board preserves or equalizes preflop advantage.",badWhy1Ru:"3BP is one strategy class.",badWhy1En:"A 3BP is one strategy class.",badWhy2Ru:"Sizing independent of range interaction.",badWhy2En:"Sizing is independent of range interaction."},
  {kind:"recognition",sourceRefs:["FTGU-E28","FTGU-E29"],cueRu:"Same board, c-bet size changes small → large.",cueEn:"Same board, c-bet size changes small → large.",questionRu:"Что меняется у defender?",questionEn:"What changes for the defender?",goodRu:"Price + likely bettor selection",goodEn:"Price plus likely bettor selection",bad1Ru:"Nothing",bad1En:"Nothing",bad2Ru:"Only pot visual size",bad2En:"Only the pot's visual size",whyRu:"Sizing is part of the range/defence matrix, not decoration.",whyEn:"Sizing is part of the range/defense matrix, not decoration.",badWhy1Ru:"All bets represent same range.",badWhy1En:"All bets represent the same range.",badWhy2Ru:"Defence thresholds never move with price.",badWhy2En:"Defense thresholds never move with price."},
  {kind:"decision",sourceRefs:["FTGU-E28"],cueRu:"Premium-preserving board + small size.",cueEn:"Premium-preserving board plus small size.",questionRu:"Best matrix cell?",questionEn:"Best matrix cell?",goodRu:"Broad aggressor bet / wide enough defence",goodEn:"Broad aggressor bet / sufficiently wide defense",bad1Ru:"Polar only / overfold",bad1En:"Polar only / overfold",bad2Ru:"Range check / range fold",bad2En:"Range check / range fold",whyRu:"Small broad betting and cheap defence are paired consequences of the same node.",whyEn:"Small broad betting and cheap defense are paired consequences of the same node.",badWhy1Ru:"Small size always means polar strength.",badWhy1En:"A small size always means polar strength.",badWhy2Ru:"Defender should ignore pot odds.",badWhy2En:"The defender should ignore pot odds."},
  {kind:"decision",sourceRefs:["FTGU-E29"],cueRu:"Equalising board + selected larger size.",cueEn:"Equalizing board plus a selected larger size.",questionRu:"Best matrix cell?",questionEn:"Best matrix cell?",goodRu:"Narrower bettor range / tighter defence",goodEn:"Narrower bettor range / tighter defense",bad1Ru:"Range-bet / same defence",bad1En:"Range-bet / same defense",bad2Ru:"Bet size irrelevant",bad2En:"Bet size irrelevant",whyRu:"Selective strategy and higher price jointly remove marginal hands from both sides' active branches.",whyEn:"Selective strategy and a higher price jointly remove marginal hands from both sides' active branches.",badWhy1Ru:"Board equalisation increases all betting.",badWhy1En:"Board equalization increases all betting.",badWhy2Ru:"Defender responds only to hand rank.",badWhy2En:"The defender responds only to hand rank."},
  {kind:"decision",sourceRefs:["FTGU-E28","FTGU-E29"],cueRu:"Unknown exact solver frequency, mechanism authority is clear.",cueEn:"Exact solver frequency is unknown, but the mechanism authority is clear.",questionRu:"Что учить?",questionEn:"What should be taught?",goodRu:"Direction/range shape/size family",goodEn:"Direction/range shape/size family",bad1Ru:"Invent exact 63%",bad1En:"Invent an exact 63%",bad2Ru:"Teach nothing",bad2En:"Teach nothing",whyRu:"The product can teach robust structural differences without fabricating exact frequencies.",whyEn:"The product can teach robust structural differences without fabricating exact frequencies.",badWhy1Ru:"Exact precision can be guessed from mechanism.",badWhy1En:"Exact precision can be guessed from the mechanism.",badWhy2Ru:"No exact frequency means no useful knowledge.",badWhy2En:"No exact frequency means no useful knowledge."},
  {kind:"changed",sourceRefs:["FTGU-E28","FTGU-E29"],cueRu:"Same role/board; sizing doubles.",cueEn:"Same role/board; sizing doubles.",questionRu:"Как меняется marginal defender?",questionEn:"How does the marginal defender change?",goodRu:"More folds / stronger continuing region",goodEn:"More folds / stronger continuing region",bad1Ru:"Wider calls",bad1En:"Wider calls",bad2Ru:"No change",bad2En:"No change",whyRu:"Larger price lowers marginal continue EV and often corresponds to a more selected bettor range.",whyEn:"A larger price lowers marginal continue EV and often corresponds to a more selected bettor range.",badWhy1Ru:"Bigger pot means better price.",badWhy1En:"A bigger pot means a better price.",badWhy2Ru:"Sizing never changes range composition.",badWhy2En:"Sizing never changes range composition.",changedVariables:["bet_size"]},
  {kind:"changed",sourceRefs:["FTGU-E28","FTGU-E29"],cueRu:"Same sizing; board dry-high → connected-middle.",cueEn:"Same sizing; board dry-high → connected-middle.",questionRu:"Что меняется?",questionEn:"What changes?",goodRu:"Aggressor frequency/selectivity and defender continue shape",goodEn:"Aggressor frequency/selectivity and defender continue shape",bad1Ru:"Nothing",bad1En:"Nothing",bad2Ru:"Only targetSeconds",bad2En:"Only targetSeconds",whyRu:"The board changes which range regions survive and therefore both sides' branches.",whyEn:"The board changes which range regions survive and therefore both sides' branches.",badWhy1Ru:"Sizing fixes strategy independent of board.",badWhy1En:"Sizing fixes strategy independent of board.",badWhy2Ru:"3BP caller never has nut coverage.",badWhy2En:"A 3BP caller never has nut coverage.",changedVariables:["board_class"]},
  {kind:"boundary",sourceRefs:["FTGU-E28","FTGU-E29"],cueRu:"Learner wants one memorized 3BP c-bet size/frequency for every role and board.",cueEn:"The learner wants one memorized 3BP c-bet size/frequency for every role and board.",questionRu:"Boundary?",questionEn:"Boundary?",goodRu:"Matrix must retain role × board × size",goodEn:"The matrix must retain role × board × size",bad1Ru:"One default is enough",bad1En:"One default is enough",bad2Ru:"Only stack matters",bad2En:"Only stack matters",whyRu:"The sources explicitly split high-frequency and selective nodes, while position changes execution.",whyEn:"The sources explicitly split high-frequency and selective nodes, while position changes execution.",badWhy1Ru:"Simplification should erase causal variables.",badWhy1En:"Simplification should erase causal variables.",badWhy2Ru:"Range advantage is static after preflop.",badWhy2En:"Range advantage is static after preflop."},
];

function fourBet(skillId:string,prefix:string,focus:string,sourceRefs:string[]): PracticalDecision[] {
  const common: S[] = [
    {kind:"recognition",sourceRefs,cueRu:`4BP low-SPR: ${focus}.`,cueEn:`4BP low-SPR: ${focus}.`,questionRu:"Что распознать прежде всего?",questionEn:"What should be recognized first?",goodRu:"Compressed tree, но не automatic stack-off",goodEn:"A compressed tree, but not automatic stack-off",bad1Ru:"Low SPR = shove any made hand",bad1En:"Low SPR = shove any made hand",bad2Ru:"SPR не важен",bad2En:"SPR is irrelevant",whyRu:"CP-G3-L10 использует low SPR как simplification geometry, не как разрешение игнорировать hand/board/role.",whyEn:"CP-G3-L10 uses low SPR as simplifying geometry, not permission to ignore hand/board/role.",badWhy1Ru:"Меньше улиц означает одинаковый EV у всех hands.",badWhy1En:"Fewer streets means equal EV for all hands.",badWhy2Ru:"4-bet pot отменяет range interaction.",badWhy2En:"A 4-bet pot cancels range interaction."},
    {kind:"recognition",sourceRefs,cueRu:"Low-SPR board changes favourable → materially adverse.",cueEn:"Low-SPR board changes from favorable → materially adverse.",questionRu:"Может ли action change?",questionEn:"Can the action change?",goodRu:"Да — board/hand family всё ещё matter",goodEn:"Yes — board/hand family still matter",bad1Ru:"Нет, SPR fixes action",bad1En:"No, SPR fixes the action",bad2Ru:"Нет, 4-bettor always commits",bad2En:"No, the 4-bettor always commits",whyRu:"Compressed geometry shortens the tree but does not remove contextual hand strength.",whyEn:"Compressed geometry shortens the tree but does not remove contextual hand strength.",badWhy1Ru:"SPR is a strategy answer key.",badWhy1En:"SPR is a strategy answer key.",badWhy2Ru:"Preflop investment forces postflop commitment.",badWhy2En:"Preflop investment forces postflop commitment."},
    {kind:"decision",sourceRefs,cueRu:"Favourable low-SPR flop with range advantage.",cueEn:"Favorable low-SPR flop with range advantage.",questionRu:"Which simplification can be practical?",questionEn:"Which simplification can be practical?",goodRu:"Small pressure with a broad eligible region",goodEn:"Small pressure with a broad eligible region",bad1Ru:"Pot-size every hand",bad1En:"Pot-size every hand",bad2Ru:"Check all",bad2En:"Check all",whyRu:"L10 supports small efficient betting on suitable compressed nodes rather than unnecessary large sizing.",whyEn:"L10 supports small efficient betting on suitable compressed nodes rather than unnecessary large sizing.",badWhy1Ru:"Low SPR requires maximum size.",badWhy1En:"Low SPR requires maximum sizing.",badWhy2Ru:"4BP always needs zero betting.",badWhy2En:"4BPs always need zero betting."},
    {kind:"decision",sourceRefs,cueRu:"Medium-strength hand would face a jam after betting.",cueEn:"A medium-strength hand would face a jam after betting.",questionRu:"Что проверить до bet?",questionEn:"What should be checked before betting?",goodRu:"Jam/reopen exposure and investment ceiling",goodEn:"Jam/reopen exposure and the investment ceiling",bad1Ru:"Only current equity",bad1En:"Only current equity",bad2Ru:"Bet because pot huge",bad2En:"Bet because the pot is huge",whyRu:"CP-G3-L10/raising framework requires planning the response tree before investing in compressed pots.",whyEn:"CP-G3-L10/raising framework requires planning the response tree before investing in compressed pots.",badWhy1Ru:"Future action can be ignored at low SPR.",badWhy1En:"Future action can be ignored at low SPR.",badWhy2Ru:"Sunk pot size forces betting.",badWhy2En:"The sunk pot size forces betting."},
    {kind:"decision",sourceRefs,cueRu:"A strong hand can check without forfeiting all value because opponent retains bluffs/value bets.",cueEn:"A strong hand can check without forfeiting all value because the opponent retains bluffs/value bets.",questionRu:"Can a protected check exist?",questionEn:"Can a protected check exist?",goodRu:"Да",goodEn:"Yes",bad1Ru:"Нет, low SPR means bet all strong hands",bad1En:"No, low SPR means bet all strong hands",bad2Ru:"Нет, checking always caps",bad2En:"No, checking always caps",whyRu:"L10 supports protected checks even in compressed pots where branch incentives justify them.",whyEn:"L10 supports protected checks even in compressed pots where branch incentives justify them.",badWhy1Ru:"Low SPR eliminates checking ranges.",badWhy1En:"Low SPR eliminates checking ranges.",badWhy2Ru:"A check always means weakness.",badWhy2En:"A check always means weakness."},
    {kind:"changed",sourceRefs,cueRu:"Same hand/board, SPR falls materially after a larger preflop pot.",cueEn:"Same hand/board, SPR falls materially after a larger preflop pot.",questionRu:"What changes?",questionEn:"What changes?",goodRu:"Tree compresses; future leverage and sizing options shrink",goodEn:"The tree compresses; future leverage and sizing options shrink",bad1Ru:"Hand becomes automatically stronger",bad1En:"The hand automatically becomes stronger",bad2Ru:"Nothing",bad2En:"Nothing",whyRu:"SPR changes decision geometry, not the intrinsic hand label.",whyEn:"SPR changes decision geometry, not the intrinsic hand label.",badWhy1Ru:"Lower SPR increases absolute hand strength.",badWhy1En:"Lower SPR increases absolute hand strength.",badWhy2Ru:"Pot geometry does not affect planning.",badWhy2En:"Pot geometry does not affect planning.",changedVariables:["spr"]},
    {kind:"changed",sourceRefs,cueRu:"Same SPR; hand family changes robust value → marginal one-pair/bluff-catcher.",cueEn:"Same SPR; hand family changes from robust value → marginal one-pair/bluff-catcher.",questionRu:"Does commitment stay identical?",questionEn:"Does commitment stay identical?",goodRu:"Нет",goodEn:"No",bad1Ru:"Да, SPR determines all",bad1En:"Yes, SPR determines everything",bad2Ru:"Да, 4BP commits all pairs",bad2En:"Yes, a 4BP commits all pairs",whyRu:"Hand-family strength and vulnerability still set the value/commitment boundary.",whyEn:"Hand-family strength and vulnerability still set the value/commitment boundary.",badWhy1Ru:"Geometry replaces hand evaluation.",badWhy1En:"Geometry replaces hand evaluation.",badWhy2Ru:"Preflop pot size guarantees stack-off.",badWhy2En:"Preflop pot size guarantees a stack-off.",changedVariables:["hand_family"]},
    {kind:"boundary",sourceRefs,cueRu:"Learner says: low SPR, therefore any top pair/overpair is automatic stack-off.",cueEn:"Learner says: low SPR, therefore any top pair/overpair is an automatic stack-off.",questionRu:"Boundary?",questionEn:"Boundary?",goodRu:"Reject universal stack-off; keep board/range/hand/jam context",goodEn:"Reject universal stack-off; keep board/range/hand/jam context",bad1Ru:"Accept rule",bad1En:"Accept the rule",bad2Ru:"Use only preflop hand rank",bad2En:"Use only preflop hand rank",whyRu:"Low SPR is a compression heuristic, not a universal commitment threshold.",whyEn:"Low SPR is a compression heuristic, not a universal commitment threshold.",badWhy1Ru:"All compressed pots have identical thresholds.",badWhy1En:"All compressed pots have identical thresholds.",badWhy2Ru:"Board/runout cannot change commitment.",badWhy2En:"Board/runout cannot change commitment."},
  ];
  return make(skillId,prefix,common);
}

export const threeBetFourBetA7ExpansionDecisions: PracticalDecision[] = [
  ...make("3BP-01","PM-3BP-01-A7",aggrIp),
  ...make("3BP-02","PM-3BP-02-A7",aggrOop),
  ...make("3BP-03","PM-3BP-03-A7",callerIp),
  ...make("3BP-04","PM-3BP-04-A7",callerOop),
  ...make("3BP-05","PM-3BP-05-A7",matrix),
  ...fourBet("4BP-01","PM-4BP-01-A7","pot geometry / compression",["CP-G3-L10"]),
  ...fourBet("4BP-02","PM-4BP-02-A7","hand-family commitment thresholds",["CP-G3-L10"]),
  ...fourBet("4BP-03","PM-4BP-03-A7","protected checking",["CP-G3-L10"]),
  ...fourBet("4BP-04","PM-4BP-04-A7","jam/reopen exposure",["CP-G3-L10","CP-G3-L04"]),
];
