import type { PracticalDecision } from "./types";

const o = (id: string, textRu: string, textEn: string, misconception?: string) => ({ id, textRu, textEn, misconception });

export const preflopCoreExpansionDecisions: PracticalDecision[] = [
  // PF-01 — RFI by position. Source: FTGU-E02.
  {
    id: "PM-PF-01-101", skillId: "PF-01", kind: "recognition", sourceRefs: ["FTGU-E02"], assumptions: ["same rake", "same stack", "no unusual table dynamic"],
    cueRu: "Сравни HJ и BTN first-in.", cueEn: "Compare HJ and BTN first-in.", questionRu: "Какая структурная причина обычно позволяет BTN открыть шире?", questionEn: "Which structural reason usually lets BTN open wider?",
    actionOptions: [o("a", "Меньше игроков позади и лучше реализация", "Fewer players behind and better realization"), o("b", "BTN автоматически получает лучшие карты", "BTN automatically gets better cards", "POSITION_MAGIC"), o("c", "Rake исчезает на BTN", "Rake disappears on the BTN", "RAKE_DISAPPEARS")],
    reasonOptions: [o("r1", "Позиция постепенно меняет EV стила и будущую реализацию equity", "Position gradually changes steal EV and future realization"), o("r2", "Позиция влияет только после флопа", "Position matters only after the flop", "POSITION_POSTFLOP_ONLY"), o("r3", "Любая поздняя позиция означает одинаковый диапазон", "Every late position implies the same range", "POSITION_COLLAPSE")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 20, explanationRu: "FTGU-E02 связывает widening с fewer players behind и улучшением equity realisation, а не с названием позиции само по себе.", explanationEn: "FTGU-E02 links widening to fewer players behind and improved equity realization, not to the position label by itself.",
  },
  {
    id: "PM-PF-01-102", skillId: "PF-01", kind: "recognition", sourceRefs: ["FTGU-E02"], assumptions: ["fringe open", "competent aggressive players behind"],
    cueRu: "Fringe open выглядит допустимо по позиции, но позади несколько сильных aggressive игроков.", cueEn: "A fringe open looks acceptable by position, but several strong aggressive players remain behind.", questionRu: "Какой фактор становится главным adjustment?", questionEn: "Which factor becomes the main adjustment?",
    actionOptions: [o("a", "Только nominal position", "Only nominal position", "POSITION_LABEL_ONLY"), o("b", "Players behind и способность range защищаться против pressure", "Players behind and the range's ability to defend versus pressure"), o("c", "Только suit руки", "Only the hand's suit", "SUIT_ONLY")],
    reasonOptions: [o("r1", "Chart fringe должен сужаться, если pressure делает дальнейшую defence плохой", "The chart fringe should contract if pressure makes future defense poor"), o("r2", "Competent players behind увеличивают fold equity opener", "Competent players behind increase the opener's fold equity", "BACKWARDS_PRESSURE"), o("r3", "Players behind не входят в opening EV", "Players behind do not enter opening EV", "PLAYERS_BEHIND_IGNORED")],
    correctActionId: "b", correctReasonId: "r1", targetSeconds: 25, explanationRu: "FTGU-E02 прямо требует корректировать fringe по игрокам позади и не открывать range, который затем невозможно защищать без явно плохих continues.", explanationEn: "FTGU-E02 explicitly adjusts the fringe for players behind and warns against opening a range that cannot be defended without clearly bad continues.",
  },
  {
    id: "PM-PF-01-103", skillId: "PF-01", kind: "decision", sourceRefs: ["FTGU-E02"], assumptions: ["same position", "rake increases", "hand is near opening fringe"],
    cueRu: "Та же позиция и hand, но rake заметно выше.", cueEn: "Same position and hand, but rake is materially higher.", questionRu: "Как должен двигаться marginal open?", questionEn: "How should a marginal open move?",
    actionOptions: [o("a", "Чаще к fold", "More often toward fold"), o("b", "Чаще к open", "More often toward open", "RAKE_BACKWARDS"), o("c", "Не менять никогда", "Never change", "RAKE_IGNORED")],
    reasonOptions: [o("r1", "Rake снимает EV прежде всего с marginal opens", "Rake removes EV first from marginal opens"), o("r2", "Higher rake улучшает steal price", "Higher rake improves the steal price", "RAKE_BACKWARDS"), o("r3", "Rake важен только на river", "Rake matters only on the river", "RAKE_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 20, explanationRu: "FTGU-E02 прямо указывает, что rake удаляет marginal opens и lower-rake games допускают более широкую архитектуру.", explanationEn: "FTGU-E02 explicitly states that rake removes marginal opens and lower-rake games support wider opening architecture.", changedVariables: ["rake"],
  },
  {
    id: "PM-PF-01-104", skillId: "PF-01", kind: "decision", sourceRefs: ["FTGU-E02"], assumptions: ["BTN first-in", "weak passive blinds", "fringe hand"],
    cueRu: "BTN first-in, blinds слабые и пассивные.", cueEn: "BTN first-in, blinds are weak and passive.", questionRu: "Что разумнее сделать с fringe range?", questionEn: "What is the reasonable adjustment to the fringe?",
    actionOptions: [o("a", "Немного расширить", "Widen somewhat"), o("b", "Сильно сузить", "Tighten sharply", "BACKWARDS_TABLE_ADJUSTMENT"), o("c", "Игнорировать blinds", "Ignore the blinds", "PLAYERS_BEHIND_IGNORED")],
    reasonOptions: [o("r1", "Слабые/passive players behind улучшают steal и realisation branches", "Weak/passive players behind improve steal and realization branches"), o("r2", "Passive blinds чаще 3-bet", "Passive blinds 3-bet more often", "PLAYER_TYPE_BACKWARDS"), o("r3", "Opening EV определяется только equity cards", "Opening EV is determined only by card equity", "CARDS_ONLY")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25, explanationRu: "FTGU-E02 разрешает widening fringe против weak/passive players behind, сохраняя charts как defaults, а не законы.", explanationEn: "FTGU-E02 allows widening the fringe against weak/passive players behind, treating charts as defaults rather than laws.",
  },
  {
    id: "PM-PF-01-105", skillId: "PF-01", kind: "decision", sourceRefs: ["FTGU-E02"], assumptions: ["UTG first-in", "hand has weak frequent strength", "many players behind"],
    cueRu: "UTG first-in с рукой, которая редко выдерживает action и имеет слабую frequent strength.", cueEn: "UTG first-in with a hand that rarely tolerates action and has weak frequent strength.", questionRu: "Какой default лучше?", questionEn: "Which default is better?",
    actionOptions: [o("a", "Open ради steal", "Open for the steal", "EARLY_STEAL_AUTOPILOT"), o("b", "Fold fringe", "Fold the fringe"), o("c", "Open, потому что suitedness всегда достаточно", "Open because suitedness is always enough", "SUITED_AUTOPILOT")],
    reasonOptions: [o("r1", "UTG architecture сильнее ориентирована на value/field thinning и имеет много игроков позади", "UTG architecture is more value/field-thinning oriented with many players behind"), o("r2", "UTG получает лучшую позицию postflop", "UTG gets the best postflop position", "POSITION_BACKWARDS"), o("r3", "Early position не влияет на range", "Early position does not affect the range", "POSITION_IGNORED")],
    correctActionId: "b", correctReasonId: "r1", targetSeconds: 25, explanationRu: "FTGU-E02 описывает UTG как более value-oriented architecture; fringe steals добавляются постепенно к поздним позициям.", explanationEn: "FTGU-E02 describes UTG as a more value-oriented architecture, with fringe steals added progressively toward late position.",
  },
  {
    id: "PM-PF-01-106", skillId: "PF-01", kind: "changed", sourceRefs: ["FTGU-E02"], assumptions: ["same BTN fringe hand", "blinds change passive -> aggressive"],
    cueRu: "BTN hand не меняется, но blinds становятся заметно агрессивнее.", cueEn: "The BTN hand is unchanged, but the blinds become materially more aggressive.", questionRu: "Как меняется attractiveness open?", questionEn: "How does the open's attractiveness change?",
    actionOptions: [o("a", "Повышается", "It increases", "PRESSURE_BACKWARDS"), o("b", "Не меняется", "It does not change", "PLAYERS_BEHIND_IGNORED"), o("c", "Падает на fringe", "It falls on the fringe")],
    reasonOptions: [o("r1", "More 3-bet pressure ухудшает EV fringe и делает defence architecture труднее", "More 3-bet pressure hurts fringe EV and makes the defense architecture harder"), o("r2", "Aggressive blinds чаще fold preflop", "Aggressive blinds fold preflop more often", "PLAYER_TYPE_BACKWARDS"), o("r3", "Only stack depth matters", "Only stack depth matters", "SINGLE_FACTOR")],
    correctActionId: "c", correctReasonId: "r1", targetSeconds: 20, explanationRu: "FTGU-E02 требует сужать fringe при tight/aggressive pressure behind.", explanationEn: "FTGU-E02 requires contracting the fringe under tight/aggressive pressure behind.", changedVariables: ["players_behind", "three_bet_pressure"],
  },
  {
    id: "PM-PF-01-107", skillId: "PF-01", kind: "boundary", sourceRefs: ["FTGU-E02"], assumptions: ["opening range widened", "facing competent 3-bets"],
    cueRu: "Range расширили настолько, что для защиты примерно половины приходится продолжать очевидно плохие hands.", cueEn: "The range has been widened so far that defending roughly half requires clearly bad continues.", questionRu: "Что это говорит об opening fringe?", questionEn: "What does that imply about the opening fringe?",
    actionOptions: [o("a", "Range, вероятно, переоткрыт", "The range is likely over-opened"), o("b", "Нужно просто call все 3-bets", "Just call all 3-bets", "DEFEND_ANYWAY"), o("c", "Это доказывает, что 3-bets слишком маленькие", "It proves the 3-bets are too small", "UNSUPPORTED_CAUSE")],
    reasonOptions: [o("r1", "Default open должен оставаться defensible без forced losing continues", "A default opening range should remain defensible without forced losing continues"), o("r2", "Opening range не связан с response tree", "The opening range is unrelated to the response tree", "TREE_DISCONNECTED"), o("r3", "Любой BTN range обязан быть очень широким", "Every BTN range must be very wide", "POSITION_LAW")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30, explanationRu: "Это один из явных boundary checks FTGU-E02: widening заканчивается там, где downstream defence требует очевидно плохих continues.", explanationEn: "This is an explicit FTGU-E02 boundary check: widening stops where downstream defense requires clearly losing continues.",
  },

  // PF-02 — limp / overlimp / isolation. Source: FTGU-E03.
  {
    id: "PM-PF-02-101", skillId: "PF-02", kind: "recognition", sourceRefs: ["FTGU-E03"], assumptions: ["limped pot"], cueRu: "Нужно решить isolate / overlimp / fold.", cueEn: "Need to choose isolate / overlimp / fold.", questionRu: "Какие три фактора FTGU ставит в основу?", questionEn: "Which three factors does FTGU put at the center?",
    actionOptions: [o("a", "Frequent strength, fold equity, position", "Frequent strength, fold equity, position"), o("b", "Только absolute hand rank", "Only absolute hand rank", "HAND_RANK_ONLY"), o("c", "Только число limpers", "Only the number of limpers", "LIMPER_COUNT_ONLY")],
    reasonOptions: [o("r1", "Эти факторы определяют, как hand зарабатывает EV в dynamic limp tree", "These factors determine how the hand earns EV in a dynamic limp tree"), o("r2", "Limped pots имеют один универсальный chart", "Limped pots have one universal chart", "UNIVERSAL_LIMP_CHART"), o("r3", "Position не важна при limpers", "Position does not matter with limpers", "POSITION_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 20, explanationRu: "FTGU-E03 организует решение именно вокруг frequent strength, fold equity и position.", explanationEn: "FTGU-E03 organizes the decision around frequent strength, fold equity and position.",
  },
  {
    id: "PM-PF-02-102", skillId: "PF-02", kind: "recognition", sourceRefs: ["FTGU-E03"], assumptions: ["suited connector", "rare nut runouts", "weak frequent strength"], cueRu: "Рука иногда делает очень сильные nuts, но редко флопает robust made hand/strong draw.", cueEn: "The hand occasionally makes very strong nuts but rarely flops a robust made hand or strong draw.", questionRu: "Что нельзя путать?", questionEn: "What should not be confused?",
    actionOptions: [o("a", "Nut potential и frequent strength", "Nut potential and frequent strength"), o("b", "Position и stack size", "Position and stack size", "WRONG_PAIR"), o("c", "Fold equity и rake", "Fold equity and rake", "WRONG_PAIR")],
    reasonOptions: [o("r1", "Редкий monster не означает, что hand часто выдерживает action", "A rare monster does not mean the hand often withstands action"), o("r2", "Nut potential автоматически делает iso прибыльным", "Nut potential automatically makes isolation profitable", "NUT_AUTOPILOT"), o("r3", "Frequent strength измеряет только showdown equity", "Frequent strength measures only showdown equity", "FREQUENT_STRENGTH_MISREAD")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 20, explanationRu: "FTGU-E03 специально отделяет frequent strength от редкого spectacular upside.", explanationEn: "FTGU-E03 explicitly separates frequent strength from rare spectacular upside.",
  },
  {
    id: "PM-PF-02-103", skillId: "PF-02", kind: "decision", sourceRefs: ["FTGU-E03"], assumptions: ["one limper", "Hero IP", "limper folds often", "players behind passive"], cueRu: "Один limper, Hero IP, limper часто fold, позади мало squeeze pressure.", cueEn: "One limper, Hero IP, limper folds often, little squeeze pressure behind.", questionRu: "Какая ветка получает больше оснований?", questionEn: "Which branch gains more support?",
    actionOptions: [o("a", "Isolation raise", "Isolation raise"), o("b", "Automatic overlimp", "Automatic overlimp", "OVERLIMP_AUTOPILOT"), o("c", "Fold любой не-premium", "Fold every non-premium hand", "OVERFOLD")],
    reasonOptions: [o("r1", "Fold equity + position могут компенсировать неидеальную frequent strength", "Fold equity plus position can compensate for imperfect frequent strength"), o("r2", "Limp всегда означает trap", "A limp always means a trap", "LIMP_TRAP_ALWAYS"), o("r3", "Isolation нужен только с top 5%", "Isolation is only for the top 5%", "UNSUPPORTED_THRESHOLD")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25, explanationRu: "FTGU-E03 допускает iso там, где fold equity и position сильны; это table-specific branch, не universal chart.", explanationEn: "FTGU-E03 supports isolation where fold equity and position are strong; it is a table-specific branch, not a universal chart.",
  },
  {
    id: "PM-PF-02-104", skillId: "PF-02", kind: "decision", sourceRefs: ["FTGU-E03"], assumptions: ["multiple limpers", "fold equity poor", "implied-odds hand", "likely multiway"], cueRu: "Несколько sticky limpers, fold equity низкая, implied-odds hand.", cueEn: "Several sticky limpers, low fold equity, implied-odds hand.", questionRu: "Какая branch часто становится привлекательнее?", questionEn: "Which branch often becomes more attractive?",
    actionOptions: [o("a", "Large iso regardless", "Large isolation regardless", "ISO_AUTOPILOT"), o("b", "Overlimp с малой initial investment", "Overlimp with a small initial investment"), o("c", "Jam", "Jam", "SIZE_OVERREACTION")],
    reasonOptions: [o("r1", "Малая инвестиция лучше сохраняет implied odds, когда folds почти нет", "A small investment better preserves implied odds when folds are scarce"), o("r2", "Multiway гарантирует realization", "Multiway guarantees realization", "MULTIWAY_GUARANTEE"), o("r3", "Overlimp всегда лучше isolation", "Overlimp is always better than isolation", "OVERLIMP_LAW")],
    correctActionId: "b", correctReasonId: "r1", targetSeconds: 25, explanationRu: "FTGU-E03 прямо выделяет overlimp small pairs/suited connected hands при poor fold equity и частом multiway.", explanationEn: "FTGU-E03 explicitly highlights overlimping small pairs/suited connected hands when fold equity is poor and multiway play is frequent.",
  },
  {
    id: "PM-PF-02-105", skillId: "PF-02", kind: "changed", sourceRefs: ["FTGU-E03"], assumptions: ["same hand", "same limper", "Hero moves IP -> OOP"], cueRu: "Hand и limper те же, но Hero теперь OOP вместо IP.", cueEn: "Same hand and limper, but Hero moves from IP to OOP.", questionRu: "Как меняется attractiveness marginal iso?", questionEn: "How does a marginal isolation raise change?",
    actionOptions: [o("a", "Становится менее привлекательным", "It becomes less attractive"), o("b", "Становится более привлекательным всегда", "It always becomes more attractive", "POSITION_BACKWARDS"), o("c", "Не меняется", "No change", "POSITION_IGNORED")],
    reasonOptions: [o("r1", "Position усиливает realisation и extraction; OOP требует сильнее frequent strength/other compensation", "Position improves realization and extraction; OOP needs stronger frequent strength or other compensation"), o("r2", "OOP автоматически создаёт больше fold equity", "OOP automatically creates more fold equity", "POSITION_BACKWARDS"), o("r3", "Position не входит в iso framework", "Position is not part of the isolation framework", "POSITION_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25, explanationRu: "Position — один из трёх центральных факторов FTGU-E03.", explanationEn: "Position is one of FTGU-E03's three central factors.", changedVariables: ["position"],
  },
  {
    id: "PM-PF-02-106", skillId: "PF-02", kind: "changed", sourceRefs: ["FTGU-E03"], assumptions: ["same iso candidate", "players behind passive -> aggressive squeezers"], cueRu: "Та же iso candidate, но игроки позади начинают часто 3-bet/squeeze.", cueEn: "Same isolation candidate, but players behind now 3-bet/squeeze often.", questionRu: "Как реагировать на sizing/branch?", questionEn: "How should sizing/branch respond?",
    actionOptions: [o("a", "Чаще уменьшать oversized iso / пересмотреть raise", "More often reduce an oversized iso / reconsider the raise"), o("b", "Увеличивать size без ограничений", "Increase size without limits", "SQUEEZE_IGNORED"), o("c", "Ничего не менять", "Change nothing", "PLAYERS_BEHIND_IGNORED")],
    reasonOptions: [o("r1", "Oversized raise становится дороже защищать против frequent 3-bets", "An oversized raise becomes more expensive to defend versus frequent 3-bets"), o("r2", "Aggressive players behind гарантируют folds limper", "Aggressive players behind guarantee limper folds", "UNRELATED_CAUSE"), o("r3", "Sizing не связано с squeeze risk", "Sizing is unrelated to squeeze risk", "SIZING_TREE_DISCONNECTED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30, explanationRu: "FTGU-E03 прямо уменьшает isolation sizing при частых aggressive 3-bets behind.", explanationEn: "FTGU-E03 explicitly reduces isolation sizing when aggressive players behind can 3-bet frequently.", changedVariables: ["players_behind", "squeeze_frequency"],
  },
  {
    id: "PM-PF-02-107", skillId: "PF-02", kind: "boundary", sourceRefs: ["FTGU-E03"], assumptions: ["limp-reraise tendency high", "deep enough stacks"], cueRu: "Limper часто limp-reraise, а позади ещё есть action.", cueEn: "The limper frequently limp-reraises and action remains behind.", questionRu: "Что происходит с generic iso heuristic?", questionEn: "What happens to a generic isolation heuristic?",
    actionOptions: [o("a", "Нужно пересчитать whole branch; autopilot iso ломается", "Recalculate the whole branch; autopilot isolation breaks"), o("b", "Iso становится автоматически лучше", "Isolation becomes automatically better", "AGGRESSION_AUTOPILOT"), o("c", "Limp-reraise tendency не важна", "Limp-reraise tendency is irrelevant", "TENDENCY_IGNORED")],
    reasonOptions: [o("r1", "Limped-pot strategy зависит от limp-fold/call/reraise и players behind", "Limped-pot strategy depends on limp-fold/call/reraise and players behind"), o("r2", "Любой limp слабый", "Every limp is weak", "LIMP_ALWAYS_WEAK"), o("r3", "Only hand strength matters", "Only hand strength matters", "HAND_ONLY")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30, explanationRu: "FTGU-E03 называет limp-reraise tendency одним из explicit table variables; универсальный iso chart здесь не заявлен.", explanationEn: "FTGU-E03 names limp-reraise tendency as an explicit table variable; no universal isolation chart is claimed.",
  },

  // PF-03 — cold-calling IP. Source: FTGU-E04.
  {
    id: "PM-PF-03-101", skillId: "PF-03", kind: "recognition", sourceRefs: ["FTGU-E04"], assumptions: ["IP cold-call candidate"], cueRu: "Hero рассматривает cold-call IP.", cueEn: "Hero considers an IP cold call.", questionRu: "Какие две базовые причины source даёт для call?", questionEn: "Which two primary reasons does the source give for calling?",
    actionOptions: [o("a", "Value или implied odds", "Value or implied odds"), o("b", "Suitedness или boredom", "Suitedness or boredom", "PLAYABLE_LOOKS"), o("c", "Только pot odds", "Pot odds only", "PRICE_ONLY")],
    reasonOptions: [o("r1", "Cold-call должен иметь ясный EV mechanism, а не просто выглядеть playable", "A cold call needs a clear EV mechanism, not merely look playable"), o("r2", "IP hand всегда реализует 100% equity", "An IP hand always realizes 100% equity", "FULL_REALISATION"), o("r3", "Any pair automatically calls", "Any pair automatically calls", "PAIR_AUTOPILOT")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 20, explanationRu: "FTGU-E04 формулирует две главные причины cold-call IP: value и implied odds.", explanationEn: "FTGU-E04 gives two main reasons to cold-call IP: value and implied odds.",
  },
  {
    id: "PM-PF-03-102", skillId: "PF-03", kind: "recognition", sourceRefs: ["FTGU-E04"], assumptions: ["caller declines to 3-bet premiums", "players behind remain"], cueRu: "Cold-call убирает большинство premiums из perceived range.", cueEn: "The cold call removes most premiums from the perceived range.", questionRu: "Как называется structural consequence?", questionEn: "What is the structural consequence?",
    actionOptions: [o("a", "Uncapped", "Uncapped", "CAP_BACKWARDS"), o("b", "Capped и уязвимая к squeeze", "Capped and vulnerable to squeezes"), o("c", "Polar by definition", "Polar by definition", "RANGE_SHAPE_MISLABEL")],
    reasonOptions: [o("r1", "Declining to 3-bet premiums caps top-end while uncapped players remain behind", "Declining to 3-bet premiums caps the top end while uncapped players remain behind"), o("r2", "Calling добавляет premiums в range", "Calling adds premiums to the range", "CAP_BACKWARDS"), o("r3", "Players behind cannot attack a caller", "Players behind cannot attack a caller", "NO_SQUEEZE")],
    correctActionId: "b", correctReasonId: "r1", targetSeconds: 20, explanationRu: "FTGU-E04 прямо связывает cold-call с cappedness и squeeze vulnerability.", explanationEn: "FTGU-E04 explicitly links cold-calling with cappedness and squeeze vulnerability.",
  },
  {
    id: "PM-PF-03-103", skillId: "PF-03", kind: "decision", sourceRefs: ["FTGU-E04"], assumptions: ["hand performs well versus opener", "3-bet would fold weaker hands", "little squeeze risk"], cueRu: "Hand впереди достаточной части opening range, но 3-bet выбивает много слабее.", cueEn: "The hand performs well versus enough of the opening range, but a 3-bet folds out many worse hands.", questionRu: "Какая причина может поддерживать call?", questionEn: "Which reason can support calling?",
    actionOptions: [o("a", "Value via keeping weaker hands in", "Value via keeping weaker hands in"), o("b", "Call потому что 3-bet всегда плох", "Call because 3-betting is always bad", "CALL_LAW"), o("c", "Call только ради set mining", "Call only to set-mine", "WRONG_MECHANISM")],
    reasonOptions: [o("r1", "Call и 3-bet могут зарабатывать EV из разных branches", "Call and 3-bet can earn EV from different branches"), o("r2", "Calling never faces action behind", "Calling never faces action behind", "PLAYERS_BEHIND_IGNORED"), o("r3", "Value call означает top pair guaranteed", "A value call means top pair is guaranteed", "VALUE_MISREAD")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25, explanationRu: "FTGU-E04 допускает обе линии, если они извлекают EV из разных веток; call может сохранить weaker range.", explanationEn: "FTGU-E04 allows both lines when they earn EV from different branches; calling can keep weaker hands in.",
  },
  {
    id: "PM-PF-03-104", skillId: "PF-03", kind: "decision", sourceRefs: ["FTGU-E04"], assumptions: ["small pair", "deep enough stack", "low squeeze risk", "future payout plausible"], cueRu: "Small pair IP, initial investment мала, future payout возможен.", cueEn: "Small pair IP, small initial investment, plausible future payout.", questionRu: "Какой mechanism оправдывает часть calls?", questionEn: "Which mechanism justifies some calls?",
    actionOptions: [o("a", "Implied odds", "Implied odds"), o("b", "Raw equity >50%", "Raw equity above 50%", "WIN_RATE_50_SHORTCUT"), o("c", "Any pocket pair always calls", "Any pocket pair always calls", "PAIR_AUTOPILOT")],
    reasonOptions: [o("r1", "Small pair может реализовать upside дискретно через set при малой цене входа", "A small pair can realize upside discretely by flopping a set at a small entry cost"), o("r2", "Set guaranteed often enough", "A set is guaranteed often enough", "SET_GUARANTEE"), o("r3", "Depth никогда не влияет implied odds", "Depth never affects implied odds", "DEPTH_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25, explanationRu: "FTGU-E04 использует small pairs как пример discrete implied-odds realization, но не превращает это в unconditional call.", explanationEn: "FTGU-E04 uses small pairs as an example of discrete implied-odds realization without making them unconditional calls.",
  },
  {
    id: "PM-PF-03-105", skillId: "PF-03", kind: "changed", sourceRefs: ["FTGU-E04"], assumptions: ["same suited connector", "stack becomes shallower"], cueRu: "Та же suited connector cold-call candidate, но effective stack заметно уменьшается.", cueEn: "Same suited-connector cold-call candidate, but effective stack becomes materially shallower.", questionRu: "Как двигается implied-odds case?", questionEn: "How does the implied-odds case move?",
    actionOptions: [o("a", "Ослабевает", "It weakens"), o("b", "Усиливается", "It strengthens", "DEPTH_BACKWARDS"), o("c", "Не меняется", "No change", "DEPTH_IGNORED")],
    reasonOptions: [o("r1", "Меньше future stack ограничивает payoff и multi-street realization", "Less future stack limits payoff and multi-street realization"), o("r2", "Shallow stacks всегда улучшают suited connectors", "Shallow stacks always improve suited connectors", "DEPTH_BACKWARDS"), o("r3", "Implied odds зависят только от current pot", "Implied odds depend only on the current pot", "FUTURE_TREE_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25, explanationRu: "FTGU-E04 подчёркивает, что suited connectors часто реализуют upside постепенно и поэтому особенно зависят от depth/position/pressure.", explanationEn: "FTGU-E04 emphasizes that suited connectors often realize upside gradually and are especially sensitive to depth, position and pressure.", changedVariables: ["effective_stack"],
  },
  {
    id: "PM-PF-03-106", skillId: "PF-03", kind: "changed", sourceRefs: ["FTGU-E04"], assumptions: ["same hand", "squeeze risk low -> high"], cueRu: "Call был приемлемым heads-up, но позади появились frequent squeezers.", cueEn: "The call was acceptable heads-up, but frequent squeezers now remain behind.", questionRu: "Как меняется EV call?", questionEn: "How does call EV change?",
    actionOptions: [o("a", "Обычно падает", "It usually falls"), o("b", "Обычно растёт", "It usually rises", "SQUEEZE_BACKWARDS"), o("c", "Не меняется", "No change", "PLAYERS_BEHIND_IGNORED")],
    reasonOptions: [o("r1", "Call может не дожить до flop или уйти multiway, ухудшая realisation", "The call may not survive to the flop or may go multiway, hurting realization"), o("r2", "Squeeze делает caller uncapped", "A squeeze makes the caller uncapped", "CAP_BACKWARDS"), o("r3", "IP отменяет squeeze risk", "Being IP eliminates squeeze risk", "POSITION_MAGIC")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25, explanationRu: "Players behind — explicit variable FTGU-E04; nominally good call может стать inferior из-за squeeze pressure.", explanationEn: "Players behind are an explicit FTGU-E04 variable; a nominally good call can become inferior under squeeze pressure.", changedVariables: ["squeeze_risk"],
  },
  {
    id: "PM-PF-03-107", skillId: "PF-03", kind: "boundary", sourceRefs: ["FTGU-E04"], assumptions: ["four-way pot likely", "one-pair hand family"], cueRu: "Cold-call почти наверняка ведёт в 4-way pot с one-pair-heavy hand family.", cueEn: "The cold call is very likely to create a four-way pot with a one-pair-heavy hand family.", questionRu: "Какой source boundary важен?", questionEn: "Which source boundary matters?",
    actionOptions: [o("a", "One-pair value падает с ростом числа игроков", "One-pair value declines as player count rises"), o("b", "More players всегда улучшают pair EV", "More players always improve pair EV", "MULTIWAY_BACKWARDS"), o("c", "Player count не влияет", "Player count does not matter", "MULTIWAY_IGNORED")],
    reasonOptions: [o("r1", "Multiway participation снижает relative strength/realisation one-pair holdings", "Multiway participation reduces the relative strength/realization of one-pair holdings"), o("r2", "Каждый дополнительный игрок добавляет dead money без downside", "Each extra player adds dead money with no downside", "DEAD_MONEY_ONLY"), o("r3", "Position guarantees realization", "Position guarantees realization", "POSITION_GUARANTEE")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30, explanationRu: "FTGU-E04 прямо отмечает, что one-pair value ухудшается при росте числа игроков.", explanationEn: "FTGU-E04 explicitly notes that one-pair value declines as more players enter the pot.",
  },

  // PF-04 — BB calling. Source: FTGU-E05.
  {
    id: "PM-PF-04-101", skillId: "PF-04", kind: "recognition", sourceRefs: ["FTGU-E05"], assumptions: ["Hero BB", "action closes"], cueRu: "Hero BB и закрывает action.", cueEn: "Hero is in the BB and closes the action.", questionRu: "Какой дополнительный preflop reason for call появляется относительно обычного cold-call?", questionEn: "Which additional preflop reason for calling appears versus a normal cold call?",
    actionOptions: [o("a", "Pot odds от уже вложенного blind", "Pot odds from the blind already invested"), o("b", "Automatic position", "Automatic position", "POSITION_FALSE"), o("c", "Guaranteed showdown", "Guaranteed showdown", "SHOWDOWN_GUARANTEE")],
    reasonOptions: [o("r1", "Fold уже реализует потерю blind, поэтому marginal call сравнивается с этим baseline", "Folding already realizes the blind loss, so a marginal call is compared with that baseline"), o("r2", "Blind возвращается при fold", "The blind is returned when folding", "SUNK_COST_FALSE"), o("r3", "BB всегда получает 50% equity", "BB always gets 50% equity", "EQUITY_MAGIC")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 20, explanationRu: "FTGU-E05 добавляет pot odds как третью причину call из BB alongside value/implied odds.", explanationEn: "FTGU-E05 adds pot odds as a third reason to call from the BB alongside value and implied odds.",
  },
  {
    id: "PM-PF-04-102", skillId: "PF-04", kind: "recognition", sourceRefs: ["FTGU-E05"], assumptions: ["small open", "wide late range", "BB closes action"], cueRu: "Small open, wide late-position range, BB closes action.", cueEn: "Small open, wide late-position range, BB closes the action.", questionRu: "Как меняется required realisable equity для marginal defend?", questionEn: "How does required realizable equity change for a marginal defend?",
    actionOptions: [o("a", "Снижается", "It decreases"), o("b", "Растёт", "It increases", "PRICE_BACKWARDS"), o("c", "Всегда 50%", "Always 50%", "WIN_RATE_50_SHORTCUT")],
    reasonOptions: [o("r1", "Price, wide origin range и closing action улучшают branch", "Price, wide origin range and closing action improve the branch"), o("r2", "BB должен быть favourite", "BB must be the favorite", "FAVOURITE_REQUIREMENT"), o("r3", "Open size не влияет", "Open size does not matter", "SIZE_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 20, explanationRu: "FTGU-E05 прямо перечисляет small open, wide range и closing action как факторы, улучшающие BB defence.", explanationEn: "FTGU-E05 explicitly lists small opens, wide ranges and closing the action as factors improving BB defense.",
  },
  {
    id: "PM-PF-04-103", skillId: "PF-04", kind: "decision", sourceRefs: ["FTGU-E05"], assumptions: ["BB marginal hand", "BTN wide open", "small sizing", "competent Hero postflop"], cueRu: "BB marginal hand против small BTN open; Hero способен нормально реализовать equity.", cueEn: "BB marginal hand versus a small BTN open; Hero can realize equity competently.", questionRu: "Какой default чаще заслуживает consideration?", questionEn: "Which default deserves more consideration?",
    actionOptions: [o("a", "Defend/call candidate", "Defend/call candidate"), o("b", "Fold потому что hand позади range", "Fold because the hand is behind the range", "BEHIND_EQUALS_FOLD"), o("c", "3-bet every marginal hand", "3-bet every marginal hand", "AGGRESSION_AUTOPILOT")],
    reasonOptions: [o("r1", "Call может быть выше EV fold даже если hand проигрывает большинство pots", "A call can beat folding in EV even if the hand loses most pots"), o("r2", "Call должен выигрывать >50%", "A call must win more than 50%", "WIN_RATE_50_SHORTCUT"), o("r3", "BB discount означает any two", "The BB discount means any two cards", "ANY_TWO")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25, explanationRu: "FTGU-E05 отвергает binary win/loss intuition: dead money и price могут сделать losing-most-pots call предпочтительнее fold.", explanationEn: "FTGU-E05 rejects binary win/loss intuition: dead money and price can make a call that loses most pots preferable to folding.",
  },
  {
    id: "PM-PF-04-104", skillId: "PF-04", kind: "decision", sourceRefs: ["FTGU-E05"], assumptions: ["BB dominated offsuit high card", "EP concentrated range"], cueRu: "BB держит dominated offsuit high-card candidate против concentrated EP range.", cueEn: "BB holds a dominated offsuit high-card candidate versus a concentrated EP range.", questionRu: "Какой risk должен сильнее толкать к fold?", questionEn: "Which risk should push more strongly toward folding?",
    actionOptions: [o("a", "Top-pair domination / strong-overpair density", "Top-pair domination / strong-overpair density"), o("b", "Too much position", "Too much position", "POSITION_FALSE"), o("c", "Closing action", "Closing the action", "BENEFIT_AS_COST")],
    reasonOptions: [o("r1", "Weak top-pair hands materially degrade versus concentrated early ranges", "Weak top-pair hands materially degrade versus concentrated early ranges"), o("r2", "EP opens are wider than BTN", "EP opens are wider than BTN", "ORIGIN_RANGE_BACKWARDS"), o("r3", "Domination не влияет postflop EV", "Domination does not affect postflop EV", "DOMINATION_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25, explanationRu: "FTGU-E05 отдельно подчёркивает domination и overpair density против EP.", explanationEn: "FTGU-E05 specifically emphasizes domination and overpair density versus EP.",
  },
  {
    id: "PM-PF-04-105", skillId: "PF-04", kind: "changed", sourceRefs: ["FTGU-E05"], assumptions: ["same BB hand", "open size increases"], cueRu: "Та же BB hand и opener, но open size становится больше.", cueEn: "Same BB hand and opener, but the open size becomes larger.", questionRu: "Как меняется marginal call?", questionEn: "How does the marginal call change?",
    actionOptions: [o("a", "Слабее", "Weaker"), o("b", "Сильнее", "Stronger", "PRICE_BACKWARDS"), o("c", "Не меняется", "No change", "SIZE_IGNORED")],
    reasonOptions: [o("r1", "Worse price повышает required realizable equity", "A worse price raises required realizable equity"), o("r2", "Больший open даёт больше dead money без cost", "A larger open gives more dead money with no cost", "PRICE_MISREAD"), o("r3", "BB price fixed regardless sizing", "BB price is fixed regardless of sizing", "SIZE_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 20, explanationRu: "Open size — explicit determinant BB defence в FTGU-E05.", explanationEn: "Open size is an explicit determinant of BB defense in FTGU-E05.", changedVariables: ["open_size", "price"],
  },
  {
    id: "PM-PF-04-106", skillId: "PF-04", kind: "changed", sourceRefs: ["FTGU-E05"], assumptions: ["same price/range", "Hero execution competent -> poor"], cueRu: "Price и opener те же, но Hero postflop execution заметно хуже.", cueEn: "Price and opener are unchanged, but Hero's postflop execution is materially worse.", questionRu: "Что происходит с marginal defend?", questionEn: "What happens to the marginal defend?",
    actionOptions: [o("a", "Становится менее привлекательным", "It becomes less attractive"), o("b", "Становится более привлекательным", "It becomes more attractive", "EXECUTION_BACKWARDS"), o("c", "Execution не влияет preflop", "Execution does not affect preflop", "REALISATION_IGNORED")],
    reasonOptions: [o("r1", "Poor execution снижает equity realisation и может перевести marginal call в минус", "Poor execution lowers equity realization and can turn a marginal call negative"), o("r2", "Raw equity гарантированно реализуется", "Raw equity is guaranteed to realize", "RAW_EQUITY_ONLY"), o("r3", "Only rake matters", "Only rake matters", "SINGLE_FACTOR")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25, explanationRu: "FTGU-E05 прямо говорит, что player skill/execution может перевести marginal calls через zero-EV boundary.", explanationEn: "FTGU-E05 explicitly says player skill/execution can move marginal calls across the zero-EV boundary.", changedVariables: ["postflop_execution"],
  },
  {
    id: "PM-PF-04-107", skillId: "PF-04", kind: "boundary", sourceRefs: ["FTGU-E05"], assumptions: ["good price", "very poor realization", "high rake"], cueRu: "BB получает хорошую цену, но rake высокий и hand реализует equity очень плохо.", cueEn: "BB gets a good price, but rake is high and the hand realizes equity very poorly.", questionRu: "Достаточно ли одной цены для call?", questionEn: "Is price alone sufficient for the call?",
    actionOptions: [o("a", "Нет", "No"), o("b", "Да, всегда", "Yes, always", "PRICE_ONLY"), o("c", "Да, если hand suited", "Yes, if the hand is suited", "SUITED_AUTOPILOT")],
    reasonOptions: [o("r1", "Rake и realisation могут уничтожить thin price-based defend", "Rake and realization can erase a thin price-based defend"), o("r2", "Pot odds автоматически гарантируют positive EV", "Pot odds automatically guarantee positive EV", "PRICE_ONLY"), o("r3", "Rake не касается BB", "Rake does not affect the BB", "RAKE_FALSE")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30, explanationRu: "Это явная boundary FTGU-E05: favourable price — необходимая часть анализа, но marginal calls могут стать unprofitable из-за rake/execution.", explanationEn: "This is an explicit FTGU-E05 boundary: favorable price matters, but marginal calls can become unprofitable because of rake/execution.",
  },

  // PF-05 — SB versus opens. Source: FTGU-E06.
  {
    id: "PM-PF-05-101", skillId: "PF-05", kind: "recognition", sourceRefs: ["FTGU-E06"], assumptions: ["SB faces open", "BB still acts"], cueRu: "SB faces open, BB ещё действует.", cueEn: "SB faces an open and the BB still acts.", questionRu: "Почему passive flat структурно хуже BB call?", questionEn: "Why is a passive flat structurally worse than a BB call?",
    actionOptions: [o("a", "Poor price + OOP + action not closed + squeeze risk", "Poor price + OOP + action not closed + squeeze risk"), o("b", "SB всегда имеет меньше equity", "SB always has less equity", "SEAT_MAGIC"), o("c", "SB cannot 3-bet", "SB cannot 3-bet", "ACTION_FALSE")],
    reasonOptions: [o("r1", "Эти costs могут deny всю equity ещё до flop и затем ухудшают realisation", "These costs can deny all equity before the flop and then hurt realization"), o("r2", "BB never squeezes", "The BB never squeezes", "NO_SQUEEZE"), o("r3", "Position matters only in multiway pots", "Position matters only in multiway pots", "POSITION_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 20, explanationRu: "FTGU-E06 прямо перечисляет poor price, OOP, not closing action и squeeze risk.", explanationEn: "FTGU-E06 explicitly lists poor price, OOP play, not closing the action and squeeze risk.",
  },
  {
    id: "PM-PF-05-102", skillId: "PF-05", kind: "recognition", sourceRefs: ["FTGU-E06"], assumptions: ["SB considers 3-bet"], cueRu: "SB рассматривает 3-bet вместо flat.", cueEn: "SB considers a 3-bet instead of a flat.", questionRu: "Какой набор benefits соответствует source?", questionEn: "Which set of benefits matches the source?",
    actionOptions: [o("a", "Uncap, isolate, deny equity, avoid squeeze, lower SPR", "Uncap, isolate, deny equity, avoid squeeze, lower SPR"), o("b", "Guarantee folds and position", "Guarantee folds and position", "GUARANTEE_FALSE"), o("c", "Remove rake completely", "Remove rake completely", "RAKE_ABSOLUTE")],
    reasonOptions: [o("r1", "3-bet решает несколько structural disadvantages, но не гарантирует outcome", "A 3-bet addresses several structural disadvantages without guaranteeing an outcome"), o("r2", "3-bet good only because aggression is always better", "A 3-bet is good only because aggression is always better", "AGGRESSION_AUTOPILOT"), o("r3", "3-bet makes Hero IP", "A 3-bet makes Hero IP", "POSITION_FALSE")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25, explanationRu: "FTGU-E06 перечисляет эти structural benefits 3-bet и отдельно предупреждает не превращать 3-bet-or-fold в unconditional law.", explanationEn: "FTGU-E06 lists these structural benefits of 3-betting and separately warns against treating 3-bet-or-fold as an unconditional law.",
  },
  {
    id: "PM-PF-05-103", skillId: "PF-05", kind: "decision", sourceRefs: ["FTGU-E06"], assumptions: ["SB dominated offsuit broadway", "open continues versus 3-bet with stronger broadways"], cueRu: "SB имеет dominated offsuit broadway; после 3-bet opener продолжит concentrated stronger broadways.", cueEn: "SB has a dominated offsuit broadway; after a 3-bet the opener continues with concentrated stronger broadways.", questionRu: "Нужно ли 3-bet только потому, что flat плох?", questionEn: "Should Hero 3-bet merely because flatting is poor?",
    actionOptions: [o("a", "Да, всегда", "Yes, always", "THREE_BET_OR_FOLD_LITERAL"), o("b", "Нет — проверить called 3-bet branch", "No — evaluate the called 3-bet branch"), o("c", "Да, если offsuit", "Yes, if offsuit", "OFFSUIT_RULE")],
    reasonOptions: [o("r1", "Unattractive flat не делает 3-bet автоматически profitable", "An unattractive flat does not automatically make the 3-bet profitable"), o("r2", "Any 3-bet wins preflop", "Any 3-bet wins preflop", "FOLD_GUARANTEE"), o("r3", "Dominated broadways improve against filtered ranges", "Dominated broadways improve against filtered ranges", "FILTERING_BACKWARDS")],
    correctActionId: "b", correctReasonId: "r1", targetSeconds: 30, explanationRu: "FTGU-E06 прямо говорит: не 3-bet hand только потому, что flat unattractive; called branch должен оставаться жизнеспособным.", explanationEn: "FTGU-E06 explicitly says not to 3-bet a hand merely because flatting is unattractive; the called branch must remain viable.",
  },
  {
    id: "PM-PF-05-104", skillId: "PF-05", kind: "decision", sourceRefs: ["FTGU-E06"], assumptions: ["SB suited wheel ace", "fold equity meaningful", "called branch playable"], cueRu: "SB suited wheel ace: blocker даёт fold equity, а suitedness сохраняет playability when called.", cueEn: "SB suited wheel ace: the blocker adds fold equity while suitedness preserves playability when called.", questionRu: "Какая ветка получает structural support?", questionEn: "Which branch gains structural support?",
    actionOptions: [o("a", "3-bet candidate", "3-bet candidate"), o("b", "Mandatory fold", "Mandatory fold", "BLOCKER_IGNORED"), o("c", "Mandatory flat", "Mandatory flat", "FLAT_AUTOPILOT")],
    reasonOptions: [o("r1", "Blocker-driven fold equity сочетается с postflop playability", "Blocker-driven fold equity combines with postflop playability"), o("r2", "Ace blocker guarantees fold", "An ace blocker guarantees a fold", "BLOCKER_GUARANTEE"), o("r3", "Suited ace cannot be dominated", "A suited ace cannot be dominated", "DOMINATION_FALSE")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25, explanationRu: "FTGU-E06 использует suited wheel aces как hand class, которая получает fold equity через removal и остаётся playable when called.", explanationEn: "FTGU-E06 uses suited wheel aces as a hand class that gains fold equity through removal while remaining playable when called.",
  },
  {
    id: "PM-PF-05-105", skillId: "PF-05", kind: "changed", sourceRefs: ["FTGU-E06"], assumptions: ["same SB flat candidate", "BB changes competent aggressive -> weak passive"], cueRu: "Та же SB hand, но BB позади из aggressive становится weak/passive.", cueEn: "Same SB hand, but the BB behind changes from aggressive to weak/passive.", questionRu: "Как меняется viability flat?", questionEn: "How does flat viability change?",
    actionOptions: [o("a", "Может улучшиться", "It can improve"), o("b", "Обязательно ухудшается", "It must worsen", "PLAYER_TYPE_BACKWARDS"), o("c", "Не меняется", "No change", "BB_BEHIND_IGNORED")],
    reasonOptions: [o("r1", "Conditional flats могут выживать, когда BB редко squeezes", "Conditional flats can survive when the BB rarely squeezes"), o("r2", "Weak BB squeezes more often", "A weak BB squeezes more often", "PLAYER_TYPE_BACKWARDS"), o("r3", "BB behind никогда не влияет", "The BB behind never matters", "BB_BEHIND_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25, explanationRu: "FTGU-E06 прямо оставляет conditional flats против weak/passive BB; title 3-bet-or-fold — simplification, не literal prohibition.", explanationEn: "FTGU-E06 explicitly leaves room for conditional flats versus a weak/passive BB; the 3-bet-or-fold title is a simplification, not a literal prohibition.", changedVariables: ["bb_tendency", "squeeze_risk"],
  },
  {
    id: "PM-PF-05-106", skillId: "PF-05", kind: "changed", sourceRefs: ["FTGU-E06"], assumptions: ["same SB 3-bet hand", "opener continues much tighter"], cueRu: "Та же SB 3-bet candidate, но opener после 3-bet продолжает намного более concentrated range.", cueEn: "Same SB 3-bet candidate, but the opener continues with a much more concentrated range.", questionRu: "Что становится важнее?", questionEn: "What becomes more important?",
    actionOptions: [o("a", "Quality of called branch / domination", "Quality of the called branch / domination"), o("b", "Only blocker count", "Only blocker count", "BLOCKER_ONLY"), o("c", "Nothing; fold equity is all that matters", "Nothing; fold equity is all that matters", "FOLD_EQUITY_ONLY")],
    reasonOptions: [o("r1", "Range filtering может сделать dominated hands плохими даже при attractive preflop aggression", "Range filtering can make dominated hands poor even when preflop aggression looks attractive"), o("r2", "Tighter continue range makes every bluff better postflop", "A tighter continue range makes every bluff better postflop", "FILTERING_BACKWARDS"), o("r3", "Called branch is irrelevant", "The called branch is irrelevant", "CALL_BRANCH_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30, explanationRu: "FTGU-E06 делает filtered called range ключевым ограничением для dominated offsuit broadways.", explanationEn: "FTGU-E06 makes the filtered called range a key constraint for dominated offsuit broadways.", changedVariables: ["opponent_continue_range"],
  },
  {
    id: "PM-PF-05-107", skillId: "PF-05", kind: "boundary", sourceRefs: ["FTGU-E06"], assumptions: ["BB weak/passive", "versatile hand", "keeping weaker ranges in valuable"], cueRu: "BB почти не squeezes, а versatile hand выигрывает от сохранения weaker ranges.", cueEn: "The BB almost never squeezes and a versatile hand benefits from keeping weaker ranges in.", questionRu: "Как трактовать 3-bet-or-fold default?", questionEn: "How should the 3-bet-or-fold default be interpreted?",
    actionOptions: [o("a", "Как default с exceptions", "As a default with exceptions"), o("b", "Как literal law", "As a literal law", "TITLE_LITERALISM"), o("c", "Как запрет 3-bet", "As a ban on 3-betting", "TITLE_INVERSION")],
    reasonOptions: [o("r1", "Source прямо допускает conditional flats при изменении table-behind incentives", "The source explicitly allows conditional flats when table-behind incentives change"), o("r2", "Defaults never need context", "Defaults never need context", "DEFAULT_AS_LAW"), o("r3", "SB position becomes IP when BB passive", "SB becomes IP when the BB is passive", "POSITION_FALSE")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25, explanationRu: "FTGU-E06 явно говорит, что название урока — simplification; некоторые flats остаются при weak/passive BB и подходящей hand class.", explanationEn: "FTGU-E06 explicitly says the lesson title is a simplification; some flats remain versus a weak/passive BB with suitable hand classes.",
  },
];
