import type { PracticalDecision } from "./types";

const o=(id:string,textRu:string,textEn:string,misconception?:string)=>({id,textRu,textEn,misconception});

type F={
  skillId:string; prefix:string; sourceRefs:string[];
  nodeRu:string; nodeEn:string;
  signalRu:string; signalEn:string;
  defaultRu:string; defaultEn:string;
  whyRu:string; whyEn:string;
  changeRu:string; changeEn:string;
  boundaryRu:string; boundaryEn:string;
  shortcutRu:string; shortcutEn:string;
};

function family(f:F):PracticalDecision[]{
  const rows:Array<{kind:PracticalDecision["kind"]; cueRu:string;cueEn:string;qRu:string;qEn:string;goodRu:string;goodEn:string;whyRu:string;whyEn:string;bad1Ru:string;bad1En:string;bad2Ru:string;bad2En:string;changed?:string[]}>= [
    {kind:"recognition",cueRu:f.nodeRu,cueEn:f.nodeEn,qRu:"Какой signal нужно назвать до action?",qEn:"Which signal should be named before choosing an action?",goodRu:f.signalRu,goodEn:f.signalEn,whyRu:f.whyRu,whyEn:f.whyEn,bad1Ru:f.shortcutRu,bad1En:f.shortcutEn,bad2Ru:"Только absolute hand rank",bad2En:"Only absolute hand rank"},
    {kind:"recognition",cueRu:`${f.nodeRu} Один upstream action меняет surviving range.`,cueEn:`${f.nodeEn} One upstream action changes the surviving range.`,qRu:"Можно ли сохранить прежний label без пересчёта?",qEn:"Can the old label be kept without recomputing?",goodRu:"Нет — ancestry меняет meaning node",goodEn:"No — ancestry changes the node's meaning",whyRu:"Later-street classes are contextual: prior actions determine which strong/bluff regions still exist.",whyEn:"Later-street classes are contextual: prior actions determine which strong/bluff regions still exist.",bad1Ru:"Да — street label достаточно",bad1En:"Yes — the street label is sufficient",bad2Ru:"Да — initiative всё определяет",bad2En:"Yes — initiative determines everything"},
    {kind:"decision",cueRu:f.nodeRu,cueEn:f.nodeEn,qRu:"Какой practical default лучше?",qEn:"Which practical default is better?",goodRu:f.defaultRu,goodEn:f.defaultEn,whyRu:f.whyRu,whyEn:f.whyEn,bad1Ru:f.shortcutRu,bad1En:f.shortcutEn,bad2Ru:"Выбирать action по размеру pot без ranges",bad2En:"Choose the action from pot size without ranges"},
    {kind:"decision",cueRu:`${f.nodeRu} У Hero есть один очевидный slogan, но branch composition не проверена.`,cueEn:`${f.nodeEn} Hero has an obvious slogan, but the branch composition has not been checked.`,qRu:"Что делать?",qEn:"What should Hero do?",goodRu:"Сначала проверить surviving value/bluff/continue regions",goodEn:"First inspect surviving value/bluff/continue regions",whyRu:"Ancestry is the causal bridge from the previous street to the current action.",whyEn:"Ancestry is the causal bridge from the previous street to the current action.",bad1Ru:f.shortcutRu,bad1En:f.shortcutEn,bad2Ru:"Игнорировать previous street",bad2En:"Ignore the previous street"},
    {kind:"decision",cueRu:`${f.nodeRu} Current price/sizing materially changes.`,cueEn:`${f.nodeEn} The current price/sizing changes materially.`,qRu:"Что пересчитать?",qEn:"What should be recomputed?",goodRu:"Threshold + continuing range + future/terminal EV",goodEn:"Threshold + continuing range + future/terminal EV",whyRu:"Sizing is part of the branch and changes both price and range selection.",whyEn:"Sizing is part of the branch and changes both price and range selection.",bad1Ru:"Ничего — hand та же",bad1En:"Nothing — the hand is unchanged",bad2Ru:"Только pot size display",bad2En:"Only the pot-size display"},
    {kind:"changed",cueRu:f.changeRu,cueEn:f.changeEn,qRu:"Как должен измениться вывод?",qEn:"How should the conclusion change?",goodRu:"Пересобрать branch, а не переносить старый action",goodEn:"Rebuild the branch rather than copying the old action",whyRu:"The changed variable alters range ownership, price, bluff supply or value targets.",whyEn:"The changed variable alters range ownership, price, bluff supply or value targets.",bad1Ru:"Action не меняется",bad1En:"The action does not change",bad2Ru:f.shortcutRu,bad2En:f.shortcutEn,changed:["material_node_variable"]},
    {kind:"changed",cueRu:`${f.nodeRu} Opponent range/action history становится заметно сильнее или более защищённой.`,cueEn:`${f.nodeEn} The opponent range/action history becomes materially stronger or better protected.`,qRu:"Что происходит с aggressive/marginal branch?",qEn:"What happens to the aggressive/marginal branch?",goodRu:"Становится более selective",goodEn:"It becomes more selective",whyRu:"Stronger surviving ranges reduce the EV of thin value, weak bluffs and marginal bluff-catches.",whyEn:"Stronger surviving ranges reduce the EV of thin value, weak bluffs and marginal bluff-catches.",bad1Ru:"Становится шире автоматически",bad1En:"It automatically becomes wider",bad2Ru:"Не меняется",bad2En:"It does not change",changed:["opponent_range_strength"]},
    {kind:"boundary",cueRu:f.boundaryRu,cueEn:f.boundaryEn,qRu:"Где boundary?",qEn:"Where is the boundary?",goodRu:"Отказаться от universal rule и вернуться к source-scoped mechanism",goodEn:"Reject the universal rule and return to the source-scoped mechanism",whyRu:f.whyRu,whyEn:f.whyEn,bad1Ru:f.shortcutRu,bad1En:f.shortcutEn,bad2Ru:"Invent exact frequency",bad2En:"Invent an exact frequency"},
  ];
  return rows.map((r,i)=>{
    const slot=i%3;
    const good=o("good",r.goodRu,r.goodEn); const b1=o("b1",r.bad1Ru,r.bad1En,"LATER_STREET_SHORTCUT"); const b2=o("b2",r.bad2Ru,r.bad2En,"ANCESTRY_IGNORED");
    const gr=o("goodR",r.whyRu,r.whyEn); const br1=o("br1","Street label сам задаёт action","The street label itself determines the action","LABEL_AS_ACTION"); const br2=o("br2","Previous action не меняет range","Previous action does not change the range","HISTORY_IGNORED");
    const actionOptions=slot===0?[good,b1,b2]:slot===1?[b1,good,b2]:[b1,b2,good];
    const reasonOptions=slot===0?[br1,gr,br2]:slot===1?[gr,br1,br2]:[br1,br2,gr];
    return {id:`${f.prefix}-${101+i}`,skillId:f.skillId,kind:r.kind,sourceRefs:f.sourceRefs,assumptions:["source-scoped later-street mechanism; no unreviewed exact frequency"],cueRu:r.cueRu,cueEn:r.cueEn,questionRu:r.qRu,questionEn:r.qEn,actionOptions,reasonOptions,correctActionId:"good",correctReasonId:"goodR",targetSeconds:27,explanationRu:r.whyRu,explanationEn:r.whyEn,changedVariables:r.changed} satisfies PracticalDecision;
  });
}

const families:F[]=[
  {skillId:"TURN-01",prefix:"PM-TURN-01-A8",sourceRefs:["FTGU-E21"],nodeRu:"Turn после flop action: нужно отличить blank от карты, которая меняет cap/nut ownership.",nodeEn:"Turn after flop action: distinguish a blank from a card that changes cap/nut ownership.",signalRu:"Runout class × surviving ranges",signalEn:"Runout class × surviving ranges",defaultRu:"Классифицировать карту через range shift, а не scary/not-scary label",defaultEn:"Classify the card through the range shift, not a scary/not-scary label",whyRu:"FTGU-E21 требует сначала понять, сохранился ли cap после конкретного flop branch.",whyEn:"FTGU-E21 first asks whether the cap survived the specific flop branch.",changeRu:"Тот же flop branch: turn меняется blank → draw-completing/range-uncapping.",changeEn:"Same flop branch: turn changes blank → draw-completing/range-uncapping.",boundaryRu:"Learner считает любую overcard scare card automatic barrel.",boundaryEn:"The learner treats every overcard scare card as an automatic barrel.",shortcutRu:"Scare card = bet",shortcutEn:"Scare card = bet"},
  {skillId:"TURN-02",prefix:"PM-TURN-02-A8",sourceRefs:["FTGU-E21","SLC-TURN-BARREL","CP-G3-L07"],nodeRu:"Hero c-bet flop и выбирает turn barrel.",nodeEn:"Hero c-bet the flop and is choosing a turn barrel.",signalRu:"Value/bluff candidate × runout × surviving continue range",signalEn:"Value/bluff candidate × runout × surviving continue range",defaultRu:"Баррелить selected value/bluffs, если card/range shift поддерживает pressure",defaultEn:"Barrel selected value/bluffs when the card/range shift supports pressure",whyRu:"Turn aggression требует подходящей hand class и изменившейся range interaction, не просто momentum.",whyEn:"Turn aggression requires a suitable hand class and changed range interaction, not just momentum.",changeRu:"Same hand/line; turn from blank favourable to caller → card that improves aggressor leverage.",changeEn:"Same hand/line; turn changes from a blank favorable to the caller → a card that improves aggressor leverage.",boundaryRu:"Learner triple-barrels because 'started betting'.",boundaryEn:"The learner keeps barreling because 'we started betting'.",shortcutRu:"Bet flop = bet turn",shortcutEn:"Bet flop = bet turn"},
  {skillId:"TURN-03",prefix:"PM-TURN-03-A8",sourceRefs:["FTGU-E20","CINJ-E06"],nodeRu:"Flop checked back; OOP рассматривает turn probe.",nodeEn:"Flop checked back; OOP considers a turn probe.",signalRu:"Какие strong hands check-back удалил и вернула ли turn card strength",signalEn:"Which strong hands the check-back removed and whether the turn restored strength",defaultRu:"Probe more when checked-back range genuinely capped/overwide",defaultEn:"Probe more when the checked-back range is genuinely capped/overwide",whyRu:"FTGU-E20 запрещает mechanical probe: exact checked range и turn card определяют leverage.",whyEn:"FTGU-E20 rejects mechanical probing: the exact checked range and turn card determine leverage.",changeRu:"Same check-back; turn now restores nutted/strong region to IP.",changeEn:"Same check-back; the turn now restores a nutted/strong region to IP.",boundaryRu:"Learner probes every missed c-bet turn.",boundaryEn:"The learner probes every turn after a missed c-bet.",shortcutRu:"Missed c-bet = probe",shortcutEn:"Missed c-bet = probe"},
  {skillId:"TURN-04",prefix:"PM-TURN-04-A8",sourceRefs:["SLC-TURN-LEADS"],nodeRu:"Hero called flop OOP and considers leading turn.",nodeEn:"Hero called flop OOP and considers leading the turn.",signalRu:"Turn changes nut/coverage ownership enough to justify a lead branch",signalEn:"The turn changes nut/coverage ownership enough to justify a leading branch",defaultRu:"Lead only on source-supported range-shifting runouts",defaultEn:"Lead only on source-supported range-shifting runouts",whyRu:"Turn lead is a conditional branch created by specific runouts, not a generic donk strategy.",whyEn:"A turn lead is a conditional branch created by specific runouts, not a generic donk strategy.",changeRu:"Same flop call; turn moves neutral → card that strongly favours caller's retained region.",changeEn:"Same flop call; turn moves neutral → a card that strongly favors the caller's retained region.",boundaryRu:"Learner leads any card that improved Hero's exact hand.",boundaryEn:"The learner leads any card that improved Hero's exact hand.",shortcutRu:"Hero improved = lead",shortcutEn:"Hero improved = lead"},
  {skillId:"TURN-05",prefix:"PM-TURN-05-A8",sourceRefs:["CP-G3-L02","FTGU-E21"],nodeRu:"Turn medium-strength showdown hand: bet thin/value/protection или check-back/pot-control.",nodeEn:"Turn medium-strength showdown hand: thin/value/protection bet or check-back/pot-control.",signalRu:"Worse continues + vulnerability + future river plan",signalEn:"Worse continues + vulnerability + future river plan",defaultRu:"Bet only if worse continues/value-protection justify it; otherwise preserve showdown",defaultEn:"Bet only if worse continues/value-protection justify it; otherwise preserve showdown",whyRu:"Thin betting must name a worse continuing region and account for what raising/river branches do.",whyEn:"Thin betting must name a worse continuing region and account for raising/river branches.",changeRu:"Same hand; opponent continue range becomes tighter/stronger.",changeEn:"Same hand; the opponent continuing range becomes tighter/stronger.",boundaryRu:"Learner bets because hand is probably ahead.",boundaryEn:"The learner bets because the hand is probably ahead.",shortcutRu:"Likely ahead = value bet",shortcutEn:"Likely ahead = value bet"},
  {skillId:"RIV-01",prefix:"PM-RIV-01-A8",sourceRefs:["LCM-09","CP-G3-L02"],nodeRu:"River value decision with no future street.",nodeEn:"River value decision with no future street.",signalRu:"Конкретные worse hands that call × chosen sizing",signalEn:"Concrete worse hands that call × chosen sizing",defaultRu:"Value bet only when plausible worse calls exist for this size",defaultEn:"Value bet only when plausible worse calls exist for this size",whyRu:"River value is defined against the calling range, not by whether Hero is often best at showdown.",whyEn:"River value is defined against the calling range, not by whether Hero is often best at showdown.",changeRu:"Same hand/board; villain calling range becomes materially tighter.",changeEn:"Same hand/board; villain calling range becomes materially tighter.",boundaryRu:"Learner bets every likely-best river hand.",boundaryEn:"The learner bets every river hand that is likely best.",shortcutRu:"Best often = value bet",shortcutEn:"Often best = value bet"},
  {skillId:"RIV-02",prefix:"PM-RIV-02-A8",sourceRefs:["FTGU-E23","CP-G3-L03"],nodeRu:"River bluff selection after a completed line.",nodeEn:"River bluff selection after a completed line.",signalRu:"Low showdown value + blockers/unblockers + credible value ancestry",signalEn:"Low showdown value + blockers/unblockers + credible value ancestry",defaultRu:"Choose bluffs that improve fold EV without blocking folds or destroying value credibility",defaultEn:"Choose bluffs that improve fold EV without blocking folds or destroying value credibility",whyRu:"FTGU-E23 selects bluffs by showdown value and card-removal effects within the line's value region.",whyEn:"FTGU-E23 selects bluffs by showdown value and card-removal effects within the line's value region.",changeRu:"Same missed draw family; one combo blocks folds while another unblocks them.",changeEn:"Same missed-draw family; one combo blocks folds while another unblocks them.",boundaryRu:"Learner bluffs every missed draw.",boundaryEn:"The learner bluffs every missed draw.",shortcutRu:"Missed draw = bluff",shortcutEn:"Missed draw = bluff"},
  {skillId:"RIV-03",prefix:"PM-RIV-03-A8",sourceRefs:["FTGU-E22","CINJ-E02","CINJ-E04"],nodeRu:"River bluff-catch: Hero beats bluffs but loses to value.",nodeEn:"River bluff-catch: Hero beats bluffs but loses to value.",signalRu:"Price × credible bluff supply × removal × line ancestry",signalEn:"Price × credible bluff supply × removal × line ancestry",defaultRu:"Call only when enough plausible bluffs survive for the price",defaultEn:"Call only when enough plausible bluffs survive for the price",whyRu:"FTGU-E22 couples pot odds with the opponent's actual bluff candidates and blocker effects.",whyEn:"FTGU-E22 couples pot odds with the opponent's actual bluff candidates and blocker effects.",changeRu:"Same price/hand; previous line removes most natural missed bluffs.",changeEn:"Same price/hand; the previous line removes most natural missed bluffs.",boundaryRu:"Learner says pot odds alone force the call.",boundaryEn:"The learner says pot odds alone force the call.",shortcutRu:"Good price = call",shortcutEn:"Good price = call"},
  {skillId:"RIV-04",prefix:"PM-RIV-04-A8",sourceRefs:["CINJ-E08"],nodeRu:"Small river block/probe line.",nodeEn:"Small river block/probe line.",signalRu:"Price-setting purpose + opponent response + hand's showdown/value class",signalEn:"Price-setting purpose + opponent response + the hand's showdown/value class",defaultRu:"Use small river line only when it improves value/realisation versus checking and has a plan vs raise",defaultEn:"Use a small river line only when it improves value/realization versus checking and has a plan versus a raise",whyRu:"CINJ-E08 treats small river bets as a specific range/price tool, not a universal cheap showdown button.",whyEn:"CINJ-E08 treats small river bets as a specific range/price tool, not a universal cheap-showdown button.",changeRu:"Same hand; opponent starts raising small river bets much more aggressively.",changeEn:"Same hand; the opponent starts raising small river bets much more aggressively.",boundaryRu:"Learner block-bets every medium-strength river hand.",boundaryEn:"The learner block-bets every medium-strength river hand.",shortcutRu:"Medium hand = block bet",shortcutEn:"Medium hand = block bet"},
  {skillId:"RIV-05",prefix:"PM-RIV-05-A8",sourceRefs:["FTGU-E24","FTGU-E25","CINJ-E10"],nodeRu:"River population exploit candidate: underbluff/overbluff evidence in one branch.",nodeEn:"River population exploit candidate: underbluff/overbluff evidence in one branch.",signalRu:"Branch-specific evidence strength + sample/observation confidence",signalEn:"Branch-specific evidence strength + sample/observation confidence",defaultRu:"Deviate only in the evidenced branch; otherwise retain baseline",defaultEn:"Deviate only in the evidenced branch; otherwise retain baseline",whyRu:"Exploitative folds/calls require actual branch evidence and must not become global player labels.",whyEn:"Exploitative folds/calls require actual branch evidence and must not become global player labels.",changeRu:"Same river spot; evidence changes from one anecdote → repeated branch-specific observation.",changeEn:"Same river spot; evidence changes from one anecdote → repeated branch-specific observation.",boundaryRu:"Learner generalises one underbluffed node to every river line.",boundaryEn:"The learner generalizes one underbluffed node to every river line.",shortcutRu:"Pool underbluffs = fold all bluff-catchers",shortcutEn:"Pool underbluffs = fold all bluff-catchers"},
];

export const turnRiverA8ExpansionDecisions:PracticalDecision[]=families.flatMap(family);

export const laterStreetLegacySkillBridges={
  "OOP-06":["TURN-04"],
  "OOP-07":["RIV-03","RIV-04"],
  "IP-03":["TURN-02"],
  "IP-04":["TURN-03"],
  "IP-05":["TURN-02","RIV-01","RIV-02"],
  "IP-06":["TURN-05","RIV-01"],
} as const;
