import type { PracticalDecision } from "./types";

const o = (id: string, textRu: string, textEn: string, misconception?: string) => ({ id, textRu, textEn, misconception });

export const preflopLiveExpansionDecisions: PracticalDecision[] = [
  // PF-09 — squeezing
  {
    id: "PM-PF-09-101", skillId: "PF-09", kind: "recognition", sourceRefs: ["SLC-M01-L02", "LCM-02"],
    assumptions: ["open + caller", "Hero considers a squeeze"],
    cueRu: "Перед Hero уже есть open и call.", cueEn: "There is already an open and a call before Hero.",
    questionRu: "Что делает spot squeeze-кандидатом, но ещё не гарантирует raise?", questionEn: "What makes the spot a squeeze candidate without yet guaranteeing a raise?",
    actionOptions: [o("a", "Dead money + возможные fold targets", "Dead money plus possible fold targets"), o("b", "Сам факт двух игроков в pot", "Merely having two players in the pot", "SQUEEZE_AUTOPILOT"), o("c", "Любая suited рука Hero", "Any suited Hero hand", "SUITED_AUTOPILOT")],
    reasonOptions: [o("r1", "Squeeze получает дополнительный EV от уже вложенных денег и folds, но called branch всё ещё важен", "A squeeze gains EV from dead money and folds, but the called branch still matters"), o("r2", "Open + call всегда означает слабые ranges", "Open plus call always means weak ranges", "RANGE_STRENGTH_IGNORED"), o("r3", "Dead money отменяют необходимость думать о продолжениях", "Dead money remove the need to consider continuations", "CALLED_BRANCH_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25,
    explanationRu: "SLC-M01-L02 и LCM-02 рассматривают dead money как часть squeeze EV, но не как автоматическую лицензию рейзить без проверки fold targets и called branch.",
    explanationEn: "SLC-M01-L02 and LCM-02 treat dead money as part of squeeze EV, not as an automatic license to raise without checking fold targets and the called branch.",
  },
  {
    id: "PM-PF-09-102", skillId: "PF-09", kind: "recognition", sourceRefs: ["SLC-M01-L02"],
    assumptions: ["caller is sticky", "opener continues reasonably", "Hero squeeze bluff candidate"],
    cueRu: "Caller редко fold на squeeze, opener тоже не overfold.", cueEn: "The caller rarely folds to squeezes and the opener does not overfold either.",
    questionRu: "Какой компонент squeeze-кандидата становится важнее?", questionEn: "Which component of squeeze-hand selection becomes more important?",
    actionOptions: [o("a", "Качество руки when called", "Hand quality when called"), o("b", "Только blocker", "Only the blocker", "BLOCKER_ONLY"), o("c", "Количество dead money независимо от responses", "Dead money regardless of responses", "DEAD_MONEY_ONLY")],
    reasonOptions: [o("r1", "При низком fold equity EV чаще приходит из value/isolation и postflop playability", "With low fold equity, EV relies more on value/isolation and postflop playability"), o("r2", "Sticky caller повышает fold equity", "A sticky caller increases fold equity", "FOLD_EQUITY_BACKWARDS"), o("r3", "Called branch не влияет на preflop selection", "The called branch does not affect preflop selection", "CALLED_BRANCH_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25,
    explanationRu: "Когда folds уменьшаются, squeeze range должен выдерживать продолжение соперников, а bluff-only candidates теряют EV.",
    explanationEn: "As folds disappear, the squeeze range must survive continuation, and bluff-only candidates lose EV.",
  },
  {
    id: "PM-PF-09-103", skillId: "PF-09", kind: "decision", sourceRefs: ["SLC-M01-L02"],
    assumptions: ["open + loose caller", "Hero has strong linear value candidate", "caller continues many worse hands"],
    cueRu: "Open + loose caller; Hero имеет strong hand, а caller часто продолжит хуже.", cueEn: "Open plus a loose caller; Hero has a strong hand and the caller often continues worse.",
    questionRu: "Какую цель squeeze нужно проверить первой?", questionEn: "Which squeeze objective should be checked first?",
    actionOptions: [o("a", "Value/isolation против худших continues", "Value/isolation versus worse continues"), o("b", "Превратить руку в bluff ради dead money", "Turn the hand into a bluff for the dead money", "VALUE_AS_BLUFF"), o("c", "Flat всегда лучше, потому что pot уже multiway", "Flat is always better because the pot is already multiway", "FLAT_AUTOPILOT")],
    reasonOptions: [o("r1", "Если худшие руки продолжают, raise может строить pot и изолировать с реальным value edge", "If worse hands continue, a raise can build the pot and isolate with a real value edge"), o("r2", "Squeeze ценен только когда все fold", "A squeeze is valuable only when everyone folds", "FOLD_ONLY_MODEL"), o("r3", "Multiway pot запрещает value raising preflop", "A multiway pot prohibits value raising preflop", "MULTIWAY_PASSIVITY")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30,
    explanationRu: "Squeeze может быть value/isolation action; его EV не обязан исходить только из folds.",
    explanationEn: "A squeeze can be a value/isolation action; its EV does not have to come only from folds.",
  },
  {
    id: "PM-PF-09-104", skillId: "PF-09", kind: "decision", sourceRefs: ["SLC-M01-L02", "FTGU-E15"],
    assumptions: ["Hero considers weak blocker bluff", "opener and caller both continue too often"],
    cueRu: "У Hero есть blocker, но оба соперника продолжают слишком часто.", cueEn: "Hero has a blocker, but both opponents continue too often.",
    questionRu: "Как относиться к blocker-only squeeze bluff?", questionEn: "How should a blocker-only squeeze bluff be treated?",
    actionOptions: [o("a", "Сильно понизить его привлекательность", "Reduce its attractiveness substantially"), o("b", "Сделать automatic squeeze", "Make it an automatic squeeze", "BLOCKER_AUTOPILOT"), o("c", "Blocker гарантирует достаточные folds", "The blocker guarantees enough folds", "BLOCKER_GUARANTEE")],
    reasonOptions: [o("r1", "Blocker полезен только внутри branch, где folds реально существуют и called branch не разрушает EV", "A blocker helps only inside a branch where folds actually exist and the called branch does not destroy EV"), o("r2", "Любой Ace blocker делает bluff прибыльным", "Any ace blocker makes the bluff profitable", "ACE_BLOCKER_MAGIC"), o("r3", "Fold equity не влияет на polar aggression", "Fold equity does not affect polar aggression", "FOLD_EQUITY_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30,
    explanationRu: "SLC squeeze framework и FTGU polar-vs-linear logic требуют реальных fold targets; blocker не заменяет branch EV.",
    explanationEn: "The SLC squeeze framework and FTGU polar-vs-linear logic require real fold targets; a blocker does not replace branch EV.",
  },
  {
    id: "PM-PF-09-105", skillId: "PF-09", kind: "decision", sourceRefs: ["SLC-M01-L02"],
    assumptions: ["same ranges", "Hero moves from BTN to SB", "meaningful stack remains"],
    cueRu: "Тот же open+call spot, но Hero теперь SB вместо BTN.", cueEn: "The same open-plus-call spot, but Hero is now in the SB instead of the BTN.",
    questionRu: "Что должно измениться в оценке marginal squeeze?", questionEn: "What should change in the evaluation of a marginal squeeze?",
    actionOptions: [o("a", "Требовать больше качества от called branch", "Demand more quality from the called branch"), o("b", "OOP делает bluff squeeze лучше автоматически", "Being OOP automatically improves bluff squeezes", "POSITION_BACKWARDS"), o("c", "Position не влияет до flop", "Position does not matter preflop", "POSITION_IGNORED")],
    reasonOptions: [o("r1", "OOP ухудшает equity realisation when called и повышает цену слабого branch", "Being OOP worsens equity realization when called and raises the cost of a weak branch"), o("r2", "SB всегда получает closing action", "The SB always closes the action", "SB_CLOSES_ACTION_FALSE"), o("r3", "Squeeze заканчивает hand независимо от response", "A squeeze ends the hand regardless of response", "RESPONSE_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30,
    explanationRu: "При одинаковой preflop fold equity позиция меняет качество postflop called branch.",
    explanationEn: "With the same preflop fold equity, position changes the quality of the postflop called branch.",
  },
  {
    id: "PM-PF-09-106", skillId: "PF-09", kind: "changed", sourceRefs: ["SLC-M01-L02"],
    assumptions: ["same Hero hand", "caller changes from sticky to overfolding"],
    cueRu: "Hero hand и opener те же; caller теперь часто fold на squeeze.", cueEn: "Hero's hand and the opener stay the same; the caller now folds frequently to squeezes.",
    questionRu: "Как меняется ценность подходящего bluff candidate?", questionEn: "How does the value of a suitable bluff candidate change?",
    actionOptions: [o("a", "Растёт", "It rises"), o("b", "Падает", "It falls", "FOLD_EQUITY_BACKWARDS"), o("c", "Не меняется", "It does not change", "OPPONENT_RESPONSE_IGNORED")],
    reasonOptions: [o("r1", "Появляется дополнительный fold branch на уже вложенные caller chips", "An additional fold branch appears against the caller's already-invested chips"), o("r2", "Caller fold уменьшает dead money", "A caller fold reduces dead money", "DEAD_MONEY_BACKWARDS"), o("r3", "Squeeze EV определяется только картами Hero", "Squeeze EV is determined only by Hero's cards", "CARDS_ONLY")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25,
    explanationRu: "Одна смена opponent response может сделать тот же candidate существенно лучше, не превращая его в universal squeeze.",
    explanationEn: "Changing only the opponent response can make the same candidate materially better without turning it into a universal squeeze.",
    changedVariables: ["caller_fold_to_squeeze"],
  },
  {
    id: "PM-PF-09-107", skillId: "PF-09", kind: "changed", sourceRefs: ["SLC-M01-L02"],
    assumptions: ["same hand and opponents", "Hero moves IP to OOP"],
    cueRu: "Тот же squeeze candidate, но Hero теряет position when called.", cueEn: "The same squeeze candidate now loses position when called.",
    questionRu: "Как двигается marginal squeeze EV?", questionEn: "Which way does marginal squeeze EV move?",
    actionOptions: [o("a", "Обычно вниз", "Generally down"), o("b", "Обычно вверх", "Generally up", "POSITION_BACKWARDS"), o("c", "Position не относится к squeeze", "Position is irrelevant to squeezing", "POSITION_IGNORED")],
    reasonOptions: [o("r1", "Called branch реализует equity хуже OOP", "The called branch realizes equity worse OOP"), o("r2", "OOP всегда создаёт больше folds", "OOP always creates more folds", "FALSE_FOLD_EQUITY"), o("r3", "Preflop raise отменяет positional disadvantage", "A preflop raise removes positional disadvantage", "POSITION_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25,
    explanationRu: "Squeeze decision должен учитывать не только preflop folds, но и качество дерева после call.",
    explanationEn: "A squeeze decision must include not only preflop folds but also the quality of the tree after a call.",
    changedVariables: ["position_when_called"],
  },
  {
    id: "PM-PF-09-108", skillId: "PF-09", kind: "boundary", sourceRefs: ["SLC-M01-L02", "LCM-02"],
    assumptions: ["large dead money", "very low fold equity", "Hero candidate performs poorly when called"],
    cueRu: "Dead money много, но почти никто не fold, а Hero плохо играет when called.", cueEn: "There is lots of dead money, but almost nobody folds and Hero performs poorly when called.",
    questionRu: "Достаточно ли dead money для squeeze bluff?", questionEn: "Is the dead money sufficient for a squeeze bluff?",
    actionOptions: [o("a", "Нет — branch может оставаться плохим", "No — the branch can still be poor"), o("b", "Да — dead money всегда перекрывают called branch", "Yes — dead money always outweigh the called branch", "DEAD_MONEY_MAGIC"), o("c", "Да, если Hero suited", "Yes if Hero is suited", "SUITED_AUTOPILOT")],
    reasonOptions: [o("r1", "Squeeze EV — сумма fold и continuation branches; большой pot не спасает плохую continuation tree автоматически", "Squeeze EV is the sum of fold and continuation branches; a large pot does not automatically rescue a bad continuation tree"), o("r2", "Уже вложенные chips принадлежат Hero после raise", "Already-invested chips belong to Hero after a raise", "DEAD_MONEY_OWNERSHIP"), o("r3", "Suitedness гарантирует enough equity", "Suitedness guarantees enough equity", "SUITED_GUARANTEE")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30,
    explanationRu: "Это boundary squeeze heuristic: dead money повышают upside, но не отменяют необходимость жизнеспособного called/4-bet tree.",
    explanationEn: "This is the boundary of the squeeze heuristic: dead money raise the upside but do not remove the need for a viable called/4-bet tree.",
  },

  // PF-10 — live/depth/rake/straddle adjustments
  {
    id: "PM-PF-10-101", skillId: "PF-10", kind: "recognition", sourceRefs: ["SLC-M01-L03"],
    assumptions: ["mandatory straddle", "same dollar stacks"],
    cueRu: "Стэки в долларах не изменились, но включился mandatory straddle.", cueEn: "Dollar stacks are unchanged, but a mandatory straddle is now on.",
    questionRu: "Что нужно переоценить первым?", questionEn: "What should be re-evaluated first?",
    actionOptions: [o("a", "Working blind unit, effective depth и action order", "Working blind unit, effective depth and action order"), o("b", "Ничего — dollar stack тот же", "Nothing — the dollar stack is unchanged", "NOMINAL_STACK_ONLY"), o("c", "Только размер rake", "Only rake size", "STRADDLE_RAKE_ONLY")],
    reasonOptions: [o("r1", "Straddle меняет цену дерева и часто делает game shallower в рабочих единицах", "A straddle changes the tree's price and often makes the game shallower in working units"), o("r2", "Depth измеряется только обычными BB", "Depth is measured only in ordinary big blinds", "NOMINAL_BB_ONLY"), o("r3", "Action order при straddle всегда тот же", "Action order is always unchanged under a straddle", "ACTION_ORDER_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25,
    explanationRu: "SLC-M01-L03 требует перестраивать working preflop geometry при straddle, а не сохранять non-straddled tree.",
    explanationEn: "SLC-M01-L03 requires rebuilding working preflop geometry under a straddle rather than preserving the non-straddled tree.",
  },
  {
    id: "PM-PF-10-102", skillId: "PF-10", kind: "recognition", sourceRefs: ["FTGU-E05"],
    assumptions: ["same BB hand/open", "rake materially higher"],
    cueRu: "Hand, opener и sizing те же; rake вырос.", cueEn: "Hand, opener and sizing are unchanged; rake rises.",
    questionRu: "Какая зона preflop range наиболее уязвима первой?", questionEn: "Which part of the preflop range is most vulnerable first?",
    actionOptions: [o("a", "Marginal thin calls", "Marginal thin calls"), o("b", "Только premium value", "Only premium value", "RAKE_PREMIUM_ONLY"), o("c", "Rake не меняет preflop EV", "Rake does not change preflop EV", "RAKE_IGNORED")],
    reasonOptions: [o("r1", "Rake вычитает EV и первым переворачивает близкие к нулю branches", "Rake subtracts EV and flips near-zero branches first"), o("r2", "Rake добавляет implied odds", "Rake adds implied odds", "RAKE_BACKWARDS"), o("r3", "Marginal calls не доходят до raked pots", "Marginal calls never reach raked pots", "RAKE_FALSE")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 20,
    explanationRu: "FTGU-E05 прямо отмечает, что высокий rake убирает marginal BB defends раньше сильных continues.",
    explanationEn: "FTGU-E05 explicitly notes that high rake removes marginal BB defenses before strong continues.",
  },
  {
    id: "PM-PF-10-103", skillId: "PF-10", kind: "decision", sourceRefs: ["FTGU-E02"],
    assumptions: ["same fringe RFI hand", "strong aggressive players behind"],
    cueRu: "Fringe open-кандидат; позади несколько сильных aggressive игроков.", cueEn: "A fringe opening candidate faces several strong aggressive players behind.",
    questionRu: "Куда должен двигаться fringe open?", questionEn: "Which way should the fringe open move?",
    actionOptions: [o("a", "К tighter/fold", "Toward tighter/fold"), o("b", "К wider open", "Toward a wider open", "PLAYERS_BEHIND_BACKWARDS"), o("c", "Не менять из-за позиции", "No change because position determines everything", "POSITION_ONLY")],
    reasonOptions: [o("r1", "Pressure behind ухудшает realisation и defensibility fringe range", "Pressure behind worsens realization and defensibility of the fringe range"), o("r2", "Aggressive players behind увеличивают immediate fold equity Hero", "Aggressive players behind increase Hero's immediate fold equity", "FALSE_FOLD_EQUITY"), o("r3", "Opening range фиксирован только seat label", "Opening range is fixed only by the seat label", "CHART_RIGIDITY")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25,
    explanationRu: "FTGU-E02 прямо разрешает двигать fringe по качеству игроков позади; chart — default, не закон.",
    explanationEn: "FTGU-E02 explicitly allows moving the fringe according to players behind; the chart is a default, not a law.",
  },
  {
    id: "PM-PF-10-104", skillId: "PF-10", kind: "decision", sourceRefs: ["FTGU-E02"],
    assumptions: ["same fringe RFI hand", "weak passive players behind", "rake unchanged"],
    cueRu: "Та же fringe hand; позади слабые пассивные игроки.", cueEn: "The same fringe hand now faces weak passive players behind.",
    questionRu: "Как меняется attractiveness open?", questionEn: "How does opening attractiveness change?",
    actionOptions: [o("a", "Может вырасти", "It can rise"), o("b", "Обязательно падает", "It must fall", "PLAYERS_BEHIND_BACKWARDS"), o("c", "Players behind никогда не меняют fringe", "Players behind never change the fringe", "CHART_RIGIDITY")],
    reasonOptions: [o("r1", "Меньше pressure и выше postflop edge могут улучшить marginal EV", "Less pressure and a larger postflop edge can improve marginal EV"), o("r2", "Слабые игроки всегда 3-bet чаще", "Weak players always 3-bet more", "PLAYER_TYPE_MAGIC"), o("r3", "Position chart запрещает adjustments", "The position chart prohibits adjustments", "CHART_RIGIDITY")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25,
    explanationRu: "Adjustment относится к fringe, а не означает безграничное widening всего opening range.",
    explanationEn: "The adjustment applies to the fringe; it does not mean unlimited widening of the entire opening range.",
  },
  {
    id: "PM-PF-10-105", skillId: "PF-10", kind: "decision", sourceRefs: ["SLC-M01-L03", "FTGU-E04"],
    assumptions: ["effective depth increases", "implied-odds hand", "position retained"],
    cueRu: "Effective depth вырос; Hero IP с implied-odds hand.", cueEn: "Effective depth increases; Hero is IP with an implied-odds hand.",
    questionRu: "Какой фактор чаще получает больше веса?", questionEn: "Which factor generally gains weight?",
    actionOptions: [o("a", "Future payoff / implied odds и nut potential", "Future payoff / implied odds and nut potential"), o("b", "Только immediate high-card strength", "Only immediate high-card strength", "HIGH_CARD_ONLY"), o("c", "Глубина не влияет на preflop branch", "Depth does not affect the preflop branch", "DEPTH_IGNORED")],
    reasonOptions: [o("r1", "Больше stack behind расширяет future tree и цену domination/reverse implied odds", "More stack behind expands the future tree and the cost of domination/reverse implied odds"), o("r2", "Deep stacks делают любую suited hand profitable", "Deep stacks make every suited hand profitable", "DEEP_SUITED_MAGIC"), o("r3", "Implied odds существуют только на flop", "Implied odds exist only on the flop", "IMPLIED_ODDS_STREET_MYTH")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30,
    explanationRu: "Глубина усиливает future-tree considerations, но не превращает suitedness в автоматический continue.",
    explanationEn: "Depth increases future-tree considerations but does not turn suitedness into an automatic continue.",
  },
  {
    id: "PM-PF-10-106", skillId: "PF-10", kind: "changed", sourceRefs: ["FTGU-E05"],
    assumptions: ["same marginal BB call", "rake low -> high"],
    cueRu: "Тот же BB spot; rake меняется с низкого на высокий.", cueEn: "The same BB spot; rake changes from low to high.",
    questionRu: "Как двигается marginal call?", questionEn: "Which way does the marginal call move?",
    actionOptions: [o("a", "К fold", "Toward fold"), o("b", "К call", "Toward call", "RAKE_BACKWARDS"), o("c", "Не меняется", "No change", "RAKE_IGNORED")],
    reasonOptions: [o("r1", "Дополнительный cost сильнее всего бьёт по near-zero EV branch", "The added cost hits a near-zero-EV branch hardest"), o("r2", "Higher rake создаёт больше dead money", "Higher rake creates more dead money", "RAKE_DEAD_MONEY_FALSE"), o("r3", "BB discount отменяет rake", "The BB discount cancels rake", "RAKE_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 20,
    explanationRu: "Это directional adjustment, не точная chart boundary.",
    explanationEn: "This is a directional adjustment, not an exact chart boundary.",
    changedVariables: ["rake"],
  },
  {
    id: "PM-PF-10-107", skillId: "PF-10", kind: "changed", sourceRefs: ["SLC-M01-L03"],
    assumptions: ["same dollar stack", "no straddle -> mandatory straddle"],
    cueRu: "Dollar stack тот же; добавился mandatory straddle.", cueEn: "The dollar stack is unchanged; a mandatory straddle is added.",
    questionRu: "Можно ли считать effective depth неизменной?", questionEn: "Can effective depth be treated as unchanged?",
    actionOptions: [o("a", "Нет", "No"), o("b", "Да", "Yes", "NOMINAL_STACK_ONLY"), o("c", "Да, если Hero не в straddle", "Yes if Hero is not the straddler", "STRADDLE_ROLE_ONLY")],
    reasonOptions: [o("r1", "Working unit и action structure изменились, поэтому тот же dollar stack представляет другое дерево", "The working unit and action structure changed, so the same dollar stack represents a different tree"), o("r2", "Только Hero straddle влияет на depth", "Only Hero's straddle affects depth", "STRADDLE_ROLE_ONLY"), o("r3", "Effective depth — абсолютная сумма долларов", "Effective depth is an absolute dollar amount", "NOMINAL_STACK_ONLY")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25,
    explanationRu: "Straddle — changed geometry node, а не косметическая дополнительная ставка.",
    explanationEn: "A straddle is a changed-geometry node, not a cosmetic extra bet.",
    changedVariables: ["straddle", "working_unit", "action_order"],
  },
  {
    id: "PM-PF-10-108", skillId: "PF-10", kind: "boundary", sourceRefs: ["FTGU-E02", "FTGU-E04", "SLC-M01-L03"],
    assumptions: ["deeper stacks", "same hand"],
    cueRu: "Стол стал глубже.", cueEn: "The table becomes deeper.",
    questionRu: "Верно ли правило «deep = шире продолжать всё suited»?", questionEn: "Is the rule 'deep = continue every suited hand wider' valid?",
    actionOptions: [o("a", "Нет — depth усиливает и upside, и reverse-implied-odds risks", "No — depth increases both upside and reverse-implied-odds risks"), o("b", "Да — suitedness всегда выигрывает от depth", "Yes — suitedness always benefits from depth", "DEEP_SUITED_MAGIC"), o("c", "Да — domination исчезает deep", "Yes — domination disappears deep", "DOMINATION_DISAPPEARS")],
    reasonOptions: [o("r1", "Nut potential/position выигрывают, но dominated one-pair branches могут становиться дороже", "Nut potential/position gain value, but dominated one-pair branches can become more expensive"), o("r2", "Stack depth не меняет future losses", "Stack depth does not change future losses", "DEPTH_IGNORED"), o("r3", "Suited hand всегда имеет достаточные implied odds", "A suited hand always has sufficient implied odds", "IMPLIED_ODDS_GUARANTEE")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30,
    explanationRu: "Depth — не однонаправленное разрешение расширять всё: nut potential, position, domination и future tree меняются вместе.",
    explanationEn: "Depth is not a one-way permission to widen everything: nut potential, position, domination and the future tree change together.",
  },
];
