import type { PracticalDecision } from "./types";

const o = (id: string, textRu: string, textEn: string, misconception?: string) => ({
  id,
  textRu,
  textEn,
  misconception,
});

/**
 * Scenario-diversity closure.
 *
 * Each row adds one independently contextualized recognition scenario to a
 * skill whose prior scored corpus lived entirely inside one generated
 * scenario family. These rows add no new exact frequencies or thresholds;
 * they exercise already-admitted directional mechanisms in a second context.
 */
export const scenarioDiversityClosureDecisions: PracticalDecision[] = [
  {
    id: "PM-FND-04-S2-101",
    skillId: "FND-04",
    kind: "recognition",
    sourceRefs: ["EXT-PC-OUTS-2026", "EXT-PC-OUTS-GUIDE-2023"],
    assumptions: ["draw quality is evaluated against the opponent range", "no exact equity claim"],
    cueRu: "Hero держит ненатсовое флеш-дро. В диапазоне соперника остаются натсовые флеш-дро и сильные готовые руки, поэтому не каждая пика гарантирует лучшую руку.",
    cueEn: "Hero holds a non-nut flush draw. The opponent range still contains nut flush draws and strong made hands, so not every spade guarantees the best hand.",
    questionRu: "Что нужно определить до того, как считать все визуальные улучшения полноценными аутами?",
    questionEn: "What must be identified before treating every visible improvement as a full out?",
    actionOptions: [
      o("a", "Только число оставшихся карт", "Only the number of unseen cards", "RAW_OUT_COUNT"),
      o("b", "Чистые и грязные ауты", "Clean versus dirty outs"),
      o("c", "Только текущий размер банка", "Only the current pot size", "CONTEXT_IGNORED"),
    ],
    reasonOptions: [
      o("r1", "Любая карта, улучшающая Hero, автоматически является полным аутом", "Any card that improves Hero is automatically a full out", "DIRTY_OUT_IGNORED"),
      o("r2", "Качество аута зависит от того, насколько часто улучшение действительно становится лучшей рукой против диапазона", "Out quality depends on how often the improvement actually becomes the best hand against the range"),
      o("r3", "Доминирование имеет значение только на ривере", "Domination matters only on the river", "DOMINATION_IGNORED"),
    ],
    correctActionId: "b",
    correctReasonId: "r2",
    targetSeconds: 20,
    explanationRu: "Сырой подсчёт аутов недостаточен: улучшения, которые не гарантируют лучшую возможную комбинацию, нужно дисконтировать против сильной части диапазона.",
    explanationEn: "Raw out count is insufficient: non-nut or shared improvements need discounting when the opponent can retain or make a stronger hand.",
  },
  {
    id: "PM-BL-07-S2-101",
    skillId: "BL-07",
    kind: "recognition",
    sourceRefs: ["EXT-UP-BVB-CALLER-2019", "EXT-GTOW-SB-SRP-2024"],
    assumptions: ["same BB hand and opponent", "SB open size changes materially"],
    cueRu: "BB защищается против SB open и будет в позиции постфлоп. Та же рука теперь сталкивается не с небольшим, а с заметно более крупным open.",
    cueEn: "BB defends versus an SB open and will have position postflop. The same hand now faces a materially larger open instead of a small one.",
    questionRu: "Какой сигнал меняется первым?",
    questionEn: "Which signal changes first?",
    actionOptions: [
      o("a", "Цена защиты и пограничные calls", "Defense price and fringe calls"),
      o("b", "Позиция BB исчезает", "BB loses postflop position", "POSITION_FALSE"),
      o("c", "SB origin перестаёт иметь значение", "SB range origin stops mattering", "ORIGIN_IGNORED"),
    ],
    reasonOptions: [
      o("r1", "Closing action делает любой размер одинаково дешёвым", "Closing action makes every size equally cheap", "PRICE_IGNORED"),
      o("r2", "Более крупный open ухудшает pot odds; позиция и SB origin сохраняются, но marginal defense сжимается", "A larger open worsens pot odds; position and SB origin remain, but marginal defense contracts"),
      o("r3", "Чем больше open, тем шире нужно коллировать ради большего банка", "The larger the open, the wider BB should call because the pot is bigger", "PRICE_BACKWARDS"),
    ],
    correctActionId: "a",
    correctReasonId: "r2",
    targetSeconds: 18,
    explanationRu: "BvB не отменяет цену: BB сохраняет closing action и позицию, но более крупный open первым убирает пограничные продолжения.",
    explanationEn: "Blind-versus-blind does not erase price: BB keeps closing action and position, but a larger open removes fringe continues first.",
  },
  {
    id: "PM-BL-08-S2-101",
    skillId: "BL-08",
    kind: "recognition",
    sourceRefs: ["EXT-UP-BVB-LIMP-2019", "EXT-GTOW-BVB-LIMP-CALLED-2024"],
    assumptions: ["SB open-limps", "BB has the option to check behind preflop or raise"],
    cueRu: "SB limp. Наблюдения показывают, что SB слишком широко limp-call и редко fold на raise; BB при этом может бесплатно реализовать позицию через check.",
    cueEn: "SB limps. Observations show SB limp-calls too widely and rarely folds to a raise; BB can still realize position for free by checking.",
    questionRu: "Что нужно сравнить перед автоматическим isolation raise?",
    questionEn: "What should be compared before automatically isolation-raising?",
    actionOptions: [
      o("a", "Raise EV против check EV", "Raise EV versus check EV"),
      o("b", "Только факт, что limp выглядит слабым", "Only the fact that the limp looks weak", "LIMP_WEAKNESS_SHORTCUT"),
      o("c", "Только абсолютную силу руки без реакции SB", "Only absolute hand strength without SB's response", "RESPONSE_TREE_IGNORED"),
    ],
    reasonOptions: [
      o("r1", "Limp всегда обязан быть наказан raise", "Every limp must be punished with a raise", "UNIVERSAL_RAISE"),
      o("r2", "Когда folds мало, raise должен зарабатывать value/denial после call; иначе бесплатная позиционная реализация через check может быть лучше", "When folds are scarce, the raise must earn value/denial after a call; otherwise free positional realization through checking can be better"),
      o("r3", "BB теряет позицию, если не рейзит", "BB loses position if it does not raise", "POSITION_FALSE"),
    ],
    correctActionId: "a",
    correctReasonId: "r2",
    targetSeconds: 20,
    explanationRu: "BB не рейзит просто потому, что SB показал limp. Чем меньше fold equity, тем важнее EV ветки после call и сравнительный EV check.",
    explanationEn: "BB does not raise merely because SB limped. As fold equity falls, the called branch and the comparison with checking matter more.",
  },
  {
    id: "PM-W4-DRAW-S2-101",
    skillId: "W4-DRAW-01",
    kind: "recognition",
    sourceRefs: ["FTGU-E09", "EXT-PC-OUTS-GUIDE-2023"],
    assumptions: ["two draws have similar raw out counts", "nut potential and domination differ"],
    cueRu: "Два флеш-дро имеют похожее число сырых аутов. Первое делает натсовый флеш и сохраняет полезные будущие карты; второе — ненатсовое и чаще попадает под доминацию.",
    cueEn: "Two flush draws have a similar raw out count. One makes the nut flush and retains useful future cards; the other is non-nut and more often dominated.",
    questionRu: "Почему эти draws нельзя считать стратегически одинаковыми?",
    questionEn: "Why should these draws not be treated as strategically identical?",
    actionOptions: [
      o("a", "Clean outs, nut potential и domination", "Clean outs, nut potential, and domination"),
      o("b", "Они одинаковы, если сырое число аутов совпадает", "They are identical whenever the raw out count matches", "RAW_OUT_EQUIVALENCE"),
      o("c", "Разница есть только если один draw уже готовая рука", "They differ only if one draw is already a made hand", "DRAW_LABEL_ONLY"),
    ],
    reasonOptions: [
      o("r1", "Одинаковое число аутов гарантирует одинаковый EV", "The same out count guarantees the same EV", "RAW_OUT_EQUIVALENCE"),
      o("r2", "Натсовость и чистота улучшений меняют реализацию и цену будущих second-best branches", "Nut potential and clean improvements change realization and the cost of future second-best branches"),
      o("r3", "Доминирование не влияет на draw decisions", "Domination does not affect draw decisions", "DOMINATION_IGNORED"),
    ],
    correctActionId: "a",
    correctReasonId: "r2",
    targetSeconds: 18,
    explanationRu: "Draw label и raw out count — только начало. Clean/nut potential и domination определяют, насколько улучшения действительно конвертируются в EV.",
    explanationEn: "The draw label and raw out count are only the start. Clean/nut potential and domination determine how reliably improvements convert into EV.",
  },
  {
    id: "PM-TURN-04-S2-101",
    skillId: "TURN-04",
    kind: "recognition",
    sourceRefs: ["SLC-TURN-LEADS"],
    assumptions: ["Hero called flop OOP", "turn materially improves the flop caller's retained strong region"],
    cueRu: "Hero call flop OOP на связанной доске. Тёрн закрывает несколько естественных продолжений flop-caller и заметно усиливает его retained strong region.",
    cueEn: "Hero calls the flop OOP on a connected board. The turn completes several natural flop-caller continues and materially strengthens the caller's retained strong region.",
    questionRu: "Какой сигнал нужно увидеть до решения о turn lead?",
    questionEn: "Which signal must be recognized before considering a turn lead?",
    actionOptions: [
      o("a", "Сдвиг range ownership для lead", "Range-ownership shift for a lead"),
      o("b", "Улучшилась ли конкретная рука Hero — этого достаточно", "Whether Hero's exact hand improved—that alone is enough", "HAND_IMPROVED_LEAD"),
      o("c", "Кто был префлоп-агрессором — этого достаточно", "Who was the preflop aggressor—that alone is enough", "INITIATIVE_ONLY"),
    ],
    reasonOptions: [
      o("r1", "Lead создаётся конкретным range shift, а не фактом улучшения одной руки", "A lead branch is created by a specific range shift, not by one hand improving"),
      o("r2", "Любой completing turn автоматически принадлежит OOP", "Every completing turn automatically belongs to OOP", "RUNOUT_LABEL_SHORTCUT"),
      o("r3", "Flop call запрещает лиды на следующей улице", "A flop call forbids leading the next street", "LINE_RIGIDITY"),
    ],
    correctActionId: "a",
    correctReasonId: "r1",
    targetSeconds: 20,
    explanationRu: "Turn lead — условная ветка: сначала нужен реальный сдвиг ownership/coverage в сохранившихся диапазонах, а не просто улучшение Hero.",
    explanationEn: "A turn lead is conditional: first there must be a real ownership/coverage shift in the surviving ranges, not merely an improvement to Hero's hand.",
  },
  {
    id: "PM-TURN-05-S2-101",
    skillId: "TURN-05",
    kind: "recognition",
    sourceRefs: ["CP-G3-L02", "FTGU-E21"],
    assumptions: ["Hero has a medium-strength showdown hand", "opponent's surviving continue range is tighter than in the baseline branch"],
    cueRu: "У Hero средняя showdown-рука на тёрне. После более сильной предыдущей линии диапазон соперника, дошедший сюда, заметно плотнее обычного.",
    cueEn: "Hero has a medium-strength showdown hand on the turn. After a stronger prior line, the opponent's surviving range is materially tighter than in the baseline branch.",
    questionRu: "Что должно быть доказано до thin/value/protection bet?",
    questionEn: "What must be established before a thin/value/protection bet?",
    actionOptions: [
      o("a", "Что Hero, вероятно, впереди", "That Hero is probably ahead", "AHEAD_EQUALS_VALUE"),
      o("b", "Хуже calls и future branches", "Worse calls and future branches"),
      o("c", "Что Hero ставил предыдущую улицу", "That Hero bet the previous street", "MOMENTUM_AUTOPILOT"),
    ],
    reasonOptions: [
      o("r1", "Thin value определяется calling range и будущими ветками, а не только текущим showdown rank", "Thin value is defined by the calling range and future branches, not only current showdown rank"),
      o("r2", "Если рука чаще впереди, bet обязателен", "If the hand is ahead more often, betting is mandatory", "AHEAD_EQUALS_VALUE"),
      o("r3", "Более сильный surviving range делает thin value автоматически шире", "A stronger surviving range automatically widens thin value", "RANGE_BACKWARDS"),
    ],
    correctActionId: "b",
    correctReasonId: "r1",
    targetSeconds: 20,
    explanationRu: "При более плотном surviving range часть тонких ставок исчезает: нужно назвать хуже calls и учесть raise/river consequences.",
    explanationEn: "Against a tighter surviving range, some thin bets disappear: name the worse calls and account for raise/river consequences.",
  },
  {
    id: "PM-MW-05-S2-101",
    skillId: "MW-05",
    kind: "recognition",
    sourceRefs: ["SLC-MULTIWAY", "EXT-PS-MULTIWAY-2026", "EXT-PS-RIVER-2025"],
    assumptions: ["river remains three-way", "two opponent ranges survived prior multiway filtering"],
    cueRu: "Ривер остаётся 3-way: два диапазона соперников прошли предыдущие улицы и оба всё ещё активны. Hero рассматривает marginal value/bluff-catch.",
    cueEn: "The river remains three-way: two opponent ranges survived the prior streets and both are still active. Hero is considering marginal value or a bluff-catch.",
    questionRu: "Какой сдвиг относительно heads-up нужно распознать первым?",
    questionEn: "Which shift from heads-up should be recognized first?",
    actionOptions: [
      o("a", "Сильнее ranges, меньше bluffs", "Stronger ranges, fewer bluffs"),
      o("b", "Хорошая pot odds автоматически компенсирует дополнительного игрока", "Good pot odds automatically compensate for the extra player", "PRICE_ONLY"),
      o("c", "Multiway не влияет на river thresholds", "Multiway does not affect river thresholds", "HU_THRESHOLD_TRANSFER"),
    ],
    reasonOptions: [
      o("r1", "Multiway river требует конкретнее назвать worse calls и credible bluffs вместо копирования HU threshold", "A multiway river requires more explicit worse-call and credible-bluff accounting instead of copying a heads-up threshold"),
      o("r2", "Дополнительный игрок всегда создаёт больше bluffs", "An extra player always creates more bluffs", "BLUFF_SUPPLY_BACKWARDS"),
      o("r3", "На ривере число диапазонов уже не важно", "The number of ranges no longer matters on the river", "MULTIWAY_IGNORED"),
    ],
    correctActionId: "a",
    correctReasonId: "r1",
    targetSeconds: 20,
    explanationRu: "Multiway filtering делает surviving ranges сильнее в среднем и сокращает естественный bluff supply; HU thresholds нельзя переносить механически.",
    explanationEn: "Multiway filtering generally strengthens surviving ranges and reduces natural bluff supply; heads-up thresholds should not be transferred mechanically.",
  },
  {
    id: "PM-DEEP-02-S2-101",
    skillId: "DEEP-02",
    kind: "recognition",
    sourceRefs: ["EXT-GTOW-DEEP-300-2025", "EXT-GTOW-DEEP-SOLUTIONS-300", "EXT-UP-SET-MINING-300-2025"],
    assumptions: ["same hand family compared at 100bb and 300bb", "position and future leverage remain relevant"],
    cueRu: "Та же hand family играется 300bb вместо 100bb. Hero OOP и после префлоп-решения остаётся много future stack.",
    cueEn: "The same hand family is played at 300bb instead of 100bb. Hero is OOP and a large amount of future stack remains after the preflop decision.",
    questionRu: "Какой фактор становится дороже игнорировать?",
    questionEn: "Which factor becomes more costly to ignore?",
    actionOptions: [
      o("a", "Position и reverse implied odds", "Position and reverse implied odds"),
      o("b", "Только название стартовой руки", "Only the starting hand label", "HAND_LABEL_ONLY"),
      o("c", "Ничего: 100bb branch автоматически переносится на 300bb", "Nothing: the 100bb branch transfers automatically to 300bb", "DEPTH_IGNORED"),
    ],
    reasonOptions: [
      o("r1", "Глубина увеличивает будущий leverage: second-best и OOP ошибки становятся дороже, а nutted/implied-odds potential ценнее", "Depth increases future leverage: second-best and OOP mistakes become more expensive while nutted/implied-odds potential becomes more valuable"),
      o("r2", "Дополнительные стеки влияют только после ривера", "Extra stack depth matters only after the river", "DEPTH_IGNORED"),
      o("r3", "Deep stack всегда означает больше aggression OOP", "Deep stacks always mean more OOP aggression", "DEPTH_AGGRESSION_SHORTCUT"),
    ],
    correctActionId: "a",
    correctReasonId: "r1",
    targetSeconds: 20,
    explanationRu: "300bb усиливают цену position и reverse implied odds; 100bb preflop branch нельзя переносить автоматически.",
    explanationEn: "At 300bb, position and reverse implied odds carry more weight; a 100bb preflop branch should not be transferred automatically.",
  },
  {
    id: "PM-EXP-02-S2-101",
    skillId: "EXP-02",
    kind: "recognition",
    sourceRefs: ["CINJ-E08", "LCM-10"],
    assumptions: ["repeated observations are branch-specific", "small and large river sizes show different responses"],
    cueRu: "Соперник повторяемо слишком широко платит небольшой river sizing, но против крупного sizing новые наблюдения показывают заметно больше folds.",
    cueEn: "The opponent repeatedly calls a small river sizing too widely, while newer observations show materially more folds versus a large sizing.",
    questionRu: "Какой exploit вывод реально поддержан?",
    questionEn: "Which exploit conclusion is actually supported?",
    actionOptions: [
      o("a", "Расширять value во всех river branches", "Widen value in every river branch", "GLOBAL_EXPLOIT"),
      o("b", "Только подтверждённая small-size branch", "Only the evidenced small-size branch"),
      o("c", "Игнорировать sizing: player type важнее", "Ignore sizing because player type matters more", "SIZE_IGNORED"),
    ],
    reasonOptions: [
      o("r1", "Exploit evidence переносится автоматически между sizes", "Exploit evidence transfers automatically across sizes", "GLOBAL_EXPLOIT"),
      o("r2", "Deviation должен оставаться branch-specific и масштабироваться качеством evidence", "The deviation should remain branch-specific and scale with evidence quality"),
      o("r3", "Один light call доказывает station во всех линиях", "One light call proves a station in every line", "SALIENCE_BIAS"),
    ],
    correctActionId: "b",
    correctReasonId: "r2",
    targetSeconds: 20,
    explanationRu: "Подтверждённый overcall на small size не лицензирует тот же value shift на крупном sizing: exploit остаётся локальным к наблюдаемой ветке.",
    explanationEn: "An evidenced overcall versus a small size does not license the same value shift versus a large size; the exploit remains local to the observed branch.",
  },
  {
    id: "PM-EXP-03-S2-101",
    skillId: "EXP-03",
    kind: "recognition",
    sourceRefs: ["CINJ-E01", "CINJ-E03", "FTGU-E24", "LCM-10"],
    assumptions: ["repeated fold evidence exists in one branch", "another street/size is not yet observed"],
    cueRu: "В конкретной turn probe branch есть повторяемый overfold. На ривере и против другого sizing таких наблюдений пока нет.",
    cueEn: "A specific turn-probe branch shows repeated overfolding. There is not yet evidence for the river or for a different sizing.",
    questionRu: "Где заканчивается доказанный bluff exploit?",
    questionEn: "Where does the evidenced bluff exploit stop?",
    actionOptions: [
      o("a", "Только наблюдаемая line/size", "Only the observed line/size"),
      o("b", "Он переносится на все streets против этого игрока", "It transfers to every street against this player", "GLOBAL_EXPLOIT"),
      o("c", "Он доказывает, что весь pool overfolds", "It proves the whole pool overfolds", "POOL_GENERALIZATION"),
    ],
    reasonOptions: [
      o("r1", "Exploit bluffing должен следовать фактическому fold response в конкретной branch и уверенности evidence", "Exploit bluffing should follow actual fold response in the specific branch and the confidence of the evidence"),
      o("r2", "Player label важнее контекста линии", "The player label matters more than line context", "PLAYER_LABEL_SHORTCUT"),
      o("r3", "Один подтверждённый node определяет всю стратегию против соперника", "One confirmed node determines the whole strategy against the opponent", "GLOBAL_EXPLOIT"),
    ],
    correctActionId: "a",
    correctReasonId: "r1",
    targetSeconds: 20,
    explanationRu: "Overfold exploit остаётся привязан к наблюдаемой ветке; перенос на другую street/size требует отдельного evidence.",
    explanationEn: "An overfold exploit remains tied to the observed branch; transferring it to another street or size requires separate evidence.",
  },
  {
    id: "PM-EXP-06-S2-101",
    skillId: "EXP-06",
    kind: "recognition",
    sourceRefs: ["EXT-PC-GAMESEL-2025", "EXT-CP-SEATSEL-2014"],
    assumptions: ["same stakes", "table quality and relative position differ"],
    cueRu: "Два стола одинаковых stakes: на первом большие стеки, но в основном сильные aggressive players; на втором несколько слабых/passive игроков и Hero может сесть с удобной относительной позицией.",
    cueEn: "Two tables have the same stakes: one has big stacks but mostly strong aggressive players; the other has several weak/passive players and offers Hero favorable relative position.",
    questionRu: "Какой сигнал важнее для выбора игры?",
    questionEn: "Which signal matters more for game selection?",
    actionOptions: [
      o("a", "Размер самых больших стеков сам по себе", "The size of the biggest stacks by itself", "STACK_APPEARANCE"),
      o("b", "Состав стола и относительная позиция", "Lineup quality and relative position"),
      o("c", "Внешний стереотип о том, кто выглядит слабее", "A superficial stereotype about who looks weaker", "SUPERFICIAL_PROFILE"),
    ],
    reasonOptions: [
      o("r1", "Table/seat selection меняет attainable hourly EV до конкретной раздачи; stack appearance сам по себе недостаточен", "Table/seat selection changes attainable hourly EV before a specific hand; stack appearance alone is insufficient"),
      o("r2", "Большой стек автоматически означает слабого игрока", "A big stack automatically means a weak player", "STACK_APPEARANCE"),
      o("r3", "Seat position против сильных aggressive игроков не влияет на EV", "Seat position relative to strong aggressive players does not affect EV", "SEAT_POSITION_IGNORED"),
    ],
    correctActionId: "b",
    correctReasonId: "r1",
    targetSeconds: 18,
    explanationRu: "Game/seat EV строится на качестве состава и относительной позиции, а не на размере стеков или поверхностном профайлинге.",
    explanationEn: "Game and seat EV depends on lineup quality and relative position, not on stack size or superficial profiling.",
  },
  {
    id: "PM-BL-09-S2-101",
    skillId: "BL-09",
    kind: "recognition",
    sourceRefs: ["EXT-UP-BVB-LIMP-2019", "EXT-GTOW-BVB-LIMP-CALLED-2024"],
    assumptions: ["SB limped before facing a BB isolation raise", "BB raise construction and size matter"],
    cueRu: "SB limp, BB делает крупнее обычного isolation raise и показывает более value-heavy construction. В исходном limp-range SB всё ещё есть сильные continues и traps.",
    cueEn: "SB limps, BB uses a materially larger isolation raise with a more value-heavy construction. SB's original limp range still contains strong continues and traps.",
    questionRu: "Какой сигнал должен изменить ответ SB?",
    questionEn: "Which signal should change SB's response?",
    actionOptions: [
      o("a", "Limp автоматически означает слабый capped range", "A limp automatically means a weak capped range", "LIMP_CAPPED"),
      o("b", "Размер и состав BB raise", "BB raise size and construction"),
      o("c", "Только факт, что SB уже вложил blind", "Only the fact that SB already posted a blind", "PRICE_ONLY"),
    ],
    reasonOptions: [
      o("r1", "Здоровый limp-range сохраняет сильные continues; более крупный/value-heavy raise сильнее давит на fringe, но не отменяет traps", "A sound limp range retains strong continues; a larger, value-heavy raise pressures the fringe more without eliminating traps"),
      o("r2", "После limp SB всегда обязан fold на raise", "After limping, SB must always fold to a raise", "LIMP_FOLD_ALWAYS"),
      o("r3", "Размер raise не влияет на response range", "Raise size does not affect the response range", "SIZE_IGNORED"),
    ],
    correctActionId: "b",
    correctReasonId: "r1",
    targetSeconds: 19,
    explanationRu: "Limp не делает диапазон автоматически слабым. Ответ SB зависит от цены и состава BB raise, а сильные limp-ветки продолжают защищать диапазон.",
    explanationEn: "A limp does not make the range automatically weak. SB's response depends on BB's price and construction while strong limp branches continue to protect the range.",
  },
  {
    id: "PM-RIV-02-S2-101",
    skillId: "RIV-02",
    kind: "recognition",
    sourceRefs: ["FTGU-E23", "CP-G3-L03"],
    assumptions: ["river line has a credible value region", "two low-showdown bluff candidates differ in blocker effects"],
    cueRu: "На ривере у Hero два low-showdown bluff candidates. Один блокирует естественные folds соперника; другой почти не блокирует folds и лучше согласуется с value ancestry линии.",
    cueEn: "On the river Hero has two low-showdown bluff candidates. One blocks natural folds in the opponent range; the other barely blocks folds and fits the line's value ancestry better.",
    questionRu: "Какой признак делает bluff-кандидата предпочтительнее?",
    questionEn: "Which feature makes the bluff candidate preferable?",
    actionOptions: [
      o("a", "Полезный blocker-профиль", "Useful blocker profile"),
      o("b", "Сам факт, что это missed draw", "Merely being a missed draw", "MISSED_DRAW_AUTOBLUFF"),
      o("c", "Самая крупная карта в руке", "The highest card in Hero's hand", "HAND_RANK_SHORTCUT"),
    ],
    reasonOptions: [
      o("r1", "River bluff candidate должен поддерживать credible value ancestry и не удалять слишком много рук, которые должны fold", "A river bluff candidate should support credible value ancestry and avoid removing too many hands that are supposed to fold"),
      o("r2", "Любой missed draw обязан bluff", "Every missed draw must bluff", "MISSED_DRAW_AUTOBLUFF"),
      o("r3", "Blockers важны только для value bets", "Blockers matter only for value bets", "BLOCKER_IGNORED"),
    ],
    correctActionId: "a",
    correctReasonId: "r1",
    targetSeconds: 20,
    explanationRu: "Хороший river bluff — не любой air: важны низкий showdown value, removal и то, согласуется ли кандидат с value-частью линии.",
    explanationEn: "A good river bluff is not arbitrary air: low showdown value, removal, and consistency with the line's value region all matter.",
  },
  {
    id: "PM-RIV-04-S2-101",
    skillId: "RIV-04",
    kind: "recognition",
    sourceRefs: ["CINJ-E08"],
    assumptions: ["Hero considers a small river block/probe size", "opponent can respond by calling, folding, or raising"],
    cueRu: "Hero рассматривает маленький river block/probe с medium showdown hand. Соперник способен не только call/fold, но и aggressively raise этот sizing.",
    cueEn: "Hero considers a small river block/probe with a medium showdown hand. The opponent can not only call or fold but also raise this sizing aggressively.",
    questionRu: "Что нужно распознать до ставки?",
    questionEn: "What must be recognized before betting?",
    actionOptions: [
      o("a", "Маленький size всегда гарантирует дешёвый showdown", "A small size always guarantees a cheap showdown", "CHEAP_SHOWDOWN_SHORTCUT"),
      o("b", "Цель small bet и raise branch", "Small-bet purpose and raise branch"),
      o("c", "Только абсолютную силу Hero", "Only Hero's absolute hand strength", "HAND_STRENGTH_ONLY"),
    ],
    reasonOptions: [
      o("r1", "Block/probe — это range-and-price tool; если raise branch делает ставку плохой, маленький размер сам по себе её не спасает", "A block/probe is a range-and-price tool; if the raise branch makes the bet poor, the small size does not rescue it by itself"),
      o("r2", "Любая маленькая ставка не может быть raise", "Any small bet cannot be raised", "RAISE_BRANCH_IGNORED"),
      o("r3", "River sizing не меняет continuing range", "River sizing does not change the continuing range", "SIZE_IGNORED"),
    ],
    correctActionId: "b",
    correctReasonId: "r1",
    targetSeconds: 20,
    explanationRu: "Small river bet — не кнопка дешёвого showdown: нужно понимать, кого он таргетит и что происходит против raise.",
    explanationEn: "A small river bet is not a cheap-showdown button: its targets and the raise response branch must be understood.",
  },
  {
    id: "PM-RIV-05-S2-101",
    skillId: "RIV-05",
    kind: "recognition",
    sourceRefs: ["FTGU-E24", "FTGU-E25", "CINJ-E10"],
    assumptions: ["branch-specific river evidence exists", "adjacent branch has not been observed enough"],
    cueRu: "В одном конкретном river branch повторяемые вскрытия указывают на underbluff. На соседнем sizing/line данных почти нет.",
    cueEn: "Repeated revealed hands indicate underbluffing in one specific river branch. There is little evidence for an adjacent sizing or line.",
    questionRu: "Где заканчивается доказанный exploit?",
    questionEn: "Where does the evidenced exploit stop?",
    actionOptions: [
      o("a", "Только подтверждённая branch", "Only the evidenced branch"),
      o("b", "Underbluff переносится на все river spots этого игрока", "Underbluffing transfers to every river spot for this player", "GLOBAL_PLAYER_LABEL"),
      o("c", "Он автоматически описывает весь pool", "It automatically describes the whole pool", "POOL_GENERALIZATION"),
    ],
    reasonOptions: [
      o("r1", "Exploit должен масштабироваться качеством и областью evidence, а не превращаться в глобальный ярлык", "An exploit should scale with the quality and scope of evidence rather than becoming a global label"),
      o("r2", "Один подтверждённый node определяет все river frequencies", "One confirmed node determines every river frequency", "GLOBAL_EXPLOIT"),
      o("r3", "Размер ставки не относится к scope evidence", "Bet size is outside the scope of the evidence", "SIZE_IGNORED"),
    ],
    correctActionId: "a",
    correctReasonId: "r1",
    targetSeconds: 18,
    explanationRu: "Branch-specific underbluff — локальное evidence. Перенос на другой sizing/line без новых наблюдений превращает exploit в stereotype.",
    explanationEn: "Branch-specific underbluffing is local evidence. Transferring it to another size or line without new observations turns an exploit into a stereotype.",
  },
  {
    id: "PM-MW-03-S2-101",
    skillId: "MW-03",
    kind: "recognition",
    sourceRefs: ["SLC-MULTIWAY", "LCM-08"],
    assumptions: ["Hero considers a bluff in a three-way pot", "two opponent ranges can continue"],
    cueRu: "Hero рассматривает bluff в 3-way pot. Один соперник выглядит capped, но второй сохранил сильный continuing range.",
    cueEn: "Hero considers a bluff in a three-way pot. One opponent appears capped, but the second opponent retains a strong continuing range.",
    questionRu: "Какой multiway сигнал нельзя потерять?",
    questionEn: "Which multiway signal must not be lost?",
    actionOptions: [
      o("a", "Достаточно выбить самого слабого соперника", "It is enough to fold out the weakest opponent", "ONE_TARGET_ONLY"),
      o("b", "Все fold targets и общий continue", "All fold targets and combined strength"),
      o("c", "Количество игроков не влияет на bluff EV", "The number of players does not affect bluff EV", "MULTIWAY_IGNORED"),
    ],
    reasonOptions: [
      o("r1", "Multiway bluff требует нескольких fold targets и сталкивается с более сильным aggregate continuing region", "A multiway bluff needs multiple fold targets and faces a stronger aggregate continuing region"),
      o("r2", "Если один range capped, остальные можно игнорировать", "If one range is capped, the others can be ignored", "ONE_TARGET_ONLY"),
      o("r3", "Пот становится больше, поэтому bluff автоматически лучше", "The pot is larger, so bluffing is automatically better", "POT_SIZE_SHORTCUT"),
    ],
    correctActionId: "b",
    correctReasonId: "r1",
    targetSeconds: 20,
    explanationRu: "В multiway недостаточно увидеть один capped range: bluff должен пройти через весь набор активных диапазонов.",
    explanationEn: "In multiway pots, identifying one capped range is not enough: the bluff has to clear the full set of active ranges.",
  },
  {
    id: "PM-MW-04-S2-101",
    skillId: "MW-04",
    kind: "recognition",
    sourceRefs: ["FTGU-E03"],
    assumptions: ["several sticky limpers", "Hero has an implied-odds hand", "heads-up isolation is unlikely"],
    cueRu: "Перед Hero несколько sticky limpers. Большой iso редко создаёт heads-up pot; рука Hero хорошо реализует implied odds в multiway.",
    cueEn: "Several sticky limpers are in front of Hero. A large isolation raise rarely creates a heads-up pot; Hero's hand realizes implied odds well multiway.",
    questionRu: "Какой сигнал отличает этот spot от обычного isolation?",
    questionEn: "Which signal distinguishes this spot from a standard isolation raise?",
    actionOptions: [
      o("a", "Низкий fold equity; multiway почти неизбежен", "Low fold equity; multiway remains likely"),
      o("b", "Сам факт наличия limper всегда требует iso", "The mere presence of a limper always requires an isolation raise", "ISO_AUTOPILOT"),
      o("c", "Количество limpers не влияет на when-called branch", "The number of limpers does not affect the when-called branch", "MULTIWAY_IGNORED"),
    ],
    reasonOptions: [
      o("r1", "Когда iso не покупает heads-up pot, нужно сравнить его цену с меньшим вложением overlimp и качеством multiway realization", "When an isolation raise does not buy a heads-up pot, compare its price with the smaller overlimp investment and multiway realization"),
      o("r2", "Больший raise всегда создаёт достаточно folds", "A larger raise always creates enough folds", "FOLD_EQUITY_ASSUMED"),
      o("r3", "Implied odds hand хуже играет при большем числе соперников по определению", "An implied-odds hand is automatically worse with more opponents", "IMPLIED_ODDS_BACKWARDS"),
    ],
    correctActionId: "a",
    correctReasonId: "r1",
    targetSeconds: 20,
    explanationRu: "Это transfer от обычного iso: если folds мало и multiway почти неизбежен, стоимость крупного raise нужно сравнивать с cheaper entry и реализацией.",
    explanationEn: "This is a transfer from ordinary isolation: when folds are scarce and multiway is likely, compare the cost of the large raise with cheaper entry and realization.",
  },
  {
    id: "PM-DEEP-04-S2-101",
    skillId: "DEEP-04",
    kind: "recognition",
    sourceRefs: ["FTGU-E04", "SLC-PREFLOP-ADJUSTMENTS"],
    assumptions: ["stack depth increases materially", "hand classes differ in nutted potential and domination risk"],
    cueRu: "При переходе со 100bb на 300bb Hero сравнивает suited connected hand в позиции и dominated offsuit broadway OOP.",
    cueEn: "Moving from 100bb to 300bb, Hero compares a suited connected hand in position with a dominated offsuit broadway OOP.",
    questionRu: "Какой deep-stack сигнал различает эти hand classes?",
    questionEn: "Which deep-stack signal separates these hand classes?",
    actionOptions: [
      o("a", "Nutted potential против domination", "Nutted potential versus domination"),
      o("b", "Глубина одинаково улучшает любую playable hand", "Depth improves every playable hand equally", "DEPTH_UNIFORM"),
      o("c", "Только preflop equity без позиции", "Only preflop equity without position", "POSITION_IGNORED"),
    ],
    reasonOptions: [
      o("r1", "Дополнительный future stack усиливает выгоду nutted outcomes и одновременно цену second-best branches, особенно OOP", "Additional future stack increases the upside of nutted outcomes and the cost of second-best branches, especially OOP"),
      o("r2", "Reverse implied odds уменьшаются автоматически с глубиной", "Reverse implied odds automatically shrink with depth", "RIO_BACKWARDS"),
      o("r3", "Position становится менее важной deep", "Position becomes less important when deep", "POSITION_BACKWARDS"),
    ],
    correctActionId: "a",
    correctReasonId: "r1",
    targetSeconds: 20,
    explanationRu: "Deep stack не расширяет всё одинаково: nutted potential и позиция дорожают, а dominated second-best branches могут становиться хуже.",
    explanationEn: "Deep stacks do not improve every hand equally: nutted potential and position gain value while dominated second-best branches can become more costly.",
  },
  {
    id: "PM-EXP-04-S2-101",
    skillId: "EXP-04",
    kind: "recognition",
    sourceRefs: ["FTGU-E22", "FTGU-E24", "FTGU-E25", "CINJ-E02", "LCM-10"],
    assumptions: ["Hero has a bluff-catcher", "price is known", "credible bluff supply differs by line"],
    cueRu: "Hero получает ту же river price в двух линиях. В первой missed draws естественно дошли до ривера; во второй предыдущая линия отфильтровала почти все natural bluffs.",
    cueEn: "Hero receives the same river price in two lines. In the first, missed draws naturally reach the river; in the second, prior action filtered out most natural bluffs.",
    questionRu: "Почему одинаковая price не даёт одинаковый bluff-catch?",
    questionEn: "Why does the same price not imply the same bluff-catch?",
    actionOptions: [
      o("a", "Цена плюс реальный bluff supply", "Price plus credible bluff supply"),
      o("b", "Одинаковая price всегда означает одинаковый call", "The same price always means the same call", "PRICE_ONLY"),
      o("c", "Blockers полностью заменяют анализ bluff supply", "Blockers completely replace bluff-supply analysis", "BLOCKER_ONLY"),
    ],
    reasonOptions: [
      o("r1", "Bluff-catch требует отдельно спросить, какие bluffs реально могли дойти до node; хорошая цена не создаёт bluffs", "A bluff-catch separately requires asking which bluffs could actually reach the node; a good price does not manufacture bluffs"),
      o("r2", "Pot odds автоматически доказывают нужное число bluffs", "Pot odds automatically prove the needed number of bluffs exists", "PRICE_ONLY"),
      o("r3", "Предыдущие streets не влияют на river bluff supply", "Previous streets do not affect river bluff supply", "ANCESTRY_IGNORED"),
    ],
    correctActionId: "a",
    correctReasonId: "r1",
    targetSeconds: 20,
    explanationRu: "Price — только порог. Реальная частота bluff-catch зависит от того, есть ли в конкретной line достаточно правдоподобных bluffs.",
    explanationEn: "Price is only the threshold. The actual bluff-catch decision depends on whether the specific line contains enough credible bluffs.",
  },
  {
    id: "PM-EXP-05-S2-101",
    skillId: "EXP-05",
    kind: "recognition",
    sourceRefs: ["CINJ-E06", "CINJ-E08", "CINJ-E09", "LCM-10"],
    assumptions: ["one repeated sizing tell is well evidenced", "a neighboring line is not yet observed"],
    cueRu: "Есть повторяемый tell: конкретный small block sizing в одном node слишком часто означает слабую region. Про click-back или другой street таких данных нет.",
    cueEn: "A repeated tell is evidenced: a specific small block sizing in one node is too often weak. There is no comparable evidence for click-backs or another street.",
    questionRu: "Как правильно ограничить exploit?",
    questionEn: "How should the exploit be bounded?",
    actionOptions: [
      o("a", "Только подтверждённый size/line", "Only the evidenced size/line"),
      o("b", "Считать любой маленький sizing слабостью во всех spots", "Treat every small sizing as weakness in every spot", "GLOBAL_SIZE_TELL"),
      o("c", "Считать игрока слабым независимо от line", "Label the player weak regardless of the line", "PLAYER_LABEL_SHORTCUT"),
    ],
    reasonOptions: [
      o("r1", "Node-specific leak создаёт EV только в той ветке, где повторяемая ошибка реально наблюдалась", "A node-specific leak creates EV only in the branch where the repeated error was actually observed"),
      o("r2", "Sizing tell универсален между streets", "A sizing tell is universal across streets", "GLOBAL_SIZE_TELL"),
      o("r3", "Один pattern доказывает весь player profile", "One pattern proves the entire player profile", "PLAYER_LABEL_SHORTCUT"),
    ],
    correctActionId: "a",
    correctReasonId: "r1",
    targetSeconds: 18,
    explanationRu: "Exploit остаётся локальным к подтверждённому node. Новый sizing/street — новый вопрос evidence, а не автоматический перенос.",
    explanationEn: "The exploit remains local to the evidenced node. A new size or street requires new evidence rather than automatic transfer.",
  },
];
