import type { PracticalDecision } from "./types";

const o=(id:string,textRu:string,textEn:string,misconception?:string)=>({id,textRu,textEn,misconception});
type F={skillId:string;prefix:string;sourceRefs:string[];nodeRu:string;nodeEn:string;signalRu:string;signalEn:string;defaultRu:string;defaultEn:string;whyRu:string;whyEn:string;changeRu:string;changeEn:string;boundaryRu:string;boundaryEn:string;shortcutRu:string;shortcutEn:string};

function family(f:F):PracticalDecision[]{
 const rows=[
  ["recognition",f.nodeRu,f.nodeEn,"Какой live-specific signal важнее всего?","Which live-specific signal matters most?",f.signalRu,f.signalEn,f.whyRu,f.whyEn],
  ["recognition",`${f.nodeRu} Один structural variable меняется.`,`${f.nodeEn} One structural variable changes.`,"Нужно ли пересчитать tree?","Should the tree be recomputed?","Да — live geometry/context changed","Yes — live geometry/context changed",f.whyRu,f.whyEn],
  ["decision",f.nodeRu,f.nodeEn,"Какой practical default лучше?","Which practical default is better?",f.defaultRu,f.defaultEn,f.whyRu,f.whyEn],
  ["decision",`${f.nodeRu} Shortcut выглядит соблазнительно.`,`${f.nodeEn} A shortcut looks tempting.`,"Что делать?","What should Hero do?","Проверить whole branch EV / remaining ranges","Inspect whole-branch EV / remaining ranges",f.whyRu,f.whyEn],
  ["decision",`${f.nodeRu} Sizing/investment materially changes.`,`${f.nodeEn} Sizing/investment changes materially.`,"Что обновить?","What should be updated?","Price, effective depth, realisation and future SPR","Price, effective depth, realization and future SPR",f.whyRu,f.whyEn],
  ["changed",f.changeRu,f.changeEn,"Как меняется решение?","How does the decision change?","Пересчитать branch; старый default не переносится автоматически","Recompute the branch; do not copy the old default automatically",f.whyRu,f.whyEn],
  ["changed",`${f.nodeRu} Number/strength of opponents increases.`,`${f.nodeEn} The number/strength of opponents increases.`,"Как сдвигается marginal aggressive/value branch?","How does the marginal aggressive/value branch shift?","Tighter / more robust hand requirements","Tighter / more robust hand requirements",f.whyRu,f.whyEn],
  ["boundary",f.boundaryRu,f.boundaryEn,"Где boundary?","Where is the boundary?","Reject universal shortcut; keep source-scoped live mechanism","Reject the universal shortcut; keep the source-scoped live mechanism",f.whyRu,f.whyEn],
 ] as const;
 return rows.map((r,i)=>{
  const [kind,cueRu,cueEn,qRu,qEn,goodRu,goodEn,whyRu,whyEn]=r;
  const slot=i%3; const good=o("good",goodRu,goodEn); const b1=o("b1",f.shortcutRu,f.shortcutEn,"LIVE_SHORTCUT"); const b2=o("b2","Игнорировать players/depth/position","Ignore players/depth/position","CONTEXT_IGNORED");
  const gr=o("goodR",whyRu,whyEn); const br1=o("br1","Heads-up 100bb intuition переносится без изменений","Heads-up 100bb intuition transfers unchanged","HU_100BB_AUTOPILOT"); const br2=o("br2","Exact hand label важнее geometry","The exact hand label matters more than geometry","GEOMETRY_IGNORED");
  return {id:`${f.prefix}-${101+i}`,skillId:f.skillId,kind:kind as PracticalDecision["kind"],sourceRefs:f.sourceRefs,assumptions:["source-scoped live-cash mechanism; no unreviewed exact frequency"],cueRu,cueEn,questionRu:qRu,questionEn:qEn,actionOptions:slot===0?[good,b1,b2]:slot===1?[b1,good,b2]:[b1,b2,good],reasonOptions:slot===0?[br1,gr,br2]:slot===1?[gr,br1,br2]:[br1,br2,gr],correctActionId:"good",correctReasonId:"goodR",targetSeconds:28,explanationRu:whyRu,explanationEn:whyEn,changedVariables:kind==="changed"?["live_context_variable"]:undefined} satisfies PracticalDecision;
 });
}

const families:F[]=[
 {skillId:"MW-01",prefix:"PM-MW-01-A9",sourceRefs:["LCM-08","SLC-MULTIWAY"],nodeRu:"Multiway pot: Hero acts between bettor and one or more players still behind.",nodeEn:"Multiway pot: Hero acts between the bettor and one or more players still behind.",signalRu:"Relative position + who still acts + closing action",signalEn:"Relative position + who still acts + closing action",defaultRu:"Tighten marginal continues/raises when sandwiched; value closing action",defaultEn:"Tighten marginal continues/raises when sandwiched; value closing action",whyRu:"Multiway EV depends on ranges still able to enter after Hero, not just absolute seat position.",whyEn:"Multiway EV depends on ranges still able to enter after Hero, not just absolute seat position.",changeRu:"Same cards/action; Hero changes from sandwiched to closing action.",changeEn:"Same cards/action; Hero changes from sandwiched to closing the action.",boundaryRu:"Learner uses heads-up IP/OOP label and ignores players behind.",boundaryEn:"The learner uses a heads-up IP/OOP label and ignores players behind.",shortcutRu:"Treat as heads-up",shortcutEn:"Treat it as heads-up"},
 {skillId:"MW-02",prefix:"PM-MW-02-A9",sourceRefs:["SLC-MULTIWAY","LCM-08"],nodeRu:"Several ranges continue to flop/turn; Hero has one-pair value candidate.",nodeEn:"Several ranges continue to flop/turn; Hero has a one-pair value candidate.",signalRu:"How many ranges can have strong continues + nut potential",signalEn:"How many ranges can have strong continues + nut potential",defaultRu:"Raise value threshold and prefer robust/nut-potential classes",defaultEn:"Raise the value threshold and prefer robust/nut-potential classes",whyRu:"With more ranges, the probability that one has strong/nutted coverage rises and marginal one-pair value degrades.",whyEn:"With more ranges, the probability that one has strong/nutted coverage rises and marginal one-pair value degrades.",changeRu:"Same hand/board moves heads-up → three-way/four-way.",changeEn:"Same hand/board moves heads-up → three-way/four-way.",boundaryRu:"Learner uses the same top-pair stack-off/value threshold as heads-up.",boundaryEn:"The learner uses the same top-pair stack-off/value threshold as heads-up.",shortcutRu:"Top pair = same value as HU",shortcutEn:"Top pair = same value as HU"},
 {skillId:"MW-03",prefix:"PM-MW-03-A9",sourceRefs:["SLC-MULTIWAY","LCM-08"],nodeRu:"Hero considers bluffing into multiple continuing ranges.",nodeEn:"Hero considers bluffing into multiple continuing ranges.",signalRu:"Number of fold targets + combined continuing strength",signalEn:"Number of fold targets + combined continuing strength",defaultRu:"Suppress marginal bluffs unless leverage/board/range mechanism is strong",defaultEn:"Suppress marginal bluffs unless the leverage/board/range mechanism is strong",whyRu:"A bluff must clear multiple ranges and faces stronger aggregate continuing regions multiway.",whyEn:"A bluff must clear multiple ranges and faces stronger aggregate continuing regions multiway.",changeRu:"Same bluff candidate moves heads-up → multiway with two credible continuing ranges.",changeEn:"Same bluff candidate moves heads-up → multiway with two credible continuing ranges.",boundaryRu:"Learner copies heads-up bluff frequency into multiway.",boundaryEn:"The learner copies heads-up bluff frequency into multiway.",shortcutRu:"Same bluff as HU",shortcutEn:"Use the same bluff as HU"},
 {skillId:"MW-04",prefix:"PM-MW-04-A9",sourceRefs:["FTGU-E03"],nodeRu:"One or more limpers; Hero chooses isolate / overlimp / fold.",nodeEn:"One or more limpers; Hero chooses isolate / overlimp / fold.",signalRu:"Frequent strength + fold equity + position + when-called branch",signalEn:"Frequent strength + fold equity + position + when-called branch",defaultRu:"Iso when value/folds/position support it; overlimp when low investment preserves implied value; fold weak branches",defaultEn:"Isolate when value/folds/position support it; overlimp when low investment preserves implied value; fold weak branches",whyRu:"FTGU-E03 explicitly frames limp decisions through multiple EV branches rather than an automatic isolation rule.",whyEn:"FTGU-E03 explicitly frames limp decisions through multiple EV branches rather than an automatic isolation rule.",changeRu:"Same hand/position; table changes fold-heavy limpers → sticky multiway callers.",changeEn:"Same hand/position; table changes from fold-heavy limpers → sticky multiway callers.",boundaryRu:"Learner automatically raises every playable hand over limpers.",boundaryEn:"The learner automatically raises every playable hand over limpers.",shortcutRu:"Limpers = iso",shortcutEn:"Limpers = isolate"},
 {skillId:"DEEP-01",prefix:"PM-DEEP-01-A9",sourceRefs:["LCM-01","SLC-DEEP-SRP-OOP"],nodeRu:"150–200bb effective with meaningful future streets remaining.",nodeEn:"150–200bb effective with meaningful future streets remaining.",signalRu:"Nut potential + reverse implied odds + leverage + future SPR",signalEn:"Nut potential + reverse implied odds + leverage + future SPR",defaultRu:"Protect against one-pair overcommitment and value robust/nutted runouts more",defaultEn:"Protect against one-pair overcommitment and value robust/nutted runouts more",whyRu:"Audited deep material increases the importance of future-tree leverage and reverse-implied-odds risk.",whyEn:"Audited deep material increases the importance of future-tree leverage and reverse-implied-odds risk.",changeRu:"Same preflop/hand family changes 100bb → 200bb effective.",changeEn:"Same preflop/hand family changes from 100bb → 200bb effective.",boundaryRu:"Learner uses identical stack-off thresholds at 100bb and 200bb.",boundaryEn:"The learner uses identical stack-off thresholds at 100bb and 200bb.",shortcutRu:"One pair plays the same at any depth",shortcutEn:"One pair plays the same at any depth"},
 {skillId:"DEEP-03",prefix:"PM-DEEP-03-A9",sourceRefs:["LCM-01","SLC-PREFLOP-ADJUSTMENTS"],nodeRu:"Mandatory straddle is added; physical stacks are unchanged.",nodeEn:"A mandatory straddle is added; physical stacks are unchanged.",signalRu:"Working blind unit + action order + effective position + post-action SPR",signalEn:"Working blind unit + action order + effective position + post-action SPR",defaultRu:"Recompute the whole tree in straddle units before choosing preflop/postflop heuristics",defaultEn:"Recompute the whole tree in straddle units before choosing preflop/postflop heuristics",whyRu:"The straddle changes the strategic denominator and can compress nominally deep physical stacks.",whyEn:"The straddle changes the strategic denominator and can compress nominally deep physical stacks.",changeRu:"Same table/stack: no-straddle → mandatory straddle.",changeEn:"Same table/stack: no-straddle → mandatory straddle.",boundaryRu:"Learner keeps ordinary-BB depth and position labels unchanged after straddle.",boundaryEn:"The learner keeps ordinary-BB depth and position labels unchanged after the straddle.",shortcutRu:"Straddle only makes pot bigger",shortcutEn:"A straddle only makes the pot bigger"},
 {skillId:"DEEP-04",prefix:"PM-DEEP-04-A9",sourceRefs:["FTGU-E04","SLC-PREFLOP-ADJUSTMENTS"],nodeRu:"Preflop stack depth increases; same candidate call/3-bet/4-bet branch.",nodeEn:"Preflop stack depth increases; same candidate call/3-bet/4-bet branch.",signalRu:"Implied/reverse-implied odds + position + postflop nut potential",signalEn:"Implied/reverse-implied odds + position + postflop nut potential",defaultRu:"Reweight branches directionally; do not copy 100bb action or invent exact deep chart",defaultEn:"Reweight branches directionally; do not copy the 100bb action or invent an exact deep chart",whyRu:"Deeper stacks change future payoff and domination costs, especially for calls and non-nutted holdings.",whyEn:"Deeper stacks change future payoff and domination costs, especially for calls and non-nutted holdings.",changeRu:"Same hand/positions, effective depth materially increases.",changeEn:"Same hand/positions, effective depth materially increases.",boundaryRu:"Learner copies a 100bb chart cell to deep live play as exact authority.",boundaryEn:"The learner copies a 100bb chart cell to deep live play as exact authority.",shortcutRu:"100bb action = deep action",shortcutEn:"100bb action = deep action"},
];

export const liveA9ExpansionDecisions:PracticalDecision[]=families.flatMap(family);
