import type { PracticalDecision } from "./types";

const o = (id: string, textRu: string, textEn: string, misconception?: string) => ({
  id,
  textRu,
  textEn,
  misconception,
});

/**
 * Scenario-diversity closure.
 *
 * Each row adds one independently contextualized recognition scenario to a
 * skill whose prior scored corpus lived entirely inside one generated
 * scenario family. These rows add no new exact frequencies or thresholds;
 * they exercise already-admitted directional mechanisms in a second context.
 */
export const scenarioDiversityClosureDecisions: PracticalDecision[] = [
  {
    id: "PM-FND-04-S2-101",
    skillId: "FND-04",
    kind: "recognition",
    sourceRefs: ["EXT-PC-OUTS-2026", "EXT-PC-OUTS-GUIDE-2023"],
    assumptions: ["draw quality is evaluated against the opponent range", "no exact equity claim"],
    cueRu: "Hero держит ненатсовое флеш-дро. В диапазоне соперника остаются натсовые флеш-дро и сильные готовые руки, поэтому не каждая пика гарантирует лучшую руку.",
    cueEn: "Hero holds a non-nut flush draw. The opponent range still contains nut flush draws and strong made hands, so not every spade guarantees the best hand.",
    questionRu: "Что нужно определить до того, как считать все визуальные улучшения полноценными аутами?",
    questionEn: "What must be identified before treating every visible improvement as a full out?",
    actionOptions: [
      o("a", "Только число оставшихся карт", "Only the number of unseen cards", "RAW_OUT_COUNT"),
      o("b", "Какие ауты чистые, а какие могут сделать вторую лучшую руку", "Which outs are clean and which can still make a second-best hand"),
      o("c", "Только текущий размер банка", "Only the current pot size", "CONTEXT_IGNORED"),
    ],
    reasonOptions: [
      o("r1", "Любая карта, улучшающая Hero, автоматически является полным аутом", "Any card that improves Hero is automatically a full out", "DIRTY_OUT_IGNORED"),
      o("r2", "Качество аута зависит от того, насколько часто улучшение действительно становится лучшей рукой против диапазона", "Out quality depends on how often the improvement actually becomes the best hand against the range"),
      o("r3", "Доминирование имеет значение только на ривере", "Domination matters only on the river", "DOMINATION_IGNORED"),
    ],
    correctActionId: "b",
    correctReasonId: "r2",
    targetSeconds: 20,
    explanationRu: "Сырой out count недостаточен: ненатсовые и общие улучшения нужно дисконтировать, если соперник может сохранить или собрать более сильную комбинацию.",
    explanationEn: "Raw out count is insufficient: non-nut or shared improvements need discounting when the opponent can retain or make a stronger hand.",
  },
  {
    id: "PM-BL-07-S2-101",
    skillId: "BL-07",
    kind: "recognition",
    sourceRefs: ["EXT-UP-BVB-CALLER-2019", "EXT-GTOW-SB-SRP-2024"],
    assumptions: ["same BB hand and opponent", "SB open size changes materially"],
    cueRu: "BB защищается против SB open и будет в позиции постфлоп. Та же рука теперь сталкивается не с небольшим, а с заметно более крупным open.",
    cueEn: "BB defends versus an SB open and will have position postflop. The same hand now faces a materially larger open instead of a small one.",
    questionRu: "Какой сигнал меняется первым?",
    questionEn: "Which signal changes first?",
    actionOptions: [
      o("a", "Цена защиты ухудшается, поэтому пограничные calls уходят первыми", "The defense price worsens, so fringe calls disappear first"),
      o("b", "Позиция BB исчезает", "BB loses postflop position", "POSITION_FALSE"),
      o("c", "SB origin перестаёт иметь значение", "SB range origin stops mattering", "ORIGIN_IGNORED"),
    ],
    reasonOptions: [
      o("r1", "Closing action делает любой размер одинаково дешёвым", "Closing action makes every size equally cheap", "PRICE_IGNORED"),
      o("r2", "Более крупный open ухудшает pot odds; позиция и SB origin сохраняются, но marginal defense сжимается", "A larger open worsens pot odds; position and SB origin remain, but marginal defense contracts"),
      o("r3", "Чем больше open, тем шире нужно коллировать ради большего банка", "The larger the open, the wider BB should call because the pot is bigger", "PRICE_BACKWARDS"),
    ],
    correctActionId: "a",
    correctReasonId: "r2",
    targetSeconds: 18,
    explanationRu: "BvB не отменяет цену: BB сохраняет closing action и позицию, но более крупный open первым убирает пограничные продолжения.",
    explanationEn: "Blind-versus-blind does not erase price: BB keeps closing action and position, but a larger open removes fringe continues first.",
  },
  {
    id: "PM-BL-08-S2-101",
    skillId: "BL-08",
    kind: "recognition",
    sourceRefs: ["EXT-UP-BVB-LIMP-2019", "EXT-GTOW-BVB-LIMP-CALLED-2024"],
    assumptions: ["SB open-limps", "BB has the option to check behind preflop or raise"],
    cueRu: "SB limp. Наблюдения показывают, что SB слишком широко limp-call и редко fold на raise; BB при этом может бесплатно реализовать позицию через check.",
    cueEn: "SB limps. Observations show SB limp-calls too widely and rarely folds to a raise; BB can still realize position for free by checking.",
    questionRu: "Что нужно сравнить перед автоматическим isolation raise?",
    questionEn: "What should be compared before automatically isolation-raising?",
    actionOptions: [
      o("a", "Raise EV против EV бесплатного check с учётом value/fold leverage конкретной руки", "Raise EV versus the free-check EV, including the hand's actual value/fold leverage"),
      o("b", "Только факт, что limp выглядит слабым", "Only the fact that the limp looks weak", "LIMP_WEAKNESS_SHORTCUT"),
      o("c", "Только абсолютную силу руки без реакции SB", "Only absolute hand strength without SB's response", "RESPONSE_TREE_IGNORED"),
    ],
    reasonOptions: [
      o("r1", "Limp всегда обязан быть наказан raise", "Every limp must be punished with a raise", "UNIVERSAL_RAISE"),
      o("r2", "Когда folds мало, raise должен зарабатывать value/denial после call; иначе бесплатная позиционная реализация через check может быть лучше", "When folds are scarce, the raise must earn value/denial after a call; otherwise free positional realization through checking can be better"),
      o("r3", "BB теряет позицию, если не рейзит", "BB loses position if it does not raise", "POSITION_FALSE"),
    ],
    correctActionId: "a",
    correctReasonId: "r2",
    targetSeconds: 20,
    explanationRu: "BB не рейзит просто потому, что SB показал limp. Чем меньше fold equity, тем важнее EV ветки после call и сравнительный EV check.",
    explanationEn: "BB does not raise merely because SB limped. As fold equity falls, the called branch and the comparison with checking matter more.",
  },
  {
    id: "PM-W4-DRAW-S2-101",
    skillId: "W4-DRAW-01",
    kind: "recognition",
    sourceRefs: ["FTGU-E09", "EXT-PC-OUTS-GUIDE-2023"],
    assumptions: ["two draws have similar raw out counts", "nut potential and domination differ"],
    cueRu: "Два флеш-дро имеют похожее число сырых аутов. Первое делает натсовый флеш и сохраняет полезные будущие карты; второе — ненатсовое и чаще попадает под доминацию.",
    cueEn: "Two flush draws have a similar raw out count. One makes the nut flush and retains useful future cards; the other is non-nut and more often dominated.",
    questionRu: "Почему эти draws нельзя считать стратегически одинаковыми?",
    questionEn: "Why should these draws not be treated as strategically identical?",
    actionOptions: [
      o("a", "Потому что качество draw зависит от clean outs, nut potential, domination и showdown value", "Because draw quality depends on clean outs, nut potential, domination, and showdown value"),
      o("b", "Они одинаковы, если сырое число аутов совпадает", "They are identical whenever the raw out count matches", "RAW_OUT_EQUIVALENCE"),
      o("c", "Разница есть только если один draw уже готовая рука", "They differ only if one draw is already a made hand", "DRAW_LABEL_ONLY"),
    ],
    reasonOptions: [
      o("r1", "Одинаковое число аутов гарантирует одинаковый EV", "The same out count guarantees the same EV", "RAW_OUT_EQUIVALENCE"),
      o("r2", "Натсовость и чистота улучшений меняют реализацию и цену будущих second-best branches", "Nut potential and clean improvements change realization and the cost of future second-best branches"),
      o("r3", "Доминирование не влияет на draw decisions", "Domination does not affect draw decisions", "DOMINATION_IGNORED"),
    ],
    correctActionId: "a",
    correctReasonId: "r2",
    targetSeconds: 18,
    explanationRu: "Draw label и raw out count — только начало. Clean/nut potential и domination определяют, насколько улучшения действительно конвертируются в EV.",
    explanationEn: "The draw label and raw out count are only the start. Clean/nut potential and domination determine how reliably improvements convert into EV.",
  },
  {
    id: "PM-TURN-04-S2-101",
    skillId: "TURN-04",
    kind: "recognition",
    sourceRefs: ["SLC-TURN-LEADS"],
    assumptions: ["Hero called flop OOP", "turn materially improves the flop caller's retained strong region"],
    cueRu: "Hero call flop OOP на связанной доске. Тёрн закрывает несколько естественных продолжений flop-caller и заметно усиливает его retained strong region.",
    cueEn: "Hero calls the flop OOP on a connected board. The turn completes several natural flop-caller continues and materially strengthens the caller's retained strong region.",
    questionRu: "Какой сигнал нужно увидеть до решения о turn lead?",
    questionEn: "Which signal must be recognized before considering a turn lead?",
    actionOptions: [
      o("a", "Сдвинулось ли nut/coverage ownership достаточно, чтобы у caller появился source-supported lead branch", "Whether nut/coverage ownership shifted enough to create a source-supported lead branch for the caller"),
      o("b", "Улучшилась ли конкретная рука Hero — этого достаточно", "Whether Hero's exact hand improved—that alone is enough", "HAND_IMPROVED_LEAD"),
      o("c", "Кто был префлоп-агрессором — этого достаточно", "Who was the preflop aggressor—that alone is enough", "INITIATIVE_ONLY"),
    ],
    reasonOptions: [
      o("r1", "Lead создаётся конкретным range shift, а не фактом улучшения одной руки", "A lead branch is created by a specific range shift, not by one hand improving"),
      o("r2", "Любой completing turn автоматически принадлежит OOP", "Every completing turn automatically belongs to OOP", "RUNOUT_LABEL_SHORTCUT"),
      o("r3", "Flop call запрещает лиды на следующей улице", "A flop call forbids leading the next street", "LINE_RIGIDITY"),
    ],
    correctActionId: "a",
    correctReasonId: "r1",
    targetSeconds: 20,
    explanationRu: "Turn lead — условная ветка: сначала нужен реальный сдвиг ownership/coverage в сохранившихся диапазонах, а не просто улучшение Hero.",
    explanationEn: "A turn lead is conditional: first there must be a real ownership/coverage shift in the surviving ranges, not merely an improvement to Hero's hand.",
  },
  {
    id: "PM-TURN-05-S2-101",
    skillId: "TURN-05",
    kind: "recognition",
    sourceRefs: ["CP-G3-L02", "FTGU-E21"],
    assumptions: ["Hero has a medium-strength showdown hand", "opponent's surviving continue range is tighter than in the baseline branch"],
    cueRu: "У Hero средняя showdown-рука на тёрне. После более сильной предыдущей линии диапазон соперника, дошедший сюда, заметно плотнее обычного.",
    cueEn: "Hero has a medium-strength showdown hand on the turn. After a stronger prior line, the opponent's surviving range is materially tighter than in the baseline branch.",
    questionRu: "Что должно быть доказано до thin/value/protection bet?",
    questionEn: "What must be established before a thin/value/protection bet?",
    actionOptions: [
      o("a", "Что Hero, вероятно, впереди", "That Hero is probably ahead", "AHEAD_EQUALS_VALUE"),
      o("b", "Какие хуже руки реально продолжают, что защищается и как выглядят raise/river branches", "Which worse hands actually continue, what needs protection, and how the raise/river branches look"),
      o("c", "Что Hero ставил предыдущую улицу", "That Hero bet the previous street", "MOMENTUM_AUTOPILOT"),
    ],
    reasonOptions: [
      o("r1", "Thin value определяется calling range и будущими ветками, а не только текущим showdown rank", "Thin value is defined by the calling range and future branches, not only current showdown rank"),
      o("r2", "Если рука чаще впереди, bet обязателен", "If the hand is ahead more often, betting is mandatory", "AHEAD_EQUALS_VALUE"),
      o("r3", "Более сильный surviving range делает thin value автоматически шире", "A stronger surviving range automatically widens thin value", "RANGE_BACKWARDS"),
    ],
    correctActionId: "b",
    correctReasonId: "r1",
    targetSeconds: 20,
    explanationRu: "При более плотном surviving range часть тонких ставок исчезает: нужно назвать хуже calls и учесть raise/river consequences.",
    explanationEn: "Against a tighter surviving range, some thin bets disappear: name the worse calls and account for raise/river consequences.",
  },
  {
    id: "PM-MW-05-S2-101",
    skillId: "MW-05",
    kind: "recognition",
    sourceRefs: ["SLC-MULTIWAY", "EXT-PS-MULTIWAY-2026", "EXT-PS-RIVER-2025"],
    assumptions: ["river remains three-way", "two opponent ranges survived prior multiway filtering"],
    cueRu: "Ривер остаётся 3-way: два диапазона соперников прошли предыдущие улицы и оба всё ещё активны. Hero рассматривает marginal value/bluff-catch.",
    cueEn: "The river remains three-way: two opponent ranges survived the prior streets and both are still active. Hero is considering marginal value or a bluff-catch.",
    questionRu: "Какой сдвиг относительно heads-up нужно распознать первым?",
    questionEn: "Which shift from heads-up should be recognized first?",
    actionOptions: [
      o("a", "Дополнительный surviving range обычно усиливает continuing region и уменьшает естественный bluff supply", "An additional surviving range generally strengthens the continuing region and reduces natural bluff supply"),
      o("b", "Хорошая pot odds автоматически компенсирует дополнительного игрока", "Good pot odds automatically compensate for the extra player", "PRICE_ONLY"),
      o("c", "Multiway не влияет на river thresholds", "Multiway does not affect river thresholds", "HU_THRESHOLD_TRANSFER"),
    ],
    reasonOptions: [
      o("r1", "Multiway river требует конкретнее назвать worse calls и credible bluffs вместо копирования HU threshold", "A multiway river requires more explicit worse-call and credible-bluff accounting instead of copying a heads-up threshold"),
      o("r2", "Дополнительный игрок всегда создаёт больше bluffs", "An extra player always creates more bluffs", "BLUFF_SUPPLY_BACKWARDS"),
      o("r3", "На ривере число диапазонов уже не важно", "The number of ranges no longer matters on the river", "MULTIWAY_IGNORED"),
    ],
    correctActionId: "a",
    correctReasonId: "r1",
    targetSeconds: 20,
    explanationRu: "Multiway filtering делает surviving ranges сильнее в среднем и сокращает естественный bluff supply; HU thresholds нельзя переносить механически.",
    explanationEn: "Multiway filtering generally strengthens surviving ranges and reduces natural bluff supply; heads-up thresholds should not be transferred mechanically.",
  },
  {
    id: "PM-DEEP-02-S2-101",
    skillId: "DEEP-02",
    kind: "recognition",
    sourceRefs: ["EXT-GTOW-DEEP-300-2025", "EXT-GTOW-DEEP-SOLUTIONS-300", "EXT-UP-SET-MINING-300-2025"],
    assumptions: ["same hand family compared at 100bb and 300bb", "position and future leverage remain relevant"],
    cueRu: "Та же hand family играется 300bb вместо 100bb. Hero OOP и после префлоп-решения остаётся много future stack.",
    cueEn: "The same hand family is played at 300bb instead of 100bb. Hero is OOP and a large amount of future stack remains after the preflop decision.",
    questionRu: "Какой фактор становится дороже игнорировать?",
    questionEn: "Which factor becomes more costly to ignore?",
    actionOptions: [
      o("a", "Position, nutted potential и reverse-implied-odds в длинном future tree", "Position, nutted potential, and reverse implied odds in the long future tree"),
      o("b", "Только название стартовой руки", "Only the starting hand label", "HAND_LABEL_ONLY"),
      o("c", "Ничего: 100bb branch автоматически переносится на 300bb", "Nothing: the 100bb branch transfers automatically to 300bb", "DEPTH_IGNORED"),
    ],
    reasonOptions: [
      o("r1", "Глубина увеличивает будущий leverage: second-best и OOP ошибки становятся дороже, а nutted/implied-odds potential ценнее", "Depth increases future leverage: second-best and OOP mistakes become more expensive while nutted/implied-odds potential becomes more valuable"),
      o("r2", "Дополнительные стеки влияют только после ривера", "Extra stack depth matters only after the river", "DEPTH_IGNORED"),
      o("r3", "Deep stack всегда означает больше aggression OOP", "Deep stacks always mean more OOP aggression", "DEPTH_AGGRESSION_SHORTCUT"),
    ],
    correctActionId: "a",
    correctReasonId: "r1",
    targetSeconds: 20,
    explanationRu: "300bb усиливают цену position и reverse implied odds; 100bb preflop branch нельзя переносить автоматически.",
    explanationEn: "At 300bb, position and reverse implied odds carry more weight; a 100bb preflop branch should not be transferred automatically.",
  },
  {
    id: "PM-EXP-02-S2-101",
    skillId: "EXP-02",
    kind: "recognition",
    sourceRefs: ["CINJ-E08", "LCM-10"],
    assumptions: ["repeated observations are branch-specific", "small and large river sizes show different responses"],
    cueRu: "Соперник повторяемо слишком широко платит небольшой river sizing, но против крупного sizing новые наблюдения показывают заметно больше folds.",
    cueEn: "The opponent repeatedly calls a small river sizing too widely, while newer observations show materially more folds versus a large sizing.",
    questionRu: "Какой exploit вывод реально поддержан?",
    questionEn: "Which exploit conclusion is actually supported?",
    actionOptions: [
      o("a", "Расширять value во всех river branches", "Widen value in every river branch", "GLOBAL_EXPLOIT"),
      o("b", "Расширить thin value только в подтверждённой small-size branch и заново оценивать крупный sizing", "Widen thin value only in the evidenced small-size branch and re-evaluate the large-size branch"),
      o("c", "Игнорировать sizing: player type важнее", "Ignore sizing because player type matters more", "SIZE_IGNORED"),
    ],
    reasonOptions: [
      o("r1", "Exploit evidence переносится автоматически между sizes", "Exploit evidence transfers automatically across sizes", "GLOBAL_EXPLOIT"),
      o("r2", "Deviation должен оставаться branch-specific и масштабироваться качеством evidence", "The deviation should remain branch-specific and scale with evidence quality"),
      o("r3", "Один light call доказывает station во всех линиях", "One light call proves a station in every line", "SALIENCE_BIAS"),
    ],
    correctActionId: "b",
    correctReasonId: "r2",
    targetSeconds: 20,
    explanationRu: "Подтверждённый overcall на small size не лицензирует тот же value shift на крупном sizing: exploit остаётся локальным к наблюдаемой ветке.",
    explanationEn: "An evidenced overcall versus a small size does not license the same value shift versus a large size; the exploit remains local to the observed branch.",
  },
  {
    id: "PM-EXP-03-S2-101",
    skillId: "EXP-03",
    kind: "recognition",
    sourceRefs: ["CINJ-E01", "CINJ-E03", "FTGU-E24", "LCM-10"],
    assumptions: ["repeated fold evidence exists in one branch", "another street/size is not yet observed"],
    cueRu: "В конкретной turn probe branch есть повторяемый overfold. На ривере и против другого sizing таких наблюдений пока нет.",
    cueEn: "A specific turn-probe branch shows repeated overfolding. There is not yet evidence for the river or for a different sizing.",
    questionRu: "Где заканчивается доказанный bluff exploit?",
    questionEn: "Where does the evidenced bluff exploit stop?",
    actionOptions: [
      o("a", "На границе наблюдаемой line/size/street; соседние branches требуют новых данных", "At the observed line/size/street boundary; adjacent branches require new evidence"),
      o("b", "Он переносится на все streets против этого игрока", "It transfers to every street against this player", "GLOBAL_EXPLOIT"),
      o("c", "Он доказывает, что весь pool overfolds", "It proves the whole pool overfolds", "POOL_GENERALIZATION"),
    ],
    reasonOptions: [
      o("r1", "Exploit bluffing должен следовать фактическому fold response в конкретной branch и уверенности evidence", "Exploit bluffing should follow actual fold response in the specific branch and the confidence of the evidence"),
      o("r2", "Player label важнее контекста линии", "The player label matters more than line context", "PLAYER_LABEL_SHORTCUT"),
      o("r3", "Один подтверждённый node определяет всю стратегию против соперника", "One confirmed node determines the whole strategy against the opponent", "GLOBAL_EXPLOIT"),
    ],
    correctActionId: "a",
    correctReasonId: "r1",
    targetSeconds: 20,
    explanationRu: "Overfold exploit остаётся привязан к наблюдаемой ветке; перенос на другую street/size требует отдельного evidence.",
    explanationEn: "An overfold exploit remains tied to the observed branch; transferring it to another street or size requires separate evidence.",
  },
  {
    id: "PM-EXP-06-S2-101",
    skillId: "EXP-06",
    kind: "recognition",
    sourceRefs: ["EXT-PC-GAMESEL-2025", "EXT-CP-SEATSEL-2014"],
    assumptions: ["same stakes", "table quality and relative position differ"],
    cueRu: "Два стола одинаковых stakes: на первом большие стеки, но в основном сильные aggressive players; на втором несколько слабых/passive игроков и Hero может сесть с удобной относительной позицией.",
    cueEn: "Two tables have the same stakes: one has big stacks but mostly strong aggressive players; the other has several weak/passive players and offers Hero favorable relative position.",
    questionRu: "Какой сигнал важнее для выбора игры?",
    questionEn: "Which signal matters more for game selection?",
    actionOptions: [
      o("a", "Размер самых больших стеков сам по себе", "The size of the biggest stacks by itself", "STACK_APPEARANCE"),
      o("b", "Качество/стиль соперников и относительная позиция, а затем устойчивость игры", "Opponent quality/style and relative position, then the sustainability of the game"),
      o("c", "Внешний стереотип о том, кто выглядит слабее", "A superficial stereotype about who looks weaker", "SUPERFICIAL_PROFILE"),
    ],
    reasonOptions: [
      o("r1", "Table/seat selection меняет attainable hourly EV до конкретной раздачи; stack appearance сам по себе недостаточен", "Table/seat selection changes attainable hourly EV before a specific hand; stack appearance alone is insufficient"),
      o("r2", "Большой стек автоматически означает слабого игрока", "A big stack automatically means a weak player", "STACK_APPEARANCE"),
      o("r3", "Seat position против сильных aggressive игроков не влияет на EV", "Seat position relative to strong aggressive players does not affect EV", "SEAT_POSITION_IGNORED"),
    ],
    correctActionId: "b",
    correctReasonId: "r1",
    targetSeconds: 18,
    explanationRu: "Game/seat EV строится на качестве состава и относительной позиции, а не на размере стеков или поверхностном профайлинге.",
    explanationEn: "Game and seat EV depends on lineup quality and relative position, not on stack size or superficial profiling.",
  },
];
