import type { PracticalDecision } from "./types";

const o = (id: string, textRu: string, textEn: string, misconception?: string) => ({ id, textRu, textEn, misconception });

export const blindDefenceExpansionDecisions: PracticalDecision[] = [
  // BL-01 — BB vs EP/HJ. FTGU-E05.
  {
    id: "PM-BL-01-101", skillId: "BL-01", kind: "recognition", sourceRefs: ["FTGU-E05"], assumptions: ["same weak BB hand", "EP origin range"], cueRu: "BB против EP open.", cueEn: "BB versus an EP open.", questionRu: "Что обычно ухудшает weak high-card defend?", questionEn: "What usually worsens a weak high-card defend?",
    actionOptions: [o("a", "Больше domination и strong-overpair density", "More domination and strong-overpair density"), o("b", "Closing action", "Closing the action", "BENEFIT_AS_COST"), o("c", "Posted blind", "The posted blind", "BENEFIT_AS_COST")],
    reasonOptions: [o("r1", "Concentrated EP range сильнее на top-pair/overpair branches", "A concentrated EP range is stronger on top-pair/overpair branches"), o("r2", "EP range всегда шире BTN", "EP range is always wider than BTN", "ORIGIN_BACKWARDS"), o("r3", "Origin range не влияет defend", "Origin range does not affect defense", "ORIGIN_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 20, explanationRu: "FTGU-E05 отдельно подчёркивает ухудшение dominated weak top-pair holdings против concentrated early ranges.", explanationEn: "FTGU-E05 specifically emphasizes the deterioration of dominated weak top-pair holdings versus concentrated early ranges.",
  },
  {
    id: "PM-BL-01-102", skillId: "BL-01", kind: "recognition", sourceRefs: ["FTGU-E05"], assumptions: ["BB closes action", "EP open"], cueRu: "BB всё ещё получает discount и closing action, но opener EP.", cueEn: "BB still gets a discount and closes the action, but the opener is EP.", questionRu: "Как правильно объединить факторы?", questionEn: "How should the factors be combined?",
    actionOptions: [o("a", "Price помогает, но stronger origin range сужает fringe", "Price helps, but the stronger origin range tightens the fringe"), o("b", "Price полностью отменяет range strength", "Price completely overrides range strength", "PRICE_ONLY"), o("c", "EP position автоматически запрещает all calls", "EP position automatically forbids all calls", "POSITION_ABSOLUTE")],
    reasonOptions: [o("r1", "BB defence is multi-factor: price/closing action versus origin strength/realisation", "BB defense is multi-factor: price/closing action versus origin strength/realization"), o("r2", "Only position label matters", "Only the position label matters", "POSITION_ONLY"), o("r3", "Only price matters", "Only price matters", "PRICE_ONLY")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25, explanationRu: "FTGU-E05 одновременно учитывает favorable price и stronger EP range; ни один фактор не является абсолютным.", explanationEn: "FTGU-E05 accounts for both favorable price and the stronger EP range; neither factor is absolute.",
  },
  {
    id: "PM-BL-01-103", skillId: "BL-01", kind: "decision", sourceRefs: ["FTGU-E05"], assumptions: ["BB fringe defend", "EP open", "high rake"], cueRu: "Пограничная защита BB против EP, рейк высокий.", cueEn: "A fringe BB defend versus EP in high rake.", questionRu: "Каким должно быть базовое направление?", questionEn: "What is the default direction?",
    actionOptions: [o("a", "Tighter / чаще fold", "Tighter / fold more often"), o("b", "Wider / чаще call", "Wider / call more often", "RAKE_BACKWARDS"), o("c", "Rake не влияет", "Rake does not matter", "RAKE_IGNORED")],
    reasonOptions: [o("r1", "Strong origin range + rake сильнее давят на marginal realisation", "A strong origin range plus rake pressures marginal realization more"), o("r2", "Rake improves pot odds", "Rake improves pot odds", "RAKE_BACKWARDS"), o("r3", "EP gives BB position", "EP gives BB position", "POSITION_FALSE")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25, explanationRu: "FTGU-E05 прямо говорит, что high rake может перевести marginal calls из profitable в unprofitable.", explanationEn: "FTGU-E05 explicitly says high rake can turn marginal calls from profitable to unprofitable.",
  },
  {
    id: "PM-BL-01-104", skillId: "BL-01", kind: "decision", sourceRefs: ["FTGU-E05"], assumptions: ["BB hand with poor top-pair domination profile", "HJ open"], cueRu: "BB hand часто делает dominated one-pair против HJ range.", cueEn: "The BB hand often makes dominated one-pair holdings versus the HJ range.", questionRu: "Что важнее красивой suitedness/hand label?", questionEn: "What matters more than attractive suitedness/hand labels?",
    actionOptions: [o("a", "Practical realisation versus the actual origin range", "Practical realization versus the actual origin range"), o("b", "Whether the hand looks playable", "Whether the hand looks playable", "PLAYABLE_LOOKS"), o("c", "Always closing action", "Always closing the action", "SINGLE_FACTOR")],
    reasonOptions: [o("r1", "Domination and future pressure can erase nominal equity", "Domination and future pressure can erase nominal equity"), o("r2", "Suited hands cannot be dominated", "Suited hands cannot be dominated", "DOMINATION_FALSE"), o("r3", "Closing action guarantees postflop realization", "Closing the action guarantees postflop realization", "REALISATION_GUARANTEE")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25, explanationRu: "FTGU-E05 teaches BB defence through realisable equity, not through a visual-playability shortcut.", explanationEn: "FTGU-E05 teaches BB defense through realizable equity rather than a visual-playability shortcut.",
  },
  {
    id: "PM-BL-01-105", skillId: "BL-01", kind: "decision", sourceRefs: ["FTGU-E05"], assumptions: ["same open size", "EP opener range unexpectedly wide by evidence"], cueRu: "EP label тот же, но evidence показывает существенно wider-than-default opening range.", cueEn: "The EP label is unchanged, but evidence shows a materially wider-than-default opening range.", questionRu: "Как меняется логика пограничной защиты?", questionEn: "How does fringe-defense logic change?",
    actionOptions: [o("a", "Можно пересмотреть в сторону wider defence", "It can be reconsidered toward wider defense"), o("b", "Position label запрещает adjustment", "The position label forbids adjustment", "LABEL_AS_LAW"), o("c", "Нужно автоматически defend any two", "Automatically defend any two", "OVERADJUST")],
    reasonOptions: [o("r1", "Source logic depends on actual origin-range strength, not the seat label alone", "Source logic depends on actual origin-range strength, not the seat label alone"), o("r2", "Observed evidence never matters", "Observed evidence never matters", "EVIDENCE_IGNORED"), o("r3", "Wider range guarantees Hero favourite", "A wider range guarantees Hero is the favorite", "FAVOURITE_SHORTCUT")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30, explanationRu: "FTGU-E05 mechanism is range-based; position is a prior for origin strength, not an immutable law.", explanationEn: "FTGU-E05 is range-based; position is a prior for origin strength, not an immutable law.",
  },
  {
    id: "PM-BL-01-106", skillId: "BL-01", kind: "changed", sourceRefs: ["FTGU-E05"], assumptions: ["same BB hand/size", "opener moves HJ -> UTG/EP"], cueRu: "Та же hand и sizing, opener сдвигается HJ → более ранняя позиция.", cueEn: "Same hand and sizing, opener moves from HJ to earlier position.", questionRu: "Как двигается пограничный колл?", questionEn: "How does the fringe call move?",
    actionOptions: [o("a", "Tighter", "Tighter"), o("b", "Wider", "Wider", "ORIGIN_BACKWARDS"), o("c", "Unchanged", "Unchanged", "ORIGIN_IGNORED")],
    reasonOptions: [o("r1", "Earlier origin range is typically more concentrated, increasing domination/overpair density", "An earlier origin range is typically more concentrated, increasing domination/overpair density"), o("r2", "Earlier position means fewer strong hands", "Earlier position means fewer strong hands", "ORIGIN_BACKWARDS"), o("r3", "Position never changes range", "Position never changes range", "POSITION_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 20, explanationRu: "Это explicit directional comparison FTGU-E05.", explanationEn: "This is an explicit directional comparison from FTGU-E05.", changedVariables: ["opener_position", "origin_range_strength"],
  },
  {
    id: "PM-BL-01-107", skillId: "BL-01", kind: "boundary", sourceRefs: ["FTGU-E05"], assumptions: ["very small open", "very wide evidence-based EP range"], cueRu: "Необычный EP игрок открывает очень широко и маленьким size.", cueEn: "An unusual EP player opens very wide for a small size.", questionRu: "Нужно ли слепо применять generic tight-vs-EP heuristic?", questionEn: "Should the generic tight-vs-EP heuristic be applied blindly?",
    actionOptions: [o("a", "Нет — actual range/price могут изменить branch", "No — actual range/price can change the branch"), o("b", "Да, seat label всегда главнее evidence", "Yes, the seat label always overrides evidence", "LABEL_AS_LAW"), o("c", "Да, open size не важен", "Yes, open size is irrelevant", "SIZE_IGNORED")],
    reasonOptions: [o("r1", "Source mechanism is price + origin range + realization, not a fixed positional command", "The source mechanism is price + origin range + realization, not a fixed positional command"), o("r2", "EP hands are physically stronger", "EP hands are physically stronger", "POSITION_MAGIC"), o("r3", "Observed tendencies cannot update priors", "Observed tendencies cannot update priors", "EVIDENCE_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30, explanationRu: "Boundary не отменяет baseline: она показывает, что actual evidence and price могут изменить positional prior.", explanationEn: "The boundary does not erase the baseline: it shows that actual evidence and price can change the positional prior.",
  },

  // BL-02 — BB vs CO. FTGU-E05.
  {
    id: "PM-BL-02-101", skillId: "BL-02", kind: "recognition", sourceRefs: ["FTGU-E05"], assumptions: ["CO open", "BB closes action"], cueRu: "BB vs CO open.", cueEn: "BB versus a CO open.", questionRu: "Как CO обычно sits between EP and BTN in origin strength?", questionEn: "How does CO usually sit between EP and BTN in origin strength?",
    actionOptions: [o("a", "Промежуточно: шире EP, уже BTN", "Intermediate: wider than EP, tighter than BTN"), o("b", "Всегда сильнее EP", "Always stronger than EP", "POSITION_BACKWARDS"), o("c", "Идентично BTN", "Identical to BTN", "POSITION_COLLAPSE")],
    reasonOptions: [o("r1", "Opening ranges widen gradually toward later positions", "Opening ranges widen gradually toward later positions"), o("r2", "All late positions are identical", "All late positions are identical", "POSITION_COLLAPSE"), o("r3", "CO has more players behind than EP", "CO has more players behind than EP", "PLAYER_COUNT_BACKWARDS")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 20, explanationRu: "FTGU-E02/E05 framework делает position a gradual range-strength variable, not binary early/late.", explanationEn: "The FTGU-E02/E05 framework treats position as a gradual range-strength variable, not a binary early/late label.",
  },
  {
    id: "PM-BL-02-102", skillId: "BL-02", kind: "recognition", sourceRefs: ["FTGU-E05"], assumptions: ["CO open small", "BB closes action"], cueRu: "CO small open, BB закрывает action.", cueEn: "CO opens small and BB closes the action.", questionRu: "Какие два factors непосредственно улучшают price branch?", questionEn: "Which two factors directly improve the price branch?",
    actionOptions: [o("a", "Small sizing + blind already invested", "Small sizing + blind already invested"), o("b", "CO label + card color", "CO label + card color", "IRRELEVANT_FACTORS"), o("c", "High rake + poor execution", "High rake + poor execution", "BACKWARDS_FACTORS")],
    reasonOptions: [o("r1", "They reduce the incremental cost relative to pot while action closes", "They reduce the incremental cost relative to the pot while action closes"), o("r2", "They guarantee equity realization", "They guarantee equity realization", "REALISATION_GUARANTEE"), o("r3", "They make Hero IP", "They make Hero IP", "POSITION_FALSE")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 20, explanationRu: "FTGU-E05 uses blind discount and small open size as direct reasons BB can continue wider than ordinary cold callers.", explanationEn: "FTGU-E05 uses the blind discount and small open size as direct reasons the BB can continue wider than ordinary cold callers.",
  },
  {
    id: "PM-BL-02-103", skillId: "BL-02", kind: "decision", sourceRefs: ["FTGU-E05"], assumptions: ["CO range not extremely wide", "marginal dominated hand", "high rake"], cueRu: "CO open, marginal dominated BB hand, high rake.", cueEn: "CO open, marginal dominated BB hand, high rake.", questionRu: "Что делать с thin defend?", questionEn: "What should happen to the thin defend?",
    actionOptions: [o("a", "Склоняться к fold", "Lean toward fold"), o("b", "Call because BB always gets price", "Call because BB always gets a price", "PRICE_ONLY"), o("c", "3-bet because dominated", "3-bet because it is dominated", "AGGRESSION_AUTOPILOT")],
    reasonOptions: [o("r1", "Rake + domination can erase a marginal price advantage", "Rake + domination can erase a marginal price advantage"), o("r2", "Rake increases realization", "Rake increases realization", "RAKE_BACKWARDS"), o("r3", "Domination improves when OOP", "Domination improves when OOP", "POSITION_BACKWARDS")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25, explanationRu: "FTGU-E05 makes thin BB calls conditional on rake and practical realisation.", explanationEn: "FTGU-E05 makes thin BB calls conditional on rake and practical realization.",
  },
  {
    id: "PM-BL-02-104", skillId: "BL-02", kind: "decision", sourceRefs: ["FTGU-E05"], assumptions: ["CO small open", "playable hand", "low rake", "Hero competent"], cueRu: "CO small open, playable BB hand, low rake, Hero competent postflop.", cueEn: "CO small open, playable BB hand, low rake, Hero competent postflop.", questionRu: "Что поддерживает defend?", questionEn: "What supports defending?",
    actionOptions: [o("a", "Price + closing action + enough realisation", "Price + closing action + enough realization"), o("b", "Hand must be favourite", "The hand must be a favorite", "FAVOURITE_REQUIREMENT"), o("c", "Any suited hand automatically", "Any suited hand automatically", "ANY_SUITED")],
    reasonOptions: [o("r1", "A call only needs to outperform the EV of folding the posted blind", "A call only needs to outperform the EV of folding the posted blind"), o("r2", "Call must win most pots", "A call must win most pots", "WIN_RATE_50_SHORTCUT"), o("r3", "Closing action guarantees profit", "Closing action guarantees profit", "GUARANTEE_FALSE")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25, explanationRu: "FTGU-E05 rejects win-most-pots intuition and compares call to the automatic loss of folding.", explanationEn: "FTGU-E05 rejects win-most-pots intuition and compares the call with the automatic loss from folding.",
  },
  {
    id: "PM-BL-02-105", skillId: "BL-02", kind: "changed", sourceRefs: ["FTGU-E05"], assumptions: ["same BB hand", "CO open size 2.2x -> 4x"], cueRu: "Та же hand; CO open резко увеличивается.", cueEn: "Same hand; the CO open becomes much larger.", questionRu: "Как двигается пограничный колл?", questionEn: "How does the fringe call move?",
    actionOptions: [o("a", "Tighter", "Tighter"), o("b", "Wider", "Wider", "PRICE_BACKWARDS"), o("c", "No change", "No change", "SIZE_IGNORED")],
    reasonOptions: [o("r1", "Worse price raises the realisable-equity requirement", "A worse price raises the realizable-equity requirement"), o("r2", "Bigger size gives Hero a discount", "A bigger size gives Hero a discount", "PRICE_BACKWARDS"), o("r3", "Open size does not enter pot odds", "Open size does not enter pot odds", "SIZE_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 18, explanationRu: "FTGU-E05 explicitly makes open size a BB defence variable.", explanationEn: "FTGU-E05 explicitly makes open size a BB-defense variable.", changedVariables: ["open_size", "price"],
  },
  {
    id: "PM-BL-02-106", skillId: "BL-02", kind: "changed", sourceRefs: ["FTGU-E05"], assumptions: ["same BB hand/size", "CO range gets wider by evidence"], cueRu: "Hand/size те же, CO evidence-based range становится шире.", cueEn: "Hand/size are unchanged, but the evidence-based CO range becomes wider.", questionRu: "Как меняется marginal defend?", questionEn: "How does the marginal defend change?",
    actionOptions: [o("a", "Может стать лучше", "It can improve"), o("b", "Всегда хуже", "Always worse", "ORIGIN_BACKWARDS"), o("c", "Range width irrelevant", "Range width is irrelevant", "RANGE_IGNORED")],
    reasonOptions: [o("r1", "Wider origin range reduces domination/strength pressure on fringe", "A wider origin range reduces domination/strength pressure on the fringe"), o("r2", "Wider range always has more premiums", "A wider range always has more premiums", "RANGE_BACKWARDS"), o("r3", "BB call sees only own cards", "A BB call considers only Hero's cards", "RANGE_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 22, explanationRu: "FTGU-E05 compares BB hand viability across stronger versus wider origin ranges.", explanationEn: "FTGU-E05 compares BB-hand viability across stronger versus wider origin ranges.", changedVariables: ["origin_range_width"],
  },
  {
    id: "PM-BL-02-107", skillId: "BL-02", kind: "boundary", sourceRefs: ["FTGU-E05"], assumptions: ["excellent price", "Hero very poor OOP execution"], cueRu: "CO даёт отличную цену, но Hero систематически overfold/misplays postflop OOP.", cueEn: "CO offers an excellent price, but Hero systematically overfolds/misplays postflop OOP.", questionRu: "Можно ли считать every theoretical marginal defend practically valid?", questionEn: "Can every theoretical marginal defend be treated as practically valid?",
    actionOptions: [o("a", "Нет", "No"), o("b", "Да, price guarantees EV", "Yes, price guarantees EV", "PRICE_ONLY"), o("c", "Да, skill never matters", "Yes, skill never matters", "EXECUTION_IGNORED")],
    reasonOptions: [o("r1", "FTGU-E05 explicitly allows execution quality to remove marginal calls", "FTGU-E05 explicitly allows execution quality to remove marginal calls"), o("r2", "Raw equity always fully realises", "Raw equity always fully realizes", "FULL_REALISATION"), o("r3", "BB always closes postflop action", "BB always closes postflop action", "POSITION_FALSE")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30, explanationRu: "Source boundary: theoretical price is not enough when practical equity realisation collapses.", explanationEn: "Source boundary: theoretical price is not enough when practical equity realization collapses.",
  },

  // BL-03 — BB vs BTN. FTGU-E05 + SLC BB-vs-BTN source group for later postflop context.
  {
    id: "PM-BL-03-101", skillId: "BL-03", kind: "recognition", sourceRefs: ["FTGU-E05"], assumptions: ["BTN wide open", "small sizing", "BB closes action"], cueRu: "BTN wide open + small size, BB closes action.", cueEn: "BTN wide open + small size, BB closes the action.", questionRu: "Почему BB fringe имеет больше воздуха для defend?", questionEn: "Why does the BB fringe have more room to defend?",
    actionOptions: [o("a", "Better price versus wider origin range", "Better price versus a wider origin range"), o("b", "BTN never has premiums", "BTN never has premiums", "RANGE_ABSOLUTE"), o("c", "BB becomes IP", "BB becomes IP", "POSITION_FALSE")],
    reasonOptions: [o("r1", "Small opens and wide ranges lower required realizable equity", "Small opens and wide ranges lower required realizable equity"), o("r2", "Wide means weak every combo", "Wide means every combo is weak", "RANGE_MISREAD"), o("r3", "Closing action gives postflop position", "Closing the action gives postflop position", "POSITION_FALSE")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 20, explanationRu: "FTGU-E05 directly links small opens, wide ranges and closing action to wider BB defence.", explanationEn: "FTGU-E05 directly links small opens, wide ranges and closing the action to wider BB defense.",
  },
  {
    id: "PM-BL-03-102", skillId: "BL-03", kind: "recognition", sourceRefs: ["FTGU-E05"], assumptions: ["BTN open", "weak top-pair prone hand"], cueRu: "BB hand часто делает weak top pair.", cueEn: "The BB hand often makes weak top pair.", questionRu: "Против какой origin range такой hand family обычно реализует лучше?", questionEn: "Against which origin range does this hand family usually realize better?",
    actionOptions: [o("a", "Wider BTN range", "A wider BTN range"), o("b", "Concentrated EP range", "A concentrated EP range", "ORIGIN_BACKWARDS"), o("c", "Both identically", "Both identically", "ORIGIN_IGNORED")],
    reasonOptions: [o("r1", "Wider range reduces domination/overpair concentration relative to EP", "A wider range reduces domination/overpair concentration relative to EP"), o("r2", "BTN cannot make top pair", "BTN cannot make top pair", "RANGE_FALSE"), o("r3", "Origin range never affects pair value", "Origin range never affects pair value", "RANGE_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 22, explanationRu: "FTGU-E05 uses exactly this relative comparison to explain weak-hand viability from BB.", explanationEn: "FTGU-E05 uses this relative comparison to explain weak-hand viability from the BB.",
  },
  {
    id: "PM-BL-03-103", skillId: "BL-03", kind: "decision", sourceRefs: ["FTGU-E05"], assumptions: ["BTN wide small open", "BB playable marginal hand", "normal rake"], cueRu: "Wide small BTN open, marginal but playable BB hand.", cueEn: "Wide small BTN open, marginal but playable BB hand.", questionRu: "Какая ошибка наиболее типична?", questionEn: "Which error is most typical?",
    actionOptions: [o("a", "Overfold because hand is behind BTN range", "Overfold because the hand is behind the BTN range"), o("b", "Recognize call can beat folding despite losing often", "Recognize the call can beat folding despite losing often"), o("c", "Assume any two must defend", "Assume any two cards must defend", "ANY_TWO")],
    reasonOptions: [o("r1", "The correct baseline compares call EV with the posted-blind loss of folding", "The correct baseline compares call EV with the posted-blind loss of folding"), o("r2", "A defend must win most pots", "A defend must win most pots", "WIN_RATE_50_SHORTCUT"), o("r3", "BTN range is always air", "The BTN range is always air", "RANGE_ABSOLUTE")],
    correctActionId: "b", correctReasonId: "r1", targetSeconds: 25, explanationRu: "FTGU-E05 explicitly rejects the intuition that a BB call must be 'more good than bad' in isolation.", explanationEn: "FTGU-E05 explicitly rejects the intuition that a BB call must be 'more good than bad' in isolation.",
  },
  {
    id: "PM-BL-03-104", skillId: "BL-03", kind: "decision", sourceRefs: ["FTGU-E05"], assumptions: ["BTN wide open", "BB hand poor playability", "Hero weak OOP execution"], cueRu: "BTN wide, но hand плохо реализует equity и Hero слаб OOP.", cueEn: "BTN is wide, but the hand realizes equity poorly and Hero is weak OOP.", questionRu: "Что делать с theoretical fringe?", questionEn: "What should happen to the theoretical fringe?",
    actionOptions: [o("a", "Сохранять весь range любой ценой", "Keep the whole range at any cost", "THEORY_LITERALISM"), o("b", "Допустить tighter practical defence", "Allow a tighter practical defense"), o("c", "3-bet every fringe hand", "3-bet every fringe hand", "AGGRESSION_AUTOPILOT")],
    reasonOptions: [o("r1", "Poor execution can remove marginal calls even versus a wide range", "Poor execution can remove marginal calls even versus a wide range"), o("r2", "Wide BTN guarantees realization", "A wide BTN range guarantees realization", "REALISATION_GUARANTEE"), o("r3", "Execution only matters on river", "Execution matters only on the river", "EXECUTION_IGNORED")],
    correctActionId: "b", correctReasonId: "r1", targetSeconds: 28, explanationRu: "FTGU-E05 makes player skill a practical EV input for marginal BB calls.", explanationEn: "FTGU-E05 makes player skill a practical EV input for marginal BB calls.",
  },
  {
    id: "PM-BL-03-105", skillId: "BL-03", kind: "decision", sourceRefs: ["FTGU-E05"], assumptions: ["BTN open", "very high rake", "thin defend"], cueRu: "BTN open, very high rake, thin BB defend.", cueEn: "BTN open, very high rake, thin BB defend.", questionRu: "Какой adjustment разумен?", questionEn: "Which adjustment is reasonable?",
    actionOptions: [o("a", "Tighten marginal calls", "Tighten marginal calls"), o("b", "Widen because rake adds dead money", "Widen because rake adds dead money", "RAKE_BACKWARDS"), o("c", "Ignore rake", "Ignore rake", "RAKE_IGNORED")],
    reasonOptions: [o("r1", "Rake subtracts EV and hits thin calls first", "Rake subtracts EV and hits thin calls first"), o("r2", "Rake is paid only by BTN", "Rake is paid only by BTN", "RAKE_FALSE"), o("r3", "Rake affects only preflop raiser", "Rake affects only the preflop raiser", "RAKE_FALSE")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 20, explanationRu: "FTGU-E05 explicitly notes that rake can turn marginal BB calls unprofitable.", explanationEn: "FTGU-E05 explicitly notes that rake can turn marginal BB calls unprofitable.",
  },
  {
    id: "PM-BL-03-106", skillId: "BL-03", kind: "changed", sourceRefs: ["FTGU-E05"], assumptions: ["same BB hand", "BTN sizing small -> large"], cueRu: "BTN range та же, но sizing становится намного больше.", cueEn: "BTN range is unchanged, but sizing becomes much larger.", questionRu: "Как меняется defend?", questionEn: "How does the defense change?",
    actionOptions: [o("a", "Tighter", "Tighter"), o("b", "Wider", "Wider", "PRICE_BACKWARDS"), o("c", "Unchanged", "Unchanged", "SIZE_IGNORED")],
    reasonOptions: [o("r1", "Worse price raises the required realizable equity", "A worse price raises the required realizable equity"), o("r2", "Bigger open gives better price", "A bigger open gives a better price", "PRICE_BACKWARDS"), o("r3", "BTN width cancels sizing", "BTN width cancels sizing", "SINGLE_FACTOR")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 18, explanationRu: "Open size remains an independent BB defence variable even against a wide BTN range.", explanationEn: "Open size remains an independent BB-defense variable even versus a wide BTN range.", changedVariables: ["open_size"],
  },
  {
    id: "PM-BL-03-107", skillId: "BL-03", kind: "boundary", sourceRefs: ["FTGU-E05"], assumptions: ["BTN extremely tight by evidence", "seat label still BTN"], cueRu: "BTN seat, но player evidence показывает unusually tight opening range.", cueEn: "BTN seat, but player evidence shows an unusually tight opening range.", questionRu: "Нужно ли сохранять default wide-vs-BTN defence?", questionEn: "Should the default wide-vs-BTN defense be preserved?",
    actionOptions: [o("a", "Нет — actual origin range matters", "No — the actual origin range matters"), o("b", "Да — BTN label is enough", "Yes — the BTN label is enough", "LABEL_AS_LAW"), o("c", "Да — closing action overrides all", "Yes — closing action overrides everything", "SINGLE_FACTOR")],
    reasonOptions: [o("r1", "Range-based reasoning updates the positional prior when evidence is strong", "Range-based reasoning updates the positional prior when evidence is strong"), o("r2", "Position labels cannot be updated", "Position labels cannot be updated", "EVIDENCE_IGNORED"), o("r3", "Tight ranges improve weak-hand domination", "Tight ranges improve weak-hand domination", "DOMINATION_BACKWARDS")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 28, explanationRu: "FTGU-E05 mechanism is explicitly range-based; BTN is a prior for width, not a permanent truth.", explanationEn: "FTGU-E05 is explicitly range-based; BTN is a prior for width, not a permanent truth.",
  },

  // BL-04 — BB vs open size. FTGU-E05.
  {
    id: "PM-BL-04-101", skillId: "BL-04", kind: "recognition", sourceRefs: ["FTGU-E05"], assumptions: ["same range/hand", "open size changes"], cueRu: "Range и hand те же; меняется только open size.", cueEn: "Range and hand are the same; only open size changes.", questionRu: "Какой primary variable меняется первым?", questionEn: "Which primary variable changes first?",
    actionOptions: [o("a", "Price / pot odds", "Price / pot odds"), o("b", "Hero's raw cards", "Hero's raw cards", "CARDS_MAGIC"), o("c", "Opponent position", "Opponent position", "POSITION_FALSE")],
    reasonOptions: [o("r1", "Larger incremental cost changes the break-even/realisable-equity requirement", "A larger incremental cost changes the break-even/realizable-equity requirement"), o("r2", "Sizing changes suits", "Sizing changes suits", "CARDS_MAGIC"), o("r3", "Open size is cosmetic", "Open size is cosmetic", "SIZE_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 18, explanationRu: "FTGU-E05 names open size as a direct BB defence determinant because it changes price.", explanationEn: "FTGU-E05 names open size as a direct BB-defense determinant because it changes price.",
  },
  {
    id: "PM-BL-04-102", skillId: "BL-04", kind: "recognition", sourceRefs: ["FTGU-E05"], assumptions: ["small open", "wide range", "closing action"], cueRu: "Small open + wide range + closing action.", cueEn: "Small open + wide range + closing action.", questionRu: "Как эта комбинация влияет на marginal defence?", questionEn: "How does this combination affect marginal defense?",
    actionOptions: [o("a", "Поддерживает больше calls", "Supports more calls"), o("b", "Требует fewer calls", "Requires fewer calls", "PRICE_BACKWARDS"), o("c", "Не влияет", "Does not matter", "MULTIFACTOR_IGNORED")],
    reasonOptions: [o("r1", "All three reduce the amount of realizable equity needed relative to a harsher branch", "All three reduce the amount of realizable equity needed relative to a harsher branch"), o("r2", "Small opens contain more premiums", "Small opens contain more premiums", "UNSUPPORTED_SIZE_TELL"), o("r3", "Closing action makes Hero IP", "Closing action makes Hero IP", "POSITION_FALSE")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 22, explanationRu: "These are the explicit favourable BB-defence conditions in FTGU-E05.", explanationEn: "These are the explicit favorable BB-defense conditions in FTGU-E05.",
  },
  {
    id: "PM-BL-04-103", skillId: "BL-04", kind: "decision", sourceRefs: ["FTGU-E05"], assumptions: ["same hand", "same BTN range", "2x open"], cueRu: "BTN 2x, BB marginal hand, остальные assumptions normal.", cueEn: "BTN opens 2x, BB has a marginal hand, other assumptions normal.", questionRu: "Как относиться к пограничной руке по сравнению с намного большим открытием?", questionEn: "How should the fringe be treated compared with facing a much larger open?",
    actionOptions: [o("a", "Больше hands могут остаться viable", "More hands can remain viable"), o("b", "Меньше hands viable", "Fewer hands are viable", "PRICE_BACKWARDS"), o("c", "Exactly same range", "Exactly the same range", "SIZE_IGNORED")],
    reasonOptions: [o("r1", "Cheaper price lowers the required realizable equity", "A cheaper price lowers required realizable equity"), o("r2", "Small sizing means stronger range by definition", "Small sizing means a stronger range by definition", "UNSUPPORTED_SIZE_TELL"), o("r3", "BB defence has no price component", "BB defense has no price component", "PRICE_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 20, explanationRu: "Directional size response is source-supported; exact chart cells remain intentionally excluded.", explanationEn: "The directional size response is source-supported; exact chart cells remain intentionally excluded.",
  },
  {
    id: "PM-BL-04-104", skillId: "BL-04", kind: "decision", sourceRefs: ["FTGU-E05"], assumptions: ["same hand", "same range", "large open"], cueRu: "Large open, BB fringe hand.", cueEn: "Large open, BB fringe hand.", questionRu: "Какой shortcut неверен?", questionEn: "Which shortcut is wrong?",
    actionOptions: [o("a", "BB already invested, so sizing can be ignored", "BB already invested, so sizing can be ignored", "SUNK_BLIND_OVERUSED"), o("b", "Posted blind helps price but does not erase the extra call cost", "The posted blind helps price but does not erase the extra call cost"), o("c", "Larger size can remove marginal calls", "A larger size can remove marginal calls", "CORRECT_FRAME_DISTRACTOR")],
    reasonOptions: [o("r1", "The blind is sunk, but the incremental amount still changes pot odds", "The blind is sunk, but the incremental amount still changes pot odds"), o("r2", "The blind makes every call free", "The blind makes every call free", "SUNK_BLIND_OVERUSED"), o("r3", "Open size changes only psychology", "Open size changes only psychology", "SIZE_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25, explanationRu: "FTGU-E05 combines the blind discount with the actual open size; neither can be ignored.", explanationEn: "FTGU-E05 combines the blind discount with the actual open size; neither can be ignored.",
  },
  {
    id: "PM-BL-04-105", skillId: "BL-04", kind: "decision", sourceRefs: ["FTGU-E05"], assumptions: ["same size", "opener becomes much wider"], cueRu: "Open size фиксирован, but origin range становится намного шире.", cueEn: "Open size is fixed, but the origin range becomes much wider.", questionRu: "Достаточно ли смотреть только на size chart?", questionEn: "Is looking only at a sizing chart sufficient?",
    actionOptions: [o("a", "Нет", "No"), o("b", "Да, size fully determines defence", "Yes, size fully determines defense", "SIZE_ONLY"), o("c", "Да, range width irrelevant", "Yes, range width is irrelevant", "RANGE_IGNORED")],
    reasonOptions: [o("r1", "Origin strength and realization remain independent inputs", "Origin strength and realization remain independent inputs"), o("r2", "All ranges at one size are identical", "All ranges at one size are identical", "RANGE_COLLAPSE"), o("r3", "BB never considers opponent range", "BB never considers opponent range", "RANGE_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 22, explanationRu: "FTGU-E05 explicitly makes size, range width and realization separate variables.", explanationEn: "FTGU-E05 explicitly makes size, range width and realization separate variables.",
  },
  {
    id: "PM-BL-04-106", skillId: "BL-04", kind: "changed", sourceRefs: ["FTGU-E05"], assumptions: ["same hand/range", "open gets cheaper"], cueRu: "Open дешевеет, hand/range неизменны.", cueEn: "The open becomes cheaper; hand/range are unchanged.", questionRu: "Как движется fringe?", questionEn: "How does the fringe move?",
    actionOptions: [o("a", "Wider", "Wider"), o("b", "Tighter", "Tighter", "PRICE_BACKWARDS"), o("c", "No change", "No change", "SIZE_IGNORED")],
    reasonOptions: [o("r1", "Cheaper incremental cost lowers required realization", "Cheaper incremental cost lowers required realization"), o("r2", "Cheaper price lowers pot size and therefore hurts every call", "Cheaper price lowers pot size and therefore hurts every call", "PRICE_BACKWARDS"), o("r3", "Sizing is not part of BB defence", "Sizing is not part of BB defense", "SIZE_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 18, explanationRu: "Directional response only; no unsupported exact frequency is claimed.", explanationEn: "Directional response only; no unsupported exact frequency is claimed.", changedVariables: ["open_size", "price"],
  },
  {
    id: "PM-BL-04-107", skillId: "BL-04", kind: "boundary", sourceRefs: ["FTGU-E05"], assumptions: ["tiny open", "extreme rake", "poor realization"], cueRu: "Open очень маленький, но rake extreme и Hero плохо реализует fringe.", cueEn: "The open is tiny, but rake is extreme and Hero realizes the fringe poorly.", questionRu: "Обязывает ли cheap price defend очень широко?", questionEn: "Does the cheap price force a very wide defense?",
    actionOptions: [o("a", "Нет", "No"), o("b", "Да, price overrides all", "Yes, price overrides everything", "PRICE_ONLY"), o("c", "Да, because BB closes action", "Yes, because BB closes the action", "SINGLE_FACTOR")],
    reasonOptions: [o("r1", "Rake and realisation can still remove marginal calls", "Rake and realization can still remove marginal calls"), o("r2", "Tiny sizing guarantees full equity realization", "Tiny sizing guarantees full equity realization", "REALISATION_GUARANTEE"), o("r3", "Rake disappears on small opens", "Rake disappears on small opens", "RAKE_FALSE")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 28, explanationRu: "FTGU-E05 is explicitly multi-factor; price is powerful but not absolute.", explanationEn: "FTGU-E05 is explicitly multi-factor; price is powerful but not absolute.",
  },

  // BL-05 — SB vs opens. FTGU-E06.
  {
    id: "PM-BL-05-101", skillId: "BL-05", kind: "recognition", sourceRefs: ["FTGU-E06"], assumptions: ["SB faces open", "BB remains"], cueRu: "SB faces open, BB remains behind.", cueEn: "SB faces an open with the BB remaining behind.", questionRu: "Что делает SB identity отличной от BB?", questionEn: "What makes SB identity different from BB?",
    actionOptions: [o("a", "Worse price, OOP, action not closed", "Worse price, OOP, action not closed"), o("b", "Same price and closing action", "Same price and closing action", "SB_EQUALS_BB"), o("c", "SB is IP postflop", "SB is IP postflop", "POSITION_FALSE")],
    reasonOptions: [o("r1", "These differences change realization and squeeze exposure before flop", "These differences change realization and squeeze exposure before the flop"), o("r2", "Blind positions share one defense identity", "Blind positions share one defense identity", "SB_EQUALS_BB"), o("r3", "Only blind amount matters", "Only blind amount matters", "BLIND_AMOUNT_ONLY")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 20, explanationRu: "FTGU-E06 explicitly explains why SB flats are structurally weaker than BB calls.", explanationEn: "FTGU-E06 explicitly explains why SB flats are structurally weaker than BB calls.",
  },
  {
    id: "PM-BL-05-102", skillId: "BL-05", kind: "recognition", sourceRefs: ["FTGU-E06"], assumptions: ["SB 3-bet"], cueRu: "SB 3-bets.", cueEn: "SB 3-bets.", questionRu: "Какой structural benefit связан именно с player behind?", questionEn: "Which structural benefit is tied specifically to the player behind?",
    actionOptions: [o("a", "Deny BB equity / avoid being squeezed", "Deny BB equity / avoid being squeezed"), o("b", "Gain postflop position", "Gain postflop position", "POSITION_FALSE"), o("c", "Guarantee opener fold", "Guarantee opener folds", "FOLD_GUARANTEE")],
    reasonOptions: [o("r1", "Aggression can remove the BB branch instead of exposing a capped flat to it", "Aggression can remove the BB branch instead of exposing a capped flat to it"), o("r2", "BB cannot act after SB", "The BB cannot act after the SB", "ACTION_ORDER_FALSE"), o("r3", "3-bet changes seat order", "A 3-bet changes seat order", "POSITION_FALSE")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 20, explanationRu: "FTGU-E06 lists denial to BB and avoidance of squeeze among the key benefits of 3-betting.", explanationEn: "FTGU-E06 lists denial to the BB and avoiding a squeeze among key benefits of 3-betting.",
  },
  {
    id: "PM-BL-05-103", skillId: "BL-05", kind: "decision", sourceRefs: ["FTGU-E06"], assumptions: ["SB marginal flat", "BB aggressive"], cueRu: "SB marginal flat, BB aggressive behind.", cueEn: "SB marginal flat, aggressive BB behind.", questionRu: "Что делает flat хуже?", questionEn: "What makes the flat worse?",
    actionOptions: [o("a", "Squeeze exposure and cappedness", "Squeeze exposure and cappedness"), o("b", "Too much position", "Too much position", "POSITION_FALSE"), o("c", "Closing action", "Closing the action", "ACTION_FALSE")],
    reasonOptions: [o("r1", "A squeeze can deny all equity before flop and the flat often lacks top-end protection", "A squeeze can deny all equity before the flop and the flat often lacks top-end protection"), o("r2", "BB aggression improves SB price", "BB aggression improves SB price", "SQUEEZE_BACKWARDS"), o("r3", "Capped ranges are harder to attack", "Capped ranges are harder to attack", "CAP_BACKWARDS")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25, explanationRu: "This is the central structural criticism of SB flats in FTGU-E06.", explanationEn: "This is the central structural criticism of SB flats in FTGU-E06.",
  },
  {
    id: "PM-BL-05-104", skillId: "BL-05", kind: "decision", sourceRefs: ["FTGU-E06"], assumptions: ["SB blocker hand", "fold equity meaningful", "called branch playable"], cueRu: "SB hand блокирует часть strong continues и не разваливается when called.", cueEn: "The SB hand blocks some strong continues and remains playable when called.", questionRu: "Какая role подходит?", questionEn: "Which role fits?",
    actionOptions: [o("a", "Potential 3-bet bluff/semi-bluff candidate", "Potential 3-bet bluff/semi-bluff candidate"), o("b", "Mandatory flat", "Mandatory flat", "FLAT_AUTOPILOT"), o("c", "Mandatory fold", "Mandatory fold", "BLOCKER_IGNORED")],
    reasonOptions: [o("r1", "Removal can add fold equity while playability protects the called branch", "Removal can add fold equity while playability protects the called branch"), o("r2", "Blocker guarantees a fold", "A blocker guarantees a fold", "BLOCKER_GUARANTEE"), o("r3", "3-bet bluffs need no called-branch EV", "3-bet bluffs need no called-branch EV", "CALL_BRANCH_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25, explanationRu: "FTGU-E06 uses suited wheel aces to illustrate this exact class-level mechanism.", explanationEn: "FTGU-E06 uses suited wheel aces to illustrate this exact class-level mechanism.",
  },
  {
    id: "PM-BL-05-105", skillId: "BL-05", kind: "decision", sourceRefs: ["FTGU-E06"], assumptions: ["SB dominated offsuit broadway", "opener continues strong"], cueRu: "SB dominated offsuit broadway; 3-bet gets called by concentrated stronger broadways.", cueEn: "SB dominated offsuit broadway; the 3-bet gets called by concentrated stronger broadways.", questionRu: "Какой trap избегать?", questionEn: "Which trap should be avoided?",
    actionOptions: [o("a", "3-bet just because flat is bad", "3-bet just because flat is bad", "THREE_BET_OR_FOLD_LITERAL"), o("b", "Evaluate the called branch", "Evaluate the called branch"), o("c", "Account for range filtering", "Account for range filtering", "CORRECT_FRAME_DISTRACTOR")],
    reasonOptions: [o("r1", "A bad flat does not make an dominated 3-bet branch good", "A bad flat does not make a dominated 3-bet branch good"), o("r2", "Aggression is always +EV", "Aggression is always +EV", "AGGRESSION_AUTOPILOT"), o("r3", "Filtered ranges become weaker by definition", "Filtered ranges become weaker by definition", "FILTERING_BACKWARDS")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25, explanationRu: "FTGU-E06 explicitly warns against converting 'flat is unattractive' into 'therefore 3-bet'.", explanationEn: "FTGU-E06 explicitly warns against converting 'flat is unattractive' into 'therefore 3-bet'.",
  },
  {
    id: "PM-BL-05-106", skillId: "BL-05", kind: "changed", sourceRefs: ["FTGU-E06"], assumptions: ["same SB versatile hand", "BB aggressive -> passive"], cueRu: "Та же SB hand, BB behind перестаёт squeeze.", cueEn: "Same SB hand, but the BB behind stops squeezing.", questionRu: "Что происходит с conditional flat branch?", questionEn: "What happens to the conditional flat branch?",
    actionOptions: [o("a", "Может стать жизнеспособнее", "It can become more viable"), o("b", "Всегда хуже", "Always worse", "PLAYER_TYPE_BACKWARDS"), o("c", "No effect", "No effect", "BB_BEHIND_IGNORED")],
    reasonOptions: [o("r1", "One major structural penalty — squeeze risk — has fallen", "One major structural penalty — squeeze risk — has fallen"), o("r2", "Passive BB creates more squeezes", "A passive BB creates more squeezes", "PLAYER_TYPE_BACKWARDS"), o("r3", "Table behind never matters", "The table behind never matters", "PLAYERS_BEHIND_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 22, explanationRu: "FTGU-E06 explicitly permits some flats when the BB is weak/passive.", explanationEn: "FTGU-E06 explicitly permits some flats when the BB is weak/passive.", changedVariables: ["bb_squeeze_tendency"],
  },
  {
    id: "PM-BL-05-107", skillId: "BL-05", kind: "boundary", sourceRefs: ["FTGU-E06"], assumptions: ["weak passive BB", "versatile hand", "keeping weaker opener range in is valuable"], cueRu: "SB default says 3-bet-or-fold, but BB weak/passive and flat keeps weaker hands in.", cueEn: "The SB default says 3-bet-or-fold, but the BB is weak/passive and a flat keeps weaker hands in.", questionRu: "Какой interpretation правильнее?", questionEn: "Which interpretation is better?",
    actionOptions: [o("a", "Default can have contextual flat exceptions", "The default can have contextual flat exceptions"), o("b", "Title is an unconditional law", "The title is an unconditional law", "TITLE_LITERALISM"), o("c", "SB should never 3-bet", "SB should never 3-bet", "TITLE_INVERSION")],
    reasonOptions: [o("r1", "The source explicitly calls 3-bet-or-fold a useful default, not a literal prohibition", "The source explicitly calls 3-bet-or-fold a useful default, not a literal prohibition"), o("r2", "Defaults never change with table context", "Defaults never change with table context", "DEFAULT_AS_LAW"), o("r3", "Weak BB changes Hero's position", "A weak BB changes Hero's position", "POSITION_FALSE")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25, explanationRu: "This boundary prevents learner over-literalism while preserving the source default.", explanationEn: "This boundary prevents learner over-literalism while preserving the source default.",
  },

  // BL-12 — blind depth/rake variants. FTGU-E05/E06 + LCM-01.
  {
    id: "PM-BL-12-101", skillId: "BL-12", kind: "recognition", sourceRefs: ["FTGU-E05", "LCM-01"], assumptions: ["same hand/open", "rake changes"], cueRu: "Hand/open те же, rake меняется.", cueEn: "Hand/open are the same, rake changes.", questionRu: "Какая часть range обычно наиболее чувствительна?", questionEn: "Which part of the range is usually most sensitive?",
    actionOptions: [o("a", "Marginal calls", "Marginal calls"), o("b", "Only premium value", "Only premium value", "MARGIN_IGNORED"), o("c", "None", "None", "RAKE_IGNORED")],
    reasonOptions: [o("r1", "Rake subtracts EV and pushes thin calls across zero first", "Rake subtracts EV and pushes thin calls across zero first"), o("r2", "Rake increases implied odds", "Rake increases implied odds", "RAKE_BACKWARDS"), o("r3", "Rake paid only after river", "Rake is paid only after the river", "RAKE_FALSE")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 20, explanationRu: "FTGU-E05 explicitly identifies marginal BB calls as rake-sensitive.", explanationEn: "FTGU-E05 explicitly identifies marginal BB calls as rake-sensitive.",
  },
  {
    id: "PM-BL-12-102", skillId: "BL-12", kind: "recognition", sourceRefs: ["LCM-01"], assumptions: ["same nominal stack", "straddle introduced"], cueRu: "Nominal stack unchanged, straddle introduced.", cueEn: "Nominal stack is unchanged, a straddle is introduced.", questionRu: "Что нужно пересчитать до blind strategy?", questionEn: "What must be recalculated before blind strategy?",
    actionOptions: [o("a", "Working effective depth/action geometry", "Working effective depth/action geometry"), o("b", "Only card ranks", "Only card ranks", "CARDS_ONLY"), o("c", "Nothing", "Nothing", "STRADDLE_IGNORED")],
    reasonOptions: [o("r1", "Straddle changes blind unit, pot and action order", "A straddle changes the blind unit, pot and action order"), o("r2", "Straddle is cosmetic", "A straddle is cosmetic", "STRADDLE_IGNORED"), o("r3", "Nominal BB count is always sufficient", "Nominal BB count is always sufficient", "NOMINAL_STACK_ONLY")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 20, explanationRu: "LCM-01 treats straddle as a geometry change, not a label change.", explanationEn: "LCM-01 treats a straddle as a geometry change, not a label change.",
  },
  {
    id: "PM-BL-12-103", skillId: "BL-12", kind: "decision", sourceRefs: ["FTGU-E05"], assumptions: ["thin BB call", "rake materially higher"], cueRu: "Thin BB call, rake materially higher than baseline.", cueEn: "Thin BB call, rake materially higher than baseline.", questionRu: "Какой должна быть базовая корректировка?", questionEn: "What is the default adjustment?",
    actionOptions: [o("a", "Tighten the thin-call fringe", "Tighten the thin-call fringe"), o("b", "Widen the thin-call fringe", "Widen the thin-call fringe", "RAKE_BACKWARDS"), o("c", "Ignore rake", "Ignore rake", "RAKE_IGNORED")],
    reasonOptions: [o("r1", "The source explicitly says rake can remove marginal defends", "The source explicitly says rake can remove marginal defends"), o("r2", "Higher rake creates more dead money", "Higher rake creates more dead money", "RAKE_BACKWARDS"), o("r3", "Rake only affects winners", "Rake affects only winners", "RAKE_FALSE")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 20, explanationRu: "This is a directional adjustment only; no unsupported frequency is claimed.", explanationEn: "This is a directional adjustment only; no unsupported frequency is claimed.",
  },
  {
    id: "PM-BL-12-104", skillId: "BL-12", kind: "decision", sourceRefs: ["FTGU-E05", "LCM-01"], assumptions: ["same nominal stack", "preflop pot much larger", "SPR lower"], cueRu: "Nominal stack тот же, но larger preflop pot делает postflop SPR ниже.", cueEn: "Nominal stack is the same, but a larger preflop pot creates lower postflop SPR.", questionRu: "Можно ли называть spot 'тем же depth'?", questionEn: "Can the spot be treated as the same depth?",
    actionOptions: [o("a", "Нет — decision geometry изменилась", "No — the decision geometry changed"), o("b", "Да — starting BB count same", "Yes — starting BB count is the same", "NOMINAL_STACK_ONLY"), o("c", "Да — pot size irrelevant", "Yes — pot size is irrelevant", "POT_IGNORED")],
    reasonOptions: [o("r1", "Effective stack relative to pot controls future leverage", "Effective stack relative to the pot controls future leverage"), o("r2", "Only starting stack matters", "Only starting stack matters", "NOMINAL_STACK_ONLY"), o("r3", "SPR is unrelated to blind strategy", "SPR is unrelated to blind strategy", "SPR_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25, explanationRu: "LCM-01 + FTGU-E05 framework requires re-evaluating realisation when geometry changes.", explanationEn: "The LCM-01 + FTGU-E05 framework requires reevaluating realization when geometry changes.",
  },
  {
    id: "PM-BL-12-105", skillId: "BL-12", kind: "decision", sourceRefs: ["FTGU-E06", "LCM-01"], assumptions: ["SB considers 3-bet", "larger pot lowers SPR"], cueRu: "SB 3-bet создаёт lower-SPR pot.", cueEn: "An SB 3-bet creates a lower-SPR pot.", questionRu: "Почему это может частично уменьшать positional disadvantage?", questionEn: "Why can this partly reduce the positional disadvantage?",
    actionOptions: [o("a", "Fewer future decisions reduce room for IP leverage", "Fewer future decisions reduce room for IP leverage"), o("b", "SB becomes IP", "SB becomes IP", "POSITION_FALSE"), o("c", "Position stops mattering completely", "Position stops mattering completely", "ABSOLUTE_CLAIM")],
    reasonOptions: [o("r1", "FTGU-E06 says lower SPR makes position matter somewhat less, not zero", "FTGU-E06 says lower SPR makes position matter somewhat less, not zero"), o("r2", "3-bet changes seat order", "A 3-bet changes seat order", "POSITION_FALSE"), o("r3", "Low SPR guarantees showdown", "Low SPR guarantees showdown", "GUARANTEE_FALSE")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25, explanationRu: "Important boundary: lower SPR reduces, but does not eliminate, positional disadvantage.", explanationEn: "Important boundary: lower SPR reduces, but does not eliminate, positional disadvantage.",
  },
  {
    id: "PM-BL-12-106", skillId: "BL-12", kind: "changed", sourceRefs: ["FTGU-E05"], assumptions: ["same BB hand/size/range", "rake low -> high"], cueRu: "Всё то же, rake low → high.", cueEn: "Everything else is the same, rake goes low → high.", questionRu: "Как двигается thin call?", questionEn: "How does the thin call move?",
    actionOptions: [o("a", "Worse", "Worse"), o("b", "Better", "Better", "RAKE_BACKWARDS"), o("c", "Unchanged", "Unchanged", "RAKE_IGNORED")],
    reasonOptions: [o("r1", "Rake subtracts from marginal EV", "Rake subtracts from marginal EV"), o("r2", "Rake improves price", "Rake improves price", "RAKE_BACKWARDS"), o("r3", "Rake only matters after showdown", "Rake matters only after showdown", "RAKE_FALSE")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 18, explanationRu: "FTGU-E05 gives this directional boundary explicitly.", explanationEn: "FTGU-E05 gives this directional boundary explicitly.", changedVariables: ["rake"],
  },
  {
    id: "PM-BL-12-107", skillId: "BL-12", kind: "boundary", sourceRefs: ["FTGU-E05", "FTGU-E06", "LCM-01"], assumptions: ["nominal depth same", "rake/SPR/players-behind differ"], cueRu: "Два blind spots имеют одинаковые '100bb' labels, но разный rake, SPR и action behind.", cueEn: "Two blind spots share the same '100bb' label but differ in rake, SPR and action behind.", questionRu: "Можно ли считать их одной strategy node?", questionEn: "Can they be treated as one strategy node?",
    actionOptions: [o("a", "Нет", "No"), o("b", "Да, nominal depth is enough", "Yes, nominal depth is enough", "NOMINAL_STACK_ONLY"), o("c", "Да, blind seat label is enough", "Yes, the blind seat label is enough", "SEAT_LABEL_ONLY")],
    reasonOptions: [o("r1", "Blind EV depends on price, realisation, action order and effective geometry", "Blind EV depends on price, realization, action order and effective geometry"), o("r2", "Only stack label matters", "Only the stack label matters", "SINGLE_FACTOR"), o("r3", "Rake and players behind cannot change preflop EV", "Rake and players behind cannot change preflop EV", "CONTEXT_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30, explanationRu: "This is the core transfer boundary connecting FTGU-E05/E06 with admitted LCM-01 geometry.", explanationEn: "This is the core transfer boundary connecting FTGU-E05/E06 with admitted LCM-01 geometry.",
  },
];
