import type { PracticalDecision } from "./types";

const o=(id:string,textRu:string,textEn:string,misconception?:string)=>({id,textRu,textEn,misconception});
type L={skillId:string;prefix:string;sourceRefs:string[];baseRu:string;baseEn:string;signalRu:string;signalEn:string;whyRu:string;whyEn:string;changeRu:string;changeEn:string;vars:string[]};

function build(v:L):PracticalDecision[]{
 const rows=[
  {kind:"recognition" as const,cueRu:v.baseRu,cueEn:v.baseEn,qRu:"Какой live-context signal нельзя пропустить?",qEn:"Which live-context signal must not be missed?",goodRu:v.signalRu,goodEn:v.signalEn,changed:undefined},
  {kind:"decision" as const,cueRu:v.baseRu,cueEn:v.baseEn,qRu:"Какой подход лучше?",qEn:"Which approach is better?",goodRu:"Пересчитать canonical branch с учётом live variable, не копировать 100bb/default автоматически",goodEn:"Recompute the canonical branch with the live variable instead of automatically copying the 100bb/default line",changed:undefined},
  {kind:"changed" as const,cueRu:v.changeRu,cueEn:v.changeEn,qRu:"Что должно измениться?",qEn:"What should change?",goodRu:"Relevant threshold/range/realisation сдвигаются из-за live variable",goodEn:"The relevant threshold/range/realization shifts because of the live variable",changed:v.vars},
  {kind:"boundary" as const,cueRu:`${v.baseRu} Learner хочет применить один live slogan ко всем столам.`,cueEn:`${v.baseEn} The learner wants to apply one live slogan to every table.`,qRu:"Где boundary?",qEn:"Where is the boundary?",goodRu:"Вернуться к branch-specific assumptions и observed evidence",goodEn:"Return to branch-specific assumptions and observed evidence",changed:undefined},
 ];
 return rows.map((r,i)=>{const slot=i%3;const good=o("good",r.goodRu,r.goodEn);const b1=o("b1","Скопировать обычный 100bb/HU default без пересчёта","Copy the ordinary 100bb/HU default without recomputing","LIVE_CONTEXT_IGNORED");const b2=o("b2","Использовать universal live-player slogan","Use a universal live-player slogan","LIVE_STEREOTYPE");const gr=o("goodR",v.whyRu,v.whyEn);const br1=o("br1","Live variables не меняют geometry/ranges","Live variables do not change geometry/ranges","GEOMETRY_IGNORED");const br2=o("br2","Один observed tendency доказывает population law","One observed tendency proves a population law","EVIDENCE_OVERGENERALIZED");return {id:`${v.prefix}-${101+i}`,skillId:v.skillId,kind:r.kind,sourceRefs:v.sourceRefs,assumptions:["B4 live-context transformation; source-scoped direction; no exact population frequency"],cueRu:r.cueRu,cueEn:r.cueEn,questionRu:r.qRu,questionEn:r.qEn,actionOptions:slot===0?[good,b1,b2]:slot===1?[b1,good,b2]:[b1,b2,good],reasonOptions:slot===0?[br1,gr,br2]:slot===1?[gr,br1,br2]:[br1,br2,gr],correctActionId:"good",correctReasonId:"goodR",targetSeconds:22,explanationRu:v.whyRu,explanationEn:v.whyEn,changedVariables:r.changed} satisfies PracticalDecision;});
}

const variants:L[]=[
 {skillId:"PF-01",prefix:"PM-B4-PF01",sourceRefs:["FTGU-E02","SLC-PREFLOP-ADJUSTMENTS","EXT-GTOW-DEEP-300-2025"],baseRu:"Live RFI spot: stacks 250bb+, players behind sticky, opening environment отличается от default chart assumptions.",baseEn:"Live RFI spot: stacks are 250bb+, players behind are sticky, and the environment differs from default chart assumptions.",signalRu:"Depth + players behind + realization/rake around the opening fringe",signalEn:"Depth + players behind + realization/rake around the opening fringe",whyRu:"Opening charts are defaults; deeper future trees and sticky players behind alter fringe EV and positional costs.",whyEn:"Opening charts are defaults; deeper future trees and sticky players behind alter fringe EV and positional costs.",changeRu:"Same hand/position: 100bb quiet table → 250bb sticky callers behind.",changeEn:"Same hand/position: 100bb quiet table → 250bb with sticky callers behind.",vars:["effective_depth","players_behind","realisation"]},
 {skillId:"PF-02",prefix:"PM-B4-PF02",sourceRefs:["FTGU-E03"],baseRu:"Two live limpers, Hero chooses iso/overlimp/fold while players behind remain active.",baseEn:"Two live limpers, Hero chooses isolate/overlimp/fold while players behind remain active.",signalRu:"Frequent strength + fold equity + position + number/stickiness of callers + players behind",signalEn:"Frequent strength + fold equity + position + number/stickiness of callers + players behind",whyRu:"FTGU-E03 frames limp decisions through the full called/fold/multiway branches, not an automatic isolation rule.",whyEn:"FTGU-E03 frames limp decisions through the full called/fold/multiway branches, not an automatic isolation rule.",changeRu:"Same hand/seat: one fold-prone limper → three sticky limpers plus aggressive player behind.",changeEn:"Same hand/seat: one fold-prone limper → three sticky limpers plus an aggressive player behind.",vars:["limper_count","caller_stickiness","players_behind"]},
 {skillId:"PF-04",prefix:"PM-B4-PF04",sourceRefs:["FTGU-E05","SLC-PREFLOP-ADJUSTMENTS"],baseRu:"BB faces a 5bb live open instead of a small online-style open.",baseEn:"BB faces a 5bb live open instead of a small online-style open.",signalRu:"Much worse price + often more selected origin range + realization cost",signalEn:"Much worse price + often more selected origin range + realization cost",whyRu:"Large live sizing removes marginal BB calls quickly; posted blind is not a reason to defend a fixed range.",whyEn:"Large live sizing removes marginal BB calls quickly; the posted blind is not a reason to defend a fixed range.",changeRu:"Same opener/hand: 2.5bb → 5bb live open.",changeEn:"Same opener/hand: 2.5bb → 5bb live open.",vars:["open_size","price"]},
 {skillId:"PF-06",prefix:"PM-B4-PF06",sourceRefs:["FTGU-E15","FTGU-E16","EXT-GTOW-DEEP-300-2025"],baseRu:"Deep live 3-bet decision: 250–300bb and caller-heavy opener change the called branch.",baseEn:"Deep live 3-bet decision: 250–300bb and a caller-heavy opener change the called branch.",signalRu:"Fold equity + deep called-branch realization + position",signalEn:"Fold equity + deep called-branch realization + position",whyRu:"At depth, OOP realization and reverse-implied exposure grow; 3-bet shape cannot be copied mechanically from 100bb.",whyEn:"At depth, OOP realization and reverse-implied exposure grow; 3-bet shape cannot be copied mechanically from 100bb.",changeRu:"Same hand/opener: 100bb → 300bb, Hero remains OOP.",changeEn:"Same hand/opener: 100bb → 300bb, Hero remains OOP.",vars:["effective_depth","position","called_branch"]},
 {skillId:"PF-07",prefix:"PM-B4-PF07",sourceRefs:["FTGU-E17","SLC-PREFLOP-ADJUSTMENTS"],baseRu:"Live 3-bet is unusually large and stacks are deep; Hero cannot defend by a remembered percentage.",baseEn:"The live 3-bet is unusually large and stacks are deep; Hero cannot defend by a remembered percentage.",signalRu:"3-bet size × depth × position × opponent construction",signalEn:"3-bet size × depth × position × opponent construction",whyRu:"Facing 3-bets is a branch-EV problem; large live sizes and deep future trees jointly move call/4-bet/fold thresholds.",whyEn:"Facing 3-bets is a branch-EV problem; large live sizes and deep future trees jointly move call/4-bet/fold thresholds.",changeRu:"Same hand/positions: standard 3-bet → oversized live 3-bet at 250bb.",changeEn:"Same hand/positions: standard 3-bet → oversized live 3-bet at 250bb.",vars:["threebet_size","effective_depth"]},
 {skillId:"BL-03",prefix:"PM-B4-BL03",sourceRefs:["FTGU-E05","SLC-BB-VS-BTN"],baseRu:"BB vs BTN in a raked live game with 4bb open and poor postflop realization.",baseEn:"BB versus BTN in a raked live game with a 4bb open and poor postflop realization.",signalRu:"Wide origin still matters, but large price/rake/realization can erase fringe calls",signalEn:"Wide origin still matters, but large price/rake/realization can erase fringe calls",whyRu:"BTN width is not a license to defend the same fringe across large sizes and poor-realization environments.",whyEn:"BTN width is not a license to defend the same fringe across large sizes and poor-realization environments.",changeRu:"Same hand/origin: small low-rake node → 4bb high-rake/poor-realization node.",changeEn:"Same hand/origin: small low-rake node → 4bb high-rake/poor-realization node.",vars:["open_size","rake","realisation"]},
 {skillId:"OOP-02",prefix:"PM-B4-OOP02",sourceRefs:["FTGU-E08","SLC-DEEP-SRP-OOP"],baseRu:"OOP SRP at 200bb: medium hand faces pressure with substantial future stack behind.",baseEn:"OOP SRP at 200bb: a medium hand faces pressure with substantial future stack behind.",signalRu:"Current price + hand robustness + deep future leverage/reverse implied odds",signalEn:"Current price + hand robustness + deep future leverage/reverse implied odds",whyRu:"Deep OOP realization makes weak dominated continues more expensive over later streets even at a seemingly attractive flop price.",whyEn:"Deep OOP realization makes weak dominated continues more expensive over later streets even at a seemingly attractive flop price.",changeRu:"Same flop/hand/size: 100bb → 200bb effective OOP.",changeEn:"Same flop/hand/size: 100bb → 200bb effective OOP.",vars:["effective_depth","future_leverage"]},
 {skillId:"3BP-05",prefix:"PM-B4-3BP05",sourceRefs:["SLC-3BET-POTS","EXT-GTOW-3BP-OOP-2023"],baseRu:"Deep 3BP: role/board remain familiar but SPR and future leverage are larger than standard 100bb.",baseEn:"Deep 3BP: role/board remain familiar but SPR and future leverage are larger than standard 100bb.",signalRu:"Role × board × sizing now also interacts with materially higher SPR",signalEn:"Role × board × sizing now also interacts with materially higher SPR",whyRu:"Deep 3BP solutions retain more future branches; low-SPR shortcuts and automatic commitment become less transferable.",whyEn:"Deep 3BP solutions retain more future branches; low-SPR shortcuts and automatic commitment become less transferable.",changeRu:"Same roles/board: 100bb 3BP → 200bb 3BP with higher flop SPR.",changeEn:"Same roles/board: 100bb 3BP → 200bb 3BP with higher flop SPR.",vars:["effective_depth","spr"]},
 {skillId:"TURN-02",prefix:"PM-B4-TURN02",sourceRefs:["FTGU-E21","SLC-TURN-BARREL"],baseRu:"Turn barrel in a deep live pot where opponent can continue and pressure rivers with substantial stacks behind.",baseEn:"Turn barrel in a deep live pot where the opponent can continue and pressure rivers with substantial stacks behind.",signalRu:"Runout/hand leverage + future river SPR, not just current fold equity",signalEn:"Runout/hand leverage + future river SPR, not just current fold equity",whyRu:"Deep future leverage changes which thin value/bluff classes want to inflate the pot and how robustly they realize on rivers.",whyEn:"Deep future leverage changes which thin value/bluff classes want to inflate the pot and how robustly they realize on rivers.",changeRu:"Same turn/hand: shallow remaining stack → deep remaining stack.",changeEn:"Same turn/hand: shallow remaining stack → deep remaining stack.",vars:["future_spr","effective_depth"]},
 {skillId:"RIV-01",prefix:"PM-B4-RIV01",sourceRefs:["LCM-09","CP-G3-L02","EXT-PS-RIVER-2025"],baseRu:"Live river value decision against a player with observed wide small-size calls but tight large-size calls.",baseEn:"Live river value decision against a player observed calling small sizes wide but large sizes tightly.",signalRu:"Worse calling region is size-specific and evidence-qualified",signalEn:"The worse calling region is size-specific and evidence-qualified",whyRu:"Value sizing must target actual worse continues; a generic 'station' label cannot justify every size.",whyEn:"Value sizing must target actual worse continues; a generic 'station' label cannot justify every size.",changeRu:"Same hand/player: small size with wide worse calls → large size where those hands fold.",changeEn:"Same hand/player: small size with wide worse calls → large size where those hands fold.",vars:["river_size","evidence_branch"]},
 {skillId:"RIV-03",prefix:"PM-B4-RIV03",sourceRefs:["FTGU-E22","CINJ-E02","CINJ-E04"],baseRu:"Live bluff-catch against a large river line with an observed underbluff tendency in this exact branch.",baseEn:"Live bluff-catch against a large river line with an observed underbluff tendency in this exact branch.",signalRu:"Price × natural bluff supply × branch-specific evidence",signalEn:"Price × natural bluff supply × branch-specific evidence",whyRu:"Population/player evidence can move the call threshold only inside the observed branch and never replaces bluff-supply reconstruction.",whyEn:"Population/player evidence can move the call threshold only inside the observed branch and never replaces bluff-supply reconstruction.",changeRu:"Same price/hand: evidence changes from unknown → repeated same-branch underbluff.",changeEn:"Same price/hand: evidence changes from unknown → repeated same-branch underbluff.",vars:["evidence_confidence","bluff_supply"]},
];

export const liveEdgeB4Decisions:PracticalDecision[]=variants.flatMap(build);
