import type { PracticalDecision, PracticalAnchor } from "./types";

// Execution Transfer Closure: bounded final wave extending existing skill families only.
// Scope: equal-blind 5/5 blind-vs-blind topology (BL-06/07/09/10, DEEP-03), turn fast
// classification (TURN-01/02), board-family recognition speed (W4-BOARD-01) and the
// hand -> relative-role bridge (W4-REL-01). No new skills, modules, state fields,
// scheduler semantics, persistent enums, routes or BL-11 closure.
// Correct option identities stay stable; display order is intentionally varied per
// decision so learner correctness cannot be inferred from a fixed option position.
const o = (id: string, textRu: string, textEn: string, misconception?: string) => ({ id, textRu, textEn, misconception });

export const executionTransferClosureDecisions: PracticalDecision[] = [
  // ---------------------------------------------------------------------
  // Section A — 5/5 equal-blind topology (BL-06 / BL-09 / BL-10 / DEEP-03)
  // ---------------------------------------------------------------------
  {
    id: "PM-BL-06-ETC-101", skillId: "BL-06", kind: "recognition", sourceRefs: ["SLC-BB-VS-SB"],
    assumptions: ["ставки 5/5 без анте", "блайнды равны", "все сфолдили до SB"],
    cueRu: "Игра 5/5, блайнды равны. Все сфолдили до SB.",
    cueEn: "5/5 game, equal blinds. Everyone folds to SB.",
    questionRu: "Стоит ли SB здесь перед стандартным выбором open/fold, как при обычном рейзе с 0.5bb до 1bb?",
    questionEn: "Is SB facing the standard open/fold choice here, the same as a normal 0.5bb-to-1bb open?",
    actionOptions: [
      o("a", "Нет — SB уже поставил полный блайнд и может бесплатно чекнуть или сам поднять", "No — SB already posted the full blind and may check for free or raise"),
      o("b", "Да — SB должен либо рейзить, либо фолдить, как при обычном префлоп-открытии", "Yes — SB must either raise or fold, same as an ordinary preflop open", "STANDARD_OPEN_TRANSFER"),
      o("c", "Да — раз действие дошло до SB, чек здесь равносилен лимпу с частичной ставкой", "Yes — since action reached SB, checking here is equivalent to limping with a partial bet", "LIMP_MISLABEL"),
    ],
    reasonOptions: [
      o("r1", "При равных блайндах SB уже внёс полную ставку, поэтому чек ничего не стоит и не совпадает с классическим деревом open/fold", "With equal blinds SB has already posted a full bet, so a check costs nothing and does not match the classic open/fold tree"),
      o("r2", "SB всегда обязан действовать так же, как игрок без блайнда впереди", "SB must always act the same as a player with no blind already posted", "STANDARD_OPEN_TRANSFER"),
      o("r3", "BB будет защищаться по тем же принципам, что и против обычного открытия", "BB will defend by the same principles as against an ordinary open", "BB_DEFENSE_TRANSFER"),
    ],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 20,
    explanationRu: "В равных блайндах SB — это не первый добровольный вход в банк, а уже полностью оплаченная ставка. Перенос стандартной логики open/fold с 0.5bb на 1bb сюда неверен: у SB есть третий вариант — бесплатный чек.",
    explanationEn: "With equal blinds, SB is not the first voluntary entry into the pot — it is already a fully paid bet. Transferring the standard 0.5bb-to-1bb open/fold logic here is wrong: SB has a third option, a free check.",
  },
  {
    id: "PM-BL-10-ETC-101", skillId: "BL-10", kind: "recognition", sourceRefs: ["SLC-BB-VS-SB", "LCM-03"],
    assumptions: ["5/5 равные блайнды", "все сфолдили до SB", "SB чекнул, BB чекнул", "флоп K72 без масти"],
    cueRu: "5/5. Все сфолдили до SB. SB чекнул, BB чекнул. Флоп K♦7♣2♠.",
    cueEn: "5/5. Everyone folds to SB. SB checks, BB checks. Flop K♦7♣2♠.",
    questionRu: "Как правильно классифицировать этот банк перед тем, как читать флоп?",
    questionEn: "How should this pot be classified before reading the flop?",
    actionOptions: [
      o("a", "Нечекнутый рейзом банк с блайндов без префлоп-агрессора — обычного PFR здесь нет", "A blind-versus-blind pot with no preflop raise — there is no conventional PFR here"),
      o("b", "Обычный single-raised pot, где SB — префлоп-агрессор", "An ordinary single-raised pot where SB is the preflop aggressor", "PFR_ASSUMED"),
      o("c", "Обычный single-raised pot, где BB — префлоп-агрессор", "An ordinary single-raised pot where BB is the preflop aggressor", "PFR_ASSUMED"),
    ],
    reasonOptions: [
      o("r1", "SB всегда сохраняет инициативу, потому что действовал первым", "SB always keeps the initiative because SB acted first", "INITIATIVE_MISATTRIBUTED"),
      o("r2", "Оба игрока чекнули префлоп добровольно, поэтому ни один диапазон не был сужен рейзом, и обычной для single-raised pot инициативы здесь нет", "Both players checked preflop voluntarily, so neither range was narrowed by a raise, and there is no single-raised-pot-style initiative here"),
      o("r3", "Чек SB автоматически делает BB агрессором на будущих улицах", "SB's check automatically makes BB the aggressor on future streets", "ROLE_INVENTED"),
    ],
    correctActionId: "a", correctReasonId: "r2", targetSeconds: 20,
    explanationRu: "Ни SB, ни BB не рейзили префлоп, поэтому ни один диапазон не отфильтрован через агрессию. Манипулировать понятием «диапазон префлоп-агрессора» здесь нельзя — оба диапазона остаются широкими и симметрично неотфильтрованными до флопа.",
    explanationEn: "Neither SB nor BB raised preflop, so neither range was filtered by aggression. There is no preflop-aggressor range advantage to invoke here — both ranges stay wide and symmetrically unfiltered going into the flop.",
  },
  {
    id: "PM-BL-09-ETC-101", skillId: "BL-09", kind: "decision", sourceRefs: ["SLC-BB-VS-SB"],
    assumptions: ["5/5 равные блайнды", "SB чекнул", "BB поднял до $20", "SB уравнял", "флоп K72 без масти"],
    cueRu: "5/5. SB чекнул. BB поднял до $20. SB уравнял. Флоп K♦7♣2♠.",
    cueEn: "5/5. SB checks. BB raises to $20. SB calls. Flop K♦7♣2♠.",
    questionRu: "Как правильно описать этот банк на флопе?",
    questionEn: "How should this pot be described on the flop?",
    actionOptions: [
      o("a", "Это обычный банк защиты BB, как против обычного открытия SB", "This is an ordinary BB-defense pot, the same as against a normal SB open", "STANDARD_BB_DEFENSE"),
      o("b", "SB сохраняет инициативу, потому что действовал первым в раздаче", "SB keeps the initiative because SB acted first in the hand", "INITIATIVE_MISATTRIBUTED"),
      o("c", "BB — префлоп-агрессор в позиции, а диапазон SB дважды отфильтрован: сначала чеком вместо рейза, затем коллом рейза", "BB is the in-position preflop aggressor, and SB's range has been filtered twice: first by checking instead of raising, then by calling the raise"),
    ],
    reasonOptions: [
      o("r1", "Любой колл SB после чека означает, что диапазон SB не изменился", "Any SB call after a check means SB's range is unchanged", "ANCESTRY_IGNORED"),
      o("r2", "Рейз BB всегда означает то же самое, что открытие с обычных блайндов", "A BB raise always means the same thing as an open from standard blinds", "SIZE_CONTEXT_IGNORED"),
      o("r3", "Диапазон SB прошёл через два фильтра подряд — добровольный чек вместо рейза, затем колл против рейза, — поэтому его нельзя приравнивать к диапазону защищающегося BB против стандартного открытия", "SB's range passed through two filters in a row — a voluntary check instead of a raise, then a call against a raise — so it cannot be equated with a defending BB's range against a standard open"),
    ],
    correctActionId: "c", correctReasonId: "r3", targetSeconds: 25,
    explanationRu: "Это узел BvB после агрессии BB, а не стандартная защита BB. Диапазон SB прошёл через две развилки подряд (чек, затем колл рейза), поэтому ветку нужно разбирать с этой ancestry, а не переносить готовое дерево из другого узла.",
    explanationEn: "This is a BvB node after BB aggression, not standard BB defense. SB's range passed through two branches in a row (check, then a call against a raise), so the node needs to be analyzed from this ancestry rather than importing a tree from a different node.",
  },
  {
    id: "PM-BL-06-ETC-102", skillId: "BL-06", kind: "decision", sourceRefs: ["SLC-BB-VS-SB"],
    assumptions: ["5/5 равные блайнды", "все сфолдили до SB", "SB поднял до $20", "BB уравнял"],
    cueRu: "5/5. Все сфолдили до SB. SB поднял до $20. BB уравнял.",
    cueEn: "5/5. Everyone folds to SB. SB raises to $20. BB calls.",
    questionRu: "Что это за узел с точки зрения того, кто создал повышенный банк?",
    questionEn: "What kind of node is this, in terms of who created the raised pot?",
    actionOptions: [
      o("a", "То же самое, что SB чекнул, а затем уравнял рейз BB", "The same as if SB had checked and then called a BB raise", "ANCESTRY_COLLAPSED"),
      o("b", "SB добровольно создал повышенный банк не в позиции, а BB защищается против этого рейза", "SB voluntarily created a raised pot out of position, and BB is defending against that raise"),
      o("c", "BB — агрессор, потому что чек всегда означает передачу инициативы", "BB is the aggressor, because a check always hands over the initiative", "ROLE_INVENTED"),
    ],
    reasonOptions: [
      o("r1", "Кто первым добровольно поднял банк и кто на это ответил — разные события, даже если итоговая позиция и итоговый размер банка похожи на другой узел", "Who first voluntarily raised the pot and who responded to it are different events, even when the resulting positions and pot size resemble a different node"),
      o("r2", "Итоговый размер банка полностью определяет, кто был инициатором", "The final pot size fully determines who was the initiator", "POT_SIZE_AS_ROLE"),
      o("r3", "SB и BB всегда меняются ролями в зависимости от карты флопа", "SB and BB always swap roles depending on the flop card", "ROLE_FROM_BOARD"),
    ],
    correctActionId: "b", correctReasonId: "r1", targetSeconds: 24,
    explanationRu: "SB — voluntary raiser не в позиции, BB — коллер, защищающий блайнд против рейза. Это отдельное событие розыгрыша, а не переформулировка узла «SB check → BB raise → SB call» (PM-BL-09-ETC-101), даже если оба заканчиваются одним и тем же одиночным повышенным банком.",
    explanationEn: "SB is the voluntary raiser out of position; BB is the caller defending the blind against a raise. This is a distinct branch, not a restatement of the 'SB check → BB raise → SB call' node (PM-BL-09-ETC-101), even though both end up as a single raised pot.",
  },
  {
    id: "PM-BL-10-ETC-102", skillId: "BL-10", kind: "changed", sourceRefs: ["SLC-BB-VS-SB", "LCM-03"],
    assumptions: ["5/5 равные блайнды", "один и тот же флоп K72 без масти в двух раздачах", "сравниваются два разных префлоп-пути"],
    cueRu: "Тот же флоп K♦7♣2♠ в двух раздачах. В первой: SB чекнул, BB чекнул. Во второй: SB чекнул, BB поднял, SB уравнял.",
    cueEn: "The same flop K♦7♣2♠ in two hands. Node A: SB checks, BB checks. Node B: SB checks, BB raises, SB calls.",
    questionRu: "Можно ли применить к раздаче со вторым сценарием ту же постфлоп-эвристику, что и к первой, раз доска и позиции совпадают?",
    questionEn: "Can node B use the same postflop heuristic as node A, since the board and positions match?",
    actionOptions: [
      o("a", "Да — совпадение доски и позиций само по себе гарантирует одинаковую стратегию", "Yes — the matching board and positions alone guarantee the same strategy", "BOARD_LABEL_SHORTCUT"),
      o("b", "Нет — префлоп-путь разный, поэтому выжившие диапазоны и распределение инициативы тоже разные", "No — the preflop path differs, so the surviving ranges and the initiative distribution differ too"),
      o("c", "Да, но только если банк на флопе одинакового размера", "Yes, but only if the flop pot is the same size", "POT_SIZE_AS_ROLE"),
    ],
    reasonOptions: [
      o("r1", "Радужная сухая доска сама задаёт единственно верную линию независимо от истории торгов", "A dry rainbow board by itself dictates the one correct line regardless of the betting history", "BOARD_LABEL_SHORTCUT"),
      o("r2", "В первой раздаче ни один диапазон не сузился рейзом, а во второй диапазон SB прошёл через рейз и колл BB — на одной и той же доске это разные выжившие диапазоны", "In node A neither range was narrowed by a raise, while in node B SB's range passed through a raise and a call — on the same board these are different surviving ranges"),
      o("r3", "Позиция важнее любой информации о префлоп-действиях", "Position matters more than any information about preflop actions", "ANCESTRY_IGNORED"),
    ],
    correctActionId: "b", correctReasonId: "r2", targetSeconds: 26,
    explanationRu: "Семейство доски ≠ действие. Один и тот же флоп после разных префлоп-путей несёт разное владение диапазоном: в первой раздаче диапазоны симметрично неотфильтрованы, во второй BB становится позиционным префлоп-агрессором против дважды отфильтрованного диапазона SB.",
    explanationEn: "Board family does not equal action. The same flop after different preflop paths carries different range ownership: node A is symmetrically unfiltered, while node B makes BB the in-position preflop aggressor against a twice-filtered SB range.",
    changedVariables: ["preflop_path", "surviving_range"],
  },
  {
    id: "PM-BL-06-ETC-103", skillId: "BL-06", kind: "boundary", sourceRefs: ["SLC-BB-VS-SB", "LCM-10"],
    assumptions: ["несколько предыдущих раздач 5/5 blind-vs-blind закончились разделом банка без единой ставки"],
    cueRu: "В нескольких предыдущих раздачах 5/5 blind-vs-blind оба игрока чекнули банк без единой ставки — банк просто разделили.",
    cueEn: "In several previous 5/5 blind-vs-blind hands, both players checked the pot down with no bet at all — the pot was simply split.",
    questionRu: "Доказывает ли это, что SB играет пассивно и туго, а BB не проявляет агрессии?",
    questionEn: "Does this prove that SB plays passively/tight and BB shows no aggression?",
    actionOptions: [
      o("a", "Да — несколько повторов подряд уже статистически значимы", "Yes — several repeats in a row are already statistically meaningful", "EVIDENCE_OVERGENERALIZED"),
      o("b", "Нет — ни одна из этих раздач не прошла ни одной стратегической развилки", "No — none of these hands went through a single strategic branch"),
      o("c", "Да, но только про SB, а не про BB", "Yes, but only about SB, not about BB", "EVIDENCE_OVERGENERALIZED"),
    ],
    reasonOptions: [
      o("r1", "Любое совпадение результата в нескольких раздачах подряд — уже надёжный профиль игрока", "Any matching outcome across several hands in a row is already a reliable player profile", "EVIDENCE_OVERGENERALIZED"),
      o("r2", "Разделённый банк всегда означает, что оба игрока держали слабые руки", "A split pot always means both players held weak hands", "SHOWDOWN_WITHOUT_ACTION"),
      o("r3", "Разделённый без единой ставки банк — это отсутствие розыгрыша стратегической ветки; такие раздачи нельзя засчитывать как наблюдение за поведением игрока в реальном решении", "A pot split with no bet at all means no strategic branch was played out; such hands cannot count as an observation of a player's behavior in an actual decision"),
    ],
    correctActionId: "b", correctReasonId: "r3", targetSeconds: 26,
    explanationRu: "Граница правила: opponent-evidence должно опираться на реально сыгранные развилки (ставка, колл, рейз, фолд под давлением). Чекнутый до конца банк без единой ставки не содержит такой развилки и не может подтверждать или опровергать стиль игрока.",
    explanationEn: "Boundary: opponent evidence must rest on branches that were actually played (a bet, a call, a raise, a fold under pressure). A pot checked down with no bet at all contains no such branch and cannot confirm or refute a player's style.",
  },
  {
    id: "PM-DEEP-03-ETC-101", skillId: "DEEP-03", kind: "boundary", sourceRefs: ["LCM-01"],
    assumptions: ["игра 5/5 с обязательным straddle 10", "планируется префлоп-глубина"],
    cueRu: "Игра 5/5 с обязательным straddle 10. Нужно спланировать префлоп-глубину.",
    cueEn: "5/5 game with a mandatory 10 straddle. Preflop depth needs to be planned.",
    questionRu: "Какая единица становится рабочим ориентиром для префлоп-планирования при таком straddle?",
    questionEn: "Which unit becomes the working reference for preflop planning under this straddle?",
    actionOptions: [
      o("a", "По-прежнему $5, потому что это номинальный большой блайнд", "Still $5, because that is the nominal big blind", "NOMINAL_STACK_ONLY"),
      o("b", "Среднее между $5 и $10", "An average between $5 and $10", "DEPTH_MISREAD"),
      o("c", "$10 — размер обязательного straddle", "$10 — the size of the mandatory straddle"),
    ],
    reasonOptions: [
      o("r1", "Straddle — последняя вынужденная ставка перед первым добровольным действием, поэтому именно она задаёт рабочую единицу для префлоп-планирования; фактический банк и текущий SPR на постфлопе считаются уже от реального остатка стека на тот момент", "The straddle is the last forced bet before the first voluntary action, so it sets the working unit for preflop planning; the actual pot and current SPR postflop are then computed from the real remaining stack at that point"),
      o("r2", "Straddle никогда не меняет рабочую единицу, потому что номинальный блайнд остаётся прежним", "A straddle never changes the working unit, because the nominal blind stays the same", "NOMINAL_STACK_ONLY"),
      o("r3", "Глубина 300bb всегда означает одну и ту же стратегию независимо от straddle", "300bb depth always means the same strategy regardless of the straddle", "DEPTH_MISREAD"),
    ],
    correctActionId: "c", correctReasonId: "r1", targetSeconds: 24,
    explanationRu: "DEEP-03: straddle сдвигает forced unit и порядок действий. Планирование ведётся от $10, а не от $5; при этом $1500 не превращаются автоматически в фиксированную «стратегию 300bb» — постфлопный SPR по-прежнему считается от текущего банка и текущего остатка стека.",
    explanationEn: "DEEP-03: a straddle shifts the forced unit and the action order. Planning runs from $10, not $5; this does not automatically turn $1500 into a fixed '300bb strategy' — postflop SPR is still computed from the current pot and current remaining stack.",
  },

  // ---------------------------------------------------------------------
  // Section B — turn fast classifier (TURN-01 classification, TURN-02 boundary)
  // ---------------------------------------------------------------------
  {
    id: "PM-TURN-01-ETC-101", skillId: "TURN-01", kind: "recognition", sourceRefs: ["FTGU-E21"],
    assumptions: ["BTN против BB, single-raised pot", "флоп K72 без масти, Hero ставит треть банка, BB коллирует", "терн — карта без масти доски"],
    cueRu: "BTN против BB, single-raised pot. Флоп K♦7♣2♠, Hero ставит треть банка, BB коллирует. Терн — 4♥.",
    cueEn: "BTN versus BB, single-raised pot. Flop K♦7♣2♠, Hero bets a third pot, BB calls. Turn is 4♥.",
    questionRu: "Как классифицировать эту карту терна для дальнейшего решения?",
    questionEn: "How should this turn card be classified for the next decision?",
    actionOptions: [
      o("a", "Карта, закрывающая дро — она меняет состав выжившего диапазона коллера", "A draw-completing card — it changes the composition of the caller's surviving range", "RUNOUT_MISCLASSIFIED"),
      o("b", "Карта, спаривающая доску, которая требует пересчёта владения натсами", "A board-pairing card that requires recomputing nut ownership", "RUNOUT_MISCLASSIFIED"),
      o("c", "Бланк — карта заметно не улучшает типичные продолжения коллера", "A blank — the card does not materially improve the caller's typical continues"),
    ],
    reasonOptions: [
      o("r1", "Любая новая карта обязана менять решение независимо от её ранга", "Any new card must change the decision regardless of its rank", "ANY_CARD_MATTERS"),
      o("r2", "4♥ не усиливает типичные руки, дошедшие до этого узла через колл флопа, и не меняет распределение владения доской", "4♥ does not strengthen the typical hands that reached this node via a flop call, and does not shift board ownership"),
      o("r3", "Бланк-терн всегда означает, что нужно продолжать давление тем же сайзингом", "A blank turn always means Hero should keep pressuring with the same sizing", "BLANK_AS_BARREL"),
    ],
    correctActionId: "c", correctReasonId: "r2", targetSeconds: 18,
    explanationRu: "FTGU-E21: 4♥ не закрывает правдоподобные дро на этой доске и не спаривает флоп, поэтому владение диапазоном практически не меняется относительно флопа — это классический бланк. Сама классификация не решает, продолжать ли ставить (см. отдельные границы про ремонтную карту и бланк ниже).",
    explanationEn: "FTGU-E21: 4♥ does not complete a plausible draw on this board and does not pair the flop, so range ownership barely shifts from the flop — a textbook blank. Classification alone does not decide whether to keep betting (see the REPAIR/BLANK ≠ ACTION boundary items).",
  },
  {
    id: "PM-TURN-01-ETC-102", skillId: "TURN-01", kind: "recognition", sourceRefs: ["FTGU-E21", "FTGU-E20"],
    assumptions: ["флоп J♠8♠6♦, Hero ставит, коллер уравнивает", "терн 9♠"],
    cueRu: "Флоп J♠8♠6♦. Hero ставит, коллер уравнивает. Терн — 9♠.",
    cueEn: "Flop J♠8♠6♦. Hero bets, the caller calls. Turn is 9♠.",
    questionRu: "К какому классу относится 9♠ и какой вопрос нужно задать следующим?",
    questionEn: "Which class does 9♠ belong to, and what question comes next?",
    actionOptions: [
      o("a", "Бланк — коллер не мог держать ничего, что усиливается этой картой", "A blank — the caller could not hold anything strengthened by this card", "RUNOUT_MISCLASSIFIED"),
      o("b", "Спаренная доска — нужно заново оценить владение сетами", "A paired board — set ownership needs to be reassessed", "RUNOUT_MISCLASSIFIED"),
      o("c", "Ремонтная карта: она усиливает несколько правдоподобных продолжений коллера (T9, 98, 97, 75, дро на флеш и комбо-дро), значит дальше нужно спросить, чей топовый диапазон реально улучшился", "A repair card: it strengthens several plausible continues of the caller (T9, 98, 97, 75, flush draws and combo draws), so next the question is whose top range actually improved"),
    ],
    reasonOptions: [
      o("r1", "9♠ никогда не меняет диапазон, потому что коллер уже был отфильтрован флопом", "9♠ never changes the range, because the caller was already filtered by the flop", "ANCESTRY_OVERWEIGHTED"),
      o("r2", "Любая карта девятки автоматически означает чек", "Any nine automatically means a check", "REPAIR_AS_CHECK"),
      o("r3", "На этой доске множество естественных продолжений коллера с флопа доходят до стрита или сильного дро именно через девятку, поэтому нужно пересчитать, чей диапазон реально усилился, прежде чем выбирать действие", "On this board, many natural flop continues of the caller reach a straight or a strong draw precisely through a nine, so it is necessary to recompute whose range actually strengthened before choosing an action"),
    ],
    correctActionId: "c", correctReasonId: "r3", targetSeconds: 20,
    explanationRu: "FTGU-E21/E20: на связанных двухмастных досках 9 закрывает частые продолжения коллера (T9, 98, 97, 75, комбо-дро). Классификация REPAIR — это триггер пересчёта владения, а не готовый ответ check/bet.",
    explanationEn: "FTGU-E21/E20: on connected two-tone boards, a 9 completes frequent caller continues (T9, 98, 97, 75, combo draws). The REPAIR classification is a trigger to recompute ownership, not a ready-made check/bet answer.",
  },
  {
    id: "PM-TURN-01-ETC-103", skillId: "TURN-01", kind: "recognition", sourceRefs: ["FTGU-E21"],
    assumptions: ["флоп K72 без масти, Hero — префлоп- и флоп-агрессор, ставит, BB коллирует широким диапазоном", "терн Q"],
    cueRu: "Флоп K♦7♣2♠. Hero — префлоп- и флоп-агрессор, ставит, BB коллирует широким диапазоном. Терн — Q♥.",
    cueEn: "Flop K♦7♣2♠. Hero is the preflop and flop aggressor, bets, BB calls with a wide continuing range. Turn is Q♥.",
    questionRu: "Что происходит с диапазонами на этой карте терна?",
    questionEn: "What happens to the ranges on this turn card?",
    actionOptions: [
      o("a", "Карта непропорционально усиливает верхнюю часть диапазона агрессора: дама добавляет новые топ-пары туда, где у коллера симметричного усиления нет", "The card disproportionately strengthens the aggressor's top range: the queen adds new top pairs where the caller gets no symmetric improvement"),
      o("b", "Любая старшая карта на терне автоматически считается усилением агрессора без проверки диапазонов", "Any high turn card automatically counts as boosting the aggressor without checking ranges", "HIGH_CARD_ALWAYS_BOOST"),
      o("c", "Ничего не меняется — оба диапазона одинаково нейтральны к даме", "Nothing changes — both ranges are equally neutral to the queen", "RUNOUT_MISCLASSIFIED"),
    ],
    reasonOptions: [
      o("r1", "Дама всегда усиливает того, кто ставил на флопе, независимо от диапазонов", "A queen always strengthens whoever bet the flop, regardless of ranges", "HIGH_CARD_ALWAYS_BOOST"),
      o("r2", "Диапазон открытия и c-bet Hero на этой доске сохраняет заметную долю комбинаций с дамой, тогда как диапазон колла BB на K72 держит их заметно реже — усиление асимметрично в пользу агрессора", "Hero's opening and c-bet range on this board retains a clear share of queen combinations, while BB's calling range on K72 holds them far less often — the improvement is asymmetric toward the aggressor"),
      o("r3", "Усиление определяется исключительно тем, что карта выше карт флопа", "The improvement is determined solely by the card being higher than the flop cards", "HIGH_CARD_ALWAYS_BOOST"),
    ],
    correctActionId: "a", correctReasonId: "r2", targetSeconds: 20,
    explanationRu: "FTGU-E21: усиление (BOOST) — это асимметрия между диапазонами, а не свойство ранга карты самой по себе. «Старшая карта = boost» — недопустимый универсальный ярлык; нужно сравнивать, у кого из двух диапазонов реально больше комбинаций с этим номиналом.",
    explanationEn: "FTGU-E21: a boost is an asymmetry between ranges, not a property of the card's rank by itself. 'High card equals boost' is not a valid universal shortcut; the two ranges must be compared for who actually holds more combinations of that rank.",
  },
  {
    id: "PM-TURN-01-ETC-104", skillId: "TURN-01", kind: "recognition", sourceRefs: ["FTGU-E21"],
    assumptions: ["флоп Q83 без масти, Hero ставит, BB коллирует", "терн 8 — доска спаривается"],
    cueRu: "Флоп Q♠8♥3♦. Hero ставит, BB коллирует. Терн — 8♦, доска спаривается.",
    cueEn: "Flop Q♠8♥3♦. Hero bets, BB calls. Turn is 8♦, the board pairs.",
    questionRu: "Кто реально выигрывает от спаривания доски в этой ветке?",
    questionEn: "Who actually benefits from the pairing in this branch?",
    actionOptions: [
      o("a", "Нужно заново оценить владение сетами и трипсами по обоим диапазонам, а не просто объявить доску более сильной", "Both ranges' set/trips ownership must be reassessed, not just declaring the board 'stronger'"),
      o("b", "Спаривание всегда автоматически усиливает диапазон агрессора", "A pairing always automatically strengthens the aggressor's range", "PAIR_AS_POLARIZATION"),
      o("c", "Спаривание всегда означает поляризацию диапазона коллера", "A pairing always means the caller's range becomes polarized", "PAIR_AS_POLARIZATION"),
    ],
    reasonOptions: [
      o("r1", "Спаренная доска сама по себе меняет только размер банка", "A paired board by itself only changes the pot size", "RUNOUT_MISCLASSIFIED"),
      o("r2", "8♦ повышает ценность конкретных заготовок (88, Q8, 83 и похожих холдингов) в обоих диапазонах по отдельности; кто из двух диапазонов реально держит больше таких комбинаций на этой доске, и определяет, кому пара выгодна", "8♦ raises the value of specific holdings (88, Q8, 83 and similar) in both ranges separately; whichever range actually holds more of these combinations on this board is who the pairing favors"),
      o("r3", "После спаривания значение имеет только абсолютная сила руки Hero, без учёта диапазона соперника", "After a pairing, only Hero's absolute hand strength matters, without considering the opponent's range", "ABSOLUTE_HAND_ONLY"),
    ],
    correctActionId: "a", correctReasonId: "r2", targetSeconds: 21,
    explanationRu: "PAIR — триггер пересчёта владения натсами (сеты, трипсы, фулл-хаусы конкретных номиналов), а не автоматическая поляризация в чью-либо пользу. Нужно сравнить фактическое количество таких комбинаций в обоих диапазонах.",
    explanationEn: "PAIR is a trigger to recompute nut ownership (sets, trips, specific full houses), not an automatic polarization toward either side. The actual count of such combinations in both ranges must be compared.",
  },
  {
    id: "PM-TURN-01-ETC-105", skillId: "TURN-01", kind: "recognition", sourceRefs: ["FTGU-E21", "FTGU-E20"],
    assumptions: ["флоп двухмастный J♠8♠6♦, Hero ставит, BB коллирует", "терн 9♠ закрывает флеш-дро на пиках"],
    cueRu: "Флоп J♠8♠6♦ с двумя пиками. Hero ставит, BB коллирует. Терн — 9♠, флеш-дро на пиках закрылось.",
    cueEn: "Flop J♠8♠6♦ with two spades. Hero bets, BB calls. Turn is 9♠, completing the spade flush draw.",
    questionRu: "Какие именно дро правдоподобно дошли до этой карты и закрылись?",
    questionEn: "Which draws plausibly survived to this card and completed?",
    actionOptions: [
      o("a", "Только те дро, которые реально входят в диапазон колла флопа на этой доске: флеш-дро на пиках и релевантные стрит-дро, а не любое визуально пугающее сочетание", "Only the draws that actually belong to the flop-call range on this board: the spade flush draw and the relevant straight draws, not any visually scary combination"),
      o("b", "Любая завершающая карта одной масти означает, что нужно фолдить весь диапазон", "Any suit-completing card means folding the entire range", "SURPRISE_EQUALS_STRENGTH"),
      o("c", "Дро считаются закрытыми только если игрок уже показывал похожую руку раньше", "Draws only count as completed if the player has already shown a similar hand before", "SHOWDOWN_WITHOUT_ACTION"),
    ],
    reasonOptions: [
      o("r1", "Пугающий внешний вид карты сам по себе доказывает, что дро закрылось", "The scary look of the card by itself proves a draw completed", "SURPRISE_EQUALS_STRENGTH"),
      o("r2", "Замена карты никогда не меняет состав выжившего диапазона", "Changing the card never changes the composition of the surviving range", "RUNOUT_MISCLASSIFIED"),
      o("r3", "Диапазон колла флопа на этой доске правдоподобно включает дро на пиках и отдельные стрит-дро; именно эти комбинации реально улучшаются 9♠, а не любая рука с пиковой картой в принципе", "The flop-call range on this board plausibly includes the spade draw and specific straight draws; these are the combinations that genuinely improve with 9♠, not any hand with a spade in it at all"),
    ],
    correctActionId: "a", correctReasonId: "r3", targetSeconds: 21,
    explanationRu: "DRAW COMPLETE классифицируется по тому, что правдоподобно дошло до этого узла через колл флопа на конкретной доске, а не по визуальной «страшности» карты.",
    explanationEn: "DRAW COMPLETE is classified by what plausibly survived to this node through the flop call on this specific board, not by the card's visual scariness.",
  },
  {
    id: "PM-TURN-01-ETC-106", skillId: "TURN-01", kind: "changed", sourceRefs: ["FTGU-E21"],
    assumptions: ["одна и та же карта терна на одной доске в двух раздачах", "в первой раздаче: ставка на флопе — колл", "во второй раздаче: чек на флопе — чек"],
    cueRu: "Одна и та же карта терна на одной доске в двух раздачах. В первой: ставка на флопе — колл. Во второй: чек на флопе — чек.",
    cueEn: "The same turn card on the same board in two hands. Node A: flop bet — call. Node B: flop check — check.",
    questionRu: "Если визуальный класс карты терна одинаков в обоих узлах, должны ли владение диапазоном и действие оставаться теми же?",
    questionEn: "If the turn card's visual class looks the same in both nodes, must range ownership and the action stay the same?",
    actionOptions: [
      o("a", "Да — визуальный класс карты полностью определяет владение диапазоном", "Yes — the card's visual class fully determines range ownership", "BOARD_LABEL_SHORTCUT"),
      o("b", "Нет — история улицы флопа разная в двух узлах, поэтому выжившие диапазоны и владение доской тоже разные", "No — the flop-street history differs between the two nodes, so the surviving ranges and board ownership differ too"),
      o("c", "Да, если позиции игроков совпадают", "Yes, if the players' positions match", "BOARD_LABEL_SHORTCUT"),
    ],
    reasonOptions: [
      o("r1", "Ставка-колл на флопе фильтрует диапазон коллера иначе, чем чек-чек; один и тот же терн попадает на два разных набора выживших рук, поэтому класс карты не переносится автоматически на владение диапазоном", "A flop bet-call filters the caller's range differently than a check-check; the same turn card lands on two different sets of surviving hands, so the card's class does not automatically transfer to range ownership"),
      o("r2", "Класс карты терна не зависит от предыдущих действий по определению", "The turn card's class is independent of prior actions by definition", "ANCESTRY_IGNORED"),
      o("r3", "Разница имеет значение только если менялся размер ставки", "The difference only matters if the bet size changed", "SIZE_CONTEXT_IGNORED"),
    ],
    correctActionId: "b", correctReasonId: "r1", targetSeconds: 24,
    explanationRu: "Класс терна ≠ действие. Классификация терна — это ярлык текстуры, а история флопа определяет, какой набор рук реально дожил до этой карты в каждой из двух раздач.",
    explanationEn: "TURN CLASS ≠ ACTION. Turn classification is a texture label; street ancestry (what happened on the flop) determines which set of hands actually survived to this card in each of the two nodes.",
    changedVariables: ["flop_action"],
  },
  {
    id: "PM-TURN-02-ETC-101", skillId: "TURN-02", kind: "boundary", sourceRefs: ["FTGU-E21", "SLC-TURN-BARREL"],
    assumptions: ["терн — ремонтная карта, усиливающая часть продолжений коллера", "Hero всё ещё владеет достаточной долей топового диапазона", "SPR и цель ставки поддерживают агрессию"],
    cueRu: "Терн усиливает часть продолжений коллера (ремонтная карта). Но Hero всё ещё владеет достаточной долей топового диапазона, а SPR и цель ставки поддерживают агрессию.",
    cueEn: "The turn strengthens some of the caller's continues (a repair card). But Hero still owns enough of the top range, and SPR and the bet's job still support aggression.",
    questionRu: "Означает ли сама по себе ремонтная карта, что нужно чекнуть?",
    questionEn: "Does a repair card by itself mean Hero should check?",
    actionOptions: [
      o("a", "Да — любое усиление диапазона коллера обязывает чекнуть", "Yes — any strengthening of the caller's range obligates a check", "REPAIR_AS_CHECK"),
      o("b", "Нет — нужно заново собрать цепочку диапазон → владение → SPR/задача ставки → действие, а не остановиться на одной метке «ремонт»", "No — the chain range -> ownership -> SPR/bet job -> action must be rebuilt, not stopped at the single label 'repair'"),
      o("c", "Да, но только если терн той же масти, что и флеш-дро на флопе", "Yes, but only if the turn matches the flop's flush-draw suit", "REPAIR_AS_CHECK"),
    ],
    reasonOptions: [
      o("r1", "Ремонтная карта отменяет любую причину для ставки автоматически", "A repair card automatically cancels any reason to bet", "REPAIR_AS_CHECK"),
      o("r2", "Классификация терна — это только триггер для пересчёта, а не готовый ответ; если Hero всё ещё владеет достаточным топовым регионом и ставка сохраняет вэлью- или фолд-эквити-задачу, агрессия остаётся оправданной, несмотря на ремонт", "Turn classification is only a trigger to recompute, not a ready-made answer; if Hero still owns enough of the top region and the bet keeps a value or fold-equity job, aggression stays justified despite the repair"),
      o("r3", "Чек становится обязательным при любом терне, который называют ремонтным", "A check becomes mandatory on any turn labeled 'repair'", "REPAIR_AS_CHECK"),
    ],
    correctActionId: "b", correctReasonId: "r2", targetSeconds: 26,
    explanationRu: "Граница правила: ремонтная карта ≠ автоматический чек. Классификация терна лишь запускает пересчёт по цепочке диапазон → владение → SPR/задача ставки → действие; сама по себе метка ремонта не отменяет ставку.",
    explanationEn: "Boundary: REPAIR does not equal an automatic check. Turn classification only triggers the range -> ownership -> SPR/job -> action recompute; the repair label alone does not cancel a bet.",
  },
  {
    id: "PM-TURN-02-ETC-102", skillId: "TURN-02", kind: "boundary", sourceRefs: ["FTGU-E21", "SLC-TURN-BARREL"],
    assumptions: ["терн визуально бланковый", "колл на флопе уже сместил диапазон коллера к силе", "у Hero нет прибыльной вэлью- или фолд-эквити-задачи для второй ставки"],
    cueRu: "Терн визуально бланковый. Но колл на флопе уже сместил диапазон коллера к силе, и у Hero нет прибыльной вэлью- или фолд-эквити-задачи для второй ставки.",
    cueEn: "The turn looks visually blank. But the flop call already filtered the caller toward strength, and Hero has no profitable value or fold-equity job for a second bet.",
    questionRu: "Создаёт ли сам факт бланкового терна причину продолжать ставить?",
    questionEn: "Does the turn being blank by itself create a reason to keep betting?",
    actionOptions: [
      o("a", "Да — бланк всегда означает продолжение того же плана давления", "Yes — a blank always means continuing the same pressure plan", "BLANK_AS_BARREL"),
      o("b", "Да, потому что бланк никогда не меняет диапазон коллера", "Yes, because a blank never changes the caller's range", "BLANK_AS_BARREL"),
      o("c", "Нет — бланк не создаёт задачу для ставки сам по себе; нужно отдельно подтвердить вэлью- или фолд-эквити-цель против выжившего диапазона коллера", "No — a blank does not create a bet's job by itself; a value or fold-equity target against the caller's surviving range must be confirmed separately"),
    ],
    reasonOptions: [
      o("r1", "Отсутствие визуального усиления диапазона коллера равносильно наличию прибыльной цели для ставки", "The absence of a visible boost to the caller's range is equivalent to having a profitable bet target", "BLANK_AS_BARREL"),
      o("r2", "Бланковый терн автоматически поддерживает любой размер второй ставки", "A blank turn automatically supports any second-bet sizing", "BLANK_AS_BARREL"),
      o("r3", "Классификация «бланк» описывает только то, что карта не усилила противника; она не проверяет, есть ли у Hero конкретная вэлью- или фолд-эквити-задача против диапазона, уже отфильтрованного коллом на флопе", "The 'blank' classification only describes that the card did not strengthen the opponent; it does not check whether Hero has a concrete value or fold-equity job against a range already filtered by the flop call"),
    ],
    correctActionId: "c", correctReasonId: "r3", targetSeconds: 26,
    explanationRu: "Граница правила: бланк ≠ автоматическое продолжение давления. Отсутствие усиления соперника — не то же самое, что наличие задачи для ставки Hero; задачу нужно подтверждать отдельно от классификации карты.",
    explanationEn: "Boundary: BLANK does not equal an automatic barrel. The opponent not improving is not the same as Hero having a job for the bet; the job must be confirmed separately from the card classification.",
  },

  // ---------------------------------------------------------------------
  // Section C — board-family recognition speed (W4-BOARD-01)
  // ---------------------------------------------------------------------
  {
    id: "PM-W4-BOARD-01-ETC-101", skillId: "W4-BOARD-01", kind: "recognition", sourceRefs: ["FTGU-E07", "SLC-SRP-BOARD-CLASSES"],
    assumptions: ["флоп для быстрой классификации структурной текстуры"],
    cueRu: "Флоп K♦9♣4♠.",
    cueEn: "Flop K♦9♣4♠.",
    questionRu: "К какому структурному семейству относится эта доска?",
    questionEn: "Which structural board family does this flop belong to?",
    actionOptions: [
      o("a", "Низкая связанная доска", "A low connected board", "TEXTURE_MISREAD"),
      o("b", "Спаренная доска", "A paired board", "TEXTURE_MISREAD"),
      o("c", "Высокая сухая доска: одна доминирующая старшая карта, разномастная раскладка, без связок", "A high dry board: one dominant high card, rainbow suits, no connectivity"),
    ],
    reasonOptions: [
      o("r1", "Три разные масти сами по себе делают доску низкой", "Three different suits by themselves make the board low", "TEXTURE_MISREAD"),
      o("r2", "Наличие короля автоматически делает доску связанной", "Having a king automatically makes the board connected", "TEXTURE_MISREAD"),
      o("r3", "Одна старшая карта без второй близкой по рангу карты, разномастная раскладка и отсутствие соседних по номиналу карт — структурные признаки высокой сухой доски", "One high card with no second close-ranked card, rainbow suits, and no adjacent ranks are the structural markers of a high dry board"),
    ],
    correctActionId: "c", correctReasonId: "r3", targetSeconds: 15,
    explanationRu: "Высота, связанность и масти определяют семейство доски независимо от того, кто её разыгрывает. K94r — эталонная высокая сухая доска.",
    explanationEn: "Height, connectivity and suits determine the board family independent of who is playing it. K94r is a canonical high dry board.",
  },
  {
    id: "PM-W4-BOARD-01-ETC-102", skillId: "W4-BOARD-01", kind: "recognition", sourceRefs: ["FTGU-E07", "SLC-SRP-BOARD-CLASSES"],
    assumptions: ["флоп для быстрой классификации структурной текстуры"],
    cueRu: "Флоп 8♠7♠5♦.",
    cueEn: "Flop 8♠7♠5♦.",
    questionRu: "К какому структурному семейству относится эта доска?",
    questionEn: "Which structural board family does this flop belong to?",
    actionOptions: [
      o("a", "Высокая сухая доска", "A high dry board", "TEXTURE_MISREAD"),
      o("b", "Доска с двумя брод-картами", "A double-broadway board", "TEXTURE_MISREAD"),
      o("c", "Низкая связанная доска с двумя картами одной масти: близкие по номиналу карты плюс частичная мастевая связка", "A low connected board with two cards of one suit: close ranks plus a partial suit connection"),
    ],
    reasonOptions: [
      o("r1", "Отсутствие туза или короля само по себе делает доску несвязанной", "Missing an ace or king by itself makes the board disconnected", "TEXTURE_MISREAD"),
      o("r2", "Связанность определяется только количеством карт одной масти", "Connectivity is determined only by the number of same-suit cards", "TEXTURE_MISREAD"),
      o("r3", "Три низкие карты, две из которых соседние по номиналу и две — одной масти, создают много стритовых и флеш-дро — признаки низкой связанной доски", "Three low cards, two of them adjacent in rank and two of one suit, create many straight and flush draws — the markers of a low connected board"),
    ],
    correctActionId: "c", correctReasonId: "r3", targetSeconds: 15,
    explanationRu: "875 с двумя картами одной масти — эталонная низкая связанная доска с высокой плотностью дро; она структурно противоположна высокой сухой доске из предыдущего пункта.",
    explanationEn: "875 with two cards of one suit is a canonical low connected board with high draw density; it is the structural opposite of the high dry board from the previous item.",
  },
  {
    id: "PM-W4-BOARD-01-ETC-103", skillId: "W4-BOARD-01", kind: "changed", sourceRefs: ["FTGU-E07", "SLC-3BET-POTS"],
    assumptions: ["доска 8♠7♠5♦ одинакова в двух сравнениях", "в первой раздаче: BTN открывал, BB защищался, single-raised pot", "во второй: то же семейство доски в глубоком 3-bet pot, где агрессор не в позиции"],
    cueRu: "Одна и та же доска 8♠7♠5♦. В первой раздаче: BTN открывал, BB защищался, single-raised pot. Во второй: то же семейство доски в глубоком 3-bet pot, где агрессор не в позиции.",
    cueEn: "Same board 8♠7♠5♦. Node A: BTN opened, BB defended, single-raised pot. Node B: same board family in a deep 3-bet pot where the aggressor is out of position.",
    questionRu: "Меняется ли план розыгрыша этой доски между двумя раздачами?",
    questionEn: "Does the plan for this board change between node A and node B?",
    actionOptions: [
      o("a", "Нет — семейство доски одно и то же, значит план розыгрыша идентичен", "No — the board family is the same, so the plan is identical", "BOARD_LABEL_SHORTCUT"),
      o("b", "Нет, потому что низкая связанная доска всегда играется по одному шаблону", "No, because a low connected board always plays by one template", "BOARD_LABEL_SHORTCUT"),
      o("c", "Да — тип банка, позиция агрессора и состав пришедших диапазонов другие, поэтому владение доской и план нужно пересчитать заново", "Yes — the pot type, the aggressor's position and the composition of the arriving ranges are different, so board ownership and the plan must be recomputed"),
    ],
    reasonOptions: [
      o("r1", "Семейство доски однозначно определяет обязательство ставить независимо от банка", "The board family alone dictates the obligation to bet regardless of the pot type", "BOARD_LABEL_SHORTCUT"),
      o("r2", "3-bet pot и single-raised pot на одинаковой доске всегда разыгрываются одной и той же схемой", "A 3-bet pot and a single-raised pot on the same board always play by the same scheme", "BOARD_LABEL_SHORTCUT"),
      o("r3", "Тип банка меняет состав пришедших диапазонов (более узкие и полярные диапазоны в 3-bet pot), а позиция агрессора меняет чек/бет-стимулы; семейство доски описывает только текстуру, а не готовый план", "The pot type changes the composition of the arriving ranges (narrower, more polarized in a 3-bet pot), and the aggressor's position changes check/bet incentives; the board family only describes texture, not a ready-made plan"),
    ],
    correctActionId: "c", correctReasonId: "r3", targetSeconds: 26,
    explanationRu: "Семейство доски ≠ действие. Одна и та же доска в single-raised и в 3-bet pot несёт разные пришедшие диапазоны и разную позицию агрессора, поэтому план нужно пересчитывать заново, а не переносить по названию текстуры.",
    explanationEn: "BOARD FAMILY does not equal ACTION. The same board in a single-raised pot versus a 3-bet pot carries different arriving ranges and a different aggressor position, so the plan must be recomputed rather than transferred by the texture's name.",
    changedVariables: ["pot_type", "arriving_ranges"],
  },
  {
    id: "PM-W4-BOARD-01-ETC-104", skillId: "W4-BOARD-01", kind: "changed", sourceRefs: ["FTGU-E07", "SLC-MULTIWAY"],
    assumptions: ["доска K♠8♥3♦ одинакова в двух сравнениях", "в первой раздаче: розыгрыш один на один", "во второй: та же доска, но флоп видят три игрока"],
    cueRu: "Одна и та же доска K♠8♥3♦. В первой раздаче — один на один. Во второй — та же доска, но флоп видят три игрока.",
    cueEn: "Same board K♠8♥3♦. Node A: heads-up. Node B: same board, but three players see the flop.",
    questionRu: "Значит ли одинаковое семейство доски, что ставка несёт одну и ту же задачу в обоих узлах?",
    questionEn: "Does the same board family mean the bet carries the same job in both nodes?",
    actionOptions: [
      o("a", "Нет — при трёх игроках продолжающие диапазоны в среднем крепче, а правдоподобие блефа ниже, поэтому обязательство ставить нельзя переносить один в один из хедз-апа", "No — with three players the continuing ranges are on average stronger and a bluff is less credible, so the heads-up betting obligation cannot be transferred directly"),
      o("b", "Да — доска одна и та же, значит частота и размер ставки не меняются", "Yes — the board is the same, so bet frequency and sizing do not change", "BOARD_LABEL_SHORTCUT"),
      o("c", "Да — количество соперников влияет только на итоговый размер банка, а не на диапазоны", "Yes — the number of opponents only affects the final pot size, not the ranges", "MULTIWAY_IGNORED"),
    ],
    reasonOptions: [
      o("r1", "С ростом числа соперников, видящих флоп, продолжающие диапазоны в среднем сильнее, а правдоподобный объём блефов на такую линию меньше; семейство доски не отменяет этот multiway-эффект", "As the number of opponents seeing the flop grows, the continuing ranges are on average stronger and the credible bluff volume for this line is smaller; the board family does not cancel this multiway effect"),
      o("r2", "Семейство доски полностью определяет частоту ставки независимо от числа игроков", "The board family alone fully determines bet frequency regardless of player count", "BOARD_LABEL_SHORTCUT"),
      o("r3", "Хедз-ап и мультивей розыгрыши идентичны, если стартовые диапазоны заранее одинаковы", "Heads-up and multiway play are identical if the starting ranges are the same in advance", "MULTIWAY_IGNORED"),
    ],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 26,
    explanationRu: "Семейство доски ≠ действие также и при смене числа соперников: multiway-эффект (более крепкий продолжающий диапазон, меньше правдоподобных блефов) применяется поверх любого класса доски, включая ту же самую доску K83r.",
    explanationEn: "Board family does not equal action when the opponent count changes either: the multiway effect (a stronger continuing range, fewer credible bluffs) applies on top of any board class, including this same K83r board.",
    changedVariables: ["opponent_count", "arriving_ranges"],
  },
  {
    id: "PM-W4-BOARD-01-ETC-105", skillId: "W4-BOARD-01", kind: "changed", sourceRefs: ["FTGU-E07", "SLC-SRP-BOARD-CLASSES"],
    assumptions: ["доска K72 без масти одинакова в двух сравнениях", "в первой раздаче: открытие с BTN, BB защищался и увидел флоп", "во второй: та же доска после открытия с ранней позиции, BB защищался тем же образом"],
    cueRu: "Одна и та же доска K♠7♦2♣. В первой раздаче: открытие с BTN, BB защищался и увидел флоп. Во второй: та же доска после открытия с ранней позиции, BB защищался тем же образом.",
    cueEn: "Same board K♠7♦2♣. Node A: BTN opened, BB defended and saw the flop. Node B: the same board after an early-position open, BB defended the same way.",
    questionRu: "Совпадает ли владение этой доской в обеих раздачах, раз роли и видимая доска совпадают?",
    questionEn: "Does board ownership match between node A and node B, since the roles and the visible board look the same?",
    actionOptions: [
      o("a", "Нет — исходный диапазон открытия разный (широкий с BTN против узкого с ранней позиции), поэтому доля топовых комбинаций у агрессора на этой доске тоже разная", "No — the opening range's origin differs (wide from BTN versus tight from early position), so the aggressor's share of top combinations on this board differs too"),
      o("b", "Да — раз BB защищался в обоих случаях, диапазон BB после флопа одинаков", "Yes — since BB defended in both cases, BB's postflop range is the same", "SOURCE_RANGE_IGNORED"),
      o("c", "Да — семейство доски (высокая сухая) само определяет владение независимо от того, кто открывал", "Yes — the board family (high dry) alone determines ownership regardless of who opened", "BOARD_LABEL_SHORTCUT"),
    ],
    reasonOptions: [
      o("r1", "Позиция агрессора на префлопе не влияет на состав его диапазона на флопе", "The aggressor's preflop position does not affect the composition of the flop range", "SOURCE_RANGE_IGNORED"),
      o("r2", "Диапазон открытия с ранней позиции у́же и сильнее по номиналу, чем с BTN, поэтому на доске K72 доля топ-пар, сетов и сильных киккеров у агрессора с ранней позиции выше даже при формально той же роли и похожей доске", "The early-position opening range is tighter and stronger by rank than the BTN range, so on a K72 board the early-position aggressor holds a higher share of top pairs, sets and strong kickers, even with the formally same role and a similar-looking board"),
      o("r3", "Разница имеет значение только если BB тоже менял размер защиты", "The difference only matters if BB also changed the defense sizing", "SOURCE_RANGE_IGNORED"),
    ],
    correctActionId: "a", correctReasonId: "r2", targetSeconds: 26,
    explanationRu: "Семейство доски ≠ действие при смене источника диапазона агрессора: одна и та же доска и формально та же роль не переносят владение натсами, если исходный диапазон открытия узкий с ранней позиции против широкого с BTN.",
    explanationEn: "Board family does not equal action when the aggressor's source range changes: the same board and formally the same role do not transfer nut ownership when the opening range is tight from early position versus wide from BTN.",
    changedVariables: ["preflop_origin_range"],
  },

  // ---------------------------------------------------------------------
  // Section D — dynamic hand -> relative-role bridge (W4-REL-01)
  // ---------------------------------------------------------------------
  {
    id: "PM-W4-REL-01-ETC-101", skillId: "W4-REL-01", kind: "recognition", sourceRefs: ["FTGU-E07", "FTGU-E08"],
    assumptions: ["AA на флопе K72 без масти", "хедз-ап, Hero в позиции", "диапазон Hero на этой доске владеет заметной долей топовых комбинаций"],
    cueRu: "У Hero AA на флопе K♦7♣2♠. Хедз-ап, Hero в позиции, диапазон Hero на этой доске владеет заметной долей топовых комбинаций.",
    cueEn: "Hero holds AA on a K♦7♣2♠ flop. Heads-up, Hero in position, and Hero's range owns a clear share of the top combinations on this board.",
    questionRu: "Какова относительная роль AA здесь и какие более слабые руки могут продолжать против ставки?",
    questionEn: "What is AA's relative role here, and which worse hands can continue against a bet?",
    actionOptions: [
      o("a", "Сильная вэлью-рука: цель — построить банк против худших пар, части рук с королём и релевантных дро, которые реально входят в диапазон коллера на этой доске", "A strong value hand: the goal is to build the pot against worse pairs, part of the king-containing hands and relevant draws that actually belong to the caller's range on this board"),
      o("b", "Рука для чек-колла, потому что AA не улучшилась флопом", "A check-call hand, because AA did not improve on the flop", "ABSOLUTE_HAND_ONLY"),
      o("c", "Блеф-кэтчер, потому что доска содержит короля", "A bluff-catcher, because the board contains a king", "ABSOLUTE_HAND_ONLY"),
    ],
    reasonOptions: [
      o("r1", "AA — абсолютно сильнейшая комбинация, поэтому она всегда должна ставить максимальным размером", "AA is the absolute strongest combination, so it must always bet the maximum size", "ABSOLUTE_HAND_ONLY"),
      o("r2", "AA нужно разыгрывать пассивно, потому что она не топ-пара по номиналу доски", "AA should be played passively, because it is not top pair by the board's rank", "ABSOLUTE_HAND_ONLY"),
      o("r3", "На этой доске у диапазона Hero есть заметное преимущество по натсам, а в диапазоне коллера правдоподобно остаются худшие пары, часть рук с королём и готовые платить дро — это и определяет роль вэлью-руки, а не сам факт AA", "On this board Hero's range has a clear nut advantage, and the caller's range plausibly still holds worse pairs, part of the king-containing hands and draws willing to pay — this is what defines the value-hand role, not the fact of holding AA by itself"),
    ],
    correctActionId: "a", correctReasonId: "r3", targetSeconds: 22,
    explanationRu: "Название руки ≠ относительная роль. AA — это карточное название комбинации; её роль вэлью-руки здесь определяется владением диапазона на конкретной доске и наличием худших рук, готовых платить, а не абсолютным рангом руки самим по себе.",
    explanationEn: "HAND NAME does not equal RELATIVE ROLE. AA is the combination's label; its value-hand role here is defined by range ownership on this specific board and the presence of worse hands willing to pay, not by the hand's absolute rank alone.",
  },
  {
    id: "PM-W4-REL-01-ETC-102", skillId: "W4-REL-01", kind: "changed", sourceRefs: ["FTGU-E07", "FTGU-E08", "SLC-DEEP-SRP-OOP"],
    assumptions: ["AA — тот же карманный оверпэр", "доска меняется на 8♠7♠5♦", "Hero не в позиции, SPR глубокий"],
    cueRu: "У Hero тот же AA, но доска — 8♠7♠5♦, Hero не в позиции, а SPR глубокий.",
    cueEn: "Hero holds the same AA, but the board is 8♠7♠5♦, Hero is out of position, and SPR is deep.",
    questionRu: "Как меняется относительная роль AA по сравнению с K72 в позиции на мелком SPR?",
    questionEn: "How does AA's relative role change compared with K72 in position at a shallow SPR?",
    actionOptions: [
      o("a", "Не меняется — AA остаётся абсолютным оверпэром в обоих случаях и разыгрывается одинаково", "It does not change — AA remains an absolute overpair in both cases and plays the same way", "ABSOLUTE_HAND_ONLY"),
      o("b", "AA остаётся оверпэром по названию, но становится более уязвимой рукой: доска связана и на две масти, Hero не в позиции, а глубокий SPR повышает цену ошибки при автоматическом наращивании банка", "AA is still an overpair by name, but becomes a more vulnerable hand: the board is connected and two-toned, Hero is out of position, and deep SPR raises the cost of automatically building the pot"),
      o("c", "AA становится однозначно более сильной рукой, потому что глубокий SPR всегда увеличивает ценность пар", "AA becomes unambiguously stronger, because deep SPR always increases the value of pairs", "DEPTH_MISREAD"),
    ],
    reasonOptions: [
      o("r1", "Смена доски на низкую связанную двухмастную резко расширяет число дро и потенциальных двух пар/сетов у диапазона соперника, позиция ухудшает реализацию, а глубокий SPR повышает цену продолжения без чёткого плана — вместе это делает AA менее комфортной автоматической вэлью-рукой, чем на K72 в позиции", "Switching to a low connected two-tone board sharply widens the opponent's two-pair/set and draw potential, position worsens realization, and deep SPR raises the cost of continuing without a clear plan — together this makes AA a less comfortable automatic value hand than on K72 in position"),
      o("r2", "Абсолютная сила комбинации важнее любых изменений доски, позиции и SPR", "The combination's absolute strength outweighs any change in board, position and SPR", "ABSOLUTE_HAND_ONLY"),
      o("r3", "Глубина SPR не влияет на то, насколько уязвима рука на связанной доске", "SPR depth does not affect how vulnerable a hand is on a connected board", "DEPTH_MISREAD"),
    ],
    correctActionId: "b", correctReasonId: "r1", targetSeconds: 26,
    explanationRu: "Тот же карточный ярлык AA получает разную относительную роль: на K72 в позиции это комфортная вэлью-рука, а на связанной двухмастной доске не в позиции при глубоком SPR — уже более осторожная, требующая отдельного плана рука.",
    explanationEn: "The same card label AA gets a different relative role: on K72 in position it is a comfortable value hand, while on a connected two-tone board out of position at deep SPR it becomes a more cautious hand requiring its own plan.",
    changedVariables: ["board_class", "position", "spr"],
  },
  {
    id: "PM-W4-REL-01-ETC-103", skillId: "W4-REL-01", kind: "changed", sourceRefs: ["FTGU-E08", "FTGU-E22"],
    assumptions: ["у Hero одна пара, которую до этого момента разыгрывали как вэлью-руку", "терн-рейз от соперника с устойчивой историей пассивной игры и недоблефа именно в этой ветке"],
    cueRu: "У Hero одна пара, которую до этого момента разыгрывали как вэлью-руку. На терне соперник с устойчивой историей пассивной игры и недоблефа именно в этой ветке делает рейз.",
    cueEn: "Hero holds one pair that has been played as a value hand up to this point. On the turn, an opponent with a stable history of passive play and underbluffing in this exact branch raises.",
    questionRu: "Как должна измениться относительная роль руки Hero после этого рейза?",
    questionEn: "How should Hero's relative role change after this raise?",
    actionOptions: [
      o("a", "Роль не меняется — рука уже была объявлена вэлью и должна довести розыгрыш до конца", "The role does not change — the hand was already declared value and must play out to the end", "ROLE_LOCKED_IN"),
      o("b", "Роль сдвигается к блеф-кэтчеру или кандидату на фолд — против диапазона с малым числом естественных блефов именно в этой ветке маргинальная пара перестаёт быть автоматической вэлью-рукой", "The role shifts toward a bluff-catcher or a fold candidate — against a range with few natural bluffs in this exact branch, a marginal pair stops being an automatic value hand"),
      o("c", "Роль автоматически становится натсовой, потому что любой терн-рейз означает максимальную силу", "The role automatically becomes nutted, because any turn raise means maximum strength", "RAISE_ALWAYS_STRONG"),
    ],
    reasonOptions: [
      o("r1", "Название «вэлью-рука» фиксируется на флопе и не пересматривается позже", "The 'value hand' label is fixed on the flop and is never revisited later", "ROLE_LOCKED_IN"),
      o("r2", "Устойчивое наблюдение именно в этой ветке — конкретное свидетельство о низком реальном количестве блефов в диапазоне рейза; при таком свидетельстве прежняя вэлью-роль пары должна быть пересчитана, а не сохранена по инерции", "A stable observation in this exact branch is concrete evidence of a low real bluff count in the raising range; given that evidence, the pair's earlier value role must be recomputed, not kept out of inertia"),
      o("r3", "Любой терн-рейз всегда означает натсы независимо от истории соперника", "Any turn raise always means the nuts regardless of the opponent's history", "RAISE_ALWAYS_STRONG"),
    ],
    correctActionId: "b", correctReasonId: "r2", targetSeconds: 26,
    explanationRu: "Относительная роль не привязана к тому, как рука называлась на предыдущей улице. Branch-специфичное свидетельство о недоблефе меняет ожидаемый состав диапазона рейза, а значит и роль руки Hero — с вэлью на блеф-кэтчер или кандидата на фолд.",
    explanationEn: "The relative role is not locked to how the hand was labeled on an earlier street. Branch-specific evidence of underbluffing changes the expected composition of the raising range, and therefore Hero's hand role — from value to a bluff-catcher or fold candidate.",
    changedVariables: ["opponent_profile", "bluff_supply"],
  },
  {
    id: "PM-W4-REL-01-ETC-104", skillId: "W4-REL-01", kind: "decision", sourceRefs: ["FTGU-E08", "FTGU-E09"],
    assumptions: ["одна и та же доска и узел", "сравниваются натсовое комбо-дро и слабое дро без достаточного левериджа"],
    cueRu: "Одна и та же доска и узел. У Hero в одном случае — натсовое комбо-дро (например, флеш-дро до туза плюс стрит-дро), в другом — слабое дро без блокеров и без запасного плана.",
    cueEn: "Same board and node. In one case Hero holds a nut combo draw (e.g. the nut flush draw plus a straight draw); in the other, a weak draw with no blockers and no backup plan.",
    questionRu: "Какая из двух рук лучше подходит для агрессивного полублефа и почему?",
    questionEn: "Which of the two hands better supports an aggressive semi-bluff, and why?",
    actionOptions: [
      o("a", "Слабое дро — оно чаще застаёт соперника врасплох", "The weak draw — it more often catches the opponent by surprise", "SURPRISE_EQUALS_STRENGTH"),
      o("b", "Натсовое комбо-дро — оно лучше поддерживает агрессивный полублеф", "The nut combo draw — it better supports an aggressive semi-bluff"),
      o("c", "Обе руки одинаково подходят, потому что обе остаются дро до вскрытия", "Both hands are equally suitable, because both remain draws until showdown", "ABSOLUTE_HAND_ONLY"),
    ],
    reasonOptions: [
      o("r1", "Любое дро с двумя картами одной масти автоматически становится лучшим кандидатом для полублефа", "Any draw with two cards of one suit automatically becomes the best semi-bluff candidate", "SUIT_ALONE_SUFFICIENT"),
      o("r2", "Слабое дро безопаснее ставить, потому что при колле теряется меньше фишек", "The weak draw is safer to bet, because a call loses fewer chips", "SIZE_RESPONSE_BACKWARDS"),
      o("r3", "Натсовое комбо-дро сочетает более высокую эквити при колле, потенциал построить нат-руку, полезные блокеры против части сильных продолжений соперника и реальную фолд-эквити; слабое дро без этих признаков хуже держит агрессивную линию", "A nut combo draw combines higher equity when called, the potential to make the nut hand, useful blockers against part of the opponent's strong continues, and real fold equity; a weak draw without these features holds up worse in an aggressive line"),
    ],
    correctActionId: "b", correctReasonId: "r3", targetSeconds: 24,
    explanationRu: "Роль полублефующей руки определяется не тем, что она формально «дро», а качеством этого дро: эквити при колле, нат-потенциал, блокеры и реальная фолд-эквити. Слабое дро без этих признаков — худший кандидат для агрессии, даже если визуально похоже на сильное.",
    explanationEn: "The semi-bluffing role is decided not by the hand formally being 'a draw', but by the draw's quality: equity when called, nut potential, blockers and real fold equity. A weak draw without these features is a worse aggression candidate, even if it looks similar on the surface.",
  },
];

export const executionTransferClosureAnchors: PracticalAnchor[] = [
  {
    id: "W4-REL-01-A02", skillId: "W4-REL-01", kind: "mixed", sourceRefs: ["FTGU-E07", "FTGU-E21", "LCM-01"],
    assumptions: ["карточка компактно связывает уже обученные отдельно механизмы", "не заменяет W4/W9 распознавание и не вводит новое правило"],
    promptRu: "Как быстро связать распознавание доски/терна с итоговым действием за столом, не теряя причинную цепочку?",
    promptEn: "How to quickly connect board/turn recognition to the final table action without losing the causal chain?",
    answerRu: "Класс доски/терна → владелец диапазона → преимущество по диапазону (в основном подсказывает, как часто действовать) → преимущество по натсам/закрытость соперника (в основном подсказывает, каким размером) → SPR (ограничивает геометрию) → задача ставки → свидетельство → действие. Классификация сама по себе не определяет действие.",
    answerEn: "Board/turn class -> range owner -> range edge (mainly informs how often) -> nut edge/capped villain (mainly informs how big) -> SPR (constrains geometry) -> job -> evidence -> action. Classification alone does not determine the action.",
    rationaleRu: "Каждое звено — уже обученный отдельно механизм (W4 доска, W9 терн, FND-06 SPR, W4-REL-01 роль руки, RIV/TURN evidence-дисциплина). Карточка только компактно связывает их в одном порядке для быстрого исполнения за столом и не создаёт нового источника ответа.",
    rationaleEn: "Every link is a mechanism already trained separately (W4 board, W9 turn, FND-06 SPR, W4-REL-01 hand role, RIV/TURN evidence discipline). The card only compresses them into one order for fast table execution and creates no new source of truth.",
  },
];
