import type { PracticalDecision } from "./types";

const opt = (id: string, textRu: string, textEn: string, misconception?: string) => ({ id, textRu, textEn, misconception });

type Case = {
  id: string;
  skillId: string;
  kind: PracticalDecision["kind"];
  sourceRefs: string[];
  cueRu: string; cueEn: string;
  questionRu: string; questionEn: string;
  goodRu: string; goodEn: string;
  bad1Ru: string; bad1En: string;
  bad2Ru: string; bad2En: string;
  whyRu: string; whyEn: string;
  wrongWhyRu?: string; wrongWhyEn?: string;
  slot: 0 | 1 | 2;
  changedVariables?: string[];
};

function mk(c: Case): PracticalDecision {
  const good = opt("good", c.goodRu, c.goodEn);
  const bad1 = opt("bad1", c.bad1Ru, c.bad1En, "PRIMARY_MISCONCEPTION");
  const bad2 = opt("bad2", c.bad2Ru, c.bad2En, "SECONDARY_MISCONCEPTION");
  const actions = [good, bad1, bad2];
  const orderedActions = c.slot === 0 ? actions : c.slot === 1 ? [bad1, good, bad2] : [bad1, bad2, good];
  const reasonGood = opt("why", c.whyRu, c.whyEn);
  const reasonBad1 = opt("whyBad1", c.wrongWhyRu ?? "Initiative/label alone decides the node.", c.wrongWhyEn ?? "Initiative/label alone decides the node.", "SHORTCUT_REASON");
  const reasonBad2 = opt("whyBad2", "Context, sizing и surviving ranges не меняют решение.", "Context, sizing and surviving ranges do not change the decision.", "CONTEXT_IGNORED");
  const reasonSlot = (c.slot + 1) % 3;
  const reasons = reasonSlot === 0 ? [reasonGood, reasonBad1, reasonBad2] : reasonSlot === 1 ? [reasonBad1, reasonGood, reasonBad2] : [reasonBad1, reasonBad2, reasonGood];
  return {
    id: c.id, skillId: c.skillId, kind: c.kind, sourceRefs: c.sourceRefs,
    assumptions: ["single-raised pot", "mechanism-level source scope", "no exact solver frequency claimed"],
    cueRu: c.cueRu, cueEn: c.cueEn, questionRu: c.questionRu, questionEn: c.questionEn,
    actionOptions: orderedActions, reasonOptions: reasons,
    correctActionId: "good", correctReasonId: "why", targetSeconds: 25,
    explanationRu: c.whyRu, explanationEn: c.whyEn, changedVariables: c.changedVariables,
  };
}

const cases: Case[] = [
  // OOP-01 — range checking as PFR / protected checking.
  {id:"PM-OOP-01-101",skillId:"OOP-01",kind:"recognition",sourceRefs:["FTGU-E27"],cueRu:"PFR OOP, low/wet middling flop сильно взаимодействует с caller range.",cueEn:"PFR OOP on a low/wet middling flop that strongly interacts with the caller range.",questionRu:"Какой structural signal важнее initiative?",questionEn:"Which structural signal matters more than initiative?",goodRu:"Range disadvantage + positional disadvantage",goodEn:"Range disadvantage plus positional disadvantage",bad1Ru:"Сам факт preflop raise",bad1En:"The fact Hero raised preflop",bad2Ru:"Только absolute hand Hero",bad2En:"Only Hero's absolute hand",whyRu:"FTGU-E27 разрешает high-frequency/range checking OOP, когда caller лучше владеет board и position усиливает disadvantage.",whyEn:"FTGU-E27 supports high-frequency/range checking OOP when the caller owns the board better and position compounds the disadvantage.",slot:1},
  {id:"PM-OOP-01-102",skillId:"OOP-01",kind:"recognition",sourceRefs:["FTGU-E27"],cueRu:"Hero выбрал heavy-check strategy OOP.",cueEn:"Hero chooses a heavy-check strategy OOP.",questionRu:"Что должно быть внутри check range?",questionEn:"What must exist inside the checking range?",goodRu:"Calls, raises и folds",goodEn:"Calls, raises and folds",bad1Ru:"Только give-ups",bad1En:"Only give-ups",bad2Ru:"Только medium showdown hands",bad2En:"Only medium showdown hands",whyRu:"Range-check simplification работает только если check branch защищён strong calls/raises, а не автоматически capped.",whyEn:"A range-check simplification works only if the check branch is protected by strong calls/raises rather than being automatically capped.",slot:2},
  {id:"PM-OOP-01-103",skillId:"OOP-01",kind:"decision",sourceRefs:["FTGU-E27"],cueRu:"OOP PFR на board, где caller имеет concentrated pairs/connectors и Hero не имеет clear range advantage.",cueEn:"OOP PFR on a board where the caller has concentrated pairs/connectors and Hero lacks a clear range advantage.",questionRu:"Какое базовое упрощение здесь разумно?",questionEn:"Which default simplification is reasonable?",goodRu:"Check very often / consider range check",goodEn:"Check very often / consider a range check",bad1Ru:"Range-bet потому что Hero PFR",bad1En:"Range bet because Hero is PFR",bad2Ru:"Pot bet every value hand",bad2En:"Pot bet every value hand",whyRu:"Инициатива не создаёт postflop ownership; OOP disadvantage может оправдать protected checking tree.",whyEn:"Initiative does not create postflop ownership; the OOP disadvantage can justify a protected checking tree.",slot:0},
  {id:"PM-OOP-01-104",skillId:"OOP-01",kind:"decision",sourceRefs:["FTGU-E27"],cueRu:"После check opponent stab-ит слишком часто.",cueEn:"After Hero checks, the opponent stabs too frequently.",questionRu:"Что делает range-check simplification exploitatively stronger?",questionEn:"What can make the range-check simplification exploitatively stronger?",goodRu:"Активнее защищать check через calls/raises",goodEn:"Defend the check more actively with calls/raises",bad1Ru:"Сразу отказаться от checking",bad1En:"Abandon checking immediately",bad2Ru:"Fold весь medium region",bad2En:"Fold the entire medium region",whyRu:"E27 отмечает population over-stabbing как причину, по которой protected high-frequency check может зарабатывать больше.",whyEn:"E27 notes population over-stabbing as a reason a protected high-frequency check can earn more.",slot:1},
  {id:"PM-OOP-01-105",skillId:"OOP-01",kind:"decision",sourceRefs:["FTGU-E27"],cueRu:"Та же board family, но Hero теперь IP.",cueEn:"Same board family, but Hero is now IP.",questionRu:"Можно ли копировать OOP range-check simplification?",questionEn:"Can the OOP range-check simplification be copied?",goodRu:"Нет, IP нужен betting branch для value/pressure",goodEn:"No, IP still needs a betting branch for value/pressure",bad1Ru:"Да, board label тот же",bad1En:"Yes, the board label is the same",bad2Ru:"Да, initiative irrelevant everywhere",bad2En:"Yes, initiative is irrelevant everywhere",whyRu:"FTGU-E27 прямо ограничивает range-check simplification OOP; IP value region должен строить pot через selective betting.",whyEn:"FTGU-E27 explicitly limits the range-check simplification to OOP; IP value still needs selective betting to build the pot.",slot:2},
  {id:"PM-OOP-01-106",skillId:"OOP-01",kind:"changed",sourceRefs:["FTGU-E27"],cueRu:"Same ranges; flop меняется с caller-friendly low/wet на dry high-card.",cueEn:"Same ranges; the flop changes from caller-friendly low/wet to dry high-card.",questionRu:"Как двигается checking frequency?",questionEn:"Which way should checking frequency move?",goodRu:"Меньше forced range-check; betting branch растёт",goodEn:"Less forced range checking; betting branch grows",bad1Ru:"Ещё больше check только из-за OOP",bad1En:"Check even more solely because Hero is OOP",bad2Ru:"Не меняется",bad2En:"No change",whyRu:"Board-range ownership изменилось; OOP сам по себе не диктует одну frequency.",whyEn:"Board-range ownership changed; being OOP alone does not dictate one frequency.",slot:0,changedVariables:["board_class","range_advantage"]},
  {id:"PM-OOP-01-107",skillId:"OOP-01",kind:"changed",sourceRefs:["FTGU-E27"],cueRu:"Same board; caller range становится более condensed/strong.",cueEn:"Same board; the caller range becomes more condensed/strong.",questionRu:"Что происходит с autopilot c-bet?",questionEn:"What happens to an autopilot c-bet?",goodRu:"Становится менее привлекательным",goodEn:"It becomes less attractive",bad1Ru:"Становится обязательным",bad1En:"It becomes mandatory",bad2Ru:"Range source не важен",bad2En:"Range source is irrelevant",whyRu:"Одинаковый board с более сильным arriving caller range ухудшает ownership PFR.",whyEn:"The same board with a stronger arriving caller range worsens PFR ownership.",slot:1,changedVariables:["caller_range_shape"]},
  {id:"PM-OOP-01-108",skillId:"OOP-01",kind:"boundary",sourceRefs:["FTGU-E27"],cueRu:"Learner слышит «range check OOP» и применяет его на всех flops.",cueEn:"The learner hears 'range check OOP' and applies it on every flop.",questionRu:"Это корректная эвристика?",questionEn:"Is that a correct heuristic?",goodRu:"Нет — это board/range-specific simplification",goodEn:"No — it is a board/range-specific simplification",bad1Ru:"Да — OOP всегда range check",bad1En:"Yes — OOP always range checks",bad2Ru:"Да — PFR никогда не c-bet OOP",bad2En:"Yes — PFR never c-bets OOP",whyRu:"Boundary E27: range checking упрощает near-high-check nodes, а не заменяет всю OOP strategy.",whyEn:"E27 boundary: range checking simplifies near-high-check nodes; it does not replace all OOP strategy.",slot:2},

  // OOP-02 — check-call / check-fold.
  {id:"PM-OOP-02-101",skillId:"OOP-02",kind:"recognition",sourceRefs:["FTGU-E08","CP-G3-L05"],cueRu:"После check Hero facing bet с medium hand.",cueEn:"After checking, Hero faces a bet with a medium hand.",questionRu:"Что отличает call от fold кроме absolute rank?",questionEn:"What separates call from fold beyond absolute rank?",goodRu:"Price, stability/realisation и opponent range",goodEn:"Price, stability/realization and opponent range",bad1Ru:"Только pair label",bad1En:"Only the pair label",bad2Ru:"Только initiative до flop",bad2En:"Only preflop initiative",whyRu:"Call/fold branch зависит от цены и того, сможет ли hand реализовать equity против betting range.",whyEn:"The call/fold branch depends on price and whether the hand can realize equity against the betting range.",slot:0},
  {id:"PM-OOP-02-102",skillId:"OOP-02",kind:"recognition",sourceRefs:["FTGU-E08"],cueRu:"Strong hand остаётся в passive branch на low-urgency board.",cueEn:"A strong hand remains in the passive branch on a low-urgency board.",questionRu:"Что это делает с check-call range?",questionEn:"What does that do to the check-call range?",goodRu:"Защищает его от automatic pressure",goodEn:"It protects it from automatic pressure",bad1Ru:"Автоматически caps range",bad1En:"It automatically caps the range",bad2Ru:"Делает fold обязательным позже",bad2En:"It forces a later fold",whyRu:"E08 показывает, что strong calls могут защищать passive branch, особенно когда immediate raise не нужен.",whyEn:"E08 shows that strong calls can protect the passive branch when an immediate raise is not needed.",slot:1},
  {id:"PM-OOP-02-103",skillId:"OOP-02",kind:"decision",sourceRefs:["FTGU-E08","CP-G3-L05"],cueRu:"Small bet, hand имеет stable showdown value и reasonable future realisation.",cueEn:"Small bet; the hand has stable showdown value and reasonable future realization.",questionRu:"Какой branch получает больше веса?",questionEn:"Which branch gains weight?",goodRu:"Check-call",goodEn:"Check-call",bad1Ru:"Auto-fold medium hand",bad1En:"Auto-fold the medium hand",bad2Ru:"Auto-raise because price small",bad2En:"Auto-raise because the price is small",whyRu:"Хорошая цена и stable hand поддерживают call без необходимости превращать medium region в raise.",whyEn:"A good price and stable hand support calling without forcing the medium region into a raise.",slot:2},
  {id:"PM-OOP-02-104",skillId:"OOP-02",kind:"decision",sourceRefs:["FTGU-E08"],cueRu:"Large bet, weak bluff-catcher, плохая future realisation.",cueEn:"Large bet, weak bluff-catcher, poor future realization.",questionRu:"Какой branch получает больше веса?",questionEn:"Which branch gains weight?",goodRu:"Check-fold",goodEn:"Check-fold",bad1Ru:"Call потому что already checked",bad1En:"Call because Hero already checked",bad2Ru:"Raise to avoid hard decision",bad2En:"Raise to avoid a hard decision",whyRu:"Хуже price и слабая realisation повышают требования к continue region.",whyEn:"A worse price and weak realization raise the requirements for the continuing region.",slot:0},
  {id:"PM-OOP-02-105",skillId:"OOP-02",kind:"decision",sourceRefs:["FTGU-E08"],cueRu:"Opponent агрессивен и способен продолжать bluff later; hand достаточно stable.",cueEn:"Opponent is aggressive and likely to keep bluffing later; the hand is sufficiently stable.",questionRu:"Почему call может превзойти raise?",questionEn:"Why can calling outperform raising?",goodRu:"Сохраняет bluffs в tree и защищает passive range",goodEn:"It keeps bluffs in the tree and protects the passive range",bad1Ru:"Raise всегда получает больше value",bad1En:"A raise always earns more value",bad2Ru:"Call делает opponent value исчезнуть",bad2En:"Calling makes opponent value disappear",whyRu:"E08 поддерживает slow-play/call branch, когда later aggression вероятна и urgency низкая.",whyEn:"E08 supports a slow-play/call branch when later aggression is likely and urgency is low.",slot:1},
  {id:"PM-OOP-02-106",skillId:"OOP-02",kind:"changed",sourceRefs:["FTGU-E08"],cueRu:"Same hand/ranges; bet size меняется small → large.",cueEn:"Same hand/ranges; bet size changes small → large.",questionRu:"Куда двигается marginal call?",questionEn:"Which way does a marginal call move?",goodRu:"К fold",goodEn:"Toward fold",bad1Ru:"К call из-за larger pot",bad1En:"Toward call because the pot is larger",bad2Ru:"Не меняется",bad2En:"No change",whyRu:"Цена continue ухудшается; one-hand threshold нельзя копировать между sizing-ами.",whyEn:"The continuation price worsens; one hand threshold cannot be copied across sizings.",slot:2,changedVariables:["bet_size","pot_odds"]},
  {id:"PM-OOP-02-107",skillId:"OOP-02",kind:"changed",sourceRefs:["FTGU-E08"],cueRu:"Same hand/size; board становится более dynamic и hand теряет stability.",cueEn:"Same hand/size; the board becomes more dynamic and the hand loses stability.",questionRu:"Как меняется passive call attractiveness?",questionEn:"How does passive-call attractiveness change?",goodRu:"Снижается",goodEn:"It decreases",bad1Ru:"Растёт автоматически",bad1En:"It rises automatically",bad2Ru:"Board не влияет на realisation",bad2En:"The board does not affect realization",whyRu:"Будущая vulnerability ухудшает equity realisation даже при той же immediate price.",whyEn:"Future vulnerability worsens equity realization even at the same immediate price.",slot:0,changedVariables:["board_dynamism","hand_stability"]},
  {id:"PM-OOP-02-108",skillId:"OOP-02",kind:"boundary",sourceRefs:["FTGU-E08"],cueRu:"Learner трактует call-only concept как «никогда не fold».",cueEn:"The learner interprets a call-only concept as 'never fold'.",questionRu:"Верно?",questionEn:"Correct?",goodRu:"Нет — call-only убирает raises, но сохраняет calls и folds",goodEn:"No — call-only removes raises but keeps calls and folds",bad1Ru:"Да — весь range call",bad1En:"Yes — the whole range calls",bad2Ru:"Да — fold запрещён после check",bad2En:"Yes — folding is forbidden after checking",whyRu:"FTGU-E08 explicitly separates call-only response structure from calling the entire range.",whyEn:"FTGU-E08 explicitly separates a call-only response structure from calling the entire range.",slot:1},

  // OOP-03 — check-raise.
  {id:"PM-OOP-03-101",skillId:"OOP-03",kind:"recognition",sourceRefs:["FTGU-E09","FTGU-E10"],cueRu:"Strong made hand OOP очень vulnerable к turn cards.",cueEn:"A strong made hand OOP is highly vulnerable to turn cards.",questionRu:"Что повышает urgency raise?",questionEn:"What increases raise urgency?",goodRu:"Immediate value + protection/equity denial",goodEn:"Immediate value plus protection/equity denial",bad1Ru:"Сам факт made hand",bad1En:"Merely being a made hand",bad2Ru:"Только размер preflop pot",bad2En:"Only the preflop pot size",whyRu:"E09 связывает aggressive raise branch с vulnerability, value now и equity denial.",whyEn:"E09 links the aggressive raise branch to vulnerability, immediate value and equity denial.",slot:2},
  {id:"PM-OOP-03-102",skillId:"OOP-03",kind:"recognition",sourceRefs:["FTGU-E09"],cueRu:"Hero выбирает bluff check-raise candidate.",cueEn:"Hero chooses a bluff check-raise candidate.",questionRu:"Какие свойства важнее low absolute rank?",questionEn:"Which properties matter more than low absolute rank?",goodRu:"Low showdown + improvement/nut potential + future barrelability",goodEn:"Low showdown plus improvement/nut potential plus future barrelability",bad1Ru:"Самая слабая рука range",bad1En:"The absolute weakest hand in range",bad2Ru:"Любой blocker без context",bad2En:"Any blocker without context",whyRu:"Polar bluff не равен bottom-of-range; candidate должен иметь полезные future properties.",whyEn:"A polar bluff is not simply the bottom of range; the candidate needs useful future properties.",slot:0},
  {id:"PM-OOP-03-103",skillId:"OOP-03",kind:"decision",sourceRefs:["FTGU-E09"],cueRu:"Hero top pair вероятно впереди betting range, но после raise продолжат в основном сильнее.",cueEn:"Hero's top pair is probably ahead of the betting range, but mostly stronger hands continue versus a raise.",questionRu:"Это value raise?",questionEn:"Is this a value raise?",goodRu:"Не обязательно; оценить against continuing range",goodEn:"Not necessarily; evaluate versus the continuing range",bad1Ru:"Да, best hand = value raise",bad1En:"Yes, best hand equals value raise",bad2Ru:"Да, top pair всегда raise",bad2En:"Yes, top pair always raises",whyRu:"E09 explicitly rejects 'probably best therefore raise'; value threshold is versus the continuation range.",whyEn:"E09 explicitly rejects 'probably best therefore raise'; the value threshold is versus the continuing range.",slot:1},
  {id:"PM-OOP-03-104",skillId:"OOP-03",kind:"decision",sourceRefs:["FTGU-E10"],cueRu:"Betting range opponent merged и содержит много worse made hands.",cueEn:"Opponent's betting range is merged and contains many worse made hands.",questionRu:"Как может измениться raise shape?",questionEn:"How can the raise shape change?",goodRu:"Может стать более merged/value-dense",goodEn:"It can become more merged/value-dense",bad1Ru:"Всегда остаётся nutted polar",bad1En:"It always remains nutted polar",bad2Ru:"Merged betting range запрещает raises",bad2En:"A merged betting range prohibits raises",whyRu:"E10 позволяет merged raising против range, где worse hands действительно продолжают/дают immediate value.",whyEn:"E10 allows more merged raising against a range where worse hands genuinely continue and provide immediate value.",slot:2},
  {id:"PM-OOP-03-105",skillId:"OOP-03",kind:"decision",sourceRefs:["FTGU-E09"],cueRu:"Board wet, Hero OOP, strong value hand может потерять action/strength на многих turns.",cueEn:"Wet board, Hero OOP, strong value can lose action/strength on many turns.",questionRu:"Какой branch чаще получает вес?",questionEn:"Which branch tends to gain weight?",goodRu:"Raise now",goodEn:"Raise now",bad1Ru:"Always slow-play",bad1En:"Always slow-play",bad2Ru:"Fold to protect stack",bad2En:"Fold to protect the stack",whyRu:"Высокая urgency делает immediate extraction/protection ценнее delayed play.",whyEn:"High urgency makes immediate extraction/protection more valuable than delayed play.",slot:0},
  {id:"PM-OOP-03-106",skillId:"OOP-03",kind:"changed",sourceRefs:["FTGU-E09"],cueRu:"Same value hand; board меняется dry/static → wet/dynamic.",cueEn:"Same value hand; board changes dry/static → wet/dynamic.",questionRu:"Как двигается raise urgency?",questionEn:"Which way does raise urgency move?",goodRu:"Вверх",goodEn:"Up",bad1Ru:"Вниз",bad1En:"Down",bad2Ru:"Не меняется",bad2En:"No change",whyRu:"Больше damaging turns увеличивают цену passive delay.",whyEn:"More damaging turns increase the cost of passive delay.",slot:1,changedVariables:["board_dynamism","vulnerability"]},
  {id:"PM-OOP-03-107",skillId:"OOP-03",kind:"changed",sourceRefs:["FTGU-E09","FTGU-E10"],cueRu:"Same Hero hand; opponent betting range меняется polar → merged.",cueEn:"Same Hero hand; opponent betting range changes polar → merged.",questionRu:"Как меняется medium raise candidate?",questionEn:"How does a medium raise candidate change?",goodRu:"Может стать лучше как merged value/protection raise",goodEn:"It can improve as a merged value/protection raise",bad1Ru:"Всегда хуже",bad1En:"Always worse",bad2Ru:"Opponent range shape irrelevant",bad2En:"Opponent range shape is irrelevant",whyRu:"Raise value depends on what worse hands bet and continue, not a fixed hand label.",whyEn:"Raise value depends on which worse hands bet and continue, not a fixed hand label.",slot:2,changedVariables:["opponent_bet_shape"]},
  {id:"PM-OOP-03-108",skillId:"OOP-03",kind:"boundary",sourceRefs:["FTGU-E09"],cueRu:"Hero имеет best hand против full betting range, но не против continuing range.",cueEn:"Hero has the best hand versus the full betting range but not versus the continuing range.",questionRu:"Достаточно ли этого для value raise?",questionEn:"Is that sufficient for a value raise?",goodRu:"Нет",goodEn:"No",bad1Ru:"Да, потому что ahead overall",bad1En:"Yes, because Hero is ahead overall",bad2Ru:"Да, если Hero OOP",bad2En:"Yes if Hero is OOP",whyRu:"Boundary: value raise должен зарабатывать против range, который продолжает после raise.",whyEn:"Boundary: a value raise must earn against the range that continues after the raise.",slot:0},

  // OOP-04 — defend vs small c-bet.
  {id:"PM-OOP-04-101",skillId:"OOP-04",kind:"recognition",sourceRefs:["FTGU-E08","SLC-HARD-CONTINUES"],cueRu:"Defender faces small c-bet.",cueEn:"Defender faces a small c-bet.",questionRu:"Как price влияет на fringe?",questionEn:"How does price affect the fringe?",goodRu:"Поддерживает больше marginal continues",goodEn:"It supports more marginal continues",bad1Ru:"Требует tighter range чем large bet",bad1En:"It requires a tighter range than a large bet",bad2Ru:"Sizing не влияет",bad2En:"Sizing does not matter",whyRu:"Small sizing предлагает лучшую цену и не должен автоматически выбивать medium/marginal region.",whyEn:"A small sizing offers a better price and should not automatically remove the medium/marginal region.",slot:1},
  {id:"PM-OOP-04-102",skillId:"OOP-04",kind:"recognition",sourceRefs:["FTGU-E08"],cueRu:"Small bet на low-urgency board; strong hand может call.",cueEn:"Small bet on a low-urgency board; a strong hand can call.",questionRu:"Почему strong calls полезны?",questionEn:"Why are strong calls useful?",goodRu:"Защищают call branch и сохраняют bluffs",goodEn:"They protect the calling branch and preserve bluffs",bad1Ru:"Чтобы never raise",bad1En:"So Hero never has to raise",bad2Ru:"Чтобы cap range",bad2En:"To cap the range",whyRu:"E08 показывает protected call-only structures, где strong hands остаются в call branch.",whyEn:"E08 shows protected call-only structures where strong hands remain in the calling branch.",slot:2},
  {id:"PM-OOP-04-103",skillId:"OOP-04",kind:"decision",sourceRefs:["FTGU-E08"],cueRu:"Small c-bet, marginal hand с reasonable equity/realisation.",cueEn:"Small c-bet, marginal hand with reasonable equity/realization.",questionRu:"Какой default против overfold autopilot?",questionEn:"Which default counters overfold autopilot?",goodRu:"Рассмотреть continue/call",goodEn:"Consider continuing/calling",bad1Ru:"Fold любую не-top-pair",bad1En:"Fold anything below top pair",bad2Ru:"Raise любой draw",bad2En:"Raise every draw",whyRu:"Цена small bet требует defend wider than a large polar sizing, subject to hand quality and range.",whyEn:"The price of a small bet supports wider defense than a large polar sizing, subject to hand quality and range.",slot:0},
  {id:"PM-OOP-04-104",skillId:"OOP-04",kind:"decision",sourceRefs:["SLC-HARD-CONTINUES"],cueRu:"Small bet часто получает automatic folds pool-а.",cueEn:"Small bets often receive automatic folds from the pool.",questionRu:"Какой exploit check сначала?",questionEn:"What exploit check comes first?",goodRu:"Есть ли у Hero enough hard continues, которые pool недозащищает",goodEn:"Whether Hero has enough hard continues that the pool under-defends",bad1Ru:"Call entire range",bad1En:"Call the entire range",bad2Ru:"Always check-raise",bad2En:"Always check-raise",whyRu:"Exploit — targeted defence of hands with sufficient properties, not indiscriminate anti-overfolding.",whyEn:"The exploit is targeted defense of hands with sufficient properties, not indiscriminate anti-overfolding.",slot:1},
  {id:"PM-OOP-04-105",skillId:"OOP-04",kind:"decision",sourceRefs:["FTGU-E08"],cueRu:"Small bet, but board extremely wet and Hero value highly vulnerable.",cueEn:"Small bet, but the board is extremely wet and Hero's value is highly vulnerable.",questionRu:"Does small size force call-only?",questionEn:"Does the small size force a call-only response?",goodRu:"Нет — urgency может вернуть raise",goodEn:"No — urgency can restore a raise",bad1Ru:"Да — small size prohibits raises",bad1En:"Yes — small size prohibits raises",bad2Ru:"Да — always call strong value",bad2En:"Yes — always call strong value",whyRu:"E08 call-only logic has wetness/vulnerability exceptions; response tree is contextual.",whyEn:"E08's call-only logic has wetness/vulnerability exceptions; the response tree is contextual.",slot:2},
  {id:"PM-OOP-04-106",skillId:"OOP-04",kind:"changed",sourceRefs:["FTGU-E08"],cueRu:"Same hand/board; c-bet меняется 25–33% → large.",cueEn:"Same hand/board; c-bet changes from small to large.",questionRu:"Как двигается fringe continue?",questionEn:"Which way does the fringe continue move?",goodRu:"К fold",goodEn:"Toward fold",bad1Ru:"К call",bad1En:"Toward call",bad2Ru:"Не меняется",bad2En:"No change",whyRu:"Цена ухудшается; small-bet defend нельзя копировать против large size.",whyEn:"The price worsens; small-bet defense cannot be copied versus a large size.",slot:0,changedVariables:["bet_size"]},
  {id:"PM-OOP-04-107",skillId:"OOP-04",kind:"changed",sourceRefs:["FTGU-E08"],cueRu:"Same small size; hand получает strong redraw/extra stability.",cueEn:"Same small size; the hand gains a strong redraw/extra stability.",questionRu:"Как меняется continue attractiveness?",questionEn:"How does continuation attractiveness change?",goodRu:"Растёт",goodEn:"It rises",bad1Ru:"Падает",bad1En:"It falls",bad2Ru:"Traits irrelevant",bad2En:"Traits are irrelevant",whyRu:"Лучше future realisation делает marginal price-based continue более устойчивым.",whyEn:"Better future realization makes a marginal price-based continue more robust.",slot:1,changedVariables:["hand_traits","redraw"]},
  {id:"PM-OOP-04-108",skillId:"OOP-04",kind:"boundary",sourceRefs:["FTGU-E08"],cueRu:"Learner слышит «не overfold к small bet».",cueEn:"The learner hears 'do not overfold to a small bet'.",questionRu:"Это означает call any two?",questionEn:"Does that mean call any two?",goodRu:"Нет — price расширяет viable region, но bottom всё ещё folds",goodEn:"No — price widens the viable region, but the bottom still folds",bad1Ru:"Да",bad1En:"Yes",bad2Ru:"Да, если OOP",bad2En:"Yes if OOP",whyRu:"Boundary E08: even call-only strategies retain folds.",whyEn:"E08 boundary: even call-only strategies retain folds.",slot:2},

  // OOP-05 — defend vs large c-bet.
  {id:"PM-OOP-05-101",skillId:"OOP-05",kind:"recognition",sourceRefs:["FTGU-E07","FTGU-E09"],cueRu:"Opponent uses large selective c-bet.",cueEn:"Opponent uses a large selective c-bet.",questionRu:"Какой range shape обычно implied?",questionEn:"Which range shape is usually implied?",goodRu:"Более polar/selective",goodEn:"More polar/selective",bad1Ru:"Более merged entire range",bad1En:"More merged entire range",bad2Ru:"Sizing ничего не говорит о shape",bad2En:"Sizing says nothing about shape",whyRu:"E07/E09 связывают larger sizing с более selective/polar value-bluff structure.",whyEn:"E07/E09 link larger sizing with a more selective/polar value-bluff structure.",slot:0},
  {id:"PM-OOP-05-102",skillId:"OOP-05",kind:"recognition",sourceRefs:["FTGU-E09"],cueRu:"Large bet на dynamic board.",cueEn:"Large bet on a dynamic board.",questionRu:"Что повышается для marginal continue?",questionEn:"What rises for a marginal continue?",goodRu:"Требование к equity/realisation/robustness",goodEn:"The requirement for equity/realization/robustness",bad1Ru:"Только желание defend frequency",bad1En:"Only the desire to hit a defense frequency",bad2Ru:"Ничего",bad2En:"Nothing",whyRu:"Worse price plus a stronger/selective betting range makes fragile continues more expensive.",whyEn:"A worse price plus a stronger/selective betting range makes fragile continues more expensive.",slot:1},
  {id:"PM-OOP-05-103",skillId:"OOP-05",kind:"decision",sourceRefs:["FTGU-E09"],cueRu:"Large polar bet; medium hand имеет low future robustness.",cueEn:"Large polar bet; a medium hand has low future robustness.",questionRu:"Какой default?",questionEn:"Which default?",goodRu:"Fold more often",goodEn:"Fold more often",bad1Ru:"Call because pot is large",bad1En:"Call because the pot is large",bad2Ru:"Raise to protect equity",bad2En:"Raise to protect equity",whyRu:"Large size charges the continue and medium hands face a stronger continuation model.",whyEn:"A large size charges the continue and medium hands face a stronger continuation model.",slot:2},
  {id:"PM-OOP-05-104",skillId:"OOP-05",kind:"decision",sourceRefs:["FTGU-E09"],cueRu:"Large bet; Hero strong draw with nut potential and good future properties.",cueEn:"Large bet; Hero has a strong draw with nut potential and good future properties.",questionRu:"Можно ли discard только из-за large size?",questionEn:"Should it be discarded solely because of the large size?",goodRu:"Нет — оценить equity/raise/call branch",goodEn:"No — evaluate equity and raise/call branches",bad1Ru:"Да — all draws fold large",bad1En:"Yes — all draws fold to large bets",bad2Ru:"Always jam",bad2En:"Always jam",whyRu:"E09 treats strong improvement/nut-potential draws as candidates for continuing/aggression; size raises requirements, not a categorical ban.",whyEn:"E09 treats strong improvement/nut-potential draws as candidates for continuing/aggression; size raises requirements rather than creating a categorical ban.",slot:0},
  {id:"PM-OOP-05-105",skillId:"OOP-05",kind:"decision",sourceRefs:["FTGU-E09"],cueRu:"Large bet but opponent branch is known overbluffed.",cueEn:"Large bet but the opponent branch is known to be overbluffed.",questionRu:"Что меняется?",questionEn:"What changes?",goodRu:"Некоторые bluff-catch continues получают больше EV",goodEn:"Some bluff-catching continues gain EV",bad1Ru:"Sizing becomes irrelevant",bad1En:"Sizing becomes irrelevant",bad2Ru:"Call entire range",bad2En:"Call the entire range",whyRu:"Range composition can offset part of the price penalty, but does not erase hand/range selectivity.",whyEn:"Range composition can offset part of the price penalty but does not erase hand/range selectivity.",slot:1},
  {id:"PM-OOP-05-106",skillId:"OOP-05",kind:"changed",sourceRefs:["FTGU-E07","FTGU-E09"],cueRu:"Same hand/board; bet small → large.",cueEn:"Same hand/board; bet changes small → large.",questionRu:"Как меняется marginal defence?",questionEn:"How does marginal defense change?",goodRu:"Сужается",goodEn:"It narrows",bad1Ru:"Расширяется",bad1En:"It widens",bad2Ru:"Не меняется",bad2En:"No change",whyRu:"Price worsens and larger ranges are usually more selective/polar.",whyEn:"The price worsens and larger betting ranges are usually more selective/polar.",slot:2,changedVariables:["bet_size","range_shape"]},
  {id:"PM-OOP-05-107",skillId:"OOP-05",kind:"changed",sourceRefs:["FTGU-E09"],cueRu:"Same large size; betting range becomes more bluff-heavy by evidence.",cueEn:"Same large size; evidence shows the betting range becomes more bluff-heavy.",questionRu:"Как двигается bluff-catch region?",questionEn:"Which way does the bluff-catching region move?",goodRu:"Может расшириться",goodEn:"It can widen",bad1Ru:"Должен сузиться",bad1En:"It must narrow",bad2Ru:"Range composition irrelevant",bad2En:"Range composition is irrelevant",whyRu:"Price is only half the problem; credible bluff supply changes call EV.",whyEn:"Price is only half the problem; credible bluff supply changes call EV.",slot:0,changedVariables:["bluff_density"]},
  {id:"PM-OOP-05-108",skillId:"OOP-05",kind:"boundary",sourceRefs:["FTGU-E09"],cueRu:"Learner слышит «large bet = strong range».",cueEn:"The learner hears 'large bet = strong range'.",questionRu:"Это universal population truth?",questionEn:"Is that a universal population truth?",goodRu:"Нет — baseline shape, exploit требует evidence",goodEn:"No — it is a baseline shape; exploit requires evidence",bad1Ru:"Да — large bet never bluffs",bad1En:"Yes — large bets never bluff",bad2Ru:"Да — always fold bluff-catchers",bad2En:"Yes — always fold bluff-catchers",whyRu:"Source supports size/shape architecture, not a universal live underbluff claim.",whyEn:"The source supports size/shape architecture, not a universal live underbluff claim.",slot:1},

  // IP-01 — range vs selective c-bet.
  {id:"PM-IP-01-101",skillId:"IP-01",kind:"recognition",sourceRefs:["FTGU-E07"],cueRu:"PFR IP сохраняет large concentrated high-card/overpair advantage.",cueEn:"PFR IP retains a large concentrated high-card/overpair advantage.",questionRu:"Какой family plausible?",questionEn:"Which family is plausible?",goodRu:"Small high-frequency/unselective bet",goodEn:"Small high-frequency/unselective bet",bad1Ru:"Large polar bet every hand",bad1En:"Large polar bet every hand",bad2Ru:"Range check always",bad2En:"Always range check",whyRu:"E07 pairs broad participation with a small size when range advantage is concentrated.",whyEn:"E07 pairs broad participation with a small size when range advantage is concentrated.",slot:2},
  {id:"PM-IP-01-102",skillId:"IP-01",kind:"recognition",sourceRefs:["FTGU-E07"],cueRu:"Flop equalises ranges and defender retains more two-pair/straight density.",cueEn:"The flop equalizes the ranges and the defender retains more two-pair/straight density.",questionRu:"Какой family plausible?",questionEn:"Which family is plausible?",goodRu:"Selective betting + more checks",goodEn:"Selective betting plus more checks",bad1Ru:"More range betting",bad1En:"More range betting",bad2Ru:"Initiative dictates bet",bad2En:"Initiative dictates a bet",whyRu:"E07 moves toward selective/polar betting as defender ownership rises.",whyEn:"E07 moves toward selective/polar betting as defender ownership rises.",slot:0},
  {id:"PM-IP-01-103",skillId:"IP-01",kind:"decision",sourceRefs:["FTGU-E07"],cueRu:"Dry high flop, weak air still has fold-equity/protection job within broad small-bet branch.",cueEn:"Dry high flop; weak air still has a fold-equity/protection job inside a broad small-bet branch.",questionRu:"Can weak hands participate?",questionEn:"Can weak hands participate?",goodRu:"Да, если range architecture поддерживает broad small bet",goodEn:"Yes, if the range architecture supports a broad small bet",bad1Ru:"Нет, bet only made hands",bad1En:"No, bet only made hands",bad2Ru:"Only if exact solver frequency known",bad2En:"Only if an exact solver frequency is known",whyRu:"Small high-frequency betting combines thin value, protection and fold equity across many hand functions.",whyEn:"Small high-frequency betting combines thin value, protection and fold equity across many hand functions.",slot:1},
  {id:"PM-IP-01-104",skillId:"IP-01",kind:"decision",sourceRefs:["FTGU-E07"],cueRu:"Equalising connected board; medium showdown hand.",cueEn:"Equalizing connected board; medium showdown hand.",questionRu:"Какая ветка чаще получает вес?",questionEn:"Which branch tends to gain weight?",goodRu:"Check back",goodEn:"Check back",bad1Ru:"Large bet because position",bad1En:"Large bet because Hero has position",bad2Ru:"Range bet because PFR",bad2En:"Range bet because Hero is PFR",whyRu:"Selective strategy shifts medium showdown hands toward check when defender ownership rises.",whyEn:"A selective strategy shifts medium showdown hands toward checking when defender ownership rises.",slot:2},
  {id:"PM-IP-01-105",skillId:"IP-01",kind:"decision",sourceRefs:["FTGU-E07"],cueRu:"Strong value on equalising board.",cueEn:"Strong value on an equalizing board.",questionRu:"Does selective mean no betting?",questionEn:"Does selective mean no betting?",goodRu:"Нет — value + bluffs form a narrower betting range",goodEn:"No — value plus bluffs form a narrower betting range",bad1Ru:"Да — check entire range",bad1En:"Yes — check the entire range",bad2Ru:"Да — board neutralises all value",bad2En:"Yes — the board neutralizes all value",whyRu:"Selective is a spectrum: stronger value and suitable bluffs still bet while medium region checks more.",whyEn:"Selective is a spectrum: stronger value and suitable bluffs still bet while the medium region checks more.",slot:0},
  {id:"PM-IP-01-106",skillId:"IP-01",kind:"changed",sourceRefs:["FTGU-E07"],cueRu:"Same ranges; board dry-high → low-connected.",cueEn:"Same ranges; board changes dry-high → low-connected.",questionRu:"Как двигается strategy?",questionEn:"How does strategy move?",goodRu:"Broad/small → more selective/checking",goodEn:"Broad/small → more selective/checking",bad1Ru:"More range-bet",bad1En:"More range betting",bad2Ru:"No change",bad2En:"No change",whyRu:"Board-range interaction, not initiative, changes the participation structure.",whyEn:"Board-range interaction, not initiative, changes the participation structure.",slot:1,changedVariables:["board_class"]},
  {id:"PM-IP-01-107",skillId:"IP-01",kind:"changed",sourceRefs:["FTGU-E07"],cueRu:"Same board; defender range теряет connected low-card region.",cueEn:"Same board; the defender range loses much of its connected low-card region.",questionRu:"Как может измениться PFR betting?",questionEn:"How can PFR betting change?",goodRu:"Стать broader/smaller",goodEn:"Become broader/smaller",bad1Ru:"Must become more selective",bad1En:"Must become more selective",bad2Ru:"Range source irrelevant",bad2En:"Range source is irrelevant",whyRu:"Removing defender's strongest board interaction can restore PFR range advantage.",whyEn:"Removing the defender's strongest board interaction can restore PFR range advantage.",slot:2,changedVariables:["defender_range_shape"]},
  {id:"PM-IP-01-108",skillId:"IP-01",kind:"boundary",sourceRefs:["FTGU-E07"],cueRu:"Board high/dry, но actual ranges unusual и defender retains more strong region than normal.",cueEn:"Board is high/dry, but actual ranges are unusual and the defender retains more strong hands than normal.",questionRu:"Можно ли range-bet только по visual label?",questionEn:"Can Hero range-bet from the visual label alone?",goodRu:"Нет",goodEn:"No",bad1Ru:"Да, high/dry всегда range bet",bad1En:"Yes, high/dry is always a range bet",bad2Ru:"Да, PFR always owns high boards",bad2En:"Yes, PFR always owns high boards",whyRu:"E07 boundary: labels are applied to actual ranges; they are not self-executing strategy tags.",whyEn:"E07 boundary: labels are applied to actual ranges; they are not self-executing strategy tags.",slot:0},

  // IP-02 — check-back / delayed setup.
  {id:"PM-IP-02-101",skillId:"IP-02",kind:"recognition",sourceRefs:["FTGU-E19","CP-G3-L08"],cueRu:"IP checks back a medium/stable hand on flop.",cueEn:"IP checks back a medium/stable hand on the flop.",questionRu:"Что check-back может сохранять?",questionEn:"What can the check-back preserve?",goodRu:"Protected range + future delayed aggression",goodEn:"A protected range plus future delayed aggression",bad1Ru:"Только surrender",bad1En:"Only surrender",bad2Ru:"Always capped range",bad2En:"An always-capped range",whyRu:"Protected checks keep strong/usable hands in the passive branch and create later betting opportunities.",whyEn:"Protected checks keep strong/usable hands in the passive branch and create later betting opportunities.",slot:1},
  {id:"PM-IP-02-102",skillId:"IP-02",kind:"recognition",sourceRefs:["FTGU-E19"],cueRu:"Opponent checks flop to IP caller; some weak hands can bet as floats.",cueEn:"Opponent checks the flop to an IP caller; some weak hands can bet as floats.",questionRu:"Что отличает useful float bet от random stab?",questionEn:"What separates a useful float bet from a random stab?",goodRu:"Fold target + future barrel/improvement properties",goodEn:"A fold target plus future barrel/improvement properties",bad1Ru:"Any two because checked to",bad1En:"Any two because it checked to Hero",bad2Ru:"Only exact solver mix",bad2En:"Only an exact solver mix",whyRu:"E19 frames float betting through branch purpose and future properties rather than check=weak autopilot.",whyEn:"E19 frames float betting through branch purpose and future properties rather than check-equals-weak autopilot.",slot:2},
  {id:"PM-IP-02-103",skillId:"IP-02",kind:"decision",sourceRefs:["CP-G3-L08"],cueRu:"Medium showdown hand на board, где betting gets little value and faces unpleasant raises.",cueEn:"Medium showdown hand on a board where betting gets little value and faces unpleasant raises.",questionRu:"Какая ветка здесь полезна?",questionEn:"Which branch is useful?",goodRu:"Check back",goodEn:"Check back",bad1Ru:"Bet because position",bad1En:"Bet because Hero has position",bad2Ru:"Overbet to avoid raise",bad2En:"Overbet to avoid a raise",whyRu:"Protected check preserves showdown value and prevents betting range from consuming every medium hand.",whyEn:"A protected check preserves showdown value and prevents the betting range from consuming every medium hand.",slot:0},
  {id:"PM-IP-02-104",skillId:"IP-02",kind:"decision",sourceRefs:["FTGU-E19"],cueRu:"Flop checked through; turn opponent shows weakness and Hero has candidate with fold equity + improvement.",cueEn:"Flop checks through; on the turn the opponent shows weakness and Hero has a candidate with fold equity plus improvement.",questionRu:"Какой concept становится relevant?",questionEn:"Which concept becomes relevant?",goodRu:"Delayed aggression",goodEn:"Delayed aggression",bad1Ru:"Flop check forbids future bet",bad1En:"A flop check forbids future betting",bad2Ru:"Only river bluff allowed",bad2En:"Only a river bluff is allowed",whyRu:"Check-back does not end aggression; later streets can become better pressure nodes after range filtering/runout change.",whyEn:"A check-back does not end aggression; later streets can become better pressure nodes after range filtering/runout changes.",slot:1},
  {id:"PM-IP-02-105",skillId:"IP-02",kind:"decision",sourceRefs:["CP-G3-L08"],cueRu:"Strong hand на low-urgency flop; aggressive opponent likely to stab later after check-back.",cueEn:"Strong hand on a low-urgency flop; an aggressive opponent is likely to stab later after a check-back.",questionRu:"Can check-back be protected?",questionEn:"Can the check-back be protected?",goodRu:"Да, часть strong hands может check",goodEn:"Yes, some strong hands can check",bad1Ru:"Нет, all strong hands bet",bad1En:"No, all strong hands bet",bad2Ru:"Only weak hands check",bad2En:"Only weak hands check",whyRu:"Protected checking prevents later nodes from knowing check-back is only medium/air and can induce future aggression.",whyEn:"Protected checking prevents later nodes from knowing the check-back is only medium/air and can induce future aggression.",slot:2},
  {id:"PM-IP-02-106",skillId:"IP-02",kind:"changed",sourceRefs:["FTGU-E19","CP-G3-L08"],cueRu:"Same medium hand; board becomes much more vulnerable/dynamic.",cueEn:"Same medium hand; the board becomes much more vulnerable/dynamic.",questionRu:"Как меняется check-back attractiveness?",questionEn:"How does check-back attractiveness change?",goodRu:"Может снизиться",goodEn:"It can decrease",bad1Ru:"Always increases",bad1En:"It always increases",bad2Ru:"Board irrelevant",bad2En:"The board is irrelevant",whyRu:"Protection/value urgency can make immediate betting more valuable on dynamic boards.",whyEn:"Protection/value urgency can make immediate betting more valuable on dynamic boards.",slot:0,changedVariables:["board_dynamism","protection_need"]},
  {id:"PM-IP-02-107",skillId:"IP-02",kind:"changed",sourceRefs:["FTGU-E19"],cueRu:"Same flop check-back; turn card improves Hero's bluff candidate and weakens opponent branch.",cueEn:"Same flop check-back; the turn improves Hero's bluff candidate and weakens the opponent branch.",questionRu:"Как меняется delayed bet?",questionEn:"How does the delayed bet change?",goodRu:"Становится привлекательнее",goodEn:"It becomes more attractive",bad1Ru:"Становится запрещённым",bad1En:"It becomes prohibited",bad2Ru:"No change",bad2En:"No change",whyRu:"Changed runout plus filtered range can create a better later pressure node.",whyEn:"The changed runout plus the filtered range can create a better later pressure node.",slot:1,changedVariables:["turn_card","opponent_range"]},
  {id:"PM-IP-02-108",skillId:"IP-02",kind:"boundary",sourceRefs:["FTGU-E19","CP-G3-L08"],cueRu:"Learner слышит «protected checking» и начинает check back всё.",cueEn:"The learner hears 'protected checking' and starts checking back everything.",questionRu:"Это correct?",questionEn:"Is that correct?",goodRu:"Нет — protection сохраняет strong hands в check, но betting value/bluff branch остаётся",goodEn:"No — protection keeps some strong hands in checks while value/bluff betting branches remain",bad1Ru:"Да — checking always safest",bad1En:"Yes — checking is always safest",bad2Ru:"Да — IP never needs initiative",bad2En:"Yes — IP never needs initiative",whyRu:"Boundary: protected checking is range construction, not passive autopilot.",whyEn:"Boundary: protected checking is range construction, not passive autopilot.",slot:2},
];

export const srpA6ExpansionDecisions: PracticalDecision[] = cases.map(mk);
