import type { PracticalDecision } from "./types";

const o = (id: string, textRu: string, textEn: string, misconception?: string) => ({ id, textRu, textEn, misconception });

export const sourceSupportedGapFillDecisions: PracticalDecision[] = [
  {
    id: "PM-FND-03-001", skillId: "FND-03", kind: "decision", sourceRefs: ["FTGU-E01"],
    assumptions: ["meaningful stack remains", "small current investment", "future payoff possible"],
    cueRu: "У Hero невысокое current equity, но дешёвая инвестиция может открыть большой будущий payoff.", cueEn: "Hero has modest current equity, but a cheap investment may unlock a large future payoff.",
    questionRu: "Какой фактор может оправдать продолжение?", questionEn: "Which factor can justify continuing?",
    actionOptions: [o("a", "Implied odds / future EV", "Implied odds / future EV"), o("b", "Только current showdown equity", "Only current showdown equity", "CURRENT_EQUITY_ONLY"), o("c", "Любая draw автоматически profitable", "Any draw is automatically profitable", "DRAW_AUTOPILOT")],
    reasonOptions: [o("r1", "Future winnings relative to current investment can change total EV", "Future winnings relative to the current investment can change total EV"), o("r2", "Будущие улицы никогда не входят в EV", "Future streets never enter EV", "FUTURE_TREE_IGNORED"), o("r3", "Implied odds гарантируют payout", "Implied odds guarantee a payout", "IMPLIED_ODDS_GUARANTEE")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25,
    explanationRu: "FTGU-E01 прямо отделяет immediate equity от future-tree value и вводит implied odds как будущую отдачу относительно текущей инвестиции.",
    explanationEn: "FTGU-E01 explicitly separates immediate equity from future-tree value and frames implied odds as future return relative to the current investment.",
  },
  {
    id: "PM-FND-06-001", skillId: "FND-06", kind: "recognition", sourceRefs: ["LCM-01", "FTGU-E01"],
    assumptions: ["same nominal starting stack", "preflop pot becomes much larger"],
    cueRu: "Nominal stack тот же, но pot к flop намного больше.", cueEn: "Nominal stack is unchanged, but the pot reaching the flop is much larger.",
    questionRu: "Что происходит с postflop SPR?", questionEn: "What happens to postflop SPR?",
    actionOptions: [o("a", "Падает", "It falls"), o("b", "Растёт", "It rises", "SPR_BACKWARDS"), o("c", "Не меняется", "It does not change", "NOMINAL_STACK_ONLY")],
    reasonOptions: [o("r1", "Оставшийся эффективный stack делится на более крупный pot", "The remaining effective stack is divided by a larger pot"), o("r2", "SPR определяется только buy-in depth", "SPR is determined only by buy-in depth", "NOMINAL_STACK_ONLY"), o("r3", "Preflop sizing не влияет postflop tree", "Preflop sizing does not affect the postflop tree", "PREFLOP_POT_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 20,
    explanationRu: "LCM-01 и FTGU-E01 связывают отношение оставшегося stack к pot с количеством будущих решений и leverage.",
    explanationEn: "LCM-01 and FTGU-E01 connect the remaining stack relative to the pot with future decisions and leverage.",
    changedVariables: ["preflop_pot_size"],
  },
  {
    id: "PM-FND-07-001", skillId: "FND-07", kind: "boundary", sourceRefs: ["FTGU-E01"],
    assumptions: ["river/all-in", "future tree effectively ended"],
    cueRu: "После решения почти не остаётся future action.", cueEn: "Almost no future action remains after the decision.",
    questionRu: "Когда equity теснее всего связано с immediate EV?", questionEn: "When is equity most tightly connected to immediate EV?",
    actionOptions: [o("a", "Когда future branches почти отсутствуют", "When future branches are almost absent"), o("b", "Всегда одинаково", "Always equally", "EQUITY_EQUALS_EV"), o("c", "Только preflop", "Only preflop", "STREET_MYTH")],
    reasonOptions: [o("r1", "All-in/river removes future leverage and realization uncertainty", "All-in/river removes future leverage and realization uncertainty"), o("r2", "Position никогда не влияет на EV", "Position never affects EV", "POSITION_IGNORED"), o("r3", "Raw equity автоматически содержит rake/future play", "Raw equity automatically contains rake/future play", "EQUITY_EQUALS_EV")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 20,
    explanationRu: "FTGU-E01 прямо выделяет river/all-in как узлы, где price и equity доминируют сильнее, чем при длинном future tree.",
    explanationEn: "FTGU-E01 explicitly identifies river/all-in nodes as spots where price and equity dominate more than in a long future tree.",
  },
  {
    id: "PM-PF-09-001", skillId: "PF-09", kind: "decision", sourceRefs: ["SLC-M01-L02"],
    assumptions: ["open + caller", "Hero considers squeeze", "live caller may continue wide"],
    cueRu: "Open + caller создают dead money, но caller часто продолжает против squeeze.", cueEn: "An open plus a caller creates dead money, but the caller often continues versus squeezes.",
    questionRu: "Что определяет качество squeeze hand кроме blockers?", questionEn: "What determines squeeze-hand quality besides blockers?",
    actionOptions: [o("a", "Как рука играет when called + fold targets + position", "How the hand performs when called plus fold targets plus position"), o("b", "Только наличие Ace blocker", "Only having an ace blocker", "BLOCKER_AUTOPILOT"), o("c", "Любая suited hand squeeze", "Squeeze any suited hand", "SUITED_SQUEEZE_AUTOPILOT")],
    reasonOptions: [o("r1", "Dead money полезны только если whole branch EV сохраняется после calls/4-bets", "Dead money help only if whole-branch EV survives calls/4-bets"), o("r2", "Blocker гарантирует folds", "A blocker guarantees folds", "BLOCKER_GUARANTEE"), o("r3", "Caller response не влияет на squeeze construction", "Caller response does not affect squeeze construction", "CALL_BRANCH_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30,
    explanationRu: "SLC-M01-L02 рассматривает squeeze через dead money, fold equity, range selection и последствия called branch, а не через один blocker shortcut.",
    explanationEn: "SLC-M01-L02 frames squeezing through dead money, fold equity, range selection and the called branch rather than a single blocker shortcut.",
  },
  {
    id: "PM-PF-10-001", skillId: "PF-10", kind: "changed", sourceRefs: ["SLC-M01-L03"],
    assumptions: ["same physical stack", "mandatory UTG straddle makes effective game shallower in straddle units"],
    cueRu: "Появился mandatory UTG straddle; stack в обычных BB не изменился.", cueEn: "A mandatory UTG straddle appears; the stack in ordinary BB is unchanged.",
    questionRu: "Можно ли сохранить non-straddled preflop tree без изменений?", questionEn: "Can the non-straddled preflop tree be preserved unchanged?",
    actionOptions: [o("a", "Нет — пересчитать effective depth/position/tree", "No — recalculate effective depth/position/tree"), o("b", "Да — nominal BB stack тот же", "Yes — nominal BB stack is unchanged", "NOMINAL_STACK_ONLY"), o("c", "Да — straddle влияет только pot size", "Yes — straddle affects only pot size", "STRADDLE_POT_ONLY")],
    reasonOptions: [o("r1", "Straddle changes working blind unit, action order and effective depth", "The straddle changes the working blind unit, action order and effective depth"), o("r2", "Preflop strategy depends only on cards", "Preflop strategy depends only on cards", "CARDS_ONLY"), o("r3", "Position labels never change under straddle", "Position labels never change under a straddle", "POSITION_STATIC")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30,
    explanationRu: "SLC-M01-L03 отдельно пересчитывает straddled tree через изменённую effective depth и position/action structure.",
    explanationEn: "SLC-M01-L03 explicitly rebuilds the straddled tree around changed effective depth and position/action structure.",
    changedVariables: ["straddle", "effective_depth", "action_order"],
  },
  {
    id: "PM-BL-01-001", skillId: "BL-01", kind: "changed", sourceRefs: ["FTGU-E05"],
    assumptions: ["same BB hand", "opener moves BTN -> EP"],
    cueRu: "BB hand та же, но opener теперь EP вместо BTN.", cueEn: "The BB hand is unchanged, but the opener is now EP instead of BTN.",
    questionRu: "Как должен двигаться fringe defend?", questionEn: "How should the fringe defense move?",
    actionOptions: [o("a", "В сторону tighter/fold", "Toward tighter/fold"), o("b", "В сторону wider call", "Toward wider calls", "ORIGIN_RANGE_BACKWARDS"), o("c", "Не менять", "No change", "ORIGIN_RANGE_IGNORED")],
    reasonOptions: [o("r1", "EP origin range сильнее и повышает domination/overpair density", "The EP origin range is stronger and increases domination/overpair density"), o("r2", "BB price полностью отменяет range strength", "BB price completely overrides range strength", "PRICE_ONLY"), o("r3", "Opener position не влияет equity", "Opener position does not affect equity", "ORIGIN_RANGE_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25,
    explanationRu: "FTGU-E05 прямо сравнивает BB weak-hand viability против wide late ranges и concentrated EP ranges.",
    explanationEn: "FTGU-E05 explicitly compares weak-hand viability versus wide late ranges and concentrated EP ranges.",
    changedVariables: ["opener_position", "origin_range_strength"],
  },
  {
    id: "PM-BL-02-001", skillId: "BL-02", kind: "decision", sourceRefs: ["FTGU-E05"],
    assumptions: ["BB closes action", "CO open", "marginal playable hand"],
    cueRu: "BB против CO open: hand marginal, но есть discount и closing action.", cueEn: "BB versus a CO open: the hand is marginal but gets a discount and closes the action.",
    questionRu: "Что нельзя делать с BTN defence range?", questionEn: "What should not be done with the BTN-defense range?",
    actionOptions: [o("a", "Копировать его без adjustment", "Copy it without adjustment"), o("b", "Учитывать более сильный CO origin range", "Account for the stronger CO origin range", "CORRECT_FRAME_DISTRACTOR"), o("c", "Учитывать price и realisation", "Account for price and realization", "CORRECT_FRAME_DISTRACTOR")],
    reasonOptions: [o("r1", "Origin range strength меняет domination и required realisation", "Origin-range strength changes domination and required realization"), o("r2", "Все late-position opens одинаковы", "All late-position opens are identical", "POSITION_PAIR_COLLAPSE"), o("r3", "BB defence определяется только open size", "BB defense is determined only by open size", "SIZE_ONLY")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25,
    explanationRu: "FTGU-E05 требует учитывать origin range, а не применять один generic BB defence ко всем positions.",
    explanationEn: "FTGU-E05 requires accounting for the origin range rather than applying one generic BB defense to all positions.",
  },
  {
    id: "PM-BL-12-001", skillId: "BL-12", kind: "changed", sourceRefs: ["FTGU-E05"],
    assumptions: ["same BB hand/open", "rake becomes materially higher"],
    cueRu: "Rake выше, остальные assumptions те же.", cueEn: "Rake is higher; other assumptions are unchanged.",
    questionRu: "Как должен двигаться marginal BB call?", questionEn: "How should a marginal BB call move?",
    actionOptions: [o("a", "Становится менее привлекательным", "It becomes less attractive"), o("b", "Становится более привлекательным", "It becomes more attractive", "RAKE_BACKWARDS"), o("c", "Rake не влияет на thin calls", "Rake does not affect thin calls", "RAKE_IGNORED")],
    reasonOptions: [o("r1", "Rake вычитает EV и сильнее давит на marginal preflop calls", "Rake subtracts EV and pressures marginal preflop calls more"), o("r2", "Rake платит только opener", "Only the opener pays rake", "RAKE_FALSE"), o("r3", "Rake учитывается только postflop", "Rake matters only postflop", "RAKE_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 20,
    explanationRu: "FTGU-E05 отдельно отмечает, что rake suppresses thin preflop calls.",
    explanationEn: "FTGU-E05 explicitly notes that rake suppresses thin preflop calls.",
    changedVariables: ["rake"],
  },
  {
    id: "PM-W4-RUNOUT-001", skillId: "W4-RUNOUT-01", kind: "changed", sourceRefs: ["FTGU-E21"],
    assumptions: ["caller capped on some blank turns", "new turn completes relevant nuts"],
    cueRu: "Turn card возвращает caller часть nutted region.", cueEn: "The turn card restores part of the caller's nutted region.",
    questionRu: "Как классифицировать этот runout стратегически?", questionEn: "How should this runout be classified strategically?",
    actionOptions: [o("a", "Game-changing / range-changing", "Game-changing / range-changing"), o("b", "Blank", "Blank", "RUNOUT_LABEL_WRONG"), o("c", "Always good for aggressor", "Always good for the aggressor", "AGGRESSOR_BIAS")],
    reasonOptions: [o("r1", "Card changes cap/nut ownership and therefore action incentives", "The card changes cap/nut ownership and therefore action incentives"), o("r2", "Only card rank matters", "Only the card rank matters", "RANGE_IGNORED"), o("r3", "Turn never changes preflop range advantage", "The turn never changes preflop range advantage", "STATIC_RANGE_ADVANTAGE")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25,
    explanationRu: "FTGU-E21 разделяет blank и game-changing turns по тому, как они изменяют range cap и nutted regions.",
    explanationEn: "FTGU-E21 separates blank and game-changing turns by how they alter range caps and nutted regions.",
    changedVariables: ["turn_card", "nut_ownership"],
  },
  {
    id: "PM-W4-HAND-001", skillId: "W4-HAND-01", kind: "recognition", sourceRefs: ["FTGU-E09"],
    assumptions: ["made hand appears strong in absolute terms", "continuing range can be much stronger"],
    cueRu: "Hero имеет made hand и думает о value raise.", cueEn: "Hero has a made hand and considers a value raise.",
    questionRu: "Какой classification нужен кроме названия hand?", questionEn: "Which classification is needed beyond the hand label?",
    actionOptions: [o("a", "Relative strength против continuing range", "Relative strength versus the continuing range"), o("b", "Только absolute hand rank", "Only absolute hand rank", "ABSOLUTE_HAND_ONLY"), o("c", "Только kicker", "Only the kicker", "SINGLE_FEATURE")],
    reasonOptions: [o("r1", "Value threshold определяется руками, которые продолжают против выбранного action", "The value threshold is determined by hands that continue versus the chosen action"), o("r2", "Top pair всегда value raise", "Top pair is always a value raise", "HAND_LABEL_AUTOPILOT"), o("r3", "Continuing range не влияет", "The continuing range does not matter", "CONTINUE_RANGE_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25,
    explanationRu: "FTGU-E09 требует оценивать value raise против continuing range, что и делает hand-family classification стратегической, а не номинальной.",
    explanationEn: "FTGU-E09 requires judging a value raise versus the continuing range, making hand-family classification strategic rather than nominal.",
  },
  {
    id: "PM-OOP-02-001", skillId: "OOP-02", kind: "decision", sourceRefs: ["FTGU-E08"],
    assumptions: ["raising adds little EV", "low urgency", "strong hands can protect calls"],
    cueRu: "OOP response node, где raise мало добавляет EV.", cueEn: "OOP response node where raising adds little EV.",
    questionRu: "Что означает call-only simplification?", questionEn: "What does a call-only simplification mean?",
    actionOptions: [o("a", "Calls + folds, with strong hands protecting calls", "Calls plus folds, with strong hands protecting calls"), o("b", "Call every hand", "Call every hand", "CALL_ONLY_EQUALS_CALL_ALL"), o("c", "Never fold", "Never fold", "CALL_ONLY_EQUALS_CALL_ALL")],
    reasonOptions: [o("r1", "Call-only removes raises, not folds, and keeps passive branch uncapped", "Call-only removes raises, not folds, and keeps the passive branch uncapped"), o("r2", "Simplification means defend 100%", "Simplification means defend 100%", "CALL_ONLY_EQUALS_CALL_ALL"), o("r3", "Strong hands must always raise", "Strong hands must always raise", "STRONG_HAND_RAISE_AUTOPILOT")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25,
    explanationRu: "FTGU-E08 специально поясняет, что call-only response всё равно содержит folds и защищён strong calls.",
    explanationEn: "FTGU-E08 explicitly clarifies that a call-only response still contains folds and is protected by strong calls.",
  },
  {
    id: "PM-OOP-07-001", skillId: "OOP-07", kind: "decision", sourceRefs: ["FTGU-E22", "CINJ-E08"],
    assumptions: ["river OOP", "marginal showdown value", "multiple line options"],
    cueRu: "OOP river marginal showdown hand.", cueEn: "OOP river with marginal showdown value.",
    questionRu: "Что должно разделить check-call/check-fold/block branches?", questionEn: "What should separate check-call/check-fold/block branches?",
    actionOptions: [o("a", "Price + value/bluff supply + blockers + response to small bet", "Price plus value/bluff supply plus blockers plus response to a small bet"), o("b", "Только strength label", "Only the strength label", "HAND_LABEL_ONLY"), o("c", "Всегда block bet marginal hands", "Always block-bet marginal hands", "BLOCK_BET_AUTOPILOT")],
    reasonOptions: [o("r1", "River choice depends on opponent range composition and how our hand interacts with it", "River choice depends on opponent range composition and how our hand interacts with it"), o("r2", "Block bet prevents raises", "A block bet prevents raises", "BLOCK_BET_MAGIC"), o("r3", "Bluff supply irrelevant once Hero has pair", "Bluff supply is irrelevant once Hero has a pair", "BLUFF_SUPPLY_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 35,
    explanationRu: "FTGU-E22 и CINJ-E08 требуют range/removal/function analysis вместо automatic block/check-call labels.",
    explanationEn: "FTGU-E22 and CINJ-E08 require range/removal/function analysis rather than automatic block/check-call labels.",
  },
  {
    id: "PM-IP-02-001", skillId: "IP-02", kind: "decision", sourceRefs: ["FTGU-E08"],
    assumptions: ["IP", "strong hand", "opponent can keep bluffing", "low urgency"],
    cueRu: "Strong hand IP, но immediate raise не нужен для protection.", cueEn: "Strong hand IP, but an immediate raise is not needed for protection.",
    questionRu: "Почему check/call branch может быть лучше?", questionEn: "Why can the check/call branch be better?",
    actionOptions: [o("a", "Protect passive range and preserve opponent bluffs", "Protect the passive range and preserve opponent bluffs"), o("b", "Strong hands обязаны fast-play", "Strong hands must always fast-play", "STRONG_HAND_RAISE_AUTOPILOT"), o("c", "Check означает weakness", "Checking means weakness", "CHECK_EQUALS_WEAK")],
    reasonOptions: [o("r1", "Low urgency allows strongest hands to protect the passive branch", "Low urgency allows strongest hands to protect the passive branch"), o("r2", "Checking removes showdown value", "Checking removes showdown value", "CHECK_EQUALS_WEAK"), o("r3", "Opponent bluffs disappear after check", "Opponent bluffs disappear after a check", "BLUFFS_DISAPPEAR")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25,
    explanationRu: "FTGU-E08 использует protected calls/checks и letting bluffs continue как ключевые причины не форсировать raise.",
    explanationEn: "FTGU-E08 uses protected calls/checks and letting bluffs continue as key reasons not to force a raise.",
  },
  {
    id: "PM-IP-03-001", skillId: "IP-03", kind: "changed", sourceRefs: ["FTGU-E21"],
    assumptions: ["flop bet called", "turn changes from blank to nut-changing"],
    cueRu: "Та же flop line, но turn теперь nut-changing.", cueEn: "Same flop line, but the turn is now nut-changing.",
    questionRu: "Можно ли сохранить blank-turn barrel plan?", questionEn: "Can the blank-turn barrel plan be preserved?",
    actionOptions: [o("a", "Нет — rebuild ranges and become more selective", "No — rebuild ranges and become more selective"), o("b", "Да — flop initiative фиксирует plan", "Yes — flop initiative fixes the plan", "BARREL_AUTOPILOT"), o("c", "Да — turn никогда не меняет cap", "Yes — the turn never changes the cap", "CAP_STATIC")],
    reasonOptions: [o("r1", "Turn may restore nutted caller region and alter value/bluff thresholds", "The turn may restore a nutted caller region and alter value/bluff thresholds"), o("r2", "Barrel frequency определяется только flop", "Barrel frequency is determined only by the flop", "TURN_IGNORED"), o("r3", "Aggressor always retains nut advantage", "The aggressor always retains nut advantage", "NUT_ADVANTAGE_STATIC")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30,
    explanationRu: "FTGU-E21 требует пересчитывать turn after the call, а не переносить flop strategy по инерции.",
    explanationEn: "FTGU-E21 requires rebuilding the turn after the call rather than carrying flop strategy forward by inertia.",
    changedVariables: ["turn_card", "nut_ownership"],
  },
  {
    id: "PM-4BP-03-001", skillId: "4BP-03", kind: "boundary", sourceRefs: ["CP-G3-L10"],
    assumptions: ["low SPR", "strong stable hands exist"],
    cueRu: "Low SPR часто толкает к automatic bet/jam thinking.", cueEn: "Low SPR often pushes players toward automatic bet/jam thinking.",
    questionRu: "Должна ли checking range оставаться защищённой?", questionEn: "Should the checking range remain protected?",
    actionOptions: [o("a", "Да, если source-supported check-call/check-jam остаются credible", "Yes, when source-supported check-call/check-jam branches remain credible"), o("b", "Нет, low SPR отменяет checking", "No, low SPR eliminates checking", "LOW_SPR_NO_CHECK"), o("c", "Нет, strong hands обязаны bet", "No, strong hands must bet", "STRONG_HAND_AUTOBET")],
    reasonOptions: [o("r1", "Protected checking prevents an auto-capped check branch", "Protected checking prevents an automatically capped check branch"), o("r2", "Low SPR makes range protection irrelevant", "Low SPR makes range protection irrelevant", "LOW_SPR_NO_PROTECTION"), o("r3", "Check always means surrender", "Checking always means surrender", "CHECK_EQUALS_WEAK")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25,
    explanationRu: "CP-G3-L10 отдельно показывает protected low-SPR checks как часть practical simplification.",
    explanationEn: "CP-G3-L10 explicitly includes protected low-SPR checks in its practical simplification.",
  },
  {
    id: "PM-TURN-03-001", skillId: "TURN-03", kind: "decision", sourceRefs: ["FTGU-E20"],
    assumptions: ["PFR checked back flop", "turn does not restore many nuts"],
    cueRu: "PFR missed flop c-bet; turn не сильно усиливает checked range.", cueEn: "PFR checked back the flop; the turn does not greatly strengthen the checked range.",
    questionRu: "Что может поддержать turn probe?", questionEn: "What can support a turn probe?",
    actionOptions: [o("a", "Flop filtering left PFR capped relative to caller", "Flop filtering left PFR capped relative to the caller"), o("b", "Missed c-bet всегда означает weakness", "A missed c-bet always means weakness", "MISSED_CBET_ALWAYS_WEAK"), o("c", "Turn probe нужен только с made hand", "A turn probe is only for made hands", "PROBE_VALUE_ONLY")],
    reasonOptions: [o("r1", "Check-back can remove some strongest flop hands, creating a range-shape opportunity", "A check-back can remove some strongest flop hands, creating a range-shape opportunity"), o("r2", "Every check-back removes all value", "Every check-back removes all value", "CHECKBACK_NO_VALUE"), o("r3", "Range history does not matter", "Range history does not matter", "ANCESTRY_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30,
    explanationRu: "FTGU-E20 строит probing от range history и exact turn, а не от generic weakness label.",
    explanationEn: "FTGU-E20 builds probing from range history and the exact turn rather than a generic weakness label.",
  },
  {
    id: "PM-RIV-01-001", skillId: "RIV-01", kind: "decision", sourceRefs: ["FTGU-E23", "LCM-09"],
    assumptions: ["river value candidate", "bet size under consideration"],
    cueRu: "Hero хочет value bet river.", cueEn: "Hero wants to value-bet the river.",
    questionRu: "Какой вопрос должен быть первым?", questionEn: "Which question should come first?",
    actionOptions: [o("a", "Какие worse hands реально call этот size?", "Which worse hands actually call this size?"), o("b", "Насколько сильна моя hand в абсолюте?", "How strong is my hand in absolute terms?", "ABSOLUTE_VALUE_ONLY"), o("c", "Могу ли я поставить большой size?", "Can I choose a large size?", "SIZE_FIRST")],
    reasonOptions: [o("r1", "Value region определяется target calls; size и bluff volume строятся вокруг него", "The value region is defined by target calls; size and bluff volume are built around it"), o("r2", "Any strong made hand is three-street value", "Any strong made hand is three-street value", "STRONG_HAND_AUTOVALUE"), o("r3", "River size independent of opponent continuing range", "River size is independent of the opponent's continuing range", "CONTINUE_RANGE_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30,
    explanationRu: "FTGU-E23 начинает balanced river construction с value region, а LCM-09 сохраняет value-target logic.",
    explanationEn: "FTGU-E23 starts balanced river construction with the value region, while LCM-09 preserves value-target logic.",
  },
  {
    id: "PM-MW-02-001", skillId: "MW-02", kind: "changed", sourceRefs: ["SLC-M04-L36"],
    assumptions: ["strong one-pair hand", "action becomes bet + call + check-raise multiway"],
    cueRu: "One-pair hand сталкивается с сильной multiway action sequence.", cueEn: "A one-pair hand faces a strong multiway action sequence.",
    questionRu: "Как меняется её relative value без backup equity?", questionEn: "How does its relative value change without backup equity?",
    actionOptions: [o("a", "Резко падает", "It drops sharply"), o("b", "Растёт из-за большого pot", "It rises because the pot is bigger", "POT_SIZE_VALUE_ILLUSION"), o("c", "Не меняется", "It does not change", "MULTIWAY_ACTION_IGNORED")],
    reasonOptions: [o("r1", "Multiple strengthened ranges make backup/nutted improvement paths more important", "Multiple strengthened ranges make backup/nutted improvement paths more important"), o("r2", "Top pair retains fixed value across player counts", "Top pair has fixed value across player counts", "ABSOLUTE_HAND_ONLY"), o("r3", "More opponents increase one-pair nut potential", "More opponents increase one-pair nut potential", "MULTIWAY_BACKWARDS")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30,
    explanationRu: "SLC-M04-L36 подчёркивает, что strong multiway sequences резко повышают требования к one-pair continues и backup equity.",
    explanationEn: "SLC-M04-L36 emphasizes that strong multiway sequences sharply raise requirements for one-pair continues and backup equity.",
    changedVariables: ["number_of_ranges", "action_strength"],
  },
  {
    id: "PM-MW-04-001", skillId: "MW-04", kind: "decision", sourceRefs: ["FTGU-E03"],
    assumptions: ["multiple limpers", "implied-odds hand", "poor fold equity"],
    cueRu: "Limp-heavy live spot с несколькими callers.", cueEn: "Limp-heavy live spot with several callers.",
    questionRu: "Что лучше, если huge iso почти не создаёт folds?", questionEn: "What is better when a huge isolation raise creates almost no folds?",
    actionOptions: [o("a", "Рассмотреть overlimp или fold вместо auto-iso", "Consider overlimp or fold instead of auto-isolating"), o("b", "Всегда увеличивать iso size", "Always increase the isolation size", "ISO_SIZE_ESCALATION"), o("c", "Любая playable hand обязана raise", "Any playable hand must raise", "ISO_AUTOPILOT")],
    reasonOptions: [o("r1", "Low fold equity changes the branch; implied-odds hands can prefer smaller investment", "Low fold equity changes the branch; implied-odds hands can prefer a smaller investment"), o("r2", "Bigger size always guarantees isolation", "A bigger size always guarantees isolation", "ISO_GUARANTEE"), o("r3", "Overlimp never has EV", "Overlimping never has EV", "OVERLIMP_ALWAYS_BAD")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30,
    explanationRu: "FTGU-E03 прямо строит live limp response через fold equity, frequent strength и position, а не automatic isolation.",
    explanationEn: "FTGU-E03 explicitly builds the live limp response around fold equity, frequent strength and position rather than automatic isolation.",
  },
  {
    id: "PM-DEEP-03-001", skillId: "DEEP-03", kind: "recognition", sourceRefs: ["LCM-01", "SLC-M01-L03"],
    assumptions: ["mandatory straddle"],
    cueRu: "В игре включён mandatory straddle.", cueEn: "The game has a mandatory straddle.",
    questionRu: "Что пересчитать до использования обычных charts/heuristics?", questionEn: "What should be recalculated before using ordinary charts/heuristics?",
    actionOptions: [o("a", "Forced unit, effective depth, action order and SPR", "Forced unit, effective depth, action order and SPR"), o("b", "Только pot size", "Only pot size", "STRADDLE_POT_ONLY"), o("c", "Ничего", "Nothing", "STRADDLE_IGNORED")],
    reasonOptions: [o("r1", "Straddle changes the actual geometry of the hand", "A straddle changes the actual geometry of the hand"), o("r2", "Nominal BB count is sufficient", "Nominal BB count is sufficient", "NOMINAL_STACK_ONLY"), o("r3", "Action order never changes", "Action order never changes", "ACTION_ORDER_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25,
    explanationRu: "LCM-01 и SLC-M01-L03 требуют re-normalize depth/position under straddle.",
    explanationEn: "LCM-01 and SLC-M01-L03 require re-normalizing depth/position under a straddle.",
  },
  {
    id: "PM-DEEP-04-001", skillId: "DEEP-04", kind: "changed", sourceRefs: ["FTGU-E04", "SLC-M01-L03"],
    assumptions: ["same hand family", "effective depth increases", "future stack remains large"],
    cueRu: "Effective depth вырос, и future streets имеют больше leverage.", cueEn: "Effective depth increased and future streets have more leverage.",
    questionRu: "Что происходит с preflop hand valuation?", questionEn: "What happens to preflop hand valuation?",
    actionOptions: [o("a", "Nut potential/implied odds gain importance; domination/reverse implied odds matter more", "Nut potential/implied odds gain importance; domination/reverse implied odds matter more"), o("b", "Все hands становятся одинаково лучше", "All hands become equally better", "DEPTH_ALL_HANDS_EQUAL"), o("c", "Depth влияет только postflop size", "Depth affects only postflop sizing", "DEPTH_PREFLOP_IGNORED")],
    reasonOptions: [o("r1", "More future money magnifies both upside of nutted hands and downside of dominated regions", "More future money magnifies both the upside of nutted hands and the downside of dominated regions"), o("r2", "Deep stacks remove reverse implied odds", "Deep stacks remove reverse implied odds", "REVERSE_IMPLIED_BACKWARDS"), o("r3", "Preflop range shape independent of depth", "Preflop range shape is independent of depth", "DEPTH_PREFLOP_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30,
    explanationRu: "FTGU-E04 и SLC-M01-L03 связывают deeper future tree с playability, implied odds и changing preflop construction.",
    explanationEn: "FTGU-E04 and SLC-M01-L03 connect a deeper future tree with playability, implied odds and changing preflop construction.",
    changedVariables: ["effective_depth", "future_leverage"],
  },
  {
    id: "PM-EXP-04-001", skillId: "EXP-04", kind: "decision", sourceRefs: ["FTGU-E25"],
    assumptions: ["air-rich river branch", "credible evidence opponent overbluffs this line"],
    cueRu: "River branch содержит много natural air, и evidence показывает excess barrels.", cueEn: "The river branch contains abundant natural air and evidence shows excess barreling.",
    questionRu: "Какой exploit source поддерживает?", questionEn: "Which exploit does the source support?",
    actionOptions: [o("a", "Wider bluff-catch calls", "Wider bluff-catch calls"), o("b", "Tighter folds независимо от evidence", "Tighter folds regardless of evidence", "UNDERBLUFF_STEREOTYPE"), o("c", "Call every bluff catcher", "Call every bluff catcher", "OVEREXPLOIT")],
    reasonOptions: [o("r1", "Excess bluff-to-value ratio makes some baseline folds profitable calls", "An excessive bluff-to-value ratio turns some baseline folds into profitable calls"), o("r2", "Aggressive player means call 100%", "An aggressive player means call 100%", "OVEREXPLOIT"), o("r3", "Blockers become irrelevant under exploit", "Blockers become irrelevant under exploit", "BLOCKER_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30,
    explanationRu: "FTGU-E25 поддерживает exploitative overcalling только в genuinely overbluffed, air-rich branches и всё ещё требует blocker/line analysis.",
    explanationEn: "FTGU-E25 supports exploitative overcalling only in genuinely overbluffed, air-rich branches and still requires blocker/line analysis.",
  },
];
