import type { PracticalDecision } from "./types";

const o = (id: string, textRu: string, textEn: string, misconception?: string) => ({ id, textRu, textEn, misconception });

export const foundationExpansionDecisions: PracticalDecision[] = [
  // FND-01 — pot odds / required equity. FTGU-E01.
  {
    id: "PM-FND-01-101", skillId: "FND-01", kind: "recognition", sourceRefs: ["FTGU-E01"], assumptions: ["all-in", "risk 1 to win 3", "no future action"],
    cueRu: "Риск 1 ради выигрыша 3.", cueEn: "Risk 1 to win 3.", questionRu: "Какой примерно break-even equity?", questionEn: "What is the approximate break-even equity?",
    actionOptions: [o("a", "25%", "25%"), o("b", "50%", "50%", "WIN_RATE_50_SHORTCUT"), o("c", "75%", "75%", "RATIO_INVERTED")],
    reasonOptions: [o("r1", "Risk / (risk + reward) = 1 / 4", "Risk / (risk + reward) = 1 / 4"), o("r2", "Любой call требует equity больше 50%", "Every call requires equity above 50%", "WIN_RATE_50_SHORTCUT"), o("r3", "Reward делится только на risk", "Reward is divided only by risk", "FORMULA_INVERTED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 20, explanationRu: "FTGU-E01 вводит pot odds как порог безубыточности: call может быть +EV, даже если проигрывает большинство раздач.", explanationEn: "FTGU-E01 frames pot odds as a break-even threshold: a call can be profitable even when it loses most runouts.",
  },
  {
    id: "PM-FND-01-102", skillId: "FND-01", kind: "decision", sourceRefs: ["FTGU-E01"], assumptions: ["all-in", "risk 1 to win 2", "Hero equity 38%"],
    cueRu: "Hero рискует 1 ради 2 и имеет около 38% equity.", cueEn: "Hero risks 1 to win 2 and has about 38% equity.", questionRu: "Что говорит сравнение цены и equity?", questionEn: "What does price-only EV imply?",
    actionOptions: [o("a", "Call может быть +EV", "The call can be +EV"), o("b", "Fold, потому что equity <50%", "Fold because equity is below 50%", "WIN_RATE_50_SHORTCUT"), o("c", "Нельзя сравнить equity с price", "Equity cannot be compared with price", "PRICE_EQUITY_DISCONNECT")],
    reasonOptions: [o("r1", "38% выше примерно 33%-ного порога безубыточности", "38% is above the roughly 33% break-even threshold"), o("r2", "38% означает проигрыш большинства, значит EV отрицателен", "38% loses most runouts, so EV is negative", "WIN_RATE_50_SHORTCUT"), o("r3", "All-in EV зависит только от позиции", "All-in EV depends only on position", "POSITION_ONLY")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25, explanationRu: "FTGU-E01 показывает: call, который проигрывает большинство раздач, всё ещё может быть +EV по цене.", explanationEn: "This is the FTGU-E01 source example: a call that loses most runouts can still be profitable at the offered price.",
  },
  {
    id: "PM-FND-01-103", skillId: "FND-01", kind: "decision", sourceRefs: ["FTGU-E01"], assumptions: ["all-in", "risk 2 to win 3", "Hero equity 37%"],
    cueRu: "Hero рискует 2 ради 3; equity около 37%.", cueEn: "Hero risks 2 to win 3; equity is about 37%.", questionRu: "Какой вывод ближе?", questionEn: "Which conclusion is closer?",
    actionOptions: [o("a", "Call проходит порог", "The call clears the threshold", "THRESHOLD_BACKWARDS"), o("b", "Call не проходит примерно 40% threshold", "The call does not clear the roughly 40% threshold"), o("c", "Нужны всегда ровно 50%", "Exactly 50% is always required", "WIN_RATE_50_SHORTCUT")],
    reasonOptions: [o("r1", "Break-even около 2/(2+3)=40%, а 37% ниже", "Break-even is about 2/(2+3)=40%, and 37% is below"), o("r2", "37% выше одной трети, значит достаточно при любой цене", "37% is above one third, so it is enough at any price", "ONE_THIRD_ALWAYS"), o("r3", "Pot odds не меняются с bet size", "Pot odds do not change with bet size", "PRICE_IGNORED")],
    correctActionId: "b", correctReasonId: "r1", targetSeconds: 25, explanationRu: "Required equity двигается вместе с price; source не учит одной универсальной цифре.", explanationEn: "Required equity moves with the price; the source does not teach one universal percentage.",
  },
  {
    id: "PM-FND-01-104", skillId: "FND-01", kind: "decision", sourceRefs: ["FTGU-E01"], assumptions: ["river call", "future action ended", "price known"],
    cueRu: "River, после call больше решений нет.", cueEn: "River, with no decisions remaining after the call.", questionRu: "Что становится особенно важным?", questionEn: "What becomes especially important?",
    actionOptions: [o("a", "Price + equity versus range", "Price + equity versus range"), o("b", "Implied odds many streets later", "Implied odds many streets later", "FUTURE_TREE_FALSE"), o("c", "Only table image", "Only table image", "SINGLE_FACTOR")],
    reasonOptions: [o("r1", "Когда future tree заканчивается, equity теснее связано с immediate EV", "When the future tree ends, equity is more tightly linked to immediate EV"), o("r2", "River call создаёт ещё три streets", "A river call creates three more streets", "STREET_FALSE"), o("r3", "Price irrelevant once river reached", "Price is irrelevant on the river", "PRICE_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 20, explanationRu: "FTGU-E01 прямо выделяет river/all-in как узлы, где price/equity доминируют сильнее.", explanationEn: "FTGU-E01 explicitly highlights river/all-in nodes where price/equity dominate more strongly.",
  },
  {
    id: "PM-FND-01-105", skillId: "FND-01", kind: "changed", sourceRefs: ["FTGU-E01"], assumptions: ["same hand equity", "call price becomes cheaper"],
    cueRu: "Equity hand не меняется, но call становится дешевле.", cueEn: "The hand's equity is unchanged, but the call becomes cheaper.", questionRu: "Как меняется required equity?", questionEn: "How does required equity change?",
    actionOptions: [o("a", "Падает", "It falls"), o("b", "Растёт", "It rises", "PRICE_BACKWARDS"), o("c", "Не меняется", "No change", "PRICE_IGNORED")],
    reasonOptions: [o("r1", "Меньший risk относительно reward снижает break-even threshold", "Less risk relative to reward lowers the break-even threshold"), o("r2", "Cheaper call требует больше equity", "A cheaper call requires more equity", "PRICE_BACKWARDS"), o("r3", "Required equity fixed at 50%", "Required equity is fixed at 50%", "WIN_RATE_50_SHORTCUT")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 18, explanationRu: "Pot odds — динамический threshold, а не фиксированная цифра.", explanationEn: "Pot odds create a dynamic threshold, not a fixed percentage.", changedVariables: ["price"],
  },
  {
    id: "PM-FND-01-106", skillId: "FND-01", kind: "changed", sourceRefs: ["FTGU-E01"], assumptions: ["same price", "equity versus range falls below threshold"],
    cueRu: "Price тот же, но после range update equity падает ниже break-even.", cueEn: "Price is unchanged, but after a range update equity falls below break-even.", questionRu: "Как должен измениться immediate all-in call?", questionEn: "How should the immediate all-in call change?",
    actionOptions: [o("a", "В сторону fold", "Toward fold"), o("b", "В сторону call", "Toward call", "EQUITY_BACKWARDS"), o("c", "Не реагировать на range", "Ignore the range", "RANGE_IGNORED")],
    reasonOptions: [o("r1", "At tree end price/equity comparison directly drives EV", "At the end of the tree, the price/equity comparison directly drives EV"), o("r2", "Hand name важнее range", "The hand name matters more than the range", "HAND_NAME_ONLY"), o("r3", "All-in calls ignore opponent range", "All-in calls ignore the opponent range", "RANGE_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 20, explanationRu: "FTGU-E01 определяет equity относительно opposing range и связывает её с price, когда future action исчезает.", explanationEn: "FTGU-E01 defines equity versus an opposing range and links it to price when future action disappears.", changedVariables: ["opponent_range", "equity"],
  },
  {
    id: "PM-FND-01-107", skillId: "FND-01", kind: "boundary", sourceRefs: ["FTGU-E01"], assumptions: ["flop", "large stack behind", "many future decisions"],
    cueRu: "Flop, большой stack behind, много future branches.", cueEn: "Flop, large stack behind, many future branches.", questionRu: "Достаточно ли сравнить raw equity только с current pot-odds threshold?", questionEn: "Is comparing raw equity only with the current pot-odds threshold sufficient?",
    actionOptions: [o("a", "Нет", "No"), o("b", "Да, всегда", "Yes, always", "EQUITY_EQUALS_EV"), o("c", "Да, если Hero IP", "Yes, if Hero is IP", "POSITION_MAGIC")],
    reasonOptions: [o("r1", "Future folds, leverage and implied odds can separate current equity from total EV", "Future folds, leverage and implied odds can separate current equity from total EV"), o("r2", "Pot odds already include every future action", "Pot odds already include every future action", "FUTURE_TREE_IGNORED"), o("r3", "Raw equity guarantees realization", "Raw equity guarantees realization", "RAW_EQUITY_ONLY")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30, explanationRu: "Это ключевая boundary FTGU-E01: current pot odds особенно чисты near tree-end, но не заменяют future-tree EV при глубоком SPR.", explanationEn: "This is a key FTGU-E01 boundary: current pot odds are cleanest near the end of the tree and do not replace future-tree EV at deep SPR.",
  },

  // FND-02 — raw vs realised equity. FTGU-E01 + E05.
  {
    id: "PM-FND-02-101", skillId: "FND-02", kind: "recognition", sourceRefs: ["FTGU-E01"], assumptions: ["hand can be folded before showdown"], cueRu: "Hand имеет equity, но может fold до showdown.", cueEn: "The hand has equity but can fold before showdown.", questionRu: "Какой термин описывает проблему?", questionEn: "Which concept describes the problem?",
    actionOptions: [o("a", "Equity realisation", "Equity realization"), o("b", "Card removal", "Card removal", "WRONG_CONCEPT"), o("c", "Only pot odds", "Only pot odds", "WRONG_CONCEPT")],
    reasonOptions: [o("r1", "Raw equity не гарантирует, что Hero увидит все remaining cards", "Raw equity does not guarantee Hero will see all remaining cards"), o("r2", "Equity always reaches showdown", "Equity always reaches showdown", "FULL_REALISATION"), o("r3", "Folding preserves all equity", "Folding preserves all equity", "FOLD_FALSE")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 18, explanationRu: "FTGU-E01 сразу ограничивает raw equity: она может быть surrendered before showdown.", explanationEn: "FTGU-E01 immediately limits raw equity: it can be surrendered before showdown.",
  },
  {
    id: "PM-FND-02-102", skillId: "FND-02", kind: "recognition", sourceRefs: ["FTGU-E05"], assumptions: ["BB marginal defend", "poor postflop skill"], cueRu: "Теоретическая цена BB call выглядит тонко положительной, но Hero плохо исполняет postflop.", cueEn: "The theoretical price of a BB call looks thinly positive, but Hero executes poorly postflop.", questionRu: "Какой component может исчезнуть?", questionEn: "Which component can disappear?",
    actionOptions: [o("a", "Realisable equity / practical EV", "Realizable equity / practical EV"), o("b", "Posted blind", "The posted blind", "WRONG_COMPONENT"), o("c", "Opponent range", "Opponent range", "WRONG_COMPONENT")],
    reasonOptions: [o("r1", "Execution quality can move marginal calls across zero EV", "Execution quality can move marginal calls across zero EV"), o("r2", "Raw equity increases when Hero misplays", "Raw equity increases when Hero misplays", "EXECUTION_BACKWARDS"), o("r3", "Skill is irrelevant to realization", "Skill is irrelevant to realization", "REALISATION_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 20, explanationRu: "FTGU-E05 explicitly links marginal BB defence to postflop execution quality.", explanationEn: "FTGU-E05 explicitly links marginal BB defense to postflop execution quality.",
  },
  {
    id: "PM-FND-02-103", skillId: "FND-02", kind: "decision", sourceRefs: ["FTGU-E01", "FTGU-E05"], assumptions: ["same raw equity", "Hero IP in one branch and OOP in another", "stack remains"], cueRu: "Raw equity одинакова; одна ветка IP, другая OOP.", cueEn: "Raw equity is identical; one branch is IP, the other OOP.", questionRu: "Можно ли считать EV одинаковым?", questionEn: "Can the EV be treated as identical?",
    actionOptions: [o("a", "Нет", "No"), o("b", "Да, raw equity всё определяет", "Yes, raw equity determines everything", "RAW_EQUITY_ONLY"), o("c", "Да, если pot одинаков", "Yes, if the pot is the same", "POT_ONLY")],
    reasonOptions: [o("r1", "Position changes future pressure and realization", "Position changes future pressure and realization"), o("r2", "Position changes dealt cards", "Position changes the dealt cards", "POSITION_MAGIC"), o("r3", "EV ignores future actions", "EV ignores future actions", "FUTURE_TREE_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 22, explanationRu: "FTGU-E01 separates equity from EV; FTGU-E05 makes execution/position part of marginal defend viability.", explanationEn: "FTGU-E01 separates equity from EV; FTGU-E05 makes execution/position part of marginal-defense viability.",
  },
  {
    id: "PM-FND-02-104", skillId: "FND-02", kind: "decision", sourceRefs: ["FTGU-E01"], assumptions: ["all-in", "no future decisions"], cueRu: "Все деньги уже в pot, future folds невозможны.", cueEn: "All money is already in the pot and future folds are impossible.", questionRu: "Как raw equity соотносится с EV теперь?", questionEn: "How does raw equity relate to EV now?",
    actionOptions: [o("a", "Связь становится намного прямее", "The relationship becomes much more direct"), o("b", "Связь становится слабее", "The relationship becomes weaker", "TREE_END_BACKWARDS"), o("c", "Equity перестаёт иметь значение", "Equity stops mattering", "EQUITY_IGNORED")],
    reasonOptions: [o("r1", "Нет future leverage/equity denial; price и equity доминируют", "There is no future leverage/equity denial; price and equity dominate"), o("r2", "All-in creates more decisions", "All-in creates more decisions", "TREE_FALSE"), o("r3", "Showdown equity is unrelated to all-in EV", "Showdown equity is unrelated to all-in EV", "EQUITY_EV_DISCONNECT")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 20, explanationRu: "FTGU-E01 прямо выделяет all-in/tree-end как место максимального сближения equity и EV.", explanationEn: "FTGU-E01 explicitly identifies all-in/tree-end nodes as places where equity and EV align most closely.",
  },
  {
    id: "PM-FND-02-105", skillId: "FND-02", kind: "changed", sourceRefs: ["FTGU-E01"], assumptions: ["same hand/range", "stack behind increases materially"], cueRu: "Hand/range те же, но behind остаётся намного больше stack.", cueEn: "Hand/range are unchanged, but much more stack remains behind.", questionRu: "Как меняется риск divergence equity и EV?", questionEn: "How does the risk of equity/EV divergence change?",
    actionOptions: [o("a", "Растёт", "It increases"), o("b", "Падает", "It decreases", "DEPTH_BACKWARDS"), o("c", "Не меняется", "No change", "DEPTH_IGNORED")],
    reasonOptions: [o("r1", "More future decisions allow folds, leverage and implied-odds effects", "More future decisions allow folds, leverage and implied-odds effects"), o("r2", "Depth removes future action", "Depth removes future action", "DEPTH_BACKWARDS"), o("r3", "Equity already includes every future decision", "Equity already includes every future decision", "EQUITY_EQUALS_EV")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 22, explanationRu: "FTGU-E01 связывает divergence equity/EV с количеством future decisions и stack-to-pot geometry.", explanationEn: "FTGU-E01 links equity/EV divergence to the amount of future decision-making and stack-to-pot geometry.", changedVariables: ["stack_behind", "future_tree"],
  },
  {
    id: "PM-FND-02-106", skillId: "FND-02", kind: "changed", sourceRefs: ["FTGU-E05"], assumptions: ["same BB hand/price", "postflop opponent changes passive -> strong pressure"], cueRu: "BB hand и price те же, но postflop opponent теперь сильнее давит.", cueEn: "The BB hand and price are unchanged, but the postflop opponent now applies stronger pressure.", questionRu: "Как двигается marginal defend?", questionEn: "How does the marginal defend move?",
    actionOptions: [o("a", "Слабее", "Weaker"), o("b", "Сильнее", "Stronger", "PRESSURE_BACKWARDS"), o("c", "Без изменений", "Unchanged", "REALISATION_IGNORED")],
    reasonOptions: [o("r1", "Harder future realization can erase a thin defend", "Harder future realization can erase a thin defend"), o("r2", "More pressure gives Hero more raw equity", "More pressure gives Hero more raw equity", "RAW_EQUITY_MAGIC"), o("r3", "Opponent skill never affects EV", "Opponent skill never affects EV", "OPPONENT_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25, explanationRu: "FTGU-E05 подчёркивает, что marginal calls зависят от ability to execute postflop, а не только от nominal price.", explanationEn: "FTGU-E05 emphasizes that marginal calls depend on the ability to execute postflop, not only nominal price.", changedVariables: ["opponent_pressure", "realisation"],
  },
  {
    id: "PM-FND-02-107", skillId: "FND-02", kind: "boundary", sourceRefs: ["FTGU-E01"], assumptions: ["river", "no future decisions"], cueRu: "River decision завершает tree.", cueEn: "The river decision ends the tree.", questionRu: "Нужно ли здесь сильно дисконтировать raw equity из-за future realisation?", questionEn: "Should raw equity be heavily discounted for future realization here?",
    actionOptions: [o("a", "Нет, future-realisation issue почти исчезает", "No, the future-realization issue mostly disappears"), o("b", "Да, ещё три streets впереди", "Yes, three more streets remain", "STREET_FALSE"), o("c", "Да, потому что equity never matters", "Yes, because equity never matters", "EQUITY_IGNORED")],
    reasonOptions: [o("r1", "Tree-end is the boundary where equity aligns more closely with immediate EV", "Tree-end is the boundary where equity aligns more closely with immediate EV"), o("r2", "River position changes unseen cards", "River position changes unseen cards", "POSITION_MAGIC"), o("r3", "Raw equity is always fully irrelevant", "Raw equity is always irrelevant", "RAW_EQUITY_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 20, explanationRu: "FTGU-E01 делает именно эту boundary: чем меньше future decisions, тем прямее связь equity с EV.", explanationEn: "FTGU-E01 draws exactly this boundary: the fewer future decisions remain, the more directly equity maps to EV.",
  },

  // FND-03 — implied odds. FTGU-E01 + E04.
  {
    id: "PM-FND-03-101", skillId: "FND-03", kind: "recognition", sourceRefs: ["FTGU-E01"], assumptions: ["small current investment", "large potential future return"], cueRu: "Небольшая инвестиция сейчас может открыть большой future payoff.", cueEn: "A small investment now can unlock a large future payoff.", questionRu: "Какой concept описывает это?", questionEn: "Which concept describes this?",
    actionOptions: [o("a", "Implied odds", "Implied odds"), o("b", "Only pot odds", "Only pot odds", "CURRENT_PRICE_ONLY"), o("c", "Blocker effect", "Blocker effect", "WRONG_CONCEPT")],
    reasonOptions: [o("r1", "Source определяет implied odds через current investment versus potential future return", "The source defines implied odds through current investment versus potential future return"), o("r2", "Future winnings never enter EV", "Future winnings never enter EV", "FUTURE_TREE_IGNORED"), o("r3", "Implied odds mean guaranteed payout", "Implied odds mean guaranteed payout", "PAYOUT_GUARANTEE")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 18, explanationRu: "FTGU-E01 формулирует implied odds именно как отношение current investment к potential future return.", explanationEn: "FTGU-E01 frames implied odds as the relationship between current investment and potential future return.",
  },
  {
    id: "PM-FND-03-102", skillId: "FND-03", kind: "recognition", sourceRefs: ["FTGU-E04"], assumptions: ["suited connector", "needs multiple streets to realize upside"], cueRu: "Hand часто улучшает equity постепенно и может требовать нескольких инвестиций.", cueEn: "The hand often improves gradually and may require multiple investments.", questionRu: "Как это влияет на implied-odds evaluation?", questionEn: "How does this affect implied-odds evaluation?",
    actionOptions: [o("a", "Position/depth/pressure становятся особенно важны", "Position/depth/pressure become especially important"), o("b", "Любая suited connector автоматически profitable", "Any suited connector is automatically profitable", "SUITED_AUTOPILOT"), o("c", "Future action не важен", "Future action does not matter", "FUTURE_TREE_IGNORED")],
    reasonOptions: [o("r1", "Gradual realization can require paying across streets before upside arrives", "Gradual realization can require paying across streets before the upside arrives"), o("r2", "Suitedness guarantees a flush", "Suitedness guarantees a flush", "DRAW_GUARANTEE"), o("r3", "Depth only matters for pairs", "Depth matters only for pairs", "DEPTH_MISREAD")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25, explanationRu: "FTGU-E04 contrasts discrete set realization with gradual suited-connector realization and explicitly links the latter to position/depth/pressure.", explanationEn: "FTGU-E04 contrasts discrete set realization with gradual suited-connector realization and explicitly links the latter to position/depth/pressure.",
  },
  {
    id: "PM-FND-03-103", skillId: "FND-03", kind: "decision", sourceRefs: ["FTGU-E01"], assumptions: ["pocket pair", "tight strong range", "small price", "deep enough future stack"], cueRu: "Pocket pair получает маленькую цену против tight range и имеет meaningful future stack.", cueEn: "A pocket pair gets a small price versus a tight range with meaningful future stack.", questionRu: "Почему low current equity не обязательно означает fold?", questionEn: "Why does low current equity not necessarily imply a fold?",
    actionOptions: [o("a", "Set upside может создать favourable implied-odds branch", "Set upside can create a favorable implied-odds branch"), o("b", "Pair always has >50% equity", "A pair always has more than 50% equity", "EQUITY_FALSE"), o("c", "Tight range pays every future bet", "A tight range pays every future bet", "PAYOUT_GUARANTEE")],
    reasonOptions: [o("r1", "Current investment can be small relative to future return when strong improvement occurs", "Current investment can be small relative to future return when a strong improvement occurs"), o("r2", "Implied odds ignore price", "Implied odds ignore price", "PRICE_IGNORED"), o("r3", "Set is guaranteed", "A set is guaranteed", "SET_GUARANTEE")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25, explanationRu: "FTGU-E01 использует pocket-pair versus tight range как пример того, как future payoff может оправдать low current equity.", explanationEn: "FTGU-E01 uses a pocket pair versus a tight range as an example of future payoff justifying low current equity.",
  },
  {
    id: "PM-FND-03-104", skillId: "FND-03", kind: "decision", sourceRefs: ["FTGU-E04"], assumptions: ["same nominal call price", "players behind likely squeeze"], cueRu: "Implied-odds hand получает нормальную цену, но часто не увидит flop из-за squeeze behind.", cueEn: "An implied-odds hand gets a reasonable price but often will not see the flop because of squeezes behind.", questionRu: "Достаточно ли nominal price?", questionEn: "Is the nominal price sufficient?",
    actionOptions: [o("a", "Нет", "No"), o("b", "Да, players behind irrelevant", "Yes, players behind are irrelevant", "PLAYERS_BEHIND_IGNORED"), o("c", "Да, если hand suited", "Yes, if the hand is suited", "SUITED_AUTOPILOT")],
    reasonOptions: [o("r1", "Survival to the future payoff branch is part of EV", "Survival to the future payoff branch is part of EV"), o("r2", "Squeezes improve implied odds", "Squeezes improve implied odds", "SQUEEZE_BACKWARDS"), o("r3", "Position guarantees flop access", "Position guarantees flop access", "POSITION_MAGIC")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25, explanationRu: "FTGU-E04 делает players behind частью call EV: implied upside не помогает, если branch часто уничтожается до flop.", explanationEn: "FTGU-E04 makes players behind part of call EV: implied upside does not help if the branch is often destroyed before the flop.",
  },
  {
    id: "PM-FND-03-105", skillId: "FND-03", kind: "changed", sourceRefs: ["FTGU-E01", "FTGU-E04"], assumptions: ["same hand/price", "effective stack gets much deeper"], cueRu: "Hand и current price те же, effective stack становится намного глубже.", cueEn: "The hand and current price are unchanged, but effective stack becomes much deeper.", questionRu: "Как меняется upside implied-odds branch?", questionEn: "How does the implied-odds upside branch change?",
    actionOptions: [o("a", "Потенциально усиливается", "It can strengthen"), o("b", "Всегда исчезает", "It always disappears", "DEPTH_BACKWARDS"), o("c", "Depth никогда не влияет", "Depth never matters", "DEPTH_IGNORED")],
    reasonOptions: [o("r1", "More future stack can increase potential return, though realization/reverse risks still matter", "More future stack can increase potential return, though realization/reverse risks still matter"), o("r2", "Deep stack guarantees payoff", "A deep stack guarantees payoff", "PAYOUT_GUARANTEE"), o("r3", "Only current pot determines implied odds", "Only the current pot determines implied odds", "FUTURE_TREE_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25, explanationRu: "Source связывает implied odds с potential future return; depth увеличивает доступный future tree, но не гарантирует payout.", explanationEn: "The source links implied odds to potential future return; depth increases the available future tree but does not guarantee a payout.", changedVariables: ["effective_stack"],
  },
  {
    id: "PM-FND-03-106", skillId: "FND-03", kind: "changed", sourceRefs: ["FTGU-E04"], assumptions: ["same suited connector", "Hero moves IP -> OOP"], cueRu: "Та же suited connector и depth, но Hero теряет position.", cueEn: "Same suited connector and depth, but Hero loses position.", questionRu: "Как двигается practical implied-odds case?", questionEn: "How does the practical implied-odds case move?",
    actionOptions: [o("a", "Обычно слабее", "Usually weaker"), o("b", "Обычно сильнее", "Usually stronger", "POSITION_BACKWARDS"), o("c", "Не меняется", "No change", "POSITION_IGNORED")],
    reasonOptions: [o("r1", "Gradual-equity hands depend strongly on position and ability to realise across streets", "Gradual-equity hands depend strongly on position and the ability to realize across streets"), o("r2", "OOP improves realization", "OOP improves realization", "POSITION_BACKWARDS"), o("r3", "Implied odds ignore position", "Implied odds ignore position", "POSITION_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 22, explanationRu: "FTGU-E04 особенно подчёркивает sensitivity suited connectors к position/depth/pressure.", explanationEn: "FTGU-E04 especially emphasizes suited connectors' sensitivity to position/depth/pressure.", changedVariables: ["position"],
  },
  {
    id: "PM-FND-03-107", skillId: "FND-03", kind: "boundary", sourceRefs: ["FTGU-E01"], assumptions: ["future payoff theoretically large", "opponent rarely pays off", "Hero may face pressure before improvement"], cueRu: "Potential pot большой, но villain редко платит, а Hero может fold раньше.", cueEn: "The potential pot is large, but villain rarely pays off and Hero may fold earlier.", questionRu: "Можно ли назвать это хорошими implied odds только из-за deep stack?", questionEn: "Can this be called good implied odds merely because stacks are deep?",
    actionOptions: [o("a", "Нет", "No"), o("b", "Да, depth автоматически достаточно", "Yes, depth alone is sufficient", "DEPTH_AUTOPILOT"), o("c", "Да, future return всегда реализуется", "Yes, future return is always realized", "PAYOUT_GUARANTEE")],
    reasonOptions: [o("r1", "Implied odds are potential future return relative to investment, not guaranteed stack access", "Implied odds are potential future return relative to investment, not guaranteed stack access"), o("r2", "Deep stacks guarantee calls", "Deep stacks guarantee calls", "PAYOUT_GUARANTEE"), o("r3", "Opponent behavior is irrelevant", "Opponent behavior is irrelevant", "OPPONENT_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30, explanationRu: "FTGU-E01 прямо предупреждает, что implied odds — не просто шанс выиграть большой pot; важен реальный future return branch.", explanationEn: "FTGU-E01 explicitly warns that implied odds are not merely the chance to win a large pot; the actual future-return branch matters.",
  },

  // FND-06 — effective stack / SPR. FTGU-E01 + admitted LCM-01 geometry.
  {
    id: "PM-FND-06-101", skillId: "FND-06", kind: "recognition", sourceRefs: ["FTGU-E01", "LCM-01"], assumptions: ["heads-up", "one player has 80bb", "other has 200bb"], cueRu: "Stacks 80bb и 200bb.", cueEn: "Stacks are 80bb and 200bb.", questionRu: "Какой stack ограничивает объём, который может быть разыгран между ними?", questionEn: "Which stack caps the amount that can be played between them?",
    actionOptions: [o("a", "80bb effective", "80bb effective"), o("b", "200bb", "200bb", "BIG_STACK_ONLY"), o("c", "280bb", "280bb", "STACKS_ADDED")],
    reasonOptions: [o("r1", "Effective stack ограничен меньшим участвующим stack", "Effective stack is capped by the smaller participating stack"), o("r2", "Stacks always add together", "Stacks always add together", "STACKS_ADDED"), o("r3", "Bigger stack defines every decision", "The bigger stack defines every decision", "BIG_STACK_ONLY")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 15, explanationRu: "LCM-01 использует effective stack как рабочую геометрию вместо nominal big stack.", explanationEn: "LCM-01 uses effective stack as the working geometry rather than the nominal larger stack.",
  },
  {
    id: "PM-FND-06-102", skillId: "FND-06", kind: "decision", sourceRefs: ["FTGU-E01", "LCM-01"], assumptions: ["remaining effective stack 90", "pot 30"], cueRu: "После action остаётся 90 в effective stack, pot 30.", cueEn: "After the action, 90 remains in the effective stack and the pot is 30.", questionRu: "Какой SPR примерно?", questionEn: "What is the approximate SPR?",
    actionOptions: [o("a", "3", "3"), o("b", "30", "30", "RATIO_MISREAD"), o("c", "0.33", "0.33", "RATIO_INVERTED")],
    reasonOptions: [o("r1", "SPR = remaining effective stack / pot", "SPR = remaining effective stack / pot"), o("r2", "SPR = pot / stack", "SPR = pot / stack", "RATIO_INVERTED"), o("r3", "SPR equals preflop raise size", "SPR equals the preflop raise size", "WRONG_FORMULA")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 18, explanationRu: "FTGU-E01 связывает stack-to-pot ratio с количеством future decisions и leverage; LCM-01 делает эту геометрию operational.", explanationEn: "FTGU-E01 links stack-to-pot ratio with future decisions and leverage; LCM-01 makes that geometry operational.",
  },
  {
    id: "PM-FND-06-103", skillId: "FND-06", kind: "decision", sourceRefs: ["FTGU-E01", "LCM-01"], assumptions: ["same hand", "SPR 1 versus SPR 8"], cueRu: "Сравни тот же hand при SPR≈1 и SPR≈8.", cueEn: "Compare the same hand at SPR≈1 and SPR≈8.", questionRu: "Где future tree обычно более сжат?", questionEn: "Where is the future tree generally more compressed?",
    actionOptions: [o("a", "SPR≈1", "SPR≈1"), o("b", "SPR≈8", "SPR≈8", "SPR_BACKWARDS"), o("c", "Одинаково", "The same", "SPR_IGNORED")],
    reasonOptions: [o("r1", "Меньше stack relative to pot оставляет меньше leverage/decision depth", "Less stack relative to pot leaves less leverage/decision depth"), o("r2", "Higher SPR ends the hand faster", "Higher SPR ends the hand faster", "SPR_BACKWARDS"), o("r3", "SPR never changes future decisions", "SPR never changes future decisions", "SPR_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 20, explanationRu: "FTGU-E01 прямо связывает larger remaining stack/SPR с большей ролью future decisions.", explanationEn: "FTGU-E01 explicitly links larger remaining stack/SPR with a greater role for future decisions.",
  },
  {
    id: "PM-FND-06-104", skillId: "FND-06", kind: "decision", sourceRefs: ["LCM-01"], assumptions: ["three-way pot", "Hero 160bb", "Villain A 70bb", "Villain B 220bb"], cueRu: "Hero 160bb, один villain 70bb, другой 220bb.", cueEn: "Hero has 160bb, one villain 70bb, the other 220bb.", questionRu: "Можно ли использовать один nominal 160bb depth для всех branches?", questionEn: "Can one nominal 160bb depth be used for every branch?",
    actionOptions: [o("a", "Нет — effective stack зависит от противника/branch", "No — effective stack depends on opponent/branch"), o("b", "Да, Hero stack определяет всё", "Yes, Hero's stack determines everything", "HERO_STACK_ONLY"), o("c", "Да, использовать biggest stack", "Yes, use the biggest stack", "BIG_STACK_ONLY")],
    reasonOptions: [o("r1", "Каждая contested branch ограничена меньшим participating stack", "Each contested branch is capped by the smaller participating stack"), o("r2", "Multiway stacks simply add", "Multiway stacks simply add", "STACKS_ADDED"), o("r3", "Effective stack irrelevant multiway", "Effective stack is irrelevant multiway", "EFFECTIVE_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25, explanationRu: "LCM-01 делает effective-stack identity частью decision geometry; nominal seat stack не заменяет branch-specific effective depth.", explanationEn: "LCM-01 makes effective-stack identity part of decision geometry; nominal seat stack does not replace branch-specific effective depth.",
  },
  {
    id: "PM-FND-06-105", skillId: "FND-06", kind: "changed", sourceRefs: ["FTGU-E01", "LCM-01"], assumptions: ["same effective stack", "preflop pot doubles before flop"], cueRu: "Effective stack тот же, но preflop action удваивает pot к flop.", cueEn: "Effective stack is the same, but preflop action doubles the pot reaching the flop.", questionRu: "Как меняется flop SPR?", questionEn: "How does flop SPR change?",
    actionOptions: [o("a", "Падает", "It falls"), o("b", "Растёт", "It rises", "SPR_BACKWARDS"), o("c", "Не меняется", "No change", "POT_IGNORED")],
    reasonOptions: [o("r1", "Same remaining stack divided by a larger pot produces lower SPR", "The same remaining stack divided by a larger pot produces lower SPR"), o("r2", "SPR uses starting stack only", "SPR uses starting stack only", "NOMINAL_STACK_ONLY"), o("r3", "Pot size is not part of SPR", "Pot size is not part of SPR", "POT_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 18, explanationRu: "Это базовая geometry: larger pot при том же remaining stack сжимает future tree.", explanationEn: "This is basic geometry: a larger pot with the same remaining stack compresses the future tree.", changedVariables: ["pot_size", "spr"],
  },
  {
    id: "PM-FND-06-106", skillId: "FND-06", kind: "changed", sourceRefs: ["FTGU-E01", "LCM-01"], assumptions: ["same pot", "effective stack doubles"], cueRu: "Pot тот же, effective stack удваивается.", cueEn: "The pot is unchanged and effective stack doubles.", questionRu: "Как меняется SPR и importance future branches?", questionEn: "How do SPR and the importance of future branches change?",
    actionOptions: [o("a", "SPR растёт; future tree важнее", "SPR rises; the future tree matters more"), o("b", "SPR падает; tree сжимается", "SPR falls; the tree compresses", "SPR_BACKWARDS"), o("c", "Ничего не меняется", "Nothing changes", "DEPTH_IGNORED")],
    reasonOptions: [o("r1", "More stack relative to pot creates more leverage and future decisions", "More stack relative to pot creates more leverage and future decisions"), o("r2", "Deeper stacks reduce future decisions", "Deeper stacks reduce future decisions", "DEPTH_BACKWARDS"), o("r3", "Only current equity matters", "Only current equity matters", "EQUITY_ONLY")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 22, explanationRu: "FTGU-E01 explicitly ties larger stack-to-pot ratio to greater divergence between current equity and total EV.", explanationEn: "FTGU-E01 explicitly ties a larger stack-to-pot ratio to greater divergence between current equity and total EV.", changedVariables: ["effective_stack", "spr"],
  },
  {
    id: "PM-FND-06-107", skillId: "FND-06", kind: "boundary", sourceRefs: ["FTGU-E01", "LCM-01"], assumptions: ["nominal 200bb buy-in", "straddle makes working depth much shallower"], cueRu: "На экране 200bb nominal, но mandatory straddle резко меняет working blind unit и pot geometry.", cueEn: "The screen shows 200bb nominal, but a mandatory straddle sharply changes the working blind unit and pot geometry.", questionRu: "Можно ли автоматически применять обычную 200bb strategy?", questionEn: "Can ordinary 200bb strategy be applied automatically?",
    actionOptions: [o("a", "Нет — сначала пересчитать effective geometry", "No — recalculate effective geometry first"), o("b", "Да, nominal stack достаточно", "Yes, nominal stack is sufficient", "NOMINAL_STACK_ONLY"), o("c", "Да, straddle меняет только labels", "Yes, the straddle changes only labels", "STRADDLE_IGNORED")],
    reasonOptions: [o("r1", "Strategy depends on effective stack, pot and future leverage rather than headline BB count", "Strategy depends on effective stack, pot and future leverage rather than headline BB count"), o("r2", "Straddle never changes SPR", "A straddle never changes SPR", "STRADDLE_IGNORED"), o("r3", "Nominal buy-in controls all branches", "Nominal buy-in controls all branches", "NOMINAL_STACK_ONLY")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30, explanationRu: "LCM-01 treats straddle/effective depth as geometry-changing variables; FTGU-E01 explains why future EV depends on stack-to-pot ratio.", explanationEn: "LCM-01 treats straddle/effective depth as geometry-changing variables; FTGU-E01 explains why future EV depends on stack-to-pot ratio.",
  },
];
