import type { PracticalDecision } from "./types";

const o = (id: string, textRu: string, textEn: string, misconception?: string) => ({ id, textRu, textEn, misconception });
type V = { skillId: string; prefix: string; sourceRefs: string[]; baseRu: string; baseEn: string; signalRu: string; signalEn: string; directRu: string; directEn: string; whyRu: string; whyEn: string; change1Ru: string; change1En: string; change2Ru: string; change2En: string; vars1: string[]; vars2: string[] };

function build(v: V): PracticalDecision[] {
  const rows = [
    { kind: "recognition" as const, cueRu: v.baseRu, cueEn: v.baseEn, qRu: "Какой существенный фактор нужно определить до решения?", qEn: "Which material variable must be extracted before deciding?", goodRu: v.signalRu, goodEn: v.signalEn, changed: undefined },
    { kind: "decision" as const, cueRu: v.baseRu, cueEn: v.baseEn, qRu: "Какая практическая ветка решения лучше?", qEn: "Which practical branch is better?", goodRu: v.directRu, goodEn: v.directEn, changed: undefined },
    { kind: "changed" as const, cueRu: v.change1Ru, cueEn: v.change1En, qRu: "Как должна измениться пограничная ветка?", qEn: "How should the marginal branch change?", goodRu: "Пересчитать направление; прежнюю базовую линию не переносить автоматически", goodEn: "Recompute the direction; do not copy the old default automatically", changed: v.vars1 },
    { kind: "changed" as const, cueRu: v.change2Ru, cueEn: v.change2En, qRu: "Что изменилось причинно?", qEn: "What changed causally?", goodRu: "Вместе с изменённым фактором меняются соответствующий порог, диапазон или реализация equity", goodEn: "The relevant threshold/range/realization changed with the variable", changed: v.vars2 },
  ];
  return rows.map((r, i) => {
    const slot = i % 3;
    const good = o("good", r.goodRu, r.goodEn);
    const b1 = o("b1", "Сохранить прежнее действие без пересчёта", "Keep the old action without recomputing", "TRANSFER_AUTOPILOT");
    const b2 = o("b2", "Решать только по названию конкретной руки", "Decide only from the exact hand label", "HAND_LABEL_ONLY");
    const gr = o("goodR", v.whyRu, v.whyEn);
    const br1 = o("br1", "Одна стратегия переносится на все похожие ситуации", "One strategy transfers across all similar spots", "UNIVERSAL_RULE");
    const br2 = o("br2", "Существенный фактор не влияет на EV", "The material variable does not affect EV", "VARIABLE_IGNORED");
    return {
      id: `${v.prefix}-${101 + i}`,
      skillId: v.skillId,
      kind: r.kind,
      sourceRefs: v.sourceRefs,
      assumptions: ["B3 intensive non-identical transfer rep; source-scoped direction; no unreviewed exact frequency"],
      cueRu: r.cueRu,
      cueEn: r.cueEn,
      questionRu: r.qRu,
      questionEn: r.qEn,
      actionOptions: slot === 0 ? [good, b1, b2] : slot === 1 ? [b1, good, b2] : [b1, b2, good],
      reasonOptions: slot === 0 ? [br1, gr, br2] : slot === 1 ? [gr, br1, br2] : [br1, br2, gr],
      correctActionId: "good",
      correctReasonId: "goodR",
      targetSeconds: 20,
      explanationRu: v.whyRu,
      explanationEn: v.whyEn,
      changedVariables: r.changed,
    } satisfies PracticalDecision;
  });
}

const variants: V[] = [
  {
    skillId: "PF-01", prefix: "PM-B3-PF01", sourceRefs: ["FTGU-E02"],
    baseRu: "Пограничная RFI-рука: до Hero все сфолдили; прежде чем переносить ячейку чарта, нужно учесть контекст стола.",
    baseEn: "RFI fringe hand: action folds to Hero; table context must be read before importing a chart cell.",
    signalRu: "Позиция + игроки позади + рейк/глубина около границы диапазона",
    signalEn: "Position + players behind + rake/depth around the fringe",
    directRu: "Используй базовый диапазон как отправную точку и меняй пограничные руки только там, где контекст действительно меняет их EV",
    directEn: "Use the source default as a baseline, then tighten/loosen only where context changes fringe EV",
    whyRu: "Материал по RFI рассматривает чарты как базу: пограничные руки меняются из-за позиции, игроков позади, рейка и реализации equity.",
    whyEn: "FTGU-E02 treats opening charts as defaults whose fringe changes with position, players behind, rake and realization.",
    change1Ru: "Та же рука переходит с BTN на HJ, и позади остаётся больше игроков.",
    change1En: "Same hand moves BTN → HJ with more players behind.",
    change2Ru: "Та же позиция и рука; рейк выше, а игроки позади хорошо реализуют equity.",
    change2En: "Same position/hand; rake rises and callers behind realize well.",
    vars1: ["position", "players_behind"], vars2: ["rake", "realisation"],
  },
  {
    skillId: "PF-04", prefix: "PM-B3-PF04", sourceRefs: ["FTGU-E05"],
    baseRu: "Пограничный call из BB: текущая цена выглядит привлекательной, но исходный диапазон открытия и реализация equity отличаются.",
    baseEn: "BB marginal call: current price looks attractive but origin range and realization differ.",
    signalRu: "Цена × позиция открытия × закрытие экшена × реализация equity",
    signalEn: "Price × opener origin × closing action × realization",
    directRu: "Сравни EV call с EV fold; сохраняй пограничные call только когда цена и реализация equity совместно это поддерживают",
    directEn: "Compare call EV with fold EV; keep marginal calls only when price and realization jointly support them",
    whyRu: "Защита BB — это решение по цене и реализации equity, а не право продолжать только потому, что блайнд уже поставлен.",
    whyEn: "FTGU-E05 makes BB calls a price-plus-realization decision rather than a posted-blind entitlement.",
    change1Ru: "Та же рука и сайзинг: открывается EP вместо BTN.",
    change1En: "Same hand/size: opener changes BTN → EP.",
    change2Ru: "Та же рука и позиция открытия: сайзинг выше, а рейк сильнее наказывает пограничный call.",
    change2En: "Same hand/origin: open size increases and rake is less forgiving.",
    vars1: ["opener_origin"], vars2: ["open_size", "rake"],
  },
  {
    skillId: "PF-06", prefix: "PM-B3-PF06", sourceRefs: ["FTGU-E15", "FTGU-E16"],
    baseRu: "Hero выбирает структуру 3-бета против опен-рейзера, чьи fold/call тенденции не постоянны.",
    baseEn: "Hero chooses a 3-bet construction against an opener whose fold/call behavior is not constant.",
    signalRu: "Fold equity + диапазон продолжения + позиция определяют линейную, полярную или смешанную структуру",
    signalEn: "Fold equity + called branch + position determine linear/polar/mixed shape",
    directRu: "Когда фолдов мало, повышай плотность вэлью; поляризуй сильнее только если блефовая часть действительно получает фолды",
    directEn: "Use more linear value density when folds are scarce; polarize more only when the bluff region earns real folds",
    whyRu: "Структура 3-бета зависит от fold equity и от того, как руки-кандидаты играют после call.",
    whyEn: "FTGU-E15/E16 tie 3-bet shape to fold equity and how candidate hands perform when called.",
    change1Ru: "Те же позиции: оппонент вместо частых фолдов начинает широко коллировать.",
    change1En: "Same positions: opener shifts from overfolding → sticky caller.",
    change2Ru: "Тот же оппонент: Hero переходит из IP в OOP, и реализация equity ухудшается.",
    change2En: "Same opponent: Hero moves IP → OOP and realization worsens.",
    vars1: ["fold_equity", "called_branch"], vars2: ["position", "realisation"],
  },
  {
    skillId: "PF-07", prefix: "PM-B3-PF07", sourceRefs: ["FTGU-E17"],
    baseRu: "Hero получает 3-бет; ориентир по частоте защиты — не универсальная точная квота.",
    baseEn: "Hero faces a 3-bet; the source ballpark is not an exact universal defense quota.",
    signalRu: "Сайзинг 3-бета + позиция + форма диапазона + класс руки",
    signalEn: "3-bet size + position + range shape + hand family",
    directRu: "Распределяй fold/call/4-bet по EV веток, а не защищай заученный точный процент",
    directEn: "Allocate fold/call/4-bet by branch EV rather than defending an exact memorized percentage",
    whyRu: "Ориентир по продолжению — лишь база; его меняют сайзинг, позиция, диапазоны и оппонент.",
    whyEn: "FTGU-E17 explicitly treats its rough continuation model as a baseline modified by size, position, range and opponent.",
    change1Ru: "Та же рука и позиции: сайзинг 3-бета становится значительно больше.",
    change1En: "Same hand/positions: 3-bet size becomes much larger.",
    change2Ru: "Те же сайзинг и рука: Hero переходит из IP в OOP.",
    change2En: "Same size/hand: Hero changes IP → OOP.",
    vars1: ["threebet_size"], vars2: ["position"],
  },
  {
    skillId: "BL-03", prefix: "PM-B3-BL03", sourceRefs: ["FTGU-E05", "SLC-BB-VS-BTN"],
    baseRu: "BB против BTN: пограничная одномастная или связная рука находится у края диапазона защиты.",
    baseEn: "BB versus BTN: a marginal suited/connected holding sits near the defense fringe.",
    signalRu: "Ширина открытия BTN + цена + рейк + реализация equity",
    signalEn: "BTN origin width + price + rake + realization",
    directRu: "Защищайся шире, чем против сильных ранних диапазонов, но убирай слабейшую периферию при худшей цене, рейке или реализации equity",
    directEn: "Defend wider than versus strong origins, but let size/rake/realization remove the weakest fringe",
    whyRu: "BB против BTN защищается широко из-за цены и широкого открытия, но пограничные call исчезают, когда ухудшаются цена, рейк или реализация.",
    whyEn: "BB-vs-BTN is structurally wide because of price and opener origin, but FTGU-E05 explicitly suppresses marginal calls as price/rake/execution worsen.",
    change1Ru: "Та же рука: BTN открывает 4bb вместо 2.5bb.",
    change1En: "Same hand: BTN open 2.5bb → 4bb.",
    change2Ru: "Та же цена и рука: постфлоп-реализация меняется с хорошей на слабую в тяжёлом высокорейковом составе.",
    change2En: "Same price/hand: postflop realization assumption changes competent → poor/high-rake environment.",
    vars1: ["open_size"], vars2: ["realisation", "rake"],
  },
  {
    skillId: "BL-04", prefix: "PM-B3-BL04", sourceRefs: ["FTGU-E05"],
    baseRu: "Защита BB не может сохранять один и тот же порог при изменении сайзинга открытия.",
    baseEn: "BB defense cannot preserve one threshold when the opener changes size.",
    signalRu: "Текущая цена + вероятный диапазон открытия",
    signalEn: "Immediate price and likely selected opener range",
    directRu: "С ростом сайзинга сужай пограничные продолжения, если другой существенный фактор не компенсирует цену",
    directEn: "Tighten marginal continues as size grows unless another material factor offsets the cost",
    whyRu: "Цена напрямую меняет безубыточный порог и требования к реализации equity.",
    whyEn: "The price term directly changes break-even requirements and the practical realization burden.",
    change1Ru: "Та же позиция открытия и рука: 2bb → 3bb.",
    change1En: "Same origin/hand: 2bb → 3bb.",
    change2Ru: "Та же позиция открытия и рука: 3bb → 5bb в live-игре.",
    change2En: "Same origin/hand: 3bb → 5bb live open.",
    vars1: ["open_size"], vars2: ["open_size", "live_size"],
  },
  {
    skillId: "W4-BOARD-01", prefix: "PM-B3-BOARD", sourceRefs: ["FTGU-E07", "SLC-SRP-BOARD-CLASSES"],
    baseRu: "Текстура флопа видна сразу, но стратегия зависит от взаимодействия доски с пришедшими на флоп диапазонами.",
    baseEn: "A flop texture is visible, but strategy comes from board interaction with arriving ranges.",
    signalRu: "Преимущество диапазона + натсовое преимущество + покрытие сильных комбинаций у caller",
    signalEn: "Range advantage + nut advantage + caller coverage",
    directRu: "Сначала определи, чей диапазон лучше взаимодействует с доской, затем выбирай широкое или выборочное давление",
    directEn: "Classify ownership first, then choose range/selective pressure",
    whyRu: "Нельзя играть по одному ярлыку текстуры: кто владеет доской, определяют реальные префлоп-диапазоны.",
    whyEn: "FTGU-E07 rejects texture-label autopilot; actual preflop ranges determine who owns the board.",
    change1Ru: "Тот же флоп: диапазоны меняются с BTN–BB на HJ–BTN.",
    change1En: "Same flop: opener/caller origins change BTN-BB → HJ-BTN.",
    change2Ru: "Те же диапазоны: сухой высокий флоп меняется на связанный средний.",
    change2En: "Same ranges: flop changes dry-high → connected-middle.",
    vars1: ["arriving_ranges"], vars2: ["board_class"],
  },
  {
    skillId: "W4-RUNOUT-01", prefix: "PM-B3-RUNOUT", sourceRefs: ["FTGU-E20", "FTGU-E21"],
    baseRu: "Карту тёрна или ривера нужно оценивать через действия на предыдущих улицах.",
    baseEn: "A turn/river card must be interpreted through the previous street's action ancestry.",
    signalRu: "Ранаут × сохранившиеся или капнутые диапазоны",
    signalEn: "Runout × surviving/capped ranges",
    directRu: "Перед оценкой карты восстанови, какие сильные, вэлью- и блеф-комбинации дошли до этой улицы",
    directEn: "Reconstruct what strong/value/bluff regions survived before labeling the card",
    whyRu: "Восстановление натсов и сдвиг диапазонов зависят от точной предыдущей линии.",
    whyEn: "FTGU-E20/E21 make cap restoration and range shift dependent on the exact prior action.",
    change1Ru: "Та же карта тёрна: линия флопа меняется с bet-call на check-back.",
    change1En: "Same turn card: flop bet-call → check-back.",
    change2Ru: "Та же линия флопа: бланк на тёрне меняется на карту, закрывающую натсовые комбинации.",
    change2En: "Same flop action: turn blank → nut-changing completion.",
    vars1: ["action_ancestry"], vars2: ["runout_class"],
  },
  {
    skillId: "OOP-02", prefix: "PM-B3-OOP02", sourceRefs: ["FTGU-E08", "CP-G3-L05"],
    baseRu: "Средняя по силе рука OOP получает ставку на флопе и выбирает call или fold; разные call реализуют equity по-разному.",
    baseEn: "An OOP medium hand faces a flop bet and must choose continue/fold without pretending every call realizes equally.",
    signalRu: "Цена + устойчивость руки + будущая нагрузка и реализация equity",
    signalEn: "Price + hand robustness + future pressure/realization",
    directRu: "Продолжай с устойчивыми классами рук по хорошей цене; убирай слабые доминируемые руки, когда растут сайзинг и будущая нагрузка",
    directEn: "Continue robust classes at good prices; remove weak dominated classes as size/future pressure rises",
    whyRu: "Защита OOP — дерево цены и реализации equity, а не снимок текущей equity.",
    whyEn: "OOP defense is a price-plus-realization tree, not a current-equity snapshot.",
    change1Ru: "Та же рука и доска: c-bet меняется с 25% на 75% банка.",
    change1En: "Same hand/board: c-bet 25% → 75% pot.",
    change2Ru: "Та же цена: устойчивая пара+дро меняется на слабую доминируемую пару без редро.",
    change2En: "Same price: hand changes robust pair+draw → dominated weak pair/no redraw.",
    vars1: ["bet_size"], vars2: ["hand_robustness"],
  },
  {
    skillId: "IP-01", prefix: "PM-B3-IP01", sourceRefs: ["FTGU-E07"],
    baseRu: "Агрессор IP выбирает между ставкой всем диапазоном и выборочной ставкой.",
    baseEn: "The IP aggressor chooses between range betting and selective betting.",
    signalRu: "Взаимодействие доски с диапазонами + натсовое покрытие caller",
    signalEn: "Board×range concentration and caller nut coverage",
    directRu: "Используй частое небольшое давление только при устойчивом преимуществе диапазона; на выравнивающих досках играй более выборочно",
    directEn: "Use broad small pressure only when concentrated advantage survives; become selective on equalizers",
    whyRu: "Стратегия c-bet зависит от реального преимущества диапазона и натсов, а не только от инициативы.",
    whyEn: "FTGU-E07 ties c-bet strategy to actual range/nut advantage rather than initiative alone.",
    change1Ru: "Та же роль и диапазоны: сухой A-high флоп меняется на низкий связанный.",
    change1En: "Same role/ranges: dry A-high → low connected flop.",
    change2Ru: "Тот же флоп: меняется исходный диапазон caller, и у него становится больше натсовых комбинаций.",
    change2En: "Same flop: caller origin changes and gains more nut coverage.",
    vars1: ["board_class"], vars2: ["caller_range"],
  },
  {
    skillId: "3BP-05", prefix: "PM-B3-3BP05", sourceRefs: ["FTGU-E28", "FTGU-E29"],
    baseRu: "В 3-bet pot стратегия должна учитывать роль, доску и сайзинг, а не одну заученную частоту c-bet.",
    baseEn: "3BP strategy must retain role × board × size instead of one memorized c-bet rule.",
    signalRu: "Позиция и роль + насколько доска выравнивает диапазоны + сайзинг",
    signalEn: "Position/role + board equalization + sizing",
    directRu: "Выбирай широкое небольшое или выборочное давление по сочетанию факторов, а не просто по типу банка",
    directEn: "Choose broad/small versus selective pressure from the matrix, not from pot type",
    whyRu: "В 3-bet pot есть как узлы с высокой частотой ставки, так и узлы с выборочным давлением.",
    whyEn: "FTGU-E28/E29 explicitly split high-frequency and selective 3BP nodes.",
    change1Ru: "Та же роль и доска: маленький c-bet меняется на крупный выборочный сайзинг.",
    change1En: "Same role/board: small c-bet → large selected sizing.",
    change2Ru: "Те же сайзинг и роль: доска меняется с сохраняющей преимущество премиумов на выравнивающую.",
    change2En: "Same size/role: premium-preserving → equalizing board.",
    vars1: ["bet_size"], vars2: ["board_class"],
  },
  {
    skillId: "TURN-02", prefix: "PM-B3-TURN02", sourceRefs: ["FTGU-E21", "SLC-TURN-BARREL", "CP-G3-L07"],
    baseRu: "Hero поставил c-bet на флопе и решает, заслуживает ли тёрн второго вэлью- или блеф-барреля.",
    baseEn: "Hero c-bet the flop and chooses whether the turn deserves another value/bluff barrel.",
    signalRu: "Сдвиг ранаута × класс руки × диапазон, продолживший на флопе",
    signalEn: "Runout shift × hand class × surviving continue range",
    directRu: "Продолжай баррелить выбранные руки, только если тёрн улучшает вэлью, защиту руки или fold leverage",
    directEn: "Barrel selected hands only when the turn improves value/protection/fold leverage",
    whyRu: "Агрессия на тёрне зависит от сдвига карты и диапазона и класса руки, а не от инерции после ставки на флопе.",
    whyEn: "Turn aggression follows the card/range shift and hand class, not momentum from betting the flop.",
    change1Ru: "Та же линия флопа и рука: бланк в пользу caller меняется на scare-карту или сдвиг диапазона в пользу агрессора.",
    change1En: "Same flop line/hand: turn blank favors caller → scare/range-shift favors aggressor.",
    change2Ru: "Тот же тёрн: блеф-кандидат с низкой showdown value меняется на руку со средней showdown value.",
    change2En: "Same turn: hand changes low-showdown bluff candidate → medium showdown hand.",
    vars1: ["runout_class"], vars2: ["hand_family"],
  },
  {
    skillId: "TURN-03", prefix: "PM-B3-TURN03", sourceRefs: ["FTGU-E20", "CINJ-E06"],
    baseRu: "После check-back на флопе игрок OOP решает, стоит ли ставить probe на тёрне.",
    baseEn: "After a flop check-back, OOP considers probing the turn.",
    signalRu: "Что именно капнул check-back + вернул ли тёрн сильные комбинации диапазону IP",
    signalEn: "What the check-back capped plus whether the turn restores strong IP regions",
    directRu: "Ставь probe чаще только когда диапазон check-back действительно капнут или слишком широк",
    directEn: "Probe more only when the checked-back range is genuinely capped/overwide",
    whyRu: "Probe зависит от точного состава check-back диапазона и от того, какие сильные руки возвращает карта тёрна.",
    whyEn: "FTGU-E20 makes probing conditional on exact check-back composition and turn restoration.",
    change1Ru: "Тот же check-back: бланк на тёрне меняется на карту, возвращающую натсы диапазону IP.",
    change1En: "Same check-back: turn blank → card that restores IP nuts.",
    change2Ru: "Тот же тёрн: линия флопа меняется с check-back на bet-call.",
    change2En: "Same turn: flop action changes check-back → bet-call.",
    vars1: ["turn_range_shift"], vars2: ["flop_action"],
  },
  {
    skillId: "RIV-01", prefix: "PM-B3-RIV01", sourceRefs: ["LCM-09", "CP-G3-L02"],
    baseRu: "На ривере после вэлью-ставки уже нет следующей улицы: нужно понимать, какие худшие руки заплатят выбранный сайзинг.",
    baseEn: "A river value bet has no future street; it must name worse calls for the chosen size.",
    signalRu: "Диапазон худших call × сайзинг",
    signalEn: "Worse calling region × sizing",
    directRu: "Ставь только если достаточно худших рук реально коллируют этот сайзинг; иначе сохраняй showdown value через check",
    directEn: "Bet only when enough worse hands plausibly call that size; otherwise preserve showdown/check",
    whyRu: "Ривер-вэлью определяется против диапазона продолжения, а не тем, что рука часто впереди на шоудауне.",
    whyEn: "River value is defined against the continuing range, not by being ahead often at showdown.",
    change1Ru: "Та же рука и доска: порог call у оппонента становится заметно тайтовее.",
    change1En: "Same hand/board: villain call threshold tightens materially.",
    change2Ru: "Та же рука и диапазон: сайзинг увеличивается настолько, что слабейшие худшие call исчезают.",
    change2En: "Same hand/range: sizing increases enough to remove the weakest worse calls.",
    vars1: ["villain_calling_range"], vars2: ["river_size"],
  },
  {
    skillId: "RIV-03", prefix: "PM-B3-RIV03", sourceRefs: ["FTGU-E22", "CINJ-E02", "CINJ-E04"],
    baseRu: "Ривер-блафкетчер бьёт блефы, но проигрывает вэлью.",
    baseEn: "A river bluff-catcher beats bluffs but loses to value.",
    signalRu: "Цена × реальные блеф-кандидаты × blocker/unblocker эффект × предыдущая линия",
    signalEn: "Price × credible bluff supply × blockers/unblockers × ancestry",
    directRu: "Коллируй только если при данной цене в диапазоне остаётся достаточно реальных блефов",
    directEn: "Call only when enough credible bluffs survive for the price",
    whyRu: "Pot odds нужно связывать с реальными блеф-кандидатами и эффектом удаления; сама цена не создаёт блефы.",
    whyEn: "FTGU-E22 couples pot odds with actual bluff candidates and removal; price alone never creates bluffs.",
    change1Ru: "Та же цена и рука: линия тёрна убирает большую часть естественных недоехавших блефов.",
    change1En: "Same price/hand: turn line removes most natural missed bluffs.",
    change2Ru: "Та же линия и цена: blocker Hero меняется с блокирования вэлью на блокирование недоехавших блефов.",
    change2En: "Same line/price: Hero blocker changes from blocking value → blocking missed bluffs.",
    vars1: ["bluff_supply", "action_ancestry"], vars2: ["blocker_effect"],
  },
  {
    skillId: "MW-01", prefix: "PM-B3-MW01", sourceRefs: ["LCM-08", "SLC-MULTIWAY"],
    baseRu: "В multiway-банке абсолютная позиция за столом не показывает, кто ещё может действовать после Hero.",
    baseEn: "In a multiway pot, absolute seat position does not tell Hero who can still act behind.",
    signalRu: "Относительная позиция + закрытие экшена",
    signalEn: "Relative position + closing action",
    directRu: "Сужай пограничные ветки, когда Hero зажат между игроками; реализуй equity свободнее, когда Hero закрывает экшен",
    directEn: "Tighten marginal branches when sandwiched; realize more freely when closing the action",
    whyRu: "В multiway EV учитывает диапазоны игроков, которые ещё могут сделать call или raise после Hero.",
    whyEn: "Multiway EV includes ranges still able to call/raise after Hero.",
    change1Ru: "Та же рука и экшен: Hero из зажатой позиции начинает закрывать экшен.",
    change1En: "Same hand/action: Hero sandwiched → closes action.",
    change2Ru: "То же место и рука: вместо одного активного игрока позади остаются два сильных диапазона.",
    change2En: "Same seat/hand: one active player behind becomes two strong active ranges.",
    vars1: ["relative_position"], vars2: ["ranges_behind"],
  },
  {
    skillId: "MW-02", prefix: "PM-B3-MW02", sourceRefs: ["SLC-MULTIWAY", "EXT-PS-MULTIWAY-2026"],
    baseRu: "Порог силы одной пары или вэлью определяется сразу несколькими живыми диапазонами, а не одним оппонентом.",
    baseEn: "A one-pair/value threshold faces several live ranges rather than one opponent.",
    signalRu: "Количество и сила сохранившихся диапазонов + натсовый потенциал",
    signalEn: "Number/strength of surviving ranges + nut potential",
    directRu: "Повышай требования к вэлью-raise и stack-off, когда остаётся больше реально сильных диапазонов",
    directEn: "Raise value/stack-off requirements as more credible strong ranges remain",
    whyRu: "Дополнительные диапазоны повышают вероятность сильных или натсовых комбинаций у кого-то из игроков и обесценивают пограничную силу одной пары.",
    whyEn: "Additional ranges increase the chance somebody owns robust/nutted regions and devalue marginal one-pair strength.",
    change1Ru: "Та же рука и доска: heads-up меняется на three-way.",
    change1En: "Same hand/board: heads-up → three-way.",
    change2Ru: "То же число игроков: пассивный капнутый диапазон позади меняется на сильный некапнутый.",
    change2En: "Same number of players: passive capped range behind → strong uncapped range behind.",
    vars1: ["player_count"], vars2: ["range_strength"],
  },
  {
    skillId: "DEEP-01", prefix: "PM-B3-DEEP01", sourceRefs: ["LCM-01", "SLC-DEEP-SRP-OOP"],
    baseRu: "При 150–200bb effective будущие улицы и рычаг ставок остаются большими.",
    baseEn: "150–200bb effective: future streets and leverage remain large.",
    signalRu: "Натсовый потенциал + reverse implied odds + будущий leverage/SPR",
    signalEn: "Nut potential + reverse implied odds + leverage/future SPR",
    directRu: "Сильнее защищайся от переигрывания одной пары и выше цени устойчивые или натсовые ветки на будущих улицах",
    directEn: "Protect against one-pair overcommitment and value robust/nutted future branches more",
    whyRu: "Глубина увеличивает значение будущего leverage и риска reverse implied odds.",
    whyEn: "Audited deep material increases the importance of future leverage and reverse-implied-odds exposure.",
    change1Ru: "Та же рука и узел: 100bb → 200bb effective.",
    change1En: "Same hand/node: 100bb → 200bb effective.",
    change2Ru: "Та же глубина: позиция меняется с IP на OOP.",
    change2En: "Same depth: position changes IP → OOP.",
    vars1: ["effective_depth"], vars2: ["position", "realisation"],
  },
  {
    skillId: "DEEP-03", prefix: "PM-B3-DEEP03", sourceRefs: ["LCM-01", "SLC-PREFLOP-ADJUSTMENTS"],
    baseRu: "Straddle меняет рабочую единицу блайнда и порядок действий ещё до оценки карт.",
    baseEn: "A straddle changes the working blind unit and action order before any cards are evaluated.",
    signalRu: "Обязательная ставка + порядок действий + фактическая позиция + рабочий SPR",
    signalEn: "Forced unit + action order + effective position + working SPR",
    directRu: "Пересчитай геометрию в единицах straddle до применения префлоп- и постфлоп-ориентиров",
    directEn: "Recompute geometry in straddle units before applying preflop/postflop defaults",
    whyRu: "Одинаковое число фишек не означает одинаковую стратегическую глубину, если меняются обязательная ставка и порядок действий.",
    whyEn: "Nominal chips do not preserve strategic depth once the forced unit and action order change.",
    change1Ru: "Те же стеки и стол: без straddle → обязательный straddle.",
    change1En: "Same chips/table: no straddle → mandatory straddle.",
    change2Ru: "Тот же straddle: effective stack оппонента меняется с 300bb physical на 90bb physical.",
    change2En: "Same straddle: effective opponent changes from 300bb physical → 90bb physical.",
    vars1: ["straddle", "action_order"], vars2: ["effective_stack"],
  },
  {
    skillId: "EXP-01", prefix: "PM-B3-EXP01", sourceRefs: ["LCM-10"],
    baseRu: "Hero видит яркое действие в live-игре и хочет превратить его в рид.",
    baseEn: "Hero sees a vivid live action and wants to convert it into a read.",
    signalRu: "Наблюдение → конкретная ветка → уверенность; рид должен обновляться",
    signalEn: "Observation → exact branch → confidence; the read must remain updateable",
    directRu: "Считай одно наблюдение гипотезой для конкретной ветки; увеличивай отклонение только при повторяющихся согласованных данных",
    directEn: "Use one observation as a scoped hypothesis; scale deviation only with repeated consistent evidence",
    whyRu: "Дисциплина наблюдений не позволяет одному запоминающемуся шоудауну превратиться в глобальный ярлык на игрока.",
    whyEn: "LCM-10 requires evidence discipline so one memorable showdown does not become a global stereotype.",
    change1Ru: "Тот же игрок: повторяющиеся наблюдения в той же ветке усиливают исходную гипотезу.",
    change1En: "Same player: repeated same-branch evidence strengthens the original hypothesis.",
    change2Ru: "Тот же игрок: новые наблюдения в той же ветке противоречат исходной гипотезе.",
    change2En: "Same player: new same-branch evidence contradicts the original hypothesis.",
    vars1: ["evidence_strength"], vars2: ["evidence_reversal"],
  },
];

export const variationB3Decisions: PracticalDecision[] = variants.flatMap(build);
