import type { PracticalDecision } from "./types";

const o = (id: string, textRu: string, textEn: string, misconception?: string) => ({ id, textRu, textEn, misconception });

export const postflopAndLiveDecisions: PracticalDecision[] = [
  {
    id: "PM-W4-BOARD-001", skillId: "W4-BOARD-01", kind: "recognition", sourceRefs: ["FTGU-E07"],
    assumptions: ["preflop ranges known", "BTN vs BB family"],
    cueRu: "Флоп низкий и связанный.", cueEn: "The flop is low and connected.",
    questionRu: "Можно ли только по label доски решить, кому она принадлежит?", questionEn: "Can the board label alone determine which range owns it?",
    actionOptions: [o("a", "Нет — применить board к конкретным preflop ranges", "No — apply the board to the actual preflop ranges"), o("b", "Да — low connected всегда BB board", "Yes — low connected is always a BB board", "BOARD_LABEL_SHORTCUT"), o("c", "Да — initiative всегда сохраняет ownership", "Yes — initiative always preserves ownership", "INITIATIVE_AUTOPILOT")],
    reasonOptions: [o("r1", "Missing premiums и конкретная range composition определяют ownership", "Missing premiums and actual range composition determine ownership"), o("r2", "Rank labels достаточны без ranges", "Rank labels are sufficient without ranges", "BOARD_LABEL_SHORTCUT"), o("r3", "Preflop action перестаёт иметь значение на flop", "Preflop action stops mattering on the flop", "ANCESTRY_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25,
    explanationRu: "FTGU-E07 прямо предупреждает, что board texture нельзя интерпретировать без preflop range shape.",
    explanationEn: "FTGU-E07 explicitly warns that board texture cannot be interpreted without the preflop range shape.",
  },
  {
    id: "PM-W4-REL-001", skillId: "W4-REL-01", kind: "changed", sourceRefs: ["FTGU-E09"],
    assumptions: ["same top-pair hand", "villain continuing range becomes stronger"],
    cueRu: "У Hero всё ещё top pair, но range, который продолжает против raise, стал сильнее.", cueEn: "Hero still has top pair, but the range continuing versus a raise became stronger.",
    questionRu: "Изменилась ли relative strength?", questionEn: "Did relative strength change?",
    actionOptions: [o("a", "Да, снизилась", "Yes, it decreased"), o("b", "Нет, top pair всегда одна и та же strength", "No, top pair always has the same strength", "ABSOLUTE_HAND_ONLY"), o("c", "Стала сильнее из-за raise", "It became stronger because of the raise", "ACTION_CREATES_STRENGTH")],
    reasonOptions: [o("r1", "Value определяется против continuing range, а не названием made hand", "Value is determined versus the continuing range, not the made-hand label"), o("r2", "Absolute rank полностью определяет EV", "Absolute rank fully determines EV", "ABSOLUTE_HAND_ONLY"), o("r3", "Continuing range не влияет на value threshold", "The continuing range does not affect the value threshold", "CONTINUE_RANGE_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25,
    explanationRu: "FTGU-E09 отделяет 'вероятно лучшая рука' от value raise: важна equity против диапазона продолжения.",
    explanationEn: "FTGU-E09 separates 'probably the best hand' from a value raise: equity versus the continuing range matters.",
    changedVariables: ["continuing_range_strength"],
  },
  {
    id: "PM-OOP-01-001", skillId: "OOP-01", kind: "decision", sourceRefs: ["FTGU-E27"],
    assumptions: ["PFR OOP", "caller owns wet/middling board", "position compounds disadvantage"],
    cueRu: "PFR OOP на board, который хорошо попадает в caller range.", cueEn: "PFR is OOP on a board that strongly interacts with the caller's range.",
    questionRu: "Нужно ли c-bet из-за initiative?", questionEn: "Should Hero c-bet because of initiative?",
    actionOptions: [o("a", "Нет — high-frequency check/range-check может быть лучше", "No — a high-frequency check/range-check can be better"), o("b", "Да — PFR обязан ставить", "Yes — the PFR must bet", "INITIATIVE_AUTOPILOT"), o("c", "Всегда pot-size bet", "Always pot-size bet", "SIZE_AUTOPILOT")],
    reasonOptions: [o("r1", "Range disadvantage + OOP могут перевесить initiative", "Range disadvantage plus OOP can outweigh initiative"), o("r2", "Initiative гарантирует range advantage", "Initiative guarantees range advantage", "INITIATIVE_AUTOPILOT"), o("r3", "Checking автоматически caps range", "Checking automatically caps the range", "CHECK_ALWAYS_CAPS")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30,
    explanationRu: "FTGU-E27 прямо отвергает automatic c-bet based on initiative и допускает range-check simplification OOP.",
    explanationEn: "FTGU-E27 explicitly rejects automatic c-betting based on initiative and supports range-check simplification OOP.",
  },
  {
    id: "PM-OOP-03-001", skillId: "OOP-03", kind: "decision", sourceRefs: ["FTGU-E09"],
    assumptions: ["OOP", "strong hand vulnerable", "many bad turns", "value available now"],
    cueRu: "Strong made hand OOP уязвима к множеству turn cards.", cueEn: "A strong made hand OOP is vulnerable to many turn cards.",
    questionRu: "Что делает immediate raise более привлекательным?", questionEn: "What makes an immediate raise more attractive?",
    actionOptions: [o("a", "Immediate value + equity denial", "Immediate value plus equity denial"), o("b", "Только желание увеличить pot", "Only the desire to build a pot", "POT_BUILD_ONLY"), o("c", "Любая made hand обязана raise", "Any made hand must raise", "MADE_HAND_RAISE")],
    reasonOptions: [o("r1", "Vulnerability и OOP повышают urgency", "Vulnerability and OOP increase urgency"), o("r2", "Будущие карты не меняют equity", "Future cards do not change equity", "RUNOUT_IGNORED"), o("r3", "Raise for value оценивается против полного betting range", "A value raise is judged against the full betting range", "WRONG_VALUE_DENOMINATOR")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30,
    explanationRu: "FTGU-E09 связывает raise branch с vulnerability, immediate value и equity denial.",
    explanationEn: "FTGU-E09 links the raise branch to vulnerability, immediate value and equity denial.",
  },
  {
    id: "PM-IP-01-001", skillId: "IP-01", kind: "changed", sourceRefs: ["FTGU-E07"],
    assumptions: ["PFR IP", "board changes from concentrated advantage to equalising texture"],
    cueRu: "Board теперь сильнее соединяется с defender и нейтрализует часть overpair advantage.", cueEn: "The board now connects more strongly with the defender and neutralizes some overpair advantage.",
    questionRu: "Как меняется c-bet strategy?", questionEn: "How does c-bet strategy change?",
    actionOptions: [o("a", "Становится более selective/polar", "It becomes more selective/polar"), o("b", "Становится ещё более range-bet", "It becomes even more of a range bet", "RANGE_BET_AUTOPILOT"), o("c", "Не меняется", "It does not change", "BOARD_RANGE_IGNORED")],
    reasonOptions: [o("r1", "Defender получает больше two-pair/straight density и medium showdown hands чаще check", "The defender gains more two-pair/straight density and medium showdown hands check more"), o("r2", "High cards preflop гарантируют flop ownership", "Preflop high cards guarantee flop ownership", "PREFLOP_ADVANTAGE_STATIC"), o("r3", "Position делает board irrelevant", "Position makes the board irrelevant", "BOARD_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25,
    explanationRu: "FTGU-E07 описывает selective/unselective betting как spectrum, зависящий от board-range interaction.",
    explanationEn: "FTGU-E07 describes selective/unselective betting as a spectrum driven by board-range interaction.",
    changedVariables: ["board_range_interaction", "nut_advantage"],
  },
  {
    id: "PM-IP-04-001", skillId: "IP-04", kind: "boundary", sourceRefs: ["FTGU-E20"],
    assumptions: ["flop checked back", "turn can strengthen checked range"],
    cueRu: "PFR missed flop c-bet; caller думает о turn probe.", cueEn: "PFR checked back the flop; caller considers a turn probe.",
    questionRu: "Можно ли mechanical probe/overbet каждый turn?", questionEn: "Can Hero mechanically probe/overbet every turn?",
    actionOptions: [o("a", "Нет — проверить exact checked range и new card", "No — inspect the exact checked range and new card"), o("b", "Да — missed c-bet всегда caps range", "Yes — a missed c-bet always caps the range", "MISSED_CBET_ALWAYS_CAPS"), o("c", "Да — turn card не влияет на cap", "Yes — the turn card does not affect the cap", "TURN_CAP_IGNORED")],
    reasonOptions: [o("r1", "Turn может вернуть strong/nutted regions в checked range", "The turn can restore strong/nutted regions to the checked range"), o("r2", "Check-back навсегда удаляет всю value", "A check-back permanently removes all value", "CHECKBACK_NO_VALUE"), o("r3", "Probe определяется только position", "A probe is determined only by position", "RANGE_HISTORY_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30,
    explanationRu: "FTGU-E20 прямо предупреждает, что missed c-bet не означает автоматический overbet probe.",
    explanationEn: "FTGU-E20 explicitly warns that a missed c-bet does not imply an automatic overbet probe.",
  },
  {
    id: "PM-3BP-01-001", skillId: "3BP-01", kind: "decision", sourceRefs: ["FTGU-E28"],
    assumptions: ["3-bet pot", "dry high-card/paired family", "aggressor premium density preserved"],
    cueRu: "3-bettor сохраняет concentrated premium advantage на dry high-card/paired flop.", cueEn: "The 3-bettor preserves concentrated premium density on a dry high-card/paired flop.",
    questionRu: "Какой practical flop branch поддерживает source?", questionEn: "Which practical flop branch does the source support?",
    actionOptions: [o("a", "Small high-frequency bet", "Small high-frequency bet"), o("b", "Range check только из-за OOP", "Range check solely because of OOP", "POSITION_ONLY"), o("c", "Large polar bet всей range", "Large polar bet with the whole range", "SIZE_SHAPE_MISMATCH")],
    reasonOptions: [o("r1", "Concentrated preflop advantage сохраняется, а small size подходит broad protection range", "The concentrated preflop advantage survives and a small size fits a broad protection range"), o("r2", "3-bet pot всегда range-bet независимо от board", "A 3-bet pot is always a range bet regardless of board", "THREEBET_AUTOPILOT"), o("r3", "Position полностью определяет frequency", "Position fully determines frequency", "POSITION_ONLY")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30,
    explanationRu: "FTGU-E28 поддерживает high-frequency small betting там, где flop сохраняет premium-range advantage.",
    explanationEn: "FTGU-E28 supports high-frequency small betting where the flop preserves premium-range advantage.",
  },
  {
    id: "PM-3BP-05-001", skillId: "3BP-05", kind: "changed", sourceRefs: ["FTGU-E28", "FTGU-E29"],
    assumptions: ["3-bet pot", "flop shifts from dry premium-preserving to coordinated equalising"],
    cueRu: "Flop теперь coordinated/middling и заметно equalises ranges.", cueEn: "The flop is now coordinated/middling and materially equalizes the ranges.",
    questionRu: "Что происходит с range-bet license?", questionEn: "What happens to the range-bet license?",
    actionOptions: [o("a", "Слабеет; нужен split/selective strategy", "It weakens; a split/selective strategy is needed"), o("b", "Усиливается", "It strengthens", "BOARD_EQUALIZATION_BACKWARDS"), o("c", "Не меняется, потому что pot 3-bet", "It does not change because the pot is 3-bet", "THREEBET_AUTOPILOT")],
    reasonOptions: [o("r1", "Shared nutted hands и caller coverage нейтрализуют premium advantage", "Shared nutted hands and caller coverage neutralize the premium advantage"), o("r2", "3-bettor всегда uncapped, значит всегда range-bet", "The 3-bettor is always uncapped, so always range-bet", "UNCAPPED_AUTOPILOT"), o("r3", "High cards alone determine ownership", "High cards alone determine ownership", "BOARD_LABEL_SHORTCUT")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30,
    explanationRu: "FTGU-E29 описывает selective middle ground, когда preflop advantage materially equalised.",
    explanationEn: "FTGU-E29 describes the selective middle ground when the preflop advantage is materially equalized.",
    changedVariables: ["board_class", "range_equalization"],
  },
  {
    id: "PM-4BP-01-001", skillId: "4BP-01", kind: "decision", sourceRefs: ["CP-G3-L10"],
    assumptions: ["low-SPR 4-bet pot", "favourable/neutral flop in studied family"],
    cueRu: "Low-SPR 4-bet pot, flop не разрушает advantage 4-bettor.", cueEn: "Low-SPR 4-bet pot, flop does not destroy the 4-bettor's advantage.",
    questionRu: "Какое simplification source считает практичным?", questionEn: "Which simplification does the source consider practical?",
    actionOptions: [o("a", "Small range-bet family", "Small range-bet family"), o("b", "Всегда jam flop", "Always jam the flop", "LOW_SPR_JAM_AUTOPILOT"), o("c", "Всегда range check", "Always range check", "LOW_SPR_CHECK_AUTOPILOT")],
    reasonOptions: [o("r1", "Low SPR compresses tree; source uses range-bet/check compression by range relation", "Low SPR compresses the tree; the source uses range-bet/check compression by range relation"), o("r2", "Exact source quarter-pot size универсален", "The source's exact quarter-pot size is universal", "EXACT_SIZE_OVERGENERALIZATION"), o("r3", "Board relation не важна в 4-bet pot", "Board relation does not matter in a 4-bet pot", "BOARD_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30,
    explanationRu: "CP-G3-L10 поддерживает compression mechanism, но exact size/frequency остаются configuration-dependent.",
    explanationEn: "CP-G3-L10 supports the compression mechanism, while exact size/frequency remain configuration-dependent.",
  },
  {
    id: "PM-4BP-04-001", skillId: "4BP-04", kind: "decision", sourceRefs: ["CP-G3-L10"],
    assumptions: ["turn low SPR", "medium-EV hand", "large bet creates easy jam remainder"],
    cueRu: "Large turn bet оставит stack, который Villain удобно jams.", cueEn: "A large turn bet leaves a stack that Villain can conveniently jam.",
    questionRu: "Какой factor обязан войти в size choice?", questionEn: "Which factor must enter the sizing choice?",
    actionOptions: [o("a", "Jam exposure / reopen risk", "Jam exposure / reopen risk"), o("b", "Только current equity", "Only current equity", "CURRENT_EQUITY_ONLY"), o("c", "Только pot size", "Only pot size", "POT_ONLY")],
    reasonOptions: [o("r1", "Bet может повысить jam frequency и ухудшить equity realisation medium region", "The bet can increase jam frequency and worsen equity realization for the medium region"), o("r2", "Future response не влияет на EV bet", "Future response does not affect bet EV", "FUTURE_BRANCH_IGNORED"), o("r3", "Low SPR означает auto-stackoff", "Low SPR means automatic stackoff", "LOW_SPR_AUTOSTACK")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30,
    explanationRu: "CP-G3-L10 называет jam-exposure отдельным sizing gate.", explanationEn: "CP-G3-L10 treats jam exposure as a separate sizing gate.",
  },
  {
    id: "PM-TURN-01-001", skillId: "TURN-01", kind: "recognition", sourceRefs: ["FTGU-E21"],
    assumptions: ["flop caller may or may not have raised strong hands"],
    cueRu: "Hero хочет назвать turn blank и продолжить pressure.", cueEn: "Hero wants to call the turn a blank and continue pressure.",
    questionRu: "Что проверить первым?", questionEn: "What should be checked first?",
    actionOptions: [o("a", "Был ли flop call branch реально capped", "Whether the flop call branch was actually capped"), o("b", "Только rank turn card", "Only the turn-card rank", "TURN_LABEL_ONLY"), o("c", "Только hero hand", "Only Hero's hand", "HAND_ONLY")],
    reasonOptions: [o("r1", "Cap зависит от того, были ли strongest hands подняты ранее", "The cap depends on whether the strongest hands were raised earlier"), o("r2", "Любой flop call автоматически capped", "Any flop call is automatically capped", "CALL_ALWAYS_CAPS"), o("r3", "Action history не влияет на turn", "Action history does not affect the turn", "ANCESTRY_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25,
    explanationRu: "FTGU-E21 начинает turn logic с вопроса, имел ли caller flop raising range.",
    explanationEn: "FTGU-E21 starts turn logic by asking whether the caller had a flop raising range.",
  },
  {
    id: "PM-TURN-02-001", skillId: "TURN-02", kind: "changed", sourceRefs: ["FTGU-E21"],
    assumptions: ["caller capped on blank", "turn creates relevant straights/flushes/two pair"],
    cueRu: "Turn materially changes nut region caller.", cueEn: "The turn materially changes the caller's nut region.",
    questionRu: "Как меняется barrel plan?", questionEn: "How does the barrel plan change?",
    actionOptions: [o("a", "Становится более selective/polar", "It becomes more selective/polar"), o("b", "Продолжается как против capped range", "Continue as if facing a capped range", "CAP_STATE_STALE"), o("c", "Range-bet всех medium hands", "Range-bet all medium hands", "MEDIUM_AUTOBET")],
    reasonOptions: [o("r1", "Game-changing card может uncap caller", "A game-changing card can uncap the caller"), o("r2", "Cap навсегда фиксируется flop action", "The cap is permanently fixed by flop action", "CAP_STATE_STALE"), o("r3", "Turn card не меняет ownership", "The turn card does not change ownership", "TURN_OWNERSHIP_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30,
    explanationRu: "FTGU-E21 прямо показывает, что capped flop branch может стать uncapped на game-changing turn.",
    explanationEn: "FTGU-E21 explicitly shows that a capped flop branch can become uncapped on a game-changing turn.",
    changedVariables: ["turn_card", "caller_cap_state"],
  },
  {
    id: "PM-RIV-02-001", skillId: "RIV-02", kind: "decision", sourceRefs: ["FTGU-E23"],
    assumptions: ["river", "multiple missed draws", "value region known"],
    cueRu: "На river осталось несколько missed draws.", cueEn: "Several missed draws remain on the river.",
    questionRu: "Как выбирать bluffs?", questionEn: "How should bluffs be selected?",
    actionOptions: [o("a", "Выбрать нужный объём по value/size и лучшие blocker/ancestry candidates", "Use value/size to set volume and choose the best blocker/ancestry candidates"), o("b", "Bluff every missed draw", "Bluff every missed draw", "BLUFF_EVERY_MISS"), o("c", "Bluff only lowest card", "Bluff only the lowest card", "ARBITRARY_HAND_RULE")],
    reasonOptions: [o("r1", "River bluff supply должен существовать в prior branches и поддерживать value region", "River bluff supply must exist in prior branches and support the value region"), o("r2", "No showdown value автоматически означает bluff", "No showdown value automatically means bluff", "BLUFF_EVERY_MISS"), o("r3", "Blockers работают независимо от line", "Blockers work independently of the line", "BLOCKER_WITHOUT_ANCESTRY")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 35,
    explanationRu: "FTGU-E23 требует сначала value region/size, затем blocker + ancestry selection; не все missed draws блефуют.",
    explanationEn: "FTGU-E23 requires value region/size first, then blocker plus ancestry selection; not every missed draw bluffs.",
  },
  {
    id: "PM-RIV-03-001", skillId: "RIV-03", kind: "decision", sourceRefs: ["FTGU-E22"],
    assumptions: ["two bluff-catchers same pair rank", "different removal effects"],
    cueRu: "Два bluff-catcher имеют одинаковую pair rank, но разные suits/blockers.", cueEn: "Two bluff-catchers have the same pair rank but different suits/blockers.",
    questionRu: "Обязаны ли они иметь одинаковый call EV?", questionEn: "Must they have the same call EV?",
    actionOptions: [o("a", "Нет", "No"), o("b", "Да", "Yes", "PAIR_RANK_ONLY"), o("c", "Да, если pot size одинаковый", "Yes, if pot size is the same", "PAIR_RANK_ONLY")],
    reasonOptions: [o("r1", "Один может block value и preserve bluffs, другой — block natural bluffs", "One may block value and preserve bluffs while the other blocks natural bluffs"), o("r2", "Pair rank полностью определяет bluff catch", "Pair rank fully determines bluff catching", "PAIR_RANK_ONLY"), o("r3", "Removal matters only preflop", "Removal matters only preflop", "REMOVAL_PREFLOP_ONLY")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30,
    explanationRu: "FTGU-E22 прямо показывает, что одинаковая relative pair strength может иметь разный call EV из-за removal.",
    explanationEn: "FTGU-E22 explicitly shows that identical relative pair strength can have different call EV because of removal.",
  },
  {
    id: "PM-RIV-05-001", skillId: "RIV-05", kind: "changed", sourceRefs: ["FTGU-E24", "FTGU-E25"],
    assumptions: ["same river size", "branch changes from airless underbluffed to air-rich overbluffed"],
    cueRu: "Bluff supply меняется с почти отсутствующего на чрезмерный.", cueEn: "Bluff supply changes from nearly absent to excessive.",
    questionRu: "Как должен двигаться exploit call threshold?", questionEn: "How should the exploit call threshold move?",
    actionOptions: [o("a", "От overfold к wider calls", "From overfolding toward wider calls"), o("b", "Не менять — MDF всегда одинаков", "Do not change — MDF is always the same", "MDF_AUTOPILOT"), o("c", "Всегда fold large bet", "Always fold a large bet", "SIZE_ONLY_FOLD")],
    reasonOptions: [o("r1", "Actual bluff/value composition branch-specific и может оправдать отклонение от baseline", "Actual bluff/value composition is branch-specific and can justify deviation from baseline"), o("r2", "Opponent evidence не должно менять strategy", "Opponent evidence should not change strategy", "EVIDENCE_IGNORED"), o("r3", "Large size всегда underbluffed", "A large size is always underbluffed", "SIZE_STEREOTYPE")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 35,
    explanationRu: "FTGU-E24/E25 дают симметричный principle: overfold underbluffed branches, overcall genuinely overbluffed branches.",
    explanationEn: "FTGU-E24/E25 give the symmetric principle: overfold underbluffed branches and overcall genuinely overbluffed branches.",
    changedVariables: ["bluff_density", "branch_evidence"],
  },
  {
    id: "PM-RIV-04-001", skillId: "RIV-04", kind: "boundary", sourceRefs: ["CINJ-E08"],
    assumptions: ["small OOP river probe", "prior bet-check line"],
    cueRu: "Hero рассматривает small river block/probe.", cueEn: "Hero considers a small river block/probe.",
    questionRu: "Как НЕ надо объяснять эту ставку?", questionEn: "How should this bet NOT be explained?",
    actionOptions: [o("a", "Как мистическую ставку 'чтобы не получить bigger bet'", "As a mystical bet 'to avoid facing a bigger bet'"), o("b", "Через thin value/bluff function и range shape", "Through thin-value/bluff function and range shape", "CORRECT_FRAME_DISTRACTOR"), o("c", "Через response elasticity", "Through response elasticity", "CORRECT_FRAME_DISTRACTOR")],
    reasonOptions: [o("r1", "Primary EV должен существовать через range/hand function; induce/avoid-bet story вторичен", "Primary EV must come from range/hand function; induce/avoid-bet stories are secondary"), o("r2", "Block bet автоматически блокирует raise", "A block bet automatically prevents a raise", "BLOCK_BET_MAGIC"), o("r3", "Small size не требует range logic", "A small size requires no range logic", "SIZE_WITHOUT_RANGE")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30,
    explanationRu: "CINJ-E08 прямо отвергает объяснение block bet как 'prevent bigger bet'.",
    explanationEn: "CINJ-E08 explicitly rejects explaining a block bet as simply preventing a bigger bet.",
  },
  {
    id: "PM-MW-01-001", skillId: "MW-01", kind: "decision", sourceRefs: ["SLC-M04-L36"],
    assumptions: ["three-way", "Hero sandwiched", "uncapped player behind"],
    cueRu: "Hero между bettor и ещё одним live range позади.", cueEn: "Hero is between the bettor and another live range behind.",
    questionRu: "Почему HU defence нельзя копировать?", questionEn: "Why can't heads-up defense be copied?",
    actionOptions: [o("a", "Нужно учитывать range behind и shared defence", "Account for the range behind and shared defense"), o("b", "Hero несёт всю MDF burden", "Hero carries the entire MDF burden", "HU_MDF_MULTIWAY"), o("c", "Player behind irrelevant until river", "The player behind is irrelevant until the river", "RANGE_BEHIND_IGNORED")],
    reasonOptions: [o("r1", "Sandwich position делает calls/raises уязвимыми к action behind", "Sandwich position makes calls/raises vulnerable to action behind"), o("r2", "Multiway работает как heads-up с большим pot", "Multiway is just heads-up with a bigger pot", "HU_COPY_MULTIWAY"), o("r3", "Closing action не имеет значения multiway", "Closing action does not matter multiway", "CLOSING_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30,
    explanationRu: "SLC-M04-L36 называет sandwich effect и shared defence центральным отличием multiway.",
    explanationEn: "SLC-M04-L36 identifies the sandwich effect and shared defense as central multiway differences.",
  },
  {
    id: "PM-MW-03-001", skillId: "MW-03", kind: "boundary", sourceRefs: ["SLC-M04-L36"],
    assumptions: ["multiway", "random low-equity air candidate"],
    cueRu: "Hero хочет добавить bluff без equity/removal просто потому, что heads-up он иногда работает.", cueEn: "Hero wants to add a bluff with no equity/removal because it sometimes works heads-up.",
    questionRu: "Хороший ли это default?", questionEn: "Is this a good default?",
    actionOptions: [o("a", "Нет", "No"), o("b", "Да, multiway нужно bluff больше", "Yes, multiway requires more bluffing", "MORE_BLUFF_MULTIWAY"), o("c", "Да, blockers не нужны", "Yes, blockers are unnecessary", "NO_REMOVAL_MULTIWAY")],
    reasonOptions: [o("r1", "More ranges must be cleared; source tightens bluffs toward equity + removal", "More ranges must be cleared; the source tightens bluffs toward equity plus removal"), o("r2", "Shared defence увеличивает random bluff EV", "Shared defense increases random bluff EV", "SHARED_DEFENCE_BACKWARDS"), o("r3", "Air имеет ту же collision risk, что heads-up", "Air has the same collision risk as heads-up", "COLLISION_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 25,
    explanationRu: "SLC-M04-L36 прямо отвергает random low-equity 'savage' bluffs multiway.",
    explanationEn: "SLC-M04-L36 explicitly rejects random low-equity 'savage' bluffs multiway.",
  },
  {
    id: "PM-DEEP-01-001", skillId: "DEEP-01", kind: "decision", sourceRefs: ["SLC-M02-L21"],
    assumptions: ["200bb", "OOP", "dynamic board", "medium equity region"],
    cueRu: "Hero deep OOP на dynamic board.", cueEn: "Hero is deep OOP on a dynamic board.",
    questionRu: "Какой defensive default source предпочитает при uncertainty?", questionEn: "Which defensive default does the source prefer under uncertainty?",
    actionOptions: [o("a", "Protected check-call structure + selective raises", "Protected check-call structure plus selective raises"), o("b", "Force marginal value into big pot", "Force marginal value into a big pot", "DEEP_VALUE_FORCE"), o("c", "Check-fold all medium equity", "Check-fold all medium equity", "MIDDLE_RANGE_ABANDON")],
    reasonOptions: [o("r1", "Deep SPR + position reduce realised EV and make runouts matter more", "Deep SPR plus position reduce realized EV and make runouts matter more"), o("r2", "Raw equity equals EV at 200bb", "Raw equity equals EV at 200bb", "RAW_EQUITY_ONLY"), o("r3", "Overpairs must always leave check-call range", "Overpairs must always leave the check-call range", "CHECK_RANGE_UNPROTECTED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 35,
    explanationRu: "SLC-M02-L21 учит protected checking/calling deep OOP и сохраняет strong hands внутри call line.",
    explanationEn: "SLC-M02-L21 teaches protected checking/calling deep OOP and retains strong hands in the call line.",
  },
  {
    id: "PM-DEEP-01-002", skillId: "DEEP-01", kind: "changed", sourceRefs: ["SLC-M02-L21"],
    assumptions: ["same deep OOP spot", "opponent bet size becomes larger"],
    cueRu: "C-bet size увеличился.", cueEn: "The c-bet size increased.",
    questionRu: "Как source двигает raise/call mix?", questionEn: "How does the source move the raise/call mix?",
    actionOptions: [o("a", "Меньше raises, больше calls", "Fewer raises, more calls"), o("b", "Больше raises, меньше calls", "More raises, fewer calls", "SIZE_RESPONSE_BACKWARDS"), o("c", "Не меняет", "No change", "SIZE_IGNORED")],
    reasonOptions: [o("r1", "Large size повышает investment/pressure; strong hands/draws защищают call line", "Large size increases investment/pressure; strong hands/draws protect the call line"), o("r2", "Large bet всегда слабее range", "A large bet always means a weaker range", "SIZE_TELL_INVENTED"), o("r3", "Deep stacks отменяют sizing effects", "Deep stacks eliminate sizing effects", "SIZE_IGNORED")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30,
    explanationRu: "SLC-M02-L21 прямо говорит: versus larger bets call more and raise less.",
    explanationEn: "SLC-M02-L21 explicitly says: versus larger bets, call more and raise less.",
    changedVariables: ["bet_size"],
  },
  {
    id: "PM-EXP-01-001", skillId: "EXP-01", kind: "boundary", sourceRefs: ["FTGU-E25"],
    assumptions: ["opponent labelled aggressive", "no exact-line evidence"],
    cueRu: "Villain выглядит aggressive.", cueEn: "Villain looks aggressive.",
    questionRu: "Достаточно ли этого для wider river calls?", questionEn: "Is that enough for wider river calls?",
    actionOptions: [o("a", "Нет — нужна branch-specific evidence", "No — branch-specific evidence is needed"), o("b", "Да — aggressive label достаточно", "Yes — the aggressive label is enough", "PROFILE_OVERGENERALIZATION"), o("c", "Да — любой reg overbluffs", "Yes — every reg overbluffs", "POOL_STEREOTYPE")],
    reasonOptions: [o("r1", "Нужны exact line, available air и evidence of overbluff", "The exact line, available air and evidence of overbluffing are needed"), o("r2", "Player type заменяет range analysis", "Player type replaces range analysis", "PROFILE_OVERGENERALIZATION"), o("r3", "One showdown validates all branches", "One showdown validates all branches", "ONE_SAMPLE_READ")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30,
    explanationRu: "FTGU-E25 привязывает exploit к exact overbluffed branch, а не generic aggressive label.",
    explanationEn: "FTGU-E25 attaches the exploit to the exact overbluffed branch, not a generic aggressive label.",
  },
  {
    id: "PM-EXP-05-001", skillId: "EXP-05", kind: "boundary", sourceRefs: ["CINJ-E08"],
    assumptions: ["source claims many humans overfold small river probes", "field validation absent"],
    cueRu: "Source предлагает exploit small river probe и описывает population overfold.", cueEn: "The source proposes a small river probe exploit and describes population overfolding.",
    questionRu: "Что можно перенести в product truth?", questionEn: "What can be promoted to product truth?",
    actionOptions: [o("a", "Mechanism, но не universal population magnitude", "The mechanism, but not a universal population magnitude"), o("b", "Universal rule: unknown live players overfold", "Universal rule: unknown live players overfold", "POOL_CLAIM_UNIVERSALIZED"), o("c", "Exact source frequencies", "Exact source frequencies", "VISUAL_FREQUENCY_COPIED")],
    reasonOptions: [o("r1", "CINJ-E08 помечает pool claims как requiring validation", "CINJ-E08 marks pool claims as requiring validation"), o("r2", "Любой source population claim универсален", "Any source population claim is universal", "POOL_CLAIM_UNIVERSALIZED"), o("r3", "Visual-dependent frequencies можно восстановить из memory", "Visual-dependent frequencies can be reconstructed from memory", "SOURCE_PURITY_BREACH")],
    correctActionId: "a", correctReasonId: "r1", targetSeconds: 30,
    explanationRu: "CINJ-E08 отделяет accepted mechanism от field-dependent pool hypothesis.",
    explanationEn: "CINJ-E08 separates the accepted mechanism from the field-dependent pool hypothesis.",
  },
];
