export type LiveMemoryRule={id:string;triggerRu:string;triggerEn:string;ruleRu:string;ruleEn:string;boundaryRu:string;boundaryEn:string;skillIds:string[];sourceRefs:string[]};

export const liveA9MemoryRules:LiveMemoryRule[]=[
{id:"A9-RULE-WHO-STILL-ACTS",triggerRu:"Multiway decision.",triggerEn:"Multiway decision.",ruleRu:"До cards-first reasoning назови, кто ещё может действовать и закрываешь ли ты action.",ruleEn:"Before cards-first reasoning, name who can still act and whether you close the action.",boundaryRu:"Absolute IP/OOP label is insufficient multiway.",boundaryEn:"An absolute IP/OOP label is insufficient multiway.",skillIds:["MW-01"],sourceRefs:["LCM-08","SLC-MULTIWAY"]},
{id:"A9-RULE-MORE-RANGES-HIGHER-BAR",triggerRu:"Банк становится multiway.",triggerEn:"The pot becomes multiway.",ruleRu:"С каждым дополнительным credible range повышай требования к marginal value и bluff; цени nut potential и robust redraws.",ruleEn:"With each additional credible range, raise the bar for marginal value/bluffs; value nut potential and robust redraws.",boundaryRu:"Do not copy heads-up top-pair or bluff thresholds.",boundaryEn:"Do not copy heads-up top-pair or bluff thresholds.",skillIds:["MW-02","MW-03"],sourceRefs:["LCM-08","SLC-MULTIWAY"]},
{id:"A9-RULE-LIMPER-BRANCH-EV",triggerRu:"Перед Hero limper(s).",triggerEn:"There are limper(s) before Hero.",ruleRu:"Не спрашивай «можно ли iso?». Сравни iso/overlimp/fold через folds, when-called performance, position и investment.",ruleEn:"Do not ask 'can I isolate?'. Compare isolate/overlimp/fold through folds, when-called performance, position and investment.",boundaryRu:"Playable hand does not imply automatic isolation.",boundaryEn:"A playable hand does not imply automatic isolation.",skillIds:["MW-04"],sourceRefs:["FTGU-E03"]},
{id:"A9-RULE-DEPTH-IS-FUTURE-TREE",triggerRu:"Стек заметно глубже обычного.",triggerEn:"The stack is materially deeper than usual.",ruleRu:"Переведи depth в future-tree questions: nut potential, reverse implied odds, leverage и post-action SPR.",ruleEn:"Translate depth into future-tree questions: nut potential, reverse implied odds, leverage and post-action SPR.",boundaryRu:"Nominal bb count is not itself a strategy.",boundaryEn:"The nominal bb count is not itself a strategy.",skillIds:["DEEP-01","DEEP-04"],sourceRefs:["LCM-01","SLC-DEEP-SRP-OOP","FTGU-E04"]},
{id:"A9-RULE-STRADDLE-RESETS-GEOMETRY",triggerRu:"Появился mandatory straddle.",triggerEn:"A mandatory straddle appears.",ruleRu:"Сбрось старую геометрию: новая forced unit → новый effective depth → action order/position → future SPR.",ruleEn:"Reset the old geometry: new forced unit → new effective depth → action order/position → future SPR.",boundaryRu:"Same physical dollars do not mean same strategic depth.",boundaryEn:"The same physical dollars do not mean the same strategic depth.",skillIds:["DEEP-03"],sourceRefs:["LCM-01","SLC-PREFLOP-ADJUSTMENTS"]},
{id:"A9-RULE-SOURCE-CEILING",triggerRu:"Хочется extrapolate 200bb lesson на 300bb+.",triggerEn:"Want to extrapolate a 200bb lesson to 300bb+.",ruleRu:"Используй только directional mechanism, не выдавай exact 300bb+ strategy без authority.",ruleEn:"Use only the directional mechanism; do not claim exact 300bb+ strategy without authority.",boundaryRu:"DEEP-02 remains source-blocked.",boundaryEn:"DEEP-02 remains source-blocked.",skillIds:["DEEP-02"],sourceRefs:["SLC-DEEP-SRP-OOP"]},
];
