export type PracticalConcept = {
  id: string;
  labelRu: string;
  labelEn: string;
  meaningRu: string;
  meaningEn: string;
  aliasesRu: string[];
  aliasesEn: string[];
};

const c = (concept: PracticalConcept): PracticalConcept => concept;

export const practicalConcepts: PracticalConcept[] = [
  c({ id: "RANGE", labelRu: "Диапазон", labelEn: "Range", meaningRu: "Набор рук, с которыми игрок может оказаться в этой точке решения.", meaningEn: "The set of hands a player can arrive at this decision point with.", aliasesRu: ["диапазон*", "range*"], aliasesEn: ["range*"] }),
  c({ id: "EQUITY", labelRu: "Эквити", labelEn: "Equity", meaningRu: "Средняя доля банка, которую рука получает против заданных рук соперника, если раздачу доиграть до конца.", meaningEn: "The average share of the pot a hand receives against specified opponent hands if the hand is played to completion.", aliasesRu: ["эквити", "equity"], aliasesEn: ["equity"] }),
  c({ id: "POT_ODDS", labelRu: "Pot odds / цена колла", labelEn: "Pot odds / call price", meaningRu: "Сколько нужно заплатить сейчас относительно итогового банка после колла.", meaningEn: "How much you must pay now relative to the final pot after calling.", aliasesRu: ["pot odds", "цена колла", "шансы банка"], aliasesEn: ["pot odds", "call price"] }),
  c({ id: "EQUITY_REALISATION", labelRu: "Реализация эквити", labelEn: "Equity realisation", meaningRu: "Какая часть потенциальной силы руки реально сохраняется через будущие решения, позицию и давление.", meaningEn: "How much of a hand's potential equity is actually preserved through future decisions, position, and pressure.", aliasesRu: ["реализац*", "реализуем* equity", "realis* equity", "equity reali*"], aliasesEn: ["equity reali*", "realis* equity", "reali*"] }),
  c({ id: "EV", labelRu: "EV", labelEn: "EV", meaningRu: "Средний денежный результат решения на дистанции; положительный EV означает, что решение в среднем зарабатывает.", meaningEn: "The average monetary result of a decision over time; positive EV means the decision earns on average.", aliasesRu: ["EV"], aliasesEn: ["EV"] }),
  c({ id: "POSITIONS", labelRu: "Позиции: EP/HJ/CO/BTN/SB/BB", labelEn: "Positions: EP/HJ/CO/BTN/SB/BB", meaningRu: "Сокращения мест за столом: ранняя позиция, hijack, cutoff, button, small blind и big blind.", meaningEn: "Table-position abbreviations: early position, hijack, cutoff, button, small blind, and big blind.", aliasesRu: ["EP", "HJ", "CO", "BTN", "SB", "BB", "UTG"], aliasesEn: ["EP", "HJ", "CO", "BTN", "SB", "BB", "UTG"] }),
  c({ id: "IP_OOP", labelRu: "IP / OOP", labelEn: "IP / OOP", meaningRu: "IP — в позиции, обычно действует после соперника постфлоп; OOP — вне позиции, обычно действует первым.", meaningEn: "IP means in position and usually acting after the opponent postflop; OOP means out of position and usually acting first.", aliasesRu: ["IP", "OOP", "в позиции", "вне позиции"], aliasesEn: ["IP", "OOP", "in position", "out of position"] }),
  c({ id: "RFI_OPEN", labelRu: "RFI / open", labelEn: "RFI / open", meaningRu: "RFI — первый добровольный рейз, когда до Hero все сфолдили; open — сам такой рейз.", meaningEn: "RFI is the first voluntary raise when everyone before Hero folded; an open is that raise.", aliasesRu: ["RFI", "first-in", "open*", "опен*", "открыт*"], aliasesEn: ["RFI", "first-in", "open*"] }),
  c({ id: "ACTION_ORDER", labelRu: "Игроки позади / закрытие торговли", labelEn: "Players behind / closing the action", meaningRu: "Если после Hero ещё кто-то действует, он может коллировать или повышать; если Hero закрывает торговлю, после его решения рейза позади уже нет.", meaningEn: "If players remain behind Hero they can still call or raise; when Hero closes the action, no player can raise behind.", aliasesRu: ["позади", "за спиной", "players behind", "closing action", "закрыва* торгов*"], aliasesEn: ["players behind", "player behind", "closing action", "closes the action"] }),
  c({ id: "RAKE", labelRu: "Рейк", labelEn: "Rake", meaningRu: "Комиссия рума из банка; она ухудшает EV особенно у тонких коллов и небольших банков.", meaningEn: "The room's fee taken from the pot; it hurts EV especially for thin calls and small pots.", aliasesRu: ["рейк", "rake"], aliasesEn: ["rake"] }),
  c({ id: "IMPLIED_ODDS", labelRu: "Implied odds", labelEn: "Implied odds", meaningRu: "Будущая возможная выплата, которая может оправдать текущий колл, если рука сильно улучшится.", meaningEn: "Potential future payoff that can justify a current call if the hand improves strongly.", aliasesRu: ["implied odds", "implied-odds", "имплайд"], aliasesEn: ["implied odds", "implied-odds"] }),
  c({ id: "REVERSE_IMPLIED_ODDS", labelRu: "Reverse implied odds", labelEn: "Reverse implied odds", meaningRu: "Риск дорого проиграть на будущих улицах, когда рука улучшится до сильной, но часто второй по силе комбинации.", meaningEn: "The risk of losing more money later when a hand improves to something strong but often second best.", aliasesRu: ["reverse implied odds", "reverse-implied", "обратные implied odds"], aliasesEn: ["reverse implied odds", "reverse-implied"] }),
  c({ id: "DOMINATION", labelRu: "Доминация", labelEn: "Domination", meaningRu: "Ситуация, где две руки часто попадают в похожую пару, но одна системно имеет более сильный кикер или старшую карту.", meaningEn: "A situation where two hands often make a similar pair but one systematically has the stronger kicker or high card.", aliasesRu: ["доминац*", "domination", "dominated"], aliasesEn: ["domination", "dominated"] }),
  c({ id: "BLOCKER", labelRu: "Блокер / removal", labelEn: "Blocker / removal", meaningRu: "Карта Hero уменьшает число комбинаций с этой картой у соперника; эффект зависит от того, какие руки важно убрать или оставить.", meaningEn: "A card in Hero's hand reduces opponent combinations containing that card; its value depends on which hands matter to remove or leave available.", aliasesRu: ["блокер", "блокеры", "blocker", "blockers", "removal", "card removal"], aliasesEn: ["blocker", "blockers", "removal", "card removal"] }),
  c({ id: "COMBOS", labelRu: "Комбо", labelEn: "Combos", meaningRu: "Конкретные комбинации двух карманных карт внутри диапазона.", meaningEn: "Specific two-card combinations inside a range.", aliasesRu: ["комбо", "combo", "combos"], aliasesEn: ["combo", "combos"] }),
  c({ id: "EFFECTIVE_STACK", labelRu: "Эффективный стек", labelEn: "Effective stack", meaningRu: "Меньший из двух релевантных стеков: больше этой суммы между этими игроками разыграть нельзя.", meaningEn: "The smaller of the two relevant stacks: those players cannot contest more than that amount.", aliasesRu: ["эффективный стек", "effective stack", "effective depth"], aliasesEn: ["effective stack", "effective depth"] }),
  c({ id: "SPR", labelRu: "SPR", labelEn: "SPR", meaningRu: "Отношение оставшегося эффективного стека к банку; ниже SPR — меньше пространства для будущих ставок.", meaningEn: "The remaining effective stack divided by the pot; lower SPR means less room for future betting.", aliasesRu: ["SPR", "stack-to-pot ratio"], aliasesEn: ["SPR", "stack-to-pot ratio"] }),
  c({ id: "BOARD_TEXTURE", labelRu: "Текстура доски", labelEn: "Board texture", meaningRu: "Свойства доски — высокая или низкая, связная, спаренная, одномастная и т.д. — которые меняют доступные сильные руки и дро.", meaningEn: "Board properties such as high/low, connected, paired, or monotone that change available strong hands and draws.", aliasesRu: ["текстур*", "board texture", "low connected", "paired board", "connected board"], aliasesEn: ["board texture", "low connected", "paired board", "connected board"] }),
  c({ id: "C_BET", labelRu: "C-bet", labelEn: "C-bet", meaningRu: "Ставка на флопе от игрока, который был последним агрессором префлоп.", meaningEn: "A flop bet by the player who was the last preflop aggressor.", aliasesRu: ["c-bet", "cbet", "контбет"], aliasesEn: ["c-bet", "cbet", "continuation bet"] }),
  c({ id: "RANGE_ADVANTAGE", labelRu: "Преимущество диапазона", labelEn: "Range advantage", meaningRu: "Один диапазон в среднем сильнее другого на этой доске, а не только одна конкретная рука Hero.", meaningEn: "One range is stronger on average than the other on this board, rather than only Hero's exact hand being strong.", aliasesRu: ["range advantage", "преимущество диапазона", "ownership", "board ownership"], aliasesEn: ["range advantage", "ownership", "board ownership"] }),
  c({ id: "NUT_ADVANTAGE", labelRu: "Nut advantage / натсовое преимущество", labelEn: "Nut advantage", meaningRu: "У одного игрока чаще есть самые сильные возможные комбинации на этой доске.", meaningEn: "One player has the strongest possible hands more often on this board.", aliasesRu: ["nut advantage", "nut strength", "nut potential", "натс*"], aliasesEn: ["nut advantage", "nut strength", "nut potential", "nutted"] }),
  c({ id: "CAPPED_RANGE", labelRu: "Капнутый диапазон", labelEn: "Capped range", meaningRu: "Диапазон, из которого предыдущие действия убрали значительную часть самых сильных комбинаций; uncapped означает, что сильный верх всё ещё реалистичен.", meaningEn: "A range whose prior actions removed much of its strongest region; uncapped means the strong top end is still realistic.", aliasesRu: ["capped", "uncapped", "капнут*", "некапнут*"], aliasesEn: ["capped", "uncapped", "range cap"] }),
  c({ id: "RANGE_SHAPE", labelRu: "Linear / polar / merged", labelEn: "Linear / polar / merged", meaningRu: "Форма диапазона: linear чаще идёт от сильнейших рук вниз; polar сочетает сильное вэлью и отдельные блефы; merged содержит больше средне-сильных рук.", meaningEn: "Range shape: linear usually runs down from the strongest hands; polar combines strong value with separate bluffs; merged contains more medium-strong hands.", aliasesRu: ["linear", "polar", "merged", "линей", "поляр", "мердж"], aliasesEn: ["linear", "polar", "merged"] }),
  c({ id: "FOLD_EQUITY", labelRu: "Fold equity", labelEn: "Fold equity", meaningRu: "Часть EV агрессии, которая появляется потому, что соперник иногда фолдит.", meaningEn: "The part of aggressive EV created because the opponent sometimes folds.", aliasesRu: ["fold equity", "фолд-эквити"], aliasesEn: ["fold equity"] }),
  c({ id: "SQUEEZE", labelRu: "Сквиз", labelEn: "Squeeze", meaningRu: "Ререйз после того, как один игрок открылся, а один или несколько игроков заколлировали.", meaningEn: "A re-raise after one player opens and one or more players call.", aliasesRu: ["squeez*", "сквиз*"], aliasesEn: ["squeez*"] }),
  c({ id: "THREE_FOUR_BET", labelRu: "3-bet / 4-bet", labelEn: "3-bet / 4-bet", meaningRu: "3-bet — первое повышение поверх открытия; 4-bet — следующее повышение поверх 3-bet.", meaningEn: "A 3-bet is the first re-raise over an open; a 4-bet is the next raise over the 3-bet.", aliasesRu: ["3-bet*", "4-bet*", "3bet*", "4bet*", "3-бет*", "4-бет*"], aliasesEn: ["3-bet*", "4-bet*", "3bet*", "4bet*"] }),
  c({ id: "POT_TYPES", labelRu: "SRP / 3BP / 4BP", labelEn: "SRP / 3BP / 4BP", meaningRu: "SRP — банк после одного префлоп-рейза; 3BP и 4BP — банки, где был 3-bet или 4-bet.", meaningEn: "SRP is a single-raised pot; 3BP and 4BP are pots that contained a 3-bet or 4-bet.", aliasesRu: ["SRP", "3BP", "4BP", "single-raised pot*", "3-bet pot*", "4-bet pot*", "3-бет-пот*", "4-бет-пот*"], aliasesEn: ["SRP", "3BP", "4BP", "single-raised pot*", "3-bet pot*", "4-bet pot*"] }),
  c({ id: "RUNOUT", labelRu: "Runout / новая карта", labelEn: "Runout", meaningRu: "Карты тёрна и ривера и то, как они меняют возможные сильные руки, дро и преимущество диапазонов.", meaningEn: "Turn and river cards and how they change strong hands, draws, and range advantages.", aliasesRu: ["runout*", "blank", "scare", "draw-completing", "range-shifting", "бланк*"], aliasesEn: ["runout*", "blank", "scare card", "draw-completing", "range-shifting"] }),
  c({ id: "BARREL", labelRu: "Barrel", labelEn: "Barrel", meaningRu: "Продолжение агрессии ставкой на следующей улице после предыдущей ставки.", meaningEn: "Continuing aggression with another bet on a later street after betting before.", aliasesRu: ["barrel*", "баррел*"], aliasesEn: ["barrel*"] }),
  c({ id: "PROBE_LEAD", labelRu: "Probe / lead", labelEn: "Probe / lead", meaningRu: "Probe — ставка после того, как предыдущий агрессор прочекал; lead — ставка OOP в игрока, который ранее сохранял инициативу.", meaningEn: "A probe is a bet after the prior aggressor checks back; a lead is an OOP bet into a player who previously held the initiative.", aliasesRu: ["probe*", "turn probe*", "lead*", "лид*"], aliasesEn: ["probe*", "turn probe*", "lead*"] }),
  c({ id: "THIN_VALUE", labelRu: "Thin value", labelEn: "Thin value", meaningRu: "Тонкая ставка на вэлью: Hero ожидает получить достаточно коллов от немного худших рук, хотя преимущество небольшое.", meaningEn: "A thin value bet expects enough calls from slightly worse hands even though the edge is small.", aliasesRu: ["thin value", "тонк* вэлью", "value target*"], aliasesEn: ["thin value", "value target*"] }),
  c({ id: "SHOWDOWN", labelRu: "Showdown value", labelEn: "Showdown value", meaningRu: "Ценность руки, если больше не вкладывать деньги и дойти до вскрытия.", meaningEn: "A hand's value if no more money goes in and it reaches showdown.", aliasesRu: ["showdown", "шоудаун"], aliasesEn: ["showdown"] }),
  c({ id: "LEVERAGE", labelRu: "Леверидж", labelEn: "Leverage", meaningRu: "Давление, которое создаёт угроза будущих крупных ставок относительно оставшегося стека.", meaningEn: "Pressure created by the threat of future large bets relative to the remaining stack.", aliasesRu: ["leverage", "леверидж*"], aliasesEn: ["leverage"] }),
  c({ id: "STACK_OFF", labelRu: "Stack-off / commitment", labelEn: "Stack-off / commitment", meaningRu: "Насколько охотно линия ведёт к вложению всего эффективного стека; это не автоматическое действие только из-за силы одной пары.", meaningEn: "How readily a line commits the full effective stack; it is not automatic from a one-pair hand label.", aliasesRu: ["stack-off*", "commitment", "overcommit*", "коммит*"], aliasesEn: ["stack-off*", "commitment", "overcommit*"] }),
  c({ id: "OVERBET", labelRu: "Overbet", labelEn: "Overbet", meaningRu: "Ставка больше текущего банка; обычно требует подходящей структуры сильных рук и блефов.", meaningEn: "A bet larger than the current pot; it usually requires an appropriate structure of strong hands and bluffs.", aliasesRu: ["overbet", "овербет"], aliasesEn: ["overbet"] }),
  c({ id: "BLUFF_CATCH", labelRu: "Bluff-catch", labelEn: "Bluff-catch", meaningRu: "Колл рукой, которая обычно проигрывает вэлью соперника и выигрывает в основном против его блефов.", meaningEn: "A call with a hand that usually loses to the opponent's value and wins mainly against bluffs.", aliasesRu: ["bluff catch*", "bluff-catch*", "блеф-кетч*"], aliasesEn: ["bluff catch*", "bluff-catch*"] }),
  c({ id: "BLUFF_FREQUENCY", labelRu: "Underbluff / overbluff", labelEn: "Underbluff / overbluff", meaningRu: "Underbluff — блефов меньше, чем нужно для базовой защиты; overbluff — больше.", meaningEn: "Underbluff means fewer bluffs than the baseline defense expects; overbluff means more.", aliasesRu: ["underbluff*", "overbluff*", "андерблеф*", "оверблеф*"], aliasesEn: ["underbluff*", "overbluff*"] }),
  c({ id: "MULTIWAY", labelRu: "Мультивей", labelEn: "Multiway", meaningRu: "Банк с тремя и более игроками, где одновременно взаимодействуют несколько диапазонов.", meaningEn: "A pot with three or more players, where several ranges interact at the same time.", aliasesRu: ["multiway", "мультивей", "троих и более"], aliasesEn: ["multiway", "three or more players"] }),
  c({ id: "STRADDLE", labelRu: "Страддл", labelEn: "Straddle", meaningRu: "Дополнительная обязательная ставка до раздачи, которая меняет рабочую единицу ставок, порядок действий и эффективную глубину.", meaningEn: "An extra forced preflop bet that changes the working betting unit, action order, and effective depth.", aliasesRu: ["straddle*", "страддл*"], aliasesEn: ["straddle*"] }),
  c({ id: "ISO_OVERLIMP", labelRu: "Iso / overlimp", labelEn: "Isolation / overlimp", meaningRu: "Iso — рейз против лимпера, чтобы сузить число соперников; overlimp — колл лимпа вместо рейза.", meaningEn: "Isolation is a raise over a limper to narrow the field; overlimp is calling the limp instead of raising.", aliasesRu: ["isolation", "isolate", "iso", "overlimp", "изолейт", "оверлимп"], aliasesEn: ["isolation", "isolate", "iso", "overlimp"] }),
  c({ id: "DRAW_OUTS", labelRu: "Дро / ауты", labelEn: "Draws / outs", meaningRu: "Дро — незавершённая рука с путями усиления; аут — карта, которая может улучшить её. Не каждый визуальный аут обязательно чистый.", meaningEn: "A draw is an incomplete hand with improvement routes; an out is a card that can improve it. Not every apparent out is necessarily clean.", aliasesRu: ["дро", "аут*", "outs", "draw*", "backdoor*", "бэкдор*"], aliasesEn: ["outs", "draw*", "backdoor*"] }),
  c({ id: "DEAD_MONEY", labelRu: "Dead money", labelEn: "Dead money", meaningRu: "Деньги уже в банке от игроков, которые могут сфолдить и больше не претендуют на него.", meaningEn: "Money already in the pot from players who may fold and no longer contest it.", aliasesRu: ["dead money"], aliasesEn: ["dead money"] }),
  c({ id: "DECISION_BRANCH", labelRu: "Ветка решения", labelEn: "Decision branch", meaningRu: "Один возможный путь после действия: например call-ветка, raise-ветка или будущая последовательность ставок.", meaningEn: "One possible path after an action, such as the call branch, raise branch, or a future betting sequence.", aliasesRu: ["branch*", "future tree", "дерево решений", "ветк*"], aliasesEn: ["branch*", "future tree", "decision tree"] }),
  c({ id: "HAND_FAMILY", labelRu: "Семейство рук", labelEn: "Hand family", meaningRu: "Структурный тип руки — например карманная пара, suited connector, Broadway или мастевой туз — а не готовое действие.", meaningEn: "A structural hand type such as a pocket pair, suited connector, Broadway hand, or suited ace, not a prescribed action.", aliasesRu: ["hand family", "hand families", "семейство", "suited connector", "broadway", "карманная пара"], aliasesEn: ["hand family", "hand families", "suited connector", "Broadway", "pocket pair"] }),
  c({ id: "GAME_SELECTION", labelRu: "Game / seat selection", labelEn: "Game / seat selection", meaningRu: "Выбор стола и места, чтобы чаще играть против подходящих соперников и в выгодной относительной позиции.", meaningEn: "Choosing a table and seat to play more often against suitable opponents and in favorable relative position.", aliasesRu: ["game selection", "seat selection", "выбор стола", "выбор места"], aliasesEn: ["game selection", "seat selection"] }),
];

function normalize(value: string): string {
  return value.toLocaleLowerCase("ru-RU").replaceAll("ё", "е");
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^$()|[\]\\{}]/g, "\\$&");
}

function aliasAppears(text: string, alias: string): boolean {
  const normalizedText = normalize(text);
  const normalizedAlias = normalize(alias);
  const prefixMatch = normalizedAlias.endsWith("*");
  const literalAlias = prefixMatch ? normalizedAlias.slice(0, -1) : normalizedAlias;
  const escaped = escapeRegExp(literalAlias);
  const startsWord = /^[\p{L}\p{N}]/u.test(literalAlias);
  const endsWord = /[\p{L}\p{N}]$/u.test(literalAlias);
  const prefix = startsWord ? "(^|[^\\p{L}\\p{N}])" : "";
  const suffix = endsWord && !prefixMatch ? "($|[^\\p{L}\\p{N}])" : "";
  return new RegExp(prefix + escaped + suffix, "iu").test(normalizedText);
}

export function practicalConceptsForTexts(locale: "ru" | "en", texts: Array<string | null | undefined>): PracticalConcept[] {
  const joined = texts.filter((value): value is string => Boolean(value?.trim())).join("\n");
  if (!joined) return [];
  return practicalConcepts.filter((concept) => {
    const aliases = locale === "ru" ? concept.aliasesRu : concept.aliasesEn;
    return aliases.some((alias) => aliasAppears(joined, alias));
  });
}

export function practicalConceptIdsForTexts(locale: "ru" | "en", texts: Array<string | null | undefined>): string[] {
  return practicalConceptsForTexts(locale, texts).map((concept) => concept.id);
}
