export const practicalObjectiveEnById = {
  "FND-01": "Connect the call price to required equity.",
  "FND-02": "Distinguish raw equity from equity that can actually be realized.",
  "FND-03": "Recognize future value and domination risk.",
  "FND-04": "Do not treat every improving card as a clean out.",
  "FND-05": "Count combinations and card removal in the actual line.",
  "FND-06": "Quickly determine the effective stack and post-action SPR.",
  "FND-07": "Connect risk/reward to the break-even threshold without false solver precision.",
  "PF-01": "Make open/fold decisions from position and context.",
  "PF-02": "Choose iso/overlimp/fold in live limp-heavy branches.",
  "PF-03": "Evaluate flats through domination, implied odds, and squeeze exposure.",
  "PF-04": "Use price, closing action, and realization instead of a fixed fold/call rule.",
  "PF-05": "Account for poor realization and the BB behind.",
  "PF-06": "Choose linear, polar, or merged shape from fold equity and the called branch.",
  "PF-07": "Split fold/call/4-bet branches by position, sizing, and hand family.",
  "PF-08": "Understand value, bluff, blocker, and stack consequences without copying charts.",
  "PF-09": "Evaluate dead money, fold targets, position, and the called branch.",
  "PF-10": "Adjust the preflop branch for large opens, depth, rake, and a weak caller pool.",
  "BL-01": "Defend the BB against stronger origin ranges.",
  "BL-02": "Recognize the wider late-position branch.",
  "BL-03": "Execute the high-frequency blind-defense family against BTN.",
  "BL-04": "Adjust defense with price and do not carry one frequency across sizings.",
  "BL-05": "Account for poor position and the BB behind.",
  "BL-06": "Recognize raise/limp/fold structure where the source supports the branch.",
  "BL-07": "Play wide-range blind-vs-blind defense.",
  "BL-08": "Distinguish check/raise branches against an SB limp.",
  "BL-09": "Continue the BvB tree after raise/3-bet rather than learning only the first action.",
  "BL-10": "Play postflop with very wide starting ranges.",
  "BL-11": "Carry blind-range width into 3-bet-pot postflop play.",
  "BL-12": "Adjust defense and 3-bet incentives as depth and rake change.",
  "W4-BOARD-01": "Quickly classify the main flop textures.",
  "W4-RUNOUT-01": "Recognize blank, scare, draw-completing, and range-shifting cards.",
  "W4-HAND-01": "Move from the exact combo to its relative hand family.",
  "W4-DRAW-01": "Distinguish nut, weak, combo, and pair+draw families and their domination risk.",
  "W4-REL-01": "Evaluate the hand relative to range and board, not by its absolute hand name.",
  "OOP-01": "Know when a range-check simplification protects the OOP tree.",
  "OOP-02": "Split continue/fold classes by size, board, and realization.",
  "OOP-03": "Build value/bluff raise candidates from urgency and range shape.",
  "OOP-04": "Do not automatically overfold to a small sizing.",
  "OOP-05": "Narrow continues and demand more realization against large sizing.",
  "OOP-06": "Recognize source-supported lead opportunities after a flop call.",
  "OOP-07": "Choose block/check-call/check-fold through range ancestry and price.",
  "IP-01": "Choose a simplified range-bet or selective strategy from board/range interaction.",
  "IP-02": "Preserve protected check-backs and use delayed aggression.",
  "IP-03": "Choose turn barrels by card class and range shift.",
  "IP-04": "Increase pressure only when action history genuinely caps the range.",
  "IP-05": "Use overbet logic only with source-supported nut/range asymmetry.",
  "IP-06": "Extract value from worse calls without turning marginal showdown value into an auto-bet.",
  "3BP-01": "Play 3-bet pots as the IP aggressor across board and sizing branches.",
  "3BP-02": "Do not copy the IP c-bet plan onto the OOP tree.",
  "3BP-03": "Execute continue/attack branches as the IP caller.",
  "3BP-04": "Defend the OOP caller range without overfold/overraise simplifications.",
  "3BP-05": "Transfer the four role trees across high, paired, and low-connected boards.",
  "4BP-01": "Understand low SPR and the compressed postflop tree.",
  "4BP-02": "Play AK/QQ/JJ/blocker families without a one-size-fits-all stack-off rule.",
  "4BP-03": "Preserve a checking range even in compressed pots where the source supports it.",
  "4BP-04": "Account for reopen/jam exposure and the investment ceiling before betting or raising.",
  "TURN-01": "Classify turns as blank, scare, completing, paired, or range-shifting.",
  "TURN-02": "Continue aggression only with suitable value/bluff classes.",
  "TURN-03": "Attack checked-back ranges where they are genuinely capped or overwide.",
  "TURN-04": "Lead after a flop call only on source-supported runouts.",
  "TURN-05": "Distinguish second/third-street value from showdown preservation.",
  "RIV-01": "Name the worse hands that actually pay the chosen sizing.",
  "RIV-02": "Choose bluffs by showdown value, blockers/unblockers, and ancestry.",
  "RIV-03": "Connect price to credible bluff supply and removal.",
  "RIV-04": "Recognize small river lines and their exploit consequences.",
  "RIV-05": "Make fold/call deviations only after branch-specific evidence.",
  "MW-01": "Track who acts behind and closing action in multiway trees.",
  "MW-02": "Raise value and nut-potential requirements against multiple ranges.",
  "MW-03": "Do not carry heads-up bluff frequencies into multiway pots.",
  "MW-04": "Choose iso/overlimp/fold against live limpers.",
  "MW-05": "Tighten bluff/value assumptions on the river with multiple ranges.",
  "DEEP-01": "Adjust nut potential, leverage, and stack-off thresholds by depth.",
  "DEEP-02": "Avoid one-pair overcommitment and value nut potential in very deep branches.",
  "DEEP-03": "Recalculate the forced unit, effective position, and SPR under a straddle.",
  "DEEP-04": "Adjust calls, 3-bets, and 4-bets as implied and reverse implied odds grow.",
  "EXP-01": "Separate an observation from a stable read and branch-specific evidence.",
  "EXP-02": "Widen value against evidenced overcall or sticky tendencies.",
  "EXP-03": "Increase or reduce bluffing against overfold/underfold evidence.",
  "EXP-04": "Adjust the call-down threshold against overbluff/underbluff evidence.",
  "EXP-05": "Respond to repeatable sizing/line tendencies without universalizing them.",
  "EXP-06": "Maximize hourly EV through table and seat quality without confusing it with hand EV.",
  "INT-01": "Choose the correct mechanism without a topic cue.",
  "INT-02": "Change the decision when one material variable changes and explain the causal shift.",
  "INT-03": "Route an error to the skill family, not only the exact drill.",
  "INT-04": "Test retained skill on topic-hidden, non-identical items.",
  "INT-05": "Link a real error to the relevant skill family and assign targeted repair.",
} as const;
