import type { PracticalDecision } from "./types";

export type PerceptualSeat = {
  position: "UTG" | "HJ" | "CO" | "BTN" | "SB" | "BB";
  stackBb: number;
  status?: "folded" | "active" | "hero";
};

export type PracticalTableState = {
  decisionId: string;
  scaffold: "guided" | "reduced" | "hidden";
  stakes: string;
  hero: PerceptualSeat["position"];
  dealer: PerceptualSeat["position"];
  seats: PerceptualSeat[];
  heroCards?: [string,string];
  board?: string[];
  potBb?: number;
  straddle?: { position: PerceptualSeat["position"]; amountBb: number };
  actions: string[];
  irrelevantCues?: string[];
  revealCueRu: string;
  revealCueEn: string;
};

const o=(id:string,textRu:string,textEn:string,misconception?:string)=>({id,textRu,textEn,misconception});

function d(input:{id:string;skillId:string;kind:"recognition"|"changed";sourceRefs:string[];questionRu:string;questionEn:string;goodRu:string;goodEn:string;whyRu:string;whyEn:string;bad1Ru:string;bad1En:string;bad2Ru:string;bad2En:string;changedVariables?:string[]}):PracticalDecision{
  const slot=Number(input.id.slice(-1))%3;
  const good=o("good",input.goodRu,input.goodEn);
  const bad1=o("bad1",input.bad1Ru,input.bad1En,"PERCEPTUAL_SHORTCUT");
  const bad2=o("bad2",input.bad2Ru,input.bad2En,"IRRELEVANT_CUE");
  const goodR=o("goodR",input.whyRu,input.whyEn);
  const badR1=o("badR1","Выбрать по названию руки без node context","Choose from hand label without node context","HAND_LABEL_ONLY");
  const badR2=o("badR2","Выбрать самый заметный визуальный объект","Choose the most visually salient object","SALIENCE_BIAS");
  return {
    id:input.id,skillId:input.skillId,kind:input.kind,sourceRefs:input.sourceRefs,
    assumptions:["B2 table-state stimulus; topic hidden before answer; visual metadata is part of the prompt"],
    cueRu:"Сначала прочитай стол. Тема намеренно скрыта.",cueEn:"Read the table first. The topic is intentionally hidden.",
    questionRu:input.questionRu,questionEn:input.questionEn,
    actionOptions:slot===0?[good,bad1,bad2]:slot===1?[bad1,good,bad2]:[bad1,bad2,good],
    reasonOptions:slot===0?[badR1,goodR,badR2]:slot===1?[goodR,badR1,badR2]:[badR1,badR2,goodR],
    correctActionId:"good",correctReasonId:"goodR",targetSeconds:18,
    explanationRu:input.whyRu,explanationEn:input.whyEn,changedVariables:input.changedVariables,
  };
}

const decisions:PracticalDecision[]=[
  d({id:"PM-PERC-FND06-1",skillId:"FND-06",kind:"recognition",sourceRefs:["LCM-01"],questionRu:"Что первым меняет реальную глубину этой руки?",questionEn:"What first changes the real depth of this hand?",goodRu:"Самый короткий stack в конкретной паре + размер уже созданного pot",goodEn:"The shorter stack in the relevant pair plus the pot already created",whyRu:"Effective stack и post-action SPR задаются участниками конкретной ветки, а не самым большим stack на столе.",whyEn:"Effective stack and post-action SPR are set by the players in the actual branch, not the largest stack at the table.",bad1Ru:"Самый большой stack за столом",bad1En:"The largest stack at the table",bad2Ru:"Количество фишек у dealer",bad2En:"The dealer's chip count"}),
  d({id:"PM-PERC-FND06-2",skillId:"FND-06",kind:"changed",sourceRefs:["LCM-01"],questionRu:"Что изменилось после того, как effective opponent стал короче?",questionEn:"What changed after the effective opponent became shorter?",goodRu:"Future SPR сжался; часть deep-stack планов теряет смысл",goodEn:"Future SPR compressed; some deep-stack plans lose relevance",whyRu:"Physical chips Hero не определяют leverage, если opponent не может покрыть их.",whyEn:"Hero's physical chips do not determine leverage when the opponent cannot cover them.",bad1Ru:"Ничего — Hero всё ещё deep",bad1En:"Nothing — Hero is still deep",bad2Ru:"Только цвет фишек",bad2En:"Only the chip color",changedVariables:["effective_stack"]}),

  d({id:"PM-PERC-BL03-1",skillId:"BL-03",kind:"recognition",sourceRefs:["FTGU-E05","SLC-BB-VS-BTN"],questionRu:"Какой node ты должен распознать до оценки hand strength?",questionEn:"Which node should you recognize before evaluating hand strength?",goodRu:"BB закрывает action против wide BTN open",goodEn:"BB closes the action versus a wide BTN open",whyRu:"BTN origin range, BB discount и closing action совместно двигают marginal defence.",whyEn:"BTN origin range, BB discount and closing action jointly move marginal defense.",bad1Ru:"Просто OOP против raise",bad1En:"Simply OOP versus a raise",bad2Ru:"BTN имеет большой stack, значит fold",bad2En:"BTN has a big stack, so fold"}),
  d({id:"PM-PERC-BL03-2",skillId:"BL-03",kind:"changed",sourceRefs:["FTGU-E05","SLC-BB-VS-BTN"],questionRu:"При той же руке BTN open стал заметно больше. Что с fringe defence?",questionEn:"With the same hand, BTN's open became much larger. What happens to fringe defense?",goodRu:"Сужается из-за худшей цены и более дорогой реализации",goodEn:"It narrows because of the worse price and costlier realization",whyRu:"Больший open ухудшает immediate price; одна и та же hand family не сохраняет прежний threshold.",whyEn:"A larger open worsens the immediate price; the same hand family does not keep the old threshold.",bad1Ru:"Не меняется — позиция та же",bad1En:"No change — positions are the same",bad2Ru:"Становится шире, потому что pot больше",bad2En:"It widens because the pot is bigger",changedVariables:["open_size"]}),

  d({id:"PM-PERC-BL04-1",skillId:"BL-04",kind:"recognition",sourceRefs:["FTGU-E05"],questionRu:"Какой визуальный cue здесь важнее cards Hero?",questionEn:"Which visual cue matters more here than Hero's exact cards?",goodRu:"Open size относительно blind/pot",goodEn:"Open size relative to the blind/pot",whyRu:"BB defence threshold materially shifts with price; sizing must be noticed before importing a memorized response.",whyEn:"BB defense thresholds materially shift with price; sizing must be noticed before importing a memorized response.",bad1Ru:"Dealer button color",bad1En:"Dealer button color",bad2Ru:"Самый высокий stack",bad2En:"The tallest stack"}),
  d({id:"PM-PERC-BL04-2",skillId:"BL-04",kind:"changed",sourceRefs:["FTGU-E05"],questionRu:"Что является единственной material change между двумя snapshots?",questionEn:"What is the only material change between the two snapshots?",goodRu:"Цена входа: 2.5bb → 4bb",goodEn:"Entry price: 2.5bb → 4bb",whyRu:"One-variable transformation должна связывать изменение размера open с изменением defence, а не с новым hand label.",whyEn:"A one-variable transformation should link the open-size change to the defense change, not to a new hand label.",bad1Ru:"Hero position",bad1En:"Hero position",bad2Ru:"Board texture",bad2En:"Board texture",changedVariables:["open_size"]}),

  d({id:"PM-PERC-BOARD-1",skillId:"W4-BOARD-01",kind:"recognition",sourceRefs:["FTGU-E07","SLC-SRP-BOARD-CLASSES"],questionRu:"Как классифицировать flop для решения, а не для словаря?",questionEn:"How should the flop be classified for a decision rather than a glossary?",goodRu:"Board × arriving ranges: кто сохраняет range/nut advantage",goodEn:"Board × arriving ranges: who retains range/nut advantage",whyRu:"Одинаковая texture может требовать другой strategy при других preflop ranges.",whyEn:"The same texture can require a different strategy with different preflop ranges.",bad1Ru:"Только 'dry A-high'",bad1En:"Only 'dry A-high'",bad2Ru:"По масти dealer button",bad2En:"By the dealer button color"}),
  d({id:"PM-PERC-BOARD-2",skillId:"W4-BOARD-01",kind:"changed",sourceRefs:["FTGU-E07"],questionRu:"Board тот же, но arriving ranges изменились. Можно ли оставить прежний c-bet family?",questionEn:"The board is the same, but arriving ranges changed. Can the old c-bet family be kept?",goodRu:"Нет — заново оценить ownership через новые ranges",goodEn:"No — reassess ownership through the new ranges",whyRu:"Board label не является action key; preflop ancestry определяет, кто реально имеет strong/nutted regions.",whyEn:"A board label is not an action key; preflop ancestry determines who actually has strong/nutted regions.",bad1Ru:"Да — board полностью определяет strategy",bad1En:"Yes — the board fully determines strategy",bad2Ru:"Да — pot size одинаков",bad2En:"Yes — the pot size is unchanged",changedVariables:["arriving_ranges"]}),

  d({id:"PM-PERC-RUNOUT-1",skillId:"W4-RUNOUT-01",kind:"recognition",sourceRefs:["FTGU-E20","FTGU-E21"],questionRu:"Что нужно восстановить перед ярлыком 'blank/scare'?",questionEn:"What must be reconstructed before using a 'blank/scare' label?",goodRu:"Flop action и surviving strong regions",goodEn:"Flop action and surviving strong regions",whyRu:"Turn meaning зависит от того, какие руки check/bet/call уже отфильтровали.",whyEn:"Turn meaning depends on which hands were filtered by the prior check/bet/call line.",bad1Ru:"Только rank turn card",bad1En:"Only the turn card rank",bad2Ru:"Количество игроков за соседним столом",bad2En:"The number of players at the next table"}),
  d({id:"PM-PERC-RUNOUT-2",skillId:"W4-RUNOUT-01",kind:"changed",sourceRefs:["FTGU-E20","FTGU-E21"],questionRu:"Same turn card, но flop action изменился bet-call → check-back. Что меняется?",questionEn:"Same turn card, but flop action changed from bet-call → check-back. What changes?",goodRu:"Range caps/surviving regions; turn может получить другой strategic meaning",goodEn:"Range caps/surviving regions; the turn can get a different strategic meaning",whyRu:"Ancestry является частью state; одна карта не имеет универсального класса вне линии.",whyEn:"Ancestry is part of the state; a card has no universal class outside the line.",bad1Ru:"Ничего — card та же",bad1En:"Nothing — the card is the same",bad2Ru:"Меняется только размер шрифта",bad2En:"Only the font size changes",changedVariables:["flop_action"]}),

  d({id:"PM-PERC-3BP05-1",skillId:"3BP-05",kind:"recognition",sourceRefs:["FTGU-E28","FTGU-E29"],questionRu:"Какие три оси нужно извлечь из snapshot до c-bet default?",questionEn:"Which three axes must be extracted before choosing a c-bet default?",goodRu:"Role/position × board interaction × sizing/SPR",goodEn:"Role/position × board interaction × sizing/SPR",whyRu:"3BP не одна strategy class: aggressor/caller и IP/OOP меняют execution даже на похожих boards.",whyEn:"A 3BP is not one strategy class: aggressor/caller and IP/OOP change execution even on similar boards.",bad1Ru:"Только '3-bet pot'",bad1En:"Only '3-bet pot'",bad2Ru:"Только absolute hand rank",bad2En:"Only absolute hand rank"}),
  d({id:"PM-PERC-3BP05-2",skillId:"3BP-05",kind:"changed",sourceRefs:["FTGU-E28","FTGU-E29"],questionRu:"Board и ranges те же, Hero из IP aggressor стал OOP aggressor. Можно копировать line?",questionEn:"Board and ranges are similar, but Hero changed from IP aggressor to OOP aggressor. Can the line be copied?",goodRu:"Нет — position меняет check/bet incentives и realisation",goodEn:"No — position changes check/bet incentives and realization",whyRu:"Role/position является first-order variable в 3BP matrix.",whyEn:"Role/position is a first-order variable in the 3BP matrix.",bad1Ru:"Да — initiative важнее position",bad1En:"Yes — initiative matters more than position",bad2Ru:"Да — pot одинаков",bad2En:"Yes — the pot is the same",changedVariables:["position_role"]}),

  d({id:"PM-PERC-MW01-1",skillId:"MW-01",kind:"recognition",sourceRefs:["SLC-MULTIWAY","EXT-PS-MULTIWAY-2026"],questionRu:"Hero сидит между bettor и двумя active players. Какой cue главный?",questionEn:"Hero is between the bettor and two active players. Which cue is primary?",goodRu:"Relative position: кто ещё действует после Hero",goodEn:"Relative position: who still acts after Hero",whyRu:"Multiway decision зависит от ranges behind; абсолютная IP/OOP метка недостаточна.",whyEn:"A multiway decision depends on ranges behind; an absolute IP/OOP label is insufficient.",bad1Ru:"Hero ближе к dealer, значит IP",bad1En:"Hero is closer to the dealer, so IP",bad2Ru:"Самый большой stack всегда главный",bad2En:"The biggest stack is always primary"}),
  d({id:"PM-PERC-MW01-2",skillId:"MW-01",kind:"changed",sourceRefs:["SLC-MULTIWAY"],questionRu:"Cards/action те же, но Hero теперь закрывает action. Что изменилось?",questionEn:"Cards/action are the same, but Hero now closes the action. What changed?",goodRu:"Нет риска squeeze/raise behind; marginal continue может реализоваться лучше",goodEn:"There is no squeeze/raise risk behind; a marginal continue can realize better",whyRu:"Closing action устраняет целую future branch и повышает realisation relative to a sandwiched seat.",whyEn:"Closing the action removes an entire future branch and improves realization relative to a sandwiched seat.",bad1Ru:"Ничего — hand та же",bad1En:"Nothing — the hand is the same",bad2Ru:"Только dealer moved",bad2En:"Only the dealer moved",changedVariables:["relative_position"]}),

  d({id:"PM-PERC-DEEP03-1",skillId:"DEEP-03",kind:"recognition",sourceRefs:["LCM-01","SLC-PREFLOP-ADJUSTMENTS"],questionRu:"Что нужно пересчитать сразу после появления straddle?",questionEn:"What should be recomputed immediately after a straddle appears?",goodRu:"Working blind unit, action order, effective depth и SPR",goodEn:"Working blind unit, action order, effective depth and SPR",whyRu:"Straddle меняет denominator и порядок действий; физические 300bb могут стать существенно менее deep в рабочих units.",whyEn:"A straddle changes the denominator and action order; a physical 300bb stack can become much less deep in working units.",bad1Ru:"Ничего — stacks физически те же",bad1En:"Nothing — physical stacks are unchanged",bad2Ru:"Только pot display",bad2En:"Only the pot display"}),
  d({id:"PM-PERC-DEEP03-2",skillId:"DEEP-03",kind:"changed",sourceRefs:["LCM-01"],questionRu:"Same chips, но straddle убран. Что произошло с strategic depth?",questionEn:"Same chips, but the straddle was removed. What happened to strategic depth?",goodRu:"Она выросла в рабочих blind units; future SPR/leverage расширились",goodEn:"It increased in working blind units; future SPR/leverage expanded",whyRu:"Depth должна измеряться относительно forced unit и pot geometry, а не только номинальных chips.",whyEn:"Depth should be measured relative to the forced unit and pot geometry, not only nominal chips.",bad1Ru:"Не изменилась",bad1En:"It did not change",bad2Ru:"Стала короче",bad2En:"It became shallower",changedVariables:["straddle"]}),

  d({id:"PM-PERC-RIV03-1",skillId:"RIV-03",kind:"recognition",sourceRefs:["FTGU-E22","CINJ-E02"],questionRu:"Перед river call какой невидимый объект нужно восстановить из action history?",questionEn:"Before a river call, which invisible object must be reconstructed from the action history?",goodRu:"Credible bluff supply versus value range",goodEn:"Credible bluff supply versus the value range",whyRu:"Price не создаёт bluffs; bluff-catch EV зависит от того, какие missed/converted bluffs реально дошли до river.",whyEn:"Price does not manufacture bluffs; bluff-catch EV depends on which missed/converted bluffs actually reach the river.",bad1Ru:"Только pot odds",bad1En:"Only pot odds",bad2Ru:"Размер Hero stack after call",bad2En:"Hero's stack after the call"}),
  d({id:"PM-PERC-RIV03-2",skillId:"RIV-03",kind:"changed",sourceRefs:["FTGU-E22"],questionRu:"Price и Hero hand те же, но turn action удалил большинство natural bluffs. Что с call?",questionEn:"Price and Hero hand are the same, but turn action removed most natural bluffs. What happens to the call?",goodRu:"Становится хуже; threshold может перестать выполняться",goodEn:"It becomes worse; the threshold may no longer be met",whyRu:"Ancestry меняет bluff supply при неизменной цене.",whyEn:"Ancestry changes bluff supply even when the price is unchanged.",bad1Ru:"Не меняется из-за той же цены",bad1En:"No change because the price is the same",bad2Ru:"Становится лучше автоматически",bad2En:"It automatically improves",changedVariables:["bluff_supply"]}),

  d({id:"PM-PERC-EXP01-1",skillId:"EXP-01",kind:"recognition",sourceRefs:["LCM-10"],questionRu:"Что из snapshot является evidence, а что только salience?",questionEn:"What in the snapshot is evidence rather than mere salience?",goodRu:"Повторяемая line/size tendency в том же branch",goodEn:"A repeatable line/size tendency in the same branch",whyRu:"Один яркий showdown не превращается в стабильный player type; evidence должен быть scoped и updateable.",whyEn:"One vivid showdown does not become a stable player type; evidence must be scoped and updateable.",bad1Ru:"Один огромный bluff = maniac навсегда",bad1En:"One huge bluff = maniac forever",bad2Ru:"Большой stack = сильный игрок",bad2En:"Big stack = strong player"}),
  d({id:"PM-PERC-EXP01-2",skillId:"EXP-01",kind:"changed",sourceRefs:["LCM-10"],questionRu:"Same player, но new evidence contradicts прежний read в том же branch. Что делать?",questionEn:"Same player, but new evidence contradicts the old read in the same branch. What should happen?",goodRu:"Ослабить/отменить read и вернуться ближе к baseline",goodEn:"Weaken/remove the read and return closer to baseline",whyRu:"Exploit evidence должно уметь умирать; иначе anecdote становится постоянным bias.",whyEn:"Exploit evidence must be able to die; otherwise an anecdote becomes a permanent bias.",bad1Ru:"Игнорировать новое evidence",bad1En:"Ignore the new evidence",bad2Ru:"Расширить read на все streets",bad2En:"Expand the read to all streets",changedVariables:["evidence_confidence"]}),
];

export const perceptualPracticalDecisions=decisions;

const seat=(position:PerceptualSeat["position"],stackBb:number,status?:PerceptualSeat["status"]):PerceptualSeat=>({position,stackBb,status});

export const practicalTableStates:PracticalTableState[]=[
  {decisionId:"PM-PERC-FND06-1",scaffold:"guided",stakes:"1/3",hero:"BTN",dealer:"BTN",seats:[seat("UTG",95,"folded"),seat("HJ",180,"folded"),seat("CO",320,"folded"),seat("BTN",260,"hero"),seat("SB",42,"active"),seat("BB",210,"active")],heroCards:["A♠","K♦"],potBb:18,actions:["BTN 3-bet to 18bb","SB calls","BB folds"],irrelevantCues:["CO has the largest stack"],revealCueRu:"В этой ветке Hero играет 42bb effective против SB, не 260bb/320bb.",revealCueEn:"In this branch Hero is 42bb effective versus SB, not 260bb/320bb."},
  {decisionId:"PM-PERC-FND06-2",scaffold:"hidden",stakes:"2/5",hero:"CO",dealer:"BTN",seats:[seat("UTG",90,"folded"),seat("HJ",400,"folded"),seat("CO",310,"hero"),seat("BTN",75,"active"),seat("SB",220,"folded"),seat("BB",260,"folded")],heroCards:["Q♠","Q♥"],potBb:24,actions:["CO opens 3bb","BTN 3-bets 11bb","CO calls"],revealCueRu:"75bb effective резко сжимает future SPR несмотря на 310bb Hero stack.",revealCueEn:"75bb effective sharply compresses future SPR despite Hero's 310bb stack."},

  {decisionId:"PM-PERC-BL03-1",scaffold:"reduced",stakes:"1/3",hero:"BB",dealer:"BTN",seats:[seat("UTG",140,"folded"),seat("HJ",160,"folded"),seat("CO",120,"folded"),seat("BTN",170,"active"),seat("SB",110,"folded"),seat("BB",165,"hero")],heroCards:["8♠","6♠"],potBb:3.5,actions:["BTN opens 2.5bb","SB folds"],revealCueRu:"Wide BTN origin + BB discount + closing action — это не generic OOP-vs-open.",revealCueEn:"Wide BTN origin + BB discount + closing action — this is not generic OOP-vs-open."},
  {decisionId:"PM-PERC-BL03-2",scaffold:"hidden",stakes:"1/3",hero:"BB",dealer:"BTN",seats:[seat("UTG",140,"folded"),seat("HJ",160,"folded"),seat("CO",120,"folded"),seat("BTN",170,"active"),seat("SB",110,"folded"),seat("BB",165,"hero")],heroCards:["8♠","6♠"],potBb:5,actions:["BTN opens 4bb","SB folds"],revealCueRu:"Единственная material change — цена open; fringe defence должен реагировать.",revealCueEn:"The only material change is the open price; fringe defense must respond."},

  {decisionId:"PM-PERC-BL04-1",scaffold:"guided",stakes:"2/5",hero:"BB",dealer:"CO",seats:[seat("UTG",100,"folded"),seat("HJ",150,"folded"),seat("CO",200,"active"),seat("BTN",90,"folded"),seat("SB",240,"folded"),seat("BB",180,"hero")],heroCards:["K♣","9♣"],potBb:4,actions:["CO opens 3bb"],revealCueRu:"Заметь размер open прежде чем доставать memorized BB rule.",revealCueEn:"Notice the open size before retrieving a memorized BB rule."},
  {decisionId:"PM-PERC-BL04-2",scaffold:"hidden",stakes:"2/5",hero:"BB",dealer:"CO",seats:[seat("UTG",100,"folded"),seat("HJ",150,"folded"),seat("CO",200,"active"),seat("BTN",90,"folded"),seat("SB",240,"folded"),seat("BB",180,"hero")],heroCards:["K♣","9♣"],potBb:5,actions:["CO opens 4bb"],revealCueRu:"Position/cards не изменились; price изменился.",revealCueEn:"Positions/cards did not change; the price did."},

  {decisionId:"PM-PERC-BOARD-1",scaffold:"reduced",stakes:"1/3",hero:"BTN",dealer:"BTN",seats:[seat("UTG",120,"folded"),seat("HJ",180,"folded"),seat("CO",150,"folded"),seat("BTN",160,"hero"),seat("SB",130,"folded"),seat("BB",155,"active")],heroCards:["K♠","Q♠"],board:["A♦","7♣","2♥"],potBb:6,actions:["BTN opens 2.5bb","BB calls","BB checks flop"],revealCueRu:"A-high texture важна через BTN-vs-BB arriving ranges, не сама по себе.",revealCueEn:"The A-high texture matters through BTN-vs-BB arriving ranges, not by itself."},
  {decisionId:"PM-PERC-BOARD-2",scaffold:"hidden",stakes:"1/3",hero:"HJ",dealer:"BTN",seats:[seat("UTG",120,"folded"),seat("HJ",160,"hero"),seat("CO",150,"folded"),seat("BTN",130,"active"),seat("SB",140,"folded"),seat("BB",155,"folded")],heroCards:["K♠","Q♠"],board:["A♦","7♣","2♥"],potBb:7,actions:["HJ opens 2.5bb","BTN calls","HJ acts flop"],revealCueRu:"Board тот же, но caller и opener ranges другие — ownership надо пересчитать.",revealCueEn:"Same board, different opener/caller ranges — ownership must be recomputed."},

  {decisionId:"PM-PERC-RUNOUT-1",scaffold:"reduced",stakes:"2/5",hero:"BB",dealer:"BTN",seats:[seat("UTG",150,"folded"),seat("HJ",170,"folded"),seat("CO",160,"folded"),seat("BTN",190,"active"),seat("SB",120,"folded"),seat("BB",185,"hero")],heroCards:["9♠","8♠"],board:["Q♣","7♦","3♣","A♥"],potBb:14,actions:["BTN opens 2.5bb","BB calls","flop: BB checks, BTN bets 33%, BB calls"],revealCueRu:"Turn A♥ нужно читать через flop bet-call surviving ranges.",revealCueEn:"The A♥ turn must be read through the flop bet-call surviving ranges."},
  {decisionId:"PM-PERC-RUNOUT-2",scaffold:"hidden",stakes:"2/5",hero:"BB",dealer:"BTN",seats:[seat("UTG",150,"folded"),seat("HJ",170,"folded"),seat("CO",160,"folded"),seat("BTN",190,"active"),seat("SB",120,"folded"),seat("BB",185,"hero")],heroCards:["9♠","8♠"],board:["Q♣","7♦","3♣","A♥"],potBb:8,actions:["BTN opens 2.5bb","BB calls","flop: BB checks, BTN checks back"],revealCueRu:"Та же A♥ имеет другое meaning после check-back composition.",revealCueEn:"The same A♥ has a different meaning after the check-back composition."},

  {decisionId:"PM-PERC-3BP05-1",scaffold:"guided",stakes:"2/5",hero:"BTN",dealer:"BTN",seats:[seat("UTG",120,"folded"),seat("HJ",140,"folded"),seat("CO",180,"folded"),seat("BTN",160,"hero"),seat("SB",170,"active"),seat("BB",110,"folded")],heroCards:["A♠","J♠"],board:["A♦","6♣","2♥"],potBb:24,actions:["BTN opens 2.5bb","SB 3-bets 11bb","BTN calls","SB checks flop"],revealCueRu:"Hero — IP caller, не aggressor. Role меняет default.",revealCueEn:"Hero is the IP caller, not the aggressor. Role changes the default."},
  {decisionId:"PM-PERC-3BP05-2",scaffold:"hidden",stakes:"2/5",hero:"SB",dealer:"BTN",seats:[seat("UTG",120,"folded"),seat("HJ",140,"folded"),seat("CO",180,"folded"),seat("BTN",160,"active"),seat("SB",170,"hero"),seat("BB",110,"folded")],heroCards:["A♠","J♠"],board:["A♦","6♣","2♥"],potBb:24,actions:["BTN opens 2.5bb","SB 3-bets 11bb","BTN calls","SB acts flop"],revealCueRu:"Same board family, но Hero теперь OOP aggressor — нельзя копировать IP caller line.",revealCueEn:"Same board family, but Hero is now the OOP aggressor — do not copy the IP caller line."},

  {decisionId:"PM-PERC-MW01-1",scaffold:"reduced",stakes:"1/3",hero:"CO",dealer:"BTN",seats:[seat("UTG",100,"active"),seat("HJ",140,"folded"),seat("CO",180,"hero"),seat("BTN",160,"active"),seat("SB",110,"folded"),seat("BB",220,"active")],heroCards:["A♣","J♣"],board:["J♦","8♠","4♥"],potBb:18,actions:["UTG bets 6bb","CO to act","BTN active behind","BB active behind"],revealCueRu:"Hero sandwiched: BTN и BB ещё могут raise/call после решения.",revealCueEn:"Hero is sandwiched: BTN and BB can still raise/call after Hero acts."},
  {decisionId:"PM-PERC-MW01-2",scaffold:"hidden",stakes:"1/3",hero:"BTN",dealer:"BTN",seats:[seat("UTG",100,"active"),seat("HJ",140,"folded"),seat("CO",180,"folded"),seat("BTN",160,"hero"),seat("SB",110,"folded"),seat("BB",220,"active")],heroCards:["A♣","J♣"],board:["J♦","8♠","4♥"],potBb:18,actions:["UTG bets 6bb","BB calls","BTN closes action"],revealCueRu:"Closing action убирает risk of action behind.",revealCueEn:"Closing the action removes the risk of action behind."},

  {decisionId:"PM-PERC-DEEP03-1",scaffold:"guided",stakes:"2/5/10 straddle",hero:"CO",dealer:"BTN",seats:[seat("UTG",300,"folded"),seat("HJ",260,"folded"),seat("CO",300,"hero"),seat("BTN",220,"active"),seat("SB",180,"active"),seat("BB",240,"active")],straddle:{position:"UTG",amountBb:2},potBb:3.5,actions:["UTG posts mandatory 10","action starts left of straddle"],revealCueRu:"300 physical BB relative to 5 is not 300 working units once 10 straddle is live.",revealCueEn:"300 physical big blinds relative to 5 are not 300 working units once the 10 straddle is live."},
  {decisionId:"PM-PERC-DEEP03-2",scaffold:"hidden",stakes:"2/5 no straddle",hero:"CO",dealer:"BTN",seats:[seat("UTG",300,"folded"),seat("HJ",260,"folded"),seat("CO",300,"hero"),seat("BTN",220,"active"),seat("SB",180,"active"),seat("BB",240,"active")],potBb:1.5,actions:["No straddle"],revealCueRu:"Убрав straddle, ты расширил strategic depth и вернул обычный action order.",revealCueEn:"Removing the straddle expands strategic depth and restores normal action order."},

  {decisionId:"PM-PERC-RIV03-1",scaffold:"reduced",stakes:"2/5",hero:"BB",dealer:"BTN",seats:[seat("UTG",150,"folded"),seat("HJ",130,"folded"),seat("CO",200,"folded"),seat("BTN",180,"active"),seat("SB",100,"folded"),seat("BB",175,"hero")],heroCards:["A♣","9♣"],board:["A♠","8♦","6♠","5♥","2♦"],potBb:42,actions:["flop: X-B33-C","turn: X-B75-C","river: X-B100"],revealCueRu:"До call восстанови natural missed draws/bluffs, а не только посчитай цену.",revealCueEn:"Before calling, reconstruct natural missed draws/bluffs rather than only calculating the price."},
  {decisionId:"PM-PERC-RIV03-2",scaffold:"hidden",stakes:"2/5",hero:"BB",dealer:"BTN",seats:[seat("UTG",150,"folded"),seat("HJ",130,"folded"),seat("CO",200,"folded"),seat("BTN",180,"active"),seat("SB",100,"folded"),seat("BB",175,"hero")],heroCards:["A♣","9♣"],board:["A♠","8♦","6♠","5♥","2♦"],potBb:42,actions:["flop: X-B33-C","turn: X-X","river: X-B100"],revealCueRu:"Price тот же, но turn check-back radically changes bluff/value ancestry.",revealCueEn:"The price is the same, but the turn check-back radically changes bluff/value ancestry."},

  {decisionId:"PM-PERC-EXP01-1",scaffold:"guided",stakes:"1/3 live",hero:"BTN",dealer:"BTN",seats:[seat("UTG",90,"active"),seat("HJ",300,"active"),seat("CO",130,"folded"),seat("BTN",200,"hero"),seat("SB",160,"active"),seat("BB",250,"active")],actions:["HJ showed one huge river bluff last orbit","No repeated same-branch sample yet"],irrelevantCues:["HJ has the biggest stack"],revealCueRu:"Один vivid showdown — observation, не stable read.",revealCueEn:"One vivid showdown is an observation, not a stable read."},
  {decisionId:"PM-PERC-EXP01-2",scaffold:"hidden",stakes:"1/3 live",hero:"BTN",dealer:"BTN",seats:[seat("UTG",90,"active"),seat("HJ",300,"active"),seat("CO",130,"folded"),seat("BTN",200,"hero"),seat("SB",160,"active"),seat("BB",250,"active")],actions:["HJ previously overbluffed large river bets","Last 4 comparable branches: checked/folded or showed value"],revealCueRu:"Read должен ослабнуть: new same-branch evidence contradicts old hypothesis.",revealCueEn:"The read should weaken: new same-branch evidence contradicts the old hypothesis."},
];

export const practicalTableStateByDecisionId=new Map(practicalTableStates.map((state)=>[state.decisionId,state]));
