import type { PracticalTableState, PerceptualSeat } from "./perceptual-table-states";

const seat=(position:PerceptualSeat["position"],stackBb:number,status?:PerceptualSeat["status"]):PerceptualSeat=>({position,stackBb,status});

export const b3PracticalTableStates:PracticalTableState[]=[
  {decisionId:"PM-B3-PF01-101",scaffold:"reduced",stakes:"1/3",hero:"BTN",dealer:"BTN",seats:[seat("UTG",150,"folded"),seat("HJ",160,"folded"),seat("CO",180,"folded"),seat("BTN",170,"hero"),seat("SB",120,"active"),seat("BB",200,"active")],heroCards:["A♣","7♣"],potBb:1.5,actions:["Folds to BTN"],revealCueRu:"RFI fringe нужно читать через position и players behind, не только по карте.",revealCueEn:"Read RFI fringe through position and players behind, not only the cards."},
  {decisionId:"PM-B3-PF01-103",scaffold:"hidden",stakes:"1/3",hero:"HJ",dealer:"BTN",seats:[seat("UTG",150,"folded"),seat("HJ",160,"hero"),seat("CO",180,"active"),seat("BTN",170,"active"),seat("SB",120,"active"),seat("BB",200,"active")],heroCards:["A♣","7♣"],potBb:1.5,actions:["Folds to HJ"],revealCueRu:"Та же hand family теперь раньше и с большим числом players behind.",revealCueEn:"The same hand family is now earlier with more players behind."},

  {decisionId:"PM-B3-PF04-101",scaffold:"reduced",stakes:"2/5",hero:"BB",dealer:"BTN",seats:[seat("UTG",160,"folded"),seat("HJ",190,"folded"),seat("CO",140,"active"),seat("BTN",170,"folded"),seat("SB",130,"folded"),seat("BB",180,"hero")],heroCards:["Q♠","8♠"],potBb:4,actions:["CO opens 3bb","SB folds"],revealCueRu:"BB call = price × origin × closing action × realization.",revealCueEn:"BB call = price × origin × closing action × realization."},
  {decisionId:"PM-B3-PF04-103",scaffold:"hidden",stakes:"2/5",hero:"BB",dealer:"BTN",seats:[seat("UTG",160,"active"),seat("HJ",190,"folded"),seat("CO",140,"folded"),seat("BTN",170,"folded"),seat("SB",130,"folded"),seat("BB",180,"hero")],heroCards:["Q♠","8♠"],potBb:4,actions:["UTG opens 3bb","SB folds"],revealCueRu:"Same price, stronger origin range — fringe call must be reconsidered.",revealCueEn:"Same price, stronger origin range — reconsider the fringe call."},

  {decisionId:"PM-B3-PF06-101",scaffold:"reduced",stakes:"1/3",hero:"BTN",dealer:"BTN",seats:[seat("UTG",120,"folded"),seat("HJ",180,"folded"),seat("CO",150,"active"),seat("BTN",170,"hero"),seat("SB",110,"active"),seat("BB",200,"active")],heroCards:["A♠","5♠"],potBb:4,actions:["CO opens 3bb","BTN to act"],irrelevantCues:["CO called several raises earlier but sample is small"],revealCueRu:"3-bet shape зависит от folds и того, как hand играет when called.",revealCueEn:"3-bet shape depends on folds and how the hand performs when called."},
  {decisionId:"PM-B3-PF06-103",scaffold:"hidden",stakes:"1/3",hero:"BTN",dealer:"BTN",seats:[seat("UTG",120,"folded"),seat("HJ",180,"folded"),seat("CO",150,"active"),seat("BTN",170,"hero"),seat("SB",110,"active"),seat("BB",200,"active")],heroCards:["A♠","5♠"],potBb:4,actions:["CO opens 3bb","CO has repeatedly called 3-bets and rarely folded"],revealCueRu:"Fold equity collapsed; bluff-heavy polar construction loses EV.",revealCueEn:"Fold equity collapsed; bluff-heavy polar construction loses EV."},

  {decisionId:"PM-B3-PF07-101",scaffold:"reduced",stakes:"2/5",hero:"BTN",dealer:"BTN",seats:[seat("UTG",150,"folded"),seat("HJ",180,"folded"),seat("CO",160,"folded"),seat("BTN",170,"hero"),seat("SB",180,"active"),seat("BB",140,"folded")],heroCards:["J♠","J♦"],potBb:14,actions:["BTN opens 2.5bb","SB 3-bets to 10bb"],revealCueRu:"Facing 3-bet: size/position/range shape matter more than memorized defend percentage.",revealCueEn:"Facing a 3-bet: size/position/range shape matter more than a memorized defense percentage."},
  {decisionId:"PM-B3-PF07-103",scaffold:"hidden",stakes:"2/5",hero:"BTN",dealer:"BTN",seats:[seat("UTG",150,"folded"),seat("HJ",180,"folded"),seat("CO",160,"folded"),seat("BTN",170,"hero"),seat("SB",180,"active"),seat("BB",140,"folded")],heroCards:["J♠","J♦"],potBb:19,actions:["BTN opens 2.5bb","SB 3-bets to 15bb"],revealCueRu:"Same hand/positions, much larger 3-bet price changes the branch.",revealCueEn:"Same hand/positions, much larger 3-bet price changes the branch."},

  {decisionId:"PM-B3-OOP02-101",scaffold:"reduced",stakes:"1/3",hero:"BB",dealer:"BTN",seats:[seat("UTG",120,"folded"),seat("HJ",150,"folded"),seat("CO",140,"folded"),seat("BTN",180,"active"),seat("SB",100,"folded"),seat("BB",170,"hero")],heroCards:["9♣","8♣"],board:["9♦","6♠","3♥"],potBb:7,actions:["BTN opens","BB calls","flop BB checks","BTN bets 25%"],revealCueRu:"OOP defence combines price with robustness and future pressure.",revealCueEn:"OOP defense combines price with robustness and future pressure."},
  {decisionId:"PM-B3-OOP02-103",scaffold:"hidden",stakes:"1/3",hero:"BB",dealer:"BTN",seats:[seat("UTG",120,"folded"),seat("HJ",150,"folded"),seat("CO",140,"folded"),seat("BTN",180,"active"),seat("SB",100,"folded"),seat("BB",170,"hero")],heroCards:["9♣","8♣"],board:["9♦","6♠","3♥"],potBb:7,actions:["BTN opens","BB calls","flop BB checks","BTN bets 75%"],revealCueRu:"Only sizing changed; marginal OOP continues must tighten.",revealCueEn:"Only sizing changed; marginal OOP continues must tighten."},

  {decisionId:"PM-B3-IP01-101",scaffold:"reduced",stakes:"2/5",hero:"BTN",dealer:"BTN",seats:[seat("UTG",130,"folded"),seat("HJ",170,"folded"),seat("CO",150,"folded"),seat("BTN",180,"hero"),seat("SB",100,"folded"),seat("BB",175,"active")],heroCards:["K♠","Q♦"],board:["A♣","7♦","2♠"],potBb:6,actions:["BTN opens","BB calls","BB checks"],revealCueRu:"Range-vs-selective c-bet starts with board×arriving ranges.",revealCueEn:"Range-vs-selective c-bet starts with board×arriving ranges."},
  {decisionId:"PM-B3-IP01-103",scaffold:"hidden",stakes:"2/5",hero:"BTN",dealer:"BTN",seats:[seat("UTG",130,"folded"),seat("HJ",170,"folded"),seat("CO",150,"folded"),seat("BTN",180,"hero"),seat("SB",100,"folded"),seat("BB",175,"active")],heroCards:["K♠","Q♦"],board:["8♣","7♦","6♠"],potBb:6,actions:["BTN opens","BB calls","BB checks"],revealCueRu:"Same ranges/role, connected board equalizes caller coverage.",revealCueEn:"Same ranges/role, connected board equalizes caller coverage."},

  {decisionId:"PM-B3-TURN02-101",scaffold:"reduced",stakes:"2/5",hero:"BTN",dealer:"BTN",seats:[seat("UTG",120,"folded"),seat("HJ",140,"folded"),seat("CO",160,"folded"),seat("BTN",180,"hero"),seat("SB",100,"folded"),seat("BB",170,"active")],heroCards:["K♠","J♠"],board:["Q♣","7♠","3♦","A♥"],potBb:15,actions:["BTN opens","BB calls","flop BB checks BTN bets BB calls","turn BB checks"],revealCueRu:"Turn barrel needs runout shift + hand class + surviving continues.",revealCueEn:"Turn barrel needs runout shift + hand class + surviving continues."},
  {decisionId:"PM-B3-TURN02-103",scaffold:"hidden",stakes:"2/5",hero:"BTN",dealer:"BTN",seats:[seat("UTG",120,"folded"),seat("HJ",140,"folded"),seat("CO",160,"folded"),seat("BTN",180,"hero"),seat("SB",100,"folded"),seat("BB",170,"active")],heroCards:["K♠","J♠"],board:["Q♣","7♠","3♦","4♥"],potBb:15,actions:["BTN opens","BB calls","flop BB checks BTN bets BB calls","turn BB checks"],revealCueRu:"Same line/hand, different turn leverage — momentum alone is not enough.",revealCueEn:"Same line/hand, different turn leverage — momentum alone is not enough."},

  {decisionId:"PM-B3-TURN03-101",scaffold:"reduced",stakes:"1/3",hero:"BB",dealer:"BTN",seats:[seat("UTG",130,"folded"),seat("HJ",160,"folded"),seat("CO",140,"folded"),seat("BTN",180,"active"),seat("SB",100,"folded"),seat("BB",170,"hero")],heroCards:["8♠","7♠"],board:["K♣","6♦","2♥","4♠"],potBb:7,actions:["BTN opens","BB calls","flop BB checks BTN checks back","turn BB to act"],revealCueRu:"Probe only after reconstructing what check-back removed/capped.",revealCueEn:"Probe only after reconstructing what the check-back removed/capped."},
  {decisionId:"PM-B3-TURN03-103",scaffold:"hidden",stakes:"1/3",hero:"BB",dealer:"BTN",seats:[seat("UTG",130,"folded"),seat("HJ",160,"folded"),seat("CO",140,"folded"),seat("BTN",180,"active"),seat("SB",100,"folded"),seat("BB",170,"hero")],heroCards:["8♠","7♠"],board:["K♣","6♦","2♥","A♠"],potBb:7,actions:["BTN opens","BB calls","flop BB checks BTN checks back","turn BB to act"],revealCueRu:"Turn can restore strong IP regions; missed c-bet is not an automatic probe license.",revealCueEn:"The turn can restore strong IP regions; a missed c-bet is not an automatic probe license."},

  {decisionId:"PM-B3-RIV01-101",scaffold:"reduced",stakes:"2/5",hero:"BTN",dealer:"BTN",seats:[seat("UTG",140,"folded"),seat("HJ",150,"folded"),seat("CO",160,"folded"),seat("BTN",180,"hero"),seat("SB",120,"folded"),seat("BB",170,"active")],heroCards:["A♠","Q♦"],board:["A♣","9♥","5♠","3♦","2♣"],potBb:30,actions:["flop BTN bet/call","turn BTN bet/call","river BB checks"],revealCueRu:"River value starts by naming worse calls for the chosen sizing.",revealCueEn:"River value starts by naming worse calls for the chosen sizing."},
  {decisionId:"PM-B3-RIV01-103",scaffold:"hidden",stakes:"2/5",hero:"BTN",dealer:"BTN",seats:[seat("UTG",140,"folded"),seat("HJ",150,"folded"),seat("CO",160,"folded"),seat("BTN",180,"hero"),seat("SB",120,"folded"),seat("BB",170,"active")],heroCards:["A♠","Q♦"],board:["A♣","9♥","5♠","3♦","2♣"],potBb:30,actions:["flop BTN bet/call","turn BTN bet/call","river BB checks","BB has shown repeated tight river calls"],revealCueRu:"Same hand/board, tighter worse-calling region reduces thin-value EV.",revealCueEn:"Same hand/board, a tighter worse-calling region reduces thin-value EV."},

  {decisionId:"PM-B3-MW02-101",scaffold:"reduced",stakes:"1/3",hero:"BTN",dealer:"BTN",seats:[seat("UTG",150,"active"),seat("HJ",130,"folded"),seat("CO",170,"active"),seat("BTN",180,"hero"),seat("SB",120,"folded"),seat("BB",160,"active")],heroCards:["K♠","Q♠"],board:["K♦","9♣","6♥"],potBb:18,actions:["UTG checks","CO bets","BTN to act","BB still active"],revealCueRu:"One-pair threshold changes because several credible ranges survive.",revealCueEn:"The one-pair threshold changes because several credible ranges survive."},
  {decisionId:"PM-B3-MW02-103",scaffold:"hidden",stakes:"1/3",hero:"BTN",dealer:"BTN",seats:[seat("UTG",150,"folded"),seat("HJ",130,"folded"),seat("CO",170,"active"),seat("BTN",180,"hero"),seat("SB",120,"folded"),seat("BB",160,"folded")],heroCards:["K♠","Q♠"],board:["K♦","9♣","6♥"],potBb:12,actions:["CO bets","BTN heads-up to act"],revealCueRu:"Same hand/board became heads-up; marginal value/continue threshold can loosen.",revealCueEn:"Same hand/board became heads-up; marginal value/continue threshold can loosen."},

  {decisionId:"PM-B3-DEEP01-101",scaffold:"reduced",stakes:"2/5",hero:"BTN",dealer:"BTN",seats:[seat("UTG",180,"folded"),seat("HJ",200,"folded"),seat("CO",160,"folded"),seat("BTN",200,"hero"),seat("SB",190,"folded"),seat("BB",200,"active")],heroCards:["A♣","J♣"],potBb:20,actions:["200bb effective","single-raised pot","meaningful stacks remain"],revealCueRu:"At 200bb, nut potential/reverse implied odds/future leverage matter more.",revealCueEn:"At 200bb, nut potential/reverse implied odds/future leverage matter more."},
  {decisionId:"PM-B3-DEEP01-103",scaffold:"hidden",stakes:"2/5",hero:"BTN",dealer:"BTN",seats:[seat("UTG",180,"folded"),seat("HJ",200,"folded"),seat("CO",160,"folded"),seat("BTN",100,"hero"),seat("SB",190,"folded"),seat("BB",100,"active")],heroCards:["A♣","J♣"],potBb:20,actions:["100bb effective","same pot type"],revealCueRu:"Only effective depth changed; one-pair/future leverage planning should react.",revealCueEn:"Only effective depth changed; one-pair/future leverage planning should react."},
];
