export type PracticalSourceBoundTeachingAsset = {
  skillId: string;
  sourceRefs: string[];
  situationRu: string;
  situationEn: string;
  mechanismRu: string;
  mechanismEn: string;
  exampleRu: string;
  exampleEn: string;
  boundaryRu: string;
  boundaryEn: string;
};

const a = (asset: PracticalSourceBoundTeachingAsset): PracticalSourceBoundTeachingAsset => asset;

/**
 * Explicit post-Quick-Start teaching for ordinary source-supported skills that
 * have assessment depth but no rule/anchor teaching entry. These assets are
 * source-bounded teaching content, not a routing allowlist: eligibility stays
 * derived from the canonical skill registry, source-gap authority,
 * prerequisites, and corpus reachability.
 */
export const practicalSourceBoundTeachingAssets: PracticalSourceBoundTeachingAsset[] = [
  a({
    skillId: "FND-06",
    sourceRefs: ["LCM-01", "FTGU-E01"],
    situationRu: "Перед решением геометрия может измениться тремя способами: соперники имеют разные стеки, сформированный банк меняется относительно оставшегося стека или обязательная единица ставки становится другой.",
    situationEn: "Before a decision, geometry can change in three ways: opponents have different stacks, the formed pot changes relative to the remaining stack, or the forced betting unit changes.",
    mechanismRu: "Сначала определи эффективный стек отдельно против каждого действительно релевантного соперника. Затем считай SPR как отношение оставшегося эффективного стека к банку: больший банк при том же стеке сжимает дерево будущих решений, а больший оставшийся стек при том же банке расширяет его. Если появился страддл, сначала переопредели рабочую глубину и порядок действий в новой обязательной единице ставки.",
    mechanismEn: "First identify the pairwise effective stack versus the relevant opponent. Then read SPR as remaining effective stack relative to the pot: a larger pot with the same stack compresses the future tree, while more remaining stack with the same pot expands it. If a straddle appears, first re-anchor working depth and action order to the new forced unit.",
    exampleRu: "Hero 160bb играет multiway против стеков 70bb и 220bb: против каждого соперника effective depth различается. Если при том же effective stack префлоп-экшен удваивает банк, flop SPR падает. Mandatory straddle дополнительно меняет рабочую единицу и может сделать nominal 200bb заметно короче стратегически.",
    exampleEn: "Hero at 160bb plays multiway versus 70bb and 220bb stacks: effective depth differs by opponent. If preflop action doubles the pot with the same effective stack, flop SPR falls. A mandatory straddle also changes the working unit and can make a nominal 200bb stack strategically much shorter.",
    boundaryRu: "Не ищи одну общую глубину для всего multiway-банка, не считай SPR по стартовому buy-in и не воспринимай straddle как косметическую метку.",
    boundaryEn: "Do not force one table-wide depth onto a multiway pot, do not compute SPR from the starting buy-in, and do not treat a straddle as a cosmetic label.",
  }),
  a({
    skillId: "FND-04",
    sourceRefs: ["EXT-PC-OUTS-2026", "EXT-PC-OUTS-GUIDE-2023"],
    situationRu: "У Hero дро, но часть карт, которые визуально улучшают руку, не гарантирует лучшую комбинацию против диапазона соперника.",
    situationEn: "Hero has a draw, but some cards that appear to improve the hand do not reliably make the best hand against the opponent's range.",
    mechanismRu: "Сначала отделяй чистые ауты от сомнительных и грязных. Аут ценен только настолько, насколько часто улучшение действительно приводит к лучшей руке; domination, общий аут и сильная часть диапазона соперника могут требовать дисконтирования.",
    mechanismEn: "Separate clean outs from questionable and dirty outs first. An out is worth only as much as the improvement actually makes the best hand; domination, shared outs, and the opponent's strong range can require discounting.",
    exampleRu: "Если тот же номинальный дро сталкивается не с диапазоном одной пары, а с более плотным набором сетов, двух пар и натсовых дро, часть прежних аутов становится грязной — сырой счёт аутов уже нельзя переносить без поправки.",
    exampleEn: "If the same nominal draw now faces a denser range of sets, two pair, and nut draws instead of mostly one-pair hands, some previous outs become dirty; the raw out count cannot be carried over unchanged.",
    boundaryRu: "Не считай каждую карту, которая улучшает Hero, полноценным аутом и не превращай приблизительный подсчёт аутов в точную equity без диапазона соперника.",
    boundaryEn: "Do not count every card that improves Hero as a full out, and do not turn an approximate out count into exact equity without the opponent's range.",
  }),
  a({
    skillId: "PF-10",
    sourceRefs: ["FTGU-E02", "FTGU-E05", "SLC-PREFLOP-ADJUSTMENTS"],
    situationRu: "Та же префлоп-рука попадает в другую среду: меняются глубина, рейк, размер открытия или качество игроков позади.",
    situationEn: "The same preflop hand moves into a different environment: depth, rake, open size, or the players behind change.",
    mechanismRu: "Корректируй прежде всего пограничную часть диапазона. Более глубокие стеки повышают ценность suited/connected и сильных flat-веток, а высокие рейк и цена давления убирают тонкие продолжения первыми.",
    mechanismEn: "Adjust the fringe of the range first. Deeper stacks increase the value of suited/connected hands and strong flat branches, while higher rake and a worse price remove thin continues first.",
    exampleRu: "При переходе со 100bb на 200-400bb не копируй прежний stack-off: сильные руки чаще сохраняют flat/call ветки, а очень глубокая игра требует более избирательного разгона банка.",
    exampleEn: "When moving from 100bb to 200-400bb, do not copy the old stack-off threshold: strong hands retain more flat/call branches and very deep play requires more selective pot building.",
    boundaryRu: "Не делай вывод, что глубина расширяет все руки одинаково или что один фактор — только рейк, только позиция или только размер открытия — полностью определяет префлоп-ветку.",
    boundaryEn: "Do not assume depth improves every hand equally or that one factor—rake, position, or open size alone—fully determines the preflop branch.",
  }),
  a({
    skillId: "BL-06",
    sourceRefs: ["EXT-GTOW-SB-SRP-2024"],
    situationRu: "До SB все сфолдили в 100bb cash; если BB продолжит, SB гарантированно будет OOP и уже имеет часть обязательной ставки в банке.",
    situationEn: "Action folds to the SB in 100bb cash; if BB continues, SB is guaranteed to play OOP and already has part of a blind invested.",
    mechanismRu: "SB first-in не сводится к forced raise-or-fold. Limp и raise могут сосуществовать, а fringe зависит от того, как BB отвечает на limp и raise.",
    mechanismEn: "SB first-in is not a forced raise-or-fold node. Limp and raise can coexist, and the fringe depends on how BB responds to limps and raises.",
    exampleRu: "Если BB меняется с пассивного check-heavy игрока на соперника, который агрессивно атакует limps, часть пограничных SB веток должна измениться — сам ярлык позиции ответа не даёт.",
    exampleEn: "If BB changes from passive/check-heavy to aggressively attacking limps, some fringe SB branches should change; the position label alone does not provide the answer.",
    boundaryRu: "Не учи SB first-in как универсальный raise-or-fold и не переносись на точные solver mixes без проверенного контекста.",
    boundaryEn: "Do not learn SB first-in as universal raise-or-fold, and do not import exact solver mixes without the reviewed context.",
  }),
  a({
    skillId: "BL-07",
    sourceRefs: ["EXT-UP-BVB-CALLER-2019", "EXT-GTOW-SB-SRP-2024"],
    situationRu: "BB защищается против SB open и закрывает префлоп-экшен, после чего получает позицию постфлоп.",
    situationEn: "BB defends versus an SB open, closes the preflop action, and will have position postflop.",
    mechanismRu: "Хорошая цена, closing action и позиционная реализация поддерживают существенно более широкий defend, чем против ранних opens; split call/3-bet всё равно зависит от свойств руки и сайзинга.",
    mechanismEn: "Good price, closing action, and positional realization support a materially wider defense than versus early-position opens; the call/3-bet split still depends on hand properties and sizing.",
    exampleRu: "При той же руке более крупный SB open ухудшает цену и первым выталкивает пограничные calls; происхождение диапазона SB и позиция BB всё ещё отличают этот узел от BB-vs-BTN.",
    exampleEn: "With the same hand, a larger SB open worsens the price and removes fringe calls first; SB range origin and BB's postflop position still distinguish this node from BB-versus-BTN.",
    boundaryRu: "Не копируй один BB-vs-open chart между EP, BTN и SB и не считай хорошую цену лицензией защищать любую руку.",
    boundaryEn: "Do not copy one BB-versus-open chart across EP, BTN, and SB, and do not treat a good price as permission to defend any hand.",
  }),
  a({
    skillId: "BL-08",
    sourceRefs: ["EXT-UP-BVB-LIMP-2019", "EXT-GTOW-BVB-LIMP-CALLED-2024"],
    situationRu: "SB open-limp; BB может бесплатно реализовать позицию через check или raise, если raise создаёт реальный value/fold leverage.",
    situationEn: "SB open-limps; BB can realize position for free by checking or raise when the raise creates real value/fold leverage.",
    mechanismRu: "Сравнивай EV raise с EV check. Raise нужен не потому, что limp выглядит слабым, а потому что конкретная рука выигрывает от folds, value или denial против состава limp-range.",
    mechanismEn: "Compare raise EV with check EV. Raise is not justified because a limp looks weak; the specific hand must gain from folds, value, or denial against the limp range.",
    exampleRu: "Если SB переходит от сбалансированного limp к слабому игроку, который слишком широко limp-call, value-часть BB raise может расшириться, а некоторые блефы — потерять привлекательность.",
    exampleEn: "If SB shifts from a balanced limp construction to a weak player who limp-calls too widely, BB's value-raise region can widen while some bluffs become less attractive.",
    boundaryRu: "Не превращай 'SB limp = weakness' в автоматический raise каждой playable рукой.",
    boundaryEn: "Do not turn 'SB limp = weakness' into an automatic raise with every playable hand.",
  }),
  a({
    skillId: "BL-09",
    sourceRefs: ["EXT-UP-BVB-LIMP-2019", "EXT-GTOW-BVB-LIMP-CALLED-2024"],
    situationRu: "SB limped, BB сделал isolation raise, и SB выбирает continue/fold/reraise.",
    situationEn: "SB limped, BB made an isolation raise, and SB now chooses continue/fold/reraise.",
    mechanismRu: "Здоровый limp-range не обязан быть capped: в нём остаются сильные продолжения и traps. Ответ зависит от размера и конструкции BB raise, а не от самого факта предыдущего limp.",
    mechanismEn: "A sound limp range need not be capped: strong continues and traps remain. The response depends on the size and construction of BB's raise, not on the fact that SB limped.",
    exampleRu: "Если BB увеличивает raise и становится value-heavy, та же пограничная SB рука должна продолжать реже, тогда как сильные limp-ветки защищают диапазон.",
    exampleEn: "If BB raises larger and becomes more value-heavy, the same fringe SB hand should continue less often while strong limp branches protect the range.",
    boundaryRu: "Не считай limped range автоматически слабым и не продолжай одинаково против каждого BB sizing.",
    boundaryEn: "Do not assume a limped range is automatically weak, and do not continue identically versus every BB sizing.",
  }),
  a({
    skillId: "BL-12",
    sourceRefs: ["FTGU-E05", "LCM-01"],
    situationRu: "Blind-defence spot сохраняет те же карты, но меняются рейк или обязательная единица ставки через straddle.",
    situationEn: "A blind-defense spot keeps the same cards while rake or the forced betting unit changes through a straddle.",
    mechanismRu: "Высокий рейк первым ухудшает тонкие calls; straddle требует заново нормализовать рабочую глубину, банк и порядок действий. Это разные причины, но обе меняют EV пограничной защиты.",
    mechanismEn: "Higher rake hurts thin calls first; a straddle requires re-normalizing working depth, pot geometry, and action order. They are different causes, but both move fringe-defense EV.",
    exampleRu: "Тонкий BB call может быть нормальным при более низком рейке и стать fold при существенно более высоком; при straddle сначала пересчитай effective depth в новой forced unit, а уже потом применяй blind heuristic.",
    exampleEn: "A thin BB call can be acceptable at lower rake and become a fold at materially higher rake; with a straddle, first recompute effective depth in the new forced unit before applying a blind heuristic.",
    boundaryRu: "Не трактуй straddle как косметическую метку и не считай, что рейк влияет только на уже сильные руки или только на river.",
    boundaryEn: "Do not treat a straddle as a cosmetic label, and do not assume rake affects only strong hands or only the river.",
  }),
  a({
    skillId: "TURN-01",
    sourceRefs: ["FTGU-E21"],
    situationRu: "W4-RUNOUT-01 уже научил замечать blank, scare, completing и range-shifting runouts. Здесь тот же знакомый класс карты нужно привязать к тому, какие диапазоны реально дошли до тёрна после конкретной линии флопа.",
    situationEn: "W4-RUNOUT-01 already taught the basic blank, scare, completing, and range-shifting runout classes. Here the familiar card class must be tied to the ranges that actually survived the specific flop line.",
    mechanismRu: "Не переучивай ярлык карты с нуля. Сначала восстанови диапазоны, сохранившиеся после флоп-экшена, затем спроси, что новая карта вернула, закрыла или перераспределила в сильной части каждого диапазона. Класс ран-аута — это сигнал пересчитать, кому принадлежит преимущество, а не готовое действие.",
    mechanismEn: "Do not relearn the card label from scratch. First reconstruct the ranges that survived the flop action, then ask what the new card restored, completed, or shifted in each range's strong region. The runout class is a trigger to recompute ownership, not a ready-made action.",
    exampleRu: "Одна и та же высокая карта может быть почти бланком после линии, где у обоих диапазонов мало комбинаций этого ранга, и заметно range-shifting после другой линии, где один диапазон сохранил гораздо больше сильных комбинаций. Поэтому сначала ancestry, потом классификация и только затем действие.",
    exampleEn: "The same high card can be close to a blank after a line where neither range retains much of that rank, yet materially range-shifting after a different line where one range kept far more strong combinations. Read ancestry first, then classification, then choose the action.",
    boundaryRu: "Не превращай знакомые ярлыки «бланк / страшная карта / закрывающая дро» в автоматические ставки или чеки и не считай любую оверкарту страшной без проверки сохранившихся диапазонов.",
    boundaryEn: "Do not turn familiar blank/scare/completing labels into automatic bets or checks, and do not call every overcard a scare card without checking the surviving ranges.",
  }),
  a({
    skillId: "W4-DRAW-01",
    sourceRefs: ["FTGU-E09", "EXT-PC-OUTS-GUIDE-2023"],
    situationRu: "У Hero draw или pair+draw; одинаковое число номинальных аутов может скрывать разное качество улучшений и разный showdown value.",
    situationEn: "Hero has a draw or pair-plus-draw; the same nominal out count can hide very different improvement quality and showdown value.",
    mechanismRu: "Оценивай чистые ауты, натсовый потенциал, пересечение и двойной подсчёт аутов, доминацию и текущую шоудаун-ценность. Для рейза важен не ярлык дро, а то, как рука играет против диапазона продолжения.",
    mechanismEn: "Evaluate clean outs, nut potential, overlap/double-counting, domination, and current showdown value. For a raise, the draw label matters less than how the hand performs against the continuing range.",
    exampleRu: "Два flush-draw с одинаковым количеством аутов не эквивалентны, если один делает nuts и сохраняет хорошие barrel cards, а второй dominated и делит часть грязных аутов.",
    exampleEn: "Two flush draws with the same raw out count are not equivalent if one makes the nuts and retains good barrel cards while the other is dominated and shares dirty outs.",
    boundaryRu: "Не приравнивай одинаковый out count к одинаковому EV и не рейзь draw только потому, что это draw.",
    boundaryEn: "Do not equate the same out count with the same EV, and do not raise a draw merely because it is a draw.",
  }),
  a({
    skillId: "OOP-04",
    sourceRefs: ["SLC-HARD-CONTINUES", "FTGU-E08"],
    situationRu: "OOP defender сталкивается с маленьким или очень частым c-bet и рискует выкинуть всё, кроме очевидных пар и сильных draws.",
    situationEn: "An OOP defender faces a small or very frequent c-bet and risks folding everything except obvious pairs and strong draws.",
    mechanismRu: "Цена и структура диапазона требуют сохранять часть неудобных продолжений с полезными бэкдорами и будущими путями к EV. Маленькая ставка не означает «коллировать всё», но автоматический оверфолд ломает диапазон.",
    mechanismEn: "Price and range structure require retaining some uncomfortable continues with useful backdoors and future EV routes. A small bet does not mean call-all, but automatic overfolding breaks the range.",
    exampleRu: "Контраст: 2/5, BTN открывает $15, BB коллирует; на флопе A♠7♦2♣ банк около $30, BTN ставит $10. K♠Q♠ у BB имеет бэкдорное флеш-дро и больше полезных будущих карт, чем K♥Q♣ без флеш-бэкдора. Прогноз до ответа: если ставка вырастет примерно до $22 при той же доске и диапазонах, K♥Q♣ должен уходить из пограничного продолжения раньше, а K♠Q♠ сохраняет больше оснований продолжать.",
    exampleEn: "Worked contrast: BTN opened wide, BB defended, and the flop faces a small frequent c-bet. A weak high-card hand with backdoor flush/straight routes can continue more often than the same high-card class without useful backdoors. Predict first: as sizing grows, the second class should fold earlier.",
    boundaryRu: "Не переноси это на любой sizing/board: wetness, vulnerability, origin ranges и более крупное давление могут резко сужать continue.",
    boundaryEn: "Do not transfer this to every sizing or board: wetness, vulnerability, range origin, and larger pressure can sharply narrow the continue region.",
  }),
  a({
    skillId: "OOP-05",
    sourceRefs: ["FTGU-E07", "FTGU-E09"],
    situationRu: "OOP defender сталкивается с более крупной или более полярной flop ставкой.",
    situationEn: "An OOP defender faces a larger or more polar flop bet.",
    mechanismRu: "Когда bet сильнее фильтрует диапазон, требования к realization и robust continues растут. Raise строится из value, которое хорошо стоит против продолжения, и качественных bluffs/semi-bluffs — не из любой руки, которая 'может улучшиться'.",
    mechanismEn: "As the bet filters ranges more strongly, realization and robust-continue requirements rise. A raise is built from value that performs well versus the continuing range plus high-quality bluffs/semi-bluffs—not every hand that can improve.",
    exampleRu: "При той же доске увеличение сайзинга может превратить тонкий колл в фолд и одновременно сделать диапазон рейза более полярным: руки средней силы чаще теряют комфортную ветку.",
    exampleEn: "On the same board, a larger sizing can turn a thin call into a fold while making raises more polar; medium-strength hands lose their comfortable branch first.",
    boundaryRu: "Не считай крупный sizing автоматическим доказательством nuts и не отвечай raise только потому, что Hero имеет draw.",
    boundaryEn: "Do not treat a large sizing as automatic proof of the nuts, and do not raise merely because Hero has a draw.",
  }),
  a({
    skillId: "3BP-02",
    sourceRefs: ["SLC-EXPLOITING-OOP-CBETS"],
    situationRu: "Hero — префлоп 3-беттор OOP; flop может сохранять или уменьшать его range/nut advantage.",
    situationEn: "Hero is the preflop 3-bettor OOP; the flop can preserve or reduce Hero's range and nut advantage.",
    mechanismRu: "Инициатива не отменяет позиционный недостаток. Частота и размер c-bet зависят от дошедших диапазонов и board interaction; на неблагоприятных/выравнивающих досках защищённый check становится важнее.",
    mechanismEn: "Initiative does not erase positional disadvantage. C-bet frequency and size depend on arriving ranges and board interaction; protected checking becomes more important on adverse or equalizing boards.",
    exampleRu: "Та же 3-bet линия может поддерживать частую небольшую ставку на сухом high-card flop и намного более выборочную стратегию на connected board, который лучше покрывает caller.",
    exampleEn: "The same 3-bet line can support frequent small betting on a dry high-card flop and a much more selective strategy on a connected board that better covers the caller.",
    boundaryRu: "Не переноси IP c-bet plan на OOP и не считай префлоп-агрессию постоянным преимуществом на любой доске.",
    boundaryEn: "Do not copy an IP c-bet plan to OOP, and do not treat preflop aggression as permanent advantage on every board.",
  }),
  a({
    skillId: "3BP-03",
    sourceRefs: ["SLC-3BET-POTS", "CINJ-E09"],
    situationRu: "Hero открылся, заколлировал 3-бет IP и теперь отвечает на OOP c-bet.",
    situationEn: "Hero opened, called a 3-bet in position, and now responds to an OOP c-bet.",
    mechanismRu: "Позиция улучшает реализацию и сохраняет ветки call/raise. Маленький raise может быть source-supported ответом на over-wide c-bet в подходящем node, но exact exploit frequency и pool tendency не считаются универсальными.",
    mechanismEn: "Position improves realization and preserves call/raise branches. A small raise can be a source-supported response to an over-wide c-bet in suitable nodes, but exact exploit frequency and pool tendency are not universal.",
    exampleRu: "Если OOP 3-беттор слишком широко ставит маленьким размером, игрок в позиции может добавить небольшой рейз частью поляризованного диапазона давления; если взаимодействие доски и диапазонов меняется, тот же приём переносить нельзя.",
    exampleEn: "If the OOP 3-bettor bets a small size with an overly wide range, the IP caller can use a small raise with part of a polar/pressure region; if board/range interaction changes, the shortcut does not automatically transfer.",
    boundaryRu: "Не превращай 'IP caller может raise' в raise любой weak hand и не используй непроверенную population frequency как факт.",
    boundaryEn: "Do not turn 'the IP caller can raise' into raising any weak hand, and do not treat an unvalidated population frequency as fact.",
  }),
  a({
    skillId: "3BP-04",
    sourceRefs: ["CP-G3-L09"],
    situationRu: "Hero заколлировал 3-бет OOP и принимает flop решение против c-bet.",
    situationEn: "Hero called a 3-bet OOP and now makes a flop decision versus a c-bet.",
    mechanismRu: "Сначала оцени EV колла через будущие пути к выигрышу, доминацию и реализацию OOP. Рейз существует только тогда, когда в диапазоне достаточно сильного верха, чтобы поддержать согласованную ветку вэлью и блефов.",
    mechanismEn: "Classify call EV first through future winning routes, domination, and OOP realization. A raise exists only when the range contains enough top-end strength to support a coherent value/bluff branch.",
    exampleRu: "Две визуально похожие unpaired руки могут разойтись: live overcards/backdoors продолжают лучше, dominated или грязные improvement routes — хуже. Небольшой c-bet сам по себе не задаёт одну defence frequency.",
    exampleEn: "Two visually similar unpaired hands can separate sharply: live overcards/backdoors continue better, while dominated or dirty improvement routes continue worse. A small c-bet alone does not define one defense frequency.",
    boundaryRu: "Не overfold и не overraise только из-за OOP; отсутствие credible tier-one value может полностью убрать raise даже при частой защите.",
    boundaryEn: "Do not overfold or overraise merely because Hero is OOP; lacking credible tier-one value can remove raising entirely even when the range defends frequently.",
  }),
  a({
    skillId: "4BP-02",
    sourceRefs: ["CP-G3-L10"],
    situationRu: "4-бет-пот приходит на flop с низким SPR, но конкретные hand families и board relation остаются разными.",
    situationEn: "A 4-bet pot reaches the flop at low SPR, but specific hand families and board relations still differ.",
    mechanismRu: "Низкий SPR сжимает дерево решений, но не делает все руки одинаковыми. Решение всё ещё зависит от соотношения диапазонов, класса руки, доски и ран-аута, а также от риска пуша или повторного рейза.",
    mechanismEn: "Low SPR compresses the tree; it does not make all hands equivalent. The decision still depends on range relation, hand class, board/runout, and jam/reopen exposure.",
    exampleRu: "Та же одна пара может быть уверенной value-hand на благоприятном board и пограничным bluff-catcher на неблагоприятном; одинаковый SPR не фиксирует stack-off.",
    exampleEn: "The same one-pair class can be robust value on a favorable board and a fringe bluff-catcher on an adverse one; identical SPR does not fix a stack-off.",
    boundaryRu: "Не используй '4-бет-пот + низкий SPR' как разрешение автоматически пушить любую top pair/overpair.",
    boundaryEn: "Do not use '4-bet pot + low SPR' as permission to automatically shove any top pair or overpair.",
  }),
  a({
    skillId: "TURN-04",
    sourceRefs: ["SLC-TURN-LEADS"],
    situationRu: "Hero OOP check-call flop; turn меняет взаимодействие сохранённых диапазонов.",
    situationEn: "Hero check-called the flop OOP; the turn changes how the surviving ranges interact.",
    mechanismRu: "Лид на тёрне — условная ветка для определённых ран-аутов, где карта меняет распределение преимущества, позволяет добирать вэлью, не давать бесплатную карту или давить на ослабленный диапазон IP.",
    mechanismEn: "A turn lead is a conditional branch on specific runouts where the card shifts ownership, enables value, denies free cards, or pressures a weak retained IP range.",
    exampleRu: "После колла на флопе низкий тёрн против диапазона c-bet, перегруженного старшими картами, может создать ветку лида; тот же принцип не переносится на нейтральную карту, которая не меняет взаимодействие диапазонов.",
    exampleEn: "After a flop call, a low turn versus a high-card-heavy c-bet range can create a leading branch; the same logic does not transfer to a neutral card that does not change range interaction.",
    boundaryRu: "Не лидь только потому, что конкретная рука героя улучшилась; нужен сдвиг на уровне диапазонов, поддержанный источником.",
    boundaryEn: "Do not lead merely because Hero's exact hand improved; a source-supported range-level shift is required.",
  }),
  a({
    skillId: "TURN-05",
    sourceRefs: ["CP-G3-L02", "FTGU-E21"],
    situationRu: "На тёрне у героя рука средней шоудаун-силы и выбор между тонким вэлью, ставкой для защиты и чеком для контроля банка.",
    situationEn: "On the turn Hero has a medium-strength showdown hand and chooses between a thin/value-protection bet and checking for pot control.",
    mechanismRu: "Сначала назови более слабые руки, которые продолжат, и состояние диапазона соперника. Если ветка колла на флопе капнута на бланковом тёрне, возможен небольшой сайзинг для тонкого вэлью или защиты; если диапазон снова не капнут, руки средней силы чаще сохраняют шоудаун через чек.",
    mechanismEn: "Name worse continues and the opponent's range state first. If the flop-call branch is capped on a blank, a thin/protection size can exist; if the range becomes uncapped, medium hands more often preserve showdown by checking.",
    exampleRu: "Та же рука может ставить против более широкого capped continue range и чекать, когда runout возвращает сопернику сильные value regions.",
    exampleEn: "The same hand can bet versus a wider capped continuing range and check when the runout restores strong value regions to the opponent.",
    boundaryRu: "Не ставь thin value только потому, что Hero 'скорее всего впереди'; ставка должна назвать худшие руки, которые продолжат, и план против raise/river.",
    boundaryEn: "Do not bet thin value merely because Hero is 'probably ahead'; the bet must name worse hands that continue and account for raise/river branches.",
  }),
  a({
    skillId: "DEEP-01",
    sourceRefs: ["LCM-01", "SLC-DEEP-SRP-OOP"],
    situationRu: "200bb эффективной глубины: у героя рука средней силы, и нужно решить, насколько охотно продолжать или разгонять банк через несколько будущих улиц.",
    situationEn: "200bb effective: Hero holds a medium-strength hand and must decide how willingly to continue or inflate the pot across several future streets.",
    mechanismRu: "Глубина увеличивает будущий леверидж и риск обратных имплайд-оддсов. Позиция отдельно меняет реализацию эквити: IP чаще контролирует размер банка и реализует среднюю силу, OOP чаще сталкивается с дорогими решениями на следующих улицах.",
    mechanismEn: "Depth increases future leverage and reverse-implied exposure. Position separately changes equity realization: IP more often controls pot growth and realizes medium strength, while OOP faces more expensive later-street decisions.",
    exampleRu: "Контраст: 2/5, эффективные стеки $1,000 (200bb), на тёрне банк $120 и у Hero одна пара средней силы; позади остаётся около $940. В позиции Hero может чаще сохранить EV через чек вдогонку и последующий колл подходящей ставки. При той же глубине вне позиции те же ранние вложения сильнее открывают сопернику возможность давить крупными ставками на следующих улицах. Прогноз до ответа: после смены IP → OOP требования к устойчивости пограничного продолжения растут; причина — потеря позиции при том же 200bb, а не сама глубина как автоматический повод фолдить.",
    exampleEn: "Worked contrast: the same medium-strength one-pair class at 200bb. IP can preserve EV more often through check-back/call branches; after IP → OOP with depth unchanged, marginal continues and early pot inflation become worse. Predict first: robustness requirements rise because position was lost, not because 200bb automatically means fold.",
    boundaryRu: "Не превращай глубокую игру в универсальное «играть пассивно»: сильные и натсовые руки, а также хорошие позиции всё ещё поддерживают агрессию; меняется цена ошибок и требования к пограничным веткам.",
    boundaryEn: "Do not turn deep play into a universal 'be passive' rule: strong/nutted hands and good position still support aggression; what changes is the cost of errors and the quality required from marginal branches.",
  }),
  a({
    skillId: "RIV-01",
    sourceRefs: ["LCM-09", "CP-G3-L02"],
    situationRu: "River: будущей улицы нет, Hero выбирает check или value bet/size.",
    situationEn: "River: there is no future street, and Hero chooses between checking and a value bet/size.",
    mechanismRu: "Вэлью на ривере определяется диапазоном, который платит выбранный сайзинг. Сначала выдели уровни вэлью и конкретные более слабые коллы; затем выбирай размер. Часто иметь лучшую руку на шоудауне недостаточно.",
    mechanismEn: "River value is defined by the range that pays the chosen sizing. Identify value tiers and concrete worse calls first, then choose the size. Being best at showdown often is not sufficient.",
    exampleRu: "Контраст: 2/5, на ривере банк $300; Hero с A♠Q♣ на A♦9♣6♥3♠2♦ выбирает размер вэлью-ставки. Ставка $90 ещё может получить колл от худших A-J/A-T и части bluff-catcher одной пары, тогда как после ставки $240 этот худший слой может сфолдить и диапазон колла останется заметно сильнее. Прогноз до ответа: если худшие руки действительно исчезают против $240, крупная ставка теряет основание для тонкого вэлью и меньший размер или чек становятся лучше; если те же худшие руки продолжают коллировать $240, граница сдвигается.",
    exampleEn: "Worked contrast: a small river size is still called by several worse one-pair bluff-catchers, but that layer folds to a large size and mainly stronger continues remain. Predict first: the large bet loses its thin-value basis, so a smaller size or check becomes better. If those same worse hands really do call the large size, the boundary changes.",
    boundaryRu: "Не ставь каждую руку, которая, вероятно, лучшая на ривере, и не добавляй блефы до того, как определён вэлью-диапазон и предел разумного вложения.",
    boundaryEn: "Do not bet every likely-best river hand, and do not add bluffs before defining the value region and its investment ceiling.",
  }),
  a({
    skillId: "MW-04",
    sourceRefs: ["FTGU-E03"],
    situationRu: "PF-02 уже дал базовый выбор iso / overlimp / fold. Здесь несколько sticky limpers делают heads-up isolation малореалистичной и повышают шанс настоящего multiway.",
    situationEn: "PF-02 already established the baseline isolate / overlimp / fold choice. Here several sticky limpers make heads-up isolation unlikely and materially raise the chance of a true multiway pot.",
    mechanismRu: "Это перенос навыка, а не повтор PF-02: при низком фолд-эквити и высокой вероятности мультивей-банка сравни цену крупного изолейта с меньшим входным вложением через оверлимп, учитывая типичную силу руки, имплайд-оддсы, позицию и игроков позади.",
    mechanismEn: "This is transfer rather than PF-02 reteaching: with low fold equity and high multiway likelihood, compare the price of a large isolation raise with the smaller entry cost of overlimping, using frequent strength, implied odds, position, and players behind.",
    exampleRu: "Три липких лимпера почти не фолдят на крупный изолейт. Одномастная связная рука или небольшая карманная пара может предпочесть оверлимп, потому что большой размер не покупает хедз-ап банк, а лишь увеличивает вложение в ветку, которая всё равно остаётся мультивей.",
    exampleEn: "Three sticky limpers almost never fold to a large isolation raise. A suited/connected or small-pair hand can prefer overlimping because the larger size does not buy a heads-up pot; it only increases the investment in a branch that still remains multiway.",
    boundaryRu: "Не превращай перенос в новое универсальное правило: при реальном фолд-эквити, достаточной силе руки и хорошей позиции изолейт снова может стать лучшей веткой.",
    boundaryEn: "Do not turn the transfer into a new universal rule: with real fold equity, strong frequent strength, and favorable position, isolation can again become the better branch.",
  }),
  a({
    skillId: "MW-05",
    sourceRefs: ["SLC-MULTIWAY", "EXT-PS-MULTIWAY-2026", "EXT-PS-RIVER-2025"],
    situationRu: "River остаётся multiway или диапазоны дошли туда после сильной фильтрации несколькими участниками.",
    situationEn: "The river remains multiway or the ranges reached it after strong filtering by multiple participants.",
    mechanismRu: "Несколько сохранившихся диапазонов обычно усиливают диапазоны продолжения и уменьшают естественный запас блефов. Вэлью, блеф и блеф-кэтч должны опираться на конкретные более слабые коллы или правдоподобные блефы, а не переносить хедз-ап порог.",
    mechanismEn: "Multiple surviving ranges generally strengthen continuing regions and reduce natural bluff supply. Value, bluff, and bluff-catch decisions should name concrete worse calls or plausible bluffs rather than import heads-up thresholds.",
    exampleRu: "River blocker, который выглядел привлекательным heads-up, может стать плохим bluff-кандидатом multiway, если он не удаляет реальное value или одновременно блокирует редкие bluffs.",
    exampleEn: "A river blocker that looked attractive heads-up can become a poor bluff candidate multiway if it does not remove realistic value or also removes scarce bluffs.",
    boundaryRu: "Не переноси HU thin-value/bluff-catch thresholds без поправки на дополнительный диапазон и предшествующую multiway фильтрацию.",
    boundaryEn: "Do not import heads-up thin-value or bluff-catch thresholds without accounting for the extra range and prior multiway filtering.",
  }),
  a({
    skillId: "DEEP-02",
    sourceRefs: ["EXT-GTOW-DEEP-300-2025", "EXT-UP-SET-MINING-300-2025"],
    situationRu: "300bb cash: физическая глубина увеличивает будущий leverage и цену позиционных/reverse-implied-odds ошибок.",
    situationEn: "At 300bb cash, physical depth increases future leverage and the cost of positional and reverse-implied-odds mistakes.",
    mechanismRu: "По мере роста глубины выше ценятся position и nutted potential, а one-pair commitment и OOP inflation требуют больше осторожности. 100bb action не становится автоматическим 300bb action.",
    mechanismEn: "As depth grows, position and nutted potential gain value while one-pair commitment and OOP pot inflation require more caution. A 100bb action does not automatically remain a 300bb action.",
    exampleRu: "При тех же positions и hand family переход 100bb → 300bb может уменьшить OOP 3-bet incentive и увеличить ценность implied-odds calls; одновременно reverse implied loss становится дороже.",
    exampleEn: "With the same positions and hand family, moving from 100bb to 300bb can reduce OOP 3-bet incentive and increase the value of implied-odds calls while also making reverse-implied losses more expensive.",
    boundaryRu: "Не копируй 100bb stack-off и не считай, что deeper автоматически делает каждую speculative hand лучше.",
    boundaryEn: "Do not copy 100bb stack-off thresholds, and do not assume deeper stacks automatically improve every speculative hand.",
  }),
  a({
    skillId: "DEEP-04",
    sourceRefs: ["FTGU-E04", "SLC-PREFLOP-ADJUSTMENTS"],
    situationRu: "То же семейство префлоп-рук играется глубже, и после текущего действия остаётся существенно больше стека на будущие улицы.",
    situationEn: "The same preflop hand family is played deeper, leaving materially more future stack after the current action.",
    mechanismRu: "Глубина усиливает разницу между nutted/implied-odds potential и domination/reverse implied odds. Префлоп-конструкция поэтому меняется: больше качественных flats/calls, более выборочный stack-off и выше требования к OOP разгонам банка.",
    mechanismEn: "Depth amplifies the difference between nutted/implied-odds potential and domination/reverse implied odds. Preflop construction therefore changes: more quality flats/calls, more selective stack-offs, and higher standards for inflating pots OOP.",
    exampleRu: "Одномастная связная рука в позиции может выиграть от дополнительного будущего стека, тогда как доминируемый разномастный бродвей может потерять EV из-за дорогих веток со второй по силе парой.",
    exampleEn: "A suited connected hand in position can gain from additional future stack, while a dominated offsuit broadway can lose EV through expensive second-best-pair branches.",
    boundaryRu: "Не применяй одну и ту же preflop matrix к 100bb и 300bb и не утверждай точные частоты там, где source visuals их не подтверждают.",
    boundaryEn: "Do not apply one preflop matrix unchanged at 100bb and 300bb, and do not claim exact frequencies where source visuals do not support them.",
  }),
  a({
    skillId: "EXP-02",
    sourceRefs: ["CINJ-E08", "LCM-10"],
    situationRu: "Повторяющиеся наблюдения в одной и той же ветке показывают, что соперник продолжает слишком широко против определённого вэлью-сайзинга.",
    situationEn: "Repeated branch-specific observations show that the opponent continues too widely versus a particular value sizing.",
    mechanismRu: "Вэлью-эксплойт расширяется только там, где подтверждены коллы более слабых рук. Сначала назови диапазон продолжения и цену; масштаб отклонения растёт вместе с качеством данных, а не с ярлыком «станция».",
    mechanismEn: "Exploit value widens only where there are evidenced worse calls. Name the continuing range and price first; the size of the deviation grows with evidence quality, not with a 'station' label.",
    exampleRu: "Если соперник повторяемо платит small river probe слишком широко, thin value может расшириться; если новые наблюдения показывают folds на larger size, это не лицензия переносить exploit на крупный bet.",
    exampleEn: "If an opponent repeatedly pays a small river probe too widely, thin value can expand; if new observations show folds versus larger sizing, that does not license transferring the exploit to a large bet.",
    boundaryRu: "Один light call не доказывает глобальную tendency; не value-bet каждую marginal hand и не переносись между streets/sizes без evidence.",
    boundaryEn: "One light call does not prove a global tendency; do not value-bet every marginal hand or transfer the read across streets and sizes without evidence.",
  }),
  a({
    skillId: "EXP-06",
    sourceRefs: ["EXT-PC-GAMESEL-2025", "EXT-CP-SEATSEL-2014"],
    situationRu: "До или во время live cash session Hero может выбрать стол и место, меняя attainable hourly EV ещё до конкретной раздачи.",
    situationEn: "Before or during a live cash session, Hero can choose a table and seat, changing attainable hourly EV before any specific hand.",
    mechanismRu: "Game/seat selection оценивает качество и стиль соперников, относительную позицию против сильных/aggressive игроков и устойчивость игры. Большие стеки или внешние стереотипы сами по себе не доказывают лучший стол.",
    mechanismEn: "Game and seat selection evaluates opponent quality/style, relative position versus strong/aggressive players, and game sustainability. Big stacks or superficial stereotypes do not by themselves prove a better game.",
    exampleRu: "При одинаковых stakes стол с несколькими слабыми/passive игроками и удобной позицией может иметь выше hourly EV, чем стол с большими stacks, но преимущественно сильными aggressive players.",
    exampleEn: "At the same stakes, a table with several weak/passive players and favorable relative position can have higher hourly EV than a table with big stacks but mostly strong aggressive players.",
    boundaryRu: "Не путай table/seat EV с EV отдельной руки и не делай жёсткий вывод о качестве игры из одного stack size, внешности или одной раздачи.",
    boundaryEn: "Do not confuse table/seat EV with the EV of one hand, and do not infer game quality from one stack size, appearance, or single hand.",
  }),
];

export const practicalSourceBoundTeachingAssetBySkillId = new Map(
  practicalSourceBoundTeachingAssets.map((asset) => [asset.skillId, asset]),
);
