import type { PracticalDecision, PracticalDecisionOption } from "./types";

const FINAL_RU_POLISH = new Map<string, string>([
  ["Небольшой открытие + широкий диапазон + закрытие торгов.", "Небольшое открытие + широкий диапазон + закрытие торгов."],
  ["Небольшой открытие, широкий диапазон поздней позиции, BB закрывает торги.", "Небольшое открытие, широкий диапазон поздней позиции, BB закрывает торги."],
  ["Это явные благоприятные условия защиты BB из.", "Это явные благоприятные условия для защиты BB."],
  ["Кандидат на изменение игры / снятие верхнего ограничения диапазона диапазона", "Кандидат на изменение игры / снятие верхнего ограничения диапазона"],
  ["Какой вывод о required equity верный?", "Какой вывод о требуемой equity верный?"],
  ["Required equity не зависит от цены", "Требуемая equity не зависит от цены"],
  ["Future action не важен", "Будущие решения не важны"],
  ["После решения почти не остаётся future action.", "После решения почти не остаётся будущих действий."],
  ["Больше hands могут остаться viable", "Больше рук могут оставаться прибыльными"],
  ["Меньше hands viable", "Меньше рук остаются прибыльными"],
  ["Какой practical flop branch поддерживает source?", "Какую практическую линию на флопе подтверждает материал?"],
  ["Какое simplification source считает практичным?", "Какое упрощение материал считает практичным?"],
  ["Какой defensive default source предпочитает при uncertainty?", "Какую базовую защитную линию материал предлагает при неопределённости?"],
  ["Как source двигает raise/call mix?", "Как материал меняет соотношение рейзов и коллов?"],
  ["Какой exploit source поддерживает?", "Какой эксплойт подтверждает материал?"],
  ["Какой direction supported?", "Какое направление изменения обосновано?"],
  ["Какая structure source предпочитает?", "Какую структуру предпочитает материал?"],
  ["Что говорит source?", "Что говорит исходный материал?"],
  ["Что learner должен назвать кроме карт?", "Что игрок должен назвать кроме карт?"],
  ["Отказаться от universal shortcut и вернуться к source assumptions", "Отказаться от универсального упрощения и вернуться к исходным допущениям"],
  ["Отказаться от universal rule и вернуться к source-scoped mechanism", "Отказаться от универсального правила и вернуться к механизму из исходного материала"],
  ["Использовать source-scoped rule и проверить relevant range/price/context", "Использовать правило из исходного материала и проверить релевантные диапазон, цену и контекст"],
  ["What changes?", "Что меняется?"],
  ["Only pot odds", "Только pot odds"],
  ["No change", "Без изменений"],
  ["Fold more", "Фолдить чаще"],
  ["Calls only", "Только коллы"],
  ["4-bets only", "Только 4-беты"],
  ["Set is guaranteed", "Сет гарантирован"],
  ["Straddle never changes SPR", "Страддл никогда не меняет SPR"],
  ["Polar by definition", "Полярный по определению"],
  ["Always 4-bet bluff more", "Всегда чаще 4-бетить в блеф"],
  ["Hero becomes IP", "Hero становится IP"],
  ["Still value by definition", "По определению это всё ещё вэлью"],
  ["Yes, if suited", "Да, если рука одномастная"],
  ["Same bluff as HU", "Тот же блеф, что и heads-up"],
  ["Showdown equity is unrelated to all-in EV", "Showdown equity неотделима от EV олл-ина"],
]);

const FINAL_RU_PHRASE_POLISH: ReadonlyArray<readonly [RegExp, string]> = [
  [/небольшой открытие/giu, "небольшое открытие"],
  [/преимущество диапазона сконцентрирован(?![А-Яа-яЁё])/giu, "преимущество диапазона сконцентрировано"],
  [/концентрированный преимущество/giu, "сконцентрированное преимущество"],
  [/расширение диапазон(?![А-Яа-яЁё])/giu, "расширение диапазона"],
  [/визуальный упрощённое правило/giu, "визуальное упрощённое правило"],
  [/обычного холодный коллер/giu, "обычного холодного коллера"],
  [/часть коллы/giu, "часть коллов"],
  [/лишение эквити equity BB/giu, "лишение equity BB"],
  [/с избыточный фолд/giu, "с избыточными фолдами"],
  [/больший стек-к-банк отношение/giu, "большее отношение стека к банку"],
  [/реализации одномастный коннекторы/giu, "реализации одномастных коннекторов"],
  [/реализацию одномастный коннекторы/giu, "реализацию одномастных коннекторов"],
  [/позиция рейзер(?![А-Яа-яЁё])/giu, "позиция рейзера"],
  [/больше слабых сохранившиеся комбинации/giu, "больше слабых сохранившихся комбинаций"],
  [/избирательный доски требуют/giu, "избирательные доски требуют"],
  [/убирают слабые кандидаты(?![А-Яа-яЁё])/giu, "убирают слабых кандидатов"],
  [/конкретными ран-ауты(?![А-Яа-яЁё])/giu, "конкретными ран-аутами"],

  [/\bmarginal hand\b/giu, "пограничная рука"],
  [/\bfuture action\b/giu, "будущие решения"],
  [/\bsource assumptions\b/giu, "исходные допущения"],
  [/\bother assumptions\b/giu, "остальные допущения"],
  [/\bassumptions\b/giu, "допущения"],
  [/\bsource-supported\b/giu, "подтверждённый материалом"],
  [/\bsource-scoped\b/giu, "ограниченный рамками материала"],
  [/\bsource example\b/giu, "пример из материала"],
  [/\bsource\b/giu, "материал"],
  [/\bsupported\b/giu, "обосновано"],
  [/\bevidence\b/giu, "подтверждение"],
  [/\blearner\b/giu, "игрок"],
  [/\bauthoring\b/giu, "редакторский текст"],
  [/\bgovernance\b/giu, "контроль публикации"],
  [/\bfingerprint\b/giu, "контрольная подпись"],
  [/\bviable region\b/giu, "рабочую область"],
  [/\bviable\b/giu, "жизнеспособны"],

  [/\brequired equity\b/giu, "требуемая equity"],
  [/\braw equity\b/giu, "исходная equity"],
  [/\braw out count\b/giu, "простой подсчёт аутов"],
  [/\bpostflop execution\b/giu, "качество постфлоп-игры"],
  [/\bcombo counts\b/giu, "число комбинаций"],
  [/\bcounts\b/giu, "количества"],
  [/\bboard\/action changes\b/giu, "изменений борда и действий"],
  [/\bwhen called\b/giu, "после колла соперника"],
  [/\blarger bets\b/giu, "крупные ставки"],
  [/\bjustify more folds\b/giu, "требуют больше фолдов"],
  [/\bballpark baseline\b/giu, "ориентир"],
  [/\bunconditional law\b/giu, "безусловное правило"],
  [/\buniversal shortcut\b/giu, "универсальное упрощение"],
  [/\buniversal rule\b/giu, "универсальное правило"],
  [/\bpractical simplification\b/giu, "практическое упрощение"],
  [/\bsimplification\b/giu, "упрощение"],
  [/\bdefensive default\b/giu, "базовая защитная линия"],
  [/\bdefault\b/giu, "базовая линия"],
  [/\buncertainty\b/giu, "неопределённости"],
  [/\bdirection\b/giu, "направление"],
  [/\bstructure\b/giu, "структура"],
  [/\bmechanism\b/giu, "механизм"],
  [/\bcontext\b/giu, "контекст"],
  [/\blabel\b/giu, "ярлык"],
  [/\bbranch\b/giu, "ветка"],
  [/\bbranches\b/giu, "ветки"],
  [/\bfuture\b/giu, "будущий"],
  [/\baction\b/giu, "действие"],

  [/\bthe\b\s*/giu, ""],
  [/\ban?\b\s*/giu, ""],
  [/\band\b/giu, "и"],
  [/\bor\b/giu, "или"],
  [/\bwith\b/giu, "с"],
  [/\bwithout\b/giu, "без"],
  [/\bagainst\b/giu, "против"],
  [/\bfrom\b/giu, "из"],
  [/\bto\b/giu, "к"],
  [/\bof\b/giu, "для"],
  [/\bif\b/giu, "если"],
  [/\bwill\b/giu, "будет"],
  [/\bhave\b/giu, "иметь"],
  [/\bhas\b/giu, "имеет"],
  [/\bis\b/giu, "—"],
  [/\bare\b/giu, "—"],
  [/\bdoes not\b/giu, "не"],
  [/\bnot\b/giu, "не"],
  [/\bthan\b/giu, "чем"],
  [/\bwhen\b/giu, "когда"],
  [/\bwhere\b/giu, "где"],
  [/\bwhile\b/giu, "пока"],
  [/\bbecause\b/giu, "потому что"],
  [/\bbut\b/giu, "но"],
  [/\bby\b/giu, "через"],
  [/\bfor\b/giu, "для"],
  [/\binto\b/giu, "в"],
  [/\bafter\b/giu, "после"],
  [/\bbefore\b/giu, "до"],
  [/\bsame\b/giu, "тот же"],
  [/\bmore\b/giu, "больше"],
  [/\bless\b/giu, "меньше"],
  [/\bonly\b/giu, "только"],
  [/\bcan\b/giu, "может"],
  [/\bmust\b/giu, "должен"],
  [/\bshould\b/giu, "следует"],
  [/\bbecomes\b/giu, "становится"],
  [/\bremains?\b/giu, "остаётся"],
  [/\bchanges?\b/giu, "изменяется"],
  [/\bincreases\b/giu, "увеличивает"],
  [/\bdecreases\b/giu, "уменьшает"],
  [/\bbe\b/giu, "быть"],
];

function preserveInitialCase(match: string, replacement: string): string {
  if (!/^[А-ЯЁ]/u.test(match)) return replacement;
  return `${replacement.charAt(0).toLocaleUpperCase("ru-RU")}${replacement.slice(1)}`;
}

function polishRu(text: string): string {
  let polished = FINAL_RU_POLISH.get(text) ?? text;
  for (const [pattern, replacement] of FINAL_RU_PHRASE_POLISH) {
    polished = polished.replace(pattern, (match) => preserveInitialCase(match, replacement));
  }
  return polished.replace(/\s{2,}/gu, " ").replace(/\s+([,.;!?])/gu, "$1").trim();
}

function polishOption(option: PracticalDecisionOption): PracticalDecisionOption {
  return { ...option, textRu: polishRu(option.textRu) };
}

export function applyPracticalRuFinalPolish(decision: PracticalDecision): PracticalDecision {
  return {
    ...decision,
    cueRu: polishRu(decision.cueRu),
    questionRu: polishRu(decision.questionRu),
    explanationRu: polishRu(decision.explanationRu),
    actionOptions: decision.actionOptions.map(polishOption),
    reasonOptions: decision.reasonOptions.map(polishOption),
  };
}
