// V7 post-blind learner-facing Russian naturalness closure.
// Presentation-only: this normalizer is applied only to RU learner copy.
// Poker identity, answers, scoring, IDs, source refs and English copy are untouched.

const PHRASE_REPAIRS: ReadonlyArray<readonly [RegExp, string]> = [
  [/\bfuture action\b/giu, "будущие решения"],
  [/\bfuture decisions\b/giu, "будущие решения"],
  [/\bcurrent price\/sizing materially changes\b/giu, "цена или сайзинг существенно меняются"],
  [/\bopponent\/range\/depth evidence becomes materially different\b/giu, "данные об оппоненте, диапазоне или глубине существенно меняются"],
  [/\bopponent\/range\/depth evidence становится materially different\b/giu, "данные об оппоненте, диапазоне или глубине существенно меняются"],
  [/\bsame player, different street\/size\/line\b/giu, "тот же игрок, но другая улица, сайзинг или линия"],
  [/\bsame player, но new evidence contradicts прежний read в том же branch\b/giu, "тот же игрок, но новые наблюдения противоречат прежнему риду в той же ветке"],
  [/\bsource-supported\b/giu, "обоснованные разбором"],
  [/\bsource-scoped mechanism\b/giu, "механизму, применимому в этих условиях"],
  [/\bsource-scoped rule\b/giu, "правило, применимое в этих условиях"],
  [/\bsource assumptions\b/giu, "условиям исходной модели"],
  [/\bsource claim\b/giu, "наблюдение из материала"],
  [/\bsource boundary\b/giu, "ограничение правила"],
  [/\bsource example\b/giu, "пример"],
  [/\bsource population claim\b/giu, "наблюдение о поле"],
  [/\bsource population\b/giu, "поле"],
  [/\bsource directly\b/giu, "разбор прямо"],
  [/\bsource прямо\b/giu, "разбор прямо"],
  [/\bsource предлагает\b/giu, "разбор предлагает"],
  [/\bsource определяет\b/giu, "разбор определяет"],
  [/\bsource связывает\b/giu, "разбор связывает"],
  [/\bsource сдвигается\b/giu, "базовая модель сдвигается"],
  [/\bsource поддерживает\b/giu, "разбор обосновывает"],
  [/\bsource считает\b/giu, "разбор считает"],
  [/\bчто говорит source\?/giu, "Что следует из этого разбора?"],
  [/\bкакой exploit source поддерживает\?/giu, "Какой эксплойт здесь обоснован?"],
  [/\bкакой exploit source поддерживает/giu, "какой эксплойт здесь обоснован"],
  [/\bкакой source boundary важен\?/giu, "Какое ограничение этого правила важно?"],
  [/\bкакой practical treatment поддерживает source\?/giu, "Какой практический подход здесь обоснован?"],
  [/\bкакой набор benefits соответствует source\?/giu, "Какой набор преимуществ соответствует разбору?"],
  [/\bкакая structure source предпочитает\?/giu, "Какая структура здесь предпочтительнее?"],
  [/\bкак source двигает raise\/call mix\?/giu, "Как меняется соотношение рейзов и коллов?"],
  [/\bкакой defensive default source предпочитает при uncertainty\?/giu, "Какая защитная базовая линия предпочтительнее при неопределённости?"],
  [/\bкакой practical flop branch поддерживает source\?/giu, "Какая практическая линия на флопе здесь подходит?"],
  [/\bкакое simplification source считает практичным\?/giu, "Какое упрощение здесь практично?"],
  [/\bкакой simplified flop plan source поддерживает при большом concentrated advantage\?/giu, "Какой упрощённый план на флопе подходит при большом сконцентрированном преимуществе?"],
  [/\bкакой practical simplification source предлагает для многих favourable\/neutral low-SPR 4-bet flops\?/giu, "Какое практическое упрощение подходит для многих благоприятных и нейтральных флопов 4-бет-банка с низким SPR?"],
  [/\bкак source меняет OOP response против larger c-bet deep\?/giu, "Как меняется OOP-стратегия против крупного c-bet на глубине?"],
  [/\bкакой exploit source поддерживает, если natural bluff supply почти исчез\?/giu, "Какой эксплойт оправдан, если естественных блефов почти не осталось?"],
  [/\bкакой exploit source поддерживает против реально overbluffed air-rich branch\?/giu, "Какой эксплойт оправдан против ветки с избытком блефов?"],
  [/\bможно ли превратить source claim ['“«]?люди часто overfold small river probes['”»]? в универсальный live rule\?/giu, "Можно ли превратить наблюдение «игроки часто оверфолдят маленькие проб-беты на ривере» в универсальное правило для лайва?"],
  [/\bsource\b/giu, "разбор"],
  [/\bevidence\b/giu, "наблюдения"],
  [/\blearner\b/giu, "игрок"],
  [/\bassumptions?\b/giu, "исходные условия"],
  [/\bmaterial change\b/giu, "существенное изменение"],
  [/\bsnapshots?\b/giu, "состояниями"],
  [/\bstrategic depth\b/giu, "стратегическая глубина"],
  [/\bwhen called\b/giu, "после колла"],
  [/\bbefore flop\b/giu, "до флопа"],
  [/\bafter the call\b/giu, "после колла"],
  [/\bfrom hand start\b/giu, "с начала раздачи"],
  [/\bversus larger bets call more and raise less\b/giu, "против более крупных ставок чаще коллировать и реже рейзить"],
  [/\blarger bets и OOP justify more folds\b/giu, "крупные ставки и OOP оправдывают больше фолдов"],
  [/\blarger bets\b/giu, "крупные ставки"],
  [/\bjustify more folds\b/giu, "оправдывают больше фолдов"],
  [/\bballpark baseline\b/giu, "приблизительный ориентир"],
  [/\bcalling range tighter\/condensed\b/giu, "диапазон колла уже и плотнее"],
  [/\bstronger continues than BB\b/giu, "сильнее продолжения, чем у BB"],
  [/\braise for value\b/giu, "вэлью-рейз"],
  [/\bbetting range\b/giu, "диапазон ставки"],
  [/\bexact source quarter-pot size\b/giu, "точный сайзинг в четверть банка"],
  [/\bremaining stack relative to pot\b/giu, "отношение оставшегося стека к банку"],
  [/\bstack-to-pot ratio\b/giu, "SPR"],
  [/\bstack-to-pot geometry\b/giu, "геометрия стека и банка"],
  [/\bcall-only simplification\b/giu, "упрощение без рейзов"],
  [/\bcall-only response strategy\b/giu, "стратегию без рейзов"],
  [/\bcall-only response\b/giu, "ответ без рейзов"],
  [/\bcall-only concept\b/giu, "идею игры без рейзов"],
  [/\bcall-only\b/giu, "без рейзов"],
  [/\brebuild ranges and become more selective\b/giu, "пересчитать диапазоны и играть избирательнее"],
  [/\bcheck-call\/check-jam\b/giu, "чек-колл и чек-пуш"],
  [/\bcredible\b/giu, "реалистичными"],
  [/\bprice-only EV\b/giu, "EV, рассчитанный только по цене"],
  [/\blosing-most-runouts call\b/giu, "колл, который проигрывает на большинстве ран-аутов"],
  [/\bprofitable\b/giu, "плюсовым"],
  [/\brequired equity\b/giu, "необходимая equity"],
  [/\bopposing range\b/giu, "диапазона оппонента"],
  [/\braw equity\b/giu, "сырая equity"],
  [/\bsurrendered\b/giu, "не реализоваться"],
  [/\bdivergence equity\/EV\b/giu, "расхождение equity и EV"],
  [/\bmarginal calls\b/giu, "пограничные коллы"],
  [/\bmarginal hand\b/giu, "пограничная рука"],
  [/\bability to execute postflop\b/giu, "качества постфлоп-реализации"],
  [/\bnominal price\b/giu, "номинальной цены"],
  [/\bcurrent investment versus potential future return\b/giu, "текущие вложения и потенциальный будущий выигрыш"],
  [/\bpotential future return\b/giu, "потенциальный будущий выигрыш"],
  [/\bfuture tree\b/giu, "дерево будущих решений"],
  [/\bpayout\b/giu, "выигрыш"],
  [/\bleverage\/decision depth\b/giu, "давление будущих ставок и глубину дерева решений"],
  [/\bleverage\b/giu, "давление будущих ставок"],
  [/\boperational\b/giu, "применимой на практике"],
  [/\bmore 3-bet pressure\b/giu, "большее давление 3-бетов"],
  [/\bEV fringe\b/giu, "EV пограничных рук"],
  [/\bdefence architecture\b/giu, "структуру защиты"],
  [/\bmore players\b/giu, "больше игроков"],
  [/\bpair EV\b/giu, "EV пары"],
  [/\bpreflop reason for call\b/giu, "причина колла префлоп"],
  [/\bsmall BTN open\b/giu, "небольшого открытия BTN"],
  [/\bstructural benefits\b/giu, "структурные преимущества"],
  [/\bunconditional law\b/giu, "абсолютное правило"],
  [/\bconditional flats\b/giu, "коллы при определённых условиях"],
  [/\bweak\/passive BB\b/giu, "слабого или пассивного BB"],
  [/\bliteral prohibition\b/giu, "буквальный запрет"],
  [/\btable-behind incentives\b/giu, "стимулов игроков позади"],
  [/\bsuited wheel aces?\b/giu, "одномастные тузы с низким кикером"],
  [/\bsuitedness\b/giu, "одномастность"],
  [/\bplayability\b/giu, "играбельность"],
  [/\bplayable\b/giu, "играбельной"],
  [/\bhand class\b/giu, "класс рук"],
  [/\bremoval\b/giu, "эффект блокеров"],
  [/\bpractical treatment\b/giu, "практический подход"],
  [/\bpolar bluff\b/giu, "полярный блеф"],
  [/\boverall losing\b/giu, "минусовым в целом"],
  [/\bjam-or-fold\b/giu, "пуш или фолд"],
  [/\bvalue-heavy\/linear response\b/giu, "более вэлью-ориентированный и линейный ответ"],
  [/\btighter stack-offs\b/giu, "более тайтовые выставления"],
  [/\bunderbluffing ranges\b/giu, "диапазоны с недоблефом"],
  [/\bbluff-only candidates\b/giu, "кандидаты, годные только для блефа"],
  [/\bblocker-only squeeze bluff\b/giu, "сквиз-блеф, основанный только на блокере"],
  [/\bequity realisation\b/giu, "реализация equity"],
  [/\bposition when called\b/giu, "позицию после колла"],
  [/\bdead money\b/giu, "мёртвых денег"],
  [/\bsits between EP and BTN in origin strength\b/giu, "обычно находится между EP и BTN по силе исходного диапазона"],
  [/\bframework\b/giu, "модель"],
  [/\bposition a gradual range-strength variable, not binary early\/late\b/giu, "позицию как постепенную переменную силы диапазона, а не бинарное деление на раннюю и позднюю"],
  [/\blabel is enough\b/giu, "названия позиции достаточно"],
  [/\bfringe compared with a much larger open\b/giu, "пограничным рукам по сравнению с намного более крупным открытием"],
  [/\bviable region\b/giu, "зону допустимых продолжений"],
  [/\bcan remain viable\b/giu, "могут оставаться допустимыми"],
  [/\bhands viable\b/giu, "рук остаются допустимыми"],
  [/\bopen size\b/giu, "размер открытия"],
  [/\bbut origin range\b/giu, "но исходный диапазон"],
  [/\bbecause BB closes action\b/giu, "потому что BB закрывает торги"],
  [/\bhand блокирует часть strong continues\b/giu, "рука блокирует часть сильных продолжений"],
  [/\bstarting BB count same\b/giu, "исходное число BB то же"],
  [/\bnominal depth is enough\b/giu, "номинальной глубины достаточно"],
  [/\bblind seat label is enough\b/giu, "названия позиции на блайнде достаточно"],
  [/\bconnectivity and range fit matter\b/giu, "важны связность доски и соответствие диапазонов"],
  [/\blow is one class\b/giu, "все низкие доски — один класс"],
  [/\bcap must be reassessed\b/giu, "верхнюю границу диапазона нужно пересчитать"],
  [/\bmore selective \/ less automatic\b/giu, "избирательнее и менее автоматически"],
  [/\bcallers are always capped\b/giu, "коллеры всегда ограничены сверху"],
  [/\btraits split the family\b/giu, "свойства разделяют это семейство"],
  [/\bsame pair means same decision\b/giu, "та же пара означает то же решение"],
  [/\bsame ranges\b/giu, "те же диапазоны"],
  [/\bsame board\b/giu, "та же доска"],
  [/\bsame hand\/ranges\b/giu, "та же рука и диапазоны"],
  [/\bsame hand\/size\b/giu, "та же рука и сайзинг"],
  [/\bsame value hand\b/giu, "та же вэлью-рука"],
  [/\bsame Hero hand\b/giu, "та же рука Hero"],
  [/\bsame small size\b/giu, "тот же небольшой сайзинг"],
  [/\bcaller-friendly low\/wet\b/giu, "низкой динамичной доски, удобной коллеру"],
  [/\bdry high-card\b/giu, "сухую высокую доску"],
  [/\bcondensed\/strong\b/giu, "более плотным и сильным"],
  [/\brange check OOP\b/giu, "чек всем диапазоном OOP"],
  [/\ball flops\b/giu, "всех флопах"],
  [/\bbet size\b/giu, "сайзинг ставки"],
  [/\bsmall → large\b/giu, "малый → крупный"],
  [/\bdynamic\b/giu, "динамичной"],
  [/\bstability\b/giu, "устойчивость"],
  [/\braises\b/giu, "рейзы"],
  [/\bcalls\b/giu, "коллы"],
  [/\bfolds\b/giu, "фолды"],
  [/\bbottom-of-range\b/giu, "самой нижней части диапазона"],
  [/\bcandidate должен иметь полезные future properties\b/giu, "кандидат должен иметь полезные свойства на будущих улицах"],
  [/\bagainst continuing range\b/giu, "против диапазона продолжения"],
  [/\bdry\/static → wet\/dynamic\b/giu, "сухой статичной на мокрую динамичную"],
  [/\bpolar → merged\b/giu, "полярного на слитый"],
  [/\bprotected call-only structures\b/giu, "защищённые структуры без рейзов"],
  [/\bstrong hands\b/giu, "сильные руки"],
  [/\bcall branch\b/giu, "ветке колла"],
  [/\breasonable equity\/realisation\b/giu, "достаточной equity и реализацией"],
  [/\bsmall bet\b/giu, "небольшая ставка"],
  [/\bdefend wider than a large polar sizing\b/giu, "защищаться шире, чем против крупного полярного сайзинга"],
  [/\bsubject to hand quality and range\b/giu, "с учётом качества руки и диапазона"],
  [/\bstrong redraw\/extra stability\b/giu, "сильный редро и дополнительную устойчивость"],
  [/\boverfold к small bet\b/giu, "оверфолдить против небольшой ставки"],
  [/\bbottom всё ещё folds\b/giu, "нижняя часть диапазона всё ещё фолдит"],
  [/\blarge bet = strong range\b/giu, "крупная ставка = сильный диапазон"],
  [/\bbet only made hands\b/giu, "ставить только готовые руки"],
  [/\bvalue \+ bluffs form a narrower betting range\b/giu, "вэлью и блефы формируют более узкий диапазон ставки"],
  [/\bdefender range\b/giu, "диапазон защитника"],
  [/\bconnected low-card region\b/giu, "зону связанных низких карт"],
  [/\bactual ranges unusual\b/giu, "фактические диапазоны необычны"],
  [/\bdefender retains more strong region than normal\b/giu, "у защитника остаётся больше сильных рук, чем обычно"],
  [/\bmedium showdown hand\b/giu, "рука средней силы с шоудаун-вэлью"],
  [/\bbetting gets little value and faces unpleasant raises\b/giu, "ставка получает мало вэлью и сталкивается с неприятными рейзами"],
  [/\bstrong hand\b/giu, "сильная рука"],
  [/\blow-urgency flop\b/giu, "флопе с низкой срочностью защиты"],
  [/\baggressive opponent likely to stab later after check-back\b/giu, "агрессивный оппонент часто поставит позже после чек-бэка"],
  [/\bprotected checking\b/giu, "защищённые чеки"],
  [/\bcheck back\b/giu, "чекать вдогонку"],
  [/\b3-bettor\b/giu, "3-беттор"],
  [/\bdry A-high board\b/giu, "сухая доска с тузом"],
  [/\bpremium\/high-card density\b/giu, "плотность премиальных и старших рук"],
  [/\bdry A-high\b/giu, "сухую доску с тузом"],
  [/\blow connected\b/giu, "низкую связанную"],
  [/\bboard changes только equity, не strategy shape\b/giu, "доска меняет только equity, но не структуру стратегии"],
  [/\b3-bet pot\b/giu, "3-бет-банк"],
  [/\bc-bet heuristics\b/giu, "эвристики c-bet"],
  [/\bOOP node\b/giu, "OOP-узел"],
  [/\bcheck keeps range protected and captures future bets\b/giu, "чек сохраняет защиту диапазона и позволяет получить будущие ставки"],
  [/\bOOP must lead\b/giu, "OOP обязан лидить"],
  [/\baction change\b/giu, "измениться действие"],
  [/\brange shift\b/giu, "сдвиг диапазонов"],
  [/\bscary\/not-scary label\b/giu, "ярлык «опасная/неопасная»"],
  [/\bautomatic barrel\b/giu, "автоматический баррель"],
  [/\buniversal rule\b/giu, "универсального правила"],
  [/\bturn barrel\b/giu, "баррель на тёрне"],
  [/\bflop action\b/giu, "линии на флопе"],
  [/\bblank\b/giu, "бланка"],
  [/\bcap\/nut ownership\b/giu, "верхнюю границу и натсовое преимущество диапазонов"],
  [/\bmedium-strength showdown hand\b/giu, "рука средней силы с шоудаун-вэлью"],
  [/\bbet thin\/value\/protection\b/giu, "тонкая ставка на вэлью или защиту"],
  [/\bcheck-back\/pot-control\b/giu, "чек-бэк или пот-контроль"],
  [/\bhero наблюдает необычную линию\/size\/showdown\b/giu, "Hero замечает необычную линию, сайзинг или шоудаун"],
  [/\bhero считает outs для draw\b/giu, "Hero считает ауты для дро"],
  [/\bopponent stronger hand\b/giu, "более сильную руку оппонента"],
  [/\bshortcut выглядит удобно\b/giu, "упрощённое правило выглядит удобным"],
  [/\brelevant range\/price\/context\b/giu, "нужный диапазон, цену и контекст"],
  [/\bforced raise-or-fold\b/giu, "жёсткое правило «рейз или фолд»"],
  [/\blimp\/raise structure\b/giu, "структуру лимпов и рейзов"],
  [/\bfringe против BB tendencies\b/giu, "пограничные руки против тенденций BB"],
  [/\blive cash session\b/giu, "лайв-кеш сессии"],
  [/\bachievable hourly EV\b/giu, "достижимый EV в час"],
  [/\blive slogan\b/giu, "правило для лайва"],
  [/\bsame turn card\b/giu, "та же карта тёрна"],
  [/\bsame chips\b/giu, "то же число фишек"],
  [/\bhero stack after call\b/giu, "стека Hero после колла"],
  [/\bboard and hole cards\b/giu, "доска и карманные карты"],
  [/\bcombos\b/giu, "комбинации"],
  [/\bboard\/action changes\b/giu, "изменений доски и линии"],
  [/\bcommitment\/leverage\b/giu, "порог готовности вкладываться и давление будущих ставок"],
  [/\b3-bet or fold\b/giu, "3-бет или фолд"],
  [/\b3-bet-or-fold\b/giu, "3-бет или фолд"],
  [/\bSB flats\b/giu, "коллов SB"],
  [/\blinear\b/giu, "линейной"],
  [/\bmedium-strength hand\b/giu, "рука средней силы"],
  [/\bprotected call region\b/giu, "защищённая зона колла"],
  [/\bbluffs\b/giu, "блефы"],
  [/\bequity before flop must enter EV\b/giu, "риск потерять всю equity до флопа нужно учитывать в EV"],
  [/\bsqueeze risk\b/giu, "риск сквиза"],
  [/\brange source\b/giu, "исходный диапазон"],
  [/\barriving-range advantage\b/giu, "преимущество диапазона, пришедшего в узел"],
  [/\bstrategic flips\b/giu, "стратегические развороты"],
  [/\bsame boards\b/giu, "одинаковых досках"],
  [/\braising мало добавляет EV\b/giu, "рейз почти не добавляет EV"],
  [/\bcall everything\b/giu, "коллировать всё"],
  [/\bindiscriminate calling\b/giu, "безразборных коллов"],
  [/\bexploitative overfold\b/giu, "эксплойтный оверфолд"],
  [/\bunderbluffed branch\b/giu, "ветки с недоблефом"],
  [/\bbluff-to-value ratio\b/giu, "соотношение блефов к вэлью"],
  [/\buncontrolled air\b/giu, "лишних пустых рук"],
  [/\bbluff-catch threshold\b/giu, "порог блафкетча"],
  [/\btight bluff categories\b/giu, "более узкие категории блефов"],
  [/\bstrategic shape\b/giu, "структура стратегии"],
  [/\brandom low-equity multiway bluffs\b/giu, "случайные мультивей-блефы с низкой equity"],
  [/\bbackup equity\b/giu, "дополнительная equity"],
  [/\bnutted improvement paths\b/giu, "пути к натсам"],
  [/\bpure-fold potential top pair without backup\b/giu, "возможность чистого фолда топ-пары без дополнительной equity"],
  [/\bstrong multiway sequence\b/giu, "сильной мультивей-линии"],
  [/\bnatural bluff supply\b/giu, "запас естественных блефов"],
  [/\boverfold relative to balanced baseline\b/giu, "оверфолд относительно сбалансированной базы"],
  [/\blarge size\b/giu, "крупного сайзинга"],
  [/\bstructurally airless runouts\b/giu, "ран-ауты, где структурно почти нет блефов"],
  [/\boverbluffed air-rich branch\b/giu, "ветки с избытком блефов"],
  [/\boverfold small river probes\b/giu, "оверфолдят маленькие проб-беты на ривере"],
  [/\buniversal live rule\b/giu, "универсальное правило для лайва"],
];

const WORD_REPAIRS: ReadonlyArray<readonly [RegExp, string]> = [
  [/\bdefault\b/giu, "базовая линия"],
  [/\buncertainty\b/giu, "неопределённости"],
  [/\bsimplification\b/giu, "упрощение"],
  [/\bpractical\b/giu, "практический"],
  [/\bbenefits\b/giu, "преимущества"],
  [/\bdirection\b/giu, "направление"],
  [/\bsupported\b/giu, "обосновано"],
  [/\bopponent\b/giu, "оппонент"],
  [/\bposition\b/giu, "позиция"],
  [/\bboard\b/giu, "доска"],
  [/\bhand\b/giu, "рука"],
  [/\bhands\b/giu, "руки"],
  [/\bturn\b/giu, "тёрн"],
  [/\bflop\b/giu, "флоп"],
  [/\briver\b/giu, "ривер"],
  [/\bshowdown\b/giu, "шоудаун"],
  [/\bblocker\b/giu, "блокер"],
  [/\bblockers\b/giu, "блокеры"],
  [/\bbluff\b/giu, "блеф"],
  [/\bvalue\b/giu, "вэлью"],
  [/\bcall\b/giu, "колл"],
  [/\bfold\b/giu, "фолд"],
  [/\braise\b/giu, "рейз"],
  [/\bbet\b/giu, "ставка"],
  [/\bbranch\b/giu, "ветка"],
  [/\bmechanism\b/giu, "механизм"],
  [/\bcontext\b/giu, "контекст"],
  [/\blabel\b/giu, "ярлык"],
  [/\bsize\b/giu, "сайзинг"],
  [/\bstructure\b/giu, "структура"],
  [/\bresponse\b/giu, "ответ"],
  [/\bstrategy\b/giu, "стратегия"],
  [/\bline\b/giu, "линия"],
  [/\branges\b/giu, "диапазоны"],
  [/\brange\b/giu, "диапазон"],
  [/\bcounts\b/giu, "число комбинаций"],
  [/\bactual\b/giu, "фактические"],
  [/\brelevant\b/giu, "нужные"],
  [/\bviable\b/giu, "допустимы"],
];

export function polishPracticalRuNaturalness(text: string): string {
  let polished = text;
  for (const [pattern, replacement] of PHRASE_REPAIRS) polished = polished.replace(pattern, replacement);
  for (const [pattern, replacement] of WORD_REPAIRS) polished = polished.replace(pattern, replacement);
  return polished
    .replace(/\s{2,}/gu, " ")
    .replace(/\s+([,.;:!?])/gu, "$1")
    .trim();
}
