import type { PracticalRule } from "./mental-model";

export const preflopA3Rules: PracticalRule[] = [
  {
    id: "RULE-PF-SQUEEZE-BRANCH-EV",
    mode: "TRIGGER_RULE",
    triggerFamily: "FOLD_EQUITY",
    skillIds: ["PF-09"],
    sourceRefs: ["SLC-M01-L02", "LCM-02"],
    triggerRu: "Open + caller создают dead money и Hero рассматривает squeeze.",
    triggerEn: "An open plus a caller creates dead money and Hero considers a squeeze.",
    defaultRu: "Сначала проверь реальные folds и качество called/4-bet branches; dead money сами по себе не делают raise прибыльным.",
    defaultEn: "Check real folds and the quality of called/4-bet branches first; dead money alone do not make the raise profitable.",
    whyRu: "Squeeze EV приходит из всей ветки: folds, weaker continues, position, realisation и response opener-а.",
    whyEn: "Squeeze EV comes from the whole tree: folds, worse continues, position, realization and the opener's response.",
    amplifiersRu: ["caller/opener overfold", "Hero IP", "hand хорошо играет when called", "реальный value/isolation edge"],
    amplifiersEn: ["caller/opener overfold", "Hero IP", "hand performs well when called", "real value/isolation edge"],
    reversalsRu: ["sticky caller", "низкий fold equity", "Hero OOP", "candidate плохо играет when called"],
    reversalsEn: ["sticky caller", "low fold equity", "Hero OOP", "candidate performs poorly when called"],
    transferCueRu: "Оставь Hero hand и opener теми же; поменяй только caller overfold → sticky.",
    transferCueEn: "Keep Hero's hand and the opener fixed; change only the caller from overfolding → sticky.",
  },
  {
    id: "RULE-PF-LIVE-GEOMETRY",
    mode: "ENVIRONMENTAL_HABIT",
    triggerFamily: "FORCED_UNIT",
    skillIds: ["PF-10"],
    sourceRefs: ["SLC-M01-L03"],
    triggerRu: "Появился straddle, изменился forced bet или working action order.",
    triggerEn: "A straddle appears, the forced bet changes, or the working action order changes.",
    defaultRu: "До решения переякорь working unit, effective depth и action order; не тащи non-straddled tree по dollar stack.",
    defaultEn: "Before deciding, re-anchor the working unit, effective depth and action order; do not carry over the non-straddled tree from the dollar stack.",
    whyRu: "Те же деньги в стеках могут представлять существенно более короткое или иначе организованное preflop-дерево.",
    whyEn: "The same dollar stacks can represent a materially shorter or differently ordered preflop tree.",
    amplifiersRu: ["mandatory straddle", "large live opens", "несколько forced bets"],
    amplifiersEn: ["mandatory straddle", "large live opens", "multiple forced bets"],
    reversalsRu: ["без изменения forced unit этот re-anchor не нужно проговаривать на каждой раздаче"],
    reversalsEn: ["without a forced-unit change, this re-anchor does not need to be rehearsed every hand"],
    transferCueRu: "Сохрани dollar stack, добавь mandatory straddle и сравни effective depth.",
    transferCueEn: "Keep the dollar stack fixed, add a mandatory straddle, and compare effective depth.",
  },
  {
    id: "RULE-PF-RAKE-FRINGE",
    mode: "TRIGGER_RULE",
    triggerFamily: "OPEN_SIZE",
    skillIds: ["PF-10", "PF-04"],
    sourceRefs: ["FTGU-E02", "FTGU-E05"],
    triggerRu: "Rake materially выше, а решение находится на marginal fringe.",
    triggerEn: "Rake is materially higher and the decision sits on a marginal fringe.",
    defaultRu: "Сначала режь near-zero opens/calls; strong value region меняется меньше.",
    defaultEn: "Trim near-zero opens/calls first; the strong value region changes less.",
    whyRu: "Дополнительный cost первым переворачивает close EV branches.",
    whyEn: "The added cost flips close-EV branches first.",
    amplifiersRu: ["marginal BB call", "fringe RFI", "плохая postflop realisation"],
    amplifiersEn: ["marginal BB call", "fringe RFI", "poor postflop realization"],
    reversalsRu: ["очень сильная value hand не становится fold только потому, что rake выше"],
    reversalsEn: ["a very strong value hand does not become a fold merely because rake is higher"],
    transferCueRu: "Оставь hand/position/sizing теми же; поменяй только low rake → high rake.",
    transferCueEn: "Keep hand/position/sizing fixed; change only low rake → high rake.",
  },
];

export function preflopA3RulesForSkill(skillId: string): PracticalRule[] {
  return preflopA3Rules.filter((rule) => rule.skillIds.includes(skillId));
}
