import type { PracticalRule } from "./mental-model";

export const recognitionA5Rules: PracticalRule[] = [
  {
    id: "RULE-REC-BOARD-RANGES",
    mode: "TRIGGER_RULE",
    triggerFamily: "BOARD_OWNERSHIP",
    skillIds: ["W4-BOARD-01", "W4-REL-01"],
    sourceRefs: ["FTGU-E07"],
    triggerRu: "Flop кажется знакомым по texture label.",
    triggerEn: "The flop looks familiar by its texture label.",
    defaultRu: "Не назначай strategy по названию board; сначала спроси, какие ranges реально пришли сюда и кто сохранил nuts/strong-pair density.",
    defaultEn: "Do not assign strategy from the board label; first ask which ranges actually arrived and who retained the nuts/strong-pair density.",
    whyRu: "Один и тот же board меняет ownership при другой preflop range architecture.",
    whyEn: "The same board changes ownership under a different preflop range architecture.",
    amplifiersRu: ["caller retains two-pair/straight region", "PFR loses overpair advantage", "range source changes"],
    amplifiersEn: ["caller retains two-pair/straight region", "PFR loses overpair advantage", "range source changes"],
    reversalsRu: ["dry high boards against wide BB can preserve concentrated PFR advantage"],
    reversalsEn: ["dry high boards against a wide BB can preserve concentrated PFR advantage"],
    transferCueRu: "Оставь flop тем же и поменяй только arriving ranges.",
    transferCueEn: "Keep the flop fixed and change only the arriving ranges.",
  },
  {
    id: "RULE-REC-COMBO-FAMILY-TRAITS",
    mode: "TRIGGER_RULE",
    triggerFamily: "BOARD_OWNERSHIP",
    skillIds: ["W4-HAND-01", "W4-REL-01"],
    sourceRefs: ["FINAL_LEARNING_INTEGRITY"],
    triggerRu: "Показана конкретная Hero hand и возникает желание запомнить ответ именно для неё.",
    triggerEn: "A concrete Hero hand is shown and there is a temptation to memorize the answer for that exact combo.",
    defaultRu: "Сожми hand в family + traits: relative strength, vulnerability, redraws, blockers; затем снова применяй context.",
    defaultEn: "Compress the hand into family plus traits: relative strength, vulnerability, redraws, blockers; then reapply context.",
    whyRu: "Exact-combo memory плохо переносится; family representation полезна только если сохраняет признаки, которые двигают решение.",
    whyEn: "Exact-combo memory transfers poorly; a family representation is useful only if it preserves the traits that move the decision.",
    amplifiersRu: ["same family across several combos", "changed board vulnerability", "changed opponent range"],
    amplifiersEn: ["same family across several combos", "changed board vulnerability", "changed opponent range"],
    reversalsRu: ["если blocker/redraw materially меняется, две внешне похожие hands не обязаны иметь одну practical identity"],
    reversalsEn: ["if a blocker/redraw changes materially, two visually similar hands need not share one practical identity"],
    transferCueRu: "Дай non-identical combo той же family и измени только один trait.",
    transferCueEn: "Use a non-identical combo from the same family and change only one trait.",
  },
  {
    id: "RULE-REC-RUNOUT-ANCESTRY",
    mode: "TRIGGER_RULE",
    triggerFamily: "RUNOUT_SHIFT",
    skillIds: ["W4-RUNOUT-01"],
    sourceRefs: ["FTGU-E20", "FTGU-E21"],
    triggerRu: "Turn выглядит blank/scare/completing card по внешнему виду.",
    triggerEn: "The turn looks like a blank/scare/completing card by appearance.",
    defaultRu: "Перед label вспомни flop branch: какие strong hands ушли через raise/check и какие новая карта возвращает.",
    defaultEn: "Before assigning the label, recall the flop branch: which strong hands left through raise/check and which ones the new card restores.",
    whyRu: "Runout меняет strategy через surviving ranges, а не через название карты само по себе.",
    whyEn: "A runout changes strategy through surviving ranges, not through the card label by itself.",
    amplifiersRu: ["draw completes", "caller was capped by prior action", "check-back removed strong hands"],
    amplifiersEn: ["draw completes", "caller was capped by prior action", "check-back removed strong hands"],
    reversalsRu: ["если prior branch был call-only и сохранял nuts, blank не делает caller автоматически capped"],
    reversalsEn: ["if the prior branch was call-only and retained nuts, a blank does not automatically make the caller capped"],
    transferCueRu: "Оставь flop/action теми же; сравни blank turn и range-restoring turn.",
    transferCueEn: "Keep flop/action fixed; compare a blank turn with a range-restoring turn.",
  },
];

export function recognitionA5RulesForSkill(skillId: string): PracticalRule[] {
  return recognitionA5Rules.filter((rule) => rule.skillIds.includes(skillId));
}
