import type { PracticalRule } from "./mental-model";

export const srpA6Rules: PracticalRule[] = [
  {
    id: "RULE-SRP-OOP-OWNERSHIP-BEFORE-INITIATIVE",
    mode: "TRIGGER_RULE",
    triggerFamily: "BOARD_OWNERSHIP",
    skillIds: ["OOP-01", "IP-01"],
    sourceRefs: ["FTGU-E07", "FTGU-E27"],
    triggerRu: "PFR видит flop и автоматически хочет c-bet из-за initiative.",
    triggerEn: "The PFR sees the flop and automatically wants to c-bet because of initiative.",
    defaultRu: "Сначала оцени board × arriving ranges × position; initiative — не право на bet.",
    defaultEn: "Read board × arriving ranges × position first; initiative is not a license to bet.",
    whyRu: "Caller-friendly/equalising boards и OOP disadvantage могут полностью изменить preferred branch.",
    whyEn: "Caller-friendly/equalizing boards and OOP disadvantage can completely change the preferred branch.",
    amplifiersRu: ["caller retains two-pair/straight density", "PFR OOP", "board neutralises overpairs"],
    amplifiersEn: ["caller retains two-pair/straight density", "PFR OOP", "board neutralizes overpairs"],
    reversalsRu: ["dry high boards with concentrated PFR advantage can support broad small betting"],
    reversalsEn: ["dry high boards with concentrated PFR advantage can support broad small betting"],
    transferCueRu: "Оставь board тем же и поменяй arriving range/role; затем оставь ranges и поменяй board.",
    transferCueEn: "Keep the board fixed and change arriving range/role; then keep ranges fixed and change the board.",
  },
  {
    id: "RULE-SRP-DEFENCE-PRICE-SHAPE",
    mode: "TRIGGER_RULE",
    triggerFamily: "OPEN_SIZE",
    skillIds: ["OOP-02", "OOP-04", "OOP-05"],
    sourceRefs: ["FTGU-E08", "FTGU-E09"],
    triggerRu: "Facing c-bet sizing materially меняется.",
    triggerEn: "The facing c-bet size changes materially.",
    defaultRu: "Small size поддерживает больше marginal continues; large/selective size повышает требования к equity, stability и range fit.",
    defaultEn: "A small size supports more marginal continues; a large/selective size raises requirements for equity, stability and range fit.",
    whyRu: "Price и betting-range shape меняются вместе; одну defence threshold нельзя переносить между sizings.",
    whyEn: "Price and betting-range shape change together; one defense threshold cannot be copied across sizings.",
    amplifiersRu: ["fragile hand", "poor future realisation", "polar betting range"],
    amplifiersEn: ["fragile hand", "poor future realization", "polar betting range"],
    reversalsRu: ["credible overbluff evidence can widen bluff-catch continues even versus large size"],
    reversalsEn: ["credible overbluff evidence can widen bluff-catching continues even versus a large size"],
    transferCueRu: "Оставь hand/board/ranges; поменяй только small → large sizing.",
    transferCueEn: "Keep hand/board/ranges fixed; change only small → large sizing.",
  },
  {
    id: "RULE-SRP-RAISE-CONTINUING-RANGE",
    mode: "TRIGGER_RULE",
    triggerFamily: "RANGE_CAP",
    skillIds: ["OOP-03"],
    sourceRefs: ["FTGU-E09", "FTGU-E10"],
    triggerRu: "Hero думает «моя рука сейчас чаще впереди, значит raise for value».",
    triggerEn: "Hero thinks 'my hand is ahead most often now, therefore raise for value'.",
    defaultRu: "Value raise оценивай против range, который продолжит после raise; urgency/vulnerability определяют, нужно ли ускорять value сейчас.",
    defaultEn: "Judge a value raise versus the range that continues after the raise; urgency/vulnerability determine whether value should be accelerated now.",
    whyRu: "Raise может выбить bluffs и оставить stronger region; absolute ahead-frequency до raise не является value test.",
    whyEn: "A raise can fold out bluffs and leave a stronger region; being ahead before the raise is not the value test.",
    amplifiersRu: ["wet board", "vulnerable value", "worse made hands continue"],
    amplifiersEn: ["wet board", "vulnerable value", "worse made hands continue"],
    reversalsRu: ["low urgency + aggressive opponent can increase value of protected calls"],
    reversalsEn: ["low urgency plus an aggressive opponent can increase the value of protected calls"],
    transferCueRu: "Оставь Hero hand; поменяй opponent betting shape polar → merged.",
    transferCueEn: "Keep Hero's hand fixed; change opponent betting shape polar → merged.",
  },
  {
    id: "RULE-SRP-PROTECTED-CHECK",
    mode: "TRIGGER_RULE",
    triggerFamily: "RANGE_CAP",
    skillIds: ["OOP-01", "OOP-02", "IP-02"],
    sourceRefs: ["FTGU-E08", "FTGU-E27", "CP-G3-L08"],
    triggerRu: "Hero выбирает check и есть риск воспринимать его как surrender.",
    triggerEn: "Hero checks and there is a risk of treating the check as surrender.",
    defaultRu: "Сохраняй strong/stable hands в passive branch там, где urgency низкая; check должен иметь future jobs.",
    defaultEn: "Keep strong/stable hands in the passive branch where urgency is low; the check should retain future jobs.",
    whyRu: "Protected check prevents later nodes from treating check range as automatically capped and can preserve opponent bluffs.",
    whyEn: "A protected check prevents later nodes from treating the checking range as automatically capped and can preserve opponent bluffs.",
    amplifiersRu: ["low urgency", "aggressive opponent", "medium showdown region needs protection"],
    amplifiersEn: ["low urgency", "aggressive opponent", "medium showdown region needs protection"],
    reversalsRu: ["wetness/vulnerability/immediate value can restore betting or raising urgency"],
    reversalsEn: ["wetness/vulnerability/immediate value can restore betting or raising urgency"],
    transferCueRu: "Сохрани hand; поменяй static board → dynamic board и reassess urgency.",
    transferCueEn: "Keep the hand fixed; change static board → dynamic board and reassess urgency.",
  },
];

export function srpA6RulesForSkill(skillId: string): PracticalRule[] {
  return srpA6Rules.filter((rule) => rule.skillIds.includes(skillId));
}
