export type LaterStreetMemoryRule={id:string;triggerRu:string;triggerEn:string;ruleRu:string;ruleEn:string;boundaryRu:string;boundaryEn:string;skillIds:string[];sourceRefs:string[]};

export const laterStreetMemoryRules:LaterStreetMemoryRule[]=[
{id:"A8-RULE-ANCESTRY-FIRST",triggerRu:"Началась новая улица.",triggerEn:"A new street begins.",ruleRu:"Перед action назови: что предыдущая улица удалила из каждой range и что новая карта вернула.",ruleEn:"Before acting, name what the previous street removed from each range and what the new card restored.",boundaryRu:"Street label сам по себе не является strategy.",boundaryEn:"The street label itself is not a strategy.",skillIds:["TURN-01","TURN-02","TURN-03","TURN-04","TURN-05","RIV-01","RIV-02","RIV-03","RIV-04","RIV-05"],sourceRefs:["FTGU-E20","FTGU-E21","FTGU-E22","FTGU-E23"]},
{id:"A8-RULE-TURN-IS-RANGE-SHIFT",triggerRu:"Turn выглядит scary/blank.",triggerEn:"The turn looks scary/blank.",ruleRu:"Не называй карту scary/blank по виду: проверь, меняет ли она nut/strong regions конкретных surviving ranges.",ruleEn:"Do not call the card scary/blank by appearance: check whether it changes the nut/strong regions of the surviving ranges.",boundaryRu:"Overcard не означает automatic barrel.",boundaryEn:"An overcard does not mean an automatic barrel.",skillIds:["TURN-01","TURN-02","TURN-03","TURN-04"],sourceRefs:["FTGU-E20","FTGU-E21"]},
{id:"A8-RULE-THIN-VALUE-NAMES-WORSE",triggerRu:"Хочется thin value bet.",triggerEn:"Considering a thin value bet.",ruleRu:"До ставки назови хуже руки, которые платят этот sizing. Не можешь назвать — value case не доказан.",ruleEn:"Before betting, name worse hands that call this sizing. If you cannot, the value case is unproven.",boundaryRu:"Being probably ahead is not enough for value.",boundaryEn:"Being probably ahead is not enough for value.",skillIds:["TURN-05","RIV-01"],sourceRefs:["CP-G3-L02","LCM-09"]},
{id:"A8-RULE-RIVER-BLUFF-SUPPLY",triggerRu:"River bluff-catch.",triggerEn:"River bluff-catch.",ruleRu:"Price отвечает только на «сколько bluffs нужно». Затем отдельно посчитай, какие bluffs реально дошли сюда.",ruleEn:"Price answers only 'how many bluffs are needed'. Then separately ask which bluffs actually reached this node.",boundaryRu:"Good price does not manufacture bluffs.",boundaryEn:"A good price does not manufacture bluffs.",skillIds:["RIV-03"],sourceRefs:["FTGU-E22","CINJ-E02","CINJ-E04"]},
{id:"A8-RULE-BLUFF-UNBLOCKS-FOLDS",triggerRu:"Выбираешь river bluff из нескольких air/missed draws.",triggerEn:"Choosing a river bluff from several air/missed-draw candidates.",ruleRu:"Предпочитай low-showdown candidates, которые не блокируют folds и поддерживают credible value ancestry.",ruleEn:"Prefer low-showdown candidates that do not block folds and support credible value ancestry.",boundaryRu:"Missed draw is not automatically a bluff.",boundaryEn:"A missed draw is not automatically a bluff.",skillIds:["RIV-02"],sourceRefs:["FTGU-E23","CP-G3-L03"]},
{id:"A8-RULE-EXPLOIT-STAYS-LOCAL",triggerRu:"Есть read, что river branch under/overbluffed.",triggerEn:"There is a read that a river branch is under/overbluffed.",ruleRu:"Отклоняйся только в подтверждённом branch. Не превращай observation в глобальный ярлык игрока/pool.",ruleEn:"Deviate only in the evidenced branch. Do not turn an observation into a global player/pool label.",boundaryRu:"Один showdown не доказывает whole-pool tendency.",boundaryEn:"One showdown does not prove a whole-pool tendency.",skillIds:["RIV-05"],sourceRefs:["FTGU-E24","FTGU-E25","CINJ-E10"]},
];
