import type { Drill, Flashcard, ModuleContent, Option } from "./types";
import type { ModuleId } from "../lib/model";

const option = (id: string, text: string, misconceptionId?: string): Option => ({ id, text, misconceptionId });

type DrillInput = Omit<Drill, "actionOptions" | "reasonOptions" | "correctActionId" | "correctReasonId"> & {
  correctAction: string;
  wrongActions: Array<[string, string]>;
  correctReason: string;
  wrongReasons: Array<[string, string]>;
};

function d(input: DrillInput): Drill {
  return {
    ...input,
    actionOptions: [
      option(`${input.id}-a0`, input.correctAction),
      option(`${input.id}-a1`, input.wrongActions[0][0], input.wrongActions[0][1]),
      option(`${input.id}-a2`, input.wrongActions[1][0], input.wrongActions[1][1]),
    ],
    reasonOptions: [
      option(`${input.id}-r0`, input.correctReason),
      option(`${input.id}-r1`, input.wrongReasons[0][0], input.wrongReasons[0][1]),
      option(`${input.id}-r2`, input.wrongReasons[1][0], input.wrongReasons[1][1]),
    ],
    correctActionId: `${input.id}-a0`,
    correctReasonId: `${input.id}-r0`,
  };
}

const c = (id: string, moduleId: ModuleId, kind: Flashcard["kind"], front: string, back: string): Flashcard => ({
  id,
  moduleId,
  kind,
  front,
  back,
});

export const modules: ModuleContent[] = [
  {
    id: "geometry",
    lcm: "LCM-01",
    title: "Эффективная глубина и геометрия банка",
    shortTitle: "Глубина и SPR",
    description: "Сначала определить реальный масштаб решения, затем выбирать линию.",
    prerequisites: [],
    admission: "ADMITTED",
    scope: "Направленная live-cash логика; точные диапазоны и частоты здесь не требуются.",
    plainGoal: "Понимать, сколько денег реально разыгрывается против каждого соперника и насколько коротким станет дальнейшее решение.",
    tableCue: "Единица → эффективный стек → банк после действия.",
    technicalTerm: "Strategic denominator, pairwise effective stack и post-action SPR.",
    theory: [
      "Стартовые big blinds полезны, но не всегда описывают текущую задачу. Обязательный straddle меняет цену preflop-дерева.",
      "В multiway-банке нет одной общей эффективной глубины: против каждого релевантного стека она своя.",
      "После крупного call или raise важнее становится отношение оставшегося стека к новому банку — SPR после действия.",
    ],
    heuristics: [
      "Какая обязательная ставка сейчас задаёт цену?",
      "Против какого стека Hero реально играет?",
      "Сколько останется в стеке и каким станет банк после действия?",
    ],
    decisionTree: [
      "Есть live straddle или другой forced bet? Выбери текущую единицу.",
      "Определи релевантных соперников и pairwise effective stack.",
      "Представь размер банка и остаток стека после следующего действия.",
      "Посчитай future SPR и только затем выбирай линию.",
    ],
    workedExample: {
      situation: "$2/$5/$10 mandatory straddle. Hero и Villain имеют по $1,400.",
      steps: [
        "Текущая стратегическая единица — $10, поэтому первая глубина равна 140 straddle-BB.",
        "В обычных BB это 280bb, но эта цифра не должна управлять решением первой.",
        "После конкретного raise/call нужно заново посчитать банк и оставшийся стек.",
      ],
      answer: "Сначала 140 straddle-BB, затем pairwise depth и post-action SPR.",
    },
    counterexample: "Стек 400bb может играться как короткий postflop-узел после огромного preflop-банка; стек 100bb может оставить несколько улиц решений в маленьком single-raised pot.",
    lab: {
      type: "spr",
      title: "SPR после call",
      description: "Введите банк до ставки, оставшийся стек и размер ставки. Система покажет SPR после call.",
      initialPot: 42,
      stack: 158,
      bet: 14,
    },
    explainBackPrompt: "Объясни своими словами, почему обычные BB, effective stack и SPR отвечают на разные вопросы.",
    tableCard: ["Текущая forced unit", "Pairwise effective stack", "Банк и стек после действия", "Future SPR"],
    glossary: [
      { term: "Effective stack", meaning: "Меньший из стеков Hero и конкретного соперника." },
      { term: "SPR", meaning: "Отношение оставшегося стека к банку." },
      { term: "Strategic denominator", meaning: "Обязательная ставка, которая задаёт текущую цену дерева." },
    ],
    drills: [
      d({ id: "geo-01", moduleId: "geometry", nodeKey: "mandatory-straddle", variantGroup: "denominator", kind: "core", targetSeconds: 30, assumptions: ["mandatory $10 straddle", "heads-up relevant stack"], cue: "$2/$5/$10, обязательный straddle. Оба стека $1,400.", question: "Какую глубину использовать первой?", correctAction: "140 straddle-BB; отдельно отметить 280 обычных BB", wrongActions: [["280 обычных BB — единственная рабочая глубина", "MC-001"], ["Глубина не важна, потому что стеки равны", "MC-002"]], correctReason: "$10 задаёт текущую цену preflop-дерева", wrongReasons: [["Большая цифра BB всегда точнее", "MC-001"], ["Straddle влияет только на размер первого рейза", "MC-003"]], explanation: "Forced bet меняет рабочую единицу, но обычные BB можно сохранить как дополнительное описание." }),
      d({ id: "geo-02", moduleId: "geometry", nodeKey: "pairwise-multiway", variantGroup: "pairwise", kind: "changed", targetSeconds: 30, assumptions: ["$1/$3", "Hero 900, A 270, B 1200"], cue: "Hero $900, A $270, B $1,200.", question: "Как описать эффективную глубину?", correctAction: "$270 против A и $900 против B", wrongActions: [["Одна общая глубина $270 для всего банка", "MC-004"], ["Средняя глубина $790", "MC-005"]], correctReason: "Effective stack считается отдельно для каждой релевантной пары", wrongReasons: [["Самый короткий стек всегда определяет весь multiway pot", "MC-004"], ["Среднее значение лучше отражает риск", "MC-005"]], explanation: "Side confrontations имеют разную доступную сумму, поэтому одной цифры недостаточно." }),
      d({ id: "geo-03", moduleId: "geometry", nodeKey: "post-call-spr", variantGroup: "future-spr", kind: "core", targetSeconds: 35, assumptions: ["pot 42", "stack 158", "bet 14", "heads-up call"], cue: "В банке 42. Стек 158. Villain ставит 14, Hero рассматривает call.", question: "Что нужно посчитать перед планом на следующие улицы?", correctAction: "SPR после call: (158−14)/(42+28) ≈ 2.06", wrongActions: [["Только pot odds текущего call", "MC-006"], ["Стартовые BB до флопа", "MC-001"]], correctReason: "Новый банк и оставшийся стек определяют длину будущего дерева", wrongReasons: [["Call автоматически убирает трудные turns", "MC-007"], ["SPR показывает только текущую equity", "MC-008"]], explanation: "Pot odds отвечают на цену call сейчас, а future SPR — на структуру решений после него." }),
      d({ id: "geo-04", moduleId: "geometry", nodeKey: "nominal-100bb", variantGroup: "future-spr", kind: "boundary", targetSeconds: 25, assumptions: ["100bb start", "small single-raised pot"], cue: "Старт 100bb, но preflop-банк остался маленьким.", question: "Можно ли автоматически назвать postflop shallow?", correctAction: "Нет; сначала оценить банк, остаток стека и будущий SPR", wrongActions: [["Да, 100bb всегда означает короткое дерево", "MC-009"], ["Да, если Hero вне позиции", "MC-010"]], correctReason: "Nominal depth не определяет post-action geometry без размера банка", wrongReasons: [["Позиция полностью заменяет SPR", "MC-010"], ["100bb — solver-константа для всех банков", "MC-009"]], explanation: "Одинаковая стартовая глубина создаёт разные деревья после разных preflop action." }),
      d({ id: "geo-05", moduleId: "geometry", nodeKey: "nominal-400bb-compressed", variantGroup: "future-spr", kind: "changed", targetSeconds: 25, assumptions: ["400bb start", "very large preflop pot"], cue: "Старт 400bb, но после крупного preflop action банк уже огромный.", question: "Какой вывод безопаснее?", correctAction: "Глубокий старт может превратиться в низкий postflop SPR", wrongActions: [["400bb всегда требует длинной четырёхулицевой стратегии", "MC-011"], ["Можно игнорировать размер банка до turn", "MC-012"]], correctReason: "Длина будущего дерева зависит от оставшегося стека относительно сформированного банка", wrongReasons: [["Глубина определяется только абсолютной суммой стека", "MC-011"], ["Большой банк автоматически даёт больше пространства", "MC-012"]], explanation: "Большой стартовый стек не гарантирует глубокую postflop-геометрию." }),
    ],
    flashcards: [
      c("geo-card-unit", "geometry", "heuristic", "Первая проверка при live straddle?", "Какая forced unit сейчас задаёт цену дерева?"),
      c("geo-card-pair", "geometry", "procedure", "Как считать effective stack multiway?", "Отдельно против каждого релевантного соперника."),
      c("geo-card-spr", "geometry", "boundary", "Почему стартовые BB могут обмануть?", "После action реальную длину дерева задаёт оставшийся стек относительно нового банка."),
    ],
  },
  {
    id: "preflop",
    lcm: "LCM-02",
    title: "Архитектура preflop-диапазона",
    shortTitle: "Call, squeeze или fold",
    description: "Сравнивать жизнеспособные ветки, а не превращать любую красивую руку в агрессию.",
    prerequisites: ["geometry"],
    admission: "ADMITTED",
    scope: "Направленные anchor-decisions; точные combo/frequency зависят от позиций, размеров, rake и поля.",
    plainGoal: "Понять, какая ветка — call, squeeze или fold — реально сохраняет ценность руки.",
    tableCue: "Цена → диапазоны → игроки сзади → реализация → линия.",
    technicalTerm: "Preflop range architecture: linear/value, polar и protected flat branches.",
    theory: ["Сначала проверь, существует ли хороший call. Удаление слабого call не автоматически создаёт bluff-raise.", "Value squeeze требует худших продолжений, fold equity или важного denial.", "Polar bluff-кандидат нуждается в реальных folds, полезных blockers и приемлемом equity при call."],
    heuristics: ["Не изобретай squeeze, пока не проверил call.", "Назови руки, которые fold и которые continue.", "Чем короче stack, тем меньше implied odds и выше ценность high cards."],
    decisionTree: ["Определи opener/caller ranges и sizing.", "Проверь игроков сзади и позицию Hero.", "Оцени качество call: цена, realisation, domination.", "Если call слаб — проверь value/denial или реальные fold targets для squeeze.", "Если ни одна ветка не работает — fold."],
    workedExample: { situation: "200bb. HJ open, CO call, Hero BTN 76s, blinds пассивны.", steps: ["Hero в позиции и закрывает меньше риска squeeze сзади.", "Глубина сохраняет implied-odds и board-coverage value.", "Рука плохо блокирует premium continues и не нуждается в насильственном раздувании банка."], answer: "Call — жизнеспособная защищённая ветка; squeeze не становится обязательным." },
    counterexample: "A5s против широких late-position ranges и реальных folds может быть polar squeeze candidate, но та же рука против tight EP + tight 3-bet branch часто просто fold.",
    lab: { type: "compare", title: "Сравнение веток", description: "Call сохраняет realisation; squeeze должен создать value, denial или folds.", leftTitle: "Call", leftText: "Цена, позиция, implied odds, доминация и игроки сзади.", rightTitle: "Squeeze", rightText: "Худшие calls, folds, blockers, equity и будущая геометрия." },
    explainBackPrompt: "Объясни, почему отсутствие хорошего call ещё не делает руку хорошим squeeze bluff.",
    tableCard: ["Цена", "Opener/caller ranges", "Игроки сзади", "Realisation", "Кому хуже от squeeze?"],
    glossary: [{ term: "Linear squeeze", meaning: "Расширение в сторону сильных high-card/value hands." }, { term: "Polar squeeze", meaning: "Value плюс bluff-кандидаты с blockers/equity и fold targets." }, { term: "Realisation", meaning: "Доля equity, которую рука реально превращает в результат через будущие решения." }],
    drills: [
      d({ id: "pre-01", moduleId: "preflop", nodeKey: "sb-tt-squeeze", variantGroup: "value-squeeze", kind: "core", targetSeconds: 30, assumptions: ["100bb", "CO 3bb", "BTN call", "Hero SB TT"], cue: "CO open 3bb, BTN call, Hero SB TT.", question: "Какая ветка первая?", correctAction: "Value squeeze core", wrongActions: [["Пассивный flat как default", "MC-013"], ["Fold из-за игры OOP", "MC-014"]], correctReason: "Широкие late ranges, denial и слабая SB-realisation делают heads-up conversion ценной", wrongReasons: [["TT всегда обязана 3-bet независимо от ranges", "MC-015"], ["Любая OOP-рука должна избегать банка", "MC-014"]], explanation: "Это directional value squeeze, а не универсальное правило для TT." }),
      d({ id: "pre-02", moduleId: "preflop", nodeKey: "btn-76s-deep", variantGroup: "protected-flat", kind: "changed", targetSeconds: 35, assumptions: ["200bb", "HJ open", "CO call", "Hero BTN 76s", "passive blinds"], cue: "200bb, Hero BTN с 76s против open+call.", question: "Какая ветка сохраняет ценность?", correctAction: "Call", wrongActions: [["Polar squeeze только потому, что рука suited", "MC-016"], ["Fold из-за низких карт", "MC-017"]], correctReason: "Позиция и глубина дают realisation/implied odds, а blockers к premium continues слабы", wrongReasons: [["Любой suited connector прибыльно call при любой цене", "MC-018"], ["Squeeze нужен для захвата инициативы", "MC-019"]], explanation: "Viable flat защищается; инициативность сама по себе не является целью." }),
      d({ id: "pre-03", moduleId: "preflop", nodeKey: "co-kjo-ep", variantGroup: "domination-fold", kind: "boundary", targetSeconds: 30, assumptions: ["100bb", "EP 4bb", "HJ call", "Hero CO KJo"], cue: "EP open 4bb, HJ call, Hero CO KJo.", question: "Что безопаснее?", correctAction: "Fold", wrongActions: [["Call ради broadway potential", "MC-020"], ["Squeeze как blocker bluff", "MC-021"]], correctReason: "Strong source ranges, domination и слабая multiway realisation перевешивают поверхностные blockers", wrongReasons: [["Любой offsuit broadway обязан fold multiway", "MC-022"], ["K-blocker гарантирует fold equity", "MC-021"]], explanation: "Решение следует из конкретной source-range и domination structure." }),
      d({ id: "pre-04", moduleId: "preflop", nodeKey: "sb-a5s-late", variantGroup: "polar-squeeze", kind: "changed", targetSeconds: 35, assumptions: ["100bb", "CO open", "BTN call", "Hero SB A5s", "BB passive"], cue: "Late open+call, Hero SB A5s.", question: "Когда polar squeeze имеет смысл?", correctAction: "Когда late ranges дают реальные folds и call-ветка хуже", wrongActions: [["Всегда, потому что A5s — solver bluff", "MC-023"], ["Никогда, потому что suited ace надо call", "MC-024"]], correctReason: "Ace blocker, nut equity и fold targets работают вместе, а не по отдельности", wrongReasons: [["Blocker сам создаёт folds", "MC-021"], ["Suitedness гарантирует profitable aggression", "MC-016"]], explanation: "Это кандидат, а не автоматическая клетка chart." }),
      d({ id: "pre-05", moduleId: "preflop", nodeKey: "bb-ajo-55bb", variantGroup: "short-linear", kind: "changed", targetSeconds: 30, assumptions: ["55bb", "BTN 2.5bb", "SB call", "Hero BB AJo"], cue: "55bb, BTN open, SB call, Hero BB AJo.", question: "Как short stack меняет branch?", correctAction: "Сдвигает к linear squeeze", wrongActions: [["Увеличивает speculative flat incentive", "MC-025"], ["Не меняет ничего относительно 200bb", "MC-026"]], correctReason: "Низкий будущий SPR повышает high-card value и уменьшает implied odds speculative calls", wrongReasons: [["Short stack делает любой ace обязательным all-in", "MC-027"], ["Глубина влияет только postflop", "MC-026"]], explanation: "Directional shift не задаёт точный размер или частоту." }),
    ],
    flashcards: [c("pre-card-seq", "preflop", "procedure", "Пять preflop-проверок?", "Цена → ranges → игроки сзади → realisation → линия."), c("pre-card-flat", "preflop", "boundary", "Когда call надо защищать от лишнего squeeze?", "Когда позиция, цена и глубина дают реальную postflop-ценность."), c("pre-card-polar", "preflop", "heuristic", "Что нужно polar squeeze bluff?", "Реальные folds, полезные blockers/equity и отсутствие лучшего call." )],
  },
  {
    id: "blinds",
    lcm: "LCM-03",
    title: "Идентичность блайндов и реализация",
    shortTitle: "SB не равен BB",
    description: "Не копировать одну защиту между позициями, которые приходят к флопу разными путями.",
    prerequisites: ["preflop"],
    admission: "ADMITTED",
    scope: "Directional range identity; точные flats/3-bets зависят от rake, size и поля.",
    plainGoal: "Понимать, почему BB часто закрывает action и получает цену, а SB остаётся OOP с игроком сзади.",
    tableCue: "Кто закрыл action? Кто ещё может проснуться?",
    technicalTerm: "Blind source identity, closing action и equity realisation.",
    theory: ["BB defend обычно шире из-за цены и закрытия action.", "SB cold-call чаще condensed и уязвим к игроку сзади.", "Одинаковый flop не означает одинаковые arriving ranges."],
    heuristics: ["Сначала назови источник range.", "Закрытие action — реальная ценность.", "OOP discomfort не заменяет анализ realisation."],
    decisionTree: ["SB или BB?", "Action закрыт?", "Есть squeeze risk сзади?", "Как рука реализует equity OOP?", "Как изменился arriving range на flop?"],
    workedExample: { situation: "CO opens. Один раз flop A-7-2r против BB defend, другой — против SB cold-call.", steps: ["BB приходит шире благодаря цене.", "SB cold-call чаще содержит condensed middling/pocket/broadway mass.", "C-bet plan должен учитывать разные continues и check-raises."], answer: "Не копировать один plan; сначала различить source range." },
    counterexample: "Если конкретный live SB подтверждённо overcalls очень широко, observed branch корректирует prior, но не отменяет action-order risk.",
    lab: { type: "compare", title: "SB и BB", description: "Один board, разные source ranges.", leftTitle: "BB defend", leftText: "Цена, closing action, широкая coverage.", rightTitle: "SB cold-call", rightText: "OOP, игрок сзади, чаще condensed range." },
    explainBackPrompt: "Объясни, почему одинаковая текстура не даёт одинаковый c-bet plan против SB и BB.",
    tableCard: ["Источник range", "Закрыт ли action", "Игроки сзади", "Цена", "Postflop realisation"],
    glossary: [{ term: "Condensed range", meaning: "Диапазон с массой средне-сильных рук и меньшим количеством крайних полюсов." }, { term: "Closing action", meaning: "После решения Hero никто больше не может raise preflop." }],
    drills: [
      d({ id: "bli-01", moduleId: "blinds", nodeKey: "sb-vs-bb-source", variantGroup: "blind-source", kind: "core", targetSeconds: 30, assumptions: ["CO 3bb", "A72r flop"], cue: "Один и тот же A-7-2r против BB defend и SB cold-call.", question: "Можно ли копировать c-bet plan?", correctAction: "Нет; сначала разделить arriving ranges", wrongActions: [["Да, board одинаковый", "MC-028"], ["Да, потому что оба игрока на блайнде", "MC-029"]], correctReason: "SB cold-call обычно более condensed, BB defend шире из-за цены", wrongReasons: [["Позиция preflop перестаёт иметь значение на flop", "MC-028"], ["Все blind ranges одинаковы после call", "MC-029"]], explanation: "Range source остаётся частью node signature." }),
      d({ id: "bli-02", moduleId: "blinds", nodeKey: "bb-closing-call", variantGroup: "closing-action", kind: "changed", targetSeconds: 30, assumptions: ["open+call", "Hero BB suited connector"], cue: "Hero BB закрывает action с suited connected hand.", question: "Что проверить до squeeze?", correctAction: "Сохранить жизнеспособный closing-action call", wrongActions: [["Squeeze для инициативы", "MC-019"], ["Fold, потому что multiway", "MC-030"]], correctReason: "Цена, отсутствие игрока сзади и coverage могут дать realisation без большого банка", wrongReasons: [["BB всегда должен защищать любую suited hand", "MC-018"], ["Closing action гарантирует прибыль", "MC-031"]], explanation: "Closing action улучшает call, но не отменяет цену и source ranges." }),
      d({ id: "bli-03", moduleId: "blinds", nodeKey: "sb-player-behind", variantGroup: "players-behind", kind: "boundary", targetSeconds: 30, assumptions: ["open+call", "Hero SB"], cue: "Hero SB рассматривает passive flat, BB ещё не действовал.", question: "Главный дополнительный риск?", correctAction: "BB может squeeze и уничтожить дешёвую реализацию", wrongActions: [["Только вероятность плохого flop", "MC-032"], ["Риск отсутствует, если hand suited", "MC-016"]], correctReason: "SB не закрывает action и остаётся OOP", wrongReasons: [["SB получает ту же цену, что BB", "MC-029"], ["Suitedness нейтрализует position", "MC-033"]], explanation: "Players-behind gate отличает SB flat от BB close." }),
      d({ id: "bli-04", moduleId: "blinds", nodeKey: "oop-realisation", variantGroup: "realisation", kind: "changed", targetSeconds: 35, assumptions: ["deep OOP pot"], cue: "Рука выглядит playable, но Hero будет глубоко OOP.", question: "Какой вопрос идёт первым?", correctAction: "Сколько equity рука реально реализует через будущие решения?", wrongActions: [["Насколько красиво рука выглядит preflop", "MC-034"], ["Можно ли избежать всех сложных turns рейзом", "MC-007"]], correctReason: "Raw equity и realised equity расходятся под positional pressure", wrongReasons: [["OOP всегда означает fold", "MC-014"], ["Initiative полностью компенсирует position", "MC-019"]], explanation: "Realisation — не чувство комфорта, а способность дойти до value без чрезмерных потерь." }),
      d({ id: "bli-05", moduleId: "blinds", nodeKey: "one-showdown", variantGroup: "blind-source", kind: "boundary", targetSeconds: 25, assumptions: ["one unusual blind call observed"], cue: "Live player один раз показал необычный blind call.", question: "Как обновить модель?", correctAction: "Записать наблюдение, но сохранить structural prior", wrongActions: [["Сразу считать blind range очень широким", "MC-035"], ["Полностью игнорировать showdown", "MC-036"]], correctReason: "Одна hand информирует note, но не доказывает стабильную branch frequency", wrongReasons: [["Любой showdown раскрывает полный range", "MC-035"], ["Theory никогда не меняется от поля", "MC-036"]], explanation: "Evidence корректирует prior постепенно и branch-specific." }),
    ],
    flashcards: [c("bli-card-source", "blinds", "heuristic", "Первый вопрос на одинаковом flop?", "Из какого preflop-source range пришёл соперник?"), c("bli-card-close", "blinds", "procedure", "Что даёт BB closing action?", "Никто не может проснуться с raise; дешёвая реализация становится реальнее."), c("bli-card-sb", "blinds", "boundary", "Почему SB flat дороже BB defend?", "SB OOP и оставляет игрока сзади." )],
  },
  {
    id: "filtering",
    lcm: "LCM-04",
    title: "Источник диапазона и фильтр действий",
    shortTitle: "Что дошло до узла",
    description: "Каждый добровольный action удаляет часть рук и усиливает оставшийся диапазон.",
    prerequisites: ["blinds"], admission: "ADMITTED", scope: "Universal reasoning framework; exact combo counts require node-specific ranges.",
    plainGoal: "Не принимать turn/river решение по исходному range, забыв, что соперник уже call/check/raise.", tableCue: "Откуда range пришёл? Что action убрал? Что осталось?", technicalTerm: "Range source, action filtering и arrival range.",
    theory: ["Range начинается в позиции и preflop branch.", "Каждый bet/call/check/raise меняет состав следующего узла.", "Эксплойт предыдущей улицы не переносится автоматически после того, как соперник продолжил."],
    heuristics: ["Source → action → survivors.", "Call обычно убирает часть воздуха.", "Blocker работает только против реально дошедшего range."],
    decisionTree: ["Назови source range.", "Пропусти его через каждый добровольный action.", "Раздели surviving value, medium hands и air.", "Только затем оцени board, size и blocker."],
    workedExample: { situation: "Hero wider c-bets против overfolder; Villain calls flop.", steps: ["Flop exploit был направлен на folds.", "Call удаляет часть слабых hands.", "Turn начинается против более сильного arrival range."], answer: "Не продолжать excess bluffing автоматически; заново построить turn range." },
    counterexample: "Check-back не всегда означает capped range: сильные hands могут защищать check, поэтому нужны source и branch assumptions.",
    lab: { type: "compare", title: "До и после call", description: "Исходный широкий range становится плотнее после добровольного продолжения.", leftTitle: "До action", leftText: "Value, medium hands и много air.", rightTitle: "После call", rightText: "Часть air исчезла; ownership и bluff supply изменились." },
    explainBackPrompt: "Объясни, почему успешный flop exploit нельзя автоматически копировать на turn после call.", tableCard: ["Source range", "Каждый action", "Surviving value", "Surviving air", "Новый decision"],
    glossary: [{ term: "Arrival range", meaning: "Руки, которые реально дошли до текущего узла после прошлых действий." }, { term: "Filtering", meaning: "Удаление и усиление частей range каждым action." }],
    drills: [
      d({ id: "fil-01", moduleId: "filtering", nodeKey: "two-calls", variantGroup: "action-filter", kind: "core", targetSeconds: 30, assumptions: ["two voluntary calls"], cue: "Villain дважды добровольно call до river.", question: "Первое обновление?", correctAction: "Пропустить source range через оба call", wrongActions: [["Оставить исходный preflop range", "MC-037"], ["Считать range автоматически nutted", "MC-038"]], correctReason: "Каждый call удаляет часть folds/air и меняет ownership", wrongReasons: [["Board важнее всей action history", "MC-039"], ["Любой двойной call означает только value", "MC-038"]], explanation: "Filtering сужает, но не превращает range в одну категорию." }),
      d({ id: "fil-02", moduleId: "filtering", nodeKey: "small-near-range", variantGroup: "size-shape", kind: "changed", targetSeconds: 30, assumptions: ["small near-range flop bet"], cue: "Flop bet маленький и near-range.", question: "Что идёт до выбора defence?", correctAction: "Определить shape betting range", wrongActions: [["Защищать только по размеру ставки", "MC-040"], ["Всегда raise vulnerable pairs", "MC-041"]], correctReason: "Одинаковый size может представлять разную range construction", wrongReasons: [["Маленькая ставка всегда слабая", "MC-042"], ["Size полностью раскрывает hand strength", "MC-040"]], explanation: "Price важна, но response строится против range shape." }),
      d({ id: "fil-03", moduleId: "filtering", nodeKey: "checkback-turn", variantGroup: "missed-action", kind: "changed", targetSeconds: 30, assumptions: ["flop check-back"], cue: "Villain check back flop, turn динамичный.", question: "С чего начать turn?", correctAction: "Перестроить range после check-back", wrongActions: [["Использовать исходный preflop range", "MC-037"], ["Считать Villain capped без проверки", "MC-043"]], correctReason: "Пропущенная ставка удаляет часть bet branches, но может сохранять protected checks", wrongReasons: [["Check всегда означает слабость", "MC-043"], ["Turn card стирает flop action", "MC-039"]], explanation: "Missed action — тоже фильтр, но его смысл зависит от strategy shape." }),
      d({ id: "fil-04", moduleId: "filtering", nodeKey: "river-arrival", variantGroup: "river-filter", kind: "boundary", targetSeconds: 40, assumptions: ["flop call", "turn call", "river change"], cue: "Villain call flop и turn; river меняет board.", question: "Что остановит blocker-only решение?", correctAction: "Посчитать, какие value и bluffs реально дошли", wrongActions: [["Выбрать самый красивый blocker", "MC-044"], ["Считать scary river автоматическим bluff card", "MC-045"]], correctReason: "River card действует через action-filtered arrival range", wrongReasons: [["Blocker сам создаёт bluff supply", "MC-046"], ["Страшная карта всегда усиливает aggressor", "MC-045"]], explanation: "Ancestry предшествует blocker." }),
      d({ id: "fil-05", moduleId: "filtering", nodeKey: "exploit-call-filter", variantGroup: "exploit-reset", kind: "changed", targetSeconds: 35, assumptions: ["wide exploit c-bet", "Villain calls"], cue: "Hero wider c-bet против overfolder, но Villain call.", question: "Как меняется turn plan?", correctAction: "Заново фильтровать и уменьшить автоматический excess bluffing", wrongActions: [["Продолжать wider bluff на всех turns", "MC-047"], ["Полностью отказаться от aggression", "MC-048"]], correctReason: "Call выбрал более сильную часть range и изменил fold supply", wrongReasons: [["Exploit действует неизменно на всех streets", "MC-047"], ["Любой call делает range неуязвимым", "MC-048"]], explanation: "Exploit — branch-specific hypothesis, а не глобальная лицензия." }),
    ],
    flashcards: [c("fil-card-source", "filtering", "procedure", "Три шага range update?", "Source → action → survivors."), c("fil-card-call", "filtering", "heuristic", "Что обычно делает call с range?", "Удаляет часть air/folds и усиливает arrival range."), c("fil-card-blocker", "filtering", "boundary", "Что идёт до blocker?", "Проверка реально дошедших value и bluffs." )],
  },
  {
    id: "shape", lcm: "LCM-05", title: "Форма ставки и ответа", shortTitle: "Small-wide vs large-polar", description: "Размер важен вместе с шириной и поляризацией betting range.", prerequisites: ["filtering"], admission: "ADMITTED", scope: "Directional response shapes; exact frequencies require solver/node validation.", plainGoal: "Отличать маленькую широкую ставку от крупной выборочной и менять calls/raises соответственно.", tableCue: "Размер + ширина range → форма ответа.", technicalTerm: "Small-wide, large-selective/polar, linear raises и protected calls.", theory: ["Small-wide branch содержит больше air и даёт лучшую цену.", "Large-selective branch сильнее и уменьшает thin raises.", "Robust hands иногда лучше защищают call, а vulnerable value может raise ради denial."], heuristics: ["Не читай size без range shape.", "Raise обязан назвать worse continues или equity denial.", "Сильнейшая рука не всегда первая на raise."], decisionTree: ["Определи wide или selective branch.", "Назови price и continuing range.", "Раздели robust и vulnerable made hands.", "Проверь value/denial targets.", "Сохрани protected call branch."], workedExample: { situation: "BTN vs BB, T-5-5r, small 25% near-range bet.", steps: ["Betting range содержит много air.", "T6s уязвимее к overcards и denial имеет ценность.", "KTs robust и может защищать calls."], answer: "T6s получает больше directional raise incentive, KTs чаще сохраняет call." }, counterexample: "Если bet становится 80% polar, thin/protection raise T6s резко сжимается.", lab: { type: "compare", title: "Одна текстура, две ставки", description: "Смена range shape меняет defence сильнее, чем номинальная сила руки.", leftTitle: "25% wide", leftText: "Шире calls, возможны linear protection raises.", rightTitle: "80% polar", rightText: "Уже calls, меньше thin raises, выше требования к equity." }, explainBackPrompt: "Объясни, почему T6s может raise чаще против 25%, но не против 80% polar bet.", tableCard: ["Size", "Wide или polar", "Robust/vulnerable", "Value targets", "Denial targets"], glossary: [{ term: "Robust hand", meaning: "Рука, которая хорошо переносит будущие карты и давление." }, { term: "Linear raise", meaning: "Raise не только nuts/bluffs, но и часть уязвимого value." }],
    drills: [
      d({ id: "sha-01", moduleId: "shape", nodeKey: "small-wide", variantGroup: "small-vs-large", kind: "core", targetSeconds: 30, assumptions: ["25% near-range bet"], cue: "Villain ставит 25% почти всем range.", question: "Какой defence direction доступнее?", correctAction: "Шире call и selected linear protection raises", wrongActions: [["Сильно сузить calls из-за частоты bet", "MC-049"], ["Raise только nuts", "MC-050"]], correctReason: "Price лучше, а betting range содержит больше air", wrongReasons: [["Маленькая ставка всегда слабая hand", "MC-042"], ["Частая ставка требует частого raise независимо от hands", "MC-051"]], explanation: "Range-level weakness создаёт room, но конкретные raises всё ещё нуждаются в jobs." }),
      d({ id: "sha-02", moduleId: "shape", nodeKey: "large-polar", variantGroup: "small-vs-large", kind: "changed", targetSeconds: 30, assumptions: ["80% selective bet"], cue: "Та же texture, но 80% selective/polar bet.", question: "Как меняется response?", correctAction: "Сжать calls и убрать thin protection raises", wrongActions: [["Raise чаще из-за большего pot", "MC-052"], ["Защищать так же, как против 25%", "MC-053"]], correctReason: "Continuing range сильнее, price хуже, denial value thin raises падает", wrongReasons: [["Большой size всегда bluff-heavy", "MC-054"], ["Размер не влияет на range composition", "MC-053"]], explanation: "Changed node требует другого response shape." }),
      d({ id: "sha-03", moduleId: "shape", nodeKey: "robust-call", variantGroup: "protected-call", kind: "boundary", targetSeconds: 35, assumptions: ["credible future aggression"], cue: "Hero держит сильную robust hand против агрессора.", question: "Почему call может быть лучше raise?", correctAction: "Защитить call branch и сохранить будущий air", wrongActions: [["Raise, потому что сильнейшая hand всегда повышает", "MC-055"], ["Call только для trap без range reason", "MC-056"]], correctReason: "Robust hand выдерживает turns и защищает weaker continues", wrongReasons: [["Slowplay всегда максимизирует value", "MC-056"], ["Raise раскрывает силу и потому плох", "MC-057"]], explanation: "Protected call — range job, не пассивность." }),
      d({ id: "sha-04", moduleId: "shape", nodeKey: "vulnerable-top-pair", variantGroup: "protection-raise", kind: "changed", targetSeconds: 35, assumptions: ["small wide bet", "dynamic board", "top-end support"], cue: "Vulnerable top pair против small-wide bet.", question: "Что делает raise валидным?", correctAction: "Назвать worse continues и живое equity, которое deny", wrongActions: [["Желание избежать сложного turn", "MC-007"], ["То, что Hero сейчас впереди", "MC-058"]], correctReason: "Merged raise нуждается в value/denial targets", wrongReasons: [["Любая ahead hand должна защищаться raise", "MC-058"], ["Комфорт является стратегической целью", "MC-007"]], explanation: "Raise должен улучшать результат против конкретного range." }),
      d({ id: "sha-05", moduleId: "shape", nodeKey: "oop-discomfort", variantGroup: "raise-job", kind: "boundary", targetSeconds: 25, assumptions: ["OOP difficult turns"], cue: "Hero не хочет играть сложные turns OOP.", question: "Достаточная ли это причина raise?", correctAction: "Нет; нужен конкретный value, denial или equity-pressure job", wrongActions: [["Да, raise покупает контроль", "MC-007"], ["Да, любая OOP line должна сокращать дерево", "MC-059"]], correctReason: "Психологический relief не меняет EV continuing ranges", wrongReasons: [["Сложность всегда означает отрицательный EV", "MC-059"], ["Initiative гарантирует control", "MC-019"]], explanation: "Discomfort — сигнал проверить line, но не её стратегическое обоснование." }),
    ], flashcards: [c("sha-card-shape", "shape", "procedure", "Что читать вместе с size?", "Ширину и поляризацию betting range."), c("sha-card-raise", "shape", "heuristic", "Два вопроса перед protection raise?", "Кто хуже call и какое equity мы deny?"), c("sha-card-robust", "shape", "boundary", "Почему strong hand может call?", "Чтобы защищать call branch и сохранить будущую агрессию соперника." )],
  },
  {
    id: "aggression", lcm: "LCM-06", title: "Агрессия и будущая работа линии", shortTitle: "У каждой ставки есть job", description: "Сначала value region, затем bluffs и будущие улицы.", prerequisites: ["shape"], admission: "ADMITTED", scope: "Directional construction; exact bluff ratios and sizes remain node-specific.", plainGoal: "Не ставить только потому, что hand слабая или карта страшная.", tableCue: "Value сначала. Потом job каждой bluff-hand.", technicalTerm: "Value-first construction, denial, equity pressure и future jobs.", theory: ["Bluff volume следует из value region и size.", "Низкий showdown value не является достаточной причиной bet.", "Turn card может выглядеть страшно, но одновременно repair caller range."], heuristics: ["Назови weakest value hand.", "Bluff должен иметь equity, blockers или river job.", "Scary card проверяй на ownership, а не на картинку."], decisionTree: ["Определи value threshold.", "Выбери size, который обслуживает value.", "Найди bluff families с полезными jobs.", "Проверь, не блокируют ли они folds.", "Построй river continuation/falsifier."], workedExample: { situation: "Turn hand почти без showdown, equity и useful blockers.", steps: ["Слабость hand не создаёт fold equity.", "Hand блокирует часть folds.", "На river нет хороших продолжений."], answer: "Это jobless barrel — check/fold family, а не автоматический bluff." }, counterexample: "Pair+draw с nut improvement и removal может быть сильным bluff candidate даже multiway, если line и ownership поддерживают aggression.", lab: { type: "compare", title: "Слабая hand vs рабочий bluff", description: "Bluff выбирается по функции, не по неприятности showdown.", leftTitle: "Jobless", leftText: "Мало equity, блокирует folds, нет river plan.", rightTitle: "Working bluff", rightText: "Equity, removal, matcher или credible future air." }, explainBackPrompt: "Объясни, почему low showdown value не равен bluff и почему value region строится первым.", tableCard: ["Weakest value", "Size", "Bluff job", "Folds blocked?", "River plan"], glossary: [{ term: "Jobless bluff", meaning: "Bluff без equity, полезных blockers и будущего плана." }, { term: "Denial", meaning: "Заставить fold руки с живым equity против Hero." }],
    drills: [
      d({ id: "agg-01", moduleId: "aggression", nodeKey: "value-first", variantGroup: "value-before-bluffs", kind: "core", targetSeconds: 25, assumptions: ["turn barrel construction"], cue: "Hero выбирает turn bluffs.", question: "Какой вопрос первый?", correctAction: "Какая weakest value hand и какой size она использует?", wrongActions: [["Какие hands выглядят слабее всего", "MC-060"], ["Сколько bluffs хочется иметь", "MC-061"]], correctReason: "Bluff supply должен обслуживать определённый value region", wrongReasons: [["Любая low-showdown hand обязана bluff", "MC-060"], ["Balance начинается с количества bluffs", "MC-061"]], explanation: "Value-first предотвращает бессистемное excess bluffing." }),
      d({ id: "agg-02", moduleId: "aggression", nodeKey: "jobless-barrel", variantGroup: "bluff-job", kind: "boundary", targetSeconds: 30, assumptions: ["low equity", "blocks folds", "no river plan"], cue: "Hand почти без equity, блокирует folds и не имеет river jobs.", question: "Классификация?", correctAction: "Jobless bluff — чаще check", wrongActions: [["Обязательный barrel из-за low showdown", "MC-060"], ["Overbet для максимального pressure", "MC-062"]], correctReason: "Слабость Hero не компенсирует отсутствие equity, removal и continuation", wrongReasons: [["Большой size создаёт folds из ничего", "MC-062"], ["Любая air должна использоваться для balance", "MC-061"]], explanation: "Bluff candidate должен улучшать range construction." }),
      d({ id: "agg-03", moduleId: "aggression", nodeKey: "caller-repair-card", variantGroup: "turn-ownership", kind: "changed", targetSeconds: 35, assumptions: ["turn completes caller draws"], cue: "Turn закрывает draws, сконцентрированные в flop calling range.", question: "Автоматический overbet?", correctAction: "Нет; проверить, не усилил ли turn caller", wrongActions: [["Да, карта визуально страшная", "MC-045"], ["Всегда check на completed draw", "MC-063"]], correctReason: "Card может уменьшить Hero value/nut advantage", wrongReasons: [["Scare card всегда принадлежит aggressor", "MC-045"], ["Completed draws всегда убивают aggression", "MC-063"]], explanation: "Ownership analysis заменяет визуальный storytelling." }),
      d({ id: "agg-04", moduleId: "aggression", nodeKey: "passive-pool-value", variantGroup: "value-timing", kind: "changed", targetSeconds: 30, assumptions: ["future actor rarely bets"], cue: "Hero имеет сильное уязвимое value, следующий игрок редко ставит.", question: "Как меняется slowplay incentive?", correctAction: "Часть value двигать вперёд", wrongActions: [["Slowplay чаще, чтобы не спугнуть", "MC-056"], ["Всегда check, потому что range protection", "MC-064"]], correctReason: "Будущая aggression может не появиться, а free cards стоят value", wrongReasons: [["Сильная hand всегда должна trap", "MC-056"], ["Passive pool никогда не call bets", "MC-065"]], explanation: "Timing value зависит от вероятности будущих bets и уязвимости." }),
      d({ id: "agg-05", moduleId: "aggression", nodeKey: "protected-call-vs-denial", variantGroup: "line-jobs", kind: "changed", targetSeconds: 35, assumptions: ["small wide bet"], cue: "Robust hand и vulnerable hand против small-wide bet.", question: "Как разделить линии?", correctAction: "Robust может call; vulnerable raise ради value/denial", wrongActions: [["Сильнейшая всегда raise, слабейшая call", "MC-055"], ["Обе raise для protection", "MC-041"]], correctReason: "Разные hands выполняют разные range jobs", wrongReasons: [["Hand strength полностью определяет action", "MC-055"], ["Protection одинаково нужна всем made hands", "MC-041"]], explanation: "Range architecture важнее линейного ранжирования силы." }),
    ], flashcards: [c("agg-card-value", "aggression", "procedure", "Что идёт до bluffs?", "Weakest value hand и size."), c("agg-card-job", "aggression", "heuristic", "Три возможных bluff jobs?", "Equity, полезные blockers/removal, credible river continuation."), c("agg-card-scary", "aggression", "boundary", "Что проверить на scary turn?", "Не repair ли карта calling range соперника." )],
  },
  {
    id: "ancestry", lcm: "LCM-07", title: "Происхождение диапазона в 3-bet pot", shortTitle: "Ancestry до blocker", description: "Считать только hands, которые могли войти и пережить прошлые actions.", prerequisites: ["aggression"], admission: "ADMITTED", scope: "Directional branch tracing; exact frequencies need source ranges and evidence.", plainGoal: "Не придумывать river bluffs или preflop folds, которых в этой branch почти нет.", tableCue: "Кто вошёл? Кто пережил каждый action?", technicalTerm: "Range ancestry, branch-specific opponent model и credible bluff supply.", theory: ["Blocker меняет сравнение существующих ranges, но не создаёт отсутствующие combos.", "Wide 3-bet branch может иметь folds к 4-bet; tight value-heavy branch — нет.", "Один opponent может over-cbet/fold и одновременно value-heavy re-raise."], heuristics: ["До blocker — ancestry.", "До exploit — конкретная branch.", "Нет fold target — нет blocker bluff."], decisionTree: ["Назови preflop source range.", "Пропусти через 3-bet/4-bet/call branches.", "Пропусти через flop/turn actions.", "Посчитай credible value и air.", "Только потом blocker и population evidence."], workedExample: { situation: "Tight SB 3-bet против EP, Hero A5s.", steps: ["SB range почти value-heavy.", "Better hands почти не fold на 4-bet.", "A-blocker уменьшает combos, но не создаёт необходимую fold frequency."], answer: "Fold/baseline, а не автоматический blocker 4-bet." }, counterexample: "BTN vs wide BB 3-bet с доказанными folds к 4-bet может сделать A5s кандидатом, если value branch определён.", lab: { type: "compare", title: "Одна hand, две ancestry", description: "A5s меняет роль вместе с source branch.", leftTitle: "Wide 3-bet + folds", leftText: "Есть fold targets; polar candidate возможен.", rightTitle: "Tight value-heavy", rightText: "Fold targets нет; blocker не спасает bluff." }, explainBackPrompt: "Объясни, почему nut blocker не является достаточным основанием river call или preflop 4-bet bluff.", tableCard: ["Source range", "Каждый action", "Value survivors", "Air survivors", "Blocker/evidence"], glossary: [{ term: "Ancestry", meaning: "История происхождения комбинаций до текущего узла." }, { term: "Credible bluff supply", meaning: "Реальные bluff families, которые могли дойти по этой линии." }],
    drills: [
      d({ id: "anc-01", moduleId: "ancestry", nodeKey: "wide-3bet-a5s", variantGroup: "4bet-target", kind: "core", targetSeconds: 35, assumptions: ["BTN open", "BB wide 3-bet", "folds to 4-bet", "A5s"], cue: "BB 3-bet wide и может fold к 4-bet; Hero A5s.", question: "Что делает bluff кандидатом?", correctAction: "Проверить value region и реальные folds", wrongActions: [["4-bet всегда из-за ace blocker", "MC-021"], ["Call всегда из-за suitedness", "MC-024"]], correctReason: "Blocker/equity полезны только при credible fold targets", wrongReasons: [["A5s — фиксированная solver-клетка", "MC-023"], ["Suited ace не может fold preflop", "MC-024"]], explanation: "Candidate зависит от branch, не от имени hand." }),
      d({ id: "anc-02", moduleId: "ancestry", nodeKey: "tight-3bet-a5s", variantGroup: "4bet-target", kind: "boundary", targetSeconds: 30, assumptions: ["EP open", "tight SB 3-bet", "A5s"], cue: "Tight value-heavy SB 3-bet против EP.", question: "Что останавливает familiar bluff?", correctAction: "Отсутствие реальных better-hand folds", wrongActions: [["Низкая абсолютная сила A5s", "MC-066"], ["Страх большого банка", "MC-067"]], correctReason: "Blocker не создаёт fold equity против почти полностью continuing range", wrongReasons: [["Bluff нельзя делать слабой hand", "MC-066"], ["Большие банки всегда требуют value only", "MC-067"]], explanation: "Причина — branch construction, а не эмоциональный risk." }),
      d({ id: "anc-03", moduleId: "ancestry", nodeKey: "ip-98s-call", variantGroup: "protected-call", kind: "changed", targetSeconds: 35, assumptions: ["150bb", "BTN vs BB 3-bet", "98s IP"], cue: "150bb, Hero IP с 98s против 3-bet.", question: "Что может повредить automatic 4-bet?", correctAction: "Хорошо реализующийся call branch", wrongActions: [["Ничего: suited connector всегда bluff 4-bet", "MC-016"], ["Call невозможен в 3-bet pot", "MC-068"]], correctReason: "Position/depth дают realisation, а hand плохо блокирует premium continues", wrongReasons: [["Любая suited hand обязана call", "MC-018"], ["4-bet нужен для инициативы", "MC-019"]], explanation: "Protected call сравнивается с bluff branch до расширения aggression." }),
      d({ id: "anc-04", moduleId: "ancestry", nodeKey: "branch-split", variantGroup: "opponent-branch", kind: "changed", targetSeconds: 35, assumptions: ["over-cbet/fold", "value-heavy flop 3-bet"], cue: "Villain c-bet слишком wide и fold к raise, но flop 3-bet value-heavy.", question: "Как хранить read?", correctAction: "Разделить c-bet/fold и c-bet/3-bet branches", wrongActions: [["Назвать игрока слабым и raise всё", "MC-069"], ["Игнорировать fold leak из-за сильного re-raise", "MC-070"]], correctReason: "Слабая fold branch и сильная re-raise branch могут сосуществовать", wrongReasons: [["У игрока должна быть одна глобальная тенденция", "MC-069"], ["Одна сильная branch отменяет другую", "MC-070"]], explanation: "Opponent model должен быть action-specific." }),
      d({ id: "anc-05", moduleId: "ancestry", nodeKey: "river-nut-blocker", variantGroup: "river-ancestry", kind: "boundary", targetSeconds: 45, assumptions: ["tight entry", "flop raise call", "turn overbet call", "river jam"], cue: "Hero держит nut-flush blocker против river jam после плотной линии.", question: "Что до blocker?", correctAction: "Посчитать credible value и bluff ancestry", wrongActions: [["Call из-за nut blocker", "MC-044"], ["Fold только потому, что size большой", "MC-071"]], correctReason: "Blocker не может создать air, которая не пережила прошлые actions", wrongReasons: [["Nut blocker автоматически лучший bluff-catcher", "MC-046"], ["Huge bet никогда не bluff", "MC-071"]], explanation: "Baseline может быть fold/unknown, если bluff supply не обоснован." }),
    ], flashcards: [c("anc-card-before", "ancestry", "procedure", "Что идёт до blocker?", "Source range и surviving value/bluff ancestry."), c("anc-card-target", "ancestry", "boundary", "Когда blocker bluff не работает?", "Когда better hands почти не fold в этой branch."), c("anc-card-model", "ancestry", "heuristic", "Как хранить opponent read?", "Отдельно по action, size и node; не глобальным ярлыком." )],
  },
  {
    id: "multiway", lcm: "LCM-08", title: "Multiway-структура и порядок действий", shortTitle: "Sandwich и closing action", description: "Защита делится между несколькими ranges; игрок сзади меняет цену call/raise.", prerequisites: ["ancestry"], admission: "ADMITTED", scope: "Directional multiway framework; exact MDF and frequencies are not claimed.", plainGoal: "Не играть three-way как heads-up и не нести весь MDF одной рукой/позицией.", tableCue: "Кто сзади? Кто закрывает? Чей board?", technicalTerm: "Sandwich pressure, shared defence, closing action и multiway ownership.", theory: ["Игрок между bettor и uncapped range защищается осторожнее.", "Closing player получает больше информации и не боится wake-up behind.", "Preflop initiative не гарантирует nut advantage на low connected boards."], heuristics: ["Не неси весь MDF один.", "Игрок сзади — отдельный gate.", "Ownership до инициативы."], decisionTree: ["Определи action order.", "Кто uncapped сзади?", "Кто закрывает action?", "Какие ranges владеют nuts/strong draws?", "Только затем call/raise/fold."], workedExample: { situation: "HJ open, BTN call, BB call. K-9-7 two-tone. HJ bet, Hero BTN KQ, BB сзади.", steps: ["Hero не закрывает action.", "BB может иметь sets/two pair/strong draws/check-raises.", "Defence shared между BTN и BB."], answer: "Не переносить heads-up MDF; сначала sandwich gate и BB continuing range." }, counterexample: "Когда Hero closing player после bet+call, unseen wake-up range отсутствует и defence может расшириться.", lab: { type: "compare", title: "Sandwich vs closing", description: "Одинаковая hand получает разную свободу из-за action order.", leftTitle: "Sandwiched", leftText: "Uncapped range сзади; call/raise дороже.", rightTitle: "Closing", rightText: "Никто не проснётся; больше информации и шире defence." }, explainBackPrompt: "Объясни, почему BTN с KQ не обязан защищать как heads-up, когда BB остаётся сзади.", tableCard: ["Players", "Action order", "Range behind", "Shared defence", "Nut ownership"], glossary: [{ term: "Sandwich", meaning: "Hero действует между aggressor и ещё не ответившим range." }, { term: "Shared defence", meaning: "Необходимая защита распределяется между несколькими игроками/ranges." }],
    drills: [
      d({ id: "mul-01", moduleId: "multiway", nodeKey: "sandwich-kq", variantGroup: "sandwich-closing", kind: "core", targetSeconds: 35, assumptions: ["HJ bet", "Hero BTN KQ", "BB behind"], cue: "Three-way K-9-7tt: HJ bet, Hero BTN KQ, BB сзади.", question: "Главный gate?", correctAction: "Учесть uncapped continuing range BB", wrongActions: [["Нести весь heads-up MDF", "MC-072"], ["Raise для protection из-за draw board", "MC-041"]], correctReason: "Defence shared, а player behind может wake up сильной range", wrongReasons: [["Top pair обязана defend против любой size", "MC-073"], ["Wet board автоматически требует raise", "MC-041"]], explanation: "Sandwich pressure меняет thresholds." }),
      d({ id: "mul-02", moduleId: "multiway", nodeKey: "closing-kq", variantGroup: "sandwich-closing", kind: "changed", targetSeconds: 30, assumptions: ["Hero closing", "bet+call before"], cue: "Та же hand, но Hero действует последним после bet+call.", question: "Что меняется?", correctAction: "Defence может расшириться как closing player", wrongActions: [["Ничего: hand strength одинаковая", "MC-074"], ["Нужно fold чаще из-за двух ranges", "MC-075"]], correctReason: "Нет unseen range behind и есть информация из prior call", wrongReasons: [["Closing action гарантирует call", "MC-031"], ["Количество игроков полностью определяет fold", "MC-075"]], explanation: "Action order — часть node, но не отменяет ranges и price." }),
      d({ id: "mul-03", moduleId: "multiway", nodeKey: "akt-hj", variantGroup: "ownership", kind: "changed", targetSeconds: 35, assumptions: ["HJ open", "SB/BB call", "AKTr"], cue: "HJ open, SB/BB call; flop A-K-T rainbow.", question: "Стартовый ownership prior?", correctAction: "HJ имеет высокую premium/nut density", wrongActions: [["BB всегда владеет connected boards", "MC-076"], ["Все ranges равны multiway", "MC-077"]], correctReason: "Tight opener сохраняет больше QJ, premiums и AK", wrongReasons: [["Initiative всегда даёт nuts", "MC-078"], ["Blind calls никогда не имеют broadways", "MC-079"]], explanation: "Здесь ownership следует из source ranges, а не только initiative." }),
      d({ id: "mul-04", moduleId: "multiway", nodeKey: "low-board-bb", variantGroup: "ownership", kind: "boundary", targetSeconds: 35, assumptions: ["CO open", "BTN call", "BB defend", "763r"], cue: "CO/BTN/BB на 7-6-3 rainbow.", question: "Что до CO range-bet?", correctAction: "Проверить low-board ownership BB", wrongActions: [["Range-bet из-за initiative", "MC-078"], ["Check всегда, потому что multiway", "MC-080"]], correctReason: "BB имеет больше low cards, two pair, sets и straight coverage", wrongReasons: [["Preflop raiser всегда имеет range advantage", "MC-078"], ["Multiway запрещает small bets", "MC-080"]], explanation: "Board family перераспределяет nut/coverage advantage." }),
      d({ id: "mul-05", moduleId: "multiway", nodeKey: "observed-sb-overcall", variantGroup: "field-update", kind: "changed", targetSeconds: 30, assumptions: ["repeated observed wide SB overcalls"], cue: "Live SB повторно показывает QJo и suited broadways в overcall.", question: "Как обновить audit?", correctAction: "Сохранить observed combos в ownership model", wrongActions: [["Игнорировать, потому что theory range уже задан", "MC-036"], ["Считать SB uncapped на всех boards", "MC-035"]], correctReason: "Repeated branch evidence корректирует prior, но не отменяет action order", wrongReasons: [["Любое observation полностью заменяет theory", "MC-035"], ["Theory никогда не меняется", "MC-036"]], explanation: "Field evidence применяется локально к подтверждённой branch." }),
    ], flashcards: [c("mul-card-sand", "multiway", "heuristic", "Первый вопрос в sandwich?", "Какой uncapped range остаётся сзади?"), c("mul-card-mdf", "multiway", "boundary", "Надо ли Hero нести весь heads-up MDF?", "Нет; defence shared между несколькими ranges."), c("mul-card-own", "multiway", "procedure", "Что идёт до initiative?", "Source-range и board ownership audit." )],
  },
  {
    id: "river", lcm: "LCM-09", title: "River-аудит value и bluffs", shortTitle: "Сначала supply, потом blocker", description: "Решение строится из дошедших combos, size exclusions и evidence.", prerequisites: ["multiway"], admission: "ADMITTED", scope: "Directional bluff-catch audit; exact bluff frequencies remain field/solver gated.", plainGoal: "Не call/fold по красоте blocker или размеру ставки без подсчёта реальных value и air.", tableCue: "Value → bluffs → size → blocker → evidence.", technicalTerm: "River ancestry, size-specific exclusions и blocker interaction.", theory: ["Blocker полезен только внутри реального value/bluff comparison.", "Некоторые bluff families невозможны из-за preflop/earlier actions.", "Extreme size может исключать medium value, но это не доказывает достаточно bluffs."], heuristics: ["Назови value combos.", "Назови естественную air, дошедшую по линии.", "Проверь, не удаляет ли blocker сами bluffs."], decisionTree: ["Trace source и actions.", "Посчитай value survivors.", "Посчитай bluff survivors.", "Примени size-specific exclusions.", "Оцени blocker и evidence; если supply не обоснован — baseline fold/unknown."], workedExample: { situation: "Nut-flush blocker против jam после flop bet-call и turn overbet-call; population data нет.", steps: ["Линия сильно фильтрует range.", "Нужно назвать air, которая пережила оба calls.", "Blocker может удалять missed flush draws — потенциальные bluffs."], answer: "Blocker не достаточен; допустим baseline fold/unknown при необоснованном bluff supply." }, counterexample: "Если extreme size исключает medium value и есть подтверждённые blocker-bluff families, call может улучшиться — но только после ancestry audit.", lab: { type: "compare", title: "Хороший и плохой blocker", description: "Один blocker уменьшает value, другой одновременно убивает bluffs.", leftTitle: "Полезный", leftText: "Удаляет value и почти не трогает bluff supply.", rightTitle: "Вредный", rightText: "Удаляет missed draws, которые должны были bluff." }, explainBackPrompt: "Объясни, почему nut blocker иногда делает call хуже и почему size не заменяет bluff count.", tableCard: ["Value arrivals", "Bluff arrivals", "Size exclusions", "Blocker removes?", "Evidence/baseline"], glossary: [{ term: "Bluff supply", meaning: "Количество и семейства естественной air, дошедшей до river." }, { term: "Size exclusion", meaning: "Value hands, которые обычно выбрали бы другой размер." }],
    drills: [
      d({ id: "riv-01", moduleId: "river", nodeKey: "before-blocker", variantGroup: "river-audit", kind: "core", targetSeconds: 35, assumptions: ["river bluff-catch"], cue: "Hero видит привлекательный blocker против river bet.", question: "Что идёт первым?", correctAction: "Посчитать credible value и bluff ancestry", wrongActions: [["Оценить только blocker", "MC-044"], ["Сравнить абсолютную силу pair", "MC-081"]], correctReason: "Blocker меняет существующее сравнение, но не создаёт bluffs", wrongReasons: [["Nut blocker всегда делает лучший call", "MC-046"], ["One pair никогда не call huge bet", "MC-082"]], explanation: "Ancestry и supply предшествуют hand-class slogans." }),
      d({ id: "riv-02", moduleId: "river", nodeKey: "impossible-bluff", variantGroup: "river-audit", kind: "boundary", targetSeconds: 30, assumptions: ["low suited connector absent preflop"], cue: "Предлагаемый bluff требует low suited connector, которого не было в preflop 3-bet range.", question: "Как учитывать?", correctAction: "Исключить невозможную bluff family", wrongActions: [["Оставить, потому что river карта подходит", "MC-083"], ["Добавить половину combos для balance", "MC-084"]], correctReason: "Board appearance не отменяет source range", wrongReasons: [["Solver всегда найдёт нужные bluffs", "MC-084"], ["Любая missed draw может появиться postflop", "MC-083"]], explanation: "Combo должен существовать на каждом предыдущем узле." }),
      d({ id: "riv-03", moduleId: "river", nodeKey: "extreme-size", variantGroup: "size-exclusion", kind: "changed", targetSeconds: 35, assumptions: ["extreme river re-raise"], cue: "Villain использует extreme size, medium value обычно ставит меньше.", question: "Что проверить?", correctAction: "Какие value hands size исключает и какие bluffs остаются", wrongActions: [["Fold все one-pair hands", "MC-082"], ["Call чаще только потому, что size polar", "MC-085"]], correctReason: "Size сужает represented value, но call зависит от surviving air", wrongReasons: [["Polar size автоматически balanced", "MC-085"], ["Большая ставка никогда не содержит medium value", "MC-086"]], explanation: "Exclusion — input, не готовый verdict." }),
      d({ id: "riv-04", moduleId: "river", nodeKey: "blocker-removes-bluffs", variantGroup: "blocker-quality", kind: "changed", targetSeconds: 35, assumptions: ["nut blocker removes missed draws"], cue: "Hero nut blocker одновременно удаляет многие missed draws.", question: "Как это влияет?", correctAction: "Blocker может ухудшить call", wrongActions: [["Всегда улучшает call", "MC-046"], ["Не влияет, потому что value важнее", "MC-087"]], correctReason: "Он уменьшает bluff supply сильнее, чем value", wrongReasons: [["Nut blocker имеет фиксированную положительную ценность", "MC-046"], ["Blockers влияют только на value", "MC-087"]], explanation: "Нужно сравнить removal с обеих сторон." }),
      d({ id: "riv-05", moduleId: "river", nodeKey: "no-air-baseline", variantGroup: "river-audit", kind: "boundary", targetSeconds: 35, assumptions: ["heavily filtered value line", "no population evidence"], cue: "Линия сильно value-heavy, естественную air назвать не удаётся.", question: "Допустимый advanced response?", correctAction: "Fold или UNKNOWN/baseline до evidence", wrongActions: [["Call ради теоретического balance", "MC-088"], ["Invent bluffs из всех missed hands", "MC-083"]], correctReason: "Без credible supply нельзя обосновать нужную bluff frequency", wrongReasons: [["Pool обязан быть balanced", "MC-088"], ["Любая missed hand может bluff", "MC-083"]], explanation: "Неопределённость — корректная граница знания." }),
    ], flashcards: [c("riv-card-order", "river", "procedure", "Порядок river audit?", "Value → bluffs → size → blocker → evidence."), c("riv-card-bad", "river", "boundary", "Когда nut blocker плох?", "Когда он удаляет больше bluff supply, чем value."), c("riv-card-unknown", "river", "heuristic", "Что делать без обоснованной air?", "Baseline fold или UNKNOWN; не придумывать balance." )],
  },
  {
    id: "evidence", lcm: "LCM-10", title: "Evidence по сопернику и полю", shortTitle: "Read должен быть branch-specific", description: "Наблюдение становится exploit только после повторения, привязки к узлу и falsifier.", prerequisites: ["river"], admission: "ADMITTED", scope: "Evidence discipline; population magnitudes remain field-gated.", plainGoal: "Не превращать один showdown в универсальный ярлык игрока.", tableCue: "Action, size, node, sample, falsifier.", technicalTerm: "Branch-specific opponent model, evidence grade и falsifier.", theory: ["Один результат подтверждает существование hand, но не frequency.", "Read должен сохранять position, action, size и later-branch consequences.", "При отсутствии sample structural baseline остаётся default."], heuristics: ["Один showdown — note, не rule.", "Exploit хранится по branch.", "Назови, что опровергнет read."], decisionTree: ["Что именно наблюдалось?", "В каком node и size?", "Повторялось ли?", "Как это меняет arrival range?", "Какой falsifier вернёт baseline?"], workedExample: { situation: "Villain часто calls small flop too wide и folds turns after missing.", steps: ["Leak относится к small-flop-call branch.", "После call turn range шире нормы, но still filtered.", "Exploit — selected turn pressure, а не global 'weak player'."], answer: "Сохранить branch-specific hypothesis и проверять turn folds." }, counterexample: "Один успешный river bluff не доказывает, что flop overbet branch overbluffed.", lab: { type: "compare", title: "Note и evidence", description: "Памятный showdown — начало наблюдения, не готовый exploit.", leftTitle: "Слабый read", leftText: "Один результат, глобальный ярлык, нет falsifier.", rightTitle: "Рабочий read", rightText: "Повтор, конкретный node/size, consequence и falsifier." }, explainBackPrompt: "Объясни, что один showdown доказывает и чего не доказывает.", tableCard: ["Observed action", "Node/size", "Sample", "Consequence", "Falsifier"], glossary: [{ term: "Falsifier", meaning: "Наблюдение, после которого hypothesis надо ослабить или отменить." }, { term: "Structural baseline", meaning: "Разумный default до надёжного exploit evidence." }],
    drills: [
      d({ id: "evi-01", moduleId: "evidence", nodeKey: "one-river-bluff", variantGroup: "sample", kind: "core", targetSeconds: 25, assumptions: ["one successful bluff"], cue: "Villain показал один успешный river bluff после необычной flop line.", question: "Что это доказывает?", correctAction: "Только существование этой hand/line; branch остаётся unconfirmed", wrongActions: [["Villain overbluffs эту branch", "MC-035"], ["Наблюдение бесполезно", "MC-036"]], correctReason: "Один result не определяет frequency и construction", wrongReasons: [["Любой showdown раскрывает range", "MC-035"], ["Sample нужен только для online stats", "MC-089"]], explanation: "Сохраняем exact note и ждём повтор/related evidence." }),
      d({ id: "evi-02", moduleId: "evidence", nodeKey: "wide-call-turn-fold", variantGroup: "branch-read", kind: "changed", targetSeconds: 30, assumptions: ["repeated small-flop overcall", "turn overfold"], cue: "Villain повторно calls small flop too wide и folds turn.", question: "Как хранить exploit?", correctAction: "Как action-specific small-call → turn-fold leak", wrongActions: [["Как глобальный ярлык calling station", "MC-069"], ["Как доказательство любого turn bluff", "MC-047"]], correctReason: "Read должен сохранять node и later filter consequence", wrongReasons: [["Player type одинаков на всех branches", "MC-069"], ["Повторный leak разрешает bluff any two", "MC-090"]], explanation: "Exploit остаётся selective и falsifiable." }),
      d({ id: "evi-03", moduleId: "evidence", nodeKey: "no-sample", variantGroup: "baseline", kind: "boundary", targetSeconds: 25, assumptions: ["familiar population belief", "no current sample"], cue: "Population belief знаком, но в текущей игре sample нет.", question: "Default?", correctAction: "Structural baseline + пометка evidence missing", wrongActions: [["Применить population rule с высокой уверенностью", "MC-091"], ["Игнорировать любые priors", "MC-092"]], correctReason: "Prior направляет внимание, но не доказывает magnitude в этой branch", wrongReasons: [["Population tendency универсальна", "MC-091"], ["Без sample невозможно принять ни одного решения", "MC-092"]], explanation: "Baseline и uncertainty могут сосуществовать." }),
      d({ id: "evi-04", moduleId: "evidence", nodeKey: "size-specific", variantGroup: "branch-read", kind: "changed", targetSeconds: 30, assumptions: ["overfold one size", "normal another size"], cue: "Villain overfolds к одному size, но нормально защищает другой.", question: "Как записать?", correctAction: "Привязать read к size и node", wrongActions: [["Считать Villain global overfolder", "MC-069"], ["Усреднить обе branches", "MC-093"]], correctReason: "Тенденция может быть реальна только в конкретной decision branch", wrongReasons: [["Player type важнее size", "MC-069"], ["Средняя frequency достаточна", "MC-093"]], explanation: "Branch split сохраняет полезность и не overgeneralizes." }),
      d({ id: "evi-05", moduleId: "evidence", nodeKey: "memorable-showdown", variantGroup: "sample", kind: "boundary", targetSeconds: 25, assumptions: ["memorable showdown"], cue: "Хочется изменить range после яркого showdown.", question: "Что спросить?", correctAction: "Повторялось ли и меняет ли это конкретное решение?", wrongActions: [["Насколько необычной была hand", "MC-094"], ["Выиграл ли Villain pot", "MC-095"]], correctReason: "Evidence ценно через stability и actionability, не эмоциональную яркость", wrongReasons: [["Редкая hand важнее sample", "MC-094"], ["Результат pot подтверждает strategy", "MC-095"]], explanation: "Result-oriented learning отделяется от branch evidence." }),
    ], flashcards: [c("evi-card-one", "evidence", "boundary", "Что доказывает один showdown?", "Что hand/line существует; не её frequency."), c("evi-card-store", "evidence", "procedure", "Как хранить read?", "Action + size + node + sample + falsifier."), c("evi-card-base", "evidence", "heuristic", "Что делать без sample?", "Structural baseline и честная отметка uncertainty." )],
  },
  {
    id: "transfer", lcm: "LCM-11", title: "Перенос, удержание и repair", shortTitle: "Понял ≠ удержал", description: "Навык считается сильным только после changed node, delay и реальной руки.", prerequisites: ["evidence"], admission: "ADMITTED", scope: "Learning governance; this module explains runtime evidence gates rather than adding a new poker chart.", plainGoal: "Различать свежую память, настоящий transfer и field validation.", tableCue: "Changed node → delay → field review.", technicalTerm: "Variant transfer, delayed retrieval, field transfer и repair family.", theory: ["Правильный ответ сразу после feedback может быть cueing.", "Transfer сохраняет механизм при изменении cards, positions, depth или action order.", "Field note становится evidence только после review reasoning."], heuristics: ["Похожее, но не то же самое.", "Позже, а не сразу.", "Реальная hand — только после review."], decisionTree: ["Классифицируй miss.", "Дай ближайший contrast.", "Проверь changed node.", "Верни item после delay.", "Проверь field note и только затем validate."], workedExample: { situation: "Learner исправил geometry item сразу после explanation.", steps: ["Immediate success показывает, что correction услышан.", "Changed stack/straddle node проверяет transfer.", "Следующий день проверяет retention."], answer: "Статус WORKING возможен; RETAINED ещё не доказан." }, counterexample: "Один correct answer не должен globally reset or certify весь module.", lab: { type: "compare", title: "Три уровня evidence", description: "Один механизм проверяется на возрастающей дистанции.", leftTitle: "Immediate", leftText: "Понял correction прямо сейчас.", rightTitle: "Transfer + delay", rightText: "Сохранил механизм при изменении и через время." }, explainBackPrompt: "Объясни разницу между correct answer, variant transfer, retention и field validation.", tableCard: ["Classify miss", "Contrast", "Changed node", "Delay", "Field review"], glossary: [{ term: "Variant distance", meaning: "Насколько новый item изменяет стратегически важные переменные." }, { term: "Repair family", meaning: "Связанный набор ошибок, который чинится одним механизмом." }],
    drills: [
      d({ id: "tra-01", moduleId: "transfer", nodeKey: "changed-node", variantGroup: "transfer-proof", kind: "core", targetSeconds: 25, assumptions: ["same mechanism, changed straddle/player behind"], cue: "Знакомый pattern появляется со straddle и player behind.", question: "Что доказывает transfer?", correctAction: "Перестроить changed node и сохранить механизм", wrongActions: [["Повторить memorized answer", "MC-096"], ["Считать все изменения новым skill", "MC-097"]], correctReason: "Transfer сохраняет causal rule при изменении relevant variables", wrongReasons: [["Одинаковые карты означают одинаковое решение", "MC-096"], ["Любое изменение отменяет прошлое обучение", "MC-097"]], explanation: "Node signature определяет, что должно сохраниться и что пересчитаться." }),
      d({ id: "tra-02", moduleId: "transfer", nodeKey: "immediate-correct", variantGroup: "retention-proof", kind: "boundary", targetSeconds: 20, assumptions: ["correct immediately after feedback"], cue: "Ответ правильный сразу после feedback.", question: "Какого evidence не хватает?", correctAction: "Delayed changed-node retrieval", wrongActions: [["Никакого: skill mastered", "MC-098"], ["Только большей confidence", "MC-099"]], correctReason: "Immediate cueing не доказывает retention", wrongReasons: [["Correctness автоматически означает long-term memory", "MC-098"], ["Confidence заменяет delay", "MC-099"]], explanation: "Time и variant distance — отдельные gates." }),
      d({ id: "tra-03", moduleId: "transfer", nodeKey: "field-note-review", variantGroup: "field-proof", kind: "changed", targetSeconds: 25, assumptions: ["raw field note"], cue: "Сохранена реальная hand: cue, action, reason.", question: "Что до field-transfer evidence?", correctAction: "Review reasoning против механизма", wrongActions: [["Сам факт записи hand", "MC-100"], ["Результат pot", "MC-095"]], correctReason: "Raw note фиксирует событие, но не валидирует causal model", wrongReasons: [["Любое применение в игре доказано", "MC-100"], ["Выигрыш подтверждает reasoning", "MC-095"]], explanation: "Field review может дать valid, repair или insufficient verdict." }),
      d({ id: "tra-04", moduleId: "transfer", nodeKey: "repair-pass", variantGroup: "repair-proof", kind: "changed", targetSeconds: 25, assumptions: ["one repair drill passed"], cue: "После structural miss learner прошёл один repair item.", question: "Интерпретация?", correctAction: "Локальное WORKING evidence, не mastery", wrongActions: [["Полный module RETAINED", "MC-098"], ["Ошибка полностью исчезла", "MC-101"]], correctReason: "Нужны diverse variants и delay", wrongReasons: [["Один contrast закрывает misconception навсегда", "MC-101"], ["Correct repair важнее всех прошлых ошибок", "MC-102"]], explanation: "Repair изменяет posterior локально, но не стирает историю." }),
      d({ id: "tra-05", moduleId: "transfer", nodeKey: "two-repairs", variantGroup: "routing", kind: "boundary", targetSeconds: 25, assumptions: ["several weak mechanisms"], cue: "После diagnostic несколько leaks конкурируют за время.", question: "Как сохранить эффективность?", correctAction: "Выбрать максимум две highest-priority repair families", wrongActions: [["Переучить весь курс", "MC-103"], ["Работать только над самым лёгким", "MC-104"]], correctReason: "Ограниченный repair сохраняет cognitive load и EV priority", wrongReasons: [["Больше тем всегда ускоряет обучение", "MC-103"], ["Лёгкие wins важнее transfer value", "MC-104"]], explanation: "Priority сочетает error evidence, live EV и learnability." }),
    ], flashcards: [c("tra-card-levels", "transfer", "procedure", "Четыре уровня после ответа?", "Correct → variant transfer → retention → field validation."), c("tra-card-delay", "transfer", "boundary", "Почему immediate correct не mastery?", "Он может быть следствием свежей подсказки."), c("tra-card-field", "transfer", "heuristic", "Когда field note становится evidence?", "После review cue-before-action и reasoning." )],
  },
];

export const moduleById = Object.fromEntries(modules.map((module) => [module.id, module])) as Record<ModuleId, ModuleContent>;
export const allDrills = modules.flatMap((module) => module.drills);
export const drillById = Object.fromEntries(allDrills.map((drill) => [drill.id, drill])) as Record<string, Drill>;
export const allCards = modules.flatMap((module) => module.flashcards);
